### ISSUE TITLE
Local Development Setup and Operation Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1003]
Re: [Local Development Setup and Operation](https://pantheon.io/docs/articles/local)
## Issue Description:
Reported in #998 - doc does not effectively guide users to creating a local environment for Pantheon sites. 
## Suggested Resolution 
Test doc thoroughly. Review related [power user thread](https://groups.google.com/a/pantheon.io/forum/#!topic/power-users/TjfZ-hkt8J4) 

The doc should be refactored so that it is easily followed. Sections where no content/context is provided should be avoided, like [Get the Code](https://pantheon.io/docs/articles/local/#get-the-code) where the only info is a link to another doc. This doc should be an all-in-one stop for successfully setting up local environments. 

Also large sites/teams should perhaps be encouraged to use multidev in place of local dev?

**Comment by nataliejeremy** [comment]
@rachelwhitton @bmackinney This was designed to be a landing page, with links to comprehensive documentation. I think sections with links to other docs work well so that content is contained within one doc, and linked to elsewhere (reducing redundancy). +1 on improving it to make sure it covers/links to all necessary info.

**Comment by rachelwhitton** [comment]
@nataliejeremy - I agree we should avoid duplicate content in the docs, but for simple tasks I don't think they should have to load another doc and lose their place. More complex/comprehensive tasks should be linked like you said. 

If I'm remembering correctly, this landing page originated as a doc, and we adapted it during our sprint for breadcrumbs. I don't think this doc should be a landing page for the local directory, there's a specific goal communicated in this article that is not parent to all contents of the local dir. 

#421 exists to evaluate landing pages - we should have a milestone and sprint towards refining the purpose of these landing pages. 

In the meantime, my suggestion is to refactor this doc to align it's purpose with the way our audience is utilizing the resource - and not according to the intent of design.

**Comment by nataliejeremy** [comment]
The purpose of a landing page (especially for our use) is to link to related content. It sounds like this doc needs to be refactored to be a landing page (similar to /users, /sites, and a new doc about Local Development Setup and Operation should be created. Leaving it up to @bmackinney

**Comment by rachelwhitton** [comment]
Sounds good to me @nataliejeremy, +1 for a new landing page and a new doc in the local dir about setting up a local dev environment. Can we define what's expected within this specific issue? Do we want to take on making a new landing page here? Or at a later date in another issue?

**Comment by greg-1-anderson** [comment]
See pantheon-systems/drops-8#84
