### ISSUE TITLE
When cache clear, site status WF fails

### ISSUE THREAD

**Issue by sukottokun** [pantheon-systems/documentation#1008]
Drupal, WP Cache Clear and Update Site Status (launch check) fails cause several tickets per week and are almost always code-related. We need a doc about how a user can resolve issues when they fail. It's often a redirect issue, $base_url, and a few other reasons we can quickly glean from tickets.

**Comment by nataliejeremy** [comment]
Update  the following docs:
https://pantheon.io/docs/wordpress-launch-check/
https://pantheon.io/docs/drupal-launch-check/

**Comment by nataliejeremy** [comment]
@sukottokun Can you add desk ticket numbers or specific error messages to this issue? I'm searching desk and can't find anything.
