### ISSUE TITLE
November Changelog Candidates

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1010]
Add October platform improvements, or Drupal/WordPress/Pantheon-related media as comments, that we should list in the November newsletter.

**Comment by bmackinney** [comment]
Drupal 8 RC-1 (MVP)

**Comment by ari-gold** [comment]
Terminus commands changing as we near Terminus (cli) 1.0 release:
https://github.com/pantheon-systems/cli/issues/291

**Comment by ari-gold** [comment]
Not merged, but one to keep an eye on, that probably deserves to be highlighted: 

Fixed drush sql-connect and sites aliases --print #607 
https://github.com/pantheon-systems/cli/pull/607

**Comment by ari-gold** [comment]
https://github.com/pantheon-systems/titan-mt/pull/13819

**Comment by ari-gold** [comment]
Edge Cache upgraded to Varnish 4

**Comment by bmackinney** [comment]
media: https://pantheon.io/blog/terminus-architecture-pantheon-cli

**Comment by nataliejeremy** [comment]
@ari-gold Can you add some detail on the edge cache upgrade, like how it impacts users? Thanks.
