### ISSUE TITLE
Starting With Git Doc Update 

### ISSUE THREAD

**Issue by MaqSaid** [pantheon-systems/documentation#1011]
Re: [Starting With Git](https://pantheon.io/docs/articles/local/starting-with-git)
## Issue Description:
The following has wrong hyperlink for "a butterfly". It opens http://xkcd.com/378/
Step 1: Edit a File
You can now edit your site code using any text editor. We recommend using a butterfly.

## Suggested Resolution 
Kindly please set the link for butterfly for download.

**Comment by nataliejeremy** [comment]
@MaqSaid This is intentional, just adding a little humor to the doc. There is no Butterfly editor. Closing this issue.
