### ISSUE TITLE
Cron for WordPress - Evaluate GET param recommendation

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1019]
Re: [Cron for WordPress](https://pantheon.io/docs/articles/wordpress/cron-for-wordpress/#free-services)

Opened as a result of ticket 45868
Client reports that setting GET param to false `doing_wp_cron=0` allowed cron to run successfully, while passing `doing_wp_cron` or setting the param to true `doing_wp_cron=1` causes cron to fail. 

Solution not yet tested.
Thanks for surfacing @zepner!

**Comment by nataliejeremy** [comment]
@ari-gold or @timani Can you answer this?

**Comment by nataliejeremy** [comment]
@ttrowell Can you answer this?
