### ISSUE TITLE
Unsupported/Problematic Modules and Plugins Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1020]
Re: [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins)

## Issue Description:
Views Data Export should link to d.o issue/patch

## Suggested Resolution 

link to https://www.drupal.org/node/1782038

**Comment by ari-gold** [comment]
@timani @ttrowell  Can you confirm this is should happen?

**Comment by ttrowell** [comment]
So, yes, users can definitely try the patch, but we still don't guarantee that the use of the /tmp dir will always be successful in all cases.  Basically, the disclaimer at the bottom of that page still applies.
