### ISSUE TITLE
Landing Page Layout

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1027]
## Issue Description:
Landing pages should have their own layout, similar to articles but without TOC. 
Landing pages should also list child articles. If we can do this without adding content types for every section of the site, that would be ideal, but if not, it's fairly simple to add them. 

List of pages: 

- /sites
 - (sites sub-articles?)
- /users
- /organizations
- /drupal
- /wordpress
- /local
 
## Suggested Resolution 
Create layout, test and gather feedback.

**Comment by bmackinney** [comment]
Part of #421

**Comment by bmackinney** [comment]
@rachelwhitton I edited the description
