### ISSUE TITLE
Local Development Setup and Operation Doc Update 

### ISSUE THREAD

**Issue by pablodelarosa** [pantheon-systems/documentation#1029]
Re: [Local Development Setup and Operation](https://pantheon.io/docs/articles/local)
## Issue Description:

terminus site clear-caches --site=<site> --env=<env>

## Suggested Resolution 

terminus site clear-cache --site=<site> --env=<env>

**Comment by rachelwhitton** [comment]
Thanks for the issue @pablodelarosa! Corrected in #998
