### ISSUE TITLE
configurations by plan

### ISSUE THREAD

**Issue by sukottokun** [pantheon-systems/documentation#1030]
Explains
- [ ] how much ram, vars, and other config that would make developers know what they are working with at each plan, with descriptions of what each "thing" is.
- [ ] how developers can get this info from the application.
- [ ] why backups and db don't factor into the ram being used.
- [ ] The difference between Dev/Test and Live, starting at the Business service level.

**Comment by nataliejeremy** [comment]
@timani @newtoid Do you know where I can find this info?

**Comment by nataliejeremy** [comment]
https://github.com/pantheon-systems/titan-mt/blob/master/pantheon/service_levels.py

**Comment by nataliejeremy** [comment]
@sukottokun Is this the type of information you want per plan? 
![screen shot 2015-11-03 at 1 44 06 pm](https://cloud.githubusercontent.com/assets/9138609/10922647/1c5d3f20-8231-11e5-8e24-27dbf11bfb64.png)

**Comment by joshkoenig** [comment]
Let's talk about why and how we are presenting this information.
