### ISSUE TITLE
Cron for Drupal Doc Update 

### ISSUE THREAD

**Issue by jlicht** [pantheon-systems/documentation#1034]
Re: [Cron for Drupal](https://pantheon.io/docs/articles/drupal/cron)
## Issue Description:

Under "Pantheon Cron Execution", the documentation says:

>Note
>
>Setting the value to "Never" will be ignored; cron will always run at least hourly.

Under "Troubleshooting Cron" the documentation says:

>Can I prevent Drupal Cron from running?
>
>Yes, from within Drupal at admin/system/config/cron, select Never from the "Run cron every" drop-down menu, then save the configuration. 

## Suggested Resolution 

Figure out which statement is correct, and fix the other one

**Comment by nataliejeremy** [comment]
Thanks for reporting this issue @jlicht We'll work on it and update it soon.

**Comment by nataliejeremy** [comment]
@ari-gold or @timani Can you verify which one is correct?

**Comment by nataliejeremy** [comment]
@newtoid Can you tell me which statement is correct?

**Comment by newtoid** [comment]
@nataliejeremy they are both correct to a degree, our system will run cron at around the top of the hour for any sites that are not reaped, but if cron is disabled at the application level it is possible that related tasks wont run. I am looking at a test site with elysia installed at the moment and will report back.
