### ISSUE TITLE
Pantheon for Agencies Doc Update 

### ISSUE THREAD

**Issue by BenSR1** [pantheon-systems/documentation#1035]
Re: [Pantheon for Agencies](https://pantheon.io/docs/articles/organizations/pantheon-for-agencies)
## Issue Description:
Agencies can ONLY add new Team Members on a site dashboard, they cannot add someone as a developer, or admin. This is only allowed at the level of Agency Dashboard.

## Suggested Resolution 

Make that page more in line with images on this: https://pantheon.io/docs/articles/sites/team-management/

**Comment by bmackinney** [comment]
@BenSR1 The images are from the organization creation process. The person creating the org has the option to add people to the org in those roles. 
Unless the process at https://dashboard.pantheon.io/organizations/create has changed, we'll want to just close the issue. 

I wouldn't mind deleting the images, but they are accurate for this procedure.

**Comment by rachelwhitton** [comment]
The [Pantheon for Agencies](https://pantheon.io/docs/articles/organizations/pantheon-for-agencies) doc is used as an unofficial landing page, not sure if covering the creation process is the most valuable focal point for an existing org admin or team member. 

IMO we should consider moving the procedural instructions for the [creation process](https://dashboard.pantheon.io/organizations/create) to a new doc, and then refactor/improve remaining content (maybe use the new layout planned in #1027). 

At the very least we should include a statement similar to the following, found in the [Change Management](https://pantheon.io/docs/articles/organizations/change-management/#managing-people-in-an-organization) doc:
>Administrators of the Organization assign roles at the Organization Dashboard's People tab.

ping @nataliejeremy @bmackinney 

@BenSR1 thanks for opening this issue! Much appreciated
