### ISSUE TITLE
services.yml documentation needs to be reworked.

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#1039]
The advice I provided on the global services.yml file was not accurate; the purpose of this file is different than I supposed, and this difference has a profound impact on how this file should be managed.  @rachel.jaro pointed out that sites/*/services.yml is in our .gitignore file (inherited from Drupal 8's example.gitignore file), and @ari-gold provided the Drupal issue that explains this:

https://www.drupal.org/node/2251113

I had not read this background information previously, so I did not realize that the purpose of this file is to store environment-specific settings, such as twig debug mode. These settings should *not* be committed to the git repository, and should *not* migrate from one environment to another when pushing code.

The [services.yml documentation](https://pantheon.io/docs/articles/drupal/8/create-services-yml-file/) should be rewritten to advise users to manage this file in SFTP mode, and to use features of their SFTP client to make it unmodifiable once they are done.  It should remain in the .gitignore file, so that it is not deployed to other environments.  The existing reference to module-specific services.yml files should be maintained.

**Comment by ari** [comment]
I provided no such link. Please stop spamming me with your tasks.

**Comment by greg-1-anderson** [comment]
Sorry @ari; I meant to tag @ari-gold, who uses @ari in slack.  Won't happen again--at least not by me!

**Comment by greg-1-anderson** [comment]
Sorry @ari; I meant to tag @ari-gold, who uses @ari in slack. Won't happen again--at least not by me!

**Comment by rachelwhitton** [comment]
Thanks for the issue @greg-1-anderson - I'll get this worked ASAP. 

Is the link you provided above correct? Content seems unrelated to `services.yml`: [Change the search link in the site nav to a search text field](https://www.drupal.org/node/225)

**Comment by greg-1-anderson** [comment]
Sorry, URL lost some characters on the end.  I put the correct link -- https://www.drupal.org/node/2251113 -- into the original description above.
