### ISSUE TITLE
Moving Drupal 8 Sites Out of Testing Doc Update 

### ISSUE THREAD

**Issue by spuky** [pantheon-systems/documentation#1042]
Re: [Moving Drupal 8 Sites Out of Testing](https://pantheon.io/docs/articles/drupal/8/moving-out-of-testing)
## Issue Description:

for me the create backups and reimport did not work as expected... 
tried to import a drush ard archive of a local site (with no files in the files dir for lower filesize of the archive)  which did not workout either because the importer discovered 2 files dirs: /vendors and /sites/default/config 

did a new install of the site
- moved in my code modules and theme via SFTP
- synced the DB of my local environment
- moved in Files via SFTP

## Suggested Resolution

> provide a Fallbackstrategy that maybe reads like this:

If importing backups fails it might help to just start the site as a New D8 site

>1. Walk trough the Drupal web installer 
>2. Copy your Code via SFTP mode
>3. Import your DB either via the Pantheon Web interface or via mysql command line
> >  drush sql-dump ../mydb.sql
> >  mysql -u pantheon -pXXXXXXXXXXXXXXX -h dbserver.dev.XXXXXX-XXX-XXX-XXX-XXX.drush.in -P XXXXX pantheon < ../mydb.sql
>
>  (correct string from Connection Info: Database command line)
>4. Copy your Files via SFTP to the files directory

your site should be up after this.

**Comment by spuky** [comment]
After writing the Issue i reread the Documentation site maybe it would be sufficient to just make the create new "Drupal 8 Site" part more obvious since my Problem was trying the Importers on the Platform...

**Comment by rachelwhitton** [comment]
Thanks for the issue @spuky! 

+1 for adding a note/content to [Moving Drupal 8 Sites Out of Testing](https://pantheon.io/docs/articles/drupal/8/moving-out-of-testing) that explicitly states Drupal 8 archives cannot be imported through the Dashboard import tools, and instead should be migrated to a newly created D8 site manually. 

@nataliejeremy and @bmackinney, thoughts?

**Comment by nataliejeremy** [comment]
+1 @rachelwhitton
