### ISSUE TITLE
New Doc Proposal: testing future WordPress

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1060]
## Outline

1. Clone site repo
2. Add remote to https://github.com/wordpress/wordpress`
3. Checkout -b update branch  `git checkout -b update`
4. Pull the branch to test and rebase `git pull upstream master` (or `git pull upstream 4.4`
5. Push to site `git push origin master`
6. Create multidev env with terminus `terminus site create-env --site=<> --to-env=update`
7. Update WordPress db `terminus wp "core update-db" --site=<> --env=update`

## Expected Audience
WordPress developers and product companies

## Path
 `source/docs/articles/wordpress/running-trunk-or-betas`

**Comment by nataliejeremy** [comment]
@bmackinney what repo do you want me to clone to write this doc?

**Comment by bmackinney** [comment]
Yes. I added more specific instructions to the outline. Ping me if you run into issues.

**Comment by nataliejeremy** [comment]
@bmackinney Ran step 4 and got this: 
![screen shot 2016-01-19 at 1 24 23 pm](https://cloud.githubusercontent.com/assets/9138609/12432420/06514c38-beb0-11e5-976c-c6cacf302924.png)

**Comment by bmackinney** [comment]
Now is a good time to write this doc. https://wordpress.org/news/2016/02/wordpress-4-5-beta-1/
