### ISSUE TITLE
How WP caches are cleared at the edge

### ISSUE THREAD

**Issue by sukottokun** [pantheon-systems/documentation#1061]
WP cache clears differently than drupal, and it affects how we rate limit cache clears at the edge. We should edit the existing doc, [WordPress Pantheon Cache Plugin Configuration](https://pantheon.io/docs/articles/wordpress/wordpress-pantheon-cache-plugin-configuration/) so CSE and users understand this and provide workarounds for cases like: https://pantheon-systems.desk.com/agent/case/46771 Nick says Sara can assist.

Todo: 

- [ ]  Using the info present in #1123 create a PR to the existing doc
- [ ]  Test 0 seconds settings, note from Ari below
 - Test using curl, as explained in [Testing varnish with curl](https://pantheon.io/docs/articles/sites/varnish/testing-varnish/#test-varnish-with-curl)

Note from Ari:
Have you tested 0 seconds? I don't think that works currently. I think current behavior is wonky, allowing minimum of 60 seconds, and if you try to set it to less than 60 seconds it will set it the TTL to 600 seconds. See current version https://github.com/pantheon-systems/WordPress/blob/6b1eefb5269a266cca3db8ceb6372899e844a41c/wp-content/mu-plugins/pantheon/pantheon-cache.php#L204

Work being done on release-4.4 branch that will change this behavior: pantheon-systems/WordPress#34

**Comment by rachelwhitton** [comment]
This will be implemented as an edit to the existing doc, and not as a new doc. Using info from Erik's PR, recreate the content on the existing doc and create a new PR. Close Eriks pr.
