### ISSUE TITLE
New Doc: Shibboleth SSO for WordPress 

### ISSUE THREAD

**Issue by wesmanning** [pantheon-systems/documentation#1062]
## Title

SSO Instructions for WordPress
## Description

Shibboleth SSO documentation for WordPress
## Path

(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by bmackinney** [comment]
SAML plugin in development.

**Comment by bmackinney** [comment]
I'm not sure why I marked as "blocked". @wesmanning @hengkit can you provide more detail about what you want in this doc?

**Comment by rachelwhitton** [comment]
Dupe #1883
