### ISSUE TITLE
Known Limitations Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#1064]
Re: [Known Limitations](https://pantheon.io/docs/articles/sites/known-limitations)
## Issue Description:
I have a case wherein someone asked me about renaming issues using SFTP. While we do have the section "Moving directories", it is not clear this is for SFTP too and for files too.

Also, search results such as "SFTP rename" doesn't result to this page so it is not easily picked up.

## Suggested Resolution 
Create a new section or edit the "Moving directories" to also include specifics about SFTP file renaming or renaming in general. But I would encourage to use SFTP mode since this feature would likely be used in SFTP.

**Comment by primerg** [comment]
And I forgot to mention that maybe adding the following reasons would help:

_Our SFTP mode doesn’t support the `mv` command, which is what most apps do when they try to “rename"_

**Comment by nataliejeremy** [comment]
@primerg Thanks for creating this issue. Are you going to submit a PR for this?

**Comment by primerg** [comment]
@nataliejeremy created the PR
