### ISSUE TITLE
New Doc Proposal: How to Roll Back the Live Environment

### ISSUE THREAD

**Issue by tadhgpearson** [pantheon-systems/documentation#1067]
## Title

How to rollback the live environment
## Description

I've just deployed my code in the live environment, and it doesn't work as expected, there's a critical bug. I want to fallback to the previous version now. How is that done?
## Outline
- How to rollback
- Considerations and consequences
## Expected Audience

Developers
## Path

(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by nataliejeremy** [comment]
Repurpose some of the content from: https://pantheon.io/docs/undo-commits/

**Comment by rachelwhitton** [comment]
Thanks for the issue @tadhgpearson! Apologies for the delayed response, but we recently revised some content in PR #1391 to better document restoring environments. Seems like we may have hit on your request here: https://pantheon.io/docs/restore-environment-backup/#restore-code We also have an existing doc that covers [hot fixes](https://pantheon.io/docs/hot-fixes/). Do you have any suggestions for missing content now that we've added content for restoring code? Thanks in advance!

**Comment by tadhgpearson** [comment]
That's an improvement Rachel... but that's not entirely what I had in mind. What I was really thinking is, if you make the push to live and the code doesn't work, how can you fall back the live environment code without rolling back the dev version and then pushing from dev -> test -> live. I literally just want to undo the "Push code to live"

A typical example would be that the HTTPS config is always different in test from live... it's possible to push a code change to the site that completely breaks the live environment but doesn't show up in dev or test. How do you roll that back quickly?

**Comment by rachelwhitton** [comment]
Thanks for the clarification! Sounds like you're referring to a [hot fix](https://pantheon.io/docs/hot-fixes/). 
> Pushing a hotfix via Git is the only way to push code directly to Live without having to go through Dev and Test.

**Comment by tadhgpearson** [comment]
I'm not sure that this is a hotfix.. It's more like an undo of my last load on the live environment.

**Comment by wakin** [comment]
Hi @tadhgpearson 

I found this solution from Drupal.org
[https://www.drupal.org/node/2135803]

I hope this helps :-)

**Comment by jenlampton** [comment]
It might be useful to look at how Acquia handles this, as they have fantastic tooling for rolling back changes in production. The Acquia dashboard provides a select list for the live environment that lets you select a previous tag, so a roll-back takes less than a minute.

**Comment by alexfornuto** [comment]
@jenlampton thanks for the additional insight! We've discussed this issue internally, and @rachelwhitton is adding your comments to the discussion. 

[Restoring an Environment from a Backup](https://pantheon.io/docs/restore-environment-backup/) and [Hotfixes](https://pantheon.io/docs/hotfixes/) covers all possibilities for reverting the Live environment directly at this time.

REF: FEAT-225
