### ISSUE TITLE
Local Development Setup and Operation Doc Update 

### ISSUE THREAD

**Issue by pablodelarosa** [pantheon-systems/documentation#1088]
Re: [Local Development Setup and Operation](https://pantheon.io/docs/articles/local)
## Issue Description:

The documentation `terminus site backups get --element=database --site=<site> --env=<env> --to-directory=$HOME/Desktop/ --latest` contains a parameter error.

## Suggested Resolution 

` --to-directory=$HOME/Desktop/` should read `--to=$HOME/Desktop/` or preferably something like ` --to=<local directory>`.

**Comment by rachelwhitton** [comment]
+1 for `--to=<local directory>`

Thanks for the issue @pablodelarosa! Much appreciated

**Comment by nataliejeremy** [comment]
Thanks for the update @pablodelarosa 
Closing as I updated on Master:
https://github.com/pantheon-systems/documentation/commit/83fefe7b4e51705842a9228bad5f05337a078b53
