### ISSUE TITLE
Anchors do not work when pasted 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1096]
[`https://pantheon.io/docs/articles/sites/domains/#why-does-my-domain-have-an-extra-"www."?`](https://pantheon.io/docs/articles/sites/domains/#why-does-my-domain-have-an-extra-"www."?) when pasted into slack or other applications (desk) break anchors and become: [`https://pantheon.io/docs/articles/sites/domains/#why-does-my-domain-have-an-extra-%22www.%22`](https://pantheon.io/docs/articles/sites/domains/#why-does-my-domain-have-an-extra-%22www.%22)

Options: 
 - 1. Debug "permalink" generated in sculpin and try to rewrite special characters like `?`
 - 2. Standardize on not using `?` in anchors (meaning all FAQs in the TOC would read as statements instead of questions - not ideal IMO)

@bmackinney please validate/prioritize bug

Reported by @ccorpus

**Comment by bmackinney** [comment]
Likely the option can be set with the hashgenerator option documented here: http://gregfranko.com/jquery.tocify.js/#Options
