### ISSUE TITLE
Using PHPMyAdmin to Locally Administer a Database Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1127]
Re: [Using PHPMyAdmin to Locally Administer a Database](https://pantheon.io/docs/articles/local/using-phpmyadmin-to-locally-administer-a-database)

1. Link within the **Download PHPMyAdmin** section leads to tangental Pantheon doc: [Accessing MySQL Databases](https://pantheon.io/docs/articles/local/accessing-mysql-databases/), but the preceding statement suggests it will lead to the GitHub repository for PHPMyAdmin or documentation for the recommended installation method:

 > The recommended way to get a copy of PHPMyAdmin is to download it via GitHub. For instructions, see [Accessing MySQL database](https://pantheon.io/docs/articles/local/accessing-mysql-databases/).

 **Suggested Resolution**: Revise last sentence content, and link new text to PHPMyAdmin docs http://docs.phpmyadmin.net/ 

2. Missing Pantheon specific installation instructions. Where do users unpack the zip archive downloaded from GitHub? [PHPMyAdmin docs](http://docs.phpmyadmin.net/en/latest/setup.html#quick-install) say: 

 > Untar or unzip the distribution (be sure to unzip the subdirectories): `tar -xzvf phpMyAdmin_x.x.x-all-languages.tar.gz` in your webserver’s document root. If you don’t have direct access to your document root, put the files in a directory on your local machine, and, after step 4, transfer the directory on your web server using, for example, ftp.

 **Suggested Resolution**: Test installation, document any instructions that are not aligned with PHPMyAdmin Quickinstall doc, review with CSE. Test it yourself.

PHPMyAdmin is a commonly used and familiar tool for WP developers, the **entire doc** should be revised so it's painfully obvious how to download and install this tool on a local machine and ultimately leave the user with an easily established connection to any one of their remote environment databases.

**Comment by bmackinney** [comment]
closed by #1127
