### ISSUE TITLE
New Doc Proposal: Content Delivery Networks and Your Pantheon Site

### ISSUE THREAD

**Issue by ajbarry** [pantheon-systems/documentation#1128]
There are a few vendor and Drupal specific documentation available on the subject of Content Delivery Networks for assets and large files, but the use-cases for fronting your entire Pantheon site with a CDN is not covered and there are a few good scenarios:
1. Inexpensive SSL
2. Global Edge Caching
3. others ...

This often requires the use of CDN specific plugins for your CMS of choice so it would be good to guide users on setting up their sites in this manner. Perhaps this can be wrapped into an introduction and index to the vendor/cms specific docs.

---

Extend scope of [existing cdn doc](https://pantheon.io/docs/articles/drupal/content-delivery-network-cdn-for-file-distribution/)

**Comment by alexfornuto** [comment]
Closing, in favor of existing doc: https://pantheon.io/docs/free-https/
