### ISSUE TITLE
WordPress Pantheon Cache Plugin Configuration Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1132]
Re: [WordPress Pantheon Cache Plugin Configuration](https://pantheon.io/docs/articles/wordpress/wordpress-pantheon-cache-plugin-configuration)
## Issue Description:
Warn against setting Cache time to 0 in live environment
## Suggested Resolution 
Include additional info from @erik-pantheon's related draft doc (#1123):
>  For no page caching, set this to 0. This is not recommended for Live environments! Pantheon's Varnish servers obey the page TTL header. If it's set to 0, it will not cache the page. 

The plugin information in his draft will be replaced with a link to this existing doc, so we should preserve it here.

**Comment by nataliejeremy** [comment]
Closing as this is taken care of in PR #1135.
