### ISSUE TITLE
Redirect Incoming Requests Doc Update 

### ISSUE THREAD

**Issue by messageagency** [pantheon-systems/documentation#1133]
Re: [Redirect Incoming Requests](https://pantheon.io/docs/articles/sites/code/redirect-incoming-requests)
## Issue Description:
This doc suggests implementing redirects in a way that will interfere with drush invocations.
For example:
```
if (isset($_SERVER['PANTHEON_ENVIRONMENT']) &&
  $_SERVER['HTTPS'] === 'ON') {
  if (!isset($_SERVER['HTTP_X_SSL']) ||
    (isset($_SERVER['HTTP_X_SSL']) && $_SERVER['HTTP_X_SSL'] != 'ON')) {
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://www.yoursite.com'. $_SERVER['REQUEST_URI']);
    exit();
  }
}
```
Since drush never sends an HTTPS or HTTP_X_SSL header, all drush commands get killed early by this clause.

## Suggested Resolution 
Documented preferred way to identify and isolate drush operations.
I'm using this approach in my settings files:
```
$is_drush = !empty($_SERVER['DRUSH_PHP']) || (!empty($_SERVER['SCRIPT_FILENAME']) && strpos($_SERVER['SCRIPT_FILENAME'], 'drush'));
if (!$is_drush) {
  // do all the redirect stuff here
}
```

**Comment by bmackinney** [comment]
@messageagency are you referring to all of the code snippets in the doc? Can you edit the description by adding details? Are you seeing issues with all drush commands? Are you using Terminus or drush aliases?
@greg-1-anderson do you see anything in the referenced document that would interfere with Drush?

**Comment by messageagency** [comment]
Description updated with an example.
I'm using drush aliases, not sure whether this applies through terminus or not

**Comment by greg-1-anderson** [comment]
All of these redirection examples need:
```
  && (php_sapi_name() != "cli")
```

**Comment by aaronbauman** [comment]
Thanks Greg, that's much cleaner than what I've been doing.
