### ISSUE TITLE
Drupal 8 on Pantheon Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1152]
Re: [Drupal 8 on Pantheon](https://pantheon.io/docs/articles/drupal/8)
## Issue Description:
Out of date

## Suggested Resolution 
Drupal 8 is out - this should probably be updated with more current information.

**Comment by nataliejeremy** [comment]
@tinefin Can you clarify what needs to be updated? We do state Drupal 8 is available, so I'm confused on what needs to change. Please elaborate. Thanks!

**Comment by rachelwhitton** [comment]
I recently committed a change on master to fix what @tinefin reported originally, see 14fde93

Closing the issue
