### ISSUE TITLE
Miscellaneous Doc Audit - Landing Page Lists

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1154]
Re: [All Articles](https://pantheon.io/docs/articles) & [Sites](https://pantheon.io/docs/articles/sites/)
## Issue Description:
Audit to move docs listed in the “miscellaneous” sections to appropriate subdirectories. “miscellaneous” shouldn’t really be a thing, its a temporary solution to help handle the lists.
## Suggested Resolution 
Move all docs in the parent level directory of docs (source/docs/articles/....) into appropriate directories. If none exists, strategize and create one. Same goes for the sites directory, no docs should be present in (source/docs/articles/sites/...) outside of the subdirectory landing pages (e.g. source/docs/articles/sites/code.md). 

Allow the issue to be triaged/prioritized before starting.

**Comment by rachelwhitton** [comment]
Remove "draft" type articles in this audit as well - those make the lists generate blank spots:
![screen shot 2015-12-04 at 10 05 57 am](https://cloud.githubusercontent.com/assets/10119525/11594272/afaee508-9a6e-11e5-939b-9e88465157d6.png)

**Comment by nataliejeremy** [comment]
+1!
