### ISSUE TITLE
Official statement required for Drupal 6 EOL

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#1176]
Drupal 6 goes end of life support on 24 Feb 2016 and Pantheon should have an official statement regarding ongoing maintenance on Drupal 6 sites.

**Comment by ari-gold** [comment]
https://www.drupal.org/drupal-6-eol

**Comment by nataliejeremy** [comment]
@bmackinney Are we going to remove d6 content from the docs? Any plan for this?

**Comment by nataliejeremy** [comment]
@bmackinney @slashzero  I think this would make a good FAQ here: https://pantheon.io/docs/articles/frequently-asked-questions/
 However, we state that we do support 6. Is that changing?

**Comment by bmackinney** [comment]
That's not a question I can answer. @ari-gold or someone in Product can to define.

**Comment by nataliejeremy** [comment]
@ari-gold Can you provide some input here?
