### ISSUE TITLE
Guide Proposal - Get Git and Fix Those Conflicts!

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#1182]
## Title  
Get Git and Fix Those Conflicts!

## Description
Take user through Installing Git and doing a conflict resolution.

## Outline
BYB: - latest version of git + terminal.
Pulling repo locally
 - SSH key references here so they do that
 - `cd` to repo docroot
Pulling in the upstream
 - describe git pull
 - highlight the possible use of -x (theirs, ours) flags
Git adding and committing the files that fix the conflict
Push back to Pantheon

## Expected Audience
WordPress users who do not use Git

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)
not sure

@bmackinney Your review requested, sir.

**Comment by rachelwhitton** [comment]
+1! Definitely in favor of this, and a guide seems like a great fit for the content. We can link to it from our manual import docs.

**Comment by bmackinney** [comment]
@ttrowell I suspect this issue will go away, since the source of most conflicts was deleting and updating the WordPress twenty-year themes and the Akismet plugin. We're not updating them in the upstream any longer, so there should not be any more conflicts...

**Comment by bmackinney** [comment]
I'm going to close this. Feel free to re-open if our current docs and the change with WordPress upstream updates does not reduce pain.
