### ISSUE TITLE
All About Application Containers Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#1198]
Re: [All About Application Containers](https://pantheon.io/docs/articles/sites/all-about-application-containers)
## Issue Description:
This question gets asked frequently: "Can upload_max_filesize and post_max_size be increased?". 
## Suggested Resolution 
I'd like to suggest an FAQ section to this doc and include an answer to the aforementioned question. Thanks!

**Comment by nataliejeremy** [comment]
@ccorpus In this doc it says the maximum upload_max_filesize and post_max_size is 100MB. Has that changed? Can you tell me the instructions for how the user can change them? Thanks!

**Comment by nataliejeremy** [comment]
@ccorpus Did some digging and found this in desk: 
Unfortunately, the PHP upload_max_filesize limit can not be changed. A possible solution for you might be to use a CDN, Amazon S3 CORS or something like that. Please take a look at the following to see if it might work for you:

https://pantheon.io/docs/articles/drupal/content-delivery-network-cdn-for-file-distribution/
https://www.drupal.org/project/amazons3_cors

Is it still accurate?

**Comment by ccorpus** [comment]
@nataliejeremy I see it in the doc "Maximum upload_max_filesize and post_max_size is 100MB". But customers are asking if this can be increased. Perhaps we can update to say: ""Maximum upload_max_filesize and post_max_size is 100MB (this cannot be increased)". I'm not familiar enough to know whether or not it can be increased. Can you confirm? Thanks!
