### ISSUE TITLE
Recommend blogvault for all WordPress imports

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1200]
Pending more testing. 
Create new: 
- [ ] /sites/migrate/bv-pantheon-plugin
 - [ ] Outline here

add links from: 
- [ ] https://pantheon.io/docs/articles/sites/migrate/export-an-existing-wordpress-site/
- [ ] /sites/migrate
- [ ] /sites/migrate/manual

**Comment by stevector** [comment]
@ataylorme Have you been testing Blogvault recently?

**Comment by ataylorme** [comment]
@stevector I have been testing BlogVault migrations for WordPress. Specifically the [Pantheon Migration Plugin](https://wordpress.org/plugins/bv-pantheon-migration/).

I ran into a few minor things which I'm discussing with Drew and the BlogVault developer but overall the migrations went well.

The first issue was a plugin using `session_start()`, which I resolved by adding the [Pantheon PHP Sessions Plugin](https://wordpress.org/plugins/wp-native-php-sessions/). 

I don't think it's a blocker but adding a link to [the existing doc on PHP Sessions](https://pantheon.io/docs/articles/wordpress/wordpress-and-php-sessions/) as a footnote might be a good idea.

BlogVault takes the Pantheon `wp-config.php` and copies over constants for the source site, including `WP_SITEURL` and `WP_HOME`.

For sites with those defined they then became defined twice. Hoping the BlogVault dev can exclude those from the constants that are copied over.

**Comment by ataylorme** [comment]
> BlogVault takes the Pantheon `wp-config.php` and copies over constants for the source site, including `WP_SITEURL` and `WP_HOME`.

> For sites with those defined they then became defined twice. Hoping the BlogVault dev can exclude those from the constants that are copied over.

BlogVault is going to rollout an update tomorrow that will exclude  `WP_SITEURL` and `WP_HOME` when copying over constants.

We are still working on testing so I would say hold on recommending BlogVault for all migrations. I will post more updates as we continue to test.

**Comment by bmackinney** [comment]
@ataylorme have there been more tests?

**Comment by ataylorme** [comment]
@bmackinney Not yet - I had a pretty full week in the SFO office this week.

We are coordinating some more tests in the next few tests.

We are also exploring using machine tokens.

**Comment by rachelwhitton** [comment]
BlogVault pushed a fix to automatically install the [WordPress Native PHP Sessions](https://wordpress.org/plugins/wp-native-php-sessions/) plugin during the migration process, we should note that. 
cc @nataliejeremy
