### ISSUE TITLE
New Doc Proposal: Using replica Databases with Drupal

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1201]
# Using replica Databases with Drupal

Drupal version of new hyperdb article. 
## Outline
- Requirements 
  - Enterprise
  - Settings.php
  - Module?
- Setup
- Testing
## Expected Audience

Enterprise Clients with drupal sites
## Path: `source/docs/articles/drupal/using-replica-databases/`

**Comment by ari-gold** [comment]
https://gist.github.com/ari-gold/ce7fbd2a4c67f39d3be9

**Comment by rachelwhitton** [comment]
https://www.drupal.org/project/autoslave

**Comment by alexfornuto** [comment]
Per conversations with @rachelwhitton and @ttrowell I'm going to close this as no longer required/requested.
