### ISSUE TITLE
Document using the pre_option filter to set env-specific config in WordPress

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/documentation#1215]
WordPress has a nice little filter mechanism to allow you to override any common config value (aka `wp_options` entry) in code:

https://codex.wordpress.org/Plugin_API/Filter_Reference/pre_option_(option_name)

Unlike with Drupal, it requires WP to be bootstrapped since it's a function-filter. However we can/should provide some best practice recommendations here.

According to @ryanduff this is common practice:

> you can do a single file just in `wp-content/mu-plugins/plugin-name.php`

We should include an example of how to do this:

https://gist.github.com/joshkoenig/e7b51b39dfbd53c1f3ef

**Comment by bmackinney** [comment]
@joshkoenig the codex page indicates this filter is used in themes for specific pages where you'd not want to change the option site-wide. I think [update_option](https://codex.wordpress.org/Function_Reference/update_option) may work better in an mu-plugin. Thoughts?

**Comment by ryanduff** [comment]
@bmackinney It's not theme specific. You can use it to override any value on the fly. 

When WordPress loads, it pulls all the auto-load options from the database. Each one is run through a variable name filter allowing you to override it at that point. 

Using `update_option` would trigger a db write to change the value. I don't think that was the outcome @joshkoenig was looking for initially.

**Comment by joshkoenig** [comment]
Correct. This method is the equivalent of variable overriding in Drupal.
