### ISSUE TITLE
Restoring an Environment from a Backup Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1218]
Re: [Restoring an Environment from a Backup](https://pantheon.io/docs/articles/sites/backups/restoring-an-environment-from-a-backup)
## Issue Description:
There is no documentation about Live backups reflecting code changes that should only be appearing in Dev. This is expected behavior. 

See [Sprintly card 1085](https://sprint.ly/product/27143/item/1085).

## Suggested Resolution 
Add this information to this existing doc.

**Comment by nataliejeremy** [comment]
@timani or @ari-gold Do you have any info to add on why code that wasn't deployed to Live is showing up in the Live backup?

**Comment by ari-gold** [comment]
@nataliejeremy I haven't run into this before, so maybe @timani or someone else in @cse knows more, but I'm guessing it has to do with the fact that Dev, Test, and Live are all on the `master` branch, but on different tags. Maybe you can create a site to experiment on? Try using  `git tags` and see if you can checkout a specific tag locally to get what you expect. https://git-scm.com/book/en/v2/Git-Basics-Tagging#Checking-out-Tags

**Comment by sukottokun** [comment]
Yes, we need to document that a code backup is the entire repo, all tags, and this is probably unexpected. Then we should explain how to restore or do whatever they are trying to do, by creating a branch off the tag or whatever is recommended: "So let's say you want to spin up a local version of your test's code base, you would 1.) create a branch of the test_# tag, 2.) etc, 3.)etc." Does that sound reasonable to all?
