### ISSUE TITLE
New Doc Proposal:  What Goes In A Pantheon Wordpress Git Repo

### ISSUE THREAD

**Issue by bthompson-mindgrub** [pantheon-systems/documentation#1270]
We've had a number of outside contractors/new developers working on sites with us over the past month or two who have had trouble with getting their head around the way Pantheon sets up the git repos for Wordpress sites.  Most of them are following the guidelines found here:  https://deliciousbrains.com/storing-wordpress-in-git/ where the git repo only holds the custom WP theme at the root of the repository.

Clearly, this does not work on Pantheon but I find myself repeating the same thing over and over again about how developers need to put the entire Wordpress repo in the Pantheon git repository.  It would be great if there was a doc outlining how a Wordpress (and Drupal) git repo on Pantheon is structured so I have a reference to send to folks.

**Comment by rachelwhitton** [comment]
+1 Thanks for the suggestion @bthompson-mindgrub! This would be a great addition

**Comment by bmackinney** [comment]
@nataliejeremy I think the very beginning of https://pantheon.io/docs/articles/sites/code/ is the place to explain this. If you agree, change from new article to doc update. 

For triage, I'm thinking 
- [ ] Change title from "Pantheon Dashboard Code Tool" to "Pantheon Site Code" or "Code running on Pantheon"
- [ ] Explain what @bthompson-mindgrub says in the second paragraph ^
- [ ] Add an image of your SFTP client at initial login to the server, showing `~/code` expanded.

@bthompson-mindgrub @rachelwhitton @nataliejeremy please add your thoughts.

**Comment by rachelwhitton** [comment]
@bmackinney I think [/docs/articles/sites/code](https://pantheon.io/docs/articles/sites/code/) is a good spot for it. We mention the directory structure in [Export an Existing WordPress Site](https://pantheon.io/docs/articles/sites/migrate/export-an-existing-wordpress-site/#manually-create-separate-site-archives) and [Export an Existing Drupal Site](https://pantheon.io/docs/articles/sites/migrate/export-an-existing-drupal-site/#manually-create-archive) - to avoid duplicating information I'd suggest replacing those directory listings with a link to the proposed new section. 

+1 for doc title change - not a huge preference but I think "Pantheon Site Code" works

**Comment by bthompson-mindgrub** [comment]
That looks like a good place for it to me.  What if we did something like "Your Site Code on Pantheon" or similar for the title?  "Pantheon Site Code" makes it sound like it is Pantheon's code (not my site's code).

@rachelwhitton I'm not sure combining sections from the export guides is the best idea.  If I'm someone who has never imported a site before, I really want to find just 1 doc that tells me what to do.  If I have to jump from doc to doc to doc I'll get frustrated and just go with <other hosting provider> who can present it to me in a more concise fashion.

**Comment by rachelwhitton** [comment]
Thanks @bthompson-mindgrub for the suggestions and insight! +1 for title "Your Site Code on Pantheon" and leaving the export docs as they are.

**Comment by nataliejeremy** [comment]
@bthompson-mindgrub Agreed. I'll leave that content where it is and add more information to the /Code doc. Changing title to: Your Site's Code on Pantheon
