### ISSUE TITLE
Creating and Revoking Machine Tokens Doc Update

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1275]
Re: [Creating and Revoking Machine Tokens](https://pantheon.io/docs/articles/local/cli/machine-tokens)
## Issue Description:
Doc does not explain cli token storage and auth/re-auth/multiple-user auth via token-email 
## Suggested Resolution 

Add information about the above to the "Authenticate with Terminus" section.

**Comment by nataliejeremy** [comment]
See info here https://drive.google.com/a/getpantheon.com/file/d/0ByoqIfy3p9UPWkdLa0IteVZ5bVU/view

[1:54] 
40:25
