### ISSUE TITLE
Add some examples of how to exclude certain pages from cache

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#1280]
This can be done for Drupal and Wordpress similar to the redirecting incoming requests

https://pantheon.io/docs/articles/sites/code/redirect-incoming-requests/#redirect-from-one-path-to-another

```
// wp-config.php or settings.php
if ($_SERVER['REQUEST_URI'] == '/cart') {
   header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
   header("Cache-Control: post-check=0, pre-check=0", false);
   header("Pragma: no-cache");
}
```

See case #51558 for an example.

**Comment by nataliejeremy** [comment]
We have an existing PR where this info should go: https://github.com/pantheon-systems/documentation/pull/1079/files

**Comment by nataliejeremy** [comment]
Closing as @erik-pantheon added this to: https://github.com/pantheon-systems/documentation/pull/1079/files#diff-d32bbb0321ab5fc01a3022629eb30d27R22
