### ISSUE TITLE
Add write-good linter

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1287]
The testing suite should check grammar
https://github.com/btford/write-good

**Comment by rachelwhitton** [comment]
@bmackinney here are [first pass results for articles](https://gist.github.com/rachelwhitton/f6f90ee6e1d590a861c6) - let me know if this is still something you would be interested in adding to the test suite.

**Comment by bmackinney** [comment]
@rachelwhitton Disable passive voice check and run again and gistify the results please.

**Comment by rachelwhitton** [comment]
@bmackinney [~2200 fewer errors if `--no-passive` option is used](https://gist.github.com/rachelwhitton/f6f90ee6e1d590a861c6#file-passive-false). Only run on articles dir, does not include changelog, guides, etc.
