### ISSUE TITLE
Redirect Incoming Requests Doc Update 

### ISSUE THREAD

**Issue by michaelpetri** [pantheon-systems/documentation#1289]
Re: [Redirect Incoming Requests](https://pantheon.io/docs/articles/sites/code/redirect-incoming-requests)
## Issue Description:
The provided code snippets doesn't check if the request comes from the cli. In our case we've got the problem that the cron wasn't executed because we redirect every non-https visitor to a https version-

## Suggested Resolution 
Check if the request comes from CLI by wrapping the following condition around the code snippets:
```
if (!(!isset($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' ||
   (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)))) {
   // ...
}
```

The condition was taken from [drupal_is_cli()](https://api.drupal.org/api/drupal/includes!bootstrap.inc/function/drupal_is_cli/7)

**Comment by bmackinney** [comment]
@michaelpetri we have a PR in progress: https://github.com/pantheon-systems/documentation/pull/1263/files Could you comment over there?
