### ISSUE TITLE
SAML/Okta doc update

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1308]
/docs/articles/organizations/saml-for-orgs-with-okta.md

The doc was unpublished until the config gets updated. 

ToDo
- Update config
- Remove "draft: true" from front matter

**Comment by nataliejeremy** [comment]
@ari-gold Has the config been updated yet?

**Comment by ari-gold** [comment]
Before a special config was necessary for Okta. Now I think the general SAML doc will give people using Okta what they need to set it up successfully.

**Comment by rachelwhitton** [comment]
+1 for deleting the Okta doc
