### ISSUE TITLE
March Changelog Candidates

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1318]

**Comment by nataliejeremy** [comment]
https://pantheon.io/blog/move-stack-cloud-integration-tools-drupal-and-wordpress-developers

**Comment by nataliejeremy** [comment]
We are no longer updating Akismet and other non-core WP. We are doing now only doing in-place WP core updates. Thanks for all of your thoughts and help.
https://github.com/pantheon-systems/WordPress/issues/53#issuecomment-182498657

**Comment by kibra** [comment]
Platform domains (i.e. dev-site.pantheon.io) are now created for all sites, even if the site is part of an org that has a custom domain.

Where as before a kalamuna site would start with:
dev-site.kalamuna.io

it now starts with *both*
dev-site.kalamuna.io
and
dev-site.pantheon.io

**Comment by rachelwhitton** [comment]
Code archives created using the Backups tool on Test and Live now checkout the most recent deployment tag automatically to reflect the state of code on the environment.

**Comment by nataliejeremy** [comment]
D6 EOL https://pantheon.io/blog/thank-you-drupal-6 and https://www.drupal.org/drupal-6-eol

**Comment by ari-gold** [comment]
Fixed issue:  Developer role should be able to delete Multidev
