### ISSUE TITLE
Considerations for Google Analytics and PANTHEON_STRIPPED Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1322]
Re: [Considerations for Google Analytics and PANTHEON_STRIPPED](https://pantheon.io/docs/articles/sites/varnish/pantheon_stripped-get-parameter-values)
## Issue Description:
- [x] Document possible edge cases where PANTHEON_STRIPPED is passed as a utm parameter 

## Suggested Resolution 
- [x] Include diagram to demonstrate Varnish handling a common Google Analytics scenario
- [x] Work with @davidstrauss to provide a code snippet that removes undesired utm parameters before URLs are integrated into a response by the site's framework.

**Comment by rachelwhitton** [comment]
@davidstrauss, thoughts?
```
// Remove query strings and tracking parameters from URLs
$strip = array('/&?__.+?(&|$)$/', '/&?utm_.+?(&|$)$/');
$_SERVER['REQUEST_URI'] = preg_replace( $strip, '', $_SERVER['REQUEST_URI'] );
```

**Comment by rachelwhitton** [comment]
@davidstrauss can you review the code snippet?

**Comment by davidstrauss** [comment]
This looks good! We should also document where to drop it (which would be `settings.php` for Drupal and elsewhere for WordPress).
