### ISSUE TITLE
Remove /articles from all docs paths

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1338]
- [x] decide whether moving guides and changelogs is necessary, if so check with marketing to claim the paths.
- [x] Move all files
- [x] ID filenames that need to change
- [x] update all internal links
- [ ] redirect /docs/articles/* to /docs/*
- [ ] update dashboard links

**Comment by bmackinney** [comment]
@informanddelight Do you still +1 this? 
@joshkoenig who in Product needs to sign off on this before we begin?

**Comment by joshkoenig** [comment]
+1 on simpler urls so long as redirects work. Old links can't break. Precious SEO juice must be retained.
