### ISSUE TITLE
Migrate to Pantheon: Manual Site Import Doc Update

### ISSUE THREAD

**Issue by ariwinokur** [pantheon-systems/documentation#1364]
Re: [Migrate to Pantheon: Manual Site Import](https://pantheon.io/docs/articles/sites/migrate/manual-site-import)
## Issue Description:

Step 6 produced these results:

`The authenticity of host '[codeserver.dev.bca1d788-7488-41c7-8251-3d314976fab0.drush.in]:2222 ([192.237.188.90]:2222)' can't be established.
RSA key fingerprint is SHA256:yPEkh1Amd9WFBSP5syXD5rhUByTjaKBxQnlb5CahZZE.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[codeserver.dev.bca1d788-7488-41c7-8251-3d314976fab0.drush.in]:2222,[192.237.188.90]:2222' (RSA) to the list of known hosts.
codeserver.dev.bca1d788-7488-4@codeserver.dev.bca1d788-7488-41c7-8251-3d314976fab0.drush.in's password:`

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Hey @ariwinokur thanks for creating this issue! I updated the doc in PR #1371 to cover authentication within step 6

`The authenticity of host....` is an SSH verification triggered when connecting to a host for the first time. The password prompt accepts your Pantheon Dashboard credentials, but SSH keys can be added within your user account on Pantheon as an alternative. 

Feel free to comment on the PR if you have any feedback. Thanks!
