### ISSUE TITLE
Single Sign-On for Pantheon Organizations and Machine Tokens Doc Updates

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1372]
Re: [Single Sign-On for Pantheon Organizations](https://pantheon.io/docs/articles/organizations/sso)
## Issue Description:
Users in SAML-enabled orgs must have only one session 
## Suggested Resolution 
Add troubleshooting section:
If you are a member of a SAML-enabled org, and the passsword field does not disappear, please log out of your active session, log back in, and try again.

**Comment by nataliejeremy** [comment]
@bmackinney I'm trying to replicate that issue by logging in on Chrome, then opening a new session on Safari and it works as it's supposed to. Can you provide more info and/or screenshot?

**Comment by nataliejeremy** [comment]
See sprintly issue: https://sprint.ly/product/27143/item/1186
