### ISSUE TITLE
Role-Based Permissions

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#1400]
Re: [Role-Based Permissions 

The following section is a little confusing: https://pantheon.io/docs/articles/organizations/change-management/#site-level-roles/permissions. 

At the site level, there is no "administrator" or "owner" role as available options to select when adding team members. Screen shot: https://www.evernote.com/l/ANFjTDstgAxG4bKjL6csx9BMC9k4xCJx1S4.

**Comment by rachelwhitton** [comment]
Thanks for the issue @ccorpus! Do you have a suggested resolution for this one? Based on your screentshot it looks like we just need to update "owner" to "user in charge"?

cc @nataliejeremy and @slivermon

**Comment by ccorpus** [comment]
@slivermon I leave the suggestion to you, sir. But updating "owner" to "user in charge", as @rachelwhitton suggested, sounds like a good idea.

**Comment by rachelwhitton** [comment]
https://sprint.ly/product/27143/item/1228
