### ISSUE TITLE
Unified Sandbox Domains

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1403]
Re: Base Domain Product Change - New Doc
## Title
Base Domains
## Issue Description
Document the addition of the `pantheonsite.io` domain to all Pantheon environments
## Suggested Resolution
- [x] Draft new doc within `sites/domains` to document the base domain provided for new sites
 - [x] Cover existing sites using legacy base domains (pantheon.io and gotpantheon.com)
- [x] Identify/Update existing content and code snippets where the `-pantheon.io` base domain is referenced, such as:
 - [Customizing Your Base Domain](https://pantheon.io/docs/articles/organizations/base-domains/)
 - [Enable HTTPS for Sites Using Customized Base Domains](https://pantheon.io/docs/articles/organizations/https-for-sites-using-customized-base-domains/)
 - [Load and Performance Testing](https://pantheon.io/docs/articles/load-and-performance-testing/#verify-varnish-is-working)

**Comment by rachelwhitton** [comment]
- [ ] Draft new doc within `sites/domains` to document the base domain provided for new sites
 - [ ] Cover existing sites using legacy base domains (pantheon.io and gotpantheon.com)
- [ ] Identify/Update existing content and code snippets where the `-pantheon.io` base domain is referenced, such as:
 - [Customizing Your Base Domain](https://pantheon.io/docs/articles/organizations/base-domains/)
 - [Enable HTTPS for Sites Using Customized Base Domains](https://pantheon.io/docs/articles/organizations/https-for-sites-using-customized-base-domains/)
 - [Load and Performance Testing](https://pantheon.io/docs/articles/load-and-performance-testing/#verify-varnish-is-working)
