### ISSUE TITLE
Explain Internal IPs in nginx access logs

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1407]
Re: [Parsing nginx Access Logs with GoAccess](https://pantheon.io/docs/articles/sites/logs/nginx-access-log/)
## Issue Description
Re: https://sprint.ly/product/27143/item/1218
Because of the way the request is routed through Varnish, it will be the styx IP, not the customers IP, that show up in then logs.

## Suggested Resolution
Add to nginx log docs where appropriate

**Comment by bmackinney** [comment]
lgtm

**Comment by ari-gold** [comment]
Styx = Routing Layer
Varnish = Edge Cache
