### ISSUE TITLE
Drupal 8 cache tags + Varnish

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1410]
Re: https://pantheon.io/docs/articles/drupal/drupal-performance-and-caching-settings

## Drupal 8 Cache tags

Drupal 8 can send cache tags to reverse proxies like Varnish through HTTP headers. See "Integration with reverse proxies" in https://www.drupal.org/developing/api/8/cache/tags These cache tags allow the reverse proxies to know all of the cache tags that make up a response (node 123, taxonomy term 456) so that if node 123 is resaved, all cached responses using node 123 can be cleared from the reverse proxy.

Our page on the general subject of Drupal and Varnish does not make it clear if we support this behavior or how to validate that it is working.

## Suggested Resolution

Confirm the behavior works and add details to the docs page.

**Comment by eeeschwartz** [comment]
Hello Pantheon! As a Drupal 8 user on Pantheon I just wanted to :+1: a desire for clarity around this topic. 

Enabling cache tags to clear Varnish on a per-page basis would be a complete game changer for many of us out there. From my light testing it's not working on [my site](https://next.lexingtonky.gov/) but perhaps I missed a config?

Thanks kindly for the great work.

**Comment by stevector** [comment]
Hi @eeeschwartz, You're correct that Varnish clearing through cache tags is not supported at this time. We're talking about it internally. We do want sensible programmatic cache clearing for both Drupal and WordPress. Here are some related threads: https://github.com/pantheon-systems/WordPress/issues/68 and https://github.com/pantheon-systems/documentation/pull/301

**Comment by eeeschwartz** [comment]
Thanks @stevector. No doubt you Pantheon folks are aware, but for the rest of us it sounds like Drupal 8 cache tags makes invalidating specific content a no-brainer. 

A good [writeup here](http://www.jeffgeerling.com/blog/2016/use-drupal-8-cache-tags-varnish-and-purge) of the respective Drupal and Varnish switches to flip.

I can't wait to set the max-age to a million years and do a bit of 🎉 at my super fast site!

**Comment by nataliejeremy** [comment]
@stevector To close out this issue, should we add that Varnish clearing through cache tags is not supported at this time?

**Comment by stevector** [comment]
@nataliejeremy Yes, and we can revise the docs once cache tags are supported.

**Comment by wimleers** [comment]
Exciting!

Also see https://www.drupal.org/developing/api/8/cache/tags/varnish.
