### ISSUE TITLE
Migrate to Pantheon: cPanel - New Doc Proposal

### ISSUE THREAD

**Issue by kellyimagined** [pantheon-systems/documentation#1441]
## Title
Workaround for GoDaddy Exports

## Description
GoDaddy seems to block the export of sites, and the module [Backup and Migrate](https://www.drupal.org/project/backup_migrate) does not work effective.

## Outline
Download entire Drupal Folder
Export Database
Create Local Site
Use [Drush ard](https://pantheon.io/docs/articles/sites/migrate/export-an-existing-drupal-site/) 
[Import to Pantheon](https://pantheon.io/docs/articles/sites/migrate/#import-your-site)

## Expected Audience
New to Pantheon

## Path
source/docs/articles/drupal

**Comment by rachelwhitton** [comment]
Hey @kellyimagined! [Export an Existing Drupal Site](https://pantheon.io/docs/drupal-export/) is an existing doc that seems to address this issue. Can you confirm? Thanks for your recent contributions, much appreciated!

**Comment by kellyimagined** [comment]
I think the issue was on GoDaddy's side. They don't allow a clean export. So the link you provided does cover, but a little more work is done when coming from GoDaddy. It might be better to just wait and see if others mention issues?

**Comment by rachelwhitton** [comment]
@kellyimagined Do you mind providing the extra steps you had to take?

**Comment by kellyimagined** [comment]
Yes, I will go through the steps again on my end and make sure to grab detailed steps.

**Comment by kellyimagined** [comment]
Login to CPanel
Click on Applications
Click My Applications
Select your site and create a backup
Go to File Manager (ROOT Directory)
Click on Applications Backup
Download Backup
Going back to Cpanel
Click on Database Manager
Export your database
Using MAMP or similar create a local site
Import database
Test site
Drush ard 
Import to Pantheon

**Comment by rachelwhitton** [comment]
Thanks @kellyimagined! 

@bmackinney what do you think about a new doc for migrating sites from a host using cPanel, where normal exporting methods are not supported (like drush ard or backup and migrate)? Title: **Migrate to Pantheon: cPanel** 

cc @nataliejeremy

**Comment by bmackinney** [comment]
Makes sense to me.
