### ISSUE TITLE
Migrate to Pantheon: Manual Site Import Doc Update 

### ISSUE THREAD

**Issue by w3wfr** [pantheon-systems/documentation#1443]
Re: [Migrate to Pantheon: Manual Site Import](https://pantheon.io/docs/articles/sites/migrate/manual-site-import)
## Issue Description:

Step 5 is not convenient on working local instance.

## Suggested Resolution 

Should add to `.gitignore`:

    sites/default/settings.php

Then do a `cp` instead of `mv`

**Comment by nataliejeremy** [comment]
Thanks for creating this issue @w3wfr We Created PR #1459 to update it.
