### ISSUE TITLE
Migrate to Pantheon: Manual Site Import Doc - bash script not working

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#1444]
Re: [Migrate to Pantheon: Manual Site Import](https://pantheon.io/docs/articles/sites/migrate/manual-site-import)
## Issue Description:
The following script does not upload files. It downloads files from Dev env to your local machine.

> 

```ENV='ENV'
SITE='SITEID'

read -sp "Your Pantheon Password: " PASSWORD
if [[ -z "$PASSWORD" ]]; then
echo "Woops, need password"
exit
fi

while [ 1 ]
do
sshpass -p "$PASSWORD" rsync --partial -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222'  $ENV.$SITE@appserver.$ENV.$SITE.drush.in:files/* --temp-dir=../tmp/  ./files/
if [ "$?" = "0" ] ; then
echo "rsync completed normally"
exit
else
echo "Rsync failure. Backing off and retrying..."
sleep 180
fi
done 
```
> This script connects to your Pantheon site's Dev environment and starts uploading your files. If an error occurs during transfer, rather than stopping, it waits 180 seconds and picks up where it left off.

https://pantheon-systems.desk.com/agent/case/57132

## Suggested Resolution 

Update script:

`sshpass -p "$PASSWORD" rsync --partial -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' ./files/* --temp-dir=../tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:files/`

Please refer to Rsync examples here -https://pantheon.io/docs/articles/local/rsync-and-sftp/#rsync

**Comment by rachelwhitton** [comment]
Thanks for the issue @rubelyn! This was corrected in #1447
