### ISSUE TITLE
New Doc Proposal: Creating Symbolic Links from code directories to files

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1446]
## Description
Sometimes plugins expect for the code directory to have write permissions. This works on Dev, but not in Test/Live. 

## Outline

1. change your dev environment code from SFTP to Git mode. If you do not have Git installed locally, you'll need to follow instructions here: https://pantheon.io/docs/articles/local/starting-with-git/

2. In your local terminal, cd to the site code repository, make a copy of the writeable directory, and delete it from the code repository. 

3. Create, commit, and push the symlink to Pantheon.
```
ln -s ./wp-content/uploads/new-directory ./wp-content/path/plugin-expects-to-write-to
git add .
```
At this point, run `git status` and you should see the symlink in green and all of the language files in red.

4. Commit your change and push to Pantheon

```
git commit -m "create symlink to writeable directory"
git push origin master
```

5. Your symlink will then exist on the Dev environment, and when the plugin creates the files, it should continue to work, even with the Dev environment in Git mode. In your previous configuration, the plugin would fail while in git mode. You should not see the newly created files in the dashboard, as "ready to commit."

6. Deploy your code changes to Test and test them there

7. Deploy your code changes to Live and create the files again there. (You can upload the files you preserved in step 2 to the Live environment's @`/wp-content/uploads/new-directory` directory via SFTP prior to deploying, if you do not want the Live environment to have to recreate them)

Here's a nice resource you can use for creating symbolic links on Mac/Linux. http://apple.stackexchange.com/questions/115646/how-can-i-create-a-symbolic-link-in-terminal

**Comment by rachelwhitton** [comment]
Can we update [Non-Standard File Locations](https://pantheon.io/docs/non-standard-file-paths/) instead of a new doc? Currently the context here is on importing sites, but we can add a few statements on plugins/modules assuming write access to the codebase. 

cc @bmackinney @nataliejeremy

**Comment by bmackinney** [comment]
No let's keep them separate. While the technique is similar, the goal is not. Consider re-titling, "Using code that expects to write to the live environment" or something that articulates the goal, not the means. The filename should change too.

**Comment by rachelwhitton** [comment]
I like that! Good plan @bmackinney +1

**Comment by nataliejeremy** [comment]
@bmackinney suggestion for the file name? changing the title to Using Extensions  that Expect Write Access (in my upcoming commit)
