### ISSUE TITLE
Composer Manager

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1449]
Re: <Doc title and/or link>
## Issue Description
Document composer manager 
Consider adding to [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins/)
## Suggested Resolution
- [x] decide if we need to re-work the installation instructions for Amazon S3 CORS, see [related drupal.org issue](https://www.drupal.org/node/2688553)
- [x] link to a doc on the proper use of Composer Manager - if we decide to go forward with it. @dustinleblanc is stumping that out now.

cc @ttrowell @allenfear

**Comment by dustinleblanc** [comment]
Hey @greg-1-anderson, in this case https://pantheon-systems.desk.com/agent/case/56255 you suggested to the customer to disable composer manager and to instead use composer directly. While I agree with that general practice (using composer directly), after reading more docs on composer manager, I wonder if we can deal with platform compatibility by simply advising clients to commit their deps in development and ensure the auto-generation of files is disabled in test/live per the docs here: https://www.drupal.org/node/2405805
excerpt for easy reading:
```
Production Environments

Dependencies should be managed in development environments and not in production.
Therefore it is recommended to disable the checkboxes that automatically build the composer.json file and run Composer commands when enabling or disabling modules on production environments.

Assuming that you can detect whether the site is in production mode via an environment variable, adding the following snippet to settings.php will disable the options where appropriate:

<?php
// Modify the logic according to your environment.
if (getenv('APP_ENV') == 'prod') {
  $conf['composer_manager_autobuild_file'] = 0;
  $conf['composer_manager_autobuild_packages'] = 0;
}
?>
```
We could test this out to make sure it works as expected on the platform. While using composer the way it was intended is my preference, I think this could help out for folks that use a module that depends on CM (as in the issue @ttrowell dealt with). What do you think?

**Comment by greg-1-anderson** [comment]
Yes, it's kind of a problem for us when a module says that it depends on Composer Manager.  If we ensure that `composer update` is never run on production, and users make sure that Composer Manager always builds on the dev machine (and the user then commits the result), then likely the result would work.

**Comment by dustinleblanc** [comment]
@rachelwhitton so I am still getting the error even with the snippet in place. I think we might need to flip the switch back to "completely unsupported, don't use it" Even with it set to not automatically regenerate the files, I am getting this error just cuz:
![image](https://cloud.githubusercontent.com/assets/3948808/13963402/94713f02-f03b-11e5-9885-3bb09efb5f06.png)

**Comment by greg-1-anderson** [comment]
Strange that Composer Manager insists on being able to create the DocRoot.

**Comment by dustinleblanc** [comment]
@greg-1-anderson I tracked it down to https://www.drupal.org/node/2567885#comment-10997567
