### ISSUE TITLE
Alternative to Amazon S3 CORS

### ISSUE THREAD

**Issue by kellyimagined** [pantheon-systems/documentation#1454]
## Title
S3 File System

## Description
The Amazon S3 CORS solution requires composer manager module, which is not supported by Pantheon. Since that module is not supported, use the S3 File System module for a cleaner more direct solution.

## Outline
3 File System (s3fs) provides an additional file system to your Drupal site,
alongside the public and private file systems, which stores files in Amazon's
Simple Storage Service (S3) (or any S3-compatible storage service). You can set
your site to use S3 File System as the default, or use it only for individual
fields. This functionality is designed for sites which are load-balanced across
multiple servers, as the mechanism used by Drupal's default file systems is not
viable under such a configuration.

## Path
/docs/articles/drupal/content-delivery-network-cdn-for-file-distribution/#amazon-s3-cors -> http://cgit.drupalcode.org/s3fs/tree/README.txt?h=7.x-2.x

**Comment by dustinleblanc** [comment]
Tested and it seems to work on the platform well! :+1:
