### ISSUE TITLE
Apache Solr on Pantheon Doc Update 

### ISSUE THREAD

**Issue by kellyimagined** [pantheon-systems/documentation#1455]
Re: [Apache Solr on Pantheon](https://pantheon.io/docs/solr)
## Issue Description:
This line "For installation instructions and additional details, see Enabling Solr for WordPress or Enabling Solr with Drupal." does not actually link to install directions.

## Suggested Resolution 
Fix the links for 
Enabling Solr for WordPress
and 
Enabling Solr with Drupal

**Comment by rachelwhitton** [comment]
Thanks for the issue @kellyimagined! Doc is now updated with the correct links
:+1:
