### ISSUE TITLE
New Doc Proposal: Implementation of Environment Indicator on Pantheon

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#1475]
Re: <Doc title and/or link>
## Description
Currently CSE informs users to utilize Environment Indicator ( https://www.drupal.org/project/environment_indicator ) if they are looking for a visual indicator of which environment they are on. We do not have documentation on how to utilize this with Pantheon's environment config, which would be helpful. Nor do we have a standard option for WP users.

## Suggested Resolution

* Document steps to install and configure Environment Indicator for Drupal sites
* Locate and Document an alternative for WP sites ( https://wordpress.org/support/view/plugin-reviews/default-admin-color-scheme looks like it might work, with some tweaking. https://wordpress.org/plugins/environment-indicator/ looks like it has been abandoned)

**Comment by bmackinney** [comment]
@lauren-kelly https://github.com/pantheon-systems/pantheon-hud/ does this for WP. For Drupal, documenting setup or creating snippets users can use in the environment indicator importer would be helpful.
