### ISSUE TITLE
Existing doc suggestion for enabling HTTPS

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#1477]
## Description
For https://pantheon.io/docs/guides/cloudflare-enable-https. As a customer, I'd like to know the trade-offs between choosing the free HTTPS CloudFlare option versus paying $30/month for SSL on a Pantheon Professional plan. 

## Expected Audience
Those wishing to enable HTTPS for their site on Pantheon.

**Comment by rachelwhitton** [comment]
Existing content in [Compatibility and Limitations](https://pantheon.io/docs/guides/cloudflare-enable-https/#compatibility-and-limitations)
