### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update

### ISSUE THREAD

**Issue by merauluka** [pantheon-systems/documentation#1482]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/drush)
## Issue Description:
Under "Known Limitations" it says:
> Migrate's support for spawning Drush processes to facilitate batch migrations is not supported on Pantheon.

It links to the following doc on drupal.org:
https://www.drupal.org/node/1958170

This appears to conflict with the following Pantheon doc's FAQ (https://pantheon.io/docs/timeouts/) that suggests setting up Migrate to use Drush via the UI in order to avoid timeouts.
> As strongly recommended by the Migrate module, use Drush, which can be invoked through Terminus. You can even configure Migrate to trigger Drush imports from the UI.

## Suggested Resolution 
Correct the documentation so it is clear whether or not Pantheon supports running Migrate operations via Drush through the UI.

**Comment by rachelwhitton** [comment]
Thanks for creating this issue @merauluka! 

@greg-1-anderson can you review and recommend a fix for the conflicting content?

**Comment by greg-1-anderson** [comment]
It should work to just set `$conf['migrate_drush_path'] = 'drush';`; this may even be the default.

Someone should test to confirm whether or not migrate works; however, it is my expectation that it should work now.

**Comment by ttrowell** [comment]
`./migrate_ui/migrate_ui.install:    variable_set('migrate_drush_path', $drush_command);`

If appears that `$drush_command` can be built with parameters:

```
Taras-MacBook-Pro:migrate tararowell$ grep -r '$drush_command' .
./migrate_ui/migrate_ui.install:  $drush_command = variable_get('wordpress_migrate_drush', '');
./migrate_ui/migrate_ui.install:  if ($drush_command) {
./migrate_ui/migrate_ui.install:    variable_set('migrate_drush_path', $drush_command);
./migrate_ui/migrate_ui.pages.inc:    $drush_command = "$drush_path $command $migrations --user=$uid --uri=$uri " .
./migrate_ui/migrate_ui.pages.inc:      $drush_command .= ' --force';
./migrate_ui/migrate_ui.pages.inc:      $drush_command .= ' --update';
./migrate_ui/migrate_ui.pages.inc:      $drush_command .= ' --notify';
./migrate_ui/migrate_ui.pages.inc:      $drush_command .= " --limit=\"$limit\"";
./migrate_ui/migrate_ui.pages.inc:    $drush_command .= " >$log_file 2>&1 &";
./migrate_ui/migrate_ui.pages.inc:    exec($drush_command, $output, $status);
```

**Comment by ttrowell** [comment]
There is no default set, after all.
On a fresh install of migrate/ migrate_ui, the variable `migrate_drush_path`  is *not* set when the module(s) are enabled.

`drush vget migrate_drush_path`  yields `No matching variable found.`
