### ISSUE TITLE
Drupal 8: Using SimpleSAMLphp with Shibboleth SSO Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1509]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)
## Issue Description:

Does doc need separate instructions for Drupal 8?
## Suggested Resolution

Set up https://www.drupal.org/project/simplesamlphp_auth on a Drupal 8 site to determine if our documentation needs updates
## ToDo
- [ ] Work with Dustin to update the doc

**Comment by dustinleblanc** [comment]
Starting

**Comment by dustinleblanc** [comment]
Running into blockers, the D8 module is using up gobs of RAM, install paradigm for D8 straddles composer dependencies and old way (including the SimpleSAMLphp project ourselves _yuck_). There may be need to augment the module to get it to work with the platform

**Comment by rachelwhitton** [comment]
@dustinleblanc any interest in taking another pass at this issue along with #1883 (WP SAML Auth)? Are we still blocked for D8?

**Comment by alexfornuto** [comment]
Reached out to @dustinleblanc for an update, assigning to him for reply.

**Comment by peter-pantheon** [comment]
Good morning, if Dustin does not have time I can revisit this and catch up on what has changed with the module and with D8 integration as it stands today.

**Comment by alexfornuto** [comment]
Yes @peter-pantheon, your time and expertise on this is highly coveted.

**Comment by peter-pantheon** [comment]
Just installed simpleSAMLphp mod into a D8 demo site and moving ahead

**Comment by sbbutkcin** [comment]
@peter-pantheon what did you do in order for the module to recognize your simplesaml library if I may ask?

**Comment by alexfornuto** [comment]
@newtoid Might you have any input on this topic?

**Comment by dustinleblanc** [comment]
This can be closed I believe, @sbbutkcin, I think we chatted about this at some point and D8 is now Samling like a boss, right?

**Comment by sbbutkcin** [comment]
@dustinleblanc it's working great for us!

**Comment by dustinleblanc** [comment]
Closing, confirmed docs are good for this with D8, thanks @sbbutkcin!
