### ISSUE TITLE
New Doc: Different Solutions for HTTPS for personal

### ISSUE THREAD

**Issue by JessiFischer** [pantheon-systems/documentation#1510]
Comes up all the time with EDU+, we need to have a public facing doc to detail the solutions.
1. Use a shared LB to terminate a WildCard or SAN cert (e.g. our existing vanity domain docs)
2. Cloudflare free SSL (shared cert)
3. Key CDN or Fast.ly 
4. BYO Network Routing

To help people understand the differences at work here, we should do simple network diagrams for these different options. Ping @joshkoenig for sketches when the time comes to do this doc page.

**Comment by joshkoenig** [comment]
From Lauren; other FAQ we should make sure that we cover:

- How much do Pantheon Enterprise and Pantheon for EDU+ customers pay to get HTTPS on their sites?
- How does a customer get HTTPS for Personal plans?
- Do we upload certs for customers? No. Adding a cert is a copy/paste operation so the customer can do it themselves.
- If a customer still wants us to upload the cert for them will we do it?
- How does a customer upload an HTTPS cert?: https://pantheon.io/docs/enable-https/#load-certificate-into-pantheon
- Can a customer not use a wildcard or SAN cert to get HTTPS? Yes is they pay.
