### ISSUE TITLE
Using SendGrid To Deliver Email with WordPress and Drupal Doc Update 

### ISSUE THREAD

**Issue by albertcausing** [pantheon-systems/documentation#1539]
Re: [Using SendGrid To Deliver Email with WordPress and Drupal](https://pantheon.io/docs/guides/sendgrid)
## Issue Description:
drush @pantheon.your-site.dev dl sendgrid_integration
drush @pantheon.your-site.dev en sendgrid_integration -y

Will not work anymore since newer sendgrid_integration module requires  composer / composer_manager now.

## Suggested Resolution 
Found on our documentation but not yet specific to sendgrid_integration module
https://pantheon.io/docs/unsupported-modules-plugins/#composer-manager

**Comment by nataliejeremy** [comment]
@zepner Can you recommend a fix for this (if there is one)?

**Comment by albertcausing** [comment]
Hi @nataliejeremy, Tim Wooten @twooten is polishing a doc on this.

**Comment by nataliejeremy** [comment]
Great! Thanks @albertcausing and @twooten

**Comment by zepner** [comment]
Sorry, just saw this. Not sure I knew the answer any better.

Zvi

On Mon, Apr 25, 2016 at 2:37 PM, Natalie Jeremy <notifications@github.com>
wrote:

> @zepner <https://github.com/zepner> Can you recommend a fix for this (if
> there is one)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/documentation/issues/1539#issuecomment-214473772>
>



-- 
Zvi Epner
Engineer, Customer Success
Pantheon Systems, Inc.
717 California St, 3rd Floor
San Francisco, CA 94108
p 646-875-8287
zvi@pantheon.io
