### ISSUE TITLE
Platform Domains Doc Inaccurate Regarding Old Domains

### ISSUE THREAD

**Issue by rvtraveller** [pantheon-systems/documentation#1540]
https://pantheon.io/docs/platform-domains/, https://pantheon.io/blog/updates-default-platform-domains, and the newsletter that was sent out in March about the change in platform domain from `pantheon.io` to `pantheonsite.io` all indicate that requests to old URLs will be redirected to the new `pantheonsite.io` domain.  This isn't happening and CSE have confirmed that sandbox sites lose their `pantheon.io` domain when they are converged (reference ticket 57559).

Seems like it is a bit late to retract the March newsletter and I don't think changing the blog post is within the scope of the documentation issue queue here but can we at least get the docs page updated to indicate that sandbox sites are losing their pantheon.io domains and they will not be redirected?

**Comment by nataliejeremy** [comment]
Thanks for creating this issue @rvtraveller 
@kibra Can you confirm if this is expected behavior or if it's a bug?

**Comment by kibra** [comment]
@nataliejeremy There was a delay in getting the redirects work deployed, as we ended up taking time to make sure it will be safe for all customers. We plan on deploying the redirects within the next couple weeks.

It is expected behavior for sandbox sites to switch over to using `pantheonsite.io`

**Comment by slivermon** [comment]
@nataliejeremy We may want to add an update that the redirect was rescheduled to occur on a new date TBD by @kibra
