### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update

### ISSUE THREAD

**Issue by eeeschwartz** [pantheon-systems/documentation#1542]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)
## Issue Description:

The example site: [dev-simplesaml.pantheonsite.io](https://dev-simplesaml.pantheonsite.io) is frozen due to inactivity.

<img width="1181" alt="screenshot 2016-04-20 10 29 19" src="https://cloud.githubusercontent.com/assets/428684/14678221/e7699fac-06e2-11e6-8416-d43f8336839e.png">

## Suggested Resolution

**Comment by nataliejeremy** [comment]
Thanks for letting us know @eeeschwartz we'll get that fixed.
