### ISSUE TITLE
New doc: Unwind WP Multisite

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1554]
We need a doc on WP multisite to single-site conversion.  This would be for use cases where someone off the platform is moving on to the platform.

**Comment by alexfornuto** [comment]
I added @aeligature to this issue, as he's been identified as a potential SME with lots of experience on this subject.

**Comment by alexfornuto** [comment]
@pantheon-systems/cse Do you guys feel that a doc on this subject would help deflect tickets?

**Comment by newtoid** [comment]
I don't know how relevant this is, we provide a wp multisite upstream, so there is no real need to convert, other than maybe price.

**Comment by alexfornuto** [comment]
Thanks for the input, @newtoid. I'm closing this for now.
