### ISSUE TITLE
Using SendGrid To Deliver Email with WordPress and Drupal Doc Update 

### ISSUE THREAD

**Issue by kellyimagined** [pantheon-systems/documentation#1557]
Re: [Using SendGrid To Deliver Email with WordPress and Drupal](https://pantheon.io/docs/guides/sendgrid)
## Issue Description:
This module requires the Mail System, Composer Manager modules to install SendGrid Integration.

## Suggested Resolution 
Isn't this a problem that composer manager is required but I thought Pantheon did not allow use of Composer Manager. Do you have another solution you suggest using?

**Comment by rachelwhitton** [comment]
Closed by #1557 

Thanks for the issue @kellyimagined!
