### ISSUE TITLE
Temporary File Management with Multiple Application Containers Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1574]
Re: [Temporary File Management with Multiple Application Containers](https://pantheon.io/docs/temp-files)
## Issue Description:
Customer reported that the Drupal override did not work (shown here: https://pantheon.io/docs/temp-files/#drupal)
$conf['file_temporary_path'] = 'public://tmp';

Bug report: https://getpantheon.atlassian.net/browse/BUGS-158

## Suggested Resolution 
Confirm if it works or not. If not, update the doc or remove it
Work with @ttrowell

**Comment by rachelwhitton** [comment]
Closed by #1668
