### ISSUE TITLE
Managing Drush Versions on Pantheon Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#1579]
Re: [Managing Drush Versions on Pantheon](https://pantheon.io/docs/drush-versions)
## Issue Description:
I checked and tried all the documents about changing the drush version (https://pantheon.io/docs/drush-versions/ and related articles) but I'm not able to change the drush version.

Ticket URL: https://pantheon-systems.desk.com/agent/case/59854

> If the site is currently running Drush 8 on Pantheon and uses composer to manage dependencies, simply add require drush/drush '8.*'. If the site does not use composer, commit the desired version of Drush directly to your site's codebase within __ROOT__/drush.

Currently, the site is running on Drush 8
` drush -> /usr/local/bin/drush8`

The instruction on how to commit the desired version is not clear. I ran the following to check the file directory structure:

`ls -la /usr/local/bin/drush*`

Here's the result:
`/usr/local/bin/drush -> /usr/local/bin/drush5`
`/usr/local/bin/drush5 -> /opt/drush/drush`

`/usr/local/bin/drush6 -> /opt/pantheon/drush-6/drush`
`/usr/local/bin/drush7 -> /opt/pantheon/drush-7/drush`
`/usr/local/bin/drush8 -> /opt/pantheon/drush-8/drush`

------
-Same issue -unable to change Drush 5.x to Drush 8 -
>Current Default is 5.x
For sites running 5.x, create a file called policy.drush.inc and place it in the .drush folder of your home directory on your local machine. You can then use hook implementations to modify versions used for remote aliases.

>The following example uses Drush 8 instead of 5.x for targets on the Pantheon platform. Our hook_drush_sitealias_alter function within the policy.drush.inc file looks like this:
`function policy_drush_sitealias_alter(&$alias_record) {
  // Fix pantheon aliases!
  if ( isset($alias_record['remote-host']) &&
      (substr($alias_record['remote-host'],0,10) == 'appserver.') ) {
    $alias_record['path-aliases']['%drush-script'] = 'drush8';
  }
}`

>Save the file and clear Drush cache by running drush cc drush, then check Drush version:

>`$ drush @pantheon.SITENAME.ENV version`
>`drush version 8.x`

Here's the output:

Note:  For debugging purposes, I added `print_r($alias_record);` in the policy.drush.inc file to check if the file is being called.

` drush @pantheon.reng-qs.dev version --strict=0`

`Array`
`(`
   ` [uri] => dev-reng-qs.pantheon.io`
    `[db-url] =>redacted
   ` [db-allows-remote] => 1`
   ` [remote-host] => redacted`
   ` [remote-user] => redacted`
   ` [ssh-options] => -p 2222 -o "AddressFamily inet"`
    `[path-aliases] => Array`
       ` (`
            `[%files] => code/sites/default/files`
           `[%drush-script] => drush8`
        `)`
    `[#name] => pantheon.reng-qs.dev`
   ` [#group] => pantheon`
   ` [#file] => /Users/rubelyneng/.drush/pantheon.aliases.drushrc.php`
`)`
`drush version 5.10.1`
`Site Audit v1.10 `

**Noticed that uri is pointing to ` [uri] => dev-reng-qs.pantheon.io`. Site is now using pantheonsite.io domain.

## Suggested Resolution

Verify if it works. Update doc and provide troubleshooting tips if possible.

**Comment by nataliejeremy** [comment]
@greg-1-anderson Would you take a look at this issue and comment with a fix? Thanks!

**Comment by dustinleblanc** [comment]
@nataliejeremy @greg-1-anderson I think this can be resolved via terminus and just ensuring customers understand this is *the* way to do this. Including your own drush  in your repo and what not doesn't seem a good way to manage drush versions. We should keep all settings in Terminus or the Dashboard and cull all other work-arounds.
