### ISSUE TITLE
New Doc Request: Working with Cookies on Pantheon

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/documentation#1581]
Currently we we bury a lot of pretty key info at the bottom of a section here:

https://pantheon.io/docs/debug-cache/#cookies-&-varnish

For many web developers, "Varnish" is a foreign word, or at least some advanced thing they don't understand. We should consider creating a doc that's focused around how to do things with websites and cookies, laying out the important basic info above, and the specific cookie tips and tricks from this page:

https://pantheon.io/docs/caching-advanced-topics/

**Comment by dustinleblanc** [comment]
We should also add to the documentation that Varnish explicitly is set to effectively a zero ttl in dev/multi-dev

**Comment by ari-gold** [comment]
@dustinleblanc Varnish will cache on Dev/Multidev
e.g.
```
[ari@ink:~ ] $ curl -I dev-ari.pantheonsite.io
HTTP/1.1 200 OK
Cache-Control: public, max-age=86400
Content-Language: en
Content-Type: text/html; charset=utf-8
Date: Wed, 25 May 2016 22:24:41 GMT
Etag: W/"1464215077-0"
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Last-Modified: Wed, 25 May 2016 22:24:37 GMT
Server: nginx
X-Drupal-Cache: HIT
X-Generator: Drupal 7 (http://drupal.org)
X-Pantheon-Endpoint: 2eadebc5-b71f-4685-b232-ac9f1dd4547a
X-Pantheon-Styx-Hostname: styxa28fb950
X-Styx-Req-Id: styx-0def1aba1a84e0de9b93301dd1630f26
X-Styx-Version: StyxGo
X-Varnish: 1003548377 1005451007
Age: 4
Via: 1.1 varnish-v4
Vary: Accept-Encoding, Cookie, Cookie
Connection: keep-alive
```
