### ISSUE TITLE
Provide Drupal 8 sample code for overriding configuration in drupal 8 settings.php file.

### ISSUE THREAD

**Issue by mmenavas** [pantheon-systems/documentation#1602]
## Issue Description
The section titled "How can I write logic based on the Pantheon server environment?" on [Configuring Settings.php](https://pantheon.io/docs/settings-php/) does not show sample code for overriding configuration in drupal 8; it only shows sample code for drupal 7.
## Suggested Resolution
Show sample code for drupal 8 or at the very least, provide a link to [Configuration override system](https://www.drupal.org/node/1928898) on drupal.org.

**Comment by mmenavas** [comment]
Below is sample code for overriding drupal 8 configuration on settings.php.
```
  // Expiration of cached pages - 15 minutes.
  $config['system.performance']['cache']['page']['max_age'] = 900;
  // Aggregate and compress CSS files in Drupal - on.
  $config['system.performance']['css']['preprocess'] = true;
  // Aggregate JavaScript files in Drupal - on.
  $config['system.performance']['js']['preprocess'] = true;
  // Google Analytics.
  $config['google_analytics.settings']['account'] = 'UA-xxxxxxx-xx';
```

**Comment by ari-gold** [comment]
Thanks for the contribution, @mmenavas!

**Comment by mmenavas** [comment]
@ari-gold My pleasure.
