### ISSUE TITLE
Drupal 8 and Composer

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1620]
Re: Drupal 8 and Composer

## Issue Description

As of Drupal 8.1.0, site owners have new options for managing modules and dependencies through the composer.json at the drupal root.

Additionally, using Pantheon has the potential for confusion as the drupal.org version of Drupal core no longer version controls the vendor directory populated by composer.

## Suggested Resolution

I will write a new with a suggested workflow for using Composer and Drupal 8 together on Pantheon. I will reference recommendations in this drupal.org docs page: https://www.drupal.org/node/2404989

**Comment by stevector** [comment]
There is a pull request in progress here: https://github.com/pantheon-systems/documentation/pull/1628

**Comment by stevector** [comment]
I'm removing myself as the assignee as I realize that may have indicated that the PR is still in progress. I think it is good to merge. Anyone have time to review?

**Comment by rachelwhitton** [comment]
+1 Thanks for the great doc @stevector !! This is awesome stuff. I added you as a contributor, feel free to tweak/edit your profile within the `app/config/sculpin_site.yml` file anytime. 

@nataliejeremy can you review and merge?
