### ISSUE TITLE
Google AMP Validator Issue

### ISSUE THREAD

**Issue by peter-pantheon** [pantheon-systems/documentation#1631]
## Title

The Google AMP Validator Fails 

## Outline

[Google AMP validator](https://www.ampproject.org/docs/guides/validate.html) fails when the New Relic Browser agent JavaScript tag is included in HTML pages formatted for AMP.  A validation error that says: “The tag 'script' is disallowed except in specific forms” may get thrown.

To remedy this on Drupal and WordPress sites, you can use PHP code to run the newrelic_disable_autorum function on your AMP pages. This prevents the New Relic JavaScript from being inserted on the AMP page.

To disable New Relic on AMP pages, follow the instructions found in [New Relic’s Disable Browser monitoring for specific pages](https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/disable-browser-monitoring-specific-pages) article.

AMP stands for [Google’s Accelerated Mobile Pages (AMP) project](https://www.ampproject.org/docs/get_started/about-amp.html) is an open source initiative whose objective is to help publishers create mobile optimized web pages that load quickly on mobile devices.

AMP consists of three different parts: AMP HTML, AMP JS, Google AMP Cache. 

In February 2016, Google integrated AMP listings into its mobile search results. Pages making use of AMP coding appear within special places in the search results and/or with a special “AMP” designation.

**Comment by rachelwhitton** [comment]
Tested on WP and Drupal 8, although validation errors were not observed when testing on D8: 

```php
$amp="/.*\?amp.*|.*\/amp\/.*/";
if (extension_loaded('newrelic')) {
  if (preg_match($amp, $_SERVER['REQUEST_URI'])) {
    newrelic_disable_autorum (FALSE);
  }
}
```
