### ISSUE TITLE
Choosing Your Start State Doc Update

### ISSUE THREAD

**Issue by icylace** [pantheon-systems/documentation#1650]
Re: [Choosing Your Start State](https://pantheon.io/docs/start-state)
## Issue Description:
CiviCRM requires SFTP mode to be active in order to install correctly.

## Suggested Resolution
Update doc to include SFTP instructions and review other distributions if necessary.

**Comment by nataliejeremy** [comment]
Thanks @icylace I think this will be better addressed in the UI where the user needs to know this (while they're making their selection). I'll make a PR in the Dashboard repo to address this.

**Comment by rachelwhitton** [comment]
closed by #1720
