### ISSUE TITLE
Penetration / Vulnerability Testing

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#1654]
Re: Penetration Testing
## Issue Description

We do not have customer-facing documentation regarding penetration or vulnerability testing
## Suggested Resolution

https://docs.google.com/a/getpantheon.com/document/d/1Hylnk8syrFyPLzTDzHaPyqR0y2fGjOm_v5fsRv8D9FU/edit?usp=sharing

**Comment by ari-gold** [comment]
@garydylina @secsal Not sure if you're already in the loop, but thought you'd want to review this proposed doc.

**Comment by lauren-kelly** [comment]
If/when this goes online, could we get a form included that generates a desk ticket? 
it should include:
*Domains to be scanned
*Approximate dates and times of scan activity
*Name of entity performing scan
*Name and contact information for person who can halt scanning if necessary
Let me know and we can discuss who it should go to and with which labels, etc.

**Comment by alexfornuto** [comment]
Per discussion with @garydylina, he and I will be spawning a new document to address penetration and vulnerability testing, once the Global Edge rollout is complete.

**Comment by alexfornuto** [comment]
Per security team, we're not going to add any documentation on pentesting.
