### ISSUE TITLE
Add render-array based example for Drupal 8 caching

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1673]
Re: https://pantheon.io/docs/cache-control

## Issue Description

While the Drupal 8 example in our cache control page works, it is not advisable in many/most situations. If there is a page that should have a max_age of 0, then one of the render arrays within that page should have set the max_age. See https://twitter.com/stevector/status/743173556121411584

## Suggested Resolution

Add render array example.

**Comment by rachelwhitton** [comment]
@stevector How about replacing the current example with `$build['#cache']['max-age'] = 0;` ? Should we change the approach to the D7 and WordPress examples as well? Thanks for opening the issue!

**Comment by stevector** [comment]
@rachelwhitton good call. Here is a PR: https://github.com/pantheon-systems/documentation/pull/1685
