### ISSUE TITLE
New Doc: Using the WordPress REST API

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1683]
## Title

Using the WordPress REST API 
## Description

Learn how to use the WordPress REST API to access data and render content. 
## Outline
- Use cases and example scenarios 
- Comprehensive snippets using `WP_Query`, `wp_remote_get`, `wp_remote_post` etc. with example responses
- Custom post types
- Adding custom endpoints
## Expected Audience

Intermediate WP developers
## Path

`docs/wordpress-rest-api`

**Comment by alexfornuto** [comment]
After internal discussion, we determined this doc would not help ticket deflection.
