### ISSUE TITLE
Adding HTTPS For Free With CloudFlare Doc Update 

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#1687]
Re: [Adding HTTPS For Free With CloudFlare](https://pantheon.io/docs/guides/cloudflare-enable-https)
## Problem
non-www resolution fails with A record set
## Solution
Update documentation to use CNAME, see case 64310

**Comment by rachelwhitton** [comment]
The guide has the following statement: 
> In addition, using CNAME Flattening is the only way to standardize on HTTPS with a root domain.

I'm not seeing that we recommend configuring DNS with an A record in this scenario; can you clarify the problem/solution @slashzero? Thanks in advance!

**Comment by nataliejeremy** [comment]
Hey @slashzero Can you tell us specifically where in the doc the issue is? We recommend using CNAME flattening and aren't sure where the confusion is. Thanks.
