### ISSUE TITLE
Log Retention

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1698]
Re: [Log Files on Pantheon](https://pantheon.io/docs/logs)
## Issue Description
Missing content on log retention/rotations
## Suggested Resolution
- [x] Documentat log retention on Pantheon. 
 - Determine if all log files are rotated similarly and explore possible variants such as service levels. 
- [x] Document available dbserver logs (`mysqld.log` and `mysqld-slow-query.log`) within the [Log Files on Pantheon](https://pantheon.io/docs/logs/#download-raw-webserver-log-files) doc. Refactor [Download MySQL Slow Query Log](https://pantheon.io/docs/logs/#download-mysql-slow-query-log) section so all dbserver logs are downloaded 

cc @hengkit

**Comment by hengkit** [comment]
Looks like:

# MySQL Status log
1 MB 

# MySQL slow log
7 days

# PHP Error, PHP FPM Error log
1 MB 

# Nginx Error log
1MB

# PHP Slow log
10MB

# Nginx Access Log
60 days
