### ISSUE TITLE
Migrate to Pantheon: Manual Site Import Doc Update

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1721]
Re: [Migrate to Pantheon: Manual Site Import](https://pantheon.io/docs/manual-import)
## Issue Description:
New "migrate existing site" flow has changed within the dashboard

## Suggested Resolution 
- Make sure language matches between UX and doc
- Order of import steps matches between UX and doc

**Comment by allenfear** [comment]
@nataliejeremy @rachelwhitton does this issue cover documentation for the Successful Site Migrations project:
https://app.asana.com/0/100649779394869/158288764778983

**Comment by rachelwhitton** [comment]
Reopening this one. The work completed in #1722 did not include any BlogVault updates. 

In addition to any outstanding BlogVault updates, we'll want to revise [Export an Existing WordPress Site](https://pantheon.io/docs/wordpress-export) and [Export an Existing Drupal Site](https://pantheon.io/docs/drupal-export). Both docs reference separate archive imports for DB, Files, and Codebase.

**Comment by ari-gold** [comment]
@rachelwhitton Revising the export docs sounds like a good idea, but not related to this issue "updated manual import doc". Also, the UI changes re BlogVault are forthcoming and will be handled in a separate docs issue.

**Comment by allenfear** [comment]
@nataliejeremy is the successful site migrations issue already created, and if not could we create it to start tracking it?

**Comment by nataliejeremy** [comment]
@allenfear That work was completed in this issue (unless something else has changed that I'm not aware of).
