### ISSUE TITLE
Using SendGrid To Deliver Email with WordPress and Drupal Doc Update

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1734]
Re: [Using SendGrid To Deliver Email with WordPress and Drupal](https://pantheon.io/docs/guides/sendgrid)
## Issue Description:

Possible Drupal 8 module for Sendgrid integration. See https://www.drupal.org/node/2686237#comment-11304147 and https://github.com/Nikeev/drupal_sendgrid
## Suggested Resolution

Test new module so that we can make a recommendation for D8

**Comment by alexfornuto** [comment]
This information has already been addressed and is present in the guide.
