### ISSUE TITLE
Common Performance Issues

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1749]
Re: [Debugging Slow Performance](https://pantheon.io/docs/debug-slow-performance/)
## Issue Description

Cover troubleshooting/debugging of additional performance issues 
## Suggested Resolution
- Running cron over web
- External call time outs within scripts
- bg processes hitting limits

See related case 66413
Reported by @zepner

**Comment by newtoid** [comment]
@peter-pantheon please can you take a look at this doc issue and let me know if you hit any issues? Thanks!

**Comment by peter-pantheon** [comment]
@newtoid This is a good doc. I would be great among the must reads in the start section of Pantheon docs (if it is not there) and reviewed during onboarding in a friendly way. For Customers with the technical chops this is a great reminder of what they need to tend to. For Customers with less tech chops, this opens their eyes to real world conditions and preps them ahead of what is in store as a site really grows on Pantheon.
