### ISSUE TITLE
Verify SimpleSAML works with latest version

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1750]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)
## Issue Description:

Our Docs point to an old version of SimpleSAML which could possibly be less secure, we should verify version constraints and adjust docs.
## Suggested Resolution

Try install with latest version and verify it works.

**Comment by rachelwhitton** [comment]
Dupe #1883
