### ISSUE TITLE
Role-Based Permissions

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1752]
Update/improve doc based on feedback from an org (provided by Kim Kiser):

This stems from this organization dealing with an incident last week.  They have a set up where there is a live client site, and a testing client site (two separate sites).  A dev that thought they were on the testing site pushed code to the live env. However turns out they were on the actual client site, and pushed an in-progress feature that wasn't ready. They are still recovering from this.

There are a number of factors that contributed to this happening, one of which is clarifying what user roles have which permissions. I'm thinking about ways to clarify this in the UI directly, but wanted to send you feedback about making the documentation more understandable.  This org has been using pantheon for years, and they didn't understand what all the roles entailed :/  (and I have a hard time wrapping my head around this too!)

So some specific examples to try to clarify:
- “Team member” vs. "Developer" roles seem counter-intuitive to me. Team member actually means full permissions.  Developer can't push to live.  This seems reversed and is a larger problem in my mind :)  But can we think about calling this out better to help tell this?

- a goal this particular org has is to give the lowest level permission to some users ("lock permissions down" is the language they used) - and it's not clear which role would do that.

- the doc itself is a little confusing in that we are trying to describe all the roles at all the levels (enterprise, partner-level, site level). It might help to group these sections together more clearly?

- we might add some screenshots to this page to help them connect our role descriptions with what they are looking at in the actual UI.

- an update is needed for: "Use the Workflow tool on Test and Live" - the workflows tab was renamed to database/files a little while ago - is this referring to that tab? If so it needs the updated name.

**Comment by ari-gold** [comment]
@nataliejeremy  When adding a user to an org there's an expandable table (screenshot below). Maybe we can include that as a screenshot? I think it succinctly explains the org level roles and perms. Maybe we can make a similar table for the site level? /cc @kimby77 

<img width="670" alt="screenshot 2016-07-19 15 27 18" src="https://cloud.githubusercontent.com/assets/7874556/16968693/51244644-4dc5-11e6-8d37-fc0986c1cb98.png">

**Comment by kimby77** [comment]
@ari-gold this would be a great table to have in this doc!

Plus I think we can do some work to orient this page around user goals.  Such as, "I want to add a client and give them the lowest level of access, so what role should I choose?"
