### ISSUE TITLE
Redis as a Caching Backend Doc Update

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1767]
Re: [Redis as a Caching Backend](https://pantheon.io/docs/redis)
## Issue Description:

We see many sites implement option B in the below example, as A and B look appear equally relevant in the documentation. This hurts site performance, in some cases quite badly, which is sad and unnecessary:
http://screencast.com/t/lQc8HAExsb
## Suggested Resolution

Could we either take out option B, move it to "trouble shooting" section, or at least make it very clear that:
- option A should be the default setup (vast majority of sites)
- option B is the rare, niche use case that is mainly relevant as a solution to an apparent performance impacting issue, where Redis evictions is defined as the root cause. 
- If at all in doubt, go with option A

**Comment by davidstrauss** [comment]
We should probably instruct our users to direct Drupal's page cache to a null cache backend.

**Comment by alexfornuto** [comment]
@tinefin does #2325 address your concerns?

@davidstrauss who would be a good SME to reach out to, in order to implement your suggestion?

**Comment by alexfornuto** [comment]
Closed by #2325
