### ISSUE TITLE
Redis as a Caching Backend Doc Update 

### ISSUE THREAD

**Issue by Steve4ASU** [pantheon-systems/documentation#1781]
Re: [Redis as a Caching Backend](https://pantheon.io/docs/redis)
## Issue Description:

Just a question. On "Step 4. Optional configurations" - Does optional mean you can skip this step? Or do you have to implement one of the options shown?

## Suggested Resolution 

If the whole step is optional, suggest adding "You may skip this step and proceed to Step 5."

If a user needs to implement one option or the other, suggest calling this step "Configuration options" instead of "Optional configurations."

**Comment by nataliejeremy** [comment]
Thanks for creating this issue @Steve4ASU 
@slashzero @tinefin Is it required to choose one configuration or are both optional?

**Comment by nataliejeremy** [comment]
Thanks for creating this issue @Steve4ASU  We are closing this issue as it was reported in #1767 and needs some additional research before we make the update.
