### ISSUE TITLE
Parsing nginx Access Logs with GoAccess Doc Update 

### ISSUE THREAD

**Issue by baptisten** [pantheon-systems/documentation#1783]
Re: [Parsing nginx Access Logs with GoAccess](https://pantheon.io/docs/nginx-access-log)
## Issue Description:
It seems goaccess.conf has changed variables and the recommended lines to add are no longer valid.
```
time_format %H:%M:%S %z
date_format %d/%b/%Y
log_format %^ %^ %^ [%d:%t] "%r" %s %b "%R" "%u" %T "%h"
```
I am running GoAccess - 1.0.2.

## Suggested Resolution 
The 3 variables are now with hyphens. time-format, date-format, log-format 
But aside from that i still get the same error, making me think there might be some changes in the actual format value.

The console error is :
> Nothing valid to process. Verify your date/time/log format.

**Comment by rachelwhitton** [comment]
Fixed by #1784 
Thanks for reporting @baptisten! Much appreciated!
