### ISSUE TITLE
Role-Based Permissions 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1791]
Re: [Role-Based Permissions & Change Management](https://pantheon.io/docs/change-management/)

## Issue
Some permissions may be incorrect for certain roles.

## Resolution
Test site-level permissions 

Surfaced by @hengkit

**Comment by hengkit** [comment]
All suggestions below pertain to the site level permissions table

The second row of the site level table should be changed to `access the site dashboard`
The `Create Sites within an org` row should be removed
The `Administrator` column should be removed
and the label on the `Site Owner` column changed to `Site Owner/User in charge`

**Comment by hengkit** [comment]
Tool tip on the unprivileged column of the Organization permissions table is inaccurate. Unprivileged users are also available in EDU+ orgs
