### ISSUE TITLE
New Doc Proposal: Using LetsEncrypt with your Pantheon site

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1798]
We've gotten several feature requests to integrate LetsEncrypt. While we won't offer native integration, we'd like to document how people can use LetsEncrypt on Pantheon. Please work with CSE, if necessary, to do discovery and document.

Related feature request: https://getpantheon.atlassian.net/browse/FEAT-152

Currently, Professional plans and above allow you to add HTTPS and you can use Let's Encrypt to obtain a certificate using the DNS challenge method to prove domain ownership.  Let's Encrypt is not automated on Pantheon at this time. 

If you'd like to add free HTTPS to a personal plan see https://pantheon.io/docs/guides/cloudflare-enable-https/

## Path

(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by thoughtchad** [comment]
+1

**Comment by mindofjonas** [comment]
+1 Is there an update on this?

**Comment by alexfornuto** [comment]
I did this configuration myself while moving to Pantheon recently, so I'll try my hand at writing this.

**Comment by alexfornuto** [comment]
Moving to blocked for the next week, until I meet with a SME who'll help me resolve issues with Drupal compatibility.

**Comment by benjifisher** [comment]
> Let's Encrypt is not automated on Pantheon at this time.

The certs from Let's Encrypt have to be renewed every 90 days.  If we cannot automate the renewal process, then it doesn't count.

**Comment by crobertwatson** [comment]
To add fuel to this fire, below is quoted a new notice my client and I just got from Google this morning that I've not yet seen on any of the sites where I've enabled CloudFlare for basic SSL (rather than pay a full $75/mo more for Pantheon Professional just to get basic SEO SSL). If LetsEncrypt renewal automation isn't in the cards, then I would love to see an SSL a la carte option as an add-on to the Personal plan for clients who don't have the 100,000 page views/month, nor a need for Redis or Solr, to justify the Professional plan.

```
Google has detected that the current SSL/TLS certificate used on https://www.osiristours.com/  does not include https://www.osiristours.com/  domain name. This means that your website is not perceived as secure by some browsers. As a result, many web browsers will block users accessing your site by displaying a security warning message. This is done to protect users’ browsing behavior from being intercepted by a third party, which can happen on sites that are not secure.

Recommended Action:

Update your certificate
To correct this problem, either update your current certificate to add your domain name to the list of domains protected by the certificate, or get a new SSL/TLS certificate for your domain. The certificate should be issued from a Certificate Authority (CA) that is trusted by web browsers.
```

**Comment by JamesJosephFinn** [comment]
@crobertwatson Cloudflare Free SSL is a proxy service. It was better than nothing for a while, but not anymore. Full end-to-end encryption is the new standard. I agree, Pantheon needs to include SSL Certs, a la WP Engine.

**Comment by alexfornuto** [comment]
This issue has been superseded by platform changes. For more information, see https://pantheon.io/docs/free-https
