### ISSUE TITLE
New Doc Proposal: Reset dev/test to code on live

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1803]
## Title

Reset your dev or test code to the state of a live site
## Description

Customer's frequently get something completely messed up in their dev/test environments and are not sure how to restore their site to be identical to live so they can start over.
## Outline
- Explain situations that might need a reset
- Step by step example for remediating the situation
## Expected Audience
- Developers who are new to git and not capable of this on their own yet.
## Path

`source/docs/revert-dev-to-live`

Here are the general steps I gave to a customer in a recent ticket:
1. Check all of your repository's tags:

``` sh
$ git pull origin master
$ git tag
8.0.0
8.0.0-beta12
8.0.0-beta14
8.0.0-p1
8.0.0-rc1
8.0.0-rc2
8.0.0-rc3
8.0.0-rc4
8.0.1
8.0.2
8.0.3
8.0.4
8.0.5
8.0.6
drupal-8-base
pantheon.initialize
pantheon_live_1
pantheon_live_2
pantheon_live_3
pantheon_live_4
pantheon_test_1
pantheon_test_2
pantheon_test_3
pantheon_test_4
```
1. We need to find the reference of our _highest_ live tag, which in the output above `pantheon_live_4`:

``` sh
$ git show-ref pantheon_live_4
e823d8fbbf144cfcadea8186e2a42c580aa6b924 refs/tags/pantheon_live_4
```
1. We need to hard reset our master branch to that reference:

``` sh
$ git reset --hard e823d8fbbf144cfcadea8186e2a42c580aa6b924
HEAD is now at de01768 Update dependencies
```
1. We now need to push this up to Pantheon:

``` sh
$ git push origin master -f
```

The dev environment should now be identical to live, you can deploy it to test using the workflow, all three environments will now point to an identical set of commits.

**Comment by nataliejeremy** [comment]
@ari-gold @sehamilton what's the recommended method for doing this? Last we heard it was for customers to use a backup from Live. Can you confirm?

**Comment by newtoid** [comment]
+1 for explaining this clearly, the latest commit on the live environment is listed on the dashboard for easy reference

**Comment by rachelwhitton** [comment]
Consider adding within an existing doc, such as [Undo Git Commits](https://pantheon.io/docs/undo-commits/).
