### ISSUE TITLE
Redirect Incoming Requests Doc Update

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1812]
Re: [Redirect Incoming Requests](https://pantheon.io/docs/redirects)
## Issue Description:

Customers frequently have compound redirect requirements that turn into a jumble of branching code statements that are super hard to understand and debug. We should provide guidance around best practices for compound redirect cases that can be used as a scaffold or template for customers to use when they have multiple conditions that they need to check for (https, www, legacy paths that don't exist anymore...)
## Suggested Resolution

Add new section to docs that covers some basic do's and don't for "choose your own path" snowflakes. There is a formula that works pretty well:
1. decide if a redirect is needed
2. determine the new location
3. perform the redirect.

This should only ever iterate _once_

This helps to avoid folks getting redirected before another condition can be evaluated or getting redirected multiple times.

**Comment by nataliejeremy** [comment]
Thanks for creating this issue @dustinleblanc Think you'll have time to work on it this week?

**Comment by dustinleblanc** [comment]
Sorry I'm slow and easily distracted :)

I'll put this on my todo list

**Comment by alexfornuto** [comment]
@dustinleblanc do you feel that the guide in it's current form still needs additional information as described in this issue?

**Comment by dustinleblanc** [comment]
@alex Yeah, its probably fine, I tried to draft up a really detailed explanation of what I think the right concept for this is and realized that there are so many permutations that an example probably won't work and the general warning is probably enough
