### ISSUE TITLE
New Relic Pro Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1819]
Re: [New Relic Pro](https://pantheon.io/docs/new-relic)
## Issue Description:
https://pantheon-systems.desk.com/agent/case/68624

## Suggested Resolution 
Could we add that to "trouble shooting" / "frequently asked questions"?
Would be great with a direct link here (an id to link to).

**Comment by nataliejeremy** [comment]
@tinefin Closing this issue as we already have that issue in the Troubleshooting section: 
Users with an active session for a different New Relic account than the one that "owns" the site account will be denied access. Log out of New Relic, and click the Go to New Relic button in the Site Dashboard.
