### ISSUE TITLE
Platform Resources by Plan Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1823]
Re: [Platform Resources by Plan](https://pantheon.io/docs/platform-resources)

Refactor doc and preserve all content from [Pricing Comparison](https://pantheon.io/pricing-comparison)

**Comment by joshkoenig** [comment]
We should also take this opportunity to vet/update the info there, as it hasn't been touched in quite a while. :)

**Comment by alexfornuto** [comment]
We recently updated this doc in #2837, so I'm calling it audited.
