### ISSUE TITLE
Log Files on Pantheon Doc Update

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1834]
Re: [Log Files on Pantheon](https://pantheon.io/docs/logs)
## Issue Description:
Scattered documentation on downloading logs

## Suggested Resolution 
Could we please either merge or clearly link to this guide:
https://pantheon.io/docs/download-logs

**Comment by nataliejeremy** [comment]
+1 for combining the docs

**Comment by rachelwhitton** [comment]
+1 - Let's preserve the content in [Automate Downloading Logs from the Live Environment
 Contribute ](https://pantheon.io/docs/download-logs/) within [Log Files on Pantheon](https://pantheon.io/docs/logs/)

Todo: Replace links throughout as needed based on `rake` (`htmlproofer`) errors
