### ISSUE TITLE
CloudFlare CDN and DNS on Pantheon Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1843]
Re: [CloudFlare CDN and DNS on Pantheon](https://pantheon.io/docs/cloudflare) and https://pantheon.io/docs/guides/cloudflare-enable-https/ 

CloudFlare has documentation on using Page Rules for Drupal & WordPress

https://www.cloudflare.com/features-page-rules/optimize-drupal/
https://www.cloudflare.com/features-page-rules/optimize-wordpress/

Would be great to confirm these work for Pantheon sites and link to the documentation

**Comment by slashzero** [comment]
Have we got a paid plan on Cloudflare that we can test this on?

**Comment by alexdicianu** [comment]
It seems both those pages for Drupal and Wordpress present general page rule features that can be used to optimize sites but aren't specific to any CMS.

**Comment by alexdicianu** [comment]
Doc addition to follow.
