### ISSUE TITLE
Launch Check - Drupal Performance and Configuration Analysis Doc Update 

### ISSUE THREAD

**Issue by alexfinnarn** [pantheon-systems/documentation#1846]
Re: [Launch Check - Drupal Performance and Configuration Analysis](https://pantheon.io/docs/drupal-launch-check)
## Issue Description:

The opt-out of checks Q&A seems outdated or is confusing to me. [https://pantheon.io/docs/drupal-launch-check/#can-i-opt-out-of-a-specific-recommendation%3F](https://pantheon.io/docs/drupal-launch-check/#can-i-opt-out-of-a-specific-recommendation%3F)

I don't see a "Cache" report but a "Drupal's caching settings" report. Similarly the "PageCompression" check is listed as "Cached page compression" on the audit page making me think "DrupalsCachingSettingsCachedPageCompression" would be the key to put in 

`$conf['site_audit']['opt_out']['DrupalsCachingSettingsCachedPageCompression'] = TRUE;`
## Suggested Resolution

I would just add more clarifying text here. I just tried: 

`$conf['site_audit']['opt_out']['ExtensionsNotRecommended'] = TRUE;` 

and no dice. So I don't know how to create the camel-cased key for exclusion. I'd either tie this to #ids on the page or some data attribute, but guessing what it is has led me to failure.

**Comment by rachelwhitton** [comment]
Thanks for reporting @alexfinnarn! I believe the following is what you're looking for: 
```
$conf['site_audit']['opt_out']['ExtensionsUnrecommended'] = TRUE;
```
The format here is a combination of the report and the check. Here's a list of checks for the extensions report for context: http://cgit.drupalcode.org/site_audit/tree/Check/Extensions


We can definitely clarify this in the doc. +1 


cc @greg-1-anderson
