### ISSUE TITLE
Migrate Sites to Pantheon: Troubleshooting Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1848]
Re: [Migrate Sites to Pantheon: Troubleshooting](https://pantheon.io/docs/migrate-troubleshooting)
## Issue Description:
@pantheon-systems/cse 
Add error messages and solutions for various failure scenarios

Try importing the following archives (https://github.com/pantheon-systems/MigrateLib/blob/master/s3-links-unsupported.txt), collect error message, and suggest solutions.

**Comment by nataliejeremy** [comment]
Hey @ari-gold I get a 404 when I click that link. Can you update it?

**Comment by rachelwhitton** [comment]
Do we need improved error reporting from product before we move forward in docs? Curious if there's a list of known error messages for failed migrations? cc @ari-gold @lauren-kelly

**Comment by ari-gold** [comment]
As we talked about last week, we surface errors to users, for the known unsupported archives listed in above in the body of this issue.
