### ISSUE TITLE
Migrating Sites to Pantheon: Preserve Existing Git History Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1860]
Re: [Migrating Sites to Pantheon: Preserve Existing Git History](https://pantheon.io/docs/migrate-preserve-history)
## Issue Description:

Regarding step 6 in this guide:
git pull --no-rebase --squash -Xtheirs pantheon master

Looks like git changed it's behaviour with regards to merging 2 projects with no common history:
https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L58-L68
http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories#answer-37938036

Customer issue at Desk id #69378

## Suggested Resolution 
I *think* adding "--allow-unrelated-histories --force" to the git pull command might work (suggested this to customer). But I do not know for sure yet (untested).

Also, I cannot say for sure whether there is a risk / edge case scenario where this could result in overwriting / removing valid custom code files.
I don't think so, but.
It needs testing :-)

**Comment by tinefin** [comment]
Adding adding "--allow-unrelated-histories --force" was unsuccessful. I have git version 2.7.4 locally, here I cannot reproduce the issue. Still looks like the change in git 2.9 very likely could be the issue.

## Suggested Resolution 
It looks like there is an issue, likely with git version 2.9 and above. This needs to be verified, tested and we likely need new guidelines / solution for git 2.9 and above.

In the meantime, it would be great if we could add something like "this will only work for git versions below 2.9" / "we have reports that there are issues with git version 2.9 and above" / or similar..

**Comment by tinefin** [comment]
FYI: Customer that reported the issue, is running git version 2.9.2

**Comment by tinefin** [comment]
Just tried this again in my local (git version 2.7.4). Getting merge conflicts in step 8 - on the *second* pull from Pantheon repository.

Did git change it's behavior in an even earlier version, so that step 6 in the guide here no longer replaces / overwrites the Drupal core files with the Pantheon upstream, but rather merges them?

Sending the gist via email, as I am unsure whether there is any non-public info in there.

**Comment by ttrowell** [comment]
Great find @tinefin !  Did you happen to test the cherry-picking solution the second guy posted in to see if it was credible?
http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories#answer-37938036

**Comment by tinefin** [comment]
# Summing up
So, we actually have 2 different issues here. 

Desk ticket reference:
#69378

## Issue 1: Git version 2.7.4 [SOLVED]
(perhaps earlier too, but this is what I got to work with)

### Symptoms:
Merge conflicts in step 8 in the guide

### Root cause:
I believe git has changed it's default pull behavior from "merge" to "rebase" and that is what causes this issue. This makes a lot of sense in general - but in this case rebase will send us into an endless loop as the local code files we are attempting to replace, will be put "on top of" the remote version repeatedly..
I don't have git changelog here to show for it, but that is what it looks like.

### Solution:
In step 8, add `--no-rebase` and things run beautifully..
The entire line then becomes:
`git pull pantheon master --no-rebase`

### Docs action items
Please update Step 8 to the above line


## Issue 2: Git version 2.9 and above
I have not verified or tested this issue as I do not have git version 2.9, but customer reports hint that git has become more reluctant to merge 2 projects with no common history.

### Symptoms:
On git pull (step 6 in the guide), git complaints that the local version of the Drupal core files will be overwritten (which is exactly what we want!).
Adding `--allow-unrelated-histories` or `--allow-unrelated-histories --force` has no effect.

From customer tests:
`$ git pull --no-rebase --squash --allow-unrelated-histories --force
-Xtheirs pantheon master
From ssh://codeserver.dev.XXX branch master -> FETCH_HEAD

error: The following untracked working tree files would be overwritten by merge:
core/assets/vendor/.gitignore
core/assets/vendor/backbone/backbone-min.js
core/assets/vendor/backbone/backbone-min.map`
...etc (listing all Drupal core files)

### Root cause:
It looks like this is caused by changed git behavior, regarding merging 2 projects with no common history:
https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L58-L68
http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories#answer-37938036

### Solution:
Needs work.

### Docs action items
Verify, Test, find a solution - perhaps add in the guide that there are known issues with git version 2.9 and above.
