### ISSUE TITLE
October Changelog Candidates

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1864]
Add September platform changes and new features to be included in the October Changelog (sent out 10/1)

**Comment by allenfear** [comment]
@nataliejeremy do we have a list of features for this already?

**Comment by kimby77** [comment]
**Dashboard Design Updates**
We've rolled out some design updates for the dashboard! These include improvements to selected states for environment tabs and navigation to help keep you better oriented when moving through the UI, added white space to give everything some breathing room, and nested the menu items on the left side to streamline navigation.


![designupdate](https://cloud.githubusercontent.com/assets/19398001/18999062/87c83a02-86f0-11e6-8f23-6ca088d9b911.png)
