### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1883]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)
## Issue Description:

This doc page is very Drupal focused
## Suggested Resolution

Research setting up SimpleSAMLphp with Wordpress and https://github.com/pantheon-systems/wp-saml-auth so that we have a solid public facing doc for Wordpress users on the same level as what we have for Drupal that is end-to-end comprehensive.

**Comment by rachelwhitton** [comment]
Include update for Drupal content to clarify symlink requirement (`/simplesaml` to `/private/simplesamlphp-1.11.x/www`). 

Reported in DSI-19

**Comment by pbuyle** [comment]
For Drupal, it seems that the symlink target is not a requirements (I've a working SimpleSAMLphp integration with Okta installed at a different path). But the path of the symlink has to be `/simplesaml`. It seems Pantheon has special handling for .php files under `/simplesaml` in order for SimpleSAMLphp to work.

**Comment by rachelwhitton** [comment]
Thanks for the insight @pbuyle! Much appreciated!

**Comment by pbuyle** [comment]
Also, we use SimpleSAMLphp 1.14.2 installed via Composer.

**Comment by alexfornuto** [comment]
@newtoid As with #1509, do you have any insight into this setup?

**Comment by alexfornuto** [comment]
Fixed previously: https://github.com/pantheon-systems/documentation/commit/73bad935b2e0c51c131c1a446c77ebb938e5d37c

**Comment by newtoid** [comment]
@alexfornuto investigating...
