### ISSUE TITLE
Backup Creation Doc Update

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1891]
Re: [Backup Creation](https://pantheon.io/docs/create-backups)
## Issue Description:

It would be great to add some wording around limitations and responsibility re backups. For instance, something like:

Pantheon does backups, but does not aim to be a full fledged backup solution. For mission critical backups it is highly recommended to store backups externally both for retention and redundancy purposes.
How to: (for instance) set up a script in a cron job externally that grabs the backups via Terminus, checks that the filesize looks sane (looks like the backup is complete and full and otherwise alerts appropriately), and stores the thing on for instance Amazon S3 (cheap).

Desk case: #72407
Jira feature request: #FEAT-255

**Comment by slashzero** [comment]
Happy to work on this - hit me up!

**Comment by nataliejeremy** [comment]
Great! @slashzero Think you'll have time this week?
