### ISSUE TITLE
Cloning an Existing Pantheon Site Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1892]
Re: [Cloning an Existing Pantheon Site](https://pantheon.io/docs/clone-site)
## Issue Description:
This guide doesn't come up in search results when I search for:
copy
clone
clone pantheon site
pantheon site
copy pantheon site
duplicate
duplicate pantheon
duplicate pantheon site
existing
existing pantheon site
etc....

## Suggested Resolution 
Can we do something so it comes up in search results somehow?

**Comment by nataliejeremy** [comment]
Thanks for letting us know @tinefin We'll take a look and get that fixed.

**Comment by rachelwhitton** [comment]
Suggest fixing this issue by adding keywords within contents of the page to improve search ranking. "Cloning" brings the page up in results because that keyword is in the title, but other keywords noted do not exist on the page.

**Comment by rachelwhitton** [comment]
Closed by #1920 - Now using Google's Custom Search Engine
