### ISSUE TITLE
Terminus, the Pantheon Command-Line Interface (CLI) Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#1893]
Re: [Terminus, the Pantheon Command-Line Interface (CLI)](https://pantheon.io/docs/terminus)
## Issue Description:
When searching for "Terminus" this page does not come up in search results. The "deprecated" version of it comes up as number 1 in the search, however..
http://screencast.com/t/AFqbKINGcT

## Suggested Resolution 
Could we fix it so this page comes up when searching for Terminus, preferably on top?

**Comment by rachelwhitton** [comment]
We should delete the deprecated page ([The Terminus Drush Extension (Deprecated)
 Contribute ](https://pantheon.io/docs/terminus-deprecated)). Any objections? cc @ari-gold @nataliejeremy

**Comment by nataliejeremy** [comment]
+1 Long overdue!
