### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update

### ISSUE THREAD

**Issue by danbohea** [pantheon-systems/documentation#1896]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/drush)
## Issue Description:

The docs here are very Drupal 7 orientated. E.g. "Registry rebuild" and `drush cc all`.
## Suggested Resolution

Update docs with separate Drupal 7 & Drupal 8 instructions & examples where applicable.

**Comment by alexfornuto** [comment]
In addition, this doc should be edited down to only include information relevant to using Drush on Pantheon specifically, leaving the documentation of Drush itself to Drush.
