### ISSUE TITLE
Using SendGrid To Deliver Email with WordPress and Drupal Doc Update 

### ISSUE THREAD

**Issue by kdmarks** [pantheon-systems/documentation#1910]
Re: [Using SendGrid To Deliver Email with WordPress and Drupal](https://pantheon.io/docs/guides/sendgrid)
## Suggested Resolution

**Comment by nataliejeremy** [comment]
@kdmarks Do you know what changed? I walked through the steps of creating a new account, went to Settings > Credentials, and it doesn't look like anything changed. Thanks for your help.
