### ISSUE TITLE
File scanning using clamav module for uploaded files

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#1913]
## Title

Scan your files using clamav before uploading them (needs better title ...)
## Description

We've recently seen a number of tickets (#73955, #73939) in which suspicious files have been uploaded via fields. These ended up in the files/ directory and have caused alerts in some cases, harming site SEO and credibility.

Modules such as ClamAV (https://www.drupal.org/project/clamav) or Upload Scanner https://wordpress.org/plugins/upload-scanner/ leverage the clamav binary installed on Pantheon to scan every file that's being uploaded. Although this would slow down the upload process, it would provide better security and would ultimately be a good practice for every site.
## Expected Audience

Site administrators, developers.
## Path

source/docs/articles/sites/clamav
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by alexfornuto** [comment]
@alexdicianu now that we have a new [Doc Template](https://github.com/pantheon-systems/documentation/blob/master/source/_docs/doc-template.md), do you wanna take a first pass at this doc?

**Comment by alexfornuto** [comment]
Whoever tackles this can look at #2780 for a rough outline.

**Comment by alexfornuto** [comment]
BUGS-1566
