### ISSUE TITLE
Security on the Pantheon Dashboard Dup Doc

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1933]
Re: [Security on the Pantheon Dashboard](https://pantheon.io/docs/security)
## Issue Description:

Duplicate docs  [Security on the Pantheon Dashboard](https://pantheon.io/docs/security) & [Locking Your Site](https://pantheon.io/docs/lock-environment)
## Suggested Resolution

Pick one, delete - add redirect on Live.

**Comment by eabquina** [comment]
Created pull request #2744 for the Security item update
Created pull request #2745 for the Lock... delete
How do we do the redirect?
