### ISSUE TITLE
Rename: Replace Links Referencing IP:PORT in Drupal

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1935]
Re: [Replace Links Referencing IP:PORT in Drupal](https://pantheon.io/docs/drupal-broken-links)
## Issue Description:

Title is a bit confusing.
## Suggested Resolution

Align with [Fix Broken Links in WordPress](https://pantheon.io/docs/wordpress-broken-links/)

 - [x] rename title in YML

**Comment by eabquina** [comment]
Could convert as a "Fix Broken Links in Drupal" where there are different 
Scenarios, in this case, scenario is about IP:PORT shows up.

For future "Broken Links" fix, can add additional scenarios in Hierarchy
