### ISSUE TITLE
Configuring wp-config.php Doc Update [low priority]

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#1942]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php)
## Issue Description:

This page seems to use a codeblock style that is inconsistent with other pages.
## Suggested Resolution

Update page with our modern codeblock style for consistency.

**Comment by alexfornuto** [comment]
I'm closing this issue. This guide will be updated along with the rest to match style conventions, once the new style guide is published.
