### ISSUE TITLE
The Pantheon Community and Power Users Group Doc Update 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#1946]
Re: [The Pantheon Community and Power Users Group](https://pantheon.io/docs/power-users)
## Issue Description:
There should be a link to the Slack channel on this page.

## Suggested Resolution 
I'll look it up later if someone else doesn't do it first.

**Comment by allenfear** [comment]
@greg-1-anderson that is actually already there in the first paragraph, but the fact that you didn't see it quickly makes we think we should edit the link text.

**Comment by greg-1-anderson** [comment]
Thanks @allenfear!
