### ISSUE TITLE
Patch available for GlobalRedirect

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#1972]
Re: https://pantheon.io/docs/unsupported-modules-plugins/#global-redirect
"I see on this page:
https://pantheon.io/docs/unsupported-modules-plugins/#global-redirect

that you are unaware of the patch that solves the home page redirect problem when the site is in maintenance mode.

Please see https://www.drupal.org/node/1399024#comment-8340647.

We patched the Numerix site with this patch today and successfully tested maintenance mode while "Frontpage Redirect Handler" was in use."

**Comment by rachelwhitton** [comment]
Closed by #1974
