### ISSUE TITLE
Session and Cookie Handling Doc Update

### ISSUE THREAD

**Issue by Jorenm** [pantheon-systems/documentation#1989]
Re: [Session and Cookie Handling](https://pantheon.io/docs/sessions-and-cookies)
## Issue Description:

This page makes no mention of prepending SESS and using only lowercase letters and numbers.

## Suggested Resolution 

Include the information on this page regarding session cookies: https://pantheon.io/docs/caching-advanced-topics/

**Comment by rachelwhitton** [comment]
+1 Thanks for opening this issue @Jorenm! Much appreciated
