### ISSUE TITLE
Rsync w/ Symlinks

### ISSUE THREAD

**Issue by timatron** [pantheon-systems/documentation#1993]
Re: https://github.com/pantheon-systems/documentation/blob/master/source/_docs/rsync-and-sftp.md#download-a-wordpress-file-from-pantheon

## Issue Description

Not sure if this is to a particular system or a particular age of a pantheon-system, but it seems that rsync w/ ssh is not following symlinks. ie 

ie in this example: 

$: export ENV=dev
$: export SITE=3ef6264e-51d9-43b9-a60b-6cc22c3129308as83
$: rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/wp-content/uploads ~/files

the symlink to :files is not working

## Suggested Resolution
$: export ENV=dev
$: export SITE=3ef6264e-51d9-43b9-a60b-6cc22c3129308as83
$: rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' $ENV.$SITE@appserver.$ENV.$SITE.drush.in:files ~/files

**Comment by alexfornuto** [comment]
@lauren-kelly is testing this under various scenarios.
