### ISSUE TITLE
New doc on debugging PHP 7 compatibility notices and errors

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2005]
Re: [BUGS-620](https://getpantheon.atlassian.net/browse/BUGS-620)

**Comment by greg-1-anderson** [comment]
On systems that utilize php opcache to boost performance (e.g. as Pantheon does), any php notices that are printed during class parsing will only occasionally be visible, as subsequent requests will use the cached result, and the notice will not be generated. Disabling opcache in settings.php makes this easier.

`ini_set("opcache.enable", 0);`

Example of php deprecation notice with opcache disabled:

![php-deprecated-constructor-no-opcache](https://cloud.githubusercontent.com/assets/612191/20778820/5ac470c4-b725-11e6-97e7-c37b356626d0.png)

Example of php deprecation notice with opcache enabled:

![php-deprecated-constructor-opcache](https://cloud.githubusercontent.com/assets/612191/20778819/5ac04b98-b725-11e6-9e26-d5fc1d77bc80.png)
