### ISSUE TITLE
Jan Changelog Candidates

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2015]
Add December platform changes and new features to be included in the Jan Changelog (sent out 1/1)

**Comment by rachelwhitton** [comment]
upgraded WP-CLI  from 0.24.1 to 1.0.0
https://getpantheon.atlassian.net/browse/IO-1702

**Comment by rachelwhitton** [comment]
WordPress 4.7 Update
https://pantheon.io/blog/wordpress-47-and-pantheon-advanced-page-cache

New Doc: https://pantheon.io/docs/wordpress-4.7-upgrade/

**Comment by ari-gold** [comment]
Drupal 7.53. Drupal 8.2.4

**Comment by ari-gold** [comment]
MIME type change:

application/octet-stream twbx; # added on 10/24/2014 

Unfortunately with recent changes, we've found this causes file recognition issues with a variety of Microsoft browsers (surprise!). Updated to

application/twbx twbx;
application/twb twb;.

**Comment by rachelwhitton** [comment]
[Privacy Shield Framework Compliance](https://pantheon.io/blog/announcing-privacy-shield-framework-compliance)

**Comment by rachelwhitton** [comment]
https://pantheon.io/blog/documentation-and-training-relaunch

**Comment by rachelwhitton** [comment]
security patch for WordPress 4.7 https://github.com/pantheon-systems/WordPress/pull/95
