### ISSUE TITLE
How to analyze CPU usage in New relic

### ISSUE THREAD

**Issue by fusionx1** [pantheon-systems/documentation#2022]
how to analyze CPU usage in New relic
## Issue Description
This client is running a load testing using loadrunner and they are too concerned about the cpu utilization when running the test. 

"We are using HP LoadRunner, 10 concurrent users for 25 min doing Login, navigate through 2 pages and Logout. Total transactions for each step is 3,400 throughout the test." - From Client

From New Relic it captures 118% cpu utilization and this why client is too concerned of this result, but as per @ari-gold theres nothing to be concerned with because the platform is on a multicore cpu.

See https://pantheon-systems.desk.com/agent/case/77635

**Comment by rachelwhitton** [comment]
Will work in #1851
