### ISSUE TITLE
Redirect Incoming Requests Doc Update

### ISSUE THREAD

**Issue by badjava** [pantheon-systems/documentation#2037]
Re: [Redirect Incoming Requests](https://pantheon.io/docs/redirects)
## Issue Description:

The code examples are wrong.

## Suggested Resolution 

When evaluating `$_SERVER['https']`, it should be 'on' and not 'ON'. This caused me way too long to debug as it never occurred to be that the actual code example could be wrong.

**Comment by rachelwhitton** [comment]
Thanks for reporting this issue @badjava! Much appreciated
