### ISSUE TITLE
Terminus Manual: Command Reference - Alpha Feedback

### ISSUE THREAD

**Issue by kevinhowbrook** [pantheon-systems/documentation#2038]
Re Alpha Doc: [Terminus Manual: Command Reference](https://terminusma-static-docs.pantheonsite.io/docs/terminus/commands)

remote:drush <site_env_id> [<drush_command>]...
drush

Should be:
remote:drush [site-name].[env] [drush_command] 

I tried editing the doc but it looks like there is js variables pulling in the commands

**Comment by rachelwhitton** [comment]
Hey @kevinhowbrook! Thanks for reporting. The docs are generated using the terminus help text, so the issue will need to be addressed there. pantheon-systems/terminus#1460 mentions it and we're tracking internally as well.
