### ISSUE TITLE
Improve Getting Support Doc

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2039]
## Title
How to best work with support

## Description
I would so love a guide on how to best work with support. Somethings like "help us to help you". 

## Outline
Things like:
- Please keep 1 ticket pr issue - no more, no less
- More issues pr ticket confuses the subject and makes it harder for us to assist and provide proper advice. CSEs also get confused!
- Many tickets / chats on the same issue ends with CSEs spending time trying to consolidate the scattered information between us, wasting time that could have been spent solving the issue.
More tickets != more/quicker support, quite the contrary!
- If opening a chat on an issue that already has a ticket, please let us know the ticket is there. Chat is currently a new product and we might miss the connection.
- Please add exact steps to reproduce the issue. We can only debug what we can see. Help us see what you see.
- Adding information on which environment, time, error message, screenshot, urls, etc is super helpful. Context is also necessary!
- If the site has an unusual configuration that means we cannot access login / edit pages etc as normal, add this information as well.
- This speeds things up: Stay responsive, help us by answering the questions we ask.
- Let us know if something doesn't make sense or we have misunderstood the issue. CSEs are highly aware of the importance to take note of every detail - but we're human too, it does happen we miss stuff.
- In general: Help us to help you!

## Expected Audience
Customers

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by newtoid** [comment]
+1 great idea, we could give an example of all the information needed by us in order to better assist

**Comment by ari-gold** [comment]
Might be good to update/combine following docs instead of creating YAD (yet another doc =)

https://pantheon.io/docs/getting-support/
https://pantheon.io/docs/scope-of-support/

**Comment by twooten** [comment]
This is really a great idea. Maybe place this after the "Ticket Support" section, but before the "FAQ" at https://pantheon.io/docs/getting-support/
