### ISSUE TITLE
Improve "Troubleshoot New Relic Access" section

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2049]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic)
## Issue Description:

Not easy to quickly find solution to problem

## Suggested Resolution 

Make it scenario based.
Show a heading of the error that someone will see
and then in body give clear instructions to get access.

e..g
# Clicking "Go to New Relic" button gives "You do not have permission to view this account"

1. Visit https://login.newrelic.com/logout
2. Refresh Pantheon site dashboard
3. Click "Go to New Relic"

Because different sites are linked to different New Relic accounts, you may need to logout of one account to get access to another. The New Relic SSO token expires after five minutes and refreshing the dashboard retrieves a new token.

**Comment by alexfornuto** [comment]
These concerns have been addressed through various PRs to the [toubleshooting](https://pantheon.io/docs/new-relic/#troubleshooting) section.
