### ISSUE TITLE
Getting Started with WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by hengkit** [pantheon-systems/documentation#2053]
Re: [Getting Started with WordPress Site Networks](https://pantheon.io/docs/create-wordpress-site-networks)
## Issue Description:

HTML fragments are showing on screen

## Suggested Resolution 

Don't show HTML fragments.
![screen shot 2016-12-21 at 3 14 57 pm](https://cloud.githubusercontent.com/assets/2086579/21409656/42d589b4-c790-11e6-95c4-194ac5a5261b.png)

**Comment by rachelwhitton** [comment]
Closed by f88fdef263dd2fb432e337680360b1cce805b635
