### ISSUE TITLE
Terminus Pancakes Plugin

### ISSUE THREAD

**Issue by uberhacker** [pantheon-systems/documentation#2071]
Re: Pantheon Plugin Directory
## Issue Description
Please add https://github.com/terminus-plugin-project/terminus-pancakes to the Pantheon Plugin Directory at https://pantheon.io/docs/terminus/plugins/directory/.
## Suggested Resolution
Plugin appears on the directory listing.

**Comment by rachelwhitton** [comment]
Added in #2098
