### ISSUE TITLE
New Doc: Pantheon Modules

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2082]
## Title
Pantheon Modules

## Description
Details on specific Drupal modules maintained and/or supported by Pantheon.

### Pantheon Maintained Drupal Modules

Drupal 8 Cache Backport

LCache

Search API Pantheon

Generate Errors

Site Audit

Panopoly

Drupal counterpart to [Pantheon Plugin](https://pantheon.io/docs/plugins) doc, include [projects supported by Pantheon's organization on drupal.org](https://www.drupal.org/pantheon).

**Comment by eabquina** [comment]
Could be merged with /docs/pantheon_api-module/ and be just /modules
Section for Drupal 7 and Drupal 8

Also, we have /docs/unsupported-modules-plugins/ 

Could be a good idea to create a new docs: /pantheon-modules-plugins that contain both WordPress and Drupal?
