### ISSUE TITLE
Contextualize when to use "Reset Dev Env to Live"

### ISSUE THREAD

**Issue by kimby77** [pantheon-systems/documentation#2083]
Re: Terminus Examples
https://pantheon.io/docs/terminus/examples/#reset-dev-environment-to-live

## Issue Description

`Reset Dev Environment to Live
Rewrite history and reset the entire Dev environment (codebase, files, and database) to the state of Live with Terminus.`

This particular example doesn't say why a user would want to do this, or when it's appropriate to do this.  

The other examples contextualize this more, such as Deploying Code:
`When you're ready to test a new set of changes, use Terminus to deploy code from development environments up to the Test environment while pulling the database and files down from Live`

@rachelwhitton, what do you think about giving this example more context?

**Comment by rachelwhitton** [comment]
+1
