### ISSUE TITLE
Git FAQs Doc Update

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#2084]
Re: [Git FAQs](https://pantheon.io/docs/git-faq/#why-am-i-being-prompted-for-my-password-after-adding-the-public-key?)
## Issue Description:
Review:

> Why am I being prompted for my password after adding the public key?
> This occurs when you have multiple SSH keys. For more information, see Permission Denied.
> 
> The easiest way to find out which SSH keys your Git client is using when trying to connect is to run the following command:

```
ssh -vT git@code.getpantheon.com
```

>The output should be similar to this:

```
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: Connecting to code.getpantheon.com [50.57.148.117] port 22.
debug1: Connection established.
debug1: identity file /home/username/.ssh/id_rsa type 1
```
>You should now be able to configure Git with the matching SSH key and clone your repository.

Just discussed this with a customer today and this part of the docs didn't seem to be up to date.

Here is my output running the command:

```
~ % ssh -vT git@code.getpantheon.com
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/dustinleblanc/.ssh/config
debug1: /Users/dustinleblanc/.ssh/config line 1: Applying options for *.getpantheon.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to code.getpantheon.com [50.57.148.117] port 22.
debug1: connect to address 50.57.148.117 port 22: Operation timed out
ssh: connect to host code.getpantheon.com port 22: Operation timed out
```

**Comment by rachelwhitton** [comment]
Shouldn't the output return successful authentication? Is `git@code.getpantheon.com` the correct host? Curious if operation timed out is expected behavior

**Comment by allenfear** [comment]
Added bug: https://getpantheon.atlassian.net/browse/BUGS-982

**Comment by rachelwhitton** [comment]
Use Terminus to identify host: 
```
terminus connection:info <site>.dev --fields=git_host
```
Then, test existing keys:

```
$ ssh -vT -p2222 codeserver.dev.<SITE_ID>.drush.in
OpenSSH_7.3p1, LibreSSL 2.4.1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: Connecting to codeserver.dev.<SITE_ID>.drush.in port 2222.
debug1: Connection established.
debug1: Offering RSA public key: /Users/username/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to appserver.dev.<SITE_ID>.drush.in:2222.
```
