### ISSUE TITLE
Apache Solr Note

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2103]
Re: [Apache Solr on Pantheon](https://pantheon.io/docs/solr)
## Issue Description:
[BUGS-979](https://getpantheon.atlassian.net/browse/BUGS-979)
## Resolution
Note: Re-indexing is required once platform incidents for Solr service degradation are resolved. Check the [status page](http://status.pantheon.io/) for current and past platform events.

**Comment by rachelwhitton** [comment]
Add link to [Check Index and Batch Sizes](https://pantheon.io/docs/solr/#apache-solr-vocabulary) and mention time outs.

**Comment by eabquina** [comment]
Submitted pull request- 2717 
https://github.com/pantheon-systems/documentation/pull/2717
