### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update : aliases

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#2118]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/drush)
## Issue Description:
[error] 'aliases' is not a registered command.

## Suggested Resolution 
It looks like this functionality was removed from Terminus (tested on 0.13.6 and 1.0.0-beta2).

**Comment by greg-1-anderson** [comment]
For Terminus 0.13.6, use `terminus sites aliases`.  I was able to use `terminus aliases` successfully on today's HEAD of master (Terminus 1.0.0).

**Comment by kyletaylored** [comment]
Ah, it looks like I had some kind of conflict with my versions of Terminus. `terminus aliases` is working on my 1.0.0-beta2 version now!

When I did run the command, it doesn't give me all the aliases that I can access through the dashboard. What are the limitations to Drush alias access?

**Comment by ilovelamp** [comment]
Could not reproduce.  

```
$ terminus aliases
 [notice] Aliases file written to ~/.drush/pantheon.aliases.drushrc.php.
```

Seemed to work for me. If you aren't seeing all the sites you have access to please open a support ticket for us.
