### ISSUE TITLE
Using Extensions That Assume Write Access Doc Update

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2125]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access)
## Issue Description:
We still get a fair few requests for help with this one (eg https://pantheon-systems.desk.com/agent/case/79783), would like to make sure everything is clear

**Comment by rachelwhitton** [comment]
@newtoid can you clarify what the issue is on this doc?

**Comment by newtoid** [comment]
@rachelwhitton yeah just want the instructions to be clear, and to consider a list of plugins that require this.
