### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2126]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins)
## Issue Description:
https://en-ca.wordpress.org/plugins/lj-maintenance-mode/ has a similar issue to global redirect, it allows to set the wp site to maintenance mode, certain themes redirect the front page and when these are active at the same time as lj-maintenance-mode, a redirect loop is caused which gives the appearance of the site being down

## Suggested Resolution 

Login at /wp-login.php and disable maintenance mode

**Comment by dustinleblanc** [comment]
@newtoid, do you have an example theme that exhibits the issue?
