### ISSUE TITLE
Local Development Doc Update: Needs settings.php / wp-config.php info

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#2136]
Re: [Local Development](https://pantheon.io/docs/local-development)
## Issue Description:
This guide does a great job explaining how to get code, database, and files locally that's not enough to get a user up and running. The last step is updating the database connection info in settings.php (Drupal) or wp-config.php (WordPress).

## Suggested Resolution 
Include information near the bottom about updating settings.php and wp-config.php. We could provide instructions on this doc, but we'd be duplicating work from https://pantheon.io/docs/settings-php/ and https://pantheon.io/docs/wp-config-php/. Perhaps we could just provide a section at the bottom where we explain what's left and link to these resources? I can make a change once someone else considers the best course of action.

**Comment by alexfornuto** [comment]
These concerns have been addressed in a new section, [here](https://pantheon.io/docs/local-development/#local-configuration-files)
