### ISSUE TITLE
Use the Pantheon Workflow Doc Update

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2143]
Re: [Use the Pantheon Workflow](https://pantheon.io/docs/pantheon-workflow)
## Issue Description:
New User confused on the workflow

## Suggested Resolution 

* Highlight that on your deploy to Test, you'll be asked if you want to clone the DB down from Live
* Provide link to the Dashboard docs: https://pantheon.io/docs/sites/ for cloning when NOT deploying to Test
* Be more clear about links to working via SFTP: https://pantheon.io/docs/sftp/  that this doc ties together the information about working on Dev with working within your Application on Dev
* Be more clear that the idea behind this is to keep the Live site as stable as possible and prevent untested code from going out to Live and potentially breaking it

**Comment by newtoid** [comment]
I think that cloning files is ambiguous to certain levels of user, and that the term "files" can be understood to mean lots of things. Cloning and Deploying are a stumbling block for these users because it essentially seems like the same thing.
