### ISSUE TITLE
Feb Changelog Candidates

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2144]
Add January platform changes and new features to be included in the Feb Changelog (sent out 2/1)

**Comment by rachelwhitton** [comment]
WordPress 4.7.2 

Terminus 1.0.0

**Comment by rachelwhitton** [comment]
Share 1.0 plugin dir, callout most popular: https://pantheon.io/docs/terminus/plugins/directory/

**Comment by ari-gold** [comment]
Drupal 8.2.5

**Comment by ari-gold** [comment]
https://status.pantheon.io/incidents/xb3w9xc5fdgp
