### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2150]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins)
## Issue Description:
Add relevant twig module issue, as discussed in CSE orientation by Omar.

**Comment by obicke** [comment]
The Twig Extensions module (https://www.drupal.org/project/twig_extensions) for Drupal 8 uses php-intl, which is not currently supported by Pantheon. A feature requests exists for enabling this (FEAT-165), but in the meantime, this module should probably be added to the list of modules with known issues.
