### ISSUE TITLE
Clarify volume of content/data for Redis caching strategies A vs. B

### ISSUE THREAD

**Issue by ccharlton** [pantheon-systems/documentation#2171]
## Title
The Redis doc mentions two configuration options, "Option A: Higher performance for smaller page counts.” & "Option B: Higher hit rate for larger page counts.”

## Description
Would love to see some clarification in that doc about what is "larger page counts", some unit of measurement.

Josh Koenig replied with, "the honest answer is based on the size of your average HTML page / available redis size based on service level (edited). e.g. if all your pages cached will fit in your Redis, that’s a no-brainer. probably; it’s not like the performance for the DB page cache is *bad*. if you have a lot of infrequently viewed content, I’d go with that option [B]."

## Path
https://pantheon.io/docs/redis/

**Comment by rachelwhitton** [comment]
Thanks for opening this issue @ccharlton - much appreciated! #1767 will address this doc so we'll track changes there. I do agree we should provide some context around the page counts if the two options persist.
