### ISSUE TITLE
Locking Your Site Doc Update

### ISSUE THREAD

**Issue by quickdraw6906** [pantheon-systems/documentation#2174]
Re: [Locking Your Site](https://pantheon.io/docs/lock-environment)
## Issue Description:
The following callout box on the above page is missing a very key detail:
"Note
The HTTP Basic Authentication core module (Drupal 8) and Basic HTTP Authentication contrib module (Drupal 7) conflict with Pantheon's Security tool when both are enabled. We recommend using Pantheon's Security tool or the module to restrict access to Pantheon environment URLs, not both."

The issue is that for new users, it is impossible to find the resolution to the conflict that occurs when both authentication schemes are turned on. In Drupal 8, there is no way using the UI to disable the core auth module. You have to use drush, which for Pantheon environments, also means using Terminus. 

## Suggested Resolution 
Reference the need to turn off the respective Drupal auth module when locking a Pantheon environment. Explain the need to use Terminus (with a link to doc about setting up and using Terminus) to use Drush to turn off the auth module and provide a link to a page that describes the step you need to take:
terminus drush $SITE.dev -- pmu basic_auth

**Comment by rachelwhitton** [comment]
Thanks for creating this issue @quickdraw6906! I spun up a new Drupal 8 site to test this out and found that I had to unlock the environment and clear cache in the Site Dashboard to resolve the 403 errors first. Then I was able to disable the module in the UI and lock the environment with Pantheon's security tool. I'll add some clarification to the docs for this, thanks!
