### ISSUE TITLE
Emoji support on Pantheon

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#2175]
## Description
Outline emoji support for various framework/CMS on the platform, how they differ, and why Pantheon is configured in the way that it is.

## Outline

* Intro
* Drupal 7 Support - no
  * why
  * workaround to get rid of PDO errors: https://www.drupal.org/project/strip_utf8mb4
* Drupal 8 Support - yes
* Wordpress Support - yes
* How to enable if needed

## Expected Audience
All developers looking to use Emoji in site databases.

## Path
not sure.

**Comment by hugovk** [comment]
Please could you give a bit more info about why Pantheon doesn't support emoji for Drupal 7?

Perhaps because my.cnf cannot be edited? https://www.jeffgeerling.com/blog/2016/getting-emoji-and-multibyte-characters-on-your-drupal-7-site-750

Thank you!

**Comment by dustinleblanc** [comment]
From the original issue report, I've sussed this out:

We can't reliably alter a Drupal 7 site to allow support for emojis. All of our Drupal 7 sites use the same MySQL settings and altering the setup for all sites on the platform could break thousands of sites.
