### ISSUE TITLE
Add guide for Drupal 8 development workflow using Terminus

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#2179]
Re: A Drupal version of [Use the Command Line to Create a WordPress Site Using Terminus and WP-CLI](https://pantheon.io/docs/guides/wordpress-commandline/)

## Issue Description

I'm working on formalizing our Terminus training for Fast Track/Jump Start. As part of that work I went back to an outline I used at in-person trainings for some Drupal Camps last year. https://github.com/stevector/d8trainingtheme/blob/d8ca09230f661673aea4015fd05bfc414a09cce1/README.md#2pm---3pm-terminus-the-pantheon-command-line-tool The outline shows how to do basic Drupal 8 workflow tasks like exporting/deploying config all with Terminus.

## Suggested Resolution

I think it'll be valuable for me to update this outline for Terminus 1.0 and put it on the docs site.

**Comment by greg-1-anderson** [comment]
I am also planning on writing a guide on the GitHub PR workflow with https://github.com/pantheon-systems/example-drops-8-composer. This workflow also uses Terminus, although the procedure is somewhat different than what is shown in your outline.

Not sure if this should be the same thing, or if there should perhaps be a section containing different guides with different Pantheon workflows.

**Comment by stevector** [comment]
@greg-1-anderson, I think those would be two different guides. This guide wouldn't be an introduction that assumes (1) a person is running all of the commands and (2) they are interacting with Pantheon directly rather than an external repo.
