### ISSUE TITLE
Rename Solr for Drupal guide.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2183]
Re: <https://pantheon.io/docs/solr-drupal/>
## Issue Description
We currently have one guide named "Enabling Solr with Drupal" which sounds like it covers all of Drupal, and one named "Enabling Solr on Drupal 8", which clearly covers only 8

## Suggested Resolution
Identify which versions of Drupal the first guide applies to and specify it in the title, and in links it from other docs.

**Comment by eabquina** [comment]
Original docs seems to be all created for Drupal 7, none here is for D8, can rename file to solr-drupal-7

solr-drupal-8 could actually need update for screenshots and a better outline for steps. Could create another Issue for Drupal 8 version
