### ISSUE TITLE
Enable Secure HTTPS Communication Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2186]
Re: [Enable Secure HTTPS Communication](https://pantheon.io/docs/enable-https)
## Issue Description:
Test with Chrome instructions out-of-date

## Suggested Resolution 

Developer Tools -> Security -> View Certificate

**Comment by alexfornuto** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134275-243506170_5-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by alexfornuto** [comment]
@ari-gold How's [this](https://github.com/pantheon-systems/documentation/pull/2198) for a resolution, eh?
