### ISSUE TITLE
HTTPS Cert Formatting

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2191]
Re: [Enable Secure HTTPS Communication](https://pantheon.io/docs/enable-https/)
## Issue Description
As described in bug 1030, customers may include additional SSL cert/key formatting not accepted by the dashboard. 

## Suggested Resolution
Specify what formatting is (and more importantly isn't) allowed around SSL certs and keys.

**Comment by garydylina** [comment]
Adding BUGS-1109 to the list of Bugs that would benefit from this clarification.

**Comment by alexfornuto** [comment]
Resolved by #2219
