### ISSUE TITLE
Domain Masking with Fastly and Pantheon out of date

### ISSUE THREAD

**Issue by gaylin** [pantheon-systems/documentation#2194]
Re: https://pantheon.io/docs/fastly-domain/#fastly-setup

## Issue Description

Fastly's web interface defaulted to new formats last fall. The information in the Fastly Setup portion of the [Domain Masking with Fastly and Pantheon](https://pantheon.io/docs/fastly-domain/#fastly-setup) guide is considerably out of date.

## Suggested Resolution

Update the steps to reflect the new web interface controls, including the new order in which those controls are accessed (things have moved around a small bit).

**Comment by dustinleblanc** [comment]
https://docs.fastly.com/guides/performance-tuning/generating-http-redirects-at-the-edge

Customer found this Fastly doc which looks like what we'll need to reference to get this working. Thanks for attention to the issue @gaylin!
