### ISSUE TITLE
Terminus Manual Doc Update

### ISSUE THREAD

**Issue by aangelinsf** [pantheon-systems/documentation#2197]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/examples)

Priority (Low‚ Medium‚ High): medium

## Issue Description:
-- is not explained anywhere

## Suggested Resolution 
Please explain what this flag does.

**Comment by greg-1-anderson** [comment]
Not sure where this should go in the Terminus manual, but here's an explanation:

`--`, or "double-dash" signifies the end of the Terminus options. Everything that comes after the double-dash is interpreted as positional parameters (arguments). This pattern is common in Unix commandline tools.

Terminus example:

`terminus drush site.env -- pm-enable rules --yes`

Without the `--` in the example above, the `--yes` option would be interpreted as a Terminus option. With the `--`, the `--yes` is passed to Drush.

Unix example:

`grep -- -v file.txt`

With the `--`, the `-v` is interpreted as the string to search for in `file.txt`. Without the `--`, the `-v` would be interpreted as the "verbose" flag, and grep would search for the string `file.txt` from its standard input.

**Comment by aangelinsf** [comment]
Thank you, just what I was looking for.
