### ISSUE TITLE
Enable Secure HTTPS Communication Doc Update

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#2200]
Re: [Enable Secure HTTPS Communication](https://pantheon.io/docs/enable-https/#ssl-certificate-types)

Priority (Low):

## Issue Description:
The SSL Certificate Types section is wrong and needs redoing.

## Suggested Resolution 
There are actually 3 types of certificates: DV (Domain Validated), OV (Organization Validated) and EV (Extended Validation)

SAN is just an extension to the certificate that binds multiple identities (e.g. domain names) to the certificate.

Wildcard domains are just a way for you to validate multiple subdomain in one line. Wildcards are usually added in the SAN field but do not represent a type of certificate. AFAIK you can't add wildcard domains to EV certs.

**Comment by alexdicianu** [comment]
Some documentation:
https://www.symantec.com/connect/blogs/types-ssl-certificates-choose-right-one
https://www.digicert.com/wildcard-ssl-certificates.htm
https://www.digicert.com/subject-alternative-name.htm

**Comment by alexfornuto** [comment]
I'm closing this issue, as these concerns will be addressed as part of larger changes coming to this doc.
