### ISSUE TITLE
New Relic APM Pro Doc Update

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2223]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/#new-relic-access)

Priority (Low):

## Issue Description:
Access solutions are not clear and/or missing

## Suggested Resolution 
This is from a recent ticket (81584) -- 
There are typically two errors we see:

1. When you go to New Relic, you see "You do not have permission to view this account"
When you see this:
- In New Relic, click on your user name on the right
- In the dropdown, select Log Out
- Back in the Pantheon Dashboard, click the **Go to New Relic** button.

2. When you go to New Relic, you are asked to log in
For this, you'll want to do the following:
- Close all New Relic tabs
- Delete New Relic cookies
- Reload your Pantheon Dashboard
- Click the **Go to New Relic** button on the Pantheon Dashboard

**Comment by alexfornuto** [comment]
@lauren-kelly I believe you addressed these issues in an unlinked PR. Would you agree that [this section](https://pantheon.io/docs/new-relic/#new-relic-access) now addresses these concerns?

**Comment by lauren-kelly** [comment]
@alexfornuto  yeppers  :+1:
