### ISSUE TITLE
Cron for Drupal Doc is confusing

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/documentation#2233]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:

This page is confusing. The following statements are made.

> Pantheon internally invokes drush pantheon_cron 3600.
> This bootstraps your site and invokes drupal_cron_run.

> Pantheon's system cron cannot be disabled and will run Drupal cron every hour, even if cron is disabled in Drupal.
> In Drupal, setting the value to "Never" will be ignored; system cron will always run at least hourly.

> Can I prevent Drupal Cron from running?

> Yes, from within Drupal at admin/system/config/cron, select Never from the "Run cron every" drop-down menu, then save the configuration. However, Pantheon system cron will run every hour and there is no way to disable it. 

## Suggested Resolution 

Explain the difference between Pantheon's internal cron and exactly what is does. How is it different from regular Drupal Cron?

**Comment by eabquina** [comment]
Marking and accepted

**Comment by eabquina** [comment]
Suggest to combine as a single paragraph and highlight the drush command as an internal platform trigger; 

>Pantheon Cron Execution
>For every site environment, Pantheon executes cron once an hour to allow Drupal to perform any scheduled tasks. The run is generally within 5 to 10 minutes of half past each hour: 4:30pm, 5:30pm, 6:30pm, etc.
>For other sites, cron is triggered via a browser/page request or crontab. 
>In the Pantheon platform, cron is triggered by a drush command:
>*drush pantheon_cron 3600*
>Technically, the command bootstraps your site and invoke drupal_cron_run, which is just like how normal Drupal cron runs. 


For "Can I prevent Drupal Cron from running?", could move this above Troubleshooting and combine with disable Pantheon's cron disable comment, and after Managing Cron section

>Disabling Cron
>You can disable Drupal cron via /admin/system/config/cron. Select "Never" from the drop-down menu, away from "Run cron every *"

>Pantheon's system cron cannot be disabled and will run Drupal cron every hour, even if cron is disabled in Drupal. Using a module like Elysia Cron will allow more granular control of what happens when Drupal cron runs.
