### ISSUE TITLE
Doc Requested: Monitor Site Availability with New Relic

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2235]
Re: https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/add-edit-monitors
## Issue Description
Documentation for Pantheon users on how to create monitors as described in the link above.

**Comment by rachelwhitton** [comment]
Add a new section to the existing new relic doc that encourages users to take advantage of synthetic lite availability monitoring, mentioning that it's free. Keep the troubleshooting steps at the bottom where they are for users that enable the bundled service and experience false positives. No content planned for upgrading new relic to a paid service plan (for now).

**Comment by alexfornuto** [comment]
#2258
