### ISSUE TITLE
New Relic APM Pro Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2236]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
Add content to explain why a user may see no data to report.
## Suggested Resolution 
Document that if a container is not receiving requests, there will not be response times to measure. Inactive containers will show no data.

**Comment by alexfornuto** [comment]
@rachelwhitton I'm closing this as resolved by #2401. If you think there's additional information still needed, we can open it back up and discuss.
