### ISSUE TITLE
Remove mention of www-redirection service

### ISSUE THREAD

**Issue by ilovelamp** [pantheon-systems/documentation#2243]
Re: https://pantheon.io/docs/domains/#serving-sites-from-www

## Issue Description

> **Pantheon's www-redirection service will automatically redirect requests to the www subdomain for sites served with HTTP.**

## Suggested Resolution

Remove or update **bolded sentence** above as we do not automatically redirect HTTP requests to "www."  

The user is expected to configure a [redirect to a common domain](https://pantheon.io/docs/redirects/#redirect-to-a-common-domain) on their own (to bare domain or www)

**Comment by rachelwhitton** [comment]
Closed by #2221
