### ISSUE TITLE
Cloning an Existing Pantheon Site Doc Update

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#2246]
Re: [Cloning an Existing Pantheon Site](https://pantheon.io/docs/clone-site)

Priority (Low‚ Medium‚ High): Low

## Issue Description:

Clearer definition for naming the archive file with --- <RANDOM_HASH>

`terminus drush <site>.<env> -- ard --destination=code/sites/default/files/<RANDOM_HASH>.tgz`

## Suggested Resolution 

Add a note what Random Hash is and why it is recommended.

**Comment by alexfornuto** [comment]
@rubelyn I did one better, and replaced `RANDOM_HASH` with a common date format, and explained why. I hope you like this resolution, if not let me know.

**Comment by greg-1-anderson** [comment]
@alexfornuto I didn't see your PR, and the published page still mentions `RANDOM_HASH`. Replacing a random hash with a predictable date format is probably a bad idea from a security standpoint. If someone suspected that a site migration was in progress, they could try downloading different well-known filename patterns, stepping through recent date patterns in the recent past. An archive dump contains hashed passwords and other sensitive information that should not be leaked.

Along these lines, this document should probably be updated to advise the prompt removal of the archive from the files directory. If someone performs multiple serial migrations (common), and they forget to remove the previous archive dumps (I've done it), they can a) inadvertently migrate the older archives to the new site, and/or b) create an archive dump that contains so many old archive dumps that it becomes larger than allowed, causing the export or the migration to fail.

Users should therefore be prepared to delete the archive dump from the source system's files directory as soon as the migration into the new system completes.

**Comment by alexfornuto** [comment]
@greg-1-anderson thanks for the input! The PR isn't merged yet, so that's good time. I'll take another pass on it based on what you said, and ask you to take a look when I'm done.

**Comment by alexfornuto** [comment]
@greg-1-anderson the [PR](https://github.com/pantheon-systems/documentation/pull/2365) has been updated, awaiting your review. Thanks!
