### ISSUE TITLE
Implement Feedback on Load and Performance doc

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2251]
Re: #2140  
## Issue Description
First iteration of refactoring this doc has been deployed but there are loads of helpful comments and suggestions we need to circle back and implement. 
## Suggested Resolution
See related PR and work with EOMs to add the suggested changes.

**Comment by alexfornuto** [comment]
Re-opening as there are still some outstanding comments left to be addressed.

**Comment by erik-pantheon** [comment]
I'll take a look at it. :)

**Comment by alexfornuto** [comment]
The discussion in #2140 points to EOM as the best source for answers to the outstanding questions from Ari's feedback. I've reached out to @erik-pantheon to confirm if he's still reviewing, but until I hear back I would say this is open to any other SME interested.

cc @lauren-kelly @JessiFischer @adamedgmond @bentekwork
