### ISSUE TITLE
Log Files on Pantheon Doc Update - logs retention policy

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#2256]
Re: [Log Files on Pantheon](https://pantheon.io/docs/logs)

Priority (Low‚ Medium‚ High): Low

## Issue Description:

Retention Policy for nginx-access.log is confusing. When an application server is migrated to a new endpoint, logs will not be retained. We routinely migrate containers for maintenance. 

Problem: Customers are expecting they can access the logs for the past 60 days. See: BUGS-1142

## Suggested Resolution 

- Change the "Retention Policy" to "Maximum Retention Policy" as suggested by Nick

**Comment by alexfornuto** [comment]
@rubelyn the table that gives the 60 day window also says:

> Do not consider canonical, as this will be wiped if the application server is reset or rebuilt.

Does this not address properly, or fully, the idea that the logs could be wiped when a container is migrated?

**Comment by rubelyn** [comment]
@alexfornuto Is there a way we can we highlight that line? Customers tend to skip reading the "Comments" column.
