### ISSUE TITLE
Bots and Indexing on Pantheon Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2263]
Re: [Bots and Indexing on Pantheon](https://pantheon.io/docs/bots-and-indexing/#google-results-for-my-site-link-to-https-using-pantheon's-shared-certificate)

Priority (Low‚ Medium‚ High): High (large support impact)

Provide code snippets for D7/D8/WP that demonstrates how to check for offending HTTPS responses and add `X-Robots-Tag: noindex`

**Comment by rachelwhitton** [comment]
> The equivalent in drupal 7 would be drupal_add_http_header() which could be done in some eary page bootstrap

**Comment by JessiFischer** [comment]
@rachelwhitton Reviewing this card and not entirely sure what's being requested here. Could you provide a bit more color? Like.... An entirely new troubleshooting section? Is this just looking for a way to deal with mixed mode warnings in browsers? Or stopping google bots from indexing any https pages?

**Comment by rachelwhitton** [comment]
@JessiFischer this was originally reported by CSE I believe.. though I can't remember who/what/why.. 

From what I can remember, it's related to this existing troubleshooting section: https://pantheon.io/docs/bots-and-indexing/#google-results-for-my-site-link-to-https-using-pantheons-shared-certificate

specifically the last bullet: 
> Add the X-Robots-Tag: noindex header to responses resulting from HTTPS requests. Note that this will not fix existing indexed results from Google, and is a preventative solution rather than a reactionary, for users who don't want to serve over HTTPS.

Do you think this is valid/useful? We can close if you determine it's no longer relevant
