### ISSUE TITLE
Desk Doc on Issue

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2265]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High): Low

## Issue Description:
Provide further instruction or examples of how to include a local settings.php file for drupal. In this case the example was for teams where each member would have a different db connection locally. 
## Suggested Resolution

**Comment by rachelwhitton** [comment]
@newtoid does the content here provide that already: https://pantheon.io/docs/settings-php/#local-database-configuration-for-development

**Comment by alexfornuto** [comment]
Closed by #2549
