### ISSUE TITLE
WP images with large dimensions can fail

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#2268]
@pantheon-systems/cse
Priority (Medium):

## Issue Description:
What ended up working was to swap out the image library used by WordPress to create thumbnails. We've found a few references to this issue and it's being tracked as a core bug in WordPress since 4.4. It only affects larger images (seems like over 2000px or more).

We found it odd that only one client installation would have this issue, but it's possible there are others that simply haven't uploaded images of this size.

Anyway, the fix was to swap to using the older Imagick library:
function change_graphic_lib($array) {
+	return array( 'WP_Image_Editor_GD', 'WP_Image_Editor_Imagick

See: BUGS-458 for historical data.

## Suggested Resolution

**Comment by rachelwhitton** [comment]
+1 Add to WordPress Known Issues and link to core bug: https://core.trac.wordpress.org/ticket/36534

**Comment by alexfornuto** [comment]
This was resolved in https://github.com/pantheon-systems/documentation/pull/2293
