### ISSUE TITLE
Desk Doc on Issue: Cloudflare's Recommended DNS in the Domains Doc

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2269]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High): Low

## Issue Description:
Is it possible to make the cloudflare setup more evident in docs? The guide is pretty clear but maybe elsewhere, I dont think this case is specific to the Cloudflare Partner Portal.

## Suggested Resolution 
More clear assertion of cloudflare config?

**Comment by alexfornuto** [comment]
What do you mean by "more evident"?

**Comment by newtoid** [comment]
with requests for cloudflare config assistance we inevitably find A and CNAME records were used, so I am thinking we need to make it clearer somehow that CNAMES only are to be used if the site has https off, and A records if https is on

**Comment by rachelwhitton** [comment]
+1 This page says if you're going to use CloudFlare's universal SSL - configure DNS as described here - which may be why folks are coming to support with A + CNAME records: https://pantheon.io/docs/domains/ 
Recommend updating doc to say CNAME flatenning is required for CloudFlare's free ssl and removing the recommendation to configure dns as described.

**Comment by rachelwhitton** [comment]
Closing, should be handled in #2631
