### ISSUE TITLE
Undo Git Commits Doc Update - sync Test and Live to Dev

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2279]
Re: [Undo Git Commits](https://pantheon.io/docs/undo-commits)

Priority (Low‚ Medium‚ High): Medium - I see several requests for this each week

## Issue Description:
We do not provide instructions for syncing Test & Live to Dev after a **git reset** 

## Suggested Resolution 
Test and Live are now ahead of Dev, and will remain there until another commit is made to Dev, to bring it ahead of them. If this is needed sooner than work will be completed, they can just make a 'dummy' commit - add a space or line to a file or edit a comment, etc - something that won't actually affect their code.
At that point they'll see that new commit on Test, instead of the old ones.

**Comment by alexfornuto** [comment]
Resolved in 45050eef800d4d57e06ee2af89b1f070dca560eb
