### ISSUE TITLE
Redis-WordPress Troubleshooting

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2304]
Re: https://pantheon.io/docs/wordpress-redis/
## Issue Description
Doesn't include useful troubleshooting information in main redis guide.
## Suggested Resolution
Duplicate information or link to main redis troubleshooting.

**Comment by alexfornuto** [comment]
[this](https://pantheon.io/docs/redis/#redis-is-enabled-but-there-is-no-data) section could be clarified, and the code example restructured.

**Comment by ttrowell** [comment]
The FAQ section could be copied over verbatim from the Drupal version (formerly main page) to the WP Redis doc IMHO.
