### ISSUE TITLE
Deploying during backups

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2310]
Re: /docs/backups
## Issue Description
Document strategies for continuing work during long running workflows

From feedback:

"When a backup is running, can I then deploy code? For example DB / Code is backed up, but Files are still being generated 35 minutes later...

I'm backing up live. If the files is still ongoing, can I then deploy from test to live without breaking things?"

**Comment by alexfornuto** [comment]
Should document where repo size and file inclusion is discussed that larger repos will affect backup time.

**Comment by tinefin** [comment]
*Backup time*
Pantheon filesystem (Valhalla) is very different than a normal filesystem. Extended backup time should be expected if the static files directory is on the large side. This is a really good resource for more information about Valhalla: https://pantheon.io/blog/inside-pantheon-valhalla-filesystem

Large file repositories might be better suited to be stored at a CDN:
https://pantheon.io/docs/content-delivery-network/

Using a CDN also helps page load time, as the page assets will origin from different urls. Most browsers have a set maximum for how many requests pr domain that will be executed simultaneously.

*What is safe to execute during backups*
_I don't think it is visible to customers how far the backup is / which steps has been executed / which are still running? (files, db, code). So I am not sure the main question makes sense here for anyone other than CSE, who have visibility into this through the logs?_

But, to answer the question:
It is usually safe to do non-static files related tasks even though the files are being backed up. This would include database clones, code deploys.

*Stuck workflows*
_Most relevant for CSE as they can see the Jenkins logs and will be able to tell whether something is stuck - or merely taking a long time (like a files backup)._

Sometimes a workflow will be "stuck". These jobs usually go away by themselves at some point in time. It is usually safe to lodge a new job of the same kind, usually it is not necessary to wait.

*Database backups / clones*
Be mindful that when creating a new multidev, cloning live database to dev or test - or any other operation that copies the LIVE database - this will run on the LIVE database. On busy sites this should be avoided during peak traffic, especially on sites that have large databases, as it can potentially impact performance significantly.

*Restoring backups*
This can take a long time, especially on sites that have large databases or static files directory. _Often it is not necessary to restore the files directory, in these cases it might be faster to restore code and database manually. It will only be faster if the customer feels comfortable doing so, of course.._

**Comment by tinefin** [comment]
*I'm backing up live. If the files is still ongoing, can I then deploy from test to live without breaking things?*

So - first of all: how would the customer actually know that it is only the files that are still ongoing? AFAIK customers have no visibility into this. And if they are still backing up code / DB, then they might very likely break things.

If for some reason they are sure it is only files backup that is still ongoing (i.e. a CSE told them so), then yes, they can deploy their code, provided the code doesn't alter something in the files directory.. But really, I would rather not document this part customer facing, as they have no visibility into backup progress and we really don't want them backing up their LIVE DB as well as running DB updates as well as serving LIVE traffic. Yes, they will go down.

In general - this whole question kinda assumes that customer has visibility into backup progress, which I find confusing. Why are we documenting something they customers cannot see? I might be missing something and they DO have visibility of course..

**Comment by alexfornuto** [comment]
Yes, visibility exists.
![screen shot 2017-04-25 at 3 35 02 pm](https://cloud.githubusercontent.com/assets/2349184/25404296/5be9cb50-29cd-11e7-9cb6-ef08439ea21b.png)
