### ISSUE TITLE
April/May Changelog Candidates.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2315]
Add April platform changes and new features to be included in the April/May Changelog.

**Comment by alexfornuto** [comment]
https://github.com/pantheon-systems/drops-8/commit/bf3942e37ce2d9ce0d9646b3a538b03bc8076c01

**Comment by greg-1-anderson** [comment]
https://github.com/pantheon-systems/WordPress/pull/112

**Comment by alexfornuto** [comment]
Closed by #2433
