### ISSUE TITLE
WIP - Doc on how to install terminus on Windows 7

### ISSUE THREAD

**Issue by fusionx1** [pantheon-systems/documentation#2327]
Priority: Low

## Title
How to install Terminus on Windows 7

## Description
Prepared my draft here - https://docs.google.com/document/d/1pBF6XtZpRTOl2ar7onFlH5aXRkQ70K-e771uksdHl1M/edit

Most customers that I encountered with that are windows  are not so familiar with linux environment the steps or instruction on how to install terminus should be detailed and visually engaging.

## Expected Audience
Windows users

## Path
docs/terminus/windows7

**Comment by rachelwhitton** [comment]
#2335
