### ISSUE TITLE
Upgrade PHP Versions Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#2336]
Priority (Low‚ Medium‚ High): Low

## Issue Description: 

The pantheon.yml file can also be created/modified via SFTP. This doc assumes Users are using GIt. This confuses first-time FTP Users. Doc is asking them to run  "git push".

## Suggested Resolution 

Add a Section for SFTP method.

**Comment by alexfornuto** [comment]
@rubelyn which doc? You didn't specify or link.

**Comment by rubelyn** [comment]
Hi @alexfornuto,

Sorry,  I'm referring to this doc - https://pantheon.io/docs/php-versions.

See this section -https://pantheon.io/docs/php-versions/#verify-changes.

Customers often ask why or where they should run "git push" command. It is not available in SFTP mode.

Thanks!
