### ISSUE TITLE
Update Enabling Solr for WordPress

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/documentation#2340]
Re: <https://pantheon.io/docs/wordpress-solr/>
## Issue Description
There also needs to be clearer documentation on how uploading and reposting a custom schema works. 
## Suggested Resolution
Add information on the following:
- Add note that custom schema.xml must be uploaded via SFTP, Terminus, or a Symlink and the respective process for each. In the case of SFTP schema.xml should be uploaded to `/files/solr-for-wordpress-on-pantheon/` directory not `/wp-content/solr-for-wordpress-on-pantheon/`

**Comment by alexfornuto** [comment]
Hi @mindofjonas,

Thanks for the suggestion? Can you clarify what you mean by "changed midstream"? We're a bit puzzled by that over here.

**Comment by mindofjonas** [comment]
Sorry about that, that "changed midstream" note was a related to another (non-pantheon related) issue. Removed

**Comment by alexfornuto** [comment]
Thanks for clarifying! I'm looking into this now, and I hope to have a PR today that should resolve your concerns.

**Comment by alexfornuto** [comment]
@mindofjonas I was able to upload a custom `schema.xml` as defined by the docs. Base on your initial issue comment, it looks like you may have missed the `uploads` part of the path. In either case, I will add information for both:

 - How the plugin uploads the schema to Solr
 - The need to upload to each environment separately.

**Comment by mindofjonas** [comment]
@alexfornuto thanks for looking into that. I had meant `/wp-content/uploads/solr-for-wordpress-on-pantheon/`. The docs refer to uploading the schema.xml to that path but Pantheon does not allow files in `wp-content/uploads/` when connecting to an environment with git. When connecting via SFTP the correct directory structure to upload the file is `files/solr-for-wordpress-on-pantheon/`

**Comment by alexfornuto** [comment]
@mindofjonas the path `/wp-content/uploads/` is a symlink to `/files/`, so it's also accessible in SFTP mode.

**Comment by mindofjonas** [comment]
Correct. But the Solr documentation doesn't note that `wp-content/uploads/` is symlinked to `/files/`. At the very least it'd be helpful to include a link to the [Pantheon Filesystem docs](https://pantheon.io/docs/files/) with a note about the file paths

**Comment by alexfornuto** [comment]
Our Solr plugin's project docs don't seem to mention the files path at all. The only reference I found to either was in an inline comment:

```
// Let's check for a custom Schema.xml. It MUST be located in
// wp-content/uploads/solr-for-wordpress-on-pantheon/schema.xml
```

I updated my PR to specify SFTP, but I'm worried that bringing up the symlink here add unnecessary complexity to the doc.

**Comment by mindofjonas** [comment]
I think mentioning SFTP should be enough to point users in the right direction.
