### ISSUE TITLE
Early Access: Free and Automated HTTPS Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2344]
Re: [Early Access: Free and Automated HTTPS](https://pantheon.io/docs/free-https/)

Priority (Low‚ Medium‚ High): High

## Issue Description:

Need a FAQ on when full release is expected, and will more sites get early access before then

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Also need to document HTTP/2 support
