### ISSUE TITLE
AWS S3 Setup for Drupal Doc Update 

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2359]
Re: [AWS S3 Setup for Drupal](https://pantheon.io/docs/drupal-s3/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
User reports that later version of library is needed (V3) in order to configure S3. (with PHP 7)

## Suggested Resolution

**Comment by ttrowell** [comment]
1. Set permissions on AWS Bucket has different wording:
![image](https://cloud.githubusercontent.com/assets/1165813/25199207/0546dd88-2518-11e7-9e05-4d9ea8f09ee1.png)

**Comment by alexfornuto** [comment]
> Set permissions on AWS Bucket has different wording in step 6:
How would you reword it, and/or which terms in the current copy correlate to which terms in your screenshot? I began rewording it [here](https://github.com/pantheon-systems/documentation/pull/2430/files#diff-bc36b7d9969fcc3e54c157ef1cf9e5b3R41), but was unsure about how to continue.

> Select 'Create your Own Policy'
Is that the casing used on their site?

>The policy creation process is a bit different now
Does [this](https://github.com/pantheon-systems/documentation/pull/2430/files#diff-bc36b7d9969fcc3e54c157ef1cf9e5b3R46) accurately match?

**Comment by ttrowell** [comment]
+1 @alexfornuto   This is good.
Let's peel off the actual clarification of the library added into another Issue to keep it more simple.  Sound OK?

**Comment by ttrowell** [comment]
The library needed is indeed Version 2, so I will test to see that the terminus/drush command pulls the expected library.

**Comment by ttrowell** [comment]
`Taras-MacBook-Pro:drupal-globaledge tararowell$ terminus connection:set drupal-globaledge.dev sftp
 [notice] Enabled on-server development via SFTP for "dev"
Taras-MacBook-Pro:drupal-globaledge tararowell$ terminus drush drupal-globaledge.dev -- en libraries s3fs -y
libraries was not found.                                               [warning]
s3fs was not found.                                                    [warning]
Would you like to download them? (y/n): y
The following projects provide some or all of the extensions not            [ok]
found:
libraries
s3fs
Project libraries (7.x-2.3) downloaded to                              [success]
/srv/bindings/6cc9153b1edc44bbb5f8144c6e96a884/code/sites/all/modules/libraries.
Project s3fs (7.x-2.10) downloaded to                                  [success]
/srv/bindings/6cc9153b1edc44bbb5f8144c6e96a884/code/sites/all/modules/s3fs.
The following extensions will be enabled: libraries, s3fs
Do you really want to continue? (y/n): y
s3fs defines the following permissions: administer s3fs
libraries was enabled successfully.                                         [ok]
s3fs was enabled successfully.                                              [ok]
 [notice] Command: drupal-globaledge.dev -- drush en libraries s3fs [Exit: 0]

Taras-MacBook-Pro:drupal-globaledge tararowell$ terminus drush drupal-globaledge.dev -- make --no-core code/sites/all/modules/s3fs/s3fs.make code/
Beginning to build code/sites/all/modules/s3fs/s3fs.make.                   [ok]
awssdk2 downloaded from                                                     [ok]
https://github.com/aws/aws-sdk-php/releases/download/2.7.25/aws.zip.
 [notice] Command: drupal-globaledge.dev -- drush make [Exit: 0]`

**Comment by ttrowell** [comment]
Tested on PHP 7 and it also worked like a charm.

```
Taras-MacBook-Pro:drupal-globaledge tararowell$ terminus drush drupal-globaledge.dev -- en libraries s3fs -y
The following module is missing from the file system: <em              [warning]
class="placeholder">libraries</em>. For information about how to fix
this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1168
The following module is missing from the file system: <em              [warning]
class="placeholder">s3fs</em>. For information about how to fix this,
see <a href="https://www.drupal.org/node/2487215">the documentation
page</a>. bootstrap.inc:1168
libraries was not found.                                               [warning]
s3fs was not found.                                                    [warning]
Would you like to download them? (y/n): y
The following projects provide some or all of the extensions not            [ok]
found:
libraries
s3fs
The following module is missing from the file system: <em              [warning]
class="placeholder">libraries</em>. For information about how to fix
this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1168
The following module is missing from the file system: <em              [warning]
class="placeholder">s3fs</em>. For information about how to fix this,
see <a href="https://www.drupal.org/node/2487215">the documentation
page</a>. bootstrap.inc:1168
Project libraries (7.x-2.3) downloaded to                              [success]
/srv/bindings/6cc9153b1edc44bbb5f8144c6e96a884/code/sites/all/modules/libraries.
Project s3fs (7.x-2.10) downloaded to                                  [success]
/srv/bindings/6cc9153b1edc44bbb5f8144c6e96a884/code/sites/all/modules/s3fs.
libraries is already enabled.                                               [ok]
s3fs is already enabled.                                                    [ok]
There were no extensions that could be enabled.                             [ok]
 [notice] Command: drupal-globaledge.dev -- drush en libraries s3fs [Exit: 0]

Taras-MacBook-Pro:drupal-globaledge tararowell$ terminus drush drupal-globaledge.dev -- make --no-core code/sites/all/modules/s3fs/s3fs.make code/
Beginning to build code/sites/all/modules/s3fs/s3fs.make.                   [ok]
awssdk2 downloaded from                                                     [ok]
https://github.com/aws/aws-sdk-php/releases/download/2.7.25/aws.zip.
 [notice] Command: drupal-globaledge.dev -- drush make [Exit: 0]
```

**Comment by alexfornuto** [comment]
@newtoid does this information satisfy the issue as seen in the original ticket (not linked)? Or do we need to perform a sync with AWS to see the issue?

**Comment by alexfornuto** [comment]
@ttrowell has proclaimed this issue ready to be closed. 🎆
