### ISSUE TITLE
Make New Relic troubleshooting information more digestible. 

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2362]
@pantheon-systems/cse
RE: <https://pantheon.io/docs/new-relic/#new-relic-access>
Priority (Low‚ Medium‚ High): low

## Issue Description:
These are frequent issues - especially for orgs and the errors and solutions are buried in text.

## Suggested Resolution 
Screenshots or greater callout to errors and resolution steps would be great.
For example:
**If you are being asked to Log in to New Relic**
- Close all New Relic Tabs
- Clear all of your browser's New Relic cookies
- Reload your Site's Pantheon Dashboard
- Click the **Go to New Relic** button

**Comment by alexfornuto** [comment]
@lauren-kelly is being asked to log in the only error you want to address? If there are others please let us know what they are, and how to reproduce (and hopefully address) them.

**Comment by alexfornuto** [comment]
I will work with @lauren-kelly next Tuesday during her docs time to make the relevant information more visible.
