### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by LuckhardtLabs** [pantheon-systems/documentation#2373]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/install/)

Priority (Low‚ Medium‚ High): Low

## Suggested Resolution

Correct the spelling error in the bolded text:

If in doubt, you can create a terminus **directory** in your $HOME and go there:

**Comment by alexfornuto** [comment]
Thanks for pointing that out!
