### ISSUE TITLE
Document known issues with Chat support and ad blockers

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#2376]
Document that some ad-blockers can prevent Chat support from working.  This generally manifests as the 'Launch Chat' button not working.  Specifically, Sybu JS blocker to my Chrome Browser prevents Chat from working (probably others as well).

Would be nice to also have tips for determining if this is the issue.

(Internal reference BUGS-1194)

Some other intercom docs: https://docs.intercom.com/faqs-and-troubleshooting/your-users-and-leads-data-in-intercom/why-am-i-missing-users-that-are-showing-up-on-my-own-system

**Comment by joshkoenig** [comment]
I've also seen issues myself where my browser hangs on a request to `ads.yahoo.com` and as a result the chat JS never loads so the button can't launch.
