### ISSUE TITLE
May/June Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2410]
Add May platform changes and new features to be included in the May/June Changelog.

**Comment by greg-1-anderson** [comment]
[Drupal 8.3.2](https://github.com/pantheon-systems/drops-8/pull/181)

**Comment by greg-1-anderson** [comment]
[php 7.0.18](https://github.com/pantheon-cookbooks/php/pull/33)

**Comment by greg-1-anderson** [comment]
[WordPress 4.7.4](https://github.com/pantheon-systems/WordPress/pull/112)

**Comment by ari-gold** [comment]
https://status.pantheon.io/incidents/4g60zwzrwx5f

**Comment by ari-gold** [comment]
https://status.pantheon.io/incidents/pnmlhm0zvbj1

**Comment by greg-1-anderson** [comment]
^^ is a "no change" notification, so maybe there's nothing to put in the ChangeLog for that?

**Comment by ari-gold** [comment]
"Changelog" isn't strictly for changes =)

**Comment by greg-1-anderson** [comment]
Most of the items here were not documented in the April / May changelog, so closing this issue was premature.

**Comment by alexfornuto** [comment]
@greg-1-anderson most of the changes here were added after the cutoff date, so adding those items was overdue, and should be replicated on the next changelog. The status report on the 28th explicitly said "The changelog is now locked in for the month." as the first sentence.

**Comment by alexfornuto** [comment]
Wrong Issue number was attached.

**Comment by ari-gold** [comment]
Adding or removing a domain is now recorded in the workflow log.

**Comment by ari-gold** [comment]
This issue is fixed: https://github.com/pantheon-systems/drops-8/issues/185

**Comment by joshkoenig** [comment]
Global CDN is in early release. https://pantheon.io/docs/global-cdn/

**Comment by taurusismysign** [comment]
Sendgrid port recommendation to 2525. https://pantheon.io/docs/guides/sendgrid/

**Comment by joshkoenig** [comment]
Our [Slack community](https://pantheon.io/docs/power-users/) is expanding. We've added new dedicated channels for Terminus discussion, Composer workflow, and higher-education oriented users. [Join any time](https://slackin.pantheon.io) to connect and compare best practices with other Pantheon Power Users!
