### ISSUE TITLE
Clef 2FA service being discontinued on 6/6/2017

### ISSUE THREAD

**Issue by ilovelamp** [pantheon-systems/documentation#2423]
Re: https://pantheon.io/docs/guides/two-factor-authentication/

Clef is being discontinued.  References to it as 2FA solution should be removed.

https://getclef.com/

> "Clef will stop working on June 6, 2017 -- we recommend transitioning to another form of two-factor authentication as soon as possible."

**Comment by alexfornuto** [comment]
Duplicate of #2222
