### ISSUE TITLE
Platform PCI Compliance Statement

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#2425]
@pantheon-systems/cse
Priority (Low):

## Issue Description:
The platform PCI compliance statement might benefit from a little more explanation. Current statement: "Because PCI certifications have yet to catch up to modern cloud infrastructures, Pantheon cannot currently offer PCI compliance out of the box. If this is a hard requirement for your project, please contact us to discuss details."  
https://pantheon.io/docs/faq/#security

## Suggested Resolution 
Consider adding a little more information to support the "Because PCI certifications have yet to catch up to modern cloud infrastructures" clause.  Perhaps something that mentions that because "each application configuration varies, we are unable to certify PCI compliance on the platform"—Lauren's verbiage—and maybe alternatives/suggestions.

**Comment by alexfornuto** [comment]
Moved to internal tracking for further discussion.
