### ISSUE TITLE
Remove Pingdom recommendation for uptime monitoring in favor of New Relic

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/documentation#2432]
Re: [Pingdom Uptime Check](https://pantheon.io/docs/guides/pingdom-uptime-check/) and [Going Live](https://pantheon.io/docs/going-live/#monitoring-services)

## Issue Description
With our New Relic integration and New Relic's [availability reporting](https://docs.newrelic.com/docs/apm/reports/other-performance-analysis/availability-report) we should be directing user's to take advantage of this existing service rather than sign up for another non-integrated service.

## Suggested Resolution
Change the doc *Pingdom Uptime Check* to *Uptime Check* and add instruction for uptime reporting with New Relic. 

Update the monitoring service reference in the *Going Live* doc to suggest New Relic, rather than Pingdom.

**Comment by sukottokun** [comment]
We want to offer both, Pingdom was part of the integrations campaign, which specifically had a larger objective of demonstrating Pantheon as integration-ready with other Saas products. Plus, not too familiar with the new NR notifications, but Pingdom offered different options, multi-tier notifications, etc. Some people are already using Pingdom for non-Pantheon applications. I agree should add a doc for doing it with NR.

**Comment by alexfornuto** [comment]
We have New Relic documentation as part of Going-Live. Any doc mentioning Pingdom also links to the New Relic documentation. I'm working on updating the monitor steps, but that's not related to this issue, so I'm closing it.
