### ISSUE TITLE
Cron and D8

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#2436]
Re: 
It does look like Elysia Cron my not make it to D8. And Ultimate Cron is there already. Pantheon documents need an adjust based on that.
See #82195

**Comment by rvtraveller** [comment]
I don't think this is a good documentation update to make as Ultimate Cron doesn't work on Pantheon (currently).  Reference Desk case # 82195.

**Comment by alexfornuto** [comment]
Closing, will address these issues while working on #2591
