### ISSUE TITLE
Platform considerations for plugin/module developers

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#2442]
@pantheon-systems/cse
Priority: low

## Issue Description:
A plugin author inquired about documentation covering operations (e.g. functions) that aren't supported or don't work on the platform. 

## Suggested Resolution 
To encourage best practices in the community, provide documentation for developers that lists known issues that could result in either failed implementation on the platform or will require fixes, e.g. create symlinks for improperly defined writeable paths, sessions, etc. 

Ref: /case/83943

**Comment by alexfornuto** [comment]
Closed by #2437
