### ISSUE TITLE
Configuring Settings.php Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2443]
Re: [Configuring Settings.php](https://pantheon.io/docs/settings-php/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Under "How can I write logic based on the Pantheon server environment?" it would be good to mention the 3rd option $_ENV: https://pantheon.io/docs/read-environment-config

It would also be great to mention and link to the "dangers" in using $_SERVER https://pantheon.io/docs/read-environment-config/#using-$_server as this causes many site failures and workflow task errors ($_SERVER is not available for drush requests / workflow tasks).

And lastly, it would be great to recommend considering for each block, whether a check for 'php_sapi_name' is necessary in order to avoid unexpected results: https://pantheon.io/docs/redirects/#command-line-conditionals

## Suggested Resolution

**Comment by alexfornuto** [comment]
Waiting on @tinefin to review my PR.
