### ISSUE TITLE
Managing WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2454]
Re: [Managing WordPress Site Networks](https://pantheon.io/docs/managing-wordpress-site-networks/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Terminus commands are <v1 syntax

## Suggested Resolution 
Update with v1+ syntax

**Comment by alexfornuto** [comment]
@tinefin Please review #2456.
