### ISSUE TITLE
WordPress Configuration Management (WP-CFM) Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2463]
Re: [WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Tracking Woocommerce `ywson_start_order_number` option using WP-CFM and the Pantheon workflow has the potential to overwrite the option on Live.
## Suggested Resolution 
Recommend this option not be tacked by WP-CFM here and perhaps in the unsupported modules doc page. Consider other Woocommerce options that would behave similarly.

**Comment by llubao** [comment]
@rachelwhitton  I would like to clarify which "other Woocommerce options" means here.

**Comment by alexfornuto** [comment]
@llubao I wouldn't worry about that for now. Other options can be added as discovered, or by those with lots of experience with Woocommerce

**Comment by newtoid** [comment]
start_order_number is not a value recognised by wp-cfm, in specific use cases, this value, if it exists, can be just not included in wp-cfm bundles. I was unable to find a plugin that used *start_order_number.
