### ISSUE TITLE
Email on Pantheon Doc Update 

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#2466]
Re: [Email on Pantheon](https://pantheon.io/docs/email/)

Priority (Low):

## Issue Description:

This page includes links to setup Drupal SMTP support but doesn't seem to do so for Wordpress. Wordpress users may get to see Sendgrid info but we should bubble up info on support for WP-SMTP directly (should they choose to use their GMail, Outlook, or other accounts that may not have a direct module).

## Suggested Resolution 

Pull up info on configuring https://wordpress.org/plugins/wp-smtp/ to this page

**Comment by dustinleblanc** [comment]
Starting working on redoing this today but Github dumped my changes like 3 times, I am going to do local dev

**Comment by alexfornuto** [comment]
Closed by #2483
