### ISSUE TITLE
Errors and Server Responses Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2475]
Re: [Errors and Server Responses](https://pantheon.io/docs/errors-and-server-responses/)

Priority (Low‚ Medium‚ High):

## Issue Description:
This document seems somewhat out of date by now. We have 500 errors, 499 errors, Cloudflare 521 and so forth. 

## Suggested Resolution 
Would be good to check this against engineering level http status codes and get the doc to reflect current platform.

**Comment by rachelwhitton** [comment]
Thanks for the issue @tinefin! I'm planning to handle this issue as part of the larger Global CDN project.
