### ISSUE TITLE
Add warning about restoring live sites with large archives

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#2477]
Re: <Doc title and/or link>
## Issue Description
Restoring sites, files and database in a live environment can take a long while if the archives are large. This leads to the site not being available.

## Suggested Resolution

Provide alternatives to restoring all archives (e.g. restore db only, Git revert etc.)

**Comment by lauren-kelly** [comment]
@alexfornuto and/or @rachelwhitton can we talk about this doc vs the undo-commits doc?
