### ISSUE TITLE
Terminus Manual Doc Update: Add instructions for command completion

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2493]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/)

Priority (Low‚ Medium‚ High): Medium

## Suggested Resolution https://wikihub.berkeley.edu/display/drupal/Autocompletion+for+Terminus+1.x+on+MacOS
- Linux, Windows?

**Comment by alexfornuto** [comment]
Following the internal discussion, I'm going to close this issue in favor of the initiative to include autocomplete into the Terminus installer: https://github.com/pantheon-systems/terminus-installer/issues/25
