### ISSUE TITLE
Troubleshooting section needed for Sendgrid

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2496]
Re: https://pantheon.io/docs/guides/sendgrid/
## Issue Description
We anticipate a good number of users will miss notifications that they need to update their sendgrid configurations, and will search the docs or come to support for assistance

## Suggested Resolution
Add a Troubleshooting section to the doc, with a screenshot of the types of errors we expect them to see if their sendgrid is configured on the wrong port.

**Comment by lauren-kelly** [comment]
@taurusismysign for when we have those screenshots

**Comment by taurusismysign** [comment]
![wp-sg-smtp-error](https://cloud.githubusercontent.com/assets/12533094/26322484/249ef9e0-3ee0-11e7-9bb5-53d87dce2f6a.jpeg)

Error screenshot when using Sendgrid with a non-localhost and wrong port

**Comment by alexfornuto** [comment]
This issue is being tracked in IO-2310.
