### ISSUE TITLE
Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2513]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate/)

Priority (Low‚ Medium‚ High):

## Issue Description:

Issue with Drupal 8 DB export w phpmyadmin:

Possible solution:
https://www.drupal.org/node/2496331#comment-10029863

chat issue: #10043491852

**Comment by alexfornuto** [comment]
@tinefin What's the issue?

**Comment by tinefin** [comment]
The Drupal.org post describes an issue where a DB export made with a particular version of phpmyadmin can't import on "some" other systems. Apparently including Pantheon, since we just had a chat on it.

The fix is to either edit the phpmyadmin export code or to export "some other way" (Drush, command line mysqldump, connect with a GUI client and export - as preferred).

Error message will be like: 
`"[500] "An error occurred while importing the database, process unsuccessful.\nERROR 1064 (42000) at line <LINE NUMBER>: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'longblob NOT NULL COMMENT 'The value.',""`
This ^^ is currently not customer facing, only CSE can access these.

This is an phpmyadmin issue (but occurs on Drupal sites), but a bit tricky to spot / track down so would be good to document for CSE and customers alike. The error will appear for instance on database import while migrating a site to Pantheon.
