### ISSUE TITLE
June/July Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2541]
Add June platform changes and new features to be included in the June/July Changelog.

**Comment by ari-gold** [comment]
WP-CLI updated from 1.1.0 to 1.2.1. 

Release notes: https://make.wordpress.org/cli/2017/06/06/version-1-2-1-released/

**Comment by ari-gold** [comment]
A little dated, but I think Changelog is a good oppty to point people to https://pantheon.io/docs/new-relic/#configure-ping-monitors-for-availability and note that New Relic APM's Availability Monitoring no longer will work

**Comment by rachelwhitton** [comment]
Terminus 1.4.0 
https://github.com/pantheon-systems/terminus/releases/tag/1.4.0

**Comment by greg-1-anderson** [comment]
Drupal 8.3.3 + 'drush cache-rebuild' now clears Pantheon edge cache too.

https://github.com/pantheon-systems/drops-8/pull/187 <- Drupal update
https://github.com/pantheon-systems/drops-8/pull/186 <- Pantheon egde cache clear feature

**Comment by greg-1-anderson** [comment]
WordPress 4.8

- https://github.com/pantheon-systems/WordPress/pull/122 <- WordPress update
- https://github.com/pantheon-systems/WordPress/pull/118 <- New screenshot
- https://github.com/pantheon-systems/WordPress/pull/102 <- Updated hash salt documentation

**Comment by greg-1-anderson** [comment]
Drupal 7.55

- https://github.com/pantheon-systems/drops-7/pull/105 <- Drupal update
- https://github.com/pantheon-systems/drops-7/pull/102 <- Apache Solr with relocated document root
- https://github.com/pantheon-systems/drops-7/pull/100 <- Prevent creation of .htaccess when running Drush

**Comment by greg-1-anderson** [comment]
`pantheon.upstream.yml` now supported on the platform

- https://github.com/pantheon-systems/documentation/pull/2584

**Comment by greg-1-anderson** [comment]
- Drupal 8.3.4 https://github.com/pantheon-systems/drops-8/pull/188
- Drupal 7.56 https://github.com/pantheon-systems/drops-7/pull/106

**Comment by greg-1-anderson** [comment]
PHP 7 by default for WordPress and Drupal 8:

- https://github.com/pantheon-systems/WordPress/pull/123
- https://github.com/pantheon-systems/drops-8/pull/189

PHP 5.6 by default for Drupal 7:

- https://github.com/pantheon-systems/drops-7/pull/107

**Comment by greg-1-anderson** [comment]
Is it too late to add to June/July?  If so, bump this to July/August:

- Drupal 8.3.5: https://github.com/pantheon-systems/drops-8/pull/190

**Comment by alexfornuto** [comment]
@greg-1-anderson if it happened on or after July 1st, it goes into the July/August log. I'll make the issue now.
