### ISSUE TITLE
Early Access: Free and Automated HTTPS Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#2542]
Re: [Early Access: Free and Automated HTTPS](https://pantheon.io/docs/free-https/)

Priority (Low‚ Medium‚ High): Low

## Issue Description: 
Doc did not mention if Customers should receive an email confirmation from Pantheon after submitting an early access request. How long should they wait? What should be the next step?

## Suggested Resolution 
Add info on how to check the status of their request including ETA to manage customer expectations.

**Comment by alexfornuto** [comment]
@ari-gold so, will they? How long should they?

**Comment by ari-gold** [comment]
@rubelyn  If you have any inquiries, please ping me directly with links to site dashboards. Thanks!

**Comment by ari-gold** [comment]
@alexfornuto @rubelyn In addition to previous comment, we have an internal wiki to help CSE determine if they should grant early access, which we can update if necessary.

**Comment by alexfornuto** [comment]
@ari-gold I think the questions were posed here so they could be answered on the docs for the public.
