### ISSUE TITLE
Starting With Git Doc Update 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#2550]
Re: [Starting With Git](https://pantheon.io/docs/git/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
There's a section which suggests using diffie-hellman-group1-sha1 as a preferred method for improving the connection performance. Being a simpler encryption method it does provide a speed benefit at the cost of a weaker security. 

SHA1 has already been broken (a collision was found) in an experiment run by Google recently and Diffie-Hellman doesn't provide forward secrecy. I'm not really comfortable with the suggestion here.

https://www.theverge.com/2017/2/23/14712118/google-sha1-collision-broken-web-encryption-shattered

Also, this algorithm is only proposed as a legacy option in openssh - http://www.openssh.com/legacy.html

## Suggested Resolution 
I haven't seen any complaints related to connection problems due to a cipher mismatch (as a trend I mean). I propose we eliminate this section.

**Comment by alexfornuto** [comment]
Thanks @alexdicianu!
