### ISSUE TITLE
Drupal 8 can fail in development for sites with too many fields

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#2555]
## Issue Description
When a site has too many fields, Drupal populates the x-drupal-cache-tags header with too much information, overflowing the size allowed by Varnish.

## Suggested Resolution
From a customer:

```
So basically the headers specially the x-drupal-cache-tags was too big,
but this header is only being sent in development mode I guess that will be
dev and test not production, so I disable this header by changing the
http.response.debug_cacheability_headers* to false in the
development.services.yml
```

**Comment by ttrowell** [comment]
This may be the best place to document this: https://pantheon.io/docs/errors-and-server-responses/#503-header-overflow

**Comment by rachelwhitton** [comment]
@greg-1-anderson is `development.services.yml` the right file to recommend for this scenario? From what I understand, the default behavior for that file is to be included only on local configurations. Setting `http.response.debug_cacheability_headers: false` in this file would only fix the issue on Pantheon for sites that have customized their configuration to include `development.services.yml` outside of a local environment. 

Would it be better to suggest using `services.pantheon.preproduction.yml` and `services.pantheon.production.yml` instead?

**Comment by greg-1-anderson** [comment]
The existing text for the #503-header-overflow in the docs states this overflow is limited to cookies; however, with this new header the same sort of thing happens.

I did not investigate the OP's claim that this header only happens in dev. I'm not sure what setting controls whether it is set or not.

`services.pantheon.preproduction.yml` is definitely the file to use to disable the header in dev. It may not be necessary to also disable it in `services.pantheon.production.yml`, but it certainly would not hurt to do so.

**Comment by peter-pantheon** [comment]
@greg-1-anderson @ttrowell @rachelwhitton  Two d.o posts on cache-tags here. It is recommended that for Drupal 8 both “your web server and your reverse proxy support response headers up to 16KB”. Noted in the section called “Integration with reverse proxies” in the first post cited below. 
 
https://www.drupal.org/docs/8/api/cache-api/cache-tags
https://www.drupal.org/node/2592471

**Comment by rachelwhitton** [comment]
TODO: Work with @ari-gold to identify size limit for HTTP response headers on the new global cdn

**Comment by greg-1-anderson** [comment]
So perhaps this isn't a problem unless the user opts in by setting `http.response.debug_cacheability_headers` to `true` in `services.pantheon.preproduction.yml`?

**Comment by rachelwhitton** [comment]
That sounds right @greg-1-anderson, for development environments. It's a problem if the user opts in on prod as well, but that isn't recommended so not sure the prod scenario requires explicit documentation. But like you said, it wouldn't hurt to set it to false there too.
