### ISSUE TITLE
Vanity Domains Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2569]
Re: [Vanity Domains](https://pantheon.io/docs/vanity-domains/)

Priority (Low‚ Medium‚ High):

## Issue Description:
We should recommend a vanity domain that is different from main production site. This will prevent the possibility of a development site cookie hijacking  the main site.  

e.g. if agency site is agency.com then we recommend using a vanity domain that does not include agency.com, but something like sites.agency.io

## Suggested Resolution

**Comment by alexfornuto** [comment]
@ari-gold are you suggesting a vanity domain specifically for the dev site, or dev and test, or something else?
