### ISSUE TITLE
Domain masking doc has old fast.ly UI

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#2573]
https://pantheon-systems.desk.com/web/agent/case/85282

@pantheon-systems/cse
Priority (Low‚ Medium‚ High):

## Issue Description:

Fast.ly UI has changed and our docs don't reflect this

## Suggested Resolution 

Review if doc and change to match latest Fast.ly UI

**Comment by rachelwhitton** [comment]
Thanks @slashzero! This doc is planned to be refactored as part of an upcoming launch for new going live procedures. We'll address this issue alongside other work in progress wrt domains/dns.
