### ISSUE TITLE
Use a custom prefix for Redis for D8 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#2586]
Re: [Redis as a Caching Backend](https://pantheon.io/docs/redis/)
## Issue Description
To match what we have in place for D7 and also to fix BUGS-1343 and https://www.drupal.org/node/2882794

## Suggested Resolution
Add the snippet below.
```
$settings['cache_prefix']['default'] = 'pantheon-redis';
```

**Comment by alexdicianu** [comment]
https://github.com/pantheon-systems/documentation/commit/37fe396b2f59742ca8dc8a994e2390d8eee76247

**Comment by rachelwhitton** [comment]
👍
