### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2589]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:

Verify Jetpack issue is fixed (https://github.com/Automattic/jetpack/pull/7322) and remove it from this page. Also a potential fix to add to Changelog?

**Comment by peter-pantheon** [comment]
I am looking at this. We may have to leave some note in the docs that compatibility begins with Jetpack version 5.1+ (though seems this update is not mentioned in the Jetpack Changelog).
