### ISSUE TITLE
Cron for Drupal Doc Update 

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#2591]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron/)

Priority (Low):

## Issue Description:
There is an option with the newer version of the Elysia Cron module that "globally disables" cron.
This probably needs to be set along with the Cron Key to prevent all cron from running - even from the platform.

## Suggested Resolution 
Test the new version of the module and verify - then add to info about Elysia.

**Comment by alexfornuto** [comment]
@ttrowell Does this affect D7, D8, or both?

**Comment by ttrowell** [comment]
- D7 verison only as a D8 version has not been released.
We *do* need to validate with another test, however, and include a screenshot of this setting, if possible.

**Comment by alexfornuto** [comment]
Removing @dustinleblanc from self-assignment since that was a month ago.

**Comment by llubao** [comment]
I am researching regarding this issue

**Comment by llubao** [comment]
Updating draft for my PR
