### ISSUE TITLE
Redis as a Caching Backend Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2618]
Re: [Redis as a Caching Backend](https://pantheon.io/docs/redis/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
Does `  $settings['cache']['bins']['form'] = 'cache.backend.database';` need to be set within the following (last part of the codeblock for D8): 
```
  // Always set the fast backend for bootstrap, discover and config, otherwise this gets lost when redis is enabled.
  $settings['cache']['bins']['bootstrap'] = 'cache.backend.chainedfast';
  $settings['cache']['bins']['discovery'] = 'cache.backend.chainedfast';
  $settings['cache']['bins']['config']    = 'cache.backend.chainedfast';
}
```

For d7 we have: 
```
  // Do not use Redis for cache_form (no performance difference).
  $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
```
## Suggested Resolution 

Confirm with SME, maybe @alexdicianu and/or @peter-pantheon whether we need to specify cache bin

**Comment by rachelwhitton** [comment]
Also, testing needed for the following user response on D8 + redis:

"Yes D8 needs a prefix, but it must also include the version number to prevent bugs during upgrades:

  // The default prefix is based on path to the webroot, which on Pantheon
  // changes from container to container.  So hard-code it, but use the version
  // prefix as in the default, so that upgrades cause new cache keys.
  $settings['cache_prefix']['default'] = DRUPAL::VERSION . ':';"

**Comment by alexdicianu** [comment]
@rachelwhitton both comments look legit although I haven't tested `$settings['cache']['bins']['form']`. If I get some time today, I'll give that a spin.

**Comment by eabquina** [comment]
Placing cache backend for form works; 
   // Do not use Redis for cache_form (no performance difference).
  $settings['cache']['bins']['form']      = 'cache.backend.database';

While  $settings['cache_prefix']['default'] = Drupal::VERSION . ':';" is not working;
