### ISSUE TITLE
Private Paths for Files and Code Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2619]
Re: [Private Paths for Files and Code](https://pantheon.io/docs/private-paths/#resolving-warning-file_put_contentsprivate:.htaccess)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
When .htaccess file is present and you get the error noted, you have to first delete the .htaccess file THEN you have to resubmit in Drupal Admin

## Suggested Resolution 
Test and add step to delete .htaccess if valid.

**Comment by ilovelamp** [comment]
Spent a lot of time trying to repro exact conditions to cause this. I made clarifications on file paths and instructions to properly configure private paths.
