### ISSUE TITLE
Early Access: Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/documentation#2622]
Re: [Early Access: Pantheon Global CDN](https://pantheon.io/docs/global-cdn/)

Priority (Low‚ Medium‚ High):

## Issue Description:

Wiki is showing that vanity domains will not work with HTTPS using Global CDN.

## Suggested Resolution 

Unless this will change, we should include a FAQ about this.

**Comment by rachelwhitton** [comment]
Closing as duplicate issue, will work on this as part of #2623
