### ISSUE TITLE
Early Access: Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#2623]
Re: [Early Access: Pantheon Global CDN](https://pantheon.io/docs/global-cdn/)

Priority (Low‚ Medium‚ High):

## Issue Description:
We need to specify somewhere that the www-redirector is no longer present on the Global CDN. This is causing confusion for some clients that were previously relying on it. We can see an example of this in ticket #85973

**Comment by ari-gold** [comment]
@alexdicianu Thanks for highlight this issue. Maybe worth a note at the end of https://pantheon.io/docs/guides/launch/redirects ?

**Comment by alexdicianu** [comment]
@ari-gold @rachelwhitton if you think that's the best place to put it, I can go ahead and send a PR with that note.
