### ISSUE TITLE
Early Access: Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2626]
Re: [Early Access: Pantheon Global CDN](https://pantheon.io/docs/global-cdn/)

Priority (Low‚ Medium‚ High):

## Issue Description:

Would be great to have a screenshot showing what a successful test would look like in step 4 under the "Test your site" section.

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Successful test would be to access the site using the custom domain over HTTPS, so it would look like this (in Chrome): 
<img width="137" alt="screen shot 2017-07-03 at 5 21 35 pm" src="https://user-images.githubusercontent.com/10119525/27809324-1dd9098e-6014-11e7-946e-c8aecf305a5d.png">

I'm not sure a screenshot is needed.

**Comment by rachelwhitton** [comment]
Closing as duplicate issue, will work on this as part of #2623
