### ISSUE TITLE
Free and Automated HTTPS Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2661]
Re: [Free and Automated HTTPS](https://pantheon.io/docs/free-https/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Add Known issue:
HTTPS will fail to provision if AAAA record is incorrect

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Make specific recommendations on which 3rd party service providers they can use to terminate HTTPS

**Comment by rachelwhitton** [comment]
Address concerns re: shared certs as cosmetic, and reaffirm legitimacy

**Comment by rachelwhitton** [comment]
Recommend maintenance window if a site cannot prove ownership, note product plans to support validation with dns challenge down the road
