### ISSUE TITLE
Clarification for timeouts

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#2664]
Re: https://pantheon.io/docs/timeouts/

**Comment by alexfornuto** [comment]
Blocked waiting on @slashzero to finish defining the issue.

**Comment by allenfear** [comment]
@slashzero could you provide steps for reproducing the 503 error masking the 502 error?

**Comment by alexfornuto** [comment]
@slashzero This issue is going to be closed soon, unless you can clarify what it is we need to update.
