### ISSUE TITLE
Update pull request guide for WordPress

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#2665]
Re: https://pantheon.io/docs/guides/github-pull-requests/
## Issue Description

Our GitHub pull request guide is currently specific to Drupal. That is largely because Drupal 8 has been the focus of our Composer examples thus far. Soon we'll be adding an `example-wordpress-composer` that will be similar to `example-drops-8-composer` and compatible with the Terminus Build Tools Plugin

## Suggested Resolution

Update https://pantheon.io/docs/guides/github-pull-requests/ to make it more generic or just separately explain WordPress differences.

**Comment by alexfornuto** [comment]
Based on user feedback, suggest updating these guides to include links or suggestions for local development setups to match.
