### ISSUE TITLE
2FA Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2678]
Re: [Secure Your Site with Two-Factor Authentication](https://pantheon.io/docs/guides/two-factor-authentication/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Refactor this page to include platform level authentication, specifically how to connect a Google account (with 2FA) and scramble the password on Pantheon. Link to the SAML doc for orgs/agencies with a note about implementing 2FA via SAML

Requested by @davidstrauss

**Comment by davidstrauss** [comment]
> specifically how to connect a Google account (with 2FA) and scramble the password on Pantheon

I'd mention other effects, too, like the need to use an SSH key for SFTP and Drush/WP-CLI.

We may also want to mention that this approach has one deficiency versus native 2FA (or the SAML approach), and that's the password reset path. The account will only be as secure as the email backing it. If they use Google for email and connect that account to Pantheon, this is not an additional risk. For people with email that isn't from Google, it might make sense to change their email address on Pantheon to match the linked Google account's GMail or G Suite address.

**Comment by davidstrauss** [comment]
Let's worry about that wall of text caveat later, though. Maybe just mention that the email account also needs to be secured because a scrambled password can still get reset.
