### ISSUE TITLE
update known issues/limitations to mention stored procedures unsupported.

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2680]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High):

## Issue Description:
MySQL stored procedures are not supported on the platform and we should update docs to reflect this, they cannot be guaranteed to persist following a database migration as we focus primarily on the site database "pantheon"

NB routines are included in backups

## Suggested Resolution 

Update docs to reflect this
look for alternative suggestions for handling SPs or at least to make them easily recoverable
manage expectations of users depending on them

**Comment by alexfornuto** [comment]
@newtoid which docs does this issue affect. What do you mean by "stored procedures"? Stored where?

**Comment by newtoid** [comment]
@alexfornuto Stored in the mysql.proc table, I have an example of this issue I can share with you

**Comment by dustinleblanc** [comment]
For reference: https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-stored-procedures.html

**Comment by alexdicianu** [comment]
I would just add one more item to this list.
https://pantheon.io/docs/platform-considerations/
