### ISSUE TITLE
Snippet to find current outgoing IP address

### ISSUE THREAD

**Issue by ilovelamp** [pantheon-systems/documentation#2681]
Re: https://pantheon.io/docs/outgoing-ips/#ip-address-ranges

## Issue Description

Despite the fact that we do not provide IP ranges for outgoing requests, some customers may still need to know what IP address is currently being used for outgoing requests from their site.

## Suggested Resolution

Our docs already recommend API keys or other authentication schemes, in addition to Pantheon Enterprise Gateway.

We should consider offering them a snippet to make an outgoing request and grab the IP address from a web service such as http://canihazip.com, for example:

```
<?php

$ip = file_get_contents("http://canihazip.com/s");

echo "ip = $ip";
```

This snippet would be recommended for manual 'one off' checking, and NOT for automated or programmatic use from their code.

**Comment by alexdicianu** [comment]
To be honest I don't see any simple way to get the outbound IP without running external requests which I'm against. If the external service goes down we have no control over it.

A better approach would be using API keys or bearer tokens - `Authorization : Bearer <token>`

**Comment by alexfornuto** [comment]
I'm also not a fan of documentation that's reliant on third-party services being stable. Beyond that, I have no other objections.

**Comment by alexfornuto** [comment]
Input from @pantheon-systems/cse would be appreciated.

**Comment by newtoid** [comment]
@alexfornuto I don't think we should encourage this - we already discourage black/whitelisting and no longer provide IP ranges. I think if we provide this snippet we expose ourselves to blame when things stop working for people who have used our snippet, and if people need to use something like this in they can figure it out without it being the official company line.

**Comment by rachelwhitton** [comment]
Agreed, we can revisit, but for now closing based on the current convo

**Comment by tdm4** [comment]
Hi,
  We do egress firewall filtering and do need to know IP ranged to let out of our network to connect to Pantheon cloud-based systems. Is there a way to get a list of *ALL* Pantheon cloud IP ranges? Does Pantheon have an AS number I can query for netblocks?

   Not providing IPs is doing a pretty big disservice here.

  Thanks,
  Tom

**Comment by allenfear** [comment]
Our recommended approaches for outbound connections are here:
https://pantheon.io/docs/outgoing-ips/#ip-address-ranges

Closing as the doc lists available options.
