### ISSUE TITLE
Free and Automated HTTPS Doc Update, Sucuri Troubleshooting

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2683]
Re: [Free and Automated HTTPS](https://pantheon.io/docs/free-https/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
HTTPS doesn't provision with Sucuri's default settings

## Suggested Resolution 
By default Sucuri blocks serving the challenges needed to verify domain ownership and issue Let's Encrypt certificates. Contact Sucuri support and request they enable the "Forward Certificate Validation" setting, which will allow HTTPS provisioning to complete successfully. Note that you'll want to keep this setting enabled, so the certificate will always renew automatically.

ref. 86058, 86880,

**Comment by alexfornuto** [comment]
Closed by https://github.com/pantheon-systems/documentation/pull/2693
