### ISSUE TITLE
Update documentation on the GitHub pull request workflow

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#2685]
Re: https://pantheon.io/docs/guides/github-pull-requests/
## Issue Description
The current GitHub Pull request document only covers installation with Drupal 8. Drupal 7 and WordPress are now also available, and should be documented.

## Suggested Resolution
- The intro can remain the same
- "Before you begin" can remain the same
- "Set up a new Project" needs Drupal 7 and WordPress info added
  - Add a three-tab section for the create-project command
  - Change the text to reflect the three options
- "Your project page" can remain the same

Everything from "Create a Pull Request" on down should move to another page. After "Your project page", there should be three links, one for each of the Drupal 8, Drupal 7 and WordPress example workflow walk-throughs, as each of these will be quite different depending on the CMS.

**Comment by alexfornuto** [comment]
Closing as a duplicate of #2665
