### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2707]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Terminus only scales to 1x

Terminus does not support issuing many commands simultaneously. When for instance creating Terminus scripts, commands will have to be run consecutively and the script will need to be run on one site at a time when executing.

## Suggested Resolution

**Comment by alexfornuto** [comment]
This issue is related to BUGS-1433. I'm marking it as "blocked" until there's a suggested resolution either here or in JIRA.

**Comment by rachelwhitton** [comment]
Closing based on conversation in related bug card
