### ISSUE TITLE
Domains and Redirects Doc Update 

### ISSUE THREAD

**Issue by roprice** [pantheon-systems/documentation#2711]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:

If you apply the www domain redirect code (here --> https://pantheon.io/docs/domains/#redirects) without defining `WP_HOME` ,   you get an infinite loop on the WordPress home page.

## Suggested Resolution 

Insert `define('WP_HOME', $base_url);` anywhere after `$base_url` is defined.

**Comment by rachelwhitton** [comment]
Thanks for reporting @roprice!
