### ISSUE TITLE
Domains and Redirects Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2712]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High):

## Issue Description:
New Relic statistics are often fairly "polluted" due to the often high percentage of calls that are (very fast) redirects. This can make it difficult to spot issues in general - and especially issues that ends up detected as the same transaction in New Relic as the redirects.

## Suggested Resolution 

Please note - the below should be tested before implemented. If interested to implement, reach out to me and I'll do the testing!

Add this in redirects:
`if (function_exists('newrelic_ignore_transaction')) {
    newrelic_ignore_transaction();
}`
Same concept as here:
https://pantheon.io/docs/new-relic/#drupal

Alternatively, make redirects turn up in their own transaction:
`if (function_exists('newrelic_name_transaction')) {
    newrelic_name_transaction("redirect");
}`
https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_name_transaction

**Comment by rachelwhitton** [comment]
Thanks for reporting @tinefin!

@davidstrauss can you weigh in?
