### ISSUE TITLE
Office 365 for SMTP Email support

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2713]
Under docs/email , need more info for users who choose Office 365 as an SMTP relay,
If we support it , especially in cases where SPF record is required

**Comment by alexfornuto** [comment]
@eabquina Before working on this issue, we'd need to know what is required from our platform to go into these SPF records.

**Comment by eabquina** [comment]
@alexfornuto It turns out, we don't support SPF records. The new PR I added is meant to highlight whats only possible related to Exchange and Office 365 - PR #2854
