### ISSUE TITLE
New Doc Proposal: Sucuri config on Global CDN

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2715]
Priority (Low‚ Medium‚ High): Low

## Title
Sucuri config on Global CDN

## Description
Customer asks, "If I want to keep Sucuri in place, what's the most secure configuration with Global CDN?"

## Outline
- Configure Sucuri to redirect all traffic to HTTPS
- Contact Sucuri to enable the "Forward Certificate Validation" so Pantheon can deploy and renew certificates on Global CDN (https://pantheon.io/docs/https/#https-doesnt-provision-with-sucuris-default-settings)

- Enable "Full SSL" (not Partial) in Sucuri (does this auto-pin certificate?)

>Partial SSL: If your website backend does not provide HTTPS, we will proxy HTTPS->HTTP on your behalf. This is not ideal, but we are securing a very large piece of the communication chain between your customers and our network. This is the initial communication with your audience, and the most susceptible to Man in the Middle (MiTM) Attacks.
from https://blog.sucuri.net/2016/04/sucuri-firewall-free-letsencrypt-ssl-certs-for-everyone.html

## Expected Audience
- Existing Sucuri customers

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by rachelwhitton** [comment]
Associated PR was closed after further consideration
