### ISSUE TITLE
August/September Changelog Candidates

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2730]
Add August platform changes and new features to be included in the August/September Changelog.

**Comment by greg-1-anderson** [comment]
Drupal 8.3.6: https://github.com/pantheon-systems/drops-8/pull/191

**Comment by greg-1-anderson** [comment]
WordPress 4.8.1: https://github.com/pantheon-systems/WordPress/pull/129

**Comment by rachelwhitton** [comment]
Terminus 1.5

**Comment by greg-1-anderson** [comment]
Drupal 8.3.7: https://github.com/pantheon-systems/drops-8/pull/193

**Comment by ari-gold** [comment]
https://status.pantheon.io/incidents/v81md6cd43b8

**Comment by ari-gold** [comment]
Updated PHP 5.6 to 5.6.31
http://www.php.net/ChangeLog-5.php#5.6.31

**Comment by ari-gold** [comment]
Global CDN Surrogate Key Cache Clearing API Improvement
We improved cache clearing behavior for a large number of surrogate keys or cache tags. The fix was made internally by Pantheon and no action required if you are already running WordPress or Drupal versions of Pantheon Advanced Page Cache.

**Comment by greg-1-anderson** [comment]
Also updated PHP 7.0 to 7.0.23.
