### ISSUE TITLE
Document role required to add custom upstreams

### ISSUE THREAD

**Issue by ilovelamp** [pantheon-systems/documentation#2742]
Re: https://pantheon.io/docs/change-management/

## Issue Description

[Change management docs](https://pantheon.io/docs/change-management/) and the:

Organizations -> People tab -> Change user role... popup for "View user roles and their permissions" option don't mention Custom Upstreams permissions:

![screenshot 2017-08-04 11 03 02](https://user-images.githubusercontent.com/24276107/28976689-824a41e0-7904-11e7-9a75-8ed1bc7e9910.png)

## Suggested Resolution

Update docs page and snippet for display in dashboard help.

**Comment by alexfornuto** [comment]
Closed by 2790
