### ISSUE TITLE
Log Files on Pantheon Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2746]
Re: [Log Files on Pantheon](https://pantheon.io/docs/logs/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Regarding log file retention:
Logs get lost on container migration, which happens regularly. So, if the container migrated 2 days ago - there will only be logs from the current container (meaning the last 2 days) as logs from the former container are no longer accessible.
Users who rely on the mentioned log retention (or longer) would need to automate fetching of logs at a suitable time interval.

## Suggested Resolution 

Perhaps add in as an FAQ item for "Why are logs missing" or similar?

**Comment by alexfornuto** [comment]
Suggestion: We have a section on the guide for scripting logs, but it doesn't cover scheduling it to run at intervals. After https://pantheon.io/docs/logs/#collect-logs, add a section on scheduling, and a warning about losing logs to container rebuilds.
