### ISSUE TITLE
Platform Considerations Doc Update 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#2749]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Currently, we say that on Drupal 7 sites emojis (or multi-byte UTF8) characters are not supported. The server settings that allow MariaDB to support utf8mb4 are actually deployed on Pantheon – see below. This used to be indeed a limitation until very recently. 

The problem I think is that some existing sites don't have this ability due to various Drupal config options that we might need to test out.

https://www.drupal.org/node/2754539

```
mysql> show global variables where Variable_name in ('innodb_large_prefix', 'innodb_file_format', 'innodb_file_per_table');
+-----------------------+-----------+
| Variable_name         | Value     |
+-----------------------+-----------+
| innodb_file_format    | Barracuda |
| innodb_file_per_table | ON        |
| innodb_large_prefix   | ON        |
+-----------------------+-----------+
3 rows in set (0.14 sec)
```

## Suggested Resolution 
I would actually delete the entire emoji section and just point our users to the drupal.org article in case they run into any issues. From a platform perspective, everything is set up correctly.

**Comment by alexfornuto** [comment]
Crosslinking #2909
