### ISSUE TITLE
Security topic about DDOS capability of Pantheon

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2750]
Re: [Security on the Pantheon Dashboard](https://pantheon.io/docs/security/)

Priority (Low‚ Medium‚ High):

## Issue Description:
User suggests putting in the docs how we actually mitigate DDOS attacks

## Suggested Resolution 
Convert samples here: https://pantheon.io/blog/ddos-attacks-pantheon-and-you
Consider new Global CDN as well

**Comment by rachelwhitton** [comment]
Closing - work planned as part of product release cycle
