### ISSUE TITLE
Introduction to Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by allenfear** [pantheon-systems/documentation#2751]
Re: [Introduction to Custom Upstreams](https://pantheon.io/docs/custom-upstream/)

Priority Medium

## Issue Description:
The note on this page reads: "We do not recommend Custom Upstreams for Drupal 8 sites managed by Composer at this time. For an alternative workflow, checkout Using [GitHub Pull Requests with Composer and Drupal 8](https://pantheon.io/docs/guides/github-pull-requests/)." But the doc on GitHub pull requests does not explain how it can be used for multiple sites in a way that would provide an alternative to a Custom Upstream. 

## Suggested Resolution 
Explain how the GitHub PR workflow can be used as a substitute for a Custom Upstream where the goal is to provide a single core codebase for many sites, rather than for a single site.

**Comment by alexfornuto** [comment]
Closing, to be addressed along with #2665
