### ISSUE TITLE
Timeouts on Pantheon Doc Update

### ISSUE THREAD

**Issue by joeparsons** [pantheon-systems/documentation#2753]
Re: [Timeouts on Pantheon](https://pantheon.io/docs/timeouts/)
## Issue Description
The `settings.php` snippet suggested as a workaround for Migrate module timeouts does not seem to work.  When I reached out to Pantheon support about this issue, they suggested I try a different drush path in the `settings.php` snippet:
```
$conf['migrate_drush_path'] = $_ENV['HOME'] . '/drush';
```
## Suggested Resolution
Correct drush path in `settings.php` snippet.

**Comment by alexfornuto** [comment]
Related to case/87433

**Comment by alexfornuto** [comment]
Thanks @joeparsons!
