### ISSUE TITLE
Managing Custom Code with Composer Doc Update 

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/documentation#2758]
Re: [Managing Custom Code with Composer](https://pantheon.io/docs/composer/)

Priority (Low):

## Issue Description:

This page seems out of date, and seems like it might be partially deprected by the Drupal 8 Composer doc. 

## Suggested Resolution 

We should probably consider structuring a small tree of docs around using Composer to manage sites on pantheon. First an overview, and then specific instructions for Drupal 8 and WordPress. TBD if we want to have a doc for Drupal 7 since that's a more unusual case.

This should help people find the right upstream, the build tools plugin, etc.

**Comment by alexfornuto** [comment]
+1 Work planned as part of #2665
