### ISSUE TITLE
Launch Essentials Doc Update on Wordpress Redirects.

### ISSUE THREAD

**Issue by albertcausing** [pantheon-systems/documentation#2760]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/redirects/)

Medium

## Issue Description:
currently, the redirection codes snippet for wordpress has this.

```
  define('WP_SITEURL', $base_url);
  define('WP_HOME', $base_url);
```

Which is already a defined within wp-config.php, this means calling this function again will have a conflicting issue of not able to redefine a constant.
https://github.com/pantheon-systems/WordPress/blob/master/wp-config.php#L78-L79
_
> Notice:  Constant WP_SITEURL already defined in line ....
_

http://php.net/manual/en/function.define.php

## Suggested Resolution 

Change it to a variable, don't redefine again, or we can have more specific instructions on how to use the snippet.

**Comment by alexfornuto** [comment]
Discussion on this issue is in progress at #2405
