### ISSUE TITLE
Can't pull down site with Kalabox

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#2762]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High): Low

## Issue Description:
Kalabox testing on windows - user reports kalabox not behaving as expected on windows environment.

## Suggested Resolution 
Test and update docs if there is a known issue

**Comment by rachelwhitton** [comment]
Should we update our docs from Kalabox to Lando? Or should that wait until Lando ships with a GUI? @newtoid @dustinleblanc

**Comment by dustinleblanc** [comment]
I personally believe that Lando is a better project, without the GUI, they just entered Beta, I don't know if we have a policy on supporting pre-release at all.

**Comment by newtoid** [comment]
Support case #87660 mentioned that they tried both with no success, I don't know if this is related to their specific windows setup or something else.

**Comment by alexfornuto** [comment]
There's a related issue on the Kalabox repo, with a comment that may or may not have the resolution for this issue: https://github.com/kalabox/kalabox/issues/1826

**Comment by alexfornuto** [comment]
According to [this](https://github.com/kalabox/kalabox/issues/1826#issuecomment-331221686) Kalabox is no longer addressing outstanding issues like this one, focusing instead on Lando. At this point I think that the best resolution is to replace out Kalabox documentation with Lando, assuming that Lando is ready for prime time.

**Comment by alexfornuto** [comment]
Removing Blocked and adding SME. Anyone is welcome to confirm Lando's functionality. Once we're satisfied with it, we can start replacing https://pantheon.io/docs/kalabox/ with https://pantheon.io/docs/lando/

**Comment by rachelwhitton** [comment]
Let's hold off on Kalabox work in the docs.
