### ISSUE TITLE
Enabling Solr for WordPress Doc - url for solr-wordpress

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2764]
Re: [Enabling Solr for WordPress](https://pantheon.io/docs/wordpress-solr/)

Priority (Low):

## Issue Description:
Need to have a redirect for wordpress-solr and solr-wordpress docs URL.

## Suggested Resolution 
we have 
/solr
/solr-drupal-7
/solr-drupal-8
/solr-wordpress <--- new url

**Comment by alexfornuto** [comment]
@eabquina Are you suggesting that we change the url for `/wordpress-solr` to `/solr-wordpress` and make a redirect, simply to match the URL format of the other docs, or are you saying that there are links being used by CSE that aren't working?

**Comment by eabquina** [comment]
@alexfornuto all of the above! the url /solr-wordpress shows Page Not Found. 
Suggesting to:
- Change URL to /solr-wordpress
- Redirect /wordpress-solr to the new URL

**Comment by alexfornuto** [comment]
@eabquina  It's Page not Found because that was never the URL where is CSE getting that link from?. @rachelwhitton, what are your thoughts on changing this URL to match the others?

**Comment by rachelwhitton** [comment]
Let's not move the page. I added a redirect for `solr-wordpress`, that should be sufficient
