### ISSUE TITLE
Varnish Caching for High Performance with Drupal and WordPress Doc Update 

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#2767]
Re: [Varnish Caching for High Performance with Drupal and WordPress](https://pantheon.io/docs/varnish/)

We should probably update (and move) this to focus on Global CDN and de-emphasize Varnish. The content can, otherwise, stay mostly the same.

**Comment by rachelwhitton** [comment]
Thanks for reporting, +1 

We can widen the scope of this issue to track updates to legacy edge content throughout, since this applies to more than one page.

**Comment by rachelwhitton** [comment]
Tracked in the [Cache Content Audit](https://github.com/pantheon-systems/documentation/projects/7) Project
