### ISSUE TITLE
Site Team Management Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2770]
Re: [Site Team Management](https://pantheon.io/docs/team-management/)

Priority (Medium):

## Issue Description:
Unclear for user if adding Team Members and changing roles can be done compared to "organization"

## Suggested Resolution 
Clarify if this can only be done by Site Owners

**Comment by alexfornuto** [comment]
Whoever takes this should probably look at #2773 at the same time.

**Comment by alexfornuto** [comment]
closed by #2798
