### ISSUE TITLE
How to Disable New Relic Pro on specific environment 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2771]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/)

Priority (Low):

## Issue Description:
User needs a way to disable New Relic (like the site page code)

## Suggested Resolution 
Need to highlight that this is not recommended as it will be difficult for Pantheon and customers to check issues for performance to their site

As a workaround, provide a sample snippet or code switch, to disable a site environment for New Relic (for edge case)

**Comment by alexfornuto** [comment]
I think that the information added in #1647 could be duplicated and generalized in it's own section under troubleshooting on how to disable New Relic. Would you agree @rachelwhitton?

**Comment by rachelwhitton** [comment]
I'd avoid duplication, but yes. I think we just need to widen the scope of this section to disabling new relic, keeping the Google AMP Validator issue in as an example scenario

**Comment by alexfornuto** [comment]
++
