### ISSUE TITLE
Bug in Code Snippet

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2774]
Re: <https://pantheon.io/docs/myisam-to-innodb/#advanced-method-via-command-line>
## Issue Description
1. Reader reports:

    > This was super helpful, but there is a bug in this script. Line 35 of "Advanced Method via Command Line" should have a closing curly brace before the final double-quote. 

2. Reader reports:

    > Not entirely clear if I need to run one of the scripts in addition to running the DB query. Assuming no, but it'd be nice to see this spelled out in a little more detail for the user.

## Suggested Resolution

1) Test and resolve.

2) Clarify

**Comment by newtoid** [comment]
There is defo a bug here, it looks like the extra single quote, but fixing it shows further issues also.

**Comment by ttrowell** [comment]
OK- I tested this.
 This is the line that needs to be corrected to the version below: (#34?)
`$sql = "SHOW TABLE STATUS WHERE Name = '{$row['Tables_in_' . $db['database']]}'";`
