### ISSUE TITLE
MySQL "my.cnf" configuration variables

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2776]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access/)

Priority (Medium):

## Issue Description:
User asks for what can be configured for their account for MySQL configuration. 
For one user "max_allowed_packet". Time out docs only provide process related 

## Suggested Resolution 
Create a new doc about "database-configuration" ?

**Comment by rachelwhitton** [comment]
There's not enough info here to act on, we'll need more details and a comprehensive outline in order to deliver. Rejecting for now, but entirely open to revisiting this once more info is collected.

**Comment by jameswilson** [comment]
I was also looking for documentation around what the max_allowed_packet  value is set to.  This would be akin to providing similar documentation around the default settings pantheon uses.  

For comparison, default PHP values are documented, but why not MySQL?

https://github.com/westonruter/pantheon-documentation/blob/master/source/docs/articles/drupal/session-and-cookie-handling.md
