### ISSUE TITLE
New Doc Proposal: ClamAV

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2780]
Priority (Low‚ Medium‚ High): Low

## Title
Enabling ClamAV with WordPress or Drupal

## Description
Scan for malware and other potential threats in Wordpress or Drupal using ClamAV, an open source antivirus engine.

## Outline
Intro / summary of why
WordPress
Drupal 7 & 8 
Conclusion

## Path
`source/_docs/clamav.md` 

Refer to config suggested in chat 11261049093 cc @newtoid

**Comment by alexfornuto** [comment]
Closing as a duplicate of #1913
