### ISSUE TITLE
Security on the Pantheon Dashboard Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2801]
Re: [Security on the Pantheon Dashboard](https://pantheon.io/docs/security/)

Priority (Low‚ Medium‚ High):

## Issue Description:
User looks for "Vulnerability" scanning features which we don't have.
Comparing the https://pantheon.io/docs/security versus https://pantheon.io/security, user seem to expect to find here a similar guide on how to

## Suggested Resolution 
Highlight that this page is about dashboard security. Try to change URL to /docs/dashboard-security  and note website security

A redirect also about "Site Security" where we list down all our recommendations, partners etc.

**Comment by rachelwhitton** [comment]
+1 

I can see this being confusing to folks looking for penetration/vulnerability/av kinda stuff. We do have a few open issues for adding that content in #2780 and #1654 so providing recommendations and crosslinking may not happen until those are worked

I'm not sure we need to change the URL, but we should tweak the intro so it's easier to tell what the page is about sooner. Maybe a screenshot above the fold
