### ISSUE TITLE
Updates and Clarifications to Drush Site Import

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2819]
Re: [Importing Drush Site Archives with Terminus](https://pantheon.io/docs/drush-import/)
## Issue Description

 - Update referred Drush versions to 7 & 8.
 - Clarify before `site:import` that you need an existing site on your account first.

**Comment by llubao** [comment]
"Update referred Drupal versions to 7 & 8." 
- Just wanted to clarify, if this means here, not Drupal but Drush versions 7 & 8

**Comment by alexfornuto** [comment]
@llubao From the page.

>A working local Drush installation that is up to date with 5.x or 6.x stable.

So yes, good catch, I'll edit the description.
