### ISSUE TITLE
Introduction to Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2821]
Re: [Introduction to Custom Upstreams](https://pantheon.io/docs/custom-upstream/)

Priority (Medium):

## Issue Description:
User wants to update "Existing Sites to use their new Custom Upstream"
The docs don't say actually how to do this, if either by recreating the site or manage a configuration file

## Suggested Resolution 
Create sample on how to update an existing site to use a new Upstream
This is possible using Terminus, and need to have a section that shows this (copy from Terminus docs)

**Comment by eabquina** [comment]
Turns out we can do this if we use "Terminus" to Switch Upstreams as found here: 
https://pantheon.io/docs/terminus/examples/#switch-upstreams

**Comment by rachelwhitton** [comment]
We don't have content on how to create/edit/maintain on the intro page, since that page is meant to simply introduce the feature. We discuss the ability to switch upstreams on the [next page](https://pantheon.io/docs/create-custom-upstream/#switch-the-repository-url)
