### ISSUE TITLE
Sites with Redis serve stale compiled CSS files

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2832]
Re: [Installing Redis on Drupal](https://pantheon.io/docs/drupal-redis/)

Priority (Low‚ Medium‚ High): Low/medium

## Issue Description:
_Something_ can cause the site to load stale CSS files resulting in 404s on stylesheets, and for some reason clearing Redis cache resolves. 

Not sure if the issue is with Redis itself, or if it's a symptom of something else.

Also not sure if this problem exists on D8/WP (I observed it on pantheon.io D7 after clearing cache on Live in the Site Dashboard)

## Suggested Resolution 
Use doc block time to investigate issue so it can be replicated, then document recommended fix (which could just be to clear Redis cache from the command line)?

**Comment by dustinleblanc** [comment]
Still working on reproducing

**Comment by rachelwhitton** [comment]
@dustinleblanc based on your efforts, should we close as cannot replicate?
