### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2844]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority (Low):

## Issue Description:
User asks where to find in the docs possible "--fields" for every command

## Suggested Resolution 
Create a table of Fields possible for all commands like workflow, org, etc
Also need to be clear if the default, that not putting "--fields" means we are showing ALL fields already rather than restricting the list

**Comment by ttrowell** [comment]
@TeslaDethray is there a reference to this data that we could review for relevance?

**Comment by rachelwhitton** [comment]
@ttrowell you can see a dump here: https://pantheon.io/docs/assets/terminus/commands.json this is what the docs use to render to table and it's generated during a build step on CircleCI 

@sehamilton @kimby77 what do ya'll think?

**Comment by kimby77** [comment]
I have no opinion other than a word of caution for making a change based on only 1 user request.  If you start getting several requests for this, that is more indicative the need is really there.

**Comment by rachelwhitton** [comment]
My biggest concern is keeping the table readable. If we include fields, does that mean we should also include arguments and other options like element or format? IMO it's best to leave this up to terminus help output so we don't create a messy table. 

Here's a screenshot of what this would look like in it's own column: 
![screencapture-localhost-8000-docs-terminus-commands-1505151497234](https://user-images.githubusercontent.com/10119525/30288413-3d510d96-96ee-11e7-8db9-10a27b4f8670.png)

And here's how it would look if we amended the usage column:
![screencapture-localhost-8000-docs-terminus-commands-1505151700608](https://user-images.githubusercontent.com/10119525/30288528-aa7fa3dc-96ee-11e7-851c-fa13d01cb0f1.png)

I'm not opposed to changing this table, I just want to consider the impact to readability. Maybe the resolution to this issue could be a note towards the top of the page suggesting the user run help on commands they want to know more about?

**Comment by kimby77** [comment]
Yeah, thumbs down to both these layout options.

The note idea seems simplest to add right now, and just adding a sentence should be ok.  Then the instruction is there for people who really need this.

**Comment by rachelwhitton** [comment]
Note: I used `{[{ command.definition.options.fields.description }]}` to add fields data from the json dump (incase I forget)
