### ISSUE TITLE
Using Extensions That Assume Write Access Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2845]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access/)

Priority (Low):

## Issue Description:
User sees "create symlink via SFTP" via command line. Wanted to be sure if this is actually an alternative way of making symlink other than pushing via Git

## Suggested Resolution 
Create alternative way to create symlink that uses or done via SFTP mode (command line) if it is actually possible. Also confirm if that works or not

**Comment by ttrowell** [comment]
I voted for removing reference to doing this via SFTP.  From what I am reading (https://stackoverflow.com/questions/5589489/create-symbolic-links-on-server-without-ssh-available), this is not widely used (if at all) and not supported in Filezilla. https://forum.filezilla-project.org/viewtopic.php?t=29607

WinSCP ref from 2008 (https://winscp.net/eng/docs/task_link)   - still not compelling IMHO.

**Comment by eabquina** [comment]
@ttrowell Noted, and I guess we can instead cite these and explicitly say we won't recommend using that via sftp symlink command. 

But let me try it again to test.

**Comment by alexfornuto** [comment]
> User sees "create symlink via SFTP" via command line.

@eabquina where is the user seeing this?

**Comment by eabquina** [comment]
@alexfornuto To get there:

1. Do SFTP via CLI (`sftp -o Port=2222 dev.<site-id>@appserver.<site-id>.drush.in`)
2. `?` for list of available commands
3. Commands `ln oldpath newpath  Symlink remote file` and `ln oldpath newpath            Symlink remote file`

Completed testing, finally tried without "-s" and gave me a different message saying SERVER doesn't support it;

`sftp> ln ./wp-content/uploads/test ./wp-content/test
Server does not support hardlink@openssh.com extension
sftp> ln -s ./wp-content/uploads/test ./wp-content/test
Couldn't symlink file "./wp-content/uploads/test" to "/srv/bindings/9a0322c38a9e4f0ca825eeac5cd20e7b/code/./wp-content/test": No such file or directory`

This is not working

**Comment by alexfornuto** [comment]
The message you get without `-s` doesn't really factor in, since the `-s` means "symbolic", which is the only kind of symlink you would want to make. Without it, ln makes a hard symlink, which is essentially telling the filesystem to treat both locations as the exact same file.
