### ISSUE TITLE
WPML is no longer blocking cashing

### ISSUE THREAD

**Issue by jakub300** [pantheon-systems/documentation#2849]
Re: [Modules and Plugins with Known Issues](https://github.com/pantheon-systems/documentation/blob/5b36930a260041d83caaf8c35b2588c59ab8c692/source/_docs/unsupported-modules-plugins.md#wpml---the-wordpress-multilingual-plugin)
## Issue Description
**Issue 2** was [fixed in WPML 3.7.0](https://wpml.org/version/wpml-3-7-0/).

## Suggested Resolution
Remove **Issue 2**.

**Comment by alexfornuto** [comment]
Thanks @jakub300!
