### ISSUE TITLE
Single Sign-On for Pantheon Organizations Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2850]
Re: [Single Sign-On for Pantheon Organizations](https://pantheon.io/docs/sso-organizations/)

Priority (Low‚ Medium‚ High):

## Issue Description:
"Example-Org-Name-SSO should be replaced with each logged-in user's actually Org Name, since it's not listed in the account."
## Suggested Resolution 
Review issue and clarify in the doc as needed

**Comment by alexfornuto** [comment]
@newtoid can we get your expertise on this?
