### ISSUE TITLE
Audit for setting.php pages.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2851]
Re: [Configuring Settings.php](https://pantheon.io/docs/settings-php/) & [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/)
## Issue Description

Content may be out of date, and not cover Drupal 8. Also, when creating the `settings.php` file (or `default`) manually, specific permissions need to be set.

## Suggested Resolution

Audit the guides, and identify needed permissions.

**Comment by rachelwhitton** [comment]
Rejecting this one for now, but do agree some content is likely stale. Audits to determine gaps and stale content should be cyclical and tracked outside the github issue queue (maybe we could use a github project instead?). As a general rule, let's keep issues in the queue specific and actionable.

@alexfornuto let me know if you disagree
