### ISSUE TITLE
WordPress in a Sub-directory

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2855]
Re: new-docs

## Issue Description
User asks if its possible place WordPress in a subdirectory in a dev site.
Not like a nested docroot project, but simply under a directory of its own.

## Suggested Resolution
Check and test the Codex docs as found here: 
https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory#Method_II_.28With_URL_change.29

So far, initial installation seems to be working; 
http://live-subfolder-test.pantheonsite.io/resources/
admin : admin

So far, the steps would be:

- Copy index.php of WordPress and update the subdirectory
- Manually update WP_HOME and SITEURL with the subdirectory
- Moving the uploads folders, includes the files path symlink to ./files directory
- SOLR, WP Native Sessions, seems to be working

Need to 'debunk' this if this will actually work, and what will not; 

- Caching will not work, "This does not seem to be a WordPress install", unless cleared via WordPress, no error encountered
- Redis seems to be not working completely
- Guide from WordPress doesn't "redirect" user to /sub-directory

Requesting more peer review.

**Comment by rachelwhitton** [comment]
Hmm, sounds like a turducken site? [Serving a site from a subdirectory of another application isn't supported](https://pantheon.io/docs/platform-considerations/#one-application-per-site) 

The site should be served from it's own FQDN (e.g., resources.example.com instead of example.com/resources). The workaround for this is to use domain masking, which requires a third party CDN provider and a big budget (for HTTPS).

@eabquina am I understanding the request correctly? I might be getting this use case mixed up 

Leaving this open for additional CSE feedback. IMO we should reject, but if we do continue working on this it needs to be signed off by product before release. 

cc @alexfornuto

**Comment by alexfornuto** [comment]
I agree with @rachelwhitton - what other use case is there for putting all of WP in a subdir?

**Comment by eabquina** [comment]
@alexfornuto  @rachelwhitton  I think that section could be it, and just highlight what we'd do if one site actually tried doing this. We can add in this section that we; recommend to them reverting (and split sites), tell the stuff that will not work (cache, file structure) and that they can't get support (unless separate the applications). 

Because of the Codex guide from Wordpress, some folks may follow it and discover that it may actually work (and figure it out themselves). We can explicitly say that "having a subdirectory" site is not allowed.

Also for Domain Masking, this is actually their plan.  They "require" that the subdirectory be literally there after the FQDN to make their configuration work for domain masking (via an external provider). They actually have an existing "parent" site outside the platform. 

And yes, this will let them have Drupal + WordPress sites on one subscription. They would want that when doing a subsite like a "/blog" page. But it turns out to be possible as well: 
- D8 - http://live-d8-wp.pantheonsite.io/
- WP - http://live-d8-wp.pantheonsite.io/blog/

You are right that this is a product concern. Aside from the upfront docs that we will not allow or support it, but would we actually put safeguards in the dashboard for them to avoid it? 

Note: I realized that having Custom Upstreams mean they can try this out. It would be helpful if the docs are more explicit for we can cover; if we won't allow it, or do we mean they are on their own for making this work.

**Comment by ttrowell** [comment]
I Agree that a site in this state is Turdurken!

If we need to add language to warn users against it and that it's not supported - great.

The platform is not designed to handle this and the site will fall completely out of Scope of Support and the warranty of uptime is negated.  

They must use two separate sites - but the masking process is still an outstanding convern.

**Comment by rachelwhitton** [comment]
Further documentation on domain masking should come with or after the next set of releases for the Global CDN. I do agree that domain masking and stacked CDNs are big gaps in the current docs, but I think it's best to plan/track the work as part of the upcoming product sprint(s) so it's a designed and supportable process. Closing in favor of handling it in the product pipeline
