### ISSUE TITLE
September/October Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2858]
Add September platform changes and new features to be included in the September/October Changelog.

**Comment by greg-1-anderson** [comment]
wp-cli 1.3.0: https://github.com/pantheon-systems/rpmbuild-wp-cli/pull/10

**Comment by alexfornuto** [comment]
@greg-1-anderson and our platform now uses that version for `terminus wp`?

**Comment by greg-1-anderson** [comment]
Yes.

**Comment by ari-gold** [comment]
New Relic Agent updated to 7.5.0.199. Contains Drupal
Release notes: https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-750199
Previous version installed on Pantheon was 6.8.0.17

Includes Drupal-related fixes from 7.4.0.198: https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-740198

**Comment by ari-gold** [comment]
Version 0.6.3 of WP Native PHP Sessions Released: 
https://wordpress.org/plugins/wp-native-php-sessions/
Fixes https://github.com/pantheon-systems/wp-native-php-sessions/issues/74

**Comment by alexfornuto** [comment]
New updates should go to #2959
