### ISSUE TITLE
HTTPS on Pantheon's Global CDN Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2862]
Re: [HTTPS on Pantheon's Global CDN](https://pantheon.io/docs/https/) or does this go in Launch Guide?

Priority (Low‚ Medium‚ High): Medium

WP Engine doesn't allow serving the ACME challenge required to pre-provision HTTPS. Skip to updating DNS and plan for a 1hr maintenance window. HTTPS will be ready within an hour after DNS routes to Pantheon.

**Comment by rachwhitts** [comment]
+1 Yeah, it'll need to go here: https://pantheon.io/docs/guides/launch/domains/

We can add a section for sites unable to verify recommending a maintenance window. thanks for reporting

**Comment by rachelwhitton** [comment]
Woops, forgot I was logged into a test account ^ 🙃
