### ISSUE TITLE
Decoupled CMS New Doc

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2872]
Re: /docs/decoupled-cms/
## Issue Description
Customer is trying to build a "decoupled CMS" in their site. In this specific example, index.html in code-root, but won't work because index.php is delivered first by the web server.

## Suggested Resolution
Need to confirm and highlight if this is actually possible or not, or in the future product pipeline.

So far, we can be guided here: 
https://pantheon.io/docs/platform-considerations/#one-application-per-site
https://pantheon.io/docs/platform-considerations/#general-php-framework-support

For confirmation as per last ticket 89023

**Comment by alexfornuto** [comment]
@eabquina would you be able to write this doc?

@pantheon-systems/cse how frequently do we get tickets about this issue?

**Comment by eabquina** [comment]
@alexfornuto I can try to make a new one. But, wanted to check with you if this should initially part of /platform-considerations as not supported? 
I realized this is also related to issue #2874 (WordPress Roots Bedrock composer build) which usually come out as headless WP too.

**Comment by alexfornuto** [comment]
@joshkoenig would you care to weigh in on if this is something we want to take a stance on in the docs at this time?

**Comment by joshkoenig** [comment]
This is a pretty sprawling topic. If we do it we should keep the scope constrained for now. I'd almost prefer a doc on "running a CMS as an API on Pantheon" instead.

That said - the `index.php` over `index.html` question _feels_ like a bug that could be corrected.
