### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2874]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/create-project/)

Priority (Low):

## Issue Description:
Support for WP Composer build Roots Bedrock (roots.io/bedrock)
Roots is required to run in web docroot, but has another subfolder
This was found as a project base by an agency partner

## Suggested Resolution 
Review if the advice is just to have symlinks created for this, or can be supported as part of Built Tools

**Comment by rachelwhitton** [comment]
Hm, I'd rather not mention Roots Bedrock in this guide unless we're able to do it in a way that allows the site to run Pantheon's WP core with a defined update strategy. I don't know much about Roots Bedrock, but unless it can run our version of core I don't think it's a good candidate for docs.

The nested doc root page does suggest users can create a symlink if they want to use a directory other than `web`, seems best to just refer folks to that page? https://pantheon.io/docs/nested-docroot/#troubleshooting

@ataylorme @stevector what do you think?

**Comment by ataylorme** [comment]
@rachelwhitton Bedrock uses Composer so it would be pretty easy to swap out `"johnpbloch/wordpress": "4.8.1",` for `"pantheon-systems/wordpress-composer": "^4.8.1",` but there are other modifications, such as those in [`composer-cleanup`](https://github.com/pantheon-systems/example-wordpress-composer/blob/master/scripts/composer/cleanup-composer) that would also need to be done to make it work.

There aren't that many differences between Bedrock and [`example-wordpress-composer`](https://github.com/pantheon-systems/example-wordpress-composer/) but enough that it's not a quick port. I think someone familiar with Bedrock could easily adopt `example-wordpress-composer` though.

**Comment by rachelwhitton** [comment]
Cool, thanks for the info! Closing this issue for now in favor of existing recommendations to use https://github.com/pantheon-systems/example-wordpress-composer
