### ISSUE TITLE
New Content Proposal - Build tools docs

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/documentation#2886]
This is not a request for a new doc; it's a request for additional info on a current doc.

## Title
How to import config before running Circle CI tests

## Description
I followed the build tools guide here: https://pantheon.io/docs/guides/build-tools/merge/
However, sometimes I write a test that requires new config to be imported; I would like to do this automatically when I make a pull request on github, but I don't know how to do so.

**Comment by alexfornuto** [comment]
@greg-1-anderson @stevector @AndrewKWilson can any of you weigh in on this idea?

**Comment by stevector** [comment]
Config imports should be happening already.

We just converted `example-drops-8-composer` to use Circle 2.0. The imports happen here: https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/scripts/pantheon/02-init-site-under-test-clone-existing#L21

In Circle 1, that import happened here: https://github.com/pantheon-systems/example-drops-8-composer/blob/001140d0e46e03640b76c86fd34d53b723db4e83/circle.yml#L61

We are planning on switching the config import to a quicksilver script: https://github.com/pantheon-systems/example-drops-8-composer/issues/112

**Comment by ptmkenny** [comment]
I see.  I had to add a line to `circle.yml` to force config import again, so I'll try to figure out why it wasn't happening in the first place.
