### ISSUE TITLE
AWS Drupal 8 module error.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2890]
Re: [AWS S3 Setup for Drupal](https://pantheon.io/docs/drupal-s3/#install-required-and-recommended-modules/)
## Issue Description

From the feedback form:

```
Can't install drupal/s3fs_cors. Error:

Problem 1
    - drupal/s3fs_cors 1.x-dev requires drupal/token 2.0.x-dev -> no matching package found.
    - drupal/s3fs_cors 1.x-dev requires drupal/token 2.0.x-dev -> no matching package found.
    - Installation request for drupal/s3fs_cors 1.x-dev -> satisfiable by drupal/s3fs_cors[1.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

## Suggested Resolution

Test to confirm and resolve.

**Comment by alexfornuto** [comment]
I've confirmed this issue, and begun experimenting with [possible solutions](https://www.drupal.org/project/s3fs_cors/issues/2803245#comment-11886563), but no luck so far.

**Comment by rachelwhitton** [comment]
Warning added to relevant section of the doc with link to [outstanding issue](https://www.drupal.org/project/s3fs_cors/issues/2852333) on the project page. Keep this issue open to track issue and remove warning once resolved.

**Comment by alexfornuto** [comment]
Tested again, found that while the bug in question was resolved, the D8 module is [still not working](https://www.drupal.org/project/contrib_tracker/issues/2635842).
