### ISSUE TITLE
Enabling Solr on Drupal 8 Doc Update 

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#2894]
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8/)

Priority: Medium

## Issue Description:
This document instructs users to install a module via Composer. If a user does this on a vanilla Drops 8 site they will break one-click updates.
## Suggested Resolution 
Include a warning about upstream updates and direct user to Composer documentation to make sure they understand how to 'take the plunge' and fully manage their site with Composer.

**Comment by alexfornuto** [comment]
While a little research/testing is needed, I think we're going to use tabs to show both avenues of installation, Composer and non-composer. The Composer method will include a "gotcha" statement referencing our new composer workflow guide.
