### ISSUE TITLE
Terminus Plugins to Add to the Plugins directory.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2895]
Re: [Terminus Plugin Directory](https://pantheon.io/docs/terminus/plugins/directory/)
## Issue Description

The following plugins are awaiting placement in the plugin directory:

 - Terminus Upstream Deployment
 - Backup All
 - Site Mount
 - Upstream Testing
 - Upstream Deployment
 - Push Code
 - [newrelic-data](https://github.com/pantheon-systems/documentation/pull/2928)

## Suggested Resolution

Pending an official review process and/or policy, review and add these plugins to the directory.

**Comment by greg-1-anderson** [comment]
Any project at https://github.com/terminus-plugin-project that has a stable release on packagist should be ready for review here.

**Comment by alexfornuto** [comment]
@greg-1-anderson do we have a review process yet?

**Comment by greg-1-anderson** [comment]
I have no information on this.

**Comment by alexfornuto** [comment]
@TeslaDethray do we have a review process yet to accept new plugins?

**Comment by greg-1-anderson** [comment]
It doesn't look like there has been any movement on the Jira card: https://getpantheon.atlassian.net/browse/AL-794

**Comment by rachelwhitton** [comment]
After further consideration, the docs will no longer promote plugins in a directory. See: AL-1304
