### ISSUE TITLE
Add A/AAAA records if adding CNAME not possible

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2899]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
MX or TXT DNS record prevents addition of CNAME record

## Suggested Resolution 
If your domain has a MX or TXT record and prevents the use of a CNAME, as recommended by the site dashboard, add A and AAAA records. To find the required values for the A and AAAA records either a) add a placeholder domain like example.com to the site dashboard or b) dig the platform domain:

A record:
`dig +short live-example.pantheonsite.io | tail -1`

AAAA records:
`dig +short live-example.pantheonsite.io AAAA | tail -2`

Note that different sites will have different required values, so do not rely on values for one site for another.

**Comment by kf6nux** [comment]
On a related note, we should tell customers what we require from them.  Perhaps something along the lines of:
```
Requirements for contiguous Managed HTTPS:
- All A/AAAA records must point to a server that serves Pantheon's acme-challenge response (e.g. http://23.185.0.1/.well-known/acme-challenge/[variableDataHere] )
- Authority Name Servers must serve mixed-case lookups.
- Authority Name Servers must not fail CAA lookups.
- CAA records must either 1) not exist or 2) authorize Let's Encrypt.
- CNAMEs must follow the above requirements
- DNAMEs must not be used.

Please check this doc periodically as requirements may be added or removed.
```

**Comment by alexfornuto** [comment]
This information is currently proposed on the Switch DNS guide, [here](https://fixdetermi-static-docs.pantheonsite.io/docs/switching-dns/#determine-the-new-dns-records). @ari-gold @kf6nux Do you think it belongs in this Domains and Redirects more than in Switching DNS? Or should we include the information in both, or link from one to the other?

@rachelwhitton your input on this would be most welcome.

**Comment by ari-gold** [comment]
@alexfornuto I'm +1 on moving it to Domains and Redirects and linking to it from a) Switch DNS and b) Launch guide

Also would be great if we can include both methods of a) adding placeholder domain and b) using dig/nslookup (make sure can get all required values A and AAAA)

Also the comment from @kf6nux is important to document, but a separate issue from this one.
