### ISSUE TITLE
Getting Started with WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2908]
Re: [Getting Started with WordPress Site Networks](https://pantheon.io/docs/create-wordpress-site-networks/)

Priority (Low):

## Issue Description:
Customer is following the guide about setting up DOMAIN_CURRENT_SITE, but wants to have forced HTTPS redirect. The guide doesn't explicitly show if that was possible for a Site Network context
 
## Suggested Resolution 
Place the link for the new domains/redirects snippet code and include sample for per domain and environment conditional

**Comment by alexfornuto** [comment]
@adamedgmond do you know about any gotchas to consider when forcing HTTPS for site networks?

**Comment by adamedgmond** [comment]
@alexfornuto Ensure all Site URLs in content aren't http:// (because of the redirect issue)

**Comment by alexfornuto** [comment]
@eabquina @adamedgmond The real question here is: does this need specific documentation, or can we link [here](https://pantheon.io/docs/http-to-https/#redirect-to-https-and-the-primary-domain)?

**Comment by eabquina** [comment]
@alexfornuto @adamedgmond This is also useful, so all their content will be replaced to "http://"

However, the use case is to have a forced redirect if they visit "http://" site for any domain, and instead use "https://". 

The quick solution was to just redirect any URL visited like this:

```
if (isset($_SERVER['PANTHEON_ENVIRONMENT']) && php_sapi_name() != 'cli') {
    # Name transaction "redirect" in New Relic for improved reporting (optional)
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://'. $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
    exit();
}
```
Should this be fine? Or should there be a consideration to DOMAIN_CURRENT_SITE somewhere here? 

Note: The "primary_domain" is not good for use in site networks, as they'll be forced to a single domain per environment (and as tried by customer).
