### ISSUE TITLE
Moar Emoji questions

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#2909]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority: Low

## Issue Description:
The docs now say that emoji support is possible on Pantheon but we don't allow for manipulation of the database settings array, which seems to contradict the documentation we link on Drupal.org. We need to carify steps to enable support on Drupal 7 or explicitly state that this is for new sites, etc.

See Intercom #11913822825

**Comment by rachelwhitton** [comment]
Related to IO-2565 and #2380

**Comment by bentekwork** [comment]
There is an additional issue when attempting to import an existing database dump into Pantheon.  All `CREATE TABLE ..`. statements will need the `ROW_FORMAT=DYNAMIC` flag added otherwise an error is thrown `ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 byte`

**Comment by dustinleblanc** [comment]
Figured out the magic:

in settings.php:
```php
$databases['default']['default']['charset'] = 'utf8mb4';
$databases['default']['default']['collation'] = 'utf8mb4_general_ci';
```

Then run this bad boy on the database: https://www.drupal.org/project/utf8mb4_convert

Then add poop to your pages: http://dev-dustins-d7.pantheonsite.io/node/3

**Comment by dustinleblanc** [comment]
I've been able to reproduce this on two existing d7 sites.

@rachelwhitton @alexfornuto The way to make this work doesn't really fit in platform considerations, is there another doc that is better for this?

**Comment by alexfornuto** [comment]
👀 ing

**Comment by dustinleblanc** [comment]
https://www.jeffgeerling.com/blog/2016/getting-emoji-and-multibyte-characters-on-your-drupal-7-site-750 was helpful in researching fyi

**Comment by dustinleblanc** [comment]
Will add new doc during next doc block or that can be assigned out to another @pantheon-systems/cse member if they can parse the needed steps from my notes above

**Comment by alexfornuto** [comment]
It works! 
![screen shot 2017-10-03 at 1 16 45 pm](https://user-images.githubusercontent.com/2349184/31138670-448f6804-a83d-11e7-99ec-e0d8df7906c7.png)

**Comment by pmackay** [comment]
@dustinleblanc could you please add a link here to the relevant Pantheon docs that describes how to upgrade a database to support this? Thanks!

**Comment by alexfornuto** [comment]
[BAM](https://pantheon.io/docs/platform-considerations/#emoji-support)!
