### ISSUE TITLE
Request for Terminus "newrelic-data" plugin to be added in the plugins directory

### ISSUE THREAD

**Issue by fusionx1** [pantheon-systems/documentation#2927]
Re: https://pantheon.io/docs/terminus/plugins/directory/
## Suggested Resolution
Name of the Plugin - Newrelic-data
Github repo - https://github.com/fusionx1/terminus-get-newrelic
Project Description - https://github.com/fusionx1/terminus-get-newrelic/blob/master/README.md

**Comment by alexfornuto** [comment]
Closing this in favor of a single issue to track all plugins awaiting entry: #2895
