### ISSUE TITLE
1 & 1 Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#2930]
Priority (Low‚ Medium‚ High): Medium

https://pantheon.io/docs/1-and-1/

Is it possible to add two AAAA records in 1 & 1?

customer provided screenshot: 
![image](https://user-images.githubusercontent.com/7874556/30928214-c979859a-a36f-11e7-8760-ba63b8402db4.png)

ref. 
case/90264
case/91765

**Comment by alexfornuto** [comment]
I've confirmed that you can only add one AAAA record to their DNS system.
