### ISSUE TITLE
Terminus running Composer

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2933]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority (Mediu):

## Issue Description:
In the docs page, composer is not an available command. But actually, it is something that we can use just like drush or wp cli

```
terminus composer site-name.dev -- install
terminus composer site-name.dev -- update
terminus composer site-name.dev -- --version
```

## Suggested Resolution 
Confirm if this is allowed and include in the list.
Also consider updating /docs/composer to include Terminus method

**Comment by alexfornuto** [comment]
@eabquina the commands listed in /terminus/commands are pulled from the terminus cli manual. If it's not included there, it won't be here. Perhaps a feature request to the Terminus team is the best step forward?

**Comment by alexfornuto** [comment]
I discovered that this requires the Terminus Composer plugin, so it's not part of Terminus' standard commands. It's also problematic, and not the recommended way to use Composer on Pantheon.
