### ISSUE TITLE
Parsing nginx Access Logs with GoAccess Doc Update 

### ISSUE THREAD

**Issue by hengkit** [pantheon-systems/documentation#2941]
Re: [Parsing nginx Access Logs with GoAccess](https://pantheon.io/docs/nginx-access-log/)

Priority (Low):

## Issue Description:

The recommended log format for Pantheon nginx files in the doc is:
`log-format %h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"`

While this is not wrong, the initial `%h` would always be the origin shield IP which is less interesting than it could be.

## Suggested Resolution 

Using:
`log-format %^ - - [%d:%t %^]  "%r" %s %b "%R" "%u" %T ~h{,"}`
would use the X-Forwarded-For header to report the actual requesting IP

**Comment by alexfornuto** [comment]
@hengkit I agree that the X-Forwarded-For header is more interesting. But the format you provided creates errors:

```
Parsed 10 lines producing the following errors:

Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'

Format Errors - Verify your log/date/time format
```
