### ISSUE TITLE
General Guidelines for Structuring Custom Upstreams

### ISSUE THREAD

**Issue by obicke** [pantheon-systems/documentation#2943]
Priority: Medium
## Title
General Guidelines for Structuring Custom Upstreams

## Description
A description of general considerations for architecting / structuring custom upstreams in such a way as to facilitate creation and customization of sites while not creating overly burdensome maintenance.

We have docs for why use upstreams, the steps required to create and maintain them, but not on how to think about, and structure, them in the first place. 

## Outline
This is a very broad topic and so we may want to start simple, with a list of observations and suggestions, and build it out with more structure going forward (e.g. dedicated sections for Drupal and WP, specific use cases, etc.)

(The ideas below, stem from an exchange with Steve P.)
- Intro to general concept of stacked upstreams
- Some guidelines and general concepts about what can should live in the upstreams, versus in the DB, with some examples from both WP and Drupal 
- using base theme / child theme setup
- "thinking of the upstream as setting up config in the database and the child theme totally customizes it"
- giving some examples, e.g. a slideshow feature in Drupal
- etc.

## Expected Audience
Anybody considering using upstreams.

## Path
(e.g. `docs/custom-upstream/considerations` and/or `docs/custom-upstream/considerations/wordpress`, and/or `docs/custom-upstream/considerations/drupal`)

**Comment by alexfornuto** [comment]
@obicke, @rachelwhitton is reviewing this issue alongside other product-related updates, and will triage it appropriately.

**Comment by rachelwhitton** [comment]
@mcdwayne you mentioned a slide from @ataylorme - noting here to remind me to circle back. running the custom upstream site on pantheon and pushing back to github

**Comment by rachelwhitton** [comment]
Rejecting this one to be tracked in AL-1098  alongside other custom upstream doc efforts
