### ISSUE TITLE
Pre Provisioning of HTTPS

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2945]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/configure-dns/)
[HTTPS](/docs/https)

Priority (Medium):

## Issue Description:
Multiple requests have been mentioned about how to "pre-provision" for cases both on existing HTTPS, NO HTTPS, or first-timers. 

Need a clear concept, illustration on how pre-provisioning works and what's only possible.

## Suggested Resolution 

Provide section that highlight when should pre-provisioning work, and what are the scenarios that these will actually work on its own.

Also, provide clarity if it is actually possible to pre-provision (even for non HTTPS sites)
Provide troubleshooting points why a domain is not pre-provisioned.

**Comment by eabquina** [comment]
Adding scenario related to TXT records if they can do it via this way: 
https://community.letsencrypt.org/t/how-to-add-dns-txt-record-for-domain-verification/31555

Update: It is not supported as of the moment

**Comment by ari-gold** [comment]
@eabquina No, this is not supported. I'll ping you with link to internal feature request

**Comment by alexfornuto** [comment]
@eabquina the `fix content` label is not appropriate here, as you're not identifying existing information that is wrong. Instead, you're suggesting new content. 

As for what new content, I'm not sure. Why would those without existing HTTPS need to pre-provision on Pantheon?

Is there any action to be taken on this issue that isn't dependent on the referenced internal issue?

**Comment by eabquina** [comment]
@alexfornuto I receive multiple requests about pre-provisioning in general. 

- Unable to use verification file in WPEngine because of a redirect
- The server doesn't support verification file without extension name like for IIS +. NET site
- A customer found the Let's Encrypt doc about TXT DNS record for verification
- A customer just can't accept the possible 1-hour downtime of HTTPS
- A customer said "just take my word for it" to pre-provision (even without HTTPS before)

It would be great to have a doc section explaining what's only possible about pre-provisioning, and what should not. It would also help with the assurance of use, suggested workarounds (redirecting to a domain first), and other future topics. 

Most of the time, the context is for migration. This should help them plan their cut-over activities.

**Comment by alexfornuto** [comment]
@eabquina thanks for clarifying. Sounds like a new section in the [https faq](https://pantheon.io/docs/https/#frequently-asked-questions), which we can then link to in Launch Essentials.
