### ISSUE TITLE
Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2957]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs/cloudflare/)

Priority (Low):

## Issue Description:
Customer encounters Certificate Mismatch error for his site already activated with Global CDN

## Suggested Resolution 
Quick fix is to disable "Orange Cloud" or use DNS Only for CloudFlare
Confirm if this is a case for the Free Accounts only; 
And check if it is relating to this document: https://support.cloudflare.com/hc/en-us/articles/200170616-Why-am-I-getting-a-SSL-mismatch-error-

**Comment by alexfornuto** [comment]
This issue was between Cloudflare and the client browser. Disabling the Cloudfront CDN (already documented) "fixed" the problem by removing the entire configuration. Ultimately not something for our docs.
