### ISSUE TITLE
October/November Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2959]
Add October platform changes and new features to be included in the October/November Changelog.

**Comment by ari-gold** [comment]
WebP images are now cached on Global CDN, like other image formats.

**Comment by davidstrauss** [comment]
Thanks, @ari-gold, for getting this into the notes.

**Comment by rachelwhitton** [comment]
Terminus 1.6.0

**Comment by ari-gold** [comment]
WordPress 4.8.3 Security Release:
https://status.pantheon.io/incidents/gd6ls2q28j2h

**Comment by alexfornuto** [comment]
New month, new [changelog](https://github.com/pantheon-systems/documentation/issues/3055)
