### ISSUE TITLE
New Relic APM Pro Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2976]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/)

Priority (Low‚ Medium‚ High):

# Issue Description:
More hands on documentation on how to disable New Relic on AMP pages would be great, as folks end up disabling New Relic completely. Code snippets would be great!

# Suggested Resolution 

## Identifying issue:
If AMP pages have a conflict w New Relic, this error message appears:
`The tag 'script' is disallowed except in specific forms.`

## Solution

For Drupal sites using amp module:
https://www.drupal.org/project/amp

D7 only needs testing - D8 needs a bit of code rewriting, WordPress needs research.

### D7, amp module:
amp_is_amp_request() (line 332 in amp.module) returns TRUE on AMP pages, I think code could be something like:
```
if (module_exists('amp')) && (amp_is_amp_request()) && (extension_loaded('newrelic')) {
  newrelic_disable_autorum (FALSE);
  newrelic_ignore_transaction();
}
```

### D8, amp module:
There is a patch here that should be possible to rewrite to a code snippet for settings.php. Needs someone who has a little more D8-fu than me:
https://www.drupal.org/node/2764673
https://www.drupal.org/files/issues/disable_new_relic_apm-2764673-2.patch

### WordPress:
Not sure..

## References:
New Relic doc is here:
https://docs.newrelic.com/docs/browser/new-relic-browser/troubleshooting/google-amp-validator-fails-due-3rd-party-script

## Monitoring AMP pages in New Relic
Is possible but needs an upgraded subscription (Browser Pro):
https://docs.newrelic.com/docs/browser/new-relic-browser/installation/monitor-amp-pages-new-relic-browser

Note that for Pantheon customers, upgrade requests need to go here:
pantheon@newrelic.com 
https://pantheon.io/blog/pantheon-new-relic-more-what-you-get

**Comment by nitinsareen** [comment]
Ideally for D7 we are looking to find a snippet that can be placed inside settings.php - https://www.drupal.org/node/2764673#comment-11784004

**Comment by nitinsareen** [comment]
After the whole day hit & trial, we finally discovered the snippet that works! 

Place this inside your settings.php for disabling newrelic only for AMP  - 

$path = $_SERVER['REQUEST_URI'];
$find = '?amp';
$pos = strpos($path, $find);
if ($pos !== false){
 if (function_exists('newrelic_disable_autorum')) {
   newrelic_disable_autorum();
 }
}

**Comment by rachelwhitton** [comment]
Thanks for the snippet @nitinsareen! Much appreciated!

@pantheon-systems/cse should we recommend disabling New Relic on AMP pages to fix `The tag 'script' is disallowed except in specific forms` by adding the following snippet to `settings.php` or `wp-config.php`? Would this work for WP/D7/D8? Seems like it would. 

```php
$path = $_SERVER['REQUEST_URI'];
$find = '?amp';
$pos = strpos($path, $find);
if ($pos !== false){
  if (function_exists('newrelic_disable_autorum')) {
    newrelic_disable_autorum();
  }
}
```

Maybe we don't need a full doc, just a small section in the new relic doc with this snippet and some context?

**Comment by rachelwhitton** [comment]
Suggested solution is to fix up the snippet in the existing [Disable New Relic Browser Monitoring Agent](https://pantheon.io/docs/new-relic/#disable-new-relic-browser-monitoring-agent)
