### ISSUE TITLE
Require HTTPS with the HSTS Header Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#2977]
Re: [Require HTTPS with the HSTS Header](https://pantheon.io/docs/hsts/)

Priority (Low‚ Medium‚ High):

## Issue Description:
LH-HSTS WP plugin currently breaks WordPress networks subdirectory setup:
https://wordpress.org/support/topic/broken-website-9/
(infinite redirect issue)

## Suggested Resolution 
Not sure if this goes here, on unsupported modules page - or whether we want to document it at all (hopefully plugin maintainer will fix it soon?).

**Comment by alexfornuto** [comment]
@peter-pantheon you recently helped update this guide. @adamedgmond you're particularly knowledgeable with site networks. Would either of you care to weigh in on this?

**Comment by rachelwhitton** [comment]
+1 

I recently encountered this issue after moving a personal site to the composer build tools workflow. When activated the plugin produces a redirect loop and adds `wp/` repeatedly to the URL: 

<img width="1098" alt="screen shot 2017-10-25 at 11 12 14 am" src="https://user-images.githubusercontent.com/10119525/32009703-675663a8-b975-11e7-8abe-8a68540544b2.png">

cc @ataylorme 

Suggest adding a section for sites using nested docroot with issue and alternative method to add HTTP Strict Transport Security (HSTS) header via custom PHP function: 

```php
/**
*
* Example custom function to add the HSTS header while rendering a response.
*
**/
add_action( 'send_headers', 'add_header_hsts' );
function add_header_hsts() {
    header('Strict-Transport-Security: max-age=15984000; includeSubDomains; preload');
}
```
   See the [WordPress documentation](https://codex.wordpress.org/Plugin_API/Action_Reference/send_headers){.external} for more details.
