### ISSUE TITLE
New Doc Proposal - Atom + Remote-FTP

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#2978]
Priority (Low‚ Medium‚ High): Low

## Title
SFTP Client Setup for Atom + Remote-FTP

## Description
Suggesting a new page to connect using Atom Editor + Remote-FTP plugin with 2 variations: 
1) Using the private/public key pair 
2) SFTP connection

## Expected Audience
Developers that is setting up their connection and IDE using Atom (https://atom.io/)

## Path
source/docs/sftp/
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by carl-alberto** [comment]
https://github.com/pantheon-systems/documentation/pull/2979

**Comment by rachelwhitton** [comment]
Closed by #2939 but please reopen if the new guide does not address original concern. 
https://pantheon.io/docs/guides/wordpress-git/themes/
