### ISSUE TITLE
Documenting "Error establishing a database connection" error that can occur with WordPress multisite

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/documentation#2982]
What would be the best place for some documentation around this issue?

![image](https://user-images.githubusercontent.com/36432/31407234-053abfe2-adb9-11e7-8161-e02d85ce8481.png)

This error can occur when moving a WordPress multisite database between environments. If `wp search-replace` was performed incorrectly (without the `--network` flag), or not at all, the end user will experience this error.

Reproduce this issue by:

1. Creating a new WordPress multisite instance with one site.
2. Manually setting the domain value in the `wp_blogs` table to `mstest.org`.
3. Manually editing the `DOMAIN_CURRENT_SITE` constant to `mstest.dev`.

When you visit `mstest.dev` in your browser, you'll see:

> Error establishing a database connection

On the command line, WP-CLI is a bit more helpful with:

> Error: Site 'mstest.dev/' not found. Verify DOMAIN_CURRENT_SITE matches an existing site or use `--url=<url>` to override.

The true source of this issue is [captured in a WordPress Trac ticket](https://core.trac.wordpress.org/ticket/41424). Essentially, WordPress displays an error message because it couldn't find the requested site in the `wp_blogs` table.

Between now and when the error message is fixed, it'd be helpful to capture these details somewhere for visibility. Happy to prepare a pull request when pointed in the right direction.

**Comment by rachelwhitton** [comment]
We have this doc: [Database Connection Errors](https://pantheon.io/docs/database-connection-errors/) though it may be quite stale and in need of some sprucing up - haven't made edits to this one in a long time. 

Other options: migration docs? WordPress multisite specific docs?
 It may make more sense to stick this in our migration troubleshooting page. https://pantheon.io/docs/migrate-troubleshooting/


@alexfornuto thoughts?

**Comment by danielbachhuber** [comment]
FYI - I'm including this on the "Best Practices and Common Issues" page in the new Site Networks Guide
