### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by roprice** [pantheon-systems/documentation#3013]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins/)

Priority (Low‚ Medium‚ High): 
Low

## Issue Description: 
Instructions for Autoptimize (https://pantheon.io/docs/unsupported-modules-plugins/#autoptimize) are incomplete (and don't work).

## Suggested Resolution 
Instruct users to place Autoptimize code *before* the ABSPATH/wp-settings.php declaration, like so:

```
/** Changes location where Autoptimize stores optimized files */
define('AUTOPTIMIZE_CACHE_CHILD_DIR','/uploads/autoptimize/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
```

**Comment by rachelwhitton** [comment]
+1 Thanks for the issue @roprice, much appreciated!
