### ISSUE TITLE
Document Pantheon's requirements for Managed HTTPS

### ISSUE THREAD

**Issue by kf6nux** [pantheon-systems/documentation#3016]
Re: https://pantheon.io/docs/https/ and/or https://pantheon.io/docs/guides/launch/configure-dns/
## Issue Description
Our customers aren't informed by documentation what Pantheon's needs from them to provide them with HTTPS.
## Suggested Resolution
Add to the FAQ and Launch guide our requirements:
```
Requirements for contiguous Managed HTTPS:
- All A/AAAA records must point to a server that serves Pantheon's acme-challenge response (e.g. http://23.185.0.1/.well-known/acme-challenge/[variableDataHere] )
- Authority Name Servers must serve mixed-case lookups.
- Authority Name Servers must not fail CAA lookups.
- CAA records must either 1) not exist for the domain and its parent domains or 2) authorize Let's Encrypt.
- CNAMEs must follow the above requirements.
- DNAMEs must not be used.

Please check this doc periodically as requirements may be added or removed.
```

First commented here https://github.com/pantheon-systems/documentation/issues/2899 , but moved to its own issue per @ari-gold 's suggestion.

**Comment by rachelwhitton** [comment]
+1 Thanks for the issue @kf6nux! Much appreciated
