### ISSUE TITLE
Date and Time Doc Update for Locale

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3018]
Re: [Date and Time](https://pantheon.io/docs/date-and-time/)

Priority (Low):

## Issue Description:
The customer is trying to print Dates in a different language. There are no available options on to make this work. 

The customer is trying to use PHP function but not working
`setlocale(LC_ALL, 'sv_SE.utf8') or die('Locale not installed');`

## Suggested Resolution

Verify if this is supported or how to properly enable this, if it is possible to be set also in PHP.ini etc,

Consider for both Drupal and WordPress

**Comment by alexfornuto** [comment]
@eabquina There are a couple things wrong with this issue:

1) Not enough description of the situation creating this issue. We don't even know what CMS, or if it's related to a CMS

2) No resolution. Related to the above, if we don't know what creates this issue we can't verify anything. I'm not even sure if this is something for docs or engineering to look into.

Feel free to open a new issue if you can collect more actionable data.

**Comment by rachelwhitton** [comment]
Seems out of scope,  unless there’s a known platform limitation to document? Like a particular php extension is missing or something. Agree with @alexfornuto, more info is needed

**Comment by eabquina** [comment]
@alexfornuto @rachelwhitton  This is actually an app server configuration. It turns out that this is not yet supported. 
Thanks to @ronnie who resolved the ticket and filed a request for this

```
C
C.utf8
en_AG
en_AG.utf8
en_AU
en_AU.iso88591
en_AU.utf8
en_BW
en_BW.iso88591
en_BW.utf8
en_CA
en_CA.iso88591
en_CA.utf8
en_DK
en_DK.iso88591
en_DK.utf8
en_GB
en_GB.iso88591
en_GB.iso885915
en_GB.utf8
en_HK
en_HK.iso88591
en_HK.utf8
en_IE
en_IE@euro
en_IE.iso88591
en_IE.iso885915@euro
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ
en_NZ.iso88591
en_NZ.utf8
en_PH
en_PH.iso88591
en_PH.utf8
en_SG
en_SG.iso88591
en_SG.utf8
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8
en_ZA
en_ZA.iso88591
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW
en_ZW.iso88591
en_ZW.utf8
POSIX
```
