### ISSUE TITLE
Workaround for text file challenge on D7 sites

### ISSUE THREAD

**Issue by bentekwork** [pantheon-systems/documentation#3020]
Priority (Medium):

## Description 
When pre-provisioning certs a folder called ".well-known" is created in the web root on the legacy server (which is typically Drupal's root folder).  

The line `RewriteRule "(^|/)." - [F]` in Drupal's default .htaccess file blocks folders starting with dots being accessed.

The best workaround is to add the line

`RewriteRule "^.well-known/acme-challenge" - [L]`

to .htaccess just above the rule

`RewriteRule "(^|/)." - [F].`

## Path
`source/docs/https/#known-issues`

**Comment by ari-gold** [comment]
Are you using https://www.drupal.org/project/letsencrypt_challenge ? Is the workaround you suggested necessary if you're using that module?

**Comment by bentekwork** [comment]
That solution works as well.  I don't see either workaround in the docs.  I may have missed it though.

**Comment by ari-gold** [comment]
Right now the module is referenced in https://pantheon.io/docs/guides/launch/domains/
I'm definitely +1 on adding it to  docs/https/#known-issues too.

**Comment by bentekwork** [comment]
@ari-gold - Submitted a PR, feedback welcome.
