### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by asreenu** [pantheon-systems/documentation#3024]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/install/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Does not address specific pre-requisites and their installation
Does not address updating.  (Terminus install requirements keep changing with every upgrade, just like it's syntax)
## Suggested Resolution

**Comment by rachelwhitton** [comment]
Thanks for the issue @asreenu! Can you clarify your first concern? We have a requirements section towards the top of the [install page](https://pantheon.io/docs/terminus/install/) that should cover pre-reqs. Are there specific gaps we should focus on?

Does the last page of the guide address your second concern? [Version Updates](https://pantheon.io/docs/terminus/updates/)

**Comment by rachelwhitton** [comment]
@asreenu closing for now. happy to re-open with clarification on what's needed

**Comment by asreenu** [comment]
Hi Rachel

It does not say how to cleanly uninstall.  Also no usable link to straight
install of composer.  It just links to the site.

**Comment by alexfornuto** [comment]
> Also no usable link to straight install of composer

The link points to Composer's own installation documentation.  We try not to duplicate existing instructions for other tools, and risk our information becoming stale.

> It does not say how to cleanly uninstall.  

Uninstall option is being discussed (FEAT-489).

**Comment by alexfornuto** [comment]
Closing this issue. We'll reopen or recreate when FEAT-489 is addressed.
