### ISSUE TITLE
Domains and Redirects Doc Update 

### ISSUE THREAD

**Issue by JacobJeffersonJakes** [pantheon-systems/documentation#3029]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Details in code snippet didn't work; needed to use different variables

## Suggested Resolution 
About a year or more ago I configured my sites to use Cloudflare, and set things up as recommended in the Pantheon documents of the time. I decided recently to just use Cloudflare for DNS, and use Fastly for CDN. This is the code snippet from the doc which seems faulty:

if ($_SERVER['HTTP_HOST'] != $primary_domain
      || !isset($_SERVER['HTTP_X_SSL'])
      || $_SERVER['HTTP_X_SSL'] != 'ON' ) {

Based on what is in wp-config.php for sites created more recently, this is what I changed it to, which made it work:

      if ($_SERVER['HTTP_HOST'] != $primary_domain
          || !isset($_SERVER['HTTP_USER_AGENT_HTTPS'])
          || $_SERVER['HTTP_USER_AGENT_HTTPS'] != 'ON' ) {

**Comment by rachelwhitton** [comment]
Thanks for reporting this issue @JacobJeffersonJakes, much appreciated!

@davidstrauss can you take a look?

**Comment by alexfornuto** [comment]
@JacobJeffersonJakes I've tested the code provided by the doc for WordPress and D7 and found it to be working fine. Can you clarify what about the example code you found faulty, and in what exact circumstances?
