### ISSUE TITLE
Best Practices for Maintaining Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by nimzie** [pantheon-systems/documentation#3046]
Re: [Best Practices for Maintaining Custom Upstreams](https://pantheon.io/docs/maintain-custom-upstream/)

Priority (Low):

## Suggested Resolution 
There is a reference in step in Test and Release Pantheon Core Updates
Step 2:

> terminus connection:info <site>.<dev> --field=git_url

I am recommending this be changed to

> terminus connection:info <site-uuid>.dev --field=git_url
Suggesting using site-uuid because that's all I could get to work.
Suggesting .dev used literally, as we are only connecting to .dev for most - if not all workflow scenarios.

**Comment by rachelwhitton** [comment]
@nimzie thanks for the issue! I think I understand the suggestion re: `.dev`, but can you clarify the suggestion to use site-uuid? 

The command should return a remote url for the site's code repository on Pantheon. Site-uuid should not be necessary. Example: 

```
╭─rachel at pantheor in [~]
╰─➤ $ terminus connection:info rachelwhitton.dev --field=git_url

ssh://codeserver.dev.81a6d2c7-07d7-46d8-b6cd-89e8fd58aee5@codeserver.dev.81a6d2c7-07d7-46d8-b6cd-89e8fd58aee5.drush.in:2222/~/repository.git
```


Terminus info: 
```
╭─rachel at pantheor in [~]
╰─➤ $ terminus self:info
 ------------------------- ---------------------------------------------------
  PHP binary                /usr/local/Cellar/php71/7.1.8_20/bin/php
  PHP version               7.1.8
  php.ini used              /usr/local/etc/php/7.1/php.ini
  Terminus project config
  Terminus root dir         /Users/rachel/vendor/pantheon-systems/terminus
  Terminus version          1.6.0
  Operating system          Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27
                            PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
 ------------------------- ---------------------------------------------------
```
