### ISSUE TITLE
Replace Kalabox documentation with Lando

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3048]
Re: <https://pantheon.io/docs/kalabox/>
## Issue Description

[Kalabox is dead](https://thinktandem.io/blog/2017/10/24/journey-to-lando-mistakes-pivots-and-vindication/). Long Live Lando!

## Suggested Resolution
 - Rewrite Kalabox doc for Lando
 - Replace and add redirect.

**Comment by rachelwhitton** [comment]
I'd prefer holding on docs on local development. We'll track that work internally
