### ISSUE TITLE
Terminus Manual Doc Update: Differentiate "Quicksilver" Terminus plugin from the Pantheon feature named Quicksilver

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#3050]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/plugins/directory/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Someone asked me if Quicksilver is a Terminus plugin. I originally said no and explained the difference between Terminus and Quicksilver. But then he showed me that there is a "Pantheon Official" Terminus plugin named "Quicksilver". This probably makes it difficult for people to learn and adopt Quicksilver if they're coming from a place where they already know Terminus.

## Suggested Resolution 
Rename the plugin from "Quicksilver" to something like "Quicksilver Helper".

**Comment by davidneedham** [comment]
Hmm, I was trying to figure out how to request feedback from @greg-1-anderson , but I think that feature may only exist in a pull request. Oh well. You're probably notified now. :-)

**Comment by rachelwhitton** [comment]
+1 Suggest changing the name to "Quicksilver Examples" if we keep it. I'm not opposed to removing it from the plugin list since it's not an actual plugin.

**Comment by greg-1-anderson** [comment]
Wait, the [Terminus Quicksilver Plugin](https://github.com/pantheon-systems/terminus-quicksilver-plugin) is in fact an actual Terminus plugin! It contains very useful commands to help install quicksilver hooks in your Pantheon site. By default, it installs named webhooks from the [Quicksilver Examples](https://github.com/pantheon-systems/quicksilver-examples) repository.

We could rename the Terminus Quicksilver Plugin to the Terminus Quicksilver Helper Plugin or simply the Terminus Quicksilver Helper; however, I'm not sure that this would completely solve the problem. There is also an incurred cost / instilled confusion when an existing component is renamed, so I would be inclined to instead improve the explanation in the existing docs.

- [Terminus Plugin Directory](https://pantheon.io/docs/terminus/plugins/directory/):

The existing summary is pretty good. It currently reads:

"Install Quicksilver webhooks from the [Quicksilver examples](https://github.com/pantheon-systems/quicksilver-examples), or a personal collection."

We could enhance this by linking the words "Quicksilver webhooks" to the main Quicksilver documentation pages.

- [Terminus Quicksilver Plugin](https://github.com/pantheon-systems/terminus-quicksilver-plugin)

The existing text here could be clearer by providing some context. We could start out by defining *Termius* and *Quicksilver* (with [docs links](https://pantheon.io/docs/quicksilver/)), and then go on with the current explanation of what the plugin is for.

- [Quicksilver Examples](https://github.com/pantheon-systems/quicksilver-examples):

The Quicksilver Examples repository could benefit from a link to the Quicksilver documentation and a pointer to the Quicksilver Terminus Plugin.

Additionally, the current terminology throughout these sources is often inconsistent; Quicksilver webhooks are sometimes called "Quicksilver Platform Hooks", sometimes "Quicksilver Cloud Hooks" and sometimes "Pantheon Cloud Integration". We should decide on the official name and make sure that each of the sources use the full official name on the first referenced use, and an agreeable short form thereafter.

Naming things is hard, so I'd like to add @joshkoenig @stevector and @ataylorme to the conversation to see if they have any feedback. Once we decide what should be named what and make all of the corrections, I'll blog about the Terminus Quicksilver Plugin to give it a bit more exposure.

**Comment by stevector** [comment]
I agree that renaming the Terminus Quicksilver Plugin is a step too far at this point and that the kinds of docs/readme improvements @greg-1-anderson suggests would help.

I also agree that we need to standardize the terminology around "Cloud/Platform" Hooks.

**Comment by davidneedham** [comment]
To be clear, I'm not suggesting that we rename the entire project for the plugin, just the title used for this plugin on the Terminus Plugins directory. All that I'm saying is that "Quicksilver" isn't enough. In fact, I believe changing it to the actual project name, "Terminus Quicksilver Plugin", would be enough context to differentiate it from the Quicksilver feature to a new user.

+10 to standardizing terminology, though this probably isn't the right place to discuss that.

**Comment by greg-1-anderson** [comment]
@rachelwhitton Do you think that "Terminus Quicksilver Plugin" would fit here? If not, how about "Quicksilver Plugin"?

If we make this change for Quicksilver, would we also want to adjust the titles of others, e.g "Rsync Plugin"?

**Comment by rachelwhitton** [comment]
@greg-1-anderson The more I think about this, the more I think it's fine how it is. Within the context of the page, it's clear that these are all Terminus Plugins. If anything, we could add helper to the title as @davidneedham originally suggested but I'm not sure that's entirely necessary.

**Comment by greg-1-anderson** [comment]
Shall I make a new issue for https://github.com/pantheon-systems/documentation/issues/3050#issuecomment-340805410?

**Comment by davidneedham** [comment]
@rachelwhitton I won't belabor the point, but keep in mind the original problem. Someone new to Pantheon came to me asking if Quicksilver was part of Terminus because they found this page. For someone totally new to our terminology and features, the context wasn't enough.

**Comment by alexfornuto** [comment]
In #4210 I've updated the directory listing to match the full name of the plugin, "Terminus Quicksilver Plugin". I'm hoping this will address @davidneedham's concerns in a way that suits everyone.
