### ISSUE TITLE
Amazon S3 File Limit and Related Docs

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3054]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)
[AWS S3 Setup for Drupal](https://pantheon.io/docs/drupal-s3/)
[CloudFront CDN Setup for WordPress](https://pantheon.io/docs/wordpress-cloudfront/)
Priority (Low):

## Issue Description:

1. Large Files section does not have a WordPress specific recommendation for Big Media file needs.  (around 500mb and up)
Also, a customer claims that the WP S3 Offload plugin (as per our wordpress-cloudfront docs) is not working. Can't upload files more than the Pantheon set limit. It seems WordPress still use the Platform limit before sending to S3

2. Different Modules in the Drupal S3 doc versus here in platform considerations. We show a different Module (amazons3_cors) vers (s3fs_cors) in the Drupal S3 guide

## Suggested Resolution 

1. Do tests to confirm if uploading big files won't work for WordPress. Provide alternative if there is any. Provide also the link for the wordpress-cloudfront docs page.

2.  Place a link for the Drupal S3 docs page instead of the different module. Also compare if the tests for uploading directly to S3 is only for the amazons3_cors module, compared to the Drupal S3 docs page using (s3fs)

**Comment by alexfornuto** [comment]
Closed based on comments sent to the author via Slack

**Comment by eabquina** [comment]
@alexfornuto  I should have placed in the intro that this comes from the Platform Cosniderations section where we can upload big files using Amazon S3 without Pantheon as intermediary. 

If you are distributing large binaries or hosting big media files, we recommend using a CDN like Amazon S3 as a cost-effective file serving solution. Modules such as Amazon S3 CORS Upload allow uploads directly to S3 from your Drupal site without using Pantheon as an intermediary.

We found out that this doesn't work on the  WordPress plugin reco.
