### ISSUE TITLE
November/December Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3055]
Add November platform changes and new features to be included in the November/December Changelog.

**Comment by greg-1-anderson** [comment]
Drupal 8.4.2: https://api.github.com/repos/pantheon-systems/drops-8/pulls/196

**Comment by ari-gold** [comment]
Global CDN now respects the `no-store` directive in the `cache-control` header.

**Comment by greg-1-anderson** [comment]
WordPress 4.9: https://github.com/pantheon-systems/WordPress/pull/142

**Comment by greg-1-anderson** [comment]
WordPress 4.9.1: https://github.com/pantheon-systems/WordPress/pull/144

**Comment by ari-gold** [comment]
Org/User Dash update: Some sites still need Global CDN upgrade

Over 200,000 sites are already on Pantheon's Global CDN, but if you still have sites pointing to the legacy, deprecated infrastructure you can now see which sites need an upgrade from your User or Organization Dashboard. Find required DNS information from the "Domains / HTTPS" tab on each site environment. Complete the upgrade as soon as possible, and let us know if you have any questions.

**Comment by kimby77** [comment]
Site Dashboard Update:
On newly created sites, you are now directed to install your WordPress or Drupal CMS as the next step. 

![image](https://user-images.githubusercontent.com/19398001/33455292-78dac322-d5d0-11e7-850f-20d29ca87eb4.png)

**Comment by greg-1-anderson** [comment]
Drupal 8.4.3 : https://github.com/pantheon-systems/drops-8/pull/199
