### ISSUE TITLE
Developing Locally with Kalabox Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3056]
Re: [Developing Locally with Kalabox](https://pantheon.io/docs/kalabox/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Kalabox is outdated by now and ships with terminus <1.0

## Suggested Resolution 

We should likely update the doc to Lando instead - would need testing etc.

**Comment by alexfornuto** [comment]
@tinefin Kalabox is indeed out of date. I opened a similar issue in #3048. As Rachel mentioned there, work on new local development documentation is being tracked internally.

@rachelwhitton perhaps in the interim we should create a deprecated header for this guide?

**Comment by rachelwhitton** [comment]
I'd prefer not to put deprecated here until we have product docs in place for pantheon local. Part of that work should determine whether this doc is deleted and redirected to our new local dev docs, or if we keep the content up and add a deprecated notice to the top. 

I'm fine adding a note towards the top, pointing folks towards lando's beta release. But it's a bit too early to make a full switch to lando in docs IMO. We need to plan it all out as part of the product release cycle. cc @taurusismysign

**Comment by alexfornuto** [comment]
I agree that a note is probably the best action to take at this time.
