### ISSUE TITLE
Testing Varnish Doc Update 

### ISSUE THREAD

**Issue by jfussion** [pantheon-systems/documentation#3059]
Re: [Testing Varnish](https://pantheon.io/docs/test-varnish/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
This document outlines how to test varnish from our legacy edge.

## Suggested Resolution 
 [ ] Update this to focus on GlobalCDN
 [ ] Create a bug card for the outdated tool referenced by this guide

**Comment by alexfornuto** [comment]
I removed `SME`, as Rachel and I want to handle this and other cache control docs as part of a cache doc audit.
