### ISSUE TITLE
Front Module breaking Cache

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3061]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/unsupported-modules-plugins/)

Priority (Low):

## Issue Description:
Caching is not working because of https://www.drupal.org/project/front module

## Suggested Resolution 
Consider if there is some settings required or this is just really conflicting with our Varnish settings

**Comment by rachelwhitton** [comment]
+1 This can be closed by adding the module to the doc page with a description of the issue. Discovery work to recommend a solution/workaround is welcomed but not a requirement for the issue.
