### ISSUE TITLE
Using Terminus to Create and Update Drupal Sites on Pantheon Doc Update 

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3063]
Re: [Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs/guides/terminus-drupal-site-management/)

Priority (Low‚ Medium‚ High): Low

## Suggested Resolution
Change: Also, the status of each of the environments within the site can be seen using a terminus site environments command.
To: Also, the status of each of the environments within the site can be seen using a terminus env:list command.

Change: Let's commit it all into the Git repo with the terminus site code commit command:
To: Let's commit it all into the Git repo with the terminus env:commit command:

Change: And finally, let's initialize the Test environment to move the code, files, and DB from Dev onward in the Pantheon workflow using env:deploy.
To: And finally, let's initialize the Test environment to move the code, files, and DB from Dev onward in the Pantheon workflow using a terminus env:deploy command.

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign for bringing this to our attention!
