### ISSUE TITLE
Adjust styling for copy button so it's not overlapping snippet

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3066]
Priority (Low‚ Medium‚ High):

## Issue Description:
![pasted image at 2017_11_07 09_50 am](https://user-images.githubusercontent.com/10119525/32510301-c0c36018-c3b5-11e7-8b42-4a6ceb2aa8d9.png)

## Suggested Resolution 
Fix overlap

cc @kimby77

**Comment by kimby77** [comment]
🎉
