### ISSUE TITLE
Cron for Drupal Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3068]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Didn't we have a section on how to set up custom cron jobs once? With Elysia I believe?
Can we get that back / added?

Ref: 
Ticket 93439

## Suggested Resolution

**Comment by alexfornuto** [comment]
Duplicate of #2591
