### ISSUE TITLE
Build Tools Doc Update - Token Updates

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3071]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/)

Priority (Medium):

## Issue Description:
A customer starts to get failures for pull request and found out that their original Tokens or Keys have been revoked. The error was not clear, and the build-tools docs did not cover specific steps for fixing the error.

After review, the [Build Customizations section](https://github.com/pantheon-systems/terminus-build-tools-plugin#build-customizations) showed an option to have GITHUB_TOKEN modified via the circle.yml file

## Suggested Resolution 
Provide a link or section on what to do when they need to update Tokens, revoked or new user.

Also, provide a better explanation of the circle.yml file.
https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/example.circle.yml

Additional comment: Customer "does not" want to use circle.yml file (so to not expose an access token). What would be the alternative other than re-building the project?

**Comment by ttrowell** [comment]
@alexfornuto Could you elaborate?  While we may need to reference another offsite doc, this was a black hole since we are providing the ability to setup a complex system, it seems we should also include more info on Troubleshooting this.   

Would input from Greg Anderson be valuable here?
