### ISSUE TITLE
Re:  Accessing MySQL Databases FAQ --Create DB Privilege

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3079]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:

> Can I create a database in addition to the Pantheon database?
No, only one database per site is provided and create privileges are not granted.

It looks like `GRANT ALL PRIVILEGES` is granted to Pantheon User:

`MariaDB [pantheon]> show grants;`

+-------------------------------------------------------------------------------------+
| Grants for pantheon@%                                                                                                       |
+-------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'pantheon'@'%' IDENTIFIED BY PASSWORD '*****'
+-------------------------------------------------------------------------------------+

I can create additional database:

`MariaDB [pantheon]> show databases;`
+--------------------+
| Database                  |
+--------------------+
| information_schema |
| mysql                        |
| pantheon                  |
| performance_schema |
+--------------------+

`MariaDB [pantheon]> create database myDB ;
Query OK, 1 row affected (0.00 sec)`

MariaDB [pantheon]> show databases;
+--------------------+
| Database                  |
+--------------------+
| information_schema |
| myDB                       |
| mysql                       |
| pantheon                 |
| performance_schema |
+--------------------+
5 rows in set (0.00 `sec)

Is this expected? 

## Suggested Resolution 

Verify info and update doc accordingly.

**Comment by alexfornuto** [comment]
Reaching out to Product to determine if this is a docs or product issue.

**Comment by rachelwhitton** [comment]
better to simply say “additional DBs are not supported and will be removed” instead of saying create privileges not granted
