### ISSUE TITLE
New Doc Proposal: Add "Scripting with Terminus" to Terminus Manual

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/documentation#3086]
We have a lot of people writing scripts with Terminus, and a lot of best practices are known, but there's no doc page for it!

It would be a nice thing to add to the terminus guide, and we could probably source an outline based on the ACE team's experiences in Jump Starts and such.

cc @ataylorme @stevector @tessak22

**Comment by uberhacker** [comment]
Would converting some of these scripts to Terminus plugins be unrealistic?

**Comment by alexfornuto** [comment]
Assigning to @rachelwhitton to coordinate with the mentioned SMEs on getting an outline together.
