### ISSUE TITLE
Let's Encrypt Rate Limit When Using Let's Encrypt outside of Pantheon

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#3095]
Re: Let's Encrypt Rate Limit When Using Let's Encrypt outside of Pantheon
## Issue Description

Requesting a Let's Encrypt certificate for a domain not hosted on Pantheon fails with a rate limit error. Rate limiting could especially impact large organizations with many domains, such as universities.

## Suggested Resolution

Pantheon requests new certificates frequently in order to add domains to existing certificates. Let's Encrypt has increased our rate limit so we aren't running into the limit you could be reaching. It looks like there are two potential paths forward (you might try both) 
1) Ask Let's Encrypt to increase your rate limit 
- https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform
2) Add example.edu to the public suffix list, which will cause Let's Encrypt to treat every subdomain of the main domain as independent for limit purposes. Also, browsers and malware scanners will treat the subdomains as independent.
- It's just a Pull request to add to the public suffix list: https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by alexfornuto** [comment]
@ari-gold which guide did you have in mind to add this information to?
