### ISSUE TITLE
CloudFront CDN Setup for WordPress Doc Update 

### ISSUE THREAD

**Issue by allenfear** [pantheon-systems/documentation#3099]
Re: [CloudFront CDN Setup for WordPress](https://pantheon.io/docs/wordpress-cloudfront/)

Priority High:

## Issue Description:
This doc should either be retired or revamped with GCDN in mind.

## Suggested Resolution 
Update or replace doc with redirect to GCDN content.

**Comment by alexfornuto** [comment]
Tracked in the [Cache Content Audit](https://github.com/pantheon-systems/documentation/projects/7) Project
