### ISSUE TITLE
Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3106]
Re: [Pantheon Global CDN](https://pantheon.io/docs/global-cdn/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Regarding the graph: after looking at it for a while puzzled by what the graph is measuring, I realized that "Visual Progress" likely means how quick elements are appearing visually on page loads?
It might be good to add a bit more explanation?

## Suggested Resolution

**Comment by alexfornuto** [comment]
Adding the `help wanted` tag to get a better definition of "Visual Progress" that we can incorporate into the explanation requested.

**Comment by alexfornuto** [comment]
@ari-gold any insight as to how we define "Visual Progress" in this context?

**Comment by ari-gold** [comment]
https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index#TOC-Measuring-Visual-Progress
