### ISSUE TITLE
Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3107]
Re: [Pantheon Global CDN](https://pantheon.io/docs/global-cdn/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Could we add a section on what the different GCDN messages in DNS settings mean?
See this chat id: 13005581508
Examples: "Upgrade to CDN", "Setup Required", "Launched".
Especially the difference between the first 2 would be good.
@ari-gold 

## Suggested Resolution

**Comment by ari-gold** [comment]
Upgrade to CDN means the domain is routing to our legacy infrastructure
Setup Required can mean several things, click "Setup Required" or "Details" to get more details
Launched is shown in two cases and you can click "Details" to get more information.
