### ISSUE TITLE
Long cache lifetime and correct cache expiry, for static assets

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3108]
Priority (Low‚ Medium‚ High):

## Description

How to manage assets with long cache lifetime / correctly do cache expiry.

Pantheon sets a max-age header of 366 days on static assets. These can be expired from Pantheon Edge, but an end users browser / a CDN in front of Pantheon will cache the asset for a year (cannot be expired).
Therefore it is needed to change the name of a static file when updated. This is somewhat impractical for assets like pdf's, favicons, or even images updated without changing the name, so could be good to document.

See BUGS-1669 for context and a list of some of the tricky scenarios that might need an effort / workaround to handle.

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by alexfornuto** [comment]
@tinefin do you think a new section in the existing [Caching: Advanced Topics](https://pantheon.io/docs/caching-advanced-topics/) would be appropriate?

Also adding the `help wanted` tag to elicit help from an SME who could suggest best practices for caching static content.

**Comment by ari-gold** [comment]
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating_and_updating_cached_responses

**Comment by alexdicianu** [comment]
Not sure what the next steps are here but I do agree that having a long-tail cache expiry for static assets is good. If the image or asset file changes, including a fingerprint (e.g. a timestamp) could solve the initial issue.
