### ISSUE TITLE
Apply Upstream Updates Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3112]
Re: [Apply Upstream Updates](https://pantheon.io/docs/upstream-updates/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Could we add a section on how to get a site back on upstream?
Reference: 93228

## Suggested Resolution

**Comment by alexfornuto** [comment]
@tinefin: @rachelwhitton and I reviewed the referenced ticket and did not find a better explanation of what the issue here is, and what the proper resolution would be. Happy to re-open if you can clarify what you're suggested is needed in the documentation?
