### ISSUE TITLE
Cannot issue certificate for subdomain - CAA records

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3117]
Priority (Low‚ Medium‚ High):

## Title
Ssl certs and CAA records for subdomains not on Pantheon

## Description
The way Pantheon works currently is that every domain on Pantheon will have a CAA record added for letsencrypt.
When attempting to get a certificate for a subdomain of a domain on Pantheon, the CA (certificate provider) looks up the CAA record chain and cannot get authorization.

Quote from simpledns (link in notes section below):

> CAA records are also inherited by subdomains, therefore a CAA record set on example.com will also apply to any subdomain, such as subdomain.example.com (unless overridden). 

When using subdomains of Pantheon added domains "somewhere else", it is therefore needed to add CAA record(s) for cert provider either for the Pantheon added domain - or for each individual subdomain that is in use "somewhere else".

If this is not present, the cert provider will not be able to issue a certificate for the subdomain.

The solution is to add a CAA record for `mycertprovider`:

1. Either add a CAA record for `mycertprovider` to `mydomainonpantheon.com`: This will enable `mycertprovider` to issue certificates for `mydomainonpantheon.com` and all subdomains of `mydomainonpantheon.com`

Or:

2. Add CAA records for `mycertprovider` to each individual subdomain of `mydomainonpantheon.com`:
This will enable `mycertprovider` to issue certificates for `mysubdomain.mydomainonpantheon.com` and any subdomains of `mysubdomain.mydomainonpantheon.com`

Checking CAA records:
https://www.whatsmydns.net/#CAA/mydomain.com

## Notes for writing doc
These probably shouldn't go in the doc, but might be helpful for context:

Reference: 95618
BUGS-1712

Additional issue with Letsencrypt rate limits:
95182
https://github.com/pantheon-systems/documentation/issues/3095

More info about CAA records:
https://support.dnsimple.com/articles/caa-record/

NB:
We might change the setup, but this is how it works currently.

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by alexfornuto** [comment]
@tinefin Is my understanding correct that the presence of the CAA record or LE when attempting to generate the new certificate request is causing the issue? If so, would it be  suitable workaround to have configured A records for the subdomain in question pointing way from Pantheon's platform?

**Comment by ari-gold** [comment]
Let's see if we can resolve this issue in BUGS-1712

**Comment by alexfornuto** [comment]
Resolved in BUGS-1712
