### ISSUE TITLE
Private Paths for Files and Code Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3118]
Re: [Private Paths for Files and Code](https://pantheon.io/docs/private-paths/)

Priority (Medium):

## Issue Description:

The customer wants to perform or create private paths for multiple sites under their organization (around 40). In their use case, they want to use Private Path for Files (`sites/default/files/private` or `wp-content/uploads/private`)

The files/private path can't be possible via custom upstream because it is not version controlled.  

## Suggested Resolution 

Add a section for the following:
- Procedure how to create/add these folders (Files or Code)
- Comment for cases when they need to add this after launch (Troubleshooting?)
- If there is a way create/add folders for multiple sites for Private Files folder

**Comment by ari-gold** [comment]
Using protected_web_paths in pantheon.yml should do the trick? We could add a short section to  https://pantheon.io/docs/private-paths/ linking to https://pantheon.io/docs/pantheon-yml/#protected-web-paths

**Comment by rachelwhitton** [comment]
If the need is to have the private path version controlled, there's no additional configuration required. The `private` dir in the site's doc root is version controlled and it's web protected already. If they'd like to declare custom private paths for code, Ari's suggestion is where we should point them. Otherwise, they can use the default path. 

@eabquina do these solutions work for what the user was trying to do? Or am I misunderstanding?

**Comment by eabquina** [comment]
@ari-gold @rachelwhitton I reviewed the conversation with the customer; the need was to use Private Path for Files (Not Version Controlled).  I guess they need it for some kind of "Private files download permission" use-case.

I tried to look around and it seems they can only do this manually. 
If you agree, I'll mention that as a section. It has to be done per site, and would not be part of custom upstream.

Note: Protected Web Paths is a good addition for this doc!

**Comment by alexfornuto** [comment]
@eabquina after further review, it seems like the [Private Files](https://pantheon.io/docs/private-paths/#private-path-for-files) documentation addresses what you've clarified the customer's concerns to be. We're going to close this issue. Feel free to reopen or submit a new issue if you have found further clarification to an outstanding need.
