### ISSUE TITLE
Drush Minor Versions

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3120]
Re: </docs/drush>
## Issue Description
User feedback wants to know if he can pick minor versions

## Suggested Resolution
Find answer and specify

**Comment by greg-1-anderson** [comment]
Users can install their own site-local Drush with their Drupal sites. Then the Pantheon Drush will redispatch to use their Drush.

Other than that, users cannot select the minor version of Drush to use, and should not select any major version of Drush lower than 8.  n.b. Drush 9 is not yet installed globally, but may be used by the same process described above.
