### ISSUE TITLE
Vanity Domains Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3132]
Re: [Vanity Domains](https://pantheon.io/docs/vanity-domains/)

Priority (Low):

## Issue Description:
Vanity domain not working on a site even it is already configured for the organization

## Suggested Resolution 
Add a section to tell, If a site was created BEFORE the vanity domain was added to the organization, it will not work.

**Comment by eabquina** [comment]
Update: I tried to add using Terminus

`terminus domain:add <site-name>.<env>  <env>.sites.domain.com`

It worked, but if added via the dashboard, it didn't work.

**Comment by alexfornuto** [comment]
@eabquina are you saying that vanity domains cannot be applied to existing site, except through terminus? If they should be able to it's product bug, not a docs issue.

**Comment by eabquina** [comment]
@alexfornuto @rachelwhitton  Based from another ticket, it says that if we converge a site, it will change and get to use the new vanity domain (even if a site was created prior the vanity domain was added). 

Let me gather more info. In the end, maybe this will be a new troubleshooting section on what to expect for Vanity Domains after adding, and what sites created prior adding the vanity domain

**Comment by alexfornuto** [comment]
See BUGS-1734
