### ISSUE TITLE
December/January Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3142]
Add December platform changes and new features to be included in the December/January Changelog.

**Comment by alexfornuto** [comment]
[Pulled from last month's issue](https://github.com/pantheon-systems/documentation/issues/3055#issuecomment-350023151)

**Comment by ari-gold** [comment]
An issue was fixed where the Redis cache was not cleared during clone operations.

ref. BUGS-1364

**Comment by ari-gold** [comment]
Updated PHP 5.6 to 5.6.32
http://www.php.net/ChangeLog-5.php#5.6.32

Updated PHP 7.0 to PHP 7.0.26
http://www.php.net/ChangeLog-7.php#7.0.26
http://www.php.net/ChangeLog-7.php#7.0.25
http://www.php.net/ChangeLog-7.php#7.0.24


Updated PHP 7.1 to 7.1.12
http://www.php.net/ChangeLog-7.php#7.1.12
http://www.php.net/ChangeLog-7.php#7.1.11
http://www.php.net/ChangeLog-7.php#7.1.10
http://www.php.net/ChangeLog-7.php#7.1.09

**Comment by ari-gold** [comment]
Added HTML Tidy PHP extension (blog post forthcoming)

**Comment by ari-gold** [comment]
An issue was fixed where UTM parameters could cause redirect loops.

ref. BUGS-1453, BUGS-1470
