### ISSUE TITLE
Describe Content VS Code Better

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/documentation#3143]
Priority (Low‚ Medium‚ High): Low

## Title
Understanding the difference between code, files and content

## Description
Many people get tripped up when cloning "files" to Test or Live and not understanding why their new plugin isn't showing up. I think part of the reason for the confusion is due to our usage of the word "files". The code that makes up a module, plugin, template, etc. is in a "file". Perhaps we should change "files" to "assets"?

## Outline
There are a few concepts that need a bit of separation, such as:

- code (these are the php files – plugins, themes, etc)
- files (images, text files, pdf documents, basically anything in wp-content/uploads/ or sites/default/files)
- content (this is the database – posts, pages, nodes, etc)

The database and files can be modified directly in production, without going through the dev —> test —> live workflow. This is actually recommended: you want your users to write posts and upload files directly in Live.

The code however needs to go through version control and thus whenever you modify a php file (i.e. a plugin) you need to make a commit, check it in dev, and then push to test and live. Installing a plugin directly in Live is not possible.

## Expected Audience
Anyone new to the platform.

## Path
I'm not sure about the best place for this. https://pantheon.io/docs/pantheon-workflow might be a good place but it's already a fairly long guide.

## Reason
This comes up all the time. The text in the Outline section above is our go-to snippet for when we need to explain this. Searching internally for the keywords "bit of separation" for when this was used results in 16 chats and 44 tickets. I field probably 4 or 5 of these a week and I'm sure I'm not the only one. 

Examples from Desk:
51921
76840

And Chat:
13584216747
13585479321

**Comment by rachelwhitton** [comment]
+1 Although, I'd like to avoid a new doc. Suggest revising the existing "Code Moves Up, Content Moves Down" section of [Use the Pantheon Workflow](https://pantheon.io/docs/pantheon-workflow/#code-moves-up-content-moves-down) to include definitions for the three major components of a site.
