### ISSUE TITLE
How Pantheon Prevents Plan Abuse Title Update 

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#3145]
Re: [How Pantheon Prevents Plan Abuse](https://pantheon.io/docs/preventing-plan-abuse/)

Priority (Low‚ Medium‚ High): Med-Low

## Issue Description:
Title focuses on the negative and is hard to remember when searching

## Suggested Resolution 
New Title:
Page View Limits on Site Plans
or something

**Comment by alexfornuto** [comment]
Already being discussed in #3144
