### ISSUE TITLE
PEG Doc Updates

### ISSUE THREAD

**Issue by JessiFischer** [pantheon-systems/documentation#3177]
https://pantheon.io/docs/pantheon-enterprise-gateway/
PEG continues to be perpetually confusing and an overhaul on the main doc would be useful. We need to more fully answer:

*How the constant relates to the port number
*How to use this in code (when to use the port, when to use the PHP constant, how to extract)

From a chat with Gary trying to help a client get a custom D8 LDAP module working:

"The constant contains the port number.  Customer code needs to extract the port number from the constant and use the port number everywhere a port number is required. The reason for this is that the port number will change from environment to environment to environment and whenever a binding migrates."

These lines of code: (edited)

[11:13] 
$resolve_host = array(sprintf(“%s:%d:%s”, $host, constant($soip_constant_name), $localhost));
$ldaphost = “ldaps://127.0.0.1:” . PANTHEON_SOIP_LDAP;
$ldaphost = sprintf(‘ldaps://127.0.0.1:%s’, PANTHEON_SOIP_LDAP);

[11:13] 
all retrieve this port number from the constant

[11:14] 
The first one does because there is an earlier line that does this:

[11:14] 
$soip_constant_name = “PANTHEON_SOIP_LDAP”;

**Comment by JessiFischer** [comment]
Good ticket thread for reference: https://pantheon-systems.desk.com/agent/case/96264

**Comment by alexfornuto** [comment]
@JessiFischer What doc does this issue pertain to?

**Comment by JessiFischer** [comment]
Oops! Sorry @alexfornuto , it's this one: https://pantheon.io/docs/pantheon-enterprise-gateway/
