### ISSUE TITLE
January/February Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3186]
You know the drill.

**Comment by greg-1-anderson** [comment]
Drupal 8.4.4 : https://github.com/pantheon-systems/drops-8/pull/200

**Comment by greg-1-anderson** [comment]
WordPress 4.9.2: https://github.com/pantheon-systems/WordPress/pull/145

**Comment by ari-gold** [comment]
Update to latest PHP 7.2.1, 7.1.13, 7.0.27 and 5.6.33

http://php.net/ChangeLog-7.php#7.2.1
http://php.net/ChangeLog-7.php#7.1.13
http://php.net/ChangeLog-7.php#7.0.27
http://php.net/ChangeLog-5.php#5.6.33

**Comment by rachelwhitton** [comment]
wp-cli 1.4.1

**Comment by greg-1-anderson** [comment]
Update WP-CLI to 1.4.1: 
https://github.com/pantheon-systems/rpmbuild-wp-cli/pull/11

Update site-audit to 8.x-2.1 (Drupal 8) / 7.x-1.16 (Drupal 7), and registry-rebuild to 7.x-2.5:
https://github.com/pantheon-systems/rpmbuild-drush-extensions/pull/1

**Comment by ari-gold** [comment]
Launch check now supports Drupal 8
Access the launch check report from the "Status" tab of each site environment, powered by the open source Site Audit project hosted on drupal.org.
