### ISSUE TITLE
301 redirect for http to https susceptible to a man in the middle attacks

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/documentation#3189]
Re: [Switching Sites from HTTP to HTTPS](https://pantheon.io/docs/http-to-https/#redirect-to-https-and-the-primary-domain)

Specifically, Redirect to HTTPS and the primary domain

## Issue Description
We recommend a `301` redirect from HTTP to HTTPS, which is susceptible to a man in the middle attacks on HTTP requests.

## Suggested Resolution
Highly suggest setting [HSTS](https://pantheon.io/docs/hsts/) by adding it as a step to this doc. A possible alternative is to update the redirect recommendation to `307` from `301`.

**Comment by Shelob9** [comment]
Following. 

I think the concern is outlined well here: https://www.troyhunt.com/understanding-http-strict-transport/

**Comment by alexfornuto** [comment]
The end of this document links to our [HSTS](https://pantheon.io/docs/hsts) doc. @ataylorme do you think we need to move this suggestion up?

**Comment by ataylorme** [comment]
Right now it's marked optional. Maybe we add a section about HTTP to HTTPS with a `301` alone being an issue? I'm not sure of the answer.

@Shelob9 originally asked me why we recommend doing a `301` when it's open to attack.

**Comment by Shelob9** [comment]
I'm also wondering why the 301 is used in the standard WordPress wp-config.php vs a 307

Also, to clarify, I'm using "wondering" in a non-confrontational context. I honestly don't know, just reading more about this subject, which I am not an expert on. So I want to make sure the advice I give re: WordPress HTTPS setup is right and also that my Pantheon-hosted sites are setup right.

**Comment by ataylorme** [comment]
I'm not an expert either. Maybe @davidstrauss can weigh in on the best practice.

**Comment by ataylorme** [comment]
@alexfornuto this is still unclear to me. The [Require HTTPS with the HSTS Header doc](https://pantheon.io/docs/hsts/) asks you to [install this plugin](https://wordpress.org/plugins/lh-hsts/).

The code example still suggests doing a `301` redirect from HTTP to HTTPS. Does using the plugin and HSTS make the unnecessary? If so, should we update the code example?

cc @davidstrauss

**Comment by davidstrauss** [comment]
I think I followed up internally on Slack, but I'll expand on my response here:

* The code in an HTTP redirect does not make it more or less susceptible to MitM. Both 301 and 307 are equally vulnerable when issued by a web server over HTTP.
* The 307 redirect shown in the linked document isn't one from the webserver. It's a "response" that Chrome generates when the website matches preloaded or cached HSTS patterns. Chrome calls it an "internal redirect" to emphasize that it wasn't actually generated by the webserver.
* The official use of 307 is for a "temporary redirect." This is appropriate for Chrome's generated responses based on HSTS rules, but it's not appropriate for a real webserver indicating that the page moved permanently to HTTPS. HTTP 301 is the right choice for that.

We do encourage use of HSTS (and provide documentation on deploying it), but it would be inappropriate to send HTTP 307 responses from the application itself for an HTTPS redirect. Chrome should still show HTTP 307 for its "internal redirects" if HSTS is properly configured and a user tries to go to an HTTP URL for the site.

**Comment by ataylorme** [comment]
Thank you for expanding @davidstrauss. The part I was missing is that HSTS allows the browser to handle the redirect for you.

The complaint is that our current docs recommend a PHP level `301` redirect from HTTP to HTTPS. I think we should update to recommend HSTS rather than implementing the redirect at the CSM level.

Any objection?

**Comment by alexfornuto** [comment]
It sounds to me like _both_ should be done for maximum effectiveness.  I feel like my adjustment in #3191 accurately denote what @davidstrauss has suggested as best practice.

I would vote to close this issue.

**Comment by davidstrauss** [comment]
Yes, doing both is best. That way, non-HSTS clients will still get redirects. It's better than non-HSTS clients getting nothing, and it doesn't worsen the MitM risk that non-HSTS clients have.

**Comment by ataylorme** [comment]
Thank you for clarifying. Going to close this out
