### ISSUE TITLE
No longer store creds as secret text

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3190]
Re: [Automatically Test and Deploy GitHub Changes to Pantheon from an Existing Jenkins Server](https://pantheon.io/docs/guides/jenkins/)
## Issue Description
From the Power Users Slack:

>Hey guys just want to point out the docs for setting up Jenkins + Pantheon seems to be wrong. It mentions for credentials that to store them as “Secret Text” however with newer versions of Jenkins + the Git Plugin those fields will not display as proper credentials. They must be stored as other formats, username/password or ssh.

## Suggested Resolution
Update the guide to use the correct format.

CC @sukottokun

**Comment by sukottokun** [comment]
I'll try to check it out next week! Thanks for the update @alexfornuto

**Comment by alexfornuto** [comment]
Scott resolved this by updating the plugin, no docs changes needed.
