### ISSUE TITLE
Make guides navigation independently scrollable

### ISSUE THREAD

**Issue by kimby77** [pantheon-systems/documentation#3196]
Re: Guides navigation

## Issue Description
On the Terminus Manual I noticed that the navigation on the left side, you can't see the options on the bottom without scrolling all the way down the main page. This would apply to any Doc Guide using this pattern (Quick Start guide, etc...). 

Example page: https://pantheon.io/docs/terminus/commands/

![image](https://user-images.githubusercontent.com/19398001/34682997-9b03ea16-f455-11e7-9fc6-d3c8598b1b7b.png)

## Suggested Resolution
To improve usability of navigation, I suggest we make the navigation area independently scrollable. When a user has their mouse hovered over the navigation, I'd expect they'd be able to scroll up/down on the navigation without scrolling the main content.  Open to other suggestions as well!

**Comment by rachelwhitton** [comment]
Thanks @kimby77! Getting ready to work this one soon, we'll resolve by:

- Identifying CSS required for independently scrollable navs on paginated content types
- Apply that to `col-md-3 manual-guide-toc` entities
