### ISSUE TITLE
Installing Redis problem in Composer+CI D8

### ISSUE THREAD

**Issue by jproctor** [pantheon-systems/documentation#3215]
Re: [Installing Redis on Drupal](https://pantheon.io/docs/drupal-redis/)
## Issue Description

The instructions for adding Redis to a D8 site don’t include instructions that work with a [drops-8-composer](https://github.com/pantheon-systems/example-drops-8-composer) site. 

While it was easy enough to adapt them in a branch on my local development copy, CircleCI was unable to test it. In the 
`prepare database for site-under test` stage, creating a multidev environment failed with this error:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
You have requested a non-existent service "cache.backend.redis".
```

## Suggested Resolution

I described the problem in the Pantheon Community slack, and @greg-1-anderson suggested adding the code first, then updating the settings. This approach worked.

Step 2 should be amended to mention that the Composer workflow requires the code to be deployed to Pantheon _before_ the settings can be updated.

**Comment by alexfornuto** [comment]
This issue should be addressed while processing #3200
