### ISSUE TITLE
Requirements for Automated Certificate Renewal

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3216]
Re: [HTTPS on Pantheon's Global CDN](https://pantheon.io/docs/https/)

Priority (Low):

## Issue Description:
Customer wanted to be clear if A and AAAA records are actually needed for automated certificate renewal

Also, customer asked about how long and when they should check if the certificate renewal worked

## Suggested Resolution 
No need for A and AAAA records. The requirement is only to have the assigned domains and its DNS records be pointed to Pantheon, regardless of A, AAAA or CNAME records

Also, need to point out when do we renew certs, and in what frequency (number of days, months etc)

**Comment by alexfornuto** [comment]
@ari-gold  Can you confirm that:

> The requirement is only to have the assigned domains and its DNS records be pointed to Pantheon, regardless of A, AAAA or CNAME records

is correct?

**Comment by rachelwhitton** [comment]
Note: renewal info added in master on 3bf52d4

**Comment by rachelwhitton** [comment]
Closed by #3034
