### ISSUE TITLE
Multidev Doc Update 

### ISSUE THREAD

**Issue by cqbent** [pantheon-systems/documentation#3227]
Re: [Multidev](https://pantheon.io/docs/multidev/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
in Clone Content section of the document is wrong - there is no "Workflow" button in the dashboard. Should be Database/Files. Also would be nice to add step by step process on cloning a multidev branch to a local environment and making updates to that environment.

## Suggested Resolution 
1) change "Workflow" to "Database/Files"
2) add documentation on process of cloning a multidev branch to a local environment (git clone; run git branch -a; checkout multidev branch; make changes and commit; push to origin multidev branch; etc.)

**Comment by alexfornuto** [comment]
Thanks for letting us know @cqbent!
