### ISSUE TITLE
Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/documentation#3254]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs/cloudflare/)

Priority  Medium:

## Issue Description:
Cloudflare domain configuration lists old CNAME-only approach to DNS settings

## Suggested Resolution 
Update DNS recommendations

**Comment by rachelwhitton** [comment]
I believe CNAME flattening is recommended in this case because the provider supports it, and it's preferable to using a specific IPv4 and/or IPv6 addresses. 

Can you clarify what approach you recommend instead @aaronbauman ?

cc @ari-gold  can you weigh in?

**Comment by my-profile-upstream** [comment]
The latest DNS instructions include A & AAAA records as well as CNAMEs, but this doc only mentions CNAMEs.
This is confusing.

**Comment by aaronbauman** [comment]
The latest DNS instructions include A & AAAA records as well as CNAMEs, but this doc only ~~mentions~~ recommends CNAMEs.
This is confusing.

**Comment by rachelwhitton** [comment]
Thanks for clarifying @aaronbauman! We describe this in the section [Locate Pantheon DNS Values](https://pantheon.io/docs/cloudflare/#locate-pantheons-dns-values) but we can do a better job at calling out the discrepancy between recommended values here and the ones in the site dashboard. 

FWIW, there's an internal issue open in our backlog to recommend CNAME values only in the site dashboard with no ETA (IO-2449)
