### ISSUE TITLE
Warn that the Apache Solr module for Drupal 8 requires Composer

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#3263]
From #composer-workflow in the Power Users slack channel:

> *ALSO,* idk if it was mentioned, but Pantheon + Solr requires composer, sooooo there's that.
> (PS we think y'all should prob be more up-front about that)
> (not that you're lying, not by any means, but it feels like a significant factor for folks to consider when deciding how to set themselves up, and it's extremely impractical (at best) to change a site from non-composer to composer after the fact)

**Comment by alexfornuto** [comment]
From [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8/#before-you-begin)

> Solr on Drupal 8 requires a Composer managed workflow, as described in our Build Tools guide. Since one module relies on Solarium, an external library, in addition to Composer's autoloader, we cannot support non-Composer workflows for Solr on Drupal 8. For details, see this Drupal.org issue.

When I tested Solr on WP, D7, and D8, I found the latter to be the only one where the user needed to explicitly use Composer in their CMS setup.

@greg-1-anderson do you know if the author of that comment was using D8, or a different CMS?

**Comment by greg-1-anderson** [comment]
@alexfornuto Yes, sorry, this was a Drupal-8-specific comment.

**Comment by greg-1-anderson** [comment]
So, yeah, looks like this can be closed "already fixed". Maybe the person commenting didn't see the note, or maybe it was added after they first tried to set up Solr on D8.
