### ISSUE TITLE
Secure pages can cause too many redirects error if no pages matched

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#3264]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High):

## Issue Description:

See Ticket 97795

## Suggested Resolution 

Add note to problematic plugins/modules

**Comment by slashzero** [comment]
Happy yo reproduce and work on this

**Comment by alexfornuto** [comment]
After reading the ticket in its entirety, the issue stems around a possible incompatibility with a module ( [Secure Pages](https://www.drupal.org/project/securepages) ) and our HTTPS redirects described [here](https://pantheon.io/docs/domains/)

The site in question is D6, and the module in question has a beta version for D7 that was last updated in 2013.

**Comment by slashzero** [comment]
Given that D6 is EOL and module is beta for D7, in retrospect I don't think other sites are likely to benefit from this being added.
