### ISSUE TITLE
Global CDN - New POPs

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3270]
Re: [Frontend Performance](https://pantheon.io/docs/guides/frontend-performance/)

Priority (Low‚ Medium‚ High): Med

## Issue Description:
POPs are out of date - this doc says 30+ when it's actually closer to 50 atm

## Suggested Resolution 
- Update maps to include new locations (based on https://pantheon.io/global-cdn) 
- Update docs throughout for each occurrence of 30+ POPs

cc @ari-gold

**Comment by alexfornuto** [comment]
Updated, but leaving this issue open and blocked while the marketing page is updated.

**Comment by alexfornuto** [comment]
Reached out to Michelle for updated maps graphics. ETA ~1 week

**Comment by rachelwhitton** [comment]
[CDN-maps-Q1-2018.zip](https://github.com/pantheon-systems/documentation/files/2027717/CDN-maps-Q1-2018.zip)
