### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by smiroshnichenko** [pantheon-systems/documentation#3273]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Its not obviously and not documented that **upstream:updates:list** command displays non-refreshed information from cache. User excepts to see actual list of upstream updates instead. 
So user should execute **site:upstream:clear-cache** before the execution of **upstream:updates:list** now.

## Suggested Resolution 
Update description of the command **upstream:updates:list** to explain that its required to execute **site:upstream:clear-cache** before to see non-cached information. 

Thanks

**Comment by rachelwhitton** [comment]
Thanks for the issue @smiroshnichenko! The docs actually pull the descriptions from the help output of Terminus, so the adjustment must be done within the pantheon-systems/terminus project itself. I went ahead and opened an issue there you can follow along with: https://github.com/pantheon-systems/terminus/issues/1814
