### ISSUE TITLE
Better format for Terminus example commands.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3274]
Re: [Style Guide](https://pantheon.io/style-guide)
## Issue Description
A reader reports, with great verbosity, that the use of `<site>.<dev>` can be confusing.

## Suggested Resolution

 - [ ] Define in the style guide a replacement example, preferably one use dummy variables and no extra symbols.
 - [ ] Find & replace throughout the repository to align.

**Comment by rachelwhitton** [comment]
Consolidating #3252 into a single issue: 

## Issue Description:
The style guide talks about exporting local variables, but it doesn't set a standard for how/where for consistency.

## Suggested Resolution
Create a visually distinct alert to notify the user local environments need to be exported
Consider whether this notice should be consistently fixed (e.g., at the top of the page, within Before You Begin section) or if it should be placed in context before the first instance.
