### ISSUE TITLE
Adding Cron Jobs

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3277]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron/)
## Issue Description
From feedback:

>is it possible to add lines?  I need to add a job

## Suggested Resolution
 - [ ] Identify if Elysia Cron can add jobs
 - [ ] If so, document it.

**Comment by mlncn** [comment]
Is [this](https://pantheon.io/blog/running-drupal-8-data-migrations-pantheon-through-drush) relevant?

Is workarounds like [this](https://www.drupal.org/project/drupal/issues/2764287) the only option right now compared to just putting a drush command in a cron job?

**Comment by alexfornuto** [comment]
My research hasn't found an easy way to add a cron job, only to use the `hook_cron` call as @mlncn indicated. I would consider that approach to be beyond the scope of this guide, except to add a link [here](https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_cron/8.6.x) under the Resources heading.

Thoughts?

**Comment by alexfornuto** [comment]
Reached out to @pantheon-systems/ace via Slack
