### ISSUE TITLE
Reading Pantheon Environment Configuration Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3289]
Re: [Reading Pantheon Environment Configuration](https://pantheon.io/docs/read-environment-config/)

Priority (Low‚ Medium‚ High):

## Issue Description:

I am pretty sure that domain access config needs to go above fi Redis config and fast_404 etc. Could we double check and edit accordingly?
I think Tara might remember too - we had a couple of issues on this that she was in on.

## Suggested Resolution

**Comment by alexfornuto** [comment]
@tinefin are you referring to the placement of the domain access snippet in `settings.php`? If not, what do you mean?

Please clarify this issue so that we can take action.

**Comment by tinefin** [comment]
Internal reference: 98141

Domain access config needs to go above redis config in settings.php.
