### ISSUE TITLE
February/March Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3292]
[ ](https://open.spotify.com/track/2ga5HWiAHUon3G6hW03zZJ)

**Comment by greg-1-anderson** [comment]
WordPress 4.9.3: https://github.com/pantheon-systems/WordPress/pull/148

**Comment by alexfornuto** [comment]
> https://github.com/pantheon-systems/documentation/issues/3292#issuecomment-363239597

Included in the previous changelog.

**Comment by greg-1-anderson** [comment]
Not so! January/February had WordPress 4.9.2.

**Comment by ari-gold** [comment]
# Legacy SSL Load Balancer Price Increase 
Starting February 28th the cost for legacy load balancers will increase from $30/month to  $60/month. To avoid increased charges, upgrade to the Global CDN by updating DNS records.

**Comment by pantheon-upstream** [comment]
Drupal 8.4.5

**Comment by pantheon-upstream** [comment]
Drupal 7.57: https://github.com/pantheon-systems/drops-7/pull/99

**Comment by alexfornuto** [comment]
New Changelog in #3439
