### ISSUE TITLE
IPv6 Expanded for some DNS Manager

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3293]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low):

## Issue Description:
Customer has domain configured in Squarespace and migrated site to Pantheon. When trying to configure "AAAA" records, their DNS manager won't accept the "shortened" version

## Suggested Resolution 
Provide correct suggestion on how to better "expand" the AAAA record entry.
Ex.:
2620:12a:8000::3
2620:12a:8000:0:0:0:0:3
2620:012A:8000:0000:0000:0000:0000:0003 <--- worked for Squarespace

Is this correct? Used some online expand tools. Need to confirm if this won't introduce any issues.

**Comment by ari-gold** [comment]
Yes, expanding is fine (use longest form from http://ipv6-literal.com/). We could have a general FAQ or troubleshooting section for this issue. We could also add a link to product with DNS-specific instructions for Squarespace...before doing that @eabquina did we ask customer to submit a bug report to Squarespace?

**Comment by eabquina** [comment]
@ari-gold I did ask the customer to go back to Squarespace, and from there we learned they "needed" an expanded address. It seems to have worked though.

Thanks for that, I was worried if it would affect certificate renewal, or something else.
