### ISSUE TITLE
Confusing Doc Redirection

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3305]
Re: https://pantheon.io/docs/guides/launch/next-steps/
## Issue Description
I did not see a pantheon-system / dashboard (or similar) repo so this issue may need to be moved. Basically, in the 'Domains / HTTPS' tab of any live environment when a custom domain is added and is successfully pointing to Pantheon's Global CDN the following success alert is displayed:

> DNS pointing successfully at Pantheon’s Global CDN
> See our [performance guide](https://pantheon.io/docs/guides/launch/next-steps/) for best practices to boost your site's performance.

When I click on 'performance guide' I expected to **only** read information about site performance. Instead, I am presented with the entire 'Best Practice Checklist for Going Live' checklist, which is confusing.

## Suggested Resolution
**Option 1:**
DNS pointing successfully at Pantheon’s Global CDN
See the [Final Checklist](https://pantheon.io/docs/guides/launch/next-steps/) on best practices for going live.

**Option 2:**
DNS pointing successfully at Pantheon’s Global CDN
See our [performance docs](https://pantheon.io/docs/performance/) for best practices to boost your site's performance.
(link changed to https://pantheon.io/docs/performance/)

**Comment by dustinleblanc** [comment]
Pull request submitted to appropriate repository/code, closing, thanks @cityofoaksdesign!
