### ISSUE TITLE
Drupal Launch Check (Status)

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3307]
Re: https://pantheon.io/docs/drupal-launch-check/
## Issue Description
Status checks are available for Drupal 7 and Drupal 8 sites, but the [Drupal Launch Check doc](https://pantheon.io/docs/drupal-launch-check/) only specifies Drupal 7.

## Suggested Resolution
**Change this**:
Pantheon provides static site analysis as a service for Drupal 7 sites to make best practice recommendations on site configurations.

**To this**:
Pantheon provides static site analysis as a service for Drupal sites to make best practice recommendations on site configurations.

**Comment by rachelwhitton** [comment]
Thanks for reporting @cityofoaksdesign! Much appreciated!
