### ISSUE TITLE
Unlinked Sentence

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3311]
Re: https://pantheon.io/docs/hsts/
## Issue Description
Under HSTS Header Configuration Attributes > preload > the last sentence of the paragraph:
"[Here is where you add your site to the preload list](https://hstspreload.org/){.external}."

## Suggested Resolution
Make the last sentence a link: [Here is where you add your site to the preload list.](https://hstspreload.org)

**Comment by rachelwhitton** [comment]
Thanks for reporting @cityofoaksdesign! Much appreciated!
