### ISSUE TITLE
Confirm override.html feature

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3314]
Re: [Running WordPress and Drupal as a Backend API](https://pantheon.io/docs/headless/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Doc describes using `override.html` to run a single page app from the root dir. Power user in slack reports they could not get this to work on a site configured w/nested docroot.

## Suggested Resolution 
Found a related feature request in the backlog FEAT-441 

Confirm whether `override.html` is supported (it was reported to work in the original PR #2872) - if so, confirm that it is supported on nested doc root configurations. If it doesn't work on nested doc root sites, report as a bug. 

cc @eabquina

**Comment by jfussion** [comment]
@rachelwhitton I upload override.html to my test site and it is not working as described in our docs. Not sure if this is a bug since override.html was just a suggestion in FEAT-441 and not yet implemented

**Comment by eabquina** [comment]
@rachelwhitton @jfussion confirmed and agreed, it turns out it was not yet implemented yet as of now.
