### ISSUE TITLE
Style Guide Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3324]
Re: [Style Guide](https://pantheon.io/docs/style-guide/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Alert usage is not described
## Suggested Resolution 
Set standards for `alert-success`, `alert-info`, `alert-warning`, `alert-danger` usage

**Comment by alexfornuto** [comment]
`alert-warning` doesn't seem so be defined, and is rendered the same as `alert-info`.

`alert-info` and `alert-danger` are described as Notes and Warnings in the style guide.
