### ISSUE TITLE
Domains and Redirects Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3333]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low):

## Issue Description:
Customer wants to use the same domain to another Pantheon site, being a new site (Drupal 7 to Drupal 8 migration). We don't have a tool to change that or do a quick change other than doing a manual remove, and re-assign

## Suggested Resolution 

Provide instructions on the specific steps of removing first from the origin site, then add to the new site, and see the new DNS values and update DNS..

**Comment by alexfornuto** [comment]
@eabquina FYI this information already lives in it's own full guide [here](https://pantheon.io/docs/switching-dns/). To resolve this issue, we're linking from Domains and Redirects to said guide.
