### ISSUE TITLE
Yoast plugin requires include in nginx.conf file

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3357]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority (Low):

## Issue Description:
Customer is trying to follow instructions of Yoast plugin to have redirects, include  .redirects folder

## Suggested Resolution 
Add as unsupported plugin for this feature

**Comment by alexfornuto** [comment]
@eabquina @xq42 was unable to find Yaost documentation related to redirects. We are unable to take action on this issue as it stands currently. Please clarify _exactly_ what the issue is.

**Comment by eabquina** [comment]
@alexfornuto @xq42  for Redirects Yoast SEO feature, under Settings, it detects two options for its redirect method, PHP and Web Server...
If Web Server is selected, it provides instructions to create an **include** in the nginx.conf file. It displays to create a file in this path and add as an include in nginx.conf:
`include /srv/bindings/<binding_id>/code/wp-content/uploads/wpseo-redirects/.redirects`

**Comment by alexfornuto** [comment]
@eabquina Thanks for the additional information. I just need to know one more thing to make this actionable: Are you saying that the customer should not use the "Web Server" option from the Yoast plugin, or that additional configuration is required?

**Comment by eabquina** [comment]
@alexfornuto yes, since we can't modify nginx.conf (as what the plugin requests), this will be for PHP only.

**Comment by alexfornuto** [comment]
@eabquina please review #3777 as a resolution.
