### ISSUE TITLE
Backups Schedule Tab Layout and Explanation

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3358]
Re: [Backups Tool](https://pantheon.io/docs/backups/)

Priority (Low):

## Issue Description:
The customer is trying to change "Daily" backup schedule but there is no button for it. The correct explanation is that the "Weekly Backup button is the same trigger that will change the schedule.

## Suggested Resolution 
Provide screenshots of how the Backup Schedule tab layout looks like and explain how it works
Clarify that it works in tandem, Daily/Weekly schedule is together

**Comment by alexfornuto** [comment]
@eabquina What was the customer trying to change about the daily backup? There is no adjustment to be made to the daily backup, only what day the weekly backup is taken.

**Comment by eabquina** [comment]
@alexfornuto For the customer, they want to schedule backup for a specific time of day that at least match their end of business hours or off-peak hours. Also, they want to specify the weekly schedule to be of a specific time of the day. 

It seems that setting time of the day for the weekly backup schedule is not possible too, but at least can try to press save a couple of times until the time is right. I propose to add in the schedule section to clarify this item.
