### ISSUE TITLE
Evaluate Removal of Global Redirect from Modules and Plugins with Known Issues

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3379]
Re: Modules and Plugins with Known Issues (Global Redirect)
## Issue Description
**Issue**: Too many redirects error when site is in maintenance mode.
**Solution**: Ensure that the "Frontpage Redirect Handler" is not checked in the Global Redirect administration page. Alternatively, [apply a patch to the module](https://www.drupal.org/node/1399024) to correct the issue.

## Suggested Resolution
Global Redirect should be able to be removed from the list of Modules and Plugins with Known Issues as [Issue 1399024](https://www.drupal.org/project/globalredirect/issues/1399024), "d7 version uses incorrect variable name for maintenance mode", was fixed in 7.x-1.6 that was released today.

https://www.drupal.org/project/globalredirect/releases/7.x-1.6

**Comment by slashzero** [comment]
+1 confirmed as working as expected with new spinup using 7.x-1.6
