### ISSUE TITLE
Modules and Plugins with Known Issues (Views data export)

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3394]
Re: Modules and Plugins with Known Issues
## Issue Description
The [patch](https://www.drupal.org/files/views_data_export_dir_conf.patch) referenced in the "Issue" paragraph was committed in [views_data_export 7.x-3.0-beta7](https://www.drupal.org/project/views_data_export/releases/7.x-3.0-beta7) and therefore may not need to be specifically referenced.

## Suggested Resolution
**Change this**:
Issue: This module requires the use of the /tmp directory. There is also a patch available, but we still cannot guarantee that the use of the /tmp directory will work successfully. See Using the tmp Directory section below for more information.

**To this**:
This module requires the use of the /tmp directory. See [Using the tmp Directory](https://pantheon.io/docs/modules-plugins-known-issues/#using-the-tmp-directory) section below.

**Comment by alexfornuto** [comment]
@cityofoaksdesign Thanks for submitting an issue! Which plugin on the list are you referring to?

**Comment by cityofoaksdesign** [comment]
Drupal's Views data export

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign!
