### ISSUE TITLE
Terminus Command Line (Dashboard Advanced Tab)

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3398]
Re: https://pantheon.io/docs/terminus/install/ VS. https://dashboard.pantheon.io/users/[user_id]#advanced
## Issue Description
There are some significant differences in the Terminus installation instructions in the [Terminus Manual](https://pantheon.io/docs/terminus/install/) vs. the installations instructions in the user dashboard (Advanced tab). 

## Suggested Resolution
Update the installation instructions in the user dashboard (Advanced tab) to more closely match the instructions outlined in the Terminus Manual in order to provide a more seamless set of instructions as exampled below:

## Terminus Command-Line Interface
Our command line interface, Terminus, provides advanced interaction with Pantheon. Terminus enables you to do almost everything in a terminal that you can do in the Dashboard and much more, such as [performing bulk operations](https://pantheon.io/docs/terminus/examples/#mass-update) on all your sites with one command.

Terminus is available for Mac OS X, Linux, and Windows 7 and 10.

## Requirements
- A command-line client
- PHP Version 5.5.9 or later (must include the [php-xml extension](https://secure.php.net/manual/en/dom.setup.php)). You can check your PHP version by running php -v from a terminal application.
- [PHP-CLI](http://www.php-cli.com/)
- [PHP-CURL](https://secure.php.net/manual/en/curl.setup.php)
- [Composer](https://getcomposer.org/download/) (NOTE: Composer is only in the "recommended" list [here](https://github.com/pantheon-systems/terminus))
- Windows Only: Terminus requires a *nix-like environment. If you don't already have a bash emulator, we recommend [Git for Windows](https://gitforwindows.org/).

If you already have it configured and are regularly using it, we have seen some users find success with [Bash on Ubuntu on Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (Windows 10 only).

## Install #3399 
Install the most recent release of Terminus with the following command within a directory where you have permission to write files. If in doubt, you can create a terminus directory in your $HOME and install there:

`$ curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install`

## Authenticate
Once Terminus is installed, login with a machine token, which is used to securely authenticate your machine. Machine tokens provide the same access as your username and password, and do not expire. For more information, see [Machine Tokens](https://pantheon.io/docs/machine-tokens/).

First, generate a Machine Token from **User Dashboard > Account > Machine Tokens**.

Once the token has been created, use it to authenticate Terminus by running the following command:
`$ terminus auth:login --machine-token=‹machine-token›`

After a token has been used, future sessions can be established by email:
`$ terminus auth:login --email=dev@example.com`

You are now ready to use Terminus! Get started by listing all your sites that you can manage with Terminus:
`$ terminus site:list`

Visit the [Terminus Manual](https://pantheon.io/docs/terminus/) to learn more about working with Terminus.

**Comment by cityofoaksdesign** [comment]
May also need to cross-reference with https://github.com/pantheon-systems/terminus#terminus--pantheons-command-line-interface

For example: the [Terminus Manual](https://pantheon.io/docs/terminus/install/) lists Composer as a "Requirement" and the [Terminus Github page](https://github.com/pantheon-systems/terminus#terminus--pantheons-command-line-interface) lists Composer as "Recommended"

**Comment by rachelwhitton** [comment]
Thanks for reporting @cityofoaksdesign! We'll submit a PR to adjust the copy in the Advanced tab along with a PR to the docs to send folks to the readme for advanced installation options

**Comment by alexfornuto** [comment]
PR 1392 to address the Dashboard instructions.

**Comment by allenfear** [comment]
Closing this as resolution will be pursued in product.
