### ISSUE TITLE
Organizations Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3408]
Re: [Organizations](https://pantheon.io/docs/organizations/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
The screenshot is outdated. We have now "Status" section. 

What's the difference between "Code Status" and "Status"? This is a bit confusing especially if there are no entries displayed under "Status".

Before:
![organization-dashboard-tour](https://user-images.githubusercontent.com/14119666/36513146-1a053254-17a9-11e8-8e19-209f3928c026.png)
Now:
<img width="330" alt="screenshot" src="https://user-images.githubusercontent.com/14119666/36513130-02b54b3e-17a9-11e8-940b-1bc543dc6b5d.png">

## Suggested Resolution 

- Update the screenshot
- Add a section explaining the difference between "Code Status" and "Status"

**Comment by lauren-kelly** [comment]
I think the only status we currently show there is frozen:
![org-status](https://user-images.githubusercontent.com/1576834/37608983-4db91070-2b72-11e8-9a37-50fc3b557f20.png)

**Comment by alexfornuto** [comment]
@lauren-kelly can we confirm if any other site statuses will show up there?

@cityofoaksdesign here's some more information on [inactive site freezing](https://pantheon.io/docs/platform-considerations/#inactive-site-freezing)
