### ISSUE TITLE
Update Plan Pages

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3415]
Re: https://pantheon.io/docs/select-plan/, https://pantheon.io/docs/site-payments/
## Issue Description
Screenshots and/or copy will need to be updated alongside upcoming dashboard design changes.

## Suggested Resolution
 - [ ] Work with @kimby77 to identify outdated information, as it becomes outdated.

**Comment by rachelwhitton** [comment]
Closing to be tracked internally
