### ISSUE TITLE
New Site Owner FAQs Doc Update 

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3416]
Re: [New Site Owner FAQs](https://pantheon.io/docs/site-owner-faq/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Under (h4) What add-ons are available for my site?
New Relic Pro is listed as an "add-on," which is technically no longer true.

## Suggested Resolution
Delete this sentence:
New Relic Pro offers a wide array of metrics that provide a nearly real-time look into the performance of a web application.

**Comment by alexfornuto** [comment]
@cityofoaksdesign what do you mean by this? New Relic Pro is still available for Pantheon Sites.

**Comment by cityofoaksdesign** [comment]
Yes, New Relic Pro is still available for Pantheon sites, but New Relic Pro is not really an "Add-on" like Apache Solr and Redis are.

In other words, the doc page says Apache Solr, New Relic Pro and Redis are available as add-ons and can be enabled "_From your Site Dashboard, click Settings, then click Add Ons. You will now see all the available add-ons for your site._"

However, when you click Add Ons New Relic Pro is not listed because it's no longer an "add-on", but rather a free "feature" available to any Pantheon site.

**Comment by alexfornuto** [comment]
@cityofoaksdesign ahh, I see. I'll take a stab at rephrasing so we can still let readers know about New Relic, without pointing them in the wrong direction.
