### ISSUE TITLE
New Site Owner FAQs Doc Update #2

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3417]
Re: [New Site Owner FAQs](https://pantheon.io/docs/site-owner-faq/)

Priority (Low‚ Medium‚ High): High

## Issue Description:
Under (h4) Can I downgrade my site to a personal plan?
I believe this sentence is no longer applicable:
"If you have HTTPS enabled on Professional plans and above, you will need to re-enable HTTPS and re-load your SSL certificate into Pantheon."

## Suggested Resolution
Remove sentence per https://pantheon.io/docs/select-plan/#downgrade-to-personal

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign! I changed this to High priority since it's providing incorrect information.
CC @ari-gold
