### ISSUE TITLE
Upgrade PHP Versions Doc Update 

### ISSUE THREAD

**Issue by xq42** [pantheon-systems/documentation#3418]
Re: [Upgrade PHP Versions](https://pantheon.io/docs/php-versions/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
While this doc does include links to the Drupal 7 php requirements and WordPress requirements pages, they are listed at the end of the doc in the "See Also" section making it, in my estimation, fairly likely that someone visiting this page looking for information on supported versions of php *for their cms* will miss them.

Also, the page does not include any reference to the Drupal 8 php requirements.

*Reason for the issue* - while php7.2 is available and supported on the platform, it is **not** supported by Drupal 8.4.x (the current version of D8). It will not be supported until 8.5.x.

While updating a few D8 sites I maintain, I also updated one of them to php7.2 via pantheon.yml assuming it would work since 7.2 is listed as supported by the platform. This resulted in errors that took some time to troubleshoot that could have been avoided if there were any indication on this page that, just because a specific version of php is supported by Pantheon, doesn't necessarily mean it is supported by your CMS of choice.

## Suggested Resolution 
Add a note of some type in the "Verify Current PHP Versions" section - either with links to the relevant D7, D8, and WP requirements, or a link to the "See Also" section - letting readers know to verify whether the version of php they'd like to use on the platform is actually compatible with their chosen CMS.

Also add a link to the D8 php requirements doc - https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements

**Comment by rachelwhitton** [comment]
+1 

We're going to handle this as an update to the existing note in the subsection **Available PHP Versions** that links to the following external resources: 

https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements#drupalversions
https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements#drupalversions
https://wordpress.org/about/requirements/

Preserve the note's content referring to D6, but provide no link.
