### ISSUE TITLE
How to remove unsupported table prefixes 

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3422]
Re: [Configuring Settings.php](https://pantheon.io/docs/mysql-access/#are-table-prefixes-supported)

Priority (Low‚ Medium‚ High):
Low

## Issue Description:
- Docs note that table prefixes are not support but do not mention what to do to remedy. 

## Suggested Resolution 
- Consider adding instructions to the FAQ question or link to remove said prefixes, e.g. this command could be run directly in mysql console by using a mysql client such as Navicat, Workbench or Sequel Pro.

`SELECT CONCAT(‘RENAME TABLE ‘, CONCAT(table_name, concat(‘ TO ‘, CONCAT(SUBSTR(table_name, 6), ‘;’))))FROM information_schema.tables WHERE table_schema =”pantheon” AND table_name LIKE “PREFIX_%”;`

**Comment by alexfornuto** [comment]
Closing as inactive.
