### ISSUE TITLE
Consider adding information about potential limiations for dropzone.js file uploads

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#3426]
Re: [Modules & Plugins](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority (Low‚ Medium‚ High): low

## Issue Description:

"Uploads work perfectly for less than 15 files, each file less than 400KB size.. But i would say that totally depends upon internet speed & existing traffic on site. (More than 15 files can be uploaded at a time too based on size of the file)."

Regarding dropzone.js (D8)

Reported in ticket 100193

## Suggested Resolution

**Comment by alexfornuto** [comment]
@slashzero thanks for the issue! We took a look at the ticket, and need a little more information before we can process this:

- Is dropzone.js a module? If so, are you suggesting a new section for it in this doc? Can you link us to the module's page on drupal.org? Or is it concerning modules that use dropzone.js? Just one, or any? 

- What's the issue/resolution? Are we documenting a limitation of a module / js file, or the platform?

**Comment by alexfornuto** [comment]
Closing due to lack of new information.
