### ISSUE TITLE
Backups Tool Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#3432]
Re: [Backups Tool](https://pantheon.io/docs/backups/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Customer asked if Pantheon is now hosting backups on GCP. Our current docs mention "Backups created on Pantheon are stored offsite on Amazon EC2 instances for redundancy" (https://pantheon.io/docs/backups/#access-backups). I asked Ben Zarzycki and he said ad-hoc (manual) backups are hosted on GCP, but our automated daily backups are still on Amazon. Ben mentioned that all backups will eventually be on GCP, but there's no ETA on that switch. Can docs investigate, confirm, and update as needed? Customer did not mention the importance of knowing this information, but said it would be good for customers to know. 

## Suggested Resolution:
 I will leave this to the docs/backups experts :)

**Comment by rachelwhitton** [comment]
Hey @ccorpus thanks for the issue. It sounds like this isn't quite ready for docs work yet -- once we're standardized on GCP, then we'll likely make a doc update. 

I'm not sure it's helpful to do one before then. I'll add a comment to the corresponding issue in Jira, closing doc issue for now - Refer to UNIPAN-3 for more discussion
