### ISSUE TITLE
March/April Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3439]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
Drupal 8.5.0

**Comment by ari-gold** [comment]
The `Surrogate-Key-Raw` header is now not sent by default.  Send the `Pantheon-Debug: 1` header to get it. This fixed a bug that caused twitter card validation to fail and reduces overall page size and will speed up load time
```curl -svo /dev/null -H "Pantheon-Debug:1" 'https://example.com'```

**Comment by ari-gold** [comment]
## Launch Check / Status Now Runs Per Environment
Launch check now runs per environment. Previosly running launch check, located on the "Status" tab, would run on all environments and this change helps address an issue where the checks would fail due to many Multidev environments on a site.

**Comment by pantheon-upstream** [comment]
Drupal 8.5.1: https://github.com/pantheon-systems/drops-8/pull/206

**Comment by pantheon-upstream** [comment]
Drupal 7.58: https://github.com/pantheon-systems/drops-7/pull/119

**Comment by greg-1-anderson** [comment]
PHP 7.2.4, 7.1.16, 7.0.29 and 5.6.35:
https://github.com/pantheon-cookbooks/php/pull/45

Drupal 6.40:
https://github.com/pantheon-systems/drops-6/pull/17

**Comment by greg-1-anderson** [comment]
Drupal 6.40:
https://github.com/pantheon-systems/drops-6/pull/17

**Comment by rachelwhitton** [comment]
Terminus 1.8.0

**Comment by greg-1-anderson** [comment]
### WordPress Security Upgrade
[WordPress 4.9.5](https://wordpress.org/news/2018/04/wordpress-4-9-5-security-and-maintenance-release/) has been pushed to all WordPress site dashboards.

**Comment by pantheon-upstream** [comment]
## WordPress 4.9.5: https://github.com/pantheon-systems/WordPress/pull/152

**Comment by pantheon-upstream** [comment]
## Drupal 6.43

**Comment by pantheon-upstream** [comment]
## Drupal 6.43 Update to Drupal pressflow-6.43.124. For more information, see https://github.com/pressflow/6/releases/tag/pressflow-6.43.124.

**Comment by pantheon-upstream** [comment]
## Drupal 6.43 
Update to Drupal pressflow-6.43.124. For more information, see https://github.com/pressflow/6/releases/tag/pressflow-6.43.124.

**Comment by alexfornuto** [comment]
Add new items to #3546
