### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by thegabrielstein** [pantheon-systems/documentation#3442]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority: Medium 

## Issue Description:
Tried to clone a Dev to Test environment through Terminus without initializing the Test environment, and it didn't warn me and as far as I can tell that caused the Test environment to become broken and irreparable. 

## Suggested Resolution
The user should be warned that the Environment isn't initialized when cloning or performing actions that are environment dependent instead of it saying everything is functioning properly and then erroring out invisibly.

**Comment by alexfornuto** [comment]
Tracking internally as `BUGS-2311`
