### ISSUE TITLE
Migrating to Custom Upstream Instructions

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3443]
Re: https://pantheon.io/docs/create-custom-upstream/ or https://pantheon.io/docs/maintain-custom-upstream/

Priority: Low

## Issue Description
There are doc pages re: creating and maintaining custom upstreams, but I don't see any documentation that explains how to switch an existing site(s) to a custom upstream. I did find the site:upstream:set command on the [Terminus Commands page](https://pantheon.io/docs/terminus/commands/), but when I tried to switch a site that I built for a client to my custom upstream, I was presented with a forbidden error and discovered that even though I built the site for my client, I can't switch my client's site to my custom upstream unless my client (the site owner) makes the request via a support ticket (they do not have access to terminus and don't want access).

## Suggested Resolution
Add a paragraph on either the '[Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/)' or '[Best Practices for Maintaining Custom Upstreams](https://pantheon.io/docs/maintain-custom-upstream/)' doc pages that explains the process of switching an existing site(s) to a custom upstream, specifically mentioning that only the owner of site can make the switch and if they don't have access to the command line they will need to file a support ticket requesting the switch be made.

**Comment by alexfornuto** [comment]
Great issue @cityofoaksdesign! We're going to make a new H2 level section at the bottom of [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/) to cover this much-needed process.

**Comment by alexfornuto** [comment]
@cityofoaksdesign please take a look at #3951 and tell me if that properly addresses your concerns.

**Comment by alexfornuto** [comment]
Thanks! I'm gonna add some warnings about merge conflicts, and suggest people clone new sites from the upstream and migrate data.
