### ISSUE TITLE
Quicksilver example of WP-CLI search-replace multiple domains after a db clone

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/documentation#3451]
Priority: Low

## Issue Description
WP-CLI search-replace is used during a clone of the database between environments. Many customers have multiple domains but they can only choose to replace one during the clone.

This QS script handles that scenario, without them having to use Terminus.

## Suggested Resolution

https://gist.github.com/twooten/e1da579fc998d64a4d9a9c72ff7e92dd

**Comment by alexfornuto** [comment]
@twooten Thanks for the issue! We're going to expand [this section](https://pantheon.io/docs/database-workflow/#troubleshooting) covering the use of Terminus to replace domains, by way of Terminus/Quicksilver tabs documenting the two methods of search-and-replace.

**Comment by twooten** [comment]
@alexfornuto great! I think the Quicksilver method would be helpful for people who would rather not have to run multiple Terminus commands every time they clone.
