### ISSUE TITLE
Find Terminus <site> argument

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3454]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/)

Priority: Low

## Issue Description:
How to quickly find the <site> name as needed to run Terminus commands, e.g. if the site _Label_ is Example Site, the corresponding `<site>` _Name_ would be `example-site`.

**Comment by jfussion** [comment]
@thomas-thackery how about `terminus site:info <site-UUID> --field name`?

**Comment by alexfornuto** [comment]
@thomas-thackery great issue! We're going to add to the [Example Usage](https://pantheon.io/docs/terminus/examples/) page a section on how to determine your "Site Name" based on your "Site Label".
