### ISSUE TITLE
HTTPS on Pantheon's Global CDN Doc Update 

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#3477]
Re: [HTTPS on Pantheon's Global CDN](https://pantheon.io/docs/https/)

Priority (Low‚ Medium‚ High):

## Issue Description:
In "Will HTTPS be available for my site throughout the upgrade process?" section
I'm seeing typo:

"Yes! As long as **your are** following the Dashboard DNS recommendations before starting the upgrade,"

## Suggested Resolution
Change "_your are_" to "_you are_":
Yes! As long as **you are** following the Dashboard DNS recommendations before starting the upgrade

**Comment by rachelwhitton** [comment]
Thanks @umandalroald! Hotfixed on master in 9e0225c
