### ISSUE TITLE
Fix link in imagecache article

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#348]
https://www.getpantheon.com/docs/articles/drupal/optimizing-the-image-cache-module-in-drupal-6 but:

#1. RC2 doesn't exist for imagecache 
#2. The link doesn't point to a patch

**Comment by nataliejeremy** [comment]
@ari-gold Would you happen to have the link to the patch or who I can ask?

**Comment by ari-gold** [comment]
No, I don't know. @timani @suzannealdrich ?

**Comment by nataliejeremy** [comment]
@bmackinney Do you know where the link is supposed to go?

**Comment by timani** [comment]
Patch is here: https://gist.github.com/tauno/4236123
