### ISSUE TITLE
Add anchors to New Relic Access issues

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3482]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/#troubleshooting)

Priority (Low‚ Medium‚ High):
Low

## Issue Description:
As a CSE, I would like to be able to provide a direct link to the New Relic Access issue that relates to the error the customer asks about. 

## Suggested Resolution
Include anchors to the New Relic Access issues in the troubleshooting section.

**Comment by alexfornuto** [comment]
Thanks for reporting @thomas-thackery! We're going to move the "New Relic Access" section above Troubleshooting as its own H2, and the subsections as linkable H3s.
