### ISSUE TITLE
Using SendGrid To Deliver Email Doc Update 

### ISSUE THREAD

**Issue by laras126** [pantheon-systems/documentation#3484]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs/guides/sendgrid/)

Priority: Medium

## Issue Description: 

Documentation out of date - setting up now involves creating an API key in the Settings area.

## Suggested Resolution

Update the documentation to reflect the changes in SendGrid.

**Comment by alexfornuto** [comment]
@laras126 thanks for letting us know! We'll test the doc and update accordingly. If there's a specific section that you could highlight as being out of date, that might help expedite a resolution.
