### ISSUE TITLE
https://www.getpantheon.com/docs/articles/sites/domains/developing-with-ssl/ is unclear

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#349]
Add a tag
add context
add image
remove reference to dev.mysite.gotpantheon.com

**Comment by nataliejeremy** [comment]
@bmackinney What should dev.mysite.gotpantheon.com be replaced with?

**Comment by nataliejeremy** [comment]
And what tag should be added? Can you add clarification? @bmackinney

**Comment by bmackinney** [comment]
`dev.mysite.gotpantheon.com` is now `dev-my-site.pantheon.io`

**Comment by bmackinney** [comment]
scratch that.

**Comment by bmackinney** [comment]
I'm not sure what "add a tag" means.
Does the sentence with the link to redirect to https imply the method for "switching connection mode to HTTPS" in sentence 1? 
Can we add two h2's for the contents to populate? 
CSE, community: Is there anything else we can add to this article?

**Comment by ari-gold** [comment]
my 2c

Change "Simply switch your connection method to HTTPS and your dev-yoursite.pantheon.io domain will work."
to
"If you're viewing your site at http://dev-yoursite.pantheon.io, simply switch your connection mode to HTTPS by visiting https://dev-yoursite.pantheon.io"

and move "For more information on managing redirection to HTTPS, see redirecting incoming requests." up" up to the first paragraph and change to "If you'd like to make sure that HTTPS is used anytime you visit a site, add logic to `settings.php` or `wp-config.php` to redirect all incoming requests to HTTPS."
