### ISSUE TITLE
Frozen site commit message "Commiting changes before freezing site.", Committing is spelled wrong.

### ISSUE THREAD

**Issue by thejimbirch** [pantheon-systems/documentation#3496]
Re: Not related to a doc, but I couldn't figure out where else to post.

## Issue Description
Looks like when a site is frozen, a commit is made.  In this commit, the word `Commiting` is spelled wrong.

## Suggested Resolution
Create an issue in the private repository which houses this code and update the spelling of `Committing`

**Comment by alexfornuto** [comment]
Thanks for letting us know @thejimbirch! I've PR'd the fix to the proper repository.
