### ISSUE TITLE
Consider adding note that sites can't be renamed after creation

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#3498]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority (Low‚ Medium‚ High):

## Suggested Resolution

**Comment by alexfornuto** [comment]
@slashzero This is documented [here](https://pantheon.io/docs/create-sites/#can-i-rename-my-pantheon-site-after-creation). We're opting not to also include it in Platform Considerations, as renaming sites is not a determining factor when deciding if Pantheon is a good fit for a project, which is the purpose of this doc.
