### ISSUE TITLE
The DNS page needs to be retested with all DNS providers for a non-www domain

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#350]
According to https://pantheon.io/docs/articles/sites/domains/ there is a way to have a non-www domain on Pantheon by using ALIAS/ANAME or Flattened CNAME provided by any of the following providers:

Alias Records (ALIAS/ANAME)

Route 53
DNSimple
DNS Made Easy
EasyDNS Flattened CNAME/Redirect
CloudFlare
ClouDNS
NameCheap
According to a client, Amazon Route 53 only allows you to use AWS hosts such as S3 and CloudFront and not external ones.
>However, after signing up for Route 53 near launch time, it does not appear that you can use non AWS host names in your Alias records. I can only use AWS hosts such as S3 and CloudFront.

Validate the above and modify documentation accordingly. 

Procedure for testing:
Spin up a Pantheon.io site, add a custom domain name, and then set up a CNAME  record on the DNS provider such that accessing the root domain resolved properly to the Pantheon.io site.

**Comment by nataliejeremy** [comment]
@timani @suzannealdrich Is this still relevant? If so can you provide a procedure for Alex J to test for each one?

**Comment by suzannealdrich** [comment]
The procedure would be to spin up a Pantheon.io site, add a custom domain name, and then set up a CNAME record record on the DNS provider such that accessing the root domain resolved properly to the Pantheon.io site.

**Comment by nataliejeremy** [comment]
@rachelwhitton or @atjuch Can either of you test this out and update the doc if the information is outdated or incorrect?

**Comment by rachelwhitton** [comment]
@natalie - to my knowledge, DNS information that currently exists in the docs are up to date with values needed to direct domains. 

As far as testing Route 53, here's what I found: 
> Amazon Route 53 effectively connects user requests to infrastructure running in AWS – such as Amazon EC2 instances, Elastic Load Balancing load balancers, or Amazon S3 buckets – and can also be used to route users to **infrastructure outside of AWS**.

I think the information reported may be out of date. At this time, Route 53 is not limited to AWS services. I created a test account and was able to add records to external destinations without issue.  


IMO we can mark this issue invalid.

**Comment by rachelwhitton** [comment]
Actually, I spoke too soon. The issue reported with Route 53 was regarding alias records specifically. Destinations are limited to the following: 
- **An alternate domain name for a CloudFront distribution**: Amazon Route 53 responds as if the query had asked for the CloudFront distribution by using the CloudFront domain name, such as d111111abcdef8.cloudfront.net.

- **An ELB load balancer**: Amazon Route 53 responds to each request with one or more IP addresses for the load balancer.

- **An Amazon S3 bucket that is configured as a static website**: Amazon Route 53 responds to each request with one IP address for the Amazon S3 bucket.

- **Another Amazon Route 53 resource record set in the same hosted zone**: Amazon Route 53 responds as if the query had asked for the resource record set that is referenced by the pointer.

If another destination is required for ANAME/Alias records, choosing another DNS host is recommended.
