### ISSUE TITLE
Clearing Caches for Drupal and WordPress Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3500]
Re: [Clearing Caches for Drupal and WordPress](https://pantheon.io/docs/clear-caches/)

Priority (Low):

## Issue Description:
Customer asks what to expect when clearing caches and provide a benchmark when to know something is wrong.

How long should it take for clearing caches to take effect? 
Is it measured in seconds, or minutes?
Is it ok to just keep on trying, or its better to hit the button at a certain interval? 
Does it take longer to clear cache for specific POPs?

## Suggested Resolution
Add a troubleshooting or FAQ section related to these questions.

**Comment by alexfornuto** [comment]
@eabquina we're closing this issue without action. We're unsure of how this is measured, and are not in a position to address these questions in the docs.

CC @ari-gold - Happy to re-open with additional guidance.
