### ISSUE TITLE
WordPress Site Networks: Promote qualifying plan to top of Doc

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3502]
Re: [WordPress Site Networks Introduction](https://pantheon.io/docs/guides/multisite/)

Priority (Low‚ Medium‚ High):
Low 

## Issue Description:
Qualifying plan(s) are mentioned at the _bottom_ of Doc rather than at the top. Were it at the top, it could inform customers initially of site expectations. 

## Suggested Resolution
Consider adding or promoting the information that "Running a WordPress Site Network requires a special configuration that is only available on **Elite** plans" at the top of the Doc.

**Comment by rachelwhitton** [comment]
Thanks for the issue @thomas-thackery, we'll work this issue by: 

- Adding `guidetoc: true` to the introduction page so the section is visible from the top (instead of restructuring the page)
