### ISSUE TITLE
Clearer retention policy for frozen sites

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#3504]
@pantheon-systems/cse
Priority: Low

## Issue Description:

Abandoned/Frozen sites blocking the use of namespaces.

## Suggested Resolution 

Clarify archive retention policy for frozen sites, see desk case 101741

**Comment by alexfornuto** [comment]
Thanks for the issue @newtoid! Here are the steps we'll take to resolve:

- Add an FAQ to [Creating Sites doc](https://pantheon.io/docs/create-sites/#frequently-asked-questions-faqs) to answer "What if my site name is already taken?" with "pick another name".

**Comment by newtoid** [comment]
sounds good to me @alexfornuto
