### ISSUE TITLE
Using Extensions That Assume Write Access Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3506]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access/)

Priority (Low):

## Issue Description:
A few customers decided to no longer use the symlinks, what is Pantheon advice on removing 

## Suggested Resolution
Add a section about how to remove in case no longer needed

**Comment by alexfornuto** [comment]
Neat idea! We'll add it under Troubleshooting.
