### ISSUE TITLE
Desk Doc on Issue

### ISSUE THREAD

**Issue by xq42** [pantheon-systems/documentation#3507]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High): Medium

## Issue Description: Standard "drush rsync" command fails when a site uses a nested doc root.

Note: This doesn't seem to affect many users, but the error messages produced don't really point to the cause of the problem so it is very difficult to diagnose unless you already know to look for it.

## Suggested Resolution

Ideally, modifying how the drush alias file is created to simply point to:

'%files' => 'files',

instead of:

'%files' => 'code/sites/default/files',

would likely be best.

Otherwise, a note in this doc:

https://pantheon.io/docs/drush/

(and possibly others?) acknowledging the issue with using a nested doc root and suggesting a manual change of the %files option to:

'%files' => 'code/web/sites/default/files',
or
'%files' => 'files',

I believe it is also recommended to clear the drush cache after updating the drush aliases file, which should likely also be noted.

**Comment by dustinleblanc** [comment]
There is an open PR on Titan for this here: https://github.com/pantheon-systems/titan-mt/pull/16211

**Comment by rachelwhitton** [comment]
Thanks for reporting @xq42 - we're deferring to BUGS-1478 for a product fix rather than a docs update. Can reconsider with additional input from eng on the bug card. Thanks!

**Comment by greg-1-anderson** [comment]
This bugfix has been deployed
