### ISSUE TITLE
File System FAQs Doc is Drupal Specific and has only one question.

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#352]
Doc: https://pantheon.io/docs/articles/sites/files/filesystem-faqs

This update should consider the following:

Do we want to move the doc to the `drupal` directory, or leave here in `sites/files`.
Can CSE's and TC Editors generate more questions that are relevant to the File System for both Drupal and WordPress.
If so, contribute to the existing branch:

**Comment by rachelwhitton** [comment]
New title already exists:
# Filesystem Writable Error
