### ISSUE TITLE
Testing Global CDN Caching Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#3520]
Re: [Testing Global CDN Caching](https://pantheon.io/docs/test-global-cdn-caching/)

Priority (Low‚ Medium‚ High): Med

The output of the main curl -I should also be updated to remove Surrogate-Key-Raw by defult

Also could document how to get the header:

View the Surrogate-Key-Raw header, used for debugging when using Pantheon Advanced Page Cache,  To receive this header when making a request, send the Pantheon-Debug: 1 header, like so:
```
 curl -IsH "Pantheon-Debug:1" https://example.com | grep key
```

**Comment by alexfornuto** [comment]
Thanks @ari-gold!
