### ISSUE TITLE
Domains and Redirects: Redirect to HTTPS for platform domains

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3521]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High):
Low 

## Issue Description:
"All platform domains are available over HTTPS. Redirecting to HTTPS during development and testing is a good best practice to ensure you are ready to go live with HTTPS," but doesn't provide a code snippet to implement. 

## Suggested Resolution
Include platform domain redirect code snippet.

**Comment by rachelwhitton** [comment]
Not sure when this was delivered or where, but the content is there under "Redirect to HTTPS" in the dropdown

**Comment by thomas-thackery** [comment]
I think some guiding language could be helpful something that directs customers that said redirect is implemented using the redirect scripts further down in the Doc.  

The button snap to the above is the *Redirect to HTTPS and the Primary Domain* section /docs/domains/#redirect-to-https-and-the-primary-domain. While there is a comment in the code  `// Redirect to HTTPS on every Pantheon environment.` the description paragraph for this section doesn't mention HTTPS for platform domains.

**Comment by alexfornuto** [comment]
Assigning to @thomas-thackery, who says he will make a PR with the change he wants to see.

![image](https://user-images.githubusercontent.com/2349184/43225900-f1ef1b78-901f-11e8-8aba-214457806743.png)
