### ISSUE TITLE
Run link checker and repair broken URLs

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#353]
Since the launch of Pantheon.io some links have been broken 
eg: https://pantheon.io/news/drush-aliases-available >> https://pantheon.io/blog/drush-aliases-available 

The above 404 was found in the currently live [FAQ](https://pantheon.io/docs/articles/frequently-asked-questions/).

**Comment by bmackinney** [comment]
Closed in #346
