### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update 

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/documentation#3533]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot/)

Priority: Medium

## Issue Description:

Using the one-click apply update button on the dashboard to apply updates for a site that has a nested docroot can definitely break a site. We mention "If you wish to stop using One-click Dashboard updates on a particular site...." in a call-out and show how to do that using Terminus.

## Suggested Resolution

I would like to suggest that we highlight the **need** to do this rather than offering it as an option.

For background on this, please see BUGS-1904

**Comment by alexfornuto** [comment]
Addressed in #3978
