### ISSUE TITLE
Apache Solr on Pantheon Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3537]
Re: [Apache Solr on Pantheon](https://pantheon.io/docs/solr/)

Priority (Low):

## Issue Description:
The customer wants to know how to measure index size in terms of MB

## Suggested Resolution
Comment if this is also a platform limitation that we cannot provide 
Or if its possible, provide steps

**Comment by alexfornuto** [comment]
Reached out to Engineering for an answer.

**Comment by alexfornuto** [comment]
Discussion continued in FEAT-551. @eabquina please add any additional requests for this information there.
