### ISSUE TITLE
Establish best practices for dealing with Let's Encrypt rate-limiting issues

### ISSUE THREAD

**Issue by obicke** [pantheon-systems/documentation#3539]
Re: https://pantheon.io/docs/https/#addressing-lets-encrypt-rate-limits
## Issue Description
Some primarily EDU client have mentioned facing "rate limiting" when trying to issue Let's Encrypt certificates. ref: https://letsencrypt.org/docs/rate-limits/

I believe that this occurs in cases where they are trying to generate certs for sites, not hosted on Pantheon, that share domains with sites that are on Pantheon. I can provide references to cases where clients have faced this issue, but to understand the underlying problem space, please refer to DTS, who has been involved with at least one of the instances.
 
## Suggested Resolution
Some solutions have bee proposed, but I believe may no longer be applicable:
- Requesting their own high-limit account with Let's Encrypt; But if I understand correctly, this may not help us, since if Pantheon+client together hit this cap, then we are just increasing the problem
- Applying for inclusion on the Public Suffix List: But the attempt to do so that I've followed appears as though it will be refused (more details can be provided internally).

Another solution proposed was to:
- Choose a different CA that supports ACME; For example, GlobalSign supports it. This would not be free though, so requires cost and procurement flexibility. Client could, however, switch to Let's Encrypt once/if one of the other solutions is in place. 

I believe that DTS is evaluating other possible solutions/scenarios.

**Comment by alexfornuto** [comment]
CC @davidstrauss
