### ISSUE TITLE
User in Charge Management

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3543]
[User in Charge management: Role-Based Permissions & Change Management](https://pantheon.io/docs/change-management/)

Priority (Low‚ Medium‚ High):
Low 

## Issue Description:
Add section on how to change the User in Charge

## Suggested Resolution
Add documentation how _User in Charge_ changes are made including
- [ ] Support can make the change if requested by an organization admin
- [x] How a next-in-line Team Member is promoted to User in Charge if removed

**Comment by rachelwhitton** [comment]
nice, thanks @thomas-thackery! +1

**Comment by alexfornuto** [comment]
@thomas-thackery Thanks for the issue! Do you know how the "next-in-line" team member is selected?

**Comment by alexfornuto** [comment]
Assigning to @thomas-thackery to define how "next-in-line" is determined.

**Comment by alexfornuto** [comment]
> How a next-in-line Team Member is promoted to User in Charge if removed

According to my testing, no one is promoted to UIC when one is removed.
