### ISSUE TITLE
April/May Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3546]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
## WordPress 4.9.5.1
Improve Pantheon customization to WordPress login form. For more information see https://github.com/pantheon-systems/WordPress/issues/155

**Comment by ari-gold** [comment]
### OCSP Stapling now Supported on Global CDN
OCSP stapling is an improved method for quickly and safely checking the validity of certificates for HTTPS. You can use [SSL Labs](https://www.ssllabs.com) (e.g. [https://www.ssllabs.com/ssltest/analyze.html?d=pantheon.io](https://www.ssllabs.com/ssltest/analyze.html?d=pantheon.io) and search for "stapling" to see it's enabled. OCSP responses are typically good for about 7 days, so a response will only get updated as its validity lifetime expiration time approaches.

**Comment by pantheon-upstream** [comment]
## Drupal 8.5.2 
Update to Drupal 8.5.2. For more information, see https://www.drupal.org/project/drupal/releases/8.5.2

**Comment by pantheon-upstream** [comment]
## Drupal 7.59 
Update to http://git.drupal.org/project/drupal.git 7.59.

**Comment by pantheon-upstream** [comment]
## Drupal 8.5.3 
Update to Drupal 8.5.3. For more information, see https://www.drupal.org/project/drupal/releases/8.5.3

**Comment by pantheon-upstream** [comment]
## Drupal 6.44 
Update to Drupal pressflow-6.44.125. For more information, see https://github.com/pressflow/6/releases/tag/pressflow-6.44.125.

**Comment by ari-gold** [comment]
Site Auditor (aka RavenCrawler) can now access platform domains like test-example.pantheonsite.io, so you can diagnose SEO errors without needing to add a custom domain.
