### ISSUE TITLE
Some anchor links are unreachable

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#355]
1. [x] Reduce font-size for toc content.
2. [x] Modify theme to a max-height for the TOC container
2. [x] Create scrollable container for TOC and test

**Comment by rachelwhitton** [comment]
@nataliejeremy @bmackinney can you weigh in on what standards you think should be set for H2s and H3s? Do we need a limit if the TOC is scrollable and not spilling into the footer? 

IMO we don't need to restrict the number of H2s and H3s if there's no overflow. 

What standard do we want to set for max characters?

**Comment by bmackinney** [comment]
We don't need to restrict if there's no overflow, correct. Max characters
will be similarly difficult to enforce. I think the styles is the only
important thing here. I'll adjust the issue description.

Brian MacKinney
Developer Training Manager | Pantheon
p 415-800-1957
brian@pantheon.io
www.linkedin.com/in/bmackinney
