### ISSUE TITLE
Considerations for Google Analytics and PANTHEON_STRIPPED Doc Update 

### ISSUE THREAD

**Issue by heydemo** [pantheon-systems/documentation#3561]
Re: [Considerations for Google Analytics and PANTHEON_STRIPPED](https://pantheon.io/docs/pantheon_stripped/)

Priority (High):

## Issue Description:

The code provided to remove tracking parameters from URLs:
```
$strip = array('/&?__.+?(&|$)$/', '/&?utm_.+?(&|$)$/');
$_SERVER['REQUEST_URI'] = preg_replace( $strip, '', $_SERVER['REQUEST_URI'] );
```

Breaks any URL with a double underscore. This is breaking panels admin for us because the following URL:
https://localhost/panels/ajax/editor/pane-css/panel_context%3Apage-homepage%3A%3Apage_homepage__panel%3A%3A%3A%3A/8580

**is truncated to:**
https://localhost/panels/ajax/editor/pane-css/panel_context%3Apage-homepage%3A%3Apage_homepage

see https://regex101.com/r/JiHVJU/1

## Suggested Resolution

It seems like the regular expressions should be changed to only match after a `?` or a `&` i.e:
```
$strip = array('/[&?]__.+?(&|$)$/', '/[&?]utm_.+?(&|$)$/');
+ $_SERVER['REQUEST_URI'] = preg_replace($strip, '', $_SERVER['REQUEST_URI']);
```

This only matches query params beginning with `utm_` or `__` but I believe that suffices

**Comment by alexfornuto** [comment]
Thanks for letting us know @heydemo!

**Comment by alexfornuto** [comment]
I'm following up internally with some SME's for more information.

**Comment by mikecwindmill** [comment]
I'm still running into this issue with a client site. We are trying to capture several `utm_` url parameters in Gravity Forms hidden fields for a landing page linked to an AdWords campaign. The URL param values seem to display correctly in the browser URL bar but the hidden field values all say "PANTHEON_STRIPPED". Is there a way to fix this? Is it possible to exclude certain pages from whatever caching is changing these values?
