### ISSUE TITLE
Caching: Advanced Topics Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3563]
Re: [Caching: Advanced Topics](https://pantheon.io/docs/caching-advanced-topics/)

Priority (Low):

## Issue Description:
We say that static assets or files are cached. But some applications build endpoints like .json or .xml and being considered as static files and thus cached as 366 days too.

## Suggested Resolution
manually-expiring-cache-for-static-assets-eg-css-js-pdfs-images

For such files, we recommend adding a query parameter string, to retrieve a new set, or refresh the version from the client. 
`.css?v=1.2`

One way is to also place a dynamic parameter so it always gets an uncached value. This sample shows a date value that increments +1 second.

`curl -v "https://example.com/example.json?"$(date +%s) > /dev/null`

Note: Not sure if this will have some implication or whatsoever

**Comment by rachelwhitton** [comment]
Closed #3651

**Comment by rachelwhitton** [comment]
Thanks for reporting @eabquina! much appreciated
