### ISSUE TITLE
Create a service level document explaining the resources a site has in each environment.

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#357]
User story:
As a User I want a service level document so I know what resources my site has in each environment.

Most of the information in this document used to be located on the [Pricing Page,](https://www-test.getpantheon.com/pricing) but it didn't account for the sandbox level. It will also describe CDE, dev, and test environment resources, and include a caveat for business and enterprise plans describing unwanted behaviors due to the number of app-servers being greater in live than in dev and test.

**Comment by rachelwhitton** [comment]
>Pantheon containers spin down after ~1 hour of idle time. LIVE environments on a paid plan will spin down after 12h of idle time. On receiving a web request, they are spun up, usually within 30 seconds. If you try to connect to the backend, you may experience an error. Load the home page, and you can connect.

Move the above content from [Scope of Support](https://pantheon.io/docs/articles/scope-of-support/) into new doc draft.

**Comment by rachelwhitton** [comment]
PR #654
