### ISSUE TITLE
Drupal Commerce on Drupal 8 Doc Update 

### ISSUE THREAD

**Issue by minutiae** [pantheon-systems/documentation#3583]
Re: [Drupal Commerce on Drupal 8](https://pantheon.io/docs/guides/drupal-8-commerce/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
When issuing the command

`terminus build:project:create pantheon-systems/example-drops-8-composer $SITENAME`

I get the following error:

> There are no commands defined in the "build:project" namespace.

**Comment by alexfornuto** [comment]
@minutiae have you installed the [Build Tools Plugin](https://pantheon.io/docs/guides/build-tools/) for Terminus?

**Comment by minutiae** [comment]
I have now and that fixed the issue, thanks.
