### ISSUE TITLE
Camayak Plugin for XMLRPC.php file

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3585]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority (Low):

## Issue Description:
When a customer installs the plugin "Camayak", it causes an error
```
HTTP/1.1 405 Method Not Allowed
 Allow: POST
```
## Suggested Resolution
Do not use the plugin, or provide more info why this is happening.
Consider workaround for use of Camayak

**Comment by alexfornuto** [comment]
@eabquina can you tell us why this is happening so we can provide that information? I feel like the suggested resolution is incomplete on this issue.

**Comment by alexfornuto** [comment]
@eabquina Is there a ticket or chat ID you can reference? Has this happened to more that one customer? Can you replicate?

**Comment by eabquina** [comment]
Adding the related Chat ID:  15833585960

@alexfornuto  I only have one sample for this one and can't replicate. It seems like i would need to have a "camayak" service subscription to do so. 
https://github.com/camayak/camayak-wordpress-plugin

I vote to skip this one for now. Thanks
