### ISSUE TITLE
Create docs for available logs files like the PHP slow log doc 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#359]
Story: As a Developer I want additional docs for available logs files like the PHP slow log doc so I have more information about the performance of my site

- [x] Create `/docs/articles/sites/logs.md` and move php slow to  `/logs/php-slow-log.md`
- [ ] Add all relevant logs articles and stuff like Timani's Drupalcon presentation to the directory.
- [x] Create a new doc for each of the different logs in `/logs`
 - [x] newrelic.log - Summarized in logs.md
 - [x] nginx-acces.log - See [Parsing nginx Access Logs with GoAccess](https://pantheon.io/docs/articles/sites/logs/nginx-access-log/)
 - [x] nginx-error.log - Summarized in logs.md
 - [x] php-error.log - Existing doc not in the logs dir - [PHP Errors and Exceptions](https://pantheon.io/docs/articles/sites/php-errors-and-exceptions/)
 - [x] php-fpm-error.log - See [PHP Slow log](https://pantheon.io/docs/articles/sites/logs/php-slow-log/#analyze-the-php-fpm-error-log)
 - [x] php-slow.log - See [PHP Slow Log](https://pantheon.io/docs/articles/sites/logs/php-slow-log/#analyze-the-php-slow-log)
 - [x] pyinotify.log - Summarized in logs.md
 - [x] watcher.log - Summarized in logs.md
 - [x] mysqld-slow-query.log - See [MySQL Slow Log](https://pantheon.io/docs/articles/sites/logs/mysql-slow-log/)

**Comment by rachelwhitton** [comment]
@timani can you create a draft for a doc from your Drupalcon LA presentation - Making your logs work for you: Drupal escalation and disaster recovery?

**Comment by timani** [comment]
@rachelwhitton there is this outline but let me know what format you need, like an overview or guide. I can grab the notes from the slides too perhaps?

https://events.drupal.org/losangeles2015/sessions/making-your-logs-work-you-drupal-escalation-and-disaster-recovery

**Comment by rachelwhitton** [comment]
@timani a full guide would be great! If you could organize a draft I can build it out. Thanks for the quick response!
