### ISSUE TITLE
Increase Visibility for Additional Redirect Scenarios

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3600]
Re: [Domains and Redirects](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
Users and CSE find it difficult to locate documentation for additional redirect scenarios, given that it's currently hidden within a dropdown panel

## Suggested Resolution
- Extract the content from the dropdown panel either 1) on this page or 2) in it's own separate doc 

Keep in mind that the only redirect we recommend implementing as part of the launch process is to redirect to HTTPS and a primary domain. All other scenarios are considered "optional" or "as needed" when it makes sense for the site. So they should be covered in a way that does not distract users while going live

**Comment by alexfornuto** [comment]
@rachelwhitton I mocked up my idea for a solution in #3601
