### ISSUE TITLE
SERVER_NAME and SERVER_PORT on Pantheon Doc Update 

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#3605]
Re: [SERVER_NAME and SERVER_PORT on Pantheon](https://pantheon.io/docs/server_name-and-server_port/)

Priority (Low‚ Medium‚ High):

## Issue Description:
First when implemented $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST']; in wp-config file visiting bare domain site redirects to Pantheon default URL:

Example:
visiting http://example.com it redirects to https://endpoint05ccd237.chios.panth.io

Also getting redirect loop when implemented with the redirect to https and primary domain:
https://pantheon.io/docs/domains/#redirect-to-https-and-the-primary-domain

**Comment by alexfornuto** [comment]
Not enough information to replicate. Marking as blocked until @umandalroald can give us more info on the circumstances around which the loop occurs.

**Comment by alexfornuto** [comment]
Per @umandalroald closing as CNR / Customer Code issue.
