### ISSUE TITLE
Enabling Solr with Drupal 7 Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3608]
Re: [Enabling Solr with Drupal 7](https://pantheon.io/docs/solr-drupal-7/)

Priority (Low):

## Issue Description:
Ticket: 103636
Customer cloned sites locally. Site includes set-up of Solr. 
How to configure the site to work with a local Solr installation alternative to the set-up

**Comment by alexfornuto** [comment]
@eabquina this is not a complete issue. There's no suggested resolution.

Moreover, we don't want to start documenting how to install third party tools on people's local computers.

For customers who want a local environment matching Pantheon, they can try Lando (although we don't officially recommend it in the docs) which has a [solr module](https://github.com/lando/lando/blob/master/docs/services/solr.md). Upcoming product work related to local development should also help alleviate this sort of concern for customers.
