### ISSUE TITLE
Enabling Solr with Drupal 7 Doc Update 

### ISSUE THREAD

**Issue by calmher** [pantheon-systems/documentation#3617]
Re: [Enabling Solr with Drupal 7](https://pantheon.io/docs/solr-drupal-7/)

Priority (Low‚ Medium‚ High):
Low 

## Issue Description:
Client was migrating his site over to us and has a pre-existing apachesolr config but it was configured for Solr 4.x and what we have on the platform is 3.x (see https://getpantheon.atlassian.net/browse/UNIPAN-16). 

From the client - "The error was that Pantheon_Apachesolr is not compatible with apachesolr module having "Commit changes to Memory" checkbox enabled on the localhost server as it is a 4.x feature. There are no instructions on Pantheon's site regarding this, and it seems that Pantheon's apachesolr module does not check for these pre-existing configurations. It probably should catch the exception when this checkbox is selected instead of white screening the site.

## Suggested Resolution
Perhaps mention the Solr version we have on Pantheon so clients can configure those changes appropriately. Attaching a screenshot on the apachesolr module setting where the options shouldn't be enabled.
![2018-04-26_12-31-07](https://user-images.githubusercontent.com/659097/39286066-70d03e0e-494e-11e8-8b2a-d530a1be492d.png)

**Comment by alexfornuto** [comment]
**Actions:**

 - Move Solr version information from FAQ page into a partial, and distribute it back into the FAQ and the three Solr installation docs.

 - Note incompatibility with the "Commit changes to memory." option in the D7 doc
 - Discover if the same warning is required for the D8 doc, and add it if so.
