### ISSUE TITLE
Update Bots and Indexing

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3619]
Re: [Bots and Indexing on Pantheon](https://pantheon.io/docs/bots-and-indexing/)

Priority: High

## Issue Description
 - Pending Engineering work will require updates to this doc.

## Suggested Resolution
 - Update doc based on engineering work resulting from FEAT-553

**Comment by alexfornuto** [comment]
Assigning to @ari-gold to clarify changes once enacted.

**Comment by ari-gold** [comment]
https://github.com/pantheon-systems/documentation/issues/3546#issuecomment-386138244
