### ISSUE TITLE
Getting the Client IP Address Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3639]
Re: [Getting the Client IP Address](https://pantheon.io/docs/client-ip/)

Priority (Low):

## Issue Description:

One customer shared that:

Cloudflare acts as a proxy so the ip address is coming from Cloudflare's network, not the user's.
I found a way to get around this by using $SERVER["HTTP_CF_CONNECTING_IP"] instead of $SERVER['REMOTEADDR'] for the field I created. However, this is really sort of a hack and it doesn't fix the issue with other logging and tracking stuff we might need. Cloudflare has a mod_cloudflare app that fixes this but needs to be installed on the server. 

## Suggested Resolution

Provide and share this as a workaround (HTTP_CF_CONNECTING_IP)

**Comment by alexfornuto** [comment]
This sounds like a new troubleshooting section for the doc referenced.
