### ISSUE TITLE
SSH Auth + Terminus

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3640]
Re: [Terminus Manual: Install](https://pantheon.io/docs/terminus/install/)

Priority (Low‚ Medium‚ High): low

## Issue Description:
The **Authentication** section does not document SSH Authentication used by commands like `remote:drush` and `remote:wp`

Inspired by [power users thread](https://pantheon-community.slack.com/archives/C57J1MUEM/p1524771906000570)

## Suggested Resolution
- Add an intro paragraph stating two authentication methods may be needed depending on usage
- Add a new H3 for the existing content, like **Machine Tokens**
- Add a new H3 for new content, like **SSH Keys**
- Document SSH authentication used for `remote:drush` and `remote:wp` - noting the same for plugins like `drupal` (Drupal Console) and `composer`, that instructs users to add an SSH key to their account to finish authentication steps. 
- Consider adding `terminustoc: true` to enable anchored headers

**Comment by alexfornuto** [comment]
@greg-1-anderson what do you think about a feature request for Terminus to have `drush` and `wp` commands auth with machine tokens? That way these commands behave like any other Terminus command would.
