### ISSUE TITLE
"Could not resolve XXX in the logs" needs to be documented to resolve DNS issues.

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#365]
We can add to the macro to point to an official doc vs debating in a ticket.

**Comment by nataliejeremy** [comment]
@ari-gold  @timani @suzannealdrich Anyone have info on this? Can you add the resolution?

**Comment by ari-gold** [comment]
Nope.

**Comment by bmackinney** [comment]
CSE: Was this resolved with #593 ?
