### ISSUE TITLE
May/June Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3653]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by ari-gold** [comment]
## PHP Updates: Upgrade to PHP 7.1 or 7.2 before December
PHP has been upgraded to [5.6.36](http://www.php.net/ChangeLog-5.php#5.6.36), [7.0.30](
http://www.php.net/ChangeLog-7.php#7.0.30), [7.1.17](http://www.php.net/ChangeLog-7.php#7.1.17) and [7.2.5](
http://www.php.net/ChangeLog-7.php#7.2.5) platform-wide. PHP 5.5 and 5.3 have reached end-of-life, and PHP 5.6 and 7.0 will reach EOL in December 2018 so [upgrade to PHP 7.1 or 7.2](https://pantheon.io/docs/php-versions/) as soon as possible.

**Comment by pantheon-upstream** [comment]
## WordPress 4.9.6
Update to WordPress 4.9.6. For more information, see https://wordpress.org/news/2018/05/wordpress-4-9-6-privacy-and-maintenance-release/

**Comment by ari-gold** [comment]
## Clone existing Pantheon sites with new Terminus plugin
For details see [cloning an existing Pantheon site](https://pantheon.io/docs/migrate/#how-do-i-clone-an-existing-pantheon-site).

(blocked by https://github.com/pantheon-systems/documentation/issues/3699)

**Comment by ari-gold** [comment]
#### PHP 7.2 MS SQL Support
The platform-wide build of PHP 7.2 now supports connecting to an external Microsoft SQL server via [sqlsrv functions](http://php.net/manual/en/ref.sqlsrv.php).
