### ISSUE TITLE
The Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#3658]
Re: [The Site Dashboard](https://pantheon.io/docs/sites/)

Priority (Medium-High):

## Issue Description:
Should take into account new Metrics tab. 

## Suggested Resolution
* Replace screenshots with versions showing current sidebar with 'metrics'
* Add section to cover 'metrics' tab

**Comment by alexfornuto** [comment]
@EdwardAngert Consider this as part of the larger site audit being planned.
