### ISSUE TITLE
Fix Broken Links in WordPress Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3669]
Re: [Fix Broken Links in WordPress](https://pantheon.io/docs/wordpress-broken-links/)

Priority (Low):

## Issue Description:
Installing the plugin breaks a site

"But please change this blog post to recommend another plugin - https://pantheon.io/docs/wordpress-broken-links/
That plugin seems to crash the site when trying to scan for links.
Just a heads up. Don't want other people running into the same problem."

**Comment by eabquina** [comment]
Chat ID: 16254230293

**Comment by alexfornuto** [comment]
@eabquina is this the only instance you've seen where the site crashed from this plugin? Do we know if there was any custom code on this site that caused it? Have you tested the plugin yourself to confirm this behavior?

**Comment by eabquina** [comment]
@alexfornuto Tried to replicate and can't prove it has issues with the current version. Deferring this one for now.
