### ISSUE TITLE
Migrate to Pantheon: WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3675]
Re: [Migrate to Pantheon: WordPress Site Networks](https://pantheon.io/docs/migrate-wordpress-site-networks/)

Priority (Low‚ Medium‚ High):

## Issue Description:

Customers and Pantheon staff easily miss that a WP multisite needs to be purchased through sales and specifically set up by Pantheon staff as a WP multisite, before importing site code and database.

## Suggested Resolution
Add relevant parts of the below, to the top of this doc:
https://pantheon.io/docs/guides/multisite/#supported-use-cases

## Ticket reference
104139

**Comment by alexfornuto** [comment]
Addressed by #3968
