### ISSUE TITLE
WordPress and Drupal Core Updates Doc Update -- Drupal Status Manager still thinks updates are available

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3691]
Re: [WordPress and Drupal Core Updates](https://pantheon.io/docs/core-updates/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Applied the core updates successfully but Drupal Update Manager still thinks updates are available.

I often see this if the Drupal.org packaging script info was added to the core module's info file. 
Ex. 

```
Information added by Drupal.org packaging script on 2017-02-01
version = "7.54"
project = "drupal"
datestamp = "1485986921"

```
As per -https://pantheon.io/blog/packaging-info-and-updating-core-git, this happens if you unpack a tarball from drupal.org. Drupal Update Manager checks .info file data when trying to determine its version. If the version specified is older, Drupal update manager will display "updates available". This is confusing. Customers will think they have not applied the core updates successfully.

Is this still working and safe to share to the customer?  -https://gist.github.com/joshkoenig/2588420.  
The script will strip drupal.org packaging data from core .info files. The blog was written 6 years ago. 

## Suggested Resolution
Identify the best way to resolve this issue and add this info to our Troubleshooting section.

**Comment by ttrowell** [comment]
@joshkoenig Is this a script we could put in the docs for troubleshooting/resolution? https://gist.github.com/joshkoenig/2588420

**Comment by alexfornuto** [comment]
@ttrowell @rubelyn how would a customer run this script on the platform?

**Comment by alexfornuto** [comment]
Closing due to lack of input.
