### ISSUE TITLE
Using Terminus to Create and Update Drupal Sites on Pantheon Doc Update 

### ISSUE THREAD

**Issue by calmher** [pantheon-systems/documentation#3692]
Re: [Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs/guides/terminus-drupal-site-management/)

Priority: Medium

## Issue Description:
It looks like from the [Update the Code](https://pantheon.io/docs/guides/terminus-drupal-site-management/#update-the-code) portion, the command `terminus drush <site>.<env> -- site-install` is creating the settings.php file. This doesn't seem to work anymore and instead getting this error: 

`exception 'Drush\Sql\SqlException' with message 'Unable to find a   
matching SQL Class. Drush cannot find your database connection
details.' in /opt/pantheon/drush8/commands/sql/sql.drush.inc:545`

## Suggested Resolution
Copying default.settings.php to settings.php seems to resolve this issue prior to running that command. But is this the intended resolution? 

I'm not sure if this is a Terminus error or a Doc issue, in which case I have also created an issue on the Terminus issue queue about this - https://github.com/pantheon-systems/terminus/issues/1855

**Comment by alexfornuto** [comment]
@greg-1-anderson is looking into this, and updating the Terminus issue.

**Comment by alexfornuto** [comment]
Update: Still waiting on updates to the [Terminus issue](https://github.com/pantheon-systems/terminus/issues/1855).

**Comment by greg-1-anderson** [comment]
See https://github.com/pantheon-systems/terminus/issues/1855#issuecomment-442632189
