### ISSUE TITLE
Add a button to get to the full search result page

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3694]
Re: <Add Doc title and/or link>

Priority (Low‚ Medium‚ High): 

## Issue Description
Currently the search results come up in a dropdown on right hand side, when typing in search bar. Which is great for most things, but not when needing to open lots of docs in tabs to see if this is where the needed info might be.

## Suggested Resolution
Could we add a search button that will go to the full search page for a query, like this:
https://pantheon.io/docs/search/?addsearch=launch%20checks

**Comment by alexfornuto** [comment]
Closing as  I don't think I can add this functionality to the drop-down.
