### ISSUE TITLE
Document Drupal "not fully protected" htaccess

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3695]
## Internal reference
104048

## Issue
Drupal status report which is part of Pantheon Launch check on Dashboard, will report:
`Temporary files directory | Error | Not fully protected` with a red error background, if there is no htaccess file there. 

This is a false negative when not using Apache. Pantheon uses Nginx which does not read the htaccess file and the directory is perfectly secure. The equivalent content of the htaccess file is in Nginx platform wide config file.

## DO issue:
https://www.drupal.org/project/drupal/issues/2141065
This is created in 2013 and needs both D8 implementation + backport to D7. It could be a while before fixed..

## Suggestion
This would be great to document as it is naturally a difficult explanation, especially since the error warning is on Pantheon Dashboard, as well as Drupal admin status page.

**Comment by slashzero** [comment]
Perhaps this could go in the module/functions known issues doc?

**Comment by alexfornuto** [comment]
Resolved by #3896
