### ISSUE TITLE
Add Composer directions to "Using SimpleSAMLphp with Shibboleth SSO"

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#3696]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
The SimpleSAML Auth module we recommend for Drupal now recommends using Composer for adding the SimpleSAMLphp library to D8 sites: https://cgit.drupalcode.org/simplesamlphp_auth/tree/README.md. 

## Suggested Resolution
Add a section to the existing page about how to install/configure with Composer.

**Comment by alexfornuto** [comment]
The linked README instructs using composer manager, a D7 module. I attempted to install simplesamplephp and simplesaml_auth on D8, using Composer for the former, and ended up with a broken site.

I'm going to mark this as `help wanted`, as the existing documentation and instructions for the library / module do not cover what's needed for this installation.
