### ISSUE TITLE
Clone existing Pantheon Site with Terminus Plugin

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#3699]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate/)

Priority (Low‚ Medium‚ High): High

## Issue Description:

"How do I clone an existing Pantheon site?" section  can be improved

## Suggested Resolution

- Include instructions on how to use new @ataylorme  terminus plugin to clone a site
- Recommend when you'd use this method vs WP Plugin
- Remove instructions to use terminus drush, if appropriate

**Comment by rachelwhitton** [comment]
Closed by #3701
