### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update 

### ISSUE THREAD

**Issue by calmher** [pantheon-systems/documentation#3718]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis/)

Priority (Low‚ Medium‚ High):
Low

## Issue Description:
This is the page that the Status page is linking to when Redis is suggested to be installed. For users with a Basic plan, the table formatting can be missed. 

## Suggested Resolution
Is it possible to highlight the Basic plan and note that it isn't available? Or a red font for *NOT AVAILABLE* for it? 

* Also created a feature request to have a better way in the Status Page to show Redis not being available on Basic plans (https://getpantheon.atlassian.net/browse/FEAT-566)

**Comment by alexfornuto** [comment]
@calmher does this address your concerns?

![image](https://user-images.githubusercontent.com/2349184/42772416-fd3762b0-88ef-11e8-8b9d-c7d8f4f4a911.png)

CC @rachelwhitton @kimby77 how does this ✗ grab you?

**Comment by kimby77** [comment]
I suggest larger characters and color coding so that this is more skimmable:

![image](https://user-images.githubusercontent.com/19398001/42775441-30a8b66e-88e9-11e8-970c-9b15502b3b81.png)

**Comment by kimby77** [comment]
To simplify, you could also remove sandbox since it's not a "plan" from a customer point of view (you don't pay for it), and the reference in the paragraph above is probably enough.

**Comment by alexfornuto** [comment]
@kimby77 Color support isn't available in Markdown. I can add it with a `<span>` tag, which adds noise in the source, but looks like your mockup:

![image](https://user-images.githubusercontent.com/2349184/42960405-4f15d87e-8b51-11e8-8dc3-49aa66bb3c91.png)

Regarding Sandbox, while it may not be a "plan", customers can still have Sandboxed sites, and they will have access to Redis.  I feel like that should be documented.

**Comment by alexfornuto** [comment]
P.S. I also replaced ✗ with ❌:

![image](https://user-images.githubusercontent.com/2349184/42960506-a45c84ea-8b51-11e8-9135-fe29915d9bb1.png)

**Comment by kimby77** [comment]
The X is better - ideally the checkmark uses a more obvious checkmark character too, because right now at such a small scale it's hard to see the notch, and it looks like a diagonal line at first glance.

**Comment by alexfornuto** [comment]
@kimby77 please clarify:

1) Are you saying the new symbol is better, or a literal capital X letter?

2)
> ideally the checkmark uses a more obvious checkmark character too

Is there another Unicode check mark I should substitute?

**Comment by kimby77** [comment]
I am agreeing with you that the latest version of the X is better.

I used a glyphicon in my example.  Font awesome probably has an icon for this two.  If you use any icon fonts or svg systems, I would look at those.

**Comment by alexfornuto** [comment]
![image](https://user-images.githubusercontent.com/2349184/42970553-3370fb4e-8b6f-11e8-86b4-7d98d24d18be.png)

@kimby77 in the example above, the first check is a FontAwesome font, the second is the unicode symbol for heavy check mark (✔), and the third is the original unicode check mark I was using (✓).

In the interest of readable markdown files, I'd like to go with the unicode heavy check mark.
