### ISSUE TITLE
Billing in the Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3721]
Re: [Billing in the Site Dashboard](https://pantheon.io/docs/site-billing/#transfer-ownership-and-billing-for-this-site)

Priority: Low

## Issue Description:
**Re: Number 2. "Click Transfer ownership and billing for this site."**

If a card is already added, then the UI states: "Transfer ownership and billing for this site."
If a card is NOT already added, then the UI states: "Invite a business owner to pay for this site"
Since this section is talking about "the most common way agencies handle billing", shouldn't Number 2 say "Invite a business owner to pay for this site" instead of "Transfer ownership and billing for this site" as an agency would not add their own credit card, but would rather invite a client to do so.

**Re: Number 4. "Ask the new site owner to add your agency as a Supporting Organization so you can continue the going live procedure on their behalf."**

Number 4 only applies if when the site was created, it was **not** associated with an organization.
In other words, if a site was associated with an organization at the time it was created, then the new site owner will not need to add your agency as a Supporting Organization as it will already be associated.

## Suggested Resolution for Number 2
It may be best to separate the two scenarios into separate sections:
One section re: Transferring ownership and billing (_which assumes the site is already being billed to a card_)
One section re: Inviting ownership and payment (_which assume the site is not currently being billed to a card_), as in the case for agencies building sites for clients.

## Suggested Resolution for Number 4
**Change this**: Ask the new site owner to add your agency as a Supporting Organization so you can continue the going live procedure on their behalf.
**To this**: If the site is not already associated with your agency, ask the new site owner to add your agency as a Supporting Organization so you can continue the going live procedure on their behalf.

thanks for considering,

**Comment by cityofoaksdesign** [comment]
Any changes would also effect: https://pantheon.io/docs/guides/launch/plans/

**Comment by cityofoaksdesign** [comment]
Just noticed that the numbered list instructions here: https://pantheon.io/docs/site-plan/#enter-billing-information (Send a Request tab) is different from the instructions here:
https://pantheon.io/docs/guides/launch/plans/
https://pantheon.io/docs/site-billing/#transfer-ownership-and-billing-for-this-site

**Comment by alexfornuto** [comment]
Gonna go with the resolution suggested for # 4. For # 2 We'll consolidate into one sentence that includes both possible phrasings from the product.
