### ISSUE TITLE
June/July Changelog Candidates

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3727]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
## Drupal 8.5.4 
Update to Drupal 8.5.4. For more information, see https://www.drupal.org/project/drupal/releases/8.5.4

**Comment by rachelwhitton** [comment]
### Terminus 1.8.1
If you haven’t updated Terminus recently, check out the [Terminus Changelog](https://pantheon.io/docs/terminus/updates/#changelog) to see what’s new and update to the [current release](https://pantheon.io/docs/terminus/updates/#update-to-the-current-release).

**Comment by ari-gold** [comment]
More crawlers can now access platform domains, like test-example.pantheonsite.io, to support pre-release SEO testing. Details: https://github.com/pantheon-systems/documentation/pull/3827

**Comment by alexfornuto** [comment]
Add new items to #3850
