### ISSUE TITLE
Document ways to access an account in case a user leaves the company

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#373]
For scenarios involving access/ownership after the current owner abandons the project leaves an agency: 

Best recommendations to regain access:

>Unfortunately that employee just left the company and did not leave us any information for the website.

In the case you know the email address of the employee, we recommend using the forgot password and working with the email administrator so you can use the reset link to gain access.

https://dashboard.pantheon.io/reset-password

Once there you can update the email address to an existing employee or department.

>We don’t know how to log into it, passwords, ANYTHING. Please help.

You can notified any other existing team members that there is a new person who needs access to the account. If anyone is available, they should contact you directly and they can confirm who you are and give you to the access to that site’s dashboard:

https://pantheon.io/docs/articles/sites/team-management/

If you go through this route, we recommend you setup your Pantheon account first so you can skip this during the invitation process.

Once you have access you can follow these directions and enter your credit card on the site and that will make your account the owner.

https://pantheon.io/docs/articles/sites/settings/add-a-credit-card-to-a-site/

submitted by @timani

**Comment by rachelwhitton** [comment]
@suzannealdrich commented:
I think that the account verification page should mention that ownership is important. Just as you should own your own domain in your own name with a permanently reachable email, you should own your site in your own name with a permanently reachable email. We should make it clear, right off the bat, that Pantheon will NEVER transfer ownership of a site from one owner to another, and this is a self-service option.

**Comment by rachelwhitton** [comment]
we are getting more account verification questions.

In most cases the requests are probably genuine but we can NOT validate who anyone is and should NOT try. Churn happens in orgs but if the request is legit it is possible for them to work this out internally and validate or take control themselves.

--submitted by @timani
