### ISSUE TITLE
Create comprehensive SSO docs

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#374]
Story: 
As a user I want more comprehensive SSO docs so that i can SSO like a boss, it's not easy.

See attached ppt: 
http://2013.badcamp.net/sessions/shibboleth-sso-drupal
Document IdP initiated SSO - possible or not possible? Currently the configuration requirements are unknown but some users have accomplished something similar. We have not received information on exact steps taken to do so.

**Comment by nataliejeremy** [comment]
@ari Do you think these docs take care of this issue? 
https://pantheon.io/docs/articles/organizations/saml-for-orgs/

https://getpantheon.atlassian.net/wiki/display/VULCAN/Technique:+Enabling+SAML+SSO+For+Orgs

**Comment by ari-gold** [comment]
Yes, I think so, for now. We can add to them as we help more customers set up SAML with other IdPs.
