### ISSUE TITLE
ESI Edge Side Includes Documentation

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3741]
Re: ESI or Edge Side Includes

Priority (Low): 

## Issue Description
ESI or Edge Side Includes is something we published that is supported. The documentation page created a sample PHP page to implement this but did not specifcy Drupal or WordPress instructions

https://pantheon.io/blog/esi-support

## Suggested Resolution
Review blog post and see if there are any changes that is worth noting for Drupal and WordPress specific entry

http://live-varnish-esi-examples.pantheonsite.io/

**Comment by alexfornuto** [comment]
@eabquina Are you suggesting a new doc covering ESI, or do you have in mind an existing doc to add this information to?

**Comment by eabquina** [comment]
@alexfornuto It turns out, the blog might be outdated as this was not tested yet with Global CDN. There is BUGS-1512 being tracked but of low priority.

**Comment by alexfornuto** [comment]
Closing, as
 - BUGS-1512 is marked as done
 - The referenced blog post (which wasn't even part of the docs site) has been removed.
