### ISSUE TITLE
Pantheon Organizations FAQs Doc Update 

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3745]
Re: [Pantheon Organizations FAQs](https://pantheon.io/docs/organization-faq/#as-an-agency-how-many-sandbox-sites-do-members-of-an-organization-receive)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:

> "Each member of an organization receives 10 Sandbox sites."

From my testing, it appears as though each additional member of an organization only receives 3 Sandbox sites.

Steps to reproduce:
1) Log in and navigate to the organization dashboard
3) Add a user with any role (I selected Administrator)
4) Log out of the dashboard
5) Click the link in the e-mail to create a Pantheon account and join the organization
6) Create the new account and log in
7) Start a new project and choose an organization for the site
8) Deploy Drupal 7
9) Navigate to dashboard and the UI says: "You can create 2 more sandbox sites."

## Suggested Resolution
If each member of an organization is suppose to receive 10 Sandbox sites, then the technical team will need to look into this.
If each member of an organization is only suppose to receive 3 Sandbox sites, then the doc page should be updated accordingly.

Also, I re-produced the above steps twice, and each time that I did I was given '1' additional Sandbox site in my account. In other words, I started off with the ability to create 21 more sandbox sites. I went through the above steps the first time and then was given the ability to create 22 more sandbox sites. I went through the above steps a 2nd time and then was given the ability to create 23 more sandbox sites. Seems like a platform bug, but I'm not 100% sure.

**Comment by cityofoaksdesign** [comment]
Just curious if this issue has been looked at. It may also need a 'product' label.
thanks,

**Comment by alexfornuto** [comment]
@cityofoaksdesign sorry about the delay! Assigning to @EdwardAngert who's working to update all the docs changing as part of the latest product releases.

**Comment by EdwardAngert** [comment]
thanks for pointing this out @cityofoaksdesign! I did some testing of it as well and am making some changes to the documentation in the next week or so.

**Comment by alexfornuto** [comment]
Work to resolve #3743 in the same PR.

**Comment by EdwardAngert** [comment]
sorry about the delay with this one, @cityofoaksdesign - this actually turns out to be a bug on the dashboard that we're going to work on (internally: BUGS-2550) to have the Dashboard accurately reflect the number of sandboxes remaining.

There's nothing to change in the documentation just yet, so I'm going to close this issue and revisit the docs when the bug is fixed.

Thanks for spotting and reporting!
