### ISSUE TITLE
Organizations Roles and Permissions

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3747]
Re:
1) Organization Dashboard > People > Add User > View user roles and their permissions
2) https://pantheon.io/docs/change-management/#organizations-roles-and-permissions

Priority (Low‚ Medium‚ High): Low

## Issue Description
EIther the table found in Organizations Dashboard > 'People' tab > 'Add User' button > 'View user roles and their permissions' should be updated to include the 'Manage a site's plan' permission per https://pantheon.io/docs/change-management/#organizations-roles-and-permissions, or that doc page should be updated to remove the 'Manage a site's plan' permission.

You might also consider adding the 'Clone Database and Files' permission everywhere this table is listed.

Additionally, in my Organization Dashboard the 'Unprivileged' role is displayed in the table, but I am unable to add a user to my organization with an Unprivileged role.

![capture1](https://user-images.githubusercontent.com/13283316/40931937-d57650a8-67fa-11e8-975a-53c8d01da222.PNG)

![capture](https://user-images.githubusercontent.com/13283316/40931874-a7900df0-67fa-11e8-91fe-50ecf448d872.PNG)

## Suggested Resolution

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign! This is an issue with the product, not the documentation, and is being tracked internally.

Internal ref: `BUGS-2212`

**Comment by alexfornuto** [comment]
@cityofoaksdesign FYI The table in the org dashboard has been updated. On the docs, the tooptip for "Unprivileged"  explains that it's for certain org types only.
