### ISSUE TITLE
Terminus plugin developer docs

### ISSUE THREAD

**Issue by twfahey1** [pantheon-systems/documentation#3750]
### Feature request
I recently was getting into writing a custom Terminus plugin. It would be cool to have a reference to some of the available TerminusCommand methods that would help to provide common functionality for a plugin command without having to go through existing plugin codebases and trying to grok those. Here's an example of what I was envisioning (perhaps in a similar fashion to the [Terminus commands documentation table](https://pantheon.io/docs/terminus/commands/):

| Command | Description  |
|---|---|
| `$this->log()->warning('Some warning message')` | This will display a warning message to the user.|
| `$this->confirm("Are you sure you want to continue?")` | This will prompt the user to confirm the operation.
| `$this->getUser()->dashboardUrl()` | This returns the URL for the currently logged in user dashboard.
| `$this->io()->writeln('Hello world')` | Write a line of text to the CLI.

I can imagine also having examples of common operations such as prompting user for a choice:

```
use Symfony\Component\Console\Question\ChoiceQuestion;

/**
* @command hello-world:ask-question
*/
public function askUserQuestion() {
     $question = new ChoiceQuestion(
          'Please select your version of Drupal',
          array('Drupal 7', 'Drupal 8'),
          0
    );
    $drupal_version = $this->io()->askQuestion($question);
    switch ($drupal_version) {
          case 'Drupal 7':
....
```

**Comment by alexfornuto** [comment]
CC @sehamilton @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Much could be written about this. We could also link to other resources such as RoboPHP, various Consolidation component documentation, and the Symfony documentation.

**Comment by alexfornuto** [comment]
Tracking this internally as FEAT-678. We'll re-open the issue when we have something from the Terminus team to work on.

@twfahey1 Thanks for the issue, and for contributing to our docs!
