### ISSUE TITLE
Platform and Custom Domains Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3769]
Re: [Platform and Custom Domains](https://pantheon.io/docs/domains/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Increase discoverability of provider specific DNS docs, like https://pantheon.io/docs/google/

Reconsider our use of drop down panel and check the search index for keywords per provider

**Comment by alexfornuto** [comment]
Example of the drop down panel can be found [here](https://pantheon.io/docs/guides/launch/configure-dns/)
