### ISSUE TITLE
Launch Essentials Doc Update 

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#3773]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/configure-dns/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Needs a note about leaving the challenge upload in place so that if the DNS is not updated within the 7 day window, and the cert has to be re-triggered, the challenge is still there to validate against.

Why? Edu client IT staff had to remove the challenge file when they did not launch when expected.  Then, when they needed to re-provision, they had to go through getting them to upload it again.

## Suggested Resolution

**Comment by alexfornuto** [comment]
I think we should add the note to [this page[(https://pantheon.io/docs/guides/launch/domains/) which explicitly talks about the challenge file.
