### ISSUE TITLE
Create clear and accurate instructions for creating an ssh tunnel into my database

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#378]
Story: As a developer using pantheon I want clear and accurate instructions for creating an ssh tunnel into my database so I don't have to use trial and error to figure it out.

https://pantheon.io/docs/articles/local/ssh-tunnels-for-secure-connections-to-pantheon-services/  is outdated and confusing.

**Comment by rachelwhitton** [comment]
I took at shot at testing the existing commands and received the following error: 
```
$ mysql -u pantheon -h 127.0.0.1 -p -P 21517 pantheon
Enter password:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

**Comment by rachelwhitton** [comment]
@erik-pantheon do you think there's anything in the current doc about manually creating and destroying a tunnel we should preserve? Or are the commands in the connection info on the environment enough? I'm thinking we can cut out the manual instructions and only direct customers to the connection info in dashboard.

**Comment by rachelwhitton** [comment]
PR #651 opened, further discussion should happen there.
