### ISSUE TITLE
WP_DEBUG_LOG will only work if the environment is on SFTP mode

### ISSUE THREAD

**Issue by geraldvillorente** [pantheon-systems/documentation#3781]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/#how-can-i-write-logic-based-on-the-pantheon-server-environment)

Priority:

## Issue Description:

This particular snippet will only work on dev environment when in SFTP mode.

```
// All Pantheon Environments.
if (defined('PANTHEON_ENVIRONMENT')) {
  //Wordpress debug settings in development environments.
  if (!in_array(PANTHEON_ENVIRONMENT, array('test', 'live'))) {
    // Debugging enabled.
    if (!defined( 'WP_DEBUG' )) {
    define( 'WP_DEBUG', true );
    }
    // Stored in wp-content/debug.log
    define( 'WP_DEBUG_LOG', true ); 
    // Display the log in the browser.
    define( 'WP_DEBUG_DISPLAY', true );
  }
  // Wordpress debug settings in live environment.
  else {
    // Debugging disabled.
    ini_set('log_errors','On');
    ini_set('display_errors','Off');
    ini_set('error_reporting', E_ALL );
    define('WP_DEBUG', false);
    define('WP_DEBUG_LOG', true);
    define('WP_DEBUG_DISPLAY', false);
  }
}
```

The default location of `debug.log` is `wp-content/` which is not writable when they put the environment in Git mode. 

## Suggested Resolution

In order to make make the `WP_DEBUG_LOG` to work even on Git mode, you need to create a plugin and place it in `code/wp-content/mu-plugins`.

* Create a file called `custom-debug-log-path.php` or whatever name you like in `code/wp-content/mu-plugins`.
* Place the below code in the file you created above.

```
<?php
/**
 * Plugin Name: Custom Debug Log Path
 */

if (defined('PANTHEON_ENVIRONMENT')) {
    // Wordpress debug settings in development and test environments.
    if (!in_array(PANTHEON_ENVIRONMENT, array('test', 'live'))) {
        define( 'WP_LOGS_DIR', sprintf( '/srv/bindings/%s/logs', PANTHEON_BINDING ) );
        // Override the default debug.log path as it is not going to work this in Git mode.
        if ( defined( 'PANTHEON_BINDING' ) ) {
            // Set the logs path. You can set the path to /srv/bindings/%s/code/wp-content/uploads which is also writable
            // all the time regardless of the connection mode. However, this is not a recommend way for security reason.
            define( 'WP_LOGS_DIR', sprintf( '/srv/bindings/%s/logs', PANTHEON_BINDING ) );
            ini_set( 'error_log', WP_LOGS_DIR . '/debug.log' );
        }
    }
}
```

**Comment by alexfornuto** [comment]
I think a plugin is a larger solution that is required here. Since this issue was opened, #4070 added a snippet further down in the page explaining how to redirect the debug logfile to a writable location.

I propose as a solution to this, we include [the snippet](https://pantheon.io/docs/wp-config-php/#how-do-i-change-the-default-debuglog-location) in the code block referenced in this issue so that it defaults to logging in the filesystem. We could optionally include a note letting the reader know we've overridden the default location.

@geraldvillorente Does this solution work for you?

**Comment by alexfornuto** [comment]
+1 From @geraldvillorente over slack.
