### ISSUE TITLE
Managing Site Plan Changes and Chargeback for EDU+ Sites Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#3792]
Re: [Managing Site Plan Changes and Chargeback for EDU+ Sites](https://pantheon.io/docs/managing-edu-plus/)

Priority: Medium

## Issue Description:
Outdated screenshots and possible stale content wrt to managing plans
## Suggested Resolution
Align with [site plan](https://pantheon.io/docs/site-plan/)

**Comment by alexfornuto** [comment]
Soliciting input form product.
