### ISSUE TITLE
MySQL Slow Log Doc Update 

### ISSUE THREAD

**Issue by geraldvillorente** [pantheon-systems/documentation#3800]
Re: [MySQL Slow Log](https://pantheon.io/docs/mysql-slow-log/)

Priority: Low

## Issue Description:

From our documentations:
https://pantheon.io/docs/logs/#database-log-files
https://pantheon.io/docs/mysql-slow-log/#download-the-mysql-slow-log-via-sftp

## Suggested Resolution

We need to explicitly mention in the docs that customers need to also replace the SFTP username of the database username. Prefix the server type in the username. As per Jesse, the SFTP username from the dashboard will only work on the app server. If the SFTP username for example is `test.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` just prefix the server type `dbserver`. It should be like this `dbserver.test.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.

Please also see the discussion in Slack for more information:
https://pantheon.slack.com/archives/C03SRV7HB/p1529402206000469
https://pantheon.slack.com/archives/C03SRV7HB/p1529402237000350
https://pantheon.slack.com/archives/C03SRV7HB/p1529402195000487

**Comment by alexfornuto** [comment]
So... I'm not understanding what the issue here is.  First off, the username stays the same. The only thing different in the SFTP connection string is that `appserver` is replaced with `dbserver`.  This is explicitly stated in the linked doc:

![image](https://user-images.githubusercontent.com/2349184/50495329-09099480-09ee-11e9-8821-c31ef1007a13.png)

@geraldvillorente what exactly are you saying needs to be changed in the documentation?

**Comment by alexfornuto** [comment]
Pinged @geraldvillorente in Slack to look at this issue.

**Comment by geraldvillorente** [comment]
@alexfornuto This doc issue started when a customer reported that they are not able to SFTP to the DB server. This seems to be fixed by engineering now but before some DB servers need to have an environment type prefix in the username to be able to access the DB. As per @spheromak the correct way should be `type.env.siteID@dbserver` from these threads - https://pantheon.slack.com/archives/C03SRV7HB/p1529402291000337
https://pantheon.slack.com/archives/C03SRV7HB/p1529402195000487
https://pantheon.slack.com/archives/C03SRV7HB/p1529402336000253

I am not able to replicate the issue now on several sites without `type` in the username though. So not sure if this is still valid.

**Comment by carl-alberto** [comment]
@geraldvillorente @alexfornuto I was able to confirm that this part of the doc `Edit and execute the command by replacing appserver with dbserver` should work and it seems that this issue/bug outlined initially is not true anymore and this issue can be now be closed
