### ISSUE TITLE
MIME Types Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3801]
Re: [MIME Types](https://pantheon.io/docs/mime-types/)

Priority (Low):

## Issue Description:
ChatID: 17068671358
Customer adds a custom mime-type un-listed in the IANA Media Type list, and wants to follow the workaround stated in the docs section

## Suggested Resolution
Provide example code snippet on how to achieve this

**Comment by alexfornuto** [comment]
@eabquina Do you know how to set up such a script? If not, who's the SME to reach out to?

**Comment by alexfornuto** [comment]
Reached out to @greg-1-anderson and @stevector as possible SMEs.

**Comment by alexfornuto** [comment]
Added as a Docs challenge Candidate to test and provide technical review to the associated PR.
