### ISSUE TITLE
Add troubleshooting help for "SSL connection error: unknown error number"

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#3802]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access/)

Priority (Low‚ Medium‚ High): High

## Issue Description:
When connecting to a MySQL server, you may encounter this error — "SSL connection error: unknown error number". This may be due to TLS versions or local CA certs.

## Suggested Resolution
- Add links or instructions for how to update your local cert.
- Guide for doing this w/ MySQL Workbench: https://dev.mysql.com/doc/workbench/en/wb-mysql-connections-ssl-wizard.html

(Edit: noting there are a few different things that may cause this. still researching.)

Internal ref: https://pantheon.slack.com/archives/C03SRV7HB/p1529363538000186

**Comment by carl-alberto** [comment]
@sarahg one user reported that this suggestion didn't work for MySQL Workbench

This seems to work for them: https://www.screencast.com/t/7t16Y7qY
When creating new connection:
1) Connection Tab
2) Connection method: (TCP/IP) > SSL Tab
3) Use SSL : No

Another solution that worked from the command line was adding the `--ssl-mode=disabled ` flag

**Comment by alexfornuto** [comment]
@carl-alberto wouldn't disabling SSL mean that their DB data is being transmitted in clear text? Would we not want to avoid that sort of security risk?

**Comment by carl-alberto** [comment]
@alexfornuto That would be correct :) maybe this option will be the last resort if all else fails, with a big disclaimer of the risk involved if using this method.

**Comment by sarahg** [comment]
@alexfornuto I don't think we want to officially recommend they bypass SSL, even though it does get people around this error in a pinch. That said, I don't know how to clear this up yet, and I haven't been able to reproduce the issue myself, but a few people in CSE have been running into it this week. We've had maybe 5-10 reports from customers about it in the last few days.

**Comment by calmher** [comment]
This guide might help renewing those certs needed by mysql - https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-rsa-files-using-mysql.html

**Comment by danheisel** [comment]
We're experiencing this issue on all of our site environments except live for our entire organization. It seems to have popped up in the last week or so. The official answer is to add local CA certs for every site, which is not something we've had to do in the past.

**Comment by alexfornuto** [comment]
Marking as blocked pending BUGS-2075

**Comment by alexfornuto** [comment]
Resolved by BUGS-2075
