### ISSUE TITLE
Update Custom Certificate doc to include CAA policy that allows LE for certain accts

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#3810]
Re: <Add Doc title and/or link>

Priority (Low‚ Medium‚ High): Medium

## Issue Description

from https://github.com/pantheon-systems/documentation/pull/3803#discussion_r197297043

I believe you can also create a CAA policy that allows Let's Encrypt but whitelists the Let's Encrypt accounts that may issue. This would also prevent Pantheon from obtaining Let's Encrypt certs for the domain while still allowing the institution to use LE: https://community.letsencrypt.org/t/the-future-of-caa/62160

We should verify that first, though.

**Comment by alexfornuto** [comment]
@ari-gold Clarification requested: Whilelists what accounts? I don't follow.

**Comment by ari-gold** [comment]
Let's Encrypt accounts. Updated body of issue,

**Comment by alexfornuto** [comment]
Unable to find any information yet on CAA restrictions at account level. Closing for now.
