### ISSUE TITLE
Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by kf6nux** [pantheon-systems/documentation#3815]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs/cloudflare/)

Priority: Low

## Issue Description:
The example configurations don't indicate how to configure a vanity domain with wildcard dns.

**Comment by alexfornuto** [comment]
@kf6nux can you provide what steps are required to configure a vanity domain with a wildcard DNS entry on Cloudflare? That would go in the "*Suggested Resolution*" section of the issue.

If not, can you suggest an SME who could provide the details required to continue with this issue?

**Comment by kf6nux** [comment]
@alexfornuto No, I haven't explored it myself.  I'm not sure who might be a SME on Cloudflare configurations.

**Comment by alexfornuto** [comment]
@kf6nux the instructions [here](https://pantheon.io/docs/vanity-domains/#create-wildcard-dns-records) explain how to create the wildcard DNS records for Vanity domains in general. Does Cloudflare need any specific instructions? Should we expect someone who is configuring vanity domains and using Cloudflare to have the prereq knowledge to use the existing data to achieve the desired results?

**Comment by kf6nux** [comment]
@alexfornuto maybe.  This issue has been open for six months and I've forgotten the context that drove me to open it.  If you want to close it for now as "won't do", I'd be okay with that.

**Comment by alexfornuto** [comment]
@kf6nux sorry for the delay. Working on bringing down our debt as we speak so we can get to issues more quickly.

Closing the issue for now, but feel free to re-open / re-create if / when more details make themselves known.
