### ISSUE TITLE
Upgrade PHP Versions Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#3819]
Re: [Upgrade PHP Versions](https://pantheon.io/docs/php-versions/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
If you specify the point release PHP version in your pantheon.yml file (e.g 7.2.6 instead of 7.2), the update will fail.

## Suggested Resolution
Note that you should not specify the point release, just the major/minor version.

**Comment by alexfornuto** [comment]
@sarahg are you comfortable with my edits?
