### ISSUE TITLE
External Libraries on Pantheon Doc -- ImageMagick

### ISSUE THREAD

**Issue by rtblair** [pantheon-systems/documentation#3821]
Re: [External Libraries on Pantheon](https://pantheon.io/docs/external-libraries/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
Documentation says that Pantheon supports the latest stable version of ImageMagick . . . 
> Pantheon runs the latest stable packaged version in Fedora, which is currently ImageMagick 6.8.8-10 Q16 x86_64 2015-03-10.

. . . but their website suggests that the latest stable version is 7.0.8. (https://www.imagemagick.org/script/download.php).

## Suggested Resolution
Clarify support for ImageMagick.

**Comment by alexfornuto** [comment]
Internal Ref: FEAT-574

**Comment by ari-gold** [comment]
Hi @rtblair  -- Thanks for creating this issue. I've created a doc update to clarify the current state of external libraries on the platform, and the feature request process.

Can you please contact support with this request? Curious to hear more about what issues you're running into with the older version.  I see two other customers that have requested an ImageMagick upgrade in the last 1.5 years. We have other higher priority issues we're working on, but we will prioritize work to upgrade libraries and figure out a safe upgrade path for customers.
