### ISSUE TITLE
WooCommerce Quick Start Doc Update 

### ISSUE THREAD

**Issue by mcdwayne** [pantheon-systems/documentation#3824]
Re: [WooCommerce Quick Start](https://pantheon.io/docs/guides/woocommerce/configure/)

Priority (Low‚ Medium‚ High):

## Issue Description:

In the description of the page for SSL forced use it shows a menu option of "checkout" but in my testing I see no such option.  
Instead I find this option under "Advanced" tab

![Imgur](https://i.imgur.com/1kAb0wA.png)

## Suggested Resolution

**Comment by alexfornuto** [comment]
Assigning to @ataylorme to reach out to the contributing author.

**Comment by ataylorme** [comment]
I verified the location is where @mcdwayne suggested and updated the image/text in #3829.

**Comment by alexfornuto** [comment]
@mcdwayne thanks for submitting the issue. @ataylorme thanks for fixing!
