### ISSUE TITLE
Document "not fully protected" public directory (Drupal)

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3838]
We regularly see tickets due to Drupal reporting public / tmp directory "not fully protected". This happens in D7 and D8.

The reason is that Drupal expects to find a .htaccess file protecting these directories, as per:
https://www.drupal.org/forum/newsletters/security-advisories-for-drupal-core/2013-11-20/sa-core-2013-003-drupal-core

Quoting from there:

> Please note that if you are using a different web server such as Nginx the .htaccess files have no effect and you need to configure PHP execution protection yourself in the respective server configuration files.

On Pantheon we have implemented the needed protection on Nginx level, so this is a false alert.

DO issue pending on this:
https://www.drupal.org/project/drupal/issues/2150399

Internal reference:
https://pantheon-systems.desk.com/agent/case/108617

**Comment by carl-alberto** [comment]
What would be relevant keywords @alexfornuto for that addition to be easily found in the docs? Customers was not able to find this easily: https://pantheon.io/docs/platform-considerations/#drupal-false-positive using this keyword "public files directory not fully protected"

**Comment by diegoluisr** [comment]
Hi, is it still a false alert?

**Comment by almadorx** [comment]
The same question here - in Drupal 10 on Pantheon I see this error:
"Public files directory: Not fully protected"
