### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#3841]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/)

Priority: low

## Issue Description: 

User had perceived terminus issues from an issue which had since cleared, the cause was their removal of build tools generated key being added to user account had been deleted

## Suggested Resolution

Include notice somewhere in doc that highlights the fact a key is generated and added by build tools

**Comment by alexfornuto** [comment]
@newtoid is this referring to a key _other_ than the machine token generated by the user in Step 4 of the first page? If so, are we talking about a Pantheon Machine Token, or other key?

**Comment by greg-1-anderson** [comment]
This is fairly common. The Build Tools script automatically creates a public/private key pair and adds the private key to CircleCI and the public key to Pantheon. Both are visible in their respective service admin pages as removable read-only objects. If you remove one, then your builds will stop working.

We don't have an automation tool to repair this situation; the user must generate a new key pair manually per https://pantheon.io/docs/ssh-keys/ (n.b. only Pantheon public key side is described; updating the CircleCI private key not described)

**Comment by alexfornuto** [comment]
@greg-1-anderson at which step in the guide is this keypair created? I'm assuming it's step 1 of page 2:

>`terminus build:project:create d8 pantheon-d8-composer-project`

**Comment by greg-1-anderson** [comment]
Yes, it is done by `build:project:create`
