### ISSUE TITLE
New Doc: Use Solr for Redirects

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#3866]
Priority: Low

## Title
Use Solr for Redirects

## Description
For sites with a large number of redirects, putting all the redirect logic into `settings.php` can severely slow down the site.

As an alternative, some customers have figured a method of passing URL requests that don't exist through Solr for matching pages, then redirecting. They were kind enough to offer assistance in the new doc.

## Outline

If @toddtomlinson and/or others would "skeleton" the basic steps, I can start formatting the doc around them.

## Path
How about `/docs/solr-for-redirects` ?

**Comment by alexfornuto** [comment]
@toddtomlinson are you still interested in this project?

**Comment by EdwardAngert** [comment]
closing this one for now.
@toddtomlinson, if you do put some steps together for this, we'll be happy to reopen the issue and work it into a doc with you
