### ISSUE TITLE
Document how to enable "Secure runtime access"

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3869]
## Description
Changelog from 2015 suggests it is possible to enable "secure runtime access", but we have no further context on where / what / how to enable.
A mysql setting perhaps? Does this persist across DB restarts?

It does mention it requires ssh tunnels.

Reference:
https://pantheon.io/docs/changelog/2015/06/#single-sign-on-sso-release

Blog post here:
https://pantheon.io/blog/website-security-modern-age

(Internal) Comment here:
BUGS-2072?focusedCommentId=59094&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-59094

(Internal) discussion here:
slack archives/C03SRV7HB/p1531490062000366

## Expected Audience
CSE + customers

**Comment by joshkoenig** [comment]
This is a setting that can be enabled by CSE. It is an organization-wide setting as this usually goes along with IT policies that mandate change management.

**Comment by alexfornuto** [comment]
Blocked pending `BUGS-2072`
