### ISSUE TITLE
WordPress and Drupal Core Updates Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3870]
Re: [WordPress and Drupal Core Updates](https://pantheon.io/docs/core-updates/)

Priority (Low‚ Medium‚ High):

## Issue Description:
We regularly have customers off upstream. It would be great to add an item under troubleshooting for instance, on how to easily get back on upstream.

## Suggested Resolution
We have an internal comment here on how to:
https://getpantheon.atlassian.net/browse/FEAT-314?focusedCommentId=40337&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-40337

Needs testing though to make sure it works.

**Comment by alexfornuto** [comment]
@tinefin for customers "off upstream" do you mean that they have set an empty/alternate upstream, or only that they have diverged from the upstream?

**Comment by alexfornuto** [comment]
@tinefin this issue is incomplete. Docs doesn't have the resources or positioning to test a solution. Once a solution is confirmed, we can implement it into the docs.
