### ISSUE TITLE
Using WP-CLI On The Pantheon Platform Doc Update 

### ISSUE THREAD

**Issue by mcdwayne** [pantheon-systems/documentation#3876]
Re: [Using WP-CLI On The Pantheon Platform](https://pantheon.io/docs/wp-cli/)
I don't think there is an actual way to extend WP-CLI on Pantheon, but the doc suggests there is...
 

Priority:

## Issue Description:

There is currently a section that reads:
"Extending WP-CLI With Subcommands
WP-CLI has a framework for users to write their own commands. Learn about the anatomy of a subcommand to solve your thorny problems with WP-CLI."
https://pantheon.io/docs/wp-cli/#extending-wp-cli-with-subcommands

Having pulled my hair out at the composer based memory errors I have seen in every attempt I have made to actually extend WP-CLI on Pantheon I do not believe this is true in the context of our platform. 

IN GENERAL this is a true thing, but on our platform specifically, not seeing evidence it is

## Suggested Resolution

Remove the section anchored here:
https://pantheon.io/docs/wp-cli/#extending-wp-cli-with-subcommands

**Comment by sarahg** [comment]
@mcdwayne I tried implementing a (very simple) custom wp-cli command (just copied [this](https://junaidbhura.com/add-a-custom-wp-cli-command-in-wordpress/)) and that worked OK. No Composer usage on that one, though. 

So maybe we just need to note that commands are subject to the same application memory limits and timeouts as the site itself? What sort of Composer problems did you run into?

**Comment by mcdwayne** [comment]
Popping open the theme's function.php file and tossing your commands in that way (per the article) probably does work, but now we can't change themes and still keep our functionality.  

wp-cli leverages composer for new things they build and using the scaffolding command (very powerful feature) end you up with a command that looks like this one to actually implement the command you are building: 
wp package install git@github.com:wp-cli/scaffold-command.git
From:  https://github.com/wp-cli/scaffold-command#installing

![screen shot 2018-09-11 at 3 57 23 pm](https://user-images.githubusercontent.com/6043617/45392470-59deb400-b5dc-11e8-9de6-8c85dfa31c38.png)


Here is another example, pretty simple code, that also fails 
wp package install git@github.com:mcdwayne/php-version.git
from: https://github.com/mcdwayne/wp-cli-commands/tree/master/php-version

![screen shot 2018-09-11 at 4 01 13 pm](https://user-images.githubusercontent.com/6043617/45392469-59deb400-b5dc-11e8-8721-9314a00482b7.png)


So,  modifying functions.php is not the issue, installing components with composer is the issue.

**Comment by sarahg** [comment]
@mcdwayne Yes, I understand the concept of themes — that demo command could go in a custom plugin as well, as long as you register it with WP_CLI::add_command, sure. Bad example I guess, sorry about that!

My thought here was that the issue isn’t with custom commands in general, but more so about the inability to run Composer commands (or something like “package install,” same idea) directly on application containers. 

I suppose the entire section could be removed, but I think a sentence about Composer memory limitations may be clearer.

**Comment by alexfornuto** [comment]
I thought that composer-based commands in general wouldn't work on the platform. Could the caveat be as simple as that?

**Comment by mcdwayne** [comment]
Sorry if I came across too strong there, was more trying to articulate the issues I saw more clearly.  guess I overexplained.  

Yes, explaining that using composer to install extensions will not work should be good with a link to the docs explaining the composer issues would be ideal.  
More accurately would be the explanation that "you can not use the wp package commands to add commands due to the limitation of running composer on Pantheon."
reference for my thinking on that:
https://developer.wordpress.org/cli/commands/package/
https://make.wordpress.org/cli/handbook/sharing-wp-cli-packages/
