### ISSUE TITLE
Best Practices for Maintaining Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#3881]
Re: [Best Practices for Maintaining Custom Upstreams](https://pantheon.io/docs/maintain-custom-upstream/)

Priority: Medium

## Issue Description:
The `rebase` instructions on this page sometimes fail.

## Suggested Resolution
Doing an ordinary `git merge` seems to work better.

See #power-users discussion:
https://pantheon-community.slack.com/archives/C2GJ3JG7Q/p1531862762000440

**Comment by populist** [comment]
Here is a good discussion of the differences between Merge and Rebase - https://www.atlassian.com/git/tutorials/merging-vs-rebasing
