### ISSUE TITLE
Relaunch Existing Pantheon Site Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3882]
Re: [Relaunch Existing Pantheon Site](https://pantheon.io/docs/relaunch/)

Priority:

## Issue Description: The Standard DNS config mentioned in the doc does not apply for sites that are using a Custom Cert.

<img width="857" alt="screenshot" src="https://user-images.githubusercontent.com/14119666/42869154-eab7a8b2-8aa6-11e8-8cc0-81a84613f23c.png">

They need to use A/AAAA records and not CNAME.

## Suggested Resolution

Update the Doc to reflect this.

**Comment by alexfornuto** [comment]
@rubelyn this drop-down covers the "Standard Configuration". Custom certs are not standard. Does the dashboard not provide what records they are supposed to create?

**Comment by carl-alberto** [comment]
@rubelyn Please check if this was your intended notes to add regarding relaunches with custom certs?
