### ISSUE TITLE
WordPress Private Path Plugins

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3883]
Re: <WordPress Private Path Plugin>

Priority: Medium

## Issue Description
Some customers would like to have their files in a private location. We offer the solution to have Private paths as shown in docs page: https://pantheon.io/docs/private-paths

For WordPress, there is no core feature to configure a private path folder. There are several plugins that will help achieve this but it would be helpful to validate available tools or such specific recommendations

https://wordpress.org/plugins/media-vault/
https://wordpress.org/plugins/private-uploads/
https://wordpress.org/plugins/download-monitor/

Several blogs talk about configuring the server, but this may not be applicable to Pantheon
https://www.shift8web.ca/2016/05/protect-and-secure-wordpress-media-uploads/

## Suggested Resolution

Create a section in private-paths docs to briefly discuss possible tools that can work with Pantheon for ensuring private paths and files

**Comment by carl-alberto** [comment]
Also got a chats about this in the past about this but haven't provided them a good solution, would love to test this out and document it if possible @eabquina

**Comment by alexfornuto** [comment]
This is a great idea, but will need to be driven by an SME who can properly test and validate what plugins to suggest as solutions.
