### ISSUE TITLE
WordPress Cache Control for REST API endpoints

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3884]
Re: [Bypassing Cache with HTTP Headers](https://pantheon.io/docs/cache-control/)

Priority (Low):

## Issue Description:
Chat: 17546135658

The customer is trying to set cache control for WP JSON pages, but it turns out, caching works differently for REST API based pages in the platform

## Suggested Resolution

Add a section that tells there is a different caching mechanism being set by the Pantheon Cache plugin 
The function ​filter_rest_post_dispatch_send_cache_control shows this logic.

**Comment by alexfornuto** [comment]
I read through the referenced chat, but would need an SME to dissect the discussion into usable content that could be added to the docs.

**Comment by Uriel1339** [comment]
Just tried to follow these instructions:
https://pantheon.io/docs/cache-control/#exclude-specific-pages-from-caching

And put it in as the following in my functions.php:
`
// This code prevents caching on API requests in HTTP Header.
$regex_path_patterns = array(
  '#^/wp-json/?#',
);

// Loop through the patterns.
foreach ($regex_path_patterns as $regex_path_pattern) {
  if (preg_match($regex_path_pattern, $_SERVER['REQUEST_URI'])) {
    add_action( 'send_headers', 'add_header_nocache', 5 );
    // No need to continue the loop once there's a match.
    break;
  }
}
function add_header_nocache() {
      header( 'Cache-Control: no-cache, must-revalidate, max-age=0' );
}`

This is clearly not working after running cURL -i commands. However after testing with a static page such as '/shop/' it works for sure. 

How can I stop API requests from being cached? This is a serious problem for our pantheon installation.

**Comment by alexfornuto** [comment]
@Uriel1339 my testing all showed that this code snippet didn't affect caching when placed in `functions.php`. But when placed in `wp-config.php` it worked as documented. If you can confirm that moving the code to `wp-config.php` resolves the issue for you, I'll update the copy in the doc to explicitly state that path.

**Comment by alexfornuto** [comment]
@eabquina It looks like the referenced chat also had the cache bypass code added to `functions.php`. Am I wrong in thinking that code put in a theme's `functions.php` file won't be executed when requesting content that doesn't use a theme (like API calls) ?
