### ISSUE TITLE
Drupal Commerce on Drupal 8 Doc Update 

### ISSUE THREAD

**Issue by healygreggatyahoo** [pantheon-systems/documentation#3890]
Re: [Drupal Commerce on Drupal 8](https://pantheon.io/docs/guides/drupal-8-commerce/)

Priority: Medium

## Issue Description:

Couldnt get it installed with:

composer require "drupalcommerce/commerce_base dev-8.x-1.x"

changed to:

composer require 'drupal/commerce:^2.8'

Although it still kicks a bunch of these back:

strpos(): Empty needle ExtensionDiscovery.php:295                      [warning]
The following module is missing from the file system: commerce         [warning]
bootstrap.inc:268

Also, in the Install Commerce section item 6, I didnt get the Install Later option and the Drop table notificatoins had me nervous.

## Suggested Resolution

Change the composer require line, remove the Install Later note and let people know its ok to drop the table.

**Comment by alexfornuto** [comment]
CC @stevector

**Comment by alexfornuto** [comment]
I confirmed the issue with `commerce_base dev-8.x-1.x` as described above, but would like input from @stevector or @mglaman on possible solutions.

**Comment by stevector** [comment]
@alexfornuto, I don't think we should make the suggested change. commerce_base` is the install profile we are guiding people to use. Yes, just the commerce `module` can be installed separately, but I don't think that's as helpful. Can you book time when we're both in the office to walk through this issue?

**Comment by alexfornuto** [comment]
The stem of this issue (as well as #4517) was an update to the `example-drop-8-composer` project that updated `drush-ops/behat-drush-endpoint` in composer.json but not in composer.lock. https://github.com/pantheon-systems/example-drops-8-composer/pull/187 will resolve the issue, and #4533 will be amended to mention `composer update` as a first troubleshooting step.

**Comment by alexfornuto** [comment]
Closed by https://github.com/pantheon-systems/example-drops-8-composer/pull/187
