### ISSUE TITLE
Temporary File Management Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#3898]
Re: [Temporary File Management](https://pantheon.io/docs/tmp/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Writable path in WP is 'wp-content/uploads' so much better to update this doc to reflect that file path

## Suggested Resolution
Updating WP related docs to reflect 'wp-content/uploads/tmp' instead of '/tmp'

**Comment by alexfornuto** [comment]
Closing per discussion in #3899.
