### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update [Fix D7 directions]

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#3924]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
The steps for Redis setup on D7 have a few issues:

- step 5 enables the module, but so does the drush command in step 2
- the path to the modules page in step 5 is incorrect (should be `admin/modules`)

## Suggested Resolution
- Remove step 5 (but replace it with a step to clear caches if that's needed)

**Comment by umandalroald** [comment]
Created a PR for this issue https://github.com/pantheon-systems/documentation/pull/3925

**Comment by alexfornuto** [comment]
@umandalroald Thanks for making the PR. You removed the step, but do we still need to replace it with a step to clear caches?
