### ISSUE TITLE
rsync and SFTP Doc Update to add how to empty folders using rsync

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#3926]
Re: [rsync and SFTP](https://pantheon.io/docs/rsync-and-sftp/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Since `rm -rf` command is not available and via ftp command line, an alternative way to recursively empty a folder is using the `rsync --delete` flag 

## Suggested Resolution
Add an example in docs on how to empty folders using rsync

**Comment by alexfornuto** [comment]
Resolved by @3927, not sure why this wasn't closed then.
