### ISSUE TITLE
Using SendGrid To Deliver Email Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#3928]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs/guides/sendgrid/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
When logged into my free Sendgrid account, there is no option for "Credentials" under "Settings". The closest match is "Subuser Management", though I can't see what happens on that tab because it's a paid service. 

## Suggested Resolution
If this is a difference between free and paid, this issue can be resolved by adding a line that explains that free plans should not look for the Credentials tab. If this is a change in SendGrid's UI, we will want to rewrite or remove that section.

**Comment by sparklingrobots** [comment]
I'm happy to take a look at this & create a PR if we have a paid account I can use to investigate.

**Comment by alexfornuto** [comment]
I _think_ that this issue was resolved by #4208, but would like it if @sparklingrobots could confirm.

**Comment by sparklingrobots** [comment]
Just double checked and all looks good!
