### ISSUE TITLE
Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3929]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs/cloudflare/)

Priority: Low

## Issue Description:

Clarification on step 4 for Option 2:

> Remove existing redirects configured via PHP in settings.php or wp-config.php.

It seems like CloudFlare Page Rule will not be able to redirect traffic for all Pantheon issued domains. 
Ex. live-*-pantheonsite.io to www.mysite.com. This will only work for all domains with orange cloud.

The redirect in wp-config.php still needed if the Customer wants to redirect their Live Pantheon domain to a primary domain.

## Suggested Resolution
Review the case, make it clearer and update the doc accordingly to avoid confusion.

**Comment by alexfornuto** [comment]
@rubelyn step 5 shows `example.com` and `www` as CNAMEs for `live-example.pantheonsite.io`. Why would the site still need a redirect in php with the CNAME records from CloudFlare pointing to the platform domain?

**Comment by dylanjameswagner** [comment]
I read the original poster's issue was with the broadness of the statement of
> Remove existing redirects configured via PHP in settings.php or wp-config.php.

In-so-far as there may be other redirect use cases that you may not want to remove. For me that takes the form of 1) redirecting Pantheon platform urls to their custom url and 2) redirecting HTTP requests to HTTPS for all Pantheon environments.

**Comment by alexfornuto** [comment]
@dylanjameswagner thanks for weighing in. I now understand that the issue is with the broadness of the statement, but I'm still unclear on exactly how it should be better clarified. Perhaps it should be modified to say something like:

> Removing any existing redirects configured in `settings.php` or `wp-config.php` that you no longer need, and update any still required to point to the domain managed by Cloudflare.

cc @rubelyn
