### ISSUE TITLE
Document non-static nature of DB connection listed as a Known Limitation 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#393]
Story: As a user I want non-static nature of DB connection listed as a Known Limitation so that I don't rely on it only to fail at the wrong time.

As a user I want non-static nature of DB connection listed as a Known Limitation so that I don't rely on it only to fail at the wrong time.   Add a tag
A user was complaining about DB connection info changing. We make no guarantees around this, so they should not rely on it. We shold document it as a Known Limitation.

Ping me on the copy, and I can review.

http://esipfed.org/ 
https://admin.dashboard.pantheon.io/sites/ecb7f47e-3cde-4c0b-bd6d-43c6edda0cb5#debug/debug/environments-debug

![sip](https://cloud.githubusercontent.com/assets/9138609/7235144/01ceebee-e741-11e4-85a4-ec6c9a4eceee.jpg)

--Submitted by Nick S

Comments:

 Brian M. commented:  timani tunduwani Can we quickly list situations where our users have needed/wanted to do this, along with a workaround for accomplishing the same thing?

 Brian M. commented: Nick Stielau Considering both [DB connection errors](https://github.com/pantheon-systems/documentation/blob/db-dynamic/source/docs/articles/sites/database/database-connection-errors.md) and [known limitations](https://github.com/pantheon-systems/documentation/blob/db-dynamic/source/docs/articles/sites/known-limitations.md). Either way, can we link to the anchor from the connection info tool?
a month ago

cc Scott Massey timani tunduwani
 Nick S. created this

**Comment by rachelwhitton** [comment]
[Configuring wp-config.php](https://pantheon.io/docs/articles/wordpress/configuring-wp-config-php/) and [Configuring Settings.php](https://pantheon.io/docs/articles/drupal/configuring-settings-php/) both have warnings stating the dynamic nature of db credentials. The docs also link to [Reading Pantheon Environment Configuration](https://pantheon.io/docs/articles/sites/code/reading-pantheon-environment-configuration/). 

@bmackinney @nstielau is this sufficient? Or should it be in the Known Limitations doc as well?

**Comment by nstielau** [comment]
It’s probably OK as it is.  This doesn’t quite fit as a ‘Known Limitation’
to me, and it doesn’t make sense for that list to cover everything that
might not work on Pantheon.  Your call.

On Wed, Jun 10, 2015 at 8:57 AM, Rachel <notifications@github.com> wrote:

> Configuring wp-config.php
> <https://pantheon.io/docs/articles/wordpress/configuring-wp-config-php/>
> and Configuring Settings.php
> <https://pantheon.io/docs/articles/drupal/configuring-settings-php/> both
> have warnings stating the dynamic nature of db credentials. The docs also
> link to Reading Pantheon Environment Configuration
> <https://pantheon.io/docs/articles/sites/code/reading-pantheon-environment-configuration/>.
>
>
> @bmackinney <https://github.com/bmackinney> @nstielau
> <https://github.com/nstielau> is this sufficient? Or should it be in the
> Known Limitations doc as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/documentation/issues/393#issuecomment-110810266>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon

**Comment by nataliejeremy** [comment]
+1
