### ISSUE TITLE
WordPress and Drupal Core Updates Doc Update - manual merge failures

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#3930]
Re: [WordPress and Drupal Core Updates](https://pantheon.io/docs/core-updates/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
Due to the recent WP update, we got a growing number of incidents that the auto-update is failing, must be related to: https://github.com/pantheon-systems/WordPress/issues/141

## Suggested Resolution
Document a workaround so they can resolve it quickly in their end

**Comment by alexfornuto** [comment]
Resolved by https://github.com/pantheon-systems/WordPress/pull/176
