### ISSUE TITLE
Improve Search Rankings for Docs

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#394]
As a Pantheor I want Higher search rankings for docs and guides so that more people find them and read them.

- [x] Add keyword meta
- [x] Add keywords to frontmatter for all docs
- [x] Evaluate/improve doc titles/descriptions
- [x] Fix sitemap.xml
- [x] move GA tracking to `<head>`
- [x] get it indexed

**Comment by rachelwhitton** [comment]
#489 closes this issue when merged.

**Comment by bmackinney** [comment]
Not fully. It will complete the fourth sub-task.
