### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site Doc Update 

### ISSUE THREAD

**Issue by jcheek** [pantheon-systems/documentation#3942]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert/)

Priority (Low‚ Medium‚ High): High

## Issue Description:

This guide tells you to create a new branch but all the work is done in a new repo.  nothing in that branch is changed.

## Suggested Resolution

Technically review this HOWTO.  Ensure that the steps actually do work.  In particular, following the steps results in a new repo that never makes it to pantheon and a new branch inside a current repo with no changes.

If the method to create a new repo is kept, this should be clearly stated at the top of the HOWTO.  This method advocates blowing away an entire repo and altering a site to use a new repo, which will result in a loss of all git history for that entire site.  This should be clearly marked, as it will be a significant barrier to adoption.

**Comment by dustinleblanc** [comment]
@jcheek this method does not create a new repository, it creates a new folder of files, then copies the original `.git` directory to the new project folder structure, which brings all of the remotes and commit history with it. The result is just two copies of the repo, one with the old structure (in case you have to bail out and keep using it), and one with the new structure. You push the from the new folder, which still contains all the git data of the original Pantheon repo.
