### ISSUE TITLE
Using SendGrid To Deliver Email Doc Update 

### ISSUE THREAD

**Issue by albertcausing** [pantheon-systems/documentation#3949]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs/guides/sendgrid/)

Priority: Low

## Issue Description:
The screenshot in WordPress Sendgrid settings interface is now different 

## Suggested Resolution
This is how it looks like:
https://monosnap.com/file/a3E4iIJmszGxfEawyv3Ry8e3AajYgO

**Comment by alexfornuto** [comment]
Resolved in #4208
