### ISSUE TITLE
Create articles on SMTP so that email is not sent from mail()

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#395]
Story:
As a user I want more stuff about SMTP so that email is not sent from mail()

“Class to use for the format() method” as MimeMailSystem and “Class to use for the mail() method” as SmtpMailSystem

There is a problem with the configuration of some Drupal modules that is resulting in PHP throwing an error that results in a crash of the thread and returns a 502 error:

Helpful links:
http://www.phparch.com/2014/07/sending-html-emails-with-drupal-7-webform-and-mandrill/
https://www.drupal.org/node/1200142
http://drupal.stackexchange.com/questions/77608/drupal-7-webform-module-is-not-sending-email-properly
http://drupal.stackexchange.com/questions/39474/how-can-i-use-the-mimemail-with-stmp-authentication-support-modules-together-on
@timani

**Comment by rachelwhitton** [comment]
@timani:
> There is a problem with the configuration of some Drupal modules that is resulting in PHP throwing an error that results in a crash of the thread and returns a 502 error:

Is that error a direct result of using mail() on the platform? Can you grab an example of the 502 error to include?

**Comment by rachelwhitton** [comment]
ping @timani  -  can you review the above question ^

**Comment by alexdicianu** [comment]
We don't really want to go into debugging Drupal's mail() function, as we don't want to encourage people to use Pantheon for sending email. It's problematic, we're on a bunch of blacklists, etc. What we want to do is:

* suggest using an email cloud service provider: Sendgrid, Google, Mandrill, etc.
* use SMTP only if the service provider doesn't have a better API integration like Sendgrid with https://www.drupal.org/project/sendgrid_integration
