### ISSUE TITLE
Configuration Workflow for Drupal 8 Sites Doc Update 

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#3956]
Re: [Configuration Workflow for Drupal 8 Sites](https://pantheon.io/docs/drupal-8-configuration-management/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
The article-subhead of [this page](https://pantheon.io/docs/drupal-8-configuration-management/) appears to be an unintended duplicate of the article subhead of [this page](https://pantheon.io/docs/drupal-caching-modules/).

## Suggested Resolution:
Write a new article-subhead that accurately represents the content of the Configuration Workflow for Drupal 8 Sites Doc page.

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign. This doc needs a top-to-bottom overhaul.
