### ISSUE TITLE
New Doc Proposal - include information about migrating wordpress sites with prefixes

### ISSUE THREAD

**Issue by nvahalik** [pantheon-systems/documentation#3973]
Priority (Low‚ Medium‚ High): Medium

## Title
Updates to wp_usermeta are also required when migrating from non wp_ prefixed sites.

## Description
Migrating sites that use a non-standard `wp_` prefix will break, even if you update the `$table_prefix` value. You will also need to run a command like the following to update the capabilities and user level metadata for users:

```update wp_usermeta set meta_key = replace(meta_key, '<oldprefix>_', 'wp_');```

## Path
`source/docs/wordpress-known-issues`

**Comment by alexfornuto** [comment]
@nvahalik thanks for the issue! Please confirm, your code snippet should _also_ be added to `wp-config.php`?

**Comment by alexfornuto** [comment]
@nvahalik please take a look at #4397 to see if it properly addresses this issue.

**Comment by nvahalik** [comment]
That looks correct @alexfornuto! I'm not sure that it needs to be added to the `wp-config.php` file itself, it just needs to be run once during the migration process.
