### ISSUE TITLE
"find tests/scripts/ -type f | xargs chmod 755" should also be removed in post-update-cmd 

### ISSUE THREAD

**Issue by geraldvillorente** [pantheon-systems/documentation#3982]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:
`composer update` command is running `"find tests/scripts/ -type f | xargs chmod 755"` which will fail because `tests` directory is already deleted.

## Suggested Resolution:
Since we deleted `tests` directory in the codebase, we also need to remove `"find tests/scripts/ -type f | xargs chmod 755"` in `post-update-cmd` section in `composer.json`.

**Comment by alexfornuto** [comment]
Thanks, but we resolved this last week with #3943.
