### ISSUE TITLE
The Quicksilver scripts in `web/private/scripts` folder is causing 500 server error.

### ISSUE THREAD

**Issue by geraldvillorente** [pantheon-systems/documentation#3983]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:
Quicksilver script in `web/private/scripts` folder is throwing PHP fatal error (500 error). This error prevents the installation of the site.

## Suggested Resolution:
Delete `web/private/scripts` folder.

**Comment by alexfornuto** [comment]
CC @ataylorme @davidneedham @mcdwayne

**Comment by alexfornuto** [comment]
Asked internally, @ataylorme asked for more details in order to properly troubleshoot.

**Comment by ataylorme** [comment]
Hi @geraldvillorente,

Please provide more details.

- What step in the guide did you run into this?
- What is the PHP error?
- Was this for an existing site? If so, do you encounter the same error following the guide on a new site?

I looked at the script in question and we have tested the guide as well and I don't see anything that would cause a 500 error.

**Comment by alexfornuto** [comment]
Reached out to @geraldvillorente to say that this issue will be closed unless he can provide actionable information.

**Comment by geraldvillorente** [comment]
@ataylorme I documented the process here including the error - https://docs.google.com/document/d/1xmXXVbth96AADNpgZYgZgSx0r2LYCfktkKmkXi9g-3Y/edit

**Comment by alexfornuto** [comment]
Closing this as CNR and not enough information.
