### ISSUE TITLE
Require HTTPS with the HSTS Header: Customer recommended alternative

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3990]
Re: [Require HTTPS with the HSTS Header](https://pantheon.io/docs/hsts/)

Priority: Low 

## Issue Description:
Customer recommending to consider **Security Headers** By Simon Waters (Surevine Ltd) (https://wordpress.org/plugins/security-headers/) as a better plugin over the current LH HSTS plugin. 

## Suggested Resolution
Evaluation of plugin by security and/or Wordpress team.

**Comment by ataylorme** [comment]
I personally like [the `lh-hsts` plugin](https://wordpress.org/plugins/lh-hsts/) as it is simple doing one thing, setting HSTS headers, well.

The maintainer has also [been responsive to issues/fixes](https://wordpress.org/support/topic/relocated-wordpress-core-directory-issues/).

The [security headers plugin](https://wordpress.org/plugins/security-headers/) description says it sets a variety of headers, not just HSTS, which is the goal of the doc.

@thomas-thackery can you expand on _why_ the switch is being suggested?

**Comment by alexfornuto** [comment]
Doesn't matter now that we're enforcing HSTS at the platform level.
