### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3995]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso/)

Priority: High

## Issue Description:
Ticket: 111830
PHP mcrypt has been deprecated in 7.1 and excluded from php core in 7.2. 
Because of this, simplesaml 1.14.x will no longer work, and ask to upgrade to 1.15.x

## Suggested Resolution

Update documentation to start using 1.15.x if PHP version is PHP 7.1 or above.

**Comment by alexfornuto** [comment]
@eabquina can we just update the instructions to use 1.15.x regardless? In other words, will that version of simplesaml work on PHP versions <7.2?
