### ISSUE TITLE
Early Access: Custom Certificates: Technical contact information 

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#3997]
Re: [Early Access: Custom Certificates on Pantheon's Global CDN](https://pantheon.io/docs/custom-certificates/)

Priority: High

## Issue Description:
The technical contact email is required to install the cert but not asked for in the Docs. 

```
Enter technical contact email: 
Enter technical contact first name: 
Enter technical contact last name: 
```

## Suggested Resolution
Consider asking for this at the same time as the CSR details. Using the CSR details might be presumed, but could be stated.

**Comment by alexfornuto** [comment]
CC @ari-gold
