### ISSUE TITLE
Instructions on how to file and monitor support requests 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#400]
Story:
As a Pantheon User I want to know how to file and monitor support requests so that I know what to expect after I file one

Logged in Pantheon users can visit their dashboard to file a support request at [https://dashboard.getpantheon.com/sites/SITE-UUID#...]()

Otherwise, sending an email to helpdesk@getpantheon.com also opens a support request that is automatically associated with your account on Pantheon, if you have one. Users without Pantheon dashboard accounts may also send an email, or fill out our contact form at [https://www.getpantheon.com/contact](https://www.getpantheon.com/contact), to initiate their requests such as billing or account login issues. Customer Success updates support requests and associates them with the appropriate user/site/org, to facilitate our troubleshooting process and help users find their tickets later.

Tickets associated with sites appear in the support panel of the Site they are associated with, as well as on the Account support panel if the ticket filer is on the site's team. Non-site related issues filed in the Account Support panel are not listed in any Site Support panels.

As an Organization Admin filing a request from the Organization's Support panel, check the box marked "Non-site related issue" and the ticket will not be associated with any particular site. The ticket will also show in the Organization Support panel, as well as the Admin's Account Support panel after they have filed it. The Organization Admin won't be seeing tickets for sites on which they're not on the team, in their Account Support panel, however. Go to the particular Site Support panel directly, or add themselves to the site team, if they need to keep a closer eye on that site's support requests.

Site Support Requests filed for paying sites that are categorized as "Downtime" at the time of filing, will receive priority support. Enterprise sites and Enterprise Organization customers can also open Emergency tickets from their Site and/or Organization Support panel. Use Only In Case Of Emergency. This form is for use in an emergency when your site is down. Please do not cause false alarms. It will immediately page an engineer even in the middle of the night. If you need to ask a question or report a bug, please go back and use the regular support request form.

Created by @suzannealdrich

**Comment by bmackinney** [comment]
@suzannealdrich Is this still relevant? The UX for tickets has changed since this card was created. Are the issues still present?

**Comment by suzannealdrich** [comment]
Yes, the UX has changed but the issues are still present. I can review current state of interface to confirm these points are all still valid.
