### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by baisong** [pantheon-systems/documentation#4007]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

In the "Removing Automation Pieces", I followed the instructions, but then I got an error referencing the `scripts` folder that wasn't accounted for.

## Suggested Resolution

Right after `Remove the "find .circleci/scripts/pantheon/ -type f | xargs chmod 755", line from the post-update-cmd section of scripts.`, also add:
```
Remove the "find tests/scripts/ -type f | xargs chmod 755" line from the post-update-cmd section of scripts.`,
```

**Comment by alexfornuto** [comment]
CC @ataylorme 

Could we just remove `pantheon` from the existing step to remove the entire scripts directory?

**Comment by ataylorme** [comment]
@baisong first off sorry you had issues with the guide but **thank you** for letting us know so we can get it fixed for others.

@alexfornuto no, the existing step is to remove [the specific line from `composer.json`](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L66).

@baisong is correct that we should add another step to the doc to remove [the following line from `composer.json`](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L67) as well.

**Comment by alexfornuto** [comment]
Thanks @baisong!
