### ISSUE TITLE
Ignore composer.lock and composer.json? (No CI)

### ISSUE THREAD

**Issue by baisong** [pantheon-systems/documentation#4008]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

In the image below "Now let’s run git status again to make sure everything is included." on these docs, the only modified file is .gitignore, but when I follow the instructions, I also see composer.json and composer.lock as modified. Should those files be ignored?

**Comment by alexfornuto** [comment]
CC @ataylorme

**Comment by ataylorme** [comment]
@baisong you should add and commit them. Then other folks working on your site can run `composer install` locally. `composer update`, which will generate a new `composer.lock` file, should only be ran when you want to update dependencies (like core or contrib modules).

**Comment by baisong** [comment]
Thank you @ataylorme!

**Comment by alexfornuto** [comment]
Thanks for reporting @baisong!
