### ISSUE TITLE
Explain tmp file management across multiple application containers 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#401]
Highly related to #363 
Story:
As a Pantheon Developer I want to understand tmp file management across multiple application containers so that my file operations are performed without error.

"The problem is that with multiple application servers Drupal assumes the tmp directory will be on the same application vs a distributed system.

You can use the sites/default/files/tmp directory as this will be shared between all the environments and can essentially serve the same purpose as the tmp directory."

"It's definitely looks like the only way to manage your temporary files securely and reliably across DROPs in cases where multiple server calls might be required to process those files (e.g. batch jobs), the only option is to use something like private://tmp in code. Use of the temporary:// scheme should be avoided at all costs!"

"The Filesystem settings are set at bootstrap when a request is processed by Drupal. The public://, private:// and temporary:// are set dynamically depending on the application server that is hit using the $_PRESSFLOW settings variable. For sites with multiple DROPs this value will change. Try and refresh the page and this value should change on the Live environment:

http://www.example.com/admin/config/media/file-system

The problem with having that set to tmp/ is that this path points to the server /tmp directory that is not accessible by the web server on an application server. This is why we set the paths to something like the following:

/srv/bindings/2976a45d0d6644caaead02e2cde9a55e/tmp

In addition these paths are not accessible from other application servers. If you need a shared location that every application will have access to, we recommend using a tmp directory within the files directory for plup if possible such as private://tmp or public://tmp"

http://drupal.org/node/1184850#comment-5604022

variable_get('plupload_temporary_uri', 'temporary://')

Drupal contrib has a lot of code that was written without any consideration for the distributed use-case. There's a similar problem in the views_bonus code for exporting a view as CSV/XML, etc

run variable_set('plupload_temporary_uri', 'public://');

[Example Cases](https://docs.google.com/a/getpantheon.com/document/d/1LoVqEZpmQn50-cXqHr957kZVGDLjywdpDUctBdi1ddU/edit?usp=sharing)

https://api.drupal.org/api/drupal/includes%21file.inc/function/file_directory_temp/7

--Submitted by @suzannealdrich 

From 363:

See this case as an example:

writing sess_* files to the /tmp directory on application endpoints
"identified your Live site as writing zero byte temporary files to our application server systems, filling it close to capacity with regard to the underlying file-systems’ “inode” capabilities."

site writing many files names with the format googlefonts###.tmp (replace ### with digits) to the server’s root /tmp directory. This is causing disk space issues for the server, and we may put your site in maintenance mode until this condition can be fixed.

It looks like this is related to a site’s theme, which appears to be based off the ReduxFramework.

There is currently a bug filed with that project documenting the issue:

reduxframework/redux-framework#1383

Please try the recommendations suggested in that thread so this theme doesn’t write temp files to the server /tmp directory. The Redux maintainer suggests installing the Redux Framework plugin, or you may need to manually update redux within your theme.

Redux Framework
Session files

**Comment by andrewmallis** [comment]
webform.module lets you export results as a CSV via batch operation out of the box. For big operations, this can result in truncated datasets if the export is performed via the UI.

**Comment by suzannealdrich** [comment]
Being addressed in #584
