### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by albertcausing** [pantheon-systems/documentation#4012]
PHP 7.2 now requires simplesamlphp 1.15.4

"_Thank you – we have resolved this by updating 1.15.4 (latest stable) and seems to be working well._"

**Comment by alexfornuto** [comment]
I believe this was addressed in #4001. If I'm wrong, please open a new issue and fill out the provided template so that I have enough information to proceed.
