### ISSUE TITLE
Scope of Support Block Broken Link

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#4020]
Re:  support/open-ticket

Priority: Low

## Issue Description
When opening a new support ticket, this block has a broken link:
<img width="362" alt="screen shot 2018-08-28 at 10 03 22 pm" src="https://user-images.githubusercontent.com/13283316/44760846-af13c380-ab0e-11e8-9a64-8548e17b7c3b.png">

## Suggested Resolution
Fix broken link :)

**Comment by alexfornuto** [comment]
Thanks @cityofoaksdesign! I added a redirect for now, and made a PR to fix the link in the dashboard.
