### ISSUE TITLE
Platform Resources for Legacy Plans Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4042]
Re: [Platform Resources for Legacy Plans](https://pantheon.io/docs/platform-resources/)

Priority: Medium or Low

## Issue Description:
The alternative doc linked in the deprecated notice does not provide the same information for new plans. 
## Suggested Resolution
Refactor this page so that new plan resources are reflected - such as the redis cache size across performance plans. 

OR work to increase comprehensive coverage on the marketing comparison page: https://pantheon.io/plans/pricing-comparison

**Comment by alexfornuto** [comment]
Assigning to @EdwardAngert who is looking into adding additional information to the marketing page referenced. Once in place, we can point the deprecated note there and close.
