### ISSUE TITLE
New Doc Proposal 

### ISSUE THREAD

**Issue by netgenius** [pantheon-systems/documentation#4053]
Priority: Low

## Title

Drupal reCAPCHA module Invalid domain

## Description

Addresses *"ERROR for site owner: Invalid domain for site key"* error when using reCAPTCHA via the 
[reCAPTCHA module](https://www.drupal.org/project/recaptcha)

## Outline

This is for Drupal 7, same may or may not apply to Drupal 8.

Add to settings-php:

```
// Deactivate reCAPTCHA if we're not running on the live site - it doesn't work if the domain name is invalid. Message "ERROR for site owner: Invalid domain for site key" is displayed.
// This is needed because otherwise it's impossible to log in or submit any protected form.
if (defined('PANTHEON_ENVIRONMENT') && $_ENV['PANTHEON_ENVIRONMENT'] != 'live') {
  $conf['recaptcha_site_key'] = NULL;
}

```
## Expected Audience
Devs

## Path
docs/modules-plugins-known-issues/

**Comment by netgenius** [comment]
Now seen I need to read [contributing guidelines](https://github.com/pantheon-systems/documentation/blob/master/CONTRIBUTING.md) - will have to come back to that, too busy right now, sorry!

**Comment by alexfornuto** [comment]
@netgenius please help me understand. Are you proposing a new doc, or suggesting we add a module to the "Known Issues" doc? Of the latter, can you help me understand what the issue is with the module?
