### ISSUE TITLE
Starting With Git Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#4062]
Priority: Low

[Starting with Git](https://pantheon.io/docs/git/)

## Add instruction on how to mirror code repo to GitLab

GitLab supports repository mirroring but it does not seem to have an option to clone via SSH.

You can import and mirror the code repo via command line:

> 1. Grab the Pantheon Git clone URL and add the `--mirror` option
> Ex. `git clone --mirror ssh://codeserver.dev.xxx@codeserver.dev.xxx.drush.in:2222/~/repository.git my-site` 
> 2. cd my-site
> 3. git fetch
> 4. git push https://[...URL of new empty repo on GitLab] --mirror

The `--mirror` option maps all refs (including remote-tracking branches, notes etc.) as-is. All local references will be overwritten each time you fetch, so it will always be the same as the original repository.

## Expected Audience
Git Lab Users

**Comment by alexfornuto** [comment]
@rubelyn which doc do you want this information added to?

**Comment by alexfornuto** [comment]
@rubelyn I'm not sure where this information fits into the doc you referenced in the title (which I edited your description to link to) - this doc doesn't discuss working with mirrors of the repo on any third party git host.

Did you mean reference a different doc?

**Comment by rubelyn** [comment]
thanks @alexfornuto I agree. This does not seem fit. Maybe we can just add this link under Additional Resources -https://docs.gitlab.com/ee/workflow/repository_mirroring.html
