### ISSUE TITLE
Database Workflow Tool Doc Update 

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#4063]
Re: [Database Workflow Tool](https://pantheon.io/docs/database-workflow/)

Priority: Low

## Issue Description:
As per BUGS-901, sites with large databases can receive a timeout when trying to search and replace through all their tables. This is because we have a 10-minute idle timeout on SSH connections.

## Suggested Resolution
Document this problem under the troubleshooting section.

@joemiller recommends that customers put something like this into their `$HOME/.ssh/ssh_config` file before executing the 'terminus wp replace ..." command:

```
Host *.drush.in
  ServerAliveInterval 60
```
This should configure their ssh client to send an "ssh keepalive" packet every 60seconds.

Other ssh clients (such as Putty) also support these keepalive packets but are configured differently. For example, putty has a GUI config option for this.

**Comment by alexfornuto** [comment]
Awesome, thanks @sarahg!
