### ISSUE TITLE
Update the known defects article 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#407]
Story:
As a User/CSE I want A known defects article so that I know what bugs Pantheon is aware of, and known workarounds (and ETA for fix if it exists)

Defects that move through the bugs board and are accepted but not

From the [Bugs Sprintly Workflow](https://getpantheon.atlassian.net/wiki/display/VULCAN/Bugs+Workflow+in+Sprint.ly): 
Accepted bugs are then re-parented into the "Engineering" product, tagged with the appropriate team, and placed in Someday 
Known defects are rejected by a PM or Eng manager and tagged "known defect" if it's something that will not be fixed

I think that both should be accounted for in a known defects document with two sections (one ENG is working on, the other we're not addressing), or that Accepted bugs re-parented to engineering are added to "known defects article" while "known defects" are added to the existing "known limitations" article.

All entries should describe the problem, indicate what causes it, and provide workarounds.

Created by @bmackinney

**Comment by bmackinney** [comment]
This seems like it will be difficult to maintain. CSE please chime in if we want to have something to point users to, for "defects" outside of "limitations"

**Comment by ari-gold** [comment]
I think that sometimes it makes sense to communicate "known defects" that "we will not fix" publicly, but not sure it should be one long article. For example, if there's a known defect that CDE names are limited to 11 characters, then we can just note it in the article about Multidev, we don't need a separate article. Then if we decide to fix the defect maybe we can include that in the customer newsletter.

**Comment by nataliejeremy** [comment]
+1
