### ISSUE TITLE
Using SendGrid To Deliver Email Doc needs to be Updated 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4072]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs/guides/sendgrid/)

Priority: Medium

## Issue Description:
User reported that our docs is outdated on this part: https://pantheon.io/docs/guides/sendgrid/#create-a-sendgrid-account

We might also need to refer them to this doc https://sendgrid.com/docs/ui/account-and-settings/api-keys/ too.

Verified that there are some GUI and menu changes from Sendgrid which renders this doc outdated https://www.screencast.com/t/QaJcFhDJi

## Suggested Resolution
Revisit the docs and update the instructions and screenshots

**Comment by alexfornuto** [comment]
Based on the information provided, I believe this issue was resolved by #4208 

@carl-alberto if that's not the case, please open a new issue (or re-open this one) and provide *specifics* about what's out of date.
