### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by mcdwayne** [pantheon-systems/documentation#4077]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority (Low‚ Medium‚ High): Medium?

## Issue Description:
Some of our commands do not show, within the documentation, all the variables you can use
example: in `terminus connection:info field=<field> ` we do not know what fields are possible outside of Terminus' `--help`

## Suggested Resolution
After talking with @ataylorme at WordCamp Sacramento, we had the idea that it would be cool to link the commands on the Command List to the Help contents that appear if you run `terminus <command> -h` 

I have generated all of these help content files and am storing them here for now:
[https://github.com/mcdwayne/terminus-list-help-files](https://github.com/mcdwayne/terminus-list-help-files)

Solution would be to 
1) upload a copy of these files to the Pantheon Documents repo
2) link the individual command's name to the corresponding file.

Completely open to other approaches but we think this would be helpful and provide better help for users

**Comment by ataylorme** [comment]
We could have a docs page for the help of each command with just the help text in a code fence.

**Comment by alexfornuto** [comment]
The advantage of the current format of this page is that the data is populated during build from the output of the current version of Terminus, making it evergreen. If we were to implement a solution like this, we would need to make it update automatically to avoid regression.

**Comment by mcdwayne** [comment]
OK, then can we get the autogeneration to show all flags and options somewhere on the page or subsection? 
 
The specific case I have in mind is 
`terminus connection:info site.env --field=FIELD`
`FIELD` is defined in the `--help` for the command but not in the way we are presenting the documents.  

If I am a new user (who is the most likely person turning to the docs for help) especially if I am new to the command line (which is pretty much all WP users and a smaller fraction of Drupal)  I would never know these options exist.  We on DevRel explain this one to one enough that it should be reflect in the docs I feel.  

Here is the disconnect I am seeing: 

Docs:

connection:infoDisplays connection information for Git, SFTP, MySQL, and Redis. | connection:info [--format [FORMAT]] [--fields [FIELDS]] [--field [FIELD]] [--] <site>.<env>
-- | --

VS


Terminus  --help:

Usage:
  connection:info [options] [--] <site_env>
  connection:info <site>.<env> Displays connection information for <site>'s <env> environment.
  connection:info <site>.<env> --fields='git_*' Displays connection information fields related to Git for <site>'s <env> environment.

Arguments:
  site_env              Site & environment in the format `site-name.env`

Options:
      --format=FORMAT   Format the result data. Available formats: csv,json,list,php,print-r,string,table,tsv,var_dump,var_export,xml,yaml [default: "table"]
      --fields=FIELDS   Available fields: SFTP Command (sftp_command), SFTP Username (sftp_username), SFTP Host (sftp_host), SFTP Password (sftp_password), SFTP URL (sftp_url), Git Command (git_command), Git Username (git_username), Git Host (git_host), Git Port (git_port), Git URL (git_url), MySQL Command (mysql_command), MySQL Username (mysql_username), MySQL Host (mysql_host), MySQL Password (mysql_password), MySQL URL (mysql_url), MySQL Port (mysql_port), MySQL Database (mysql_database), Redis Command (redis_command), Redis Port (redis_port), Redis URL (redis_url), Redis Password (redis_password) [default: "*_command"]
      --field=FIELD     Select just one field, and force format to 'string'. [default: ""]
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -y, --yes             Answer all confirmations with "yes"
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Displays connection information for Git, SFTP, MySQL, and Redis.

**Comment by alexfornuto** [comment]
What I've discovered:

Output of `terminus $COMMAND --help` can be programmatically formatted and sorted with a one-liner like:  

```
terminus list --raw | grep -o '^\S*' | while read line; do printf "$line\n" && terminus $line --help && printf "\n\n"; done
```

What would be left to do is format the output into JSON so it could be read by the existing code that parses the output of `terminus list --format=json`. 

Currently seeking SMEs to help with formatting.

**Comment by ataylorme** [comment]
> What would be left to do is format the output into JSON 

@alexfornuto I think this may be tough for a few reasons.

1. The terminus commands, and their help text, contain symbols which are used to format JSON `:`, `[`, `]`, etc.
1. The help text output is multiple lines. I assume that is how we will want to display it to the user but storing it is JSON would mean stripping the newlines.

What if the build step write the contents of each help command to a separate `.txt` file, with the output as-is from Terminus help? I believe Angular can read text files.

**Comment by alexfornuto** [comment]
@ataylorme one iteration of my command above _did_ in fact put the output into separate files, but I'm trying to make this a drop-in replacement for `commands.json` since I don't know how to update the code that parses it, and the developer of that code is no longer on the project.

BUT

Thanks to @greg-1-anderson I now have a one-liner that will provide all the output in JSON:

```
terminus list --raw | grep -o '^\S*' | while read line; do terminus help $line --format=json >> source/docs/assets/terminus/help.json; done
```
What's missing is a way to programmatically add `{commands:[` to the front, `]}` to the end, and the unavoidable editing of [navbar.html](https://github.com/pantheon-systems/documentation/blob/master/source/_partials/navbar.html#L317-L388) to properly parse the new fields.

**Comment by alexfornuto** [comment]
BTW this issue is a continuation of a discussion started in #2844

**Comment by ataylorme** [comment]
@alexfornuto try this:

```bash
#!/bin/bash

# Name the output file
TERMINUS_HELP_FILE="source/docs/assets/terminus/help.json"

# Start an empty JSON array in the output file
echo '{commands:[' > $TERMINUS_HELP_FILE

# Loop through all Terminus commands
terminus list --raw | grep -o '^\S*' | while read TERMINUS_COMMAND; do
    # Skip any empty Terminus commands as the grep isn't perfect
    if [ -z "$TERMINUS_COMMAND" ]
    then
        continue
    fi

    # Let the user know we are still working
    echo -e "\nGenerating help text for the $TERMINUS_COMMAND command...\n"

    # Append the JSON of the help text for the current command to the output file
    terminus help $TERMINUS_COMMAND --format=json >> $TERMINUS_HELP_FILE

    # Append a comma to the output file
    echo ',' >> $TERMINUS_HELP_FILE
done

# Remove the trailing comma with sed as JSON is picky
echo $(sed '$! { P; D; }; s/.$//' $TERMINUS_HELP_FILE) > $TERMINUS_HELP_FILE

# End the JSON in the output file
echo ']}' >> $TERMINUS_HELP_FILE

echo -e "All done! Check out $TERMINUS_HELP_FILE"
```

**Comment by alexfornuto** [comment]
@ataylorme's script as well as @TeslaDethray's one liner:

`help=$(terminus list --raw | sed 's/ .*//' | while read line ; do $terminus_location $line --help --format=json && echo "," ; done) && echo "[${help%?}]"` 

both look good. Unfortunately I don't know what to do with the data once it's there. Angular JS is not something I know how to manipulate in this way.

I'm going to move forward on the changes made in #4408, but consider any discussion on leaving this issue open past its merge to continue improving this doc.

**Comment by TeslaDethray** [comment]
Whoops, I left a bit of localization in that one-liner:
`help=$(terminus list --raw | sed 's/ .*//' | while read line ; do terminus $line --help --format=json && echo "," ; done) && echo "[${help%?}]"`
