### ISSUE TITLE
Create Enterprise Change Management Doc

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#408]
Story:
As an Enterprise site user I want Change Management Documentation so that I can understand how roles/permissions work on my site. 

We documented generally for Agency organizations, and need to add a doc or refactor the CM docs to account for Enterprise CM at the site level.

Created by @bmackinney

**Comment by timani** [comment]
+1 to a more comprehensive section, not just one doc here and there. There are different cases for partners, resellers, enterprise orgs that are not accounted for that a section would help clarify.

**Comment by slivermon** [comment]
Some use case examples would be great too.

**Comment by bmackinney** [comment]
@nataliejeremy I'd like your opinion. Please comment.
It's important for our internal docs that we all understand the whole picture. Affected customers only need to understand what they can/can't do based on their type. @all Alternative proposals welcome.
## Organization Docs Structure Proposal

### Benefits
 - orgs who know their type can access docs specific to their use case. (This can be accomplished through separate docs or anchor tags)
 - Clear instructions for each use-case

### Drawbacks 
 - Redundant information in multiple docs

### Articles
- `/organizations/partners`
 - `/allies`
 - `/partners`
 - `/strategic`
 - `/oem`
 - `/resellers`
- `/organizations/enterprise`
 - `/contract-billing`
 - `/one`

### Sections
```
## Features
### Change Management (site-level as enterprise add-on, org-level as partner feature)
### Org Dash
### Multidev
### Supporting Orgs
## Roles and Permissions
### Administrators
### Team Member
### Developer
```

**Comment by bmackinney** [comment]
Also need either a section or a page for "Site ownership and support"

**Comment by nataliejeremy** [comment]
@bmackinney Yes, let's create articles for each specific user type. A section on site ownership is helpful and can link to this doc:https://pantheon.io/docs/articles/sites/new-site-owner/
