### ISSUE TITLE
Multidev Doc Update - Add in FAQ if multidev can be increased or not

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4102]
Re: [Multidev](https://pantheon.io/docs/multidev/)

Priority: Low

## Issue Description:
Possibility of adding multidev count can be increased or not

## Suggested Resolution
Add in the FAQ to answer this question: *Can I buy or request additional multidev from the default count?*

**Comment by alexfornuto** [comment]
@carl-alberto issue is incomplete without the answer.

**Comment by carl-alberto** [comment]
@alexfornuto I tried to ask around regarding this question but didn't get a definite response, not sure who can we ask around?
