### ISSUE TITLE
New FAQ for Pantheon Migration Plugin WP

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4103]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate/)

Priority: Low

## Suggested Resolution
Work with BlogVault and/or Ari to produce a new FAQ on the migrate doc page that discusses performance impact of running the migration plugin on a production site. 

For example, the following question was posed in the power users slack community: 
> Does running a migration on a wordpress website to pantheon using the plugin cause the live site to go down / experience any downtime?

I've had one client voice similar concerns, noting that they would not use it because they don't want to increase load on the production site. 

@lauren-kelly mentioned fielding concerns like this often with a +1 from @sarahg - seems worth having in the docs. 

@ari-gold provided [this page](https://blogvault.net/migration-using-blogvault-faq/), stating question 13 is related - might be a good starting point.

**Comment by sparklingrobots** [comment]
+1; I have seen questions like this in chat a few times.

**Comment by sewmyheadon** [comment]
For what it's worth, I +1 this too. As someone who has moved a lot of sites to Pantheon, I've never seen migration take an origin site down, but I have wondered about the performance impacts of the BlogVault plugin while the migration is running.
