### ISSUE TITLE
Update docs project to Terminus 1.9.0

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4105]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/updates/)

Priority (Low‚ Medium‚ High): Med - high

## Issue Description:
This page shows an out of date version for the current release, should be 1.9.0 - changelog is also missing as a result.

## Suggested Resolution
Update doc project's site local terminus version

**Comment by alexfornuto** [comment]
Updated in the Docker image file. Related to #4125
