### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by tenken** [pantheon-systems/documentation#4106]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: High

## Issue Description:

I reported this via the Support Chat today. On the listed page this section of the tutorial states:

```txt
git add .

git commit -m 'Drupal 8 and dependencies'

git push --force
```

followed by Drush commands to install a site. These commands will fail and visiting the site url, for example from a Pushed LANDO an installed copy of the site to DEV, will fail to show a site in the browser and the developer will encounter a message: A Site was not found on this project. Please commit your Code to the project.

The above error/issue is caused because upon Git commit the cloned example-drops-8-composer `patheon.yml` file has not been edited in any way and upon initial git commit the Platform does not know to affect the `web_docroot: true` policy onto the Site. So when loading the site in the browser, or issuing Drush commands the site appears misconfigured on the Platform.

## Suggested Resolution

In whatever recommendation you see as best -- revise the tutorial to note that you the developer should modify `pantheon.yml` with a newline, flip the php version in 2 commits from `7.1` and then back to `7.2` but ultimately the Platform must be provided with a `pantheon.yml` revision to assure `web_docroot` is enforced in the project structure.

Thank you for your consideration and saving future users ~1 hour of their development effort.

**Comment by alexfornuto** [comment]
@tenken thanks for reporting! I just ran through this guide again and found that Pantheon detected the changes to `pantheon.yml` without any additional steps:

```
$ git push --force
Counting objects: 25994, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (23877/23877), done.
Writing objects: 100% (25994/25994), 21.01 MiB | 2.86 MiB/s, done.
Total 25994 (delta 5030), reused 682 (delta 372)
remote: 
remote: PANTHEON NOTICE:
remote: 
remote: Changes to `pantheon.yml` detected.
remote: 
remote: Successfully applied `pantheon.yml` to the 'dev' environment.
remote: 
remote: 
To ssh://codeserver.dev.....drush.in:2222/~/repository.git
 + 3fe8ce4...b0b32c2 master -> master (forced update)
```

I wasn't able to try this with Lando, as I'm currently awaiting a resolution to a Terminus authentication issue with that tool.

@oseldman may reach out to you for further clarification.

**Comment by tenken** [comment]
Did you try to access the DEV site url in a browser after receiving that terminal meaasge?

**Comment by alexfornuto** [comment]
I _did_ have to switch to SFTP mode, as indicated by the error page:

```
Error: Unable to install Drupal 8 in Git mode.

Drupal 8 installation requires write access. Please change your connection mode to SFTP and try again.
```

I switched to SFTP mode to resolve that. I didn't get the sort of error you referenced.

**Comment by alexfornuto** [comment]
Closing the issue as could not replicate.
