### ISSUE TITLE
Document how to send HTTP headers that Varnish will care about 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#414]
Story: As a website developers I want to understand how to send HTTP headers that Varnish will care about so that I can control my websites cache behavior.

Right now we have people setting cookies as a way to prevent pages from being cached, which is bass-ackwards. We should start teaching people about HTTP headers and how to set them to control downstream caching.

Problem: I want to control cacheability and/or cache-lifetime on a per-page basis
Soution: get smart about how to use the internal page cache, and HTTP headers for downstream (varnish) caching
About HTTP headers
How/why to use both the internal page cache and the downstream page cache
Customizing cache lifetime
Preventing a single page from caching

--submitted by @joshkoenig

**Comment by bmackinney** [comment]
@nataliejeremy work with @timani to refine this issue and get it ready to write.

**Comment by timani** [comment]
I stumbled upon this and just adding as a note: 

https://www.fastly.com/blog/best-practices-for-using-the-vary-header

Maybe having settings.php or wp-config.php examples but it would require some testing.

**Comment by nataliejeremy** [comment]
@timani This is the one we're working on: https://github.com/pantheon-systems/documentation/pull/1079
