### ISSUE TITLE
Instructions on how to migrate a site to Pantheon 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#415]
Story:
As a user I want to know how to migrate my site to Pantheon so that I can go live on the platform faster

- [x] Migration for specific platforms (WordPress and Drupal), which cover the following: 
 - [x] Provide example for single file archive structure
 - [x] Provide example for code archive
 - [x] Single .sql file provided in archive
- [x] Restore migrating-sites.md - this will act as the landing page for a new Migration directory. Discuss migrations/imports at a highlevel in this doc - a user should see the full process in this single page. Link to edge cases with more details on export practices. 
- [x] Move all related import docs to the new Migration dir
- [x] Revise the Migrating Sites doc so that all import instructions are included - this will be the one import doc to rule them all. 

Created by @bmackinney

**Comment by rachelwhitton** [comment]
Suggestion from #620: 

1. Revise [Importing an Existing Site to Pantheon](https://pantheon.io/docs/articles/sites/create/importing-an-existing-site/) so that it only goes through Dashboard/Terminus import steps. (At this stage the user has an archive already created - beginning of the doc can link to CMS specific docs on generating archives)

2. Create separate and CMS specific docs for preparing sites for exports.

- This means [Importing an Existing Drupal Site to Pantheon](https://pantheon.io/docs/articles/drupal/importing-an-existing-drupal-site-to-pantheon/) would be renamed to **Prepare Drupal Site Exports** or something similar - in addition to being revised so that only prep instructions are present. 

- We would have to draft a WP specific export doc where manual instructions are provided. Currently we only have export instructions via plugins (e.g. duplicator).

**Comment by rachelwhitton** [comment]
# Current Migration/Import Documentation:
[Importing an Existing Site to Pantheon](https://pantheon.io/docs/articles/sites/create/importing-an-existing-site/)
[Importing a Large Site](https://pantheon.io/docs/articles/sites/create/importing-a-large-site/)
[How do I import a site with existing Git history?](https://pantheon.io/docs/articles/local/git-faq/#how-do-i-import-a-site-with-existing-git-history?)
[Cloning an Existing Site from a Dashboard Backup (Import your code/files/database section)](https://pantheon.io/docs/articles/sites/backups/cloning-an-existing-site-from-a-dashboard-backup/#import-your-code/files/database)
[Migrate Sites from Other Hosts](https://pantheon.io/docs/articles/sites/create/migrating-sites/)

## Drupal Specific
[Importing Drush Site Archives with Terminus](https://pantheon.io/docs/articles/sites/create/importing-drush-site-archives-with-terminus/)

## WordPress Specific
[Importing a WordPress Site](https://pantheon.io/docs/articles/wordpress/importing-a-wordpress-site/)
[Clone a WordPress site to Pantheon using Duplicator plugin](https://pantheon.io/docs/articles/wordpress/clone-a-wordpress-site-with-duplicator-plugin/)

**Comment by ttrowell** [comment]
One of the most prominent issues I see is that when people import sites, the existing site's archives of the database or the entire export is not done in a way that can be read by our importer.

I think the steps to creating the archives need to be more detailed and should include some way to test or verify the archive before they try using it.  (I don't know what the possibilities are on that one.)

**Comment by rachelwhitton** [comment]
@ttrowell - to my knowledge, the most effective way of testing an archive against our importer is to simply try it out. If the import fails there's a big error message on the dash. We could add something to the existing docs advising users to verify export methods and try again. Something like this:
>The following warning can appear on newly created sites where the import of your site archive failed: 
>![screen shot 2015-07-07 at 3 24 23 pm](https://cloud.githubusercontent.com/assets/10119525/8556374/46a3aa6c-24bc-11e5-8f4f-0b7338ea3c66.png)
>Verify the steps for preparing your WordPress or Drupal site for export and re-create the archive and import following the instructions above. 

Thoughts?

**Comment by rachelwhitton** [comment]
Include what a WP archive should contain and add terminus import instructions -
[Importing a WordPress Site](https://pantheon.io/docs/articles/wordpress/importing-a-wordpress-site/) perhaps
