### ISSUE TITLE
Drupal Commerce on Drupal 8 Doc Update - Add recommendation in creating new D8 site using Drupal 8 composer no CI 

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#4153]
Re: [Drupal Commerce on Drupal 8](https://pantheon.io/docs/guides/drupal-8-commerce/)

Priority: Low

## Issue Description:
Some of the customers don't want to implement build CI in their Drupal 8 commerce site.

## Suggested Resolution
Add alternative Drupal 8 installation with composer no CI https://pantheon.io/docs/guides/drupal-8-composer-no-ci/ under **Create a New Drupal 8 Site** section

**Comment by alexfornuto** [comment]
Since this guide expects CI and has instructions dependent on it, this is really a request for a new guide on Drupal Commerce on D8 Without CI

**Comment by umandalroald** [comment]
Hi @alexfornuto I can help creating a new guide for Drupal Commerce on D8 Without CI

**Comment by alexfornuto** [comment]
@umandalroald Excellent! I suggest you make a copy of the existing doc, renamed to a new file, and start editing from there to remove the CI steps. Don't worry about the copy, I can take care of that once you have the technical steps worked out.

**Comment by umandalroald** [comment]
will do @alexfornuto thank you for the suggestion.

**Comment by alexfornuto** [comment]
Closing this issue until such time as a PR is submitted. This issue has been noted in the [Multidev discussion](https://github.com/pantheon-systems/documentation/projects/12) project.

**Comment by alexfornuto** [comment]
https://github.com/pantheon-systems/documentation/projects/12
