### ISSUE TITLE
Caching: Advanced Topics Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4157]
Re: [Caching: Advanced Topics](https://pantheon.io/docs/caching-advanced-topics/)

Priority: Low

## Issue Description:
Indication in our doc that Varnish configuration (VCL) is not user editable and we don't provide the complete copy of that file. Related to internal ticket - 115663.

## Suggested Resolution
Pages in the doc that might have Varnish Configuration related contents
https://pantheon.io/docs/caching-advanced-topics/
https://pantheon.io/docs/platform-considerations/
https://pantheon.io/docs/cache-control/

**Comment by alexfornuto** [comment]
@carl-alberto you don't think this warning covers it?

![image](https://user-images.githubusercontent.com/2349184/46756302-bc36dd00-cc8c-11e8-8edf-e56fa386e0c9.png)

**Comment by carl-alberto** [comment]
@alex looks like it is and adding an indication that we do not provide the whole configuration file would improve it :)

Would it be discovered easily if every config file like the Varnish Config(.vcl) is in this doc along with nginx.conf? https://pantheon.io/docs/platform-considerations/#nginxconf

Then other docs that mentions Varnish Config like these:
https://pantheon.io/docs/cache-control/
https://pantheon.io/docs/caching-advanced-topics/
can reference to the new Varnish Configs that will be added in here https://pantheon.io/docs/platform-considerations/ ?

**Comment by alexfornuto** [comment]
We're going to close this issue, for the following reasons:

 - The warning I referenced already covers the big issue here
 - Regarding access to the VCL file, future product updates will likely negate the need for access.
