### ISSUE TITLE
Troubleshooting Migration issues

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#4165]
Re: [Major Version Drupal Upgrades](https://pantheon.io/docs/drupal-updates/)

Priority: Low

## Issue Description:
Ref: Ticket 116246

Customers sometimes encounter errors due to platform limits like Timeouts or Max Memory 

For such scenarios, it is possible to clone the target site locally and perform the migration there where they can overcome any limitations

## Suggested Resolution

Refer to Power Users
Add section about limits and resort to doing this locally

**Comment by alexfornuto** [comment]
>Refer to Power Users

What, the entire Slack channel? Please be more specific, or link to specific conversations.
