### ISSUE TITLE
Testing Global CDN Caching Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#4166]
Re: [Testing Global CDN Caching](https://pantheon.io/docs/test-global-cdn-caching/)

Priority: Med

## Issue Description:

Because testing via curl or browser requires multiple requests, would benefit from animated gif or short video

## Suggested Resolution

Include video or animated gif, maybe two, one that shows caching and one that shows it not caching

**Comment by alexfornuto** [comment]
A gif/video isn't very accessibility-friendly, but now that we've expanded our code blocks to use [line highlighting](https://pantheon.io/docs/style-guide#line-highlighting), we can do a better job of indicating the specific line we're looking at for the age change.
