### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update: iThemes Security (formerly Better WP Security)

### ISSUE THREAD

**Issue by ruthiehallarsis** [pantheon-systems/documentation#4187]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority: Low

## Issue Description:

https://wordpress.org/plugins/better-wp-security/
This plugin has a feature to protect the site from brute force attacks by writing "deny <IP>" to the *nginx.conf* file. But this will not work since nginx.conf file in the platform is non-configurable.

## Suggested Resolution

They can't use any feature of the plugin that requires modifying the nginx.conf file. But If they'd like to take action to remove this message about nginx.conf file:

"The file path supplied in NGINX Conf File is not writable. Please supply a file path that can be written to."

They can do so by going to the configuration page for the plugin

/wp-admin/admin.php?page=itsec&module_type=recommended

In the "Global Settings" block, click on "Configure settings" and scroll down to the field titled "NGINX Conf File". There you can enter a path that is writable.

You can use something like this:

/srv/bindings/---your-binding-id---/code/wp-content/uploads/nginx.conf

This will only make the message go away, but any feature of this plugin requiring modifying nginx.conf file will still not work.

Another suggestion is they can use third party services like cloudflare to block IPs. I believe they have something called CloudFlare firewall where you can whitelist/block some IPs. https://support.cloudflare.com/hc/en-us/articles/217074967-How-do-I-control-IP-access-to-my-site-

Related desk case: 117015

**Comment by ruthiehallarsis** [comment]
In the related ticket, the customer is saying that we are recommending this plugin from our site and from our live chat. 

I think he is referring to this page: https://pantheon.io/resources/quickstart-guide-wordpress-security

**Comment by byKamB** [comment]
Great

**Comment by byKamB** [comment]
DidYouUpLoad?

**Comment by alexfornuto** [comment]
Closed by #4364
