### ISSUE TITLE
New Doc Proposal - Solr SpellCheck component documentation

### ISSUE THREAD

**Issue by braican** [pantheon-systems/documentation#4188]
Priority: Medium

## Title

Solr SpellCheck component documentation

## Description

Address how the SpellCheck component is configured. Specifically looking for documentation around how to define the spellcheck index.

## Expected Audience

Developers using the Solr service either on a WordPress or Drupal site.

## Path
`source/docs/solr/spellcheck`

**Comment by dficker** [comment]
@braican Is this something you have implemented on a few sites? Or you're just interested in trying to implement this on sites?

If you have implemented it on a site, do you have an example of how it was implemented? Or could you provide some info on what you used to get us started on the documentation?

**Comment by braican** [comment]
@dficker No, I wasn't able to implement the SpellChecker component on the site I was working on. Partially due to the lack of documentation and the timeline we were on, we decided to forgo the SpellCheck component in favor of the NGramFilterFactory to handle some simple spell-checking capabilities.

**Comment by alexfornuto** [comment]
@braican thanks for the update. This hits on a case where we look to the documentation from the maintainers of the software in question (Solr) to [document](https://lucene.apache.org/solr/guide/6_6/spell-checking.html) their own features. If there is/was something Pantheon-specific that needed to be mentioned to make it compatible, that's what we would include in our repo.

I understand that you went in a different direction on this project, but with this framing in mind please feel free to continue making suggestions or edits to the Pantheon Docs. Thanks!
