### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#4191]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso/)

Priority: Medium

## Issue Description:
We are now recommending that WP sites utilize the OneLogin library bundled in with the wp-plugin.
See: https://github.com/pantheon-systems/wp-saml-auth#installation

## Suggested Resolution
Update this document to reflect the change

**Comment by sarahg** [comment]
This update could also close https://github.com/pantheon-systems/documentation/issues/4083.
