### ISSUE TITLE
Timeouts on Pantheon Doc Update 

### ISSUE THREAD

**Issue by calmher** [pantheon-systems/documentation#4195]
Re: [Timeouts on Pantheon](https://pantheon.io/docs/timeouts/)

Priority: Medium

## Issue Description:
This is for the section 'What if I run into a timeout when using the Drupal Migrate UI?' - the suggested config settings mentioned here indicating drush on the home directory doesn't work - 
$conf['migrate_drush_path'] = $_ENV['HOME'] . '/drush';

## Suggested Resolution
First step would be to take out the part where it mentions it - 
"You can also configure Migrate to trigger Drush imports from the UI by configuring the migrate_drush_path variable to:

$conf['migrate_drush_path'] = $_ENV['HOME'] . '/drush';"

Second, it would be good to find out the correct path to drush that can work for the Migrate module.

**Comment by alexfornuto** [comment]
Resolved by #4366
