### ISSUE TITLE
Mention possibility of using New Relic's Synthetics ping monitoring to hit cron 

### ISSUE THREAD

**Issue by obicke** [pantheon-systems/documentation#4205]
Priority: Medium

## Title
Using New Relic's Synthetics's Ping Monitoring to Trigger Cron URLs 

## Description
Describes benefits and process for configuring New Relic's Synthetics's ping monitoring to trigger cron URLs 

## Outline
* Describe how/why it can be useful to hit cron more than once per hour. 
* Mention something like, "while you can do this with services such as Pingdom, if you already have New Relic associated to your site, you can avoid setting up yet another third-party service.
* Describe how to configure New Relic's Synthetics's ping monitoring to trigger cron URLs:
** Go to New Relic
** Click on Synthetics tab
** Click on the button to add a monitor
** Select the Ping option (although there are other interesting ones there too)
** Add cron URL
** Select a region to hit it from
** Select the frequency
** optionally set up a notification email
** Click button to set it up. 
This is described in more detail here, but not specific to setting up cron jobs: https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/add-edit-monitors

* Mention how it would be preferable to use Elysia cron, or some other tool to break up the cron job so that some things are run more frequently than others.

## Expected Audience
* Everybody who would like to run cron more than once per hour and not have to setup yet another third party service.

## Path
TBD

**Comment by alexfornuto** [comment]
@obicke If the only reason to duplicate the information already provided by NR's documentation is to re-frame it in the context of hitting a cron endpoint, I think we're better served by the additions you made in #4207. That way we're not responsible for keeping documentation on someone else's product up to date, and can rely on existing information that's already well-defined, with a simple note on our docs saying "works for cron too, yo".

I'll leave this issue open for now and ask for some other opinions, but will likely consider this resolved when #4207 is merged.
