### ISSUE TITLE
WordPress Site Networks Doc Updates and clarifications

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4223]
Re: [WordPress Site Networks](https://pantheon.io/docs/guides/multisite/)

Priority: Low

## Issue Description:
- ~~Docs indicate to reach out with their account managers, how do non Pantheon customers or existing customers that don't have account managers avail WP multisites~~
- Unsupported Use Cases indicates WordPress Multi-Network installations, clarification regarding this will be appreciated by non technical people, if this pertains to multiple domains connected to a single wp site installation
- Composer based multisite seems to be a possibility in the platform so it is also good to indicate it here as what have Andrew suggested that onboarding managers could possible assist regarding that matter https://github.com/pantheon-systems/example-wordpress-composer/issues/67
- I also saw some people that try to attempt installing Bedrock + multisite https://roots.io/guides/laravel-valet-and-bedrock-multisite/, maybe a good idea to indicate that it wont work out of the box and its recommended to have a contract account and let onboarding managers assist them

## Suggested Resolution
None yet, but would love to help out in finding the right answers

**Comment by allenfear** [comment]
@carl-alberto customers should contact sales to learn more about purchasing a site network. Fixed in #4247.

**Comment by alexfornuto** [comment]
Marking as needs more info until we get answers to bullet points 2, & 3.
