### ISSUE TITLE
Local Development Doc Update that contains the content of wp-config-local.php

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4226]
Re: [Local Development](https://pantheon.io/docs/local-development/)

Priority: Low

## Issue Description:
There are no references on what to put in the the wp local config file wp-config-local.php

## Suggested Resolution
Haven't seen doc regarding the wp-config-local.php yet but the config outlined here seems to work fine https://github.com/pantheon-systems/WordPress/issues/178

**Comment by NeoMeteor** [comment]
Is this not the reference for that file: https://pantheon.io/docs/wp-config-php/#local-database-configuration-for-development
