### ISSUE TITLE
Restore breadcrumbs (requires parent article creation)

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#424]
The repo has a library called autobreadcrumbs.js which takes each directory in the path and turns it into a hyperlink, assuming there will be an article at that path. I disabled the feature before we deployed because not all of the parent articles exist. To re-enable breadcrumbs in this fashion, we will need to ensure that for each subdirectory `/name`, the parent directory must have an article `name.md`

- [ ] restore the library
- [ ] style the block
- [ ] deployment blocked by #423

**Comment by ari-gold** [comment]
Can this be closed?
