### ISSUE TITLE
WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#4241]
Re: [WordPress Site Networks](https://pantheon.io/docs/guides/multisite/)

Priority: Low

## Issue Description: 

-The doc does not have a link who to contact if user does not have a Pantheon account yet. Should they go to Sales? -https://pantheon.io/contact-us

This should be added to our doc to set customer expectations.

## Suggested Resolution

- Add links who to contact
- Add unsupported use-case

**Comment by alexfornuto** [comment]
>The vanilla upstream is known to work (unsupported) with subdomain-style site networks.

Can you provide some context / clarity for this line?

**Comment by rubelyn** [comment]
> > The vanilla upstream is known to work (unsupported) with subdomain-style site networks.
> 
> Can you provide some context / clarity for this line?

Hi @alexfornuto ,  I got that from our internal wiki -https://getpantheon.atlassian.net/wiki/spaces/VULCAN/pages/82247691/WordPress+Site+Networks.

We used to include in our doc before that WP SIte Network on Vanilla upstream is not supported -- I'm not sure why this was removed.
