### ISSUE TITLE
Platform Considerations Doc Update - Include node.js

### ISSUE THREAD

**Issue by ruthiehallarsis** [pantheon-systems/documentation#4242]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority: Low

## Issue Description: 

The only mention of node.js not being available in the platform is here: https://pantheon.io/docs/guides/trainers/#initial-setup

## Suggested Resolution

I think it would be nice to also include it in our Platform considerations page.

Related chat: `19518831986`

**Comment by alexfornuto** [comment]
So there's the catchall [here](https://pantheon.io/docs/platform-considerations/#general-php-framework-support):

>### General PHP Framework Support
>Pantheon does not currently support any PHP frameworks outside of Drupal and WordPress. The platform is only optimized for Drupal or WordPress and no others. Although PHP will run, we can not assist you in getting the non-approved frameworks running in any way.

And another [here](https://pantheon.io/docs/organization-faq/#can-we-run-our-joomla-magento-laravel-or-insert-other-php-framework-here):

>### Can we run our Joomla, Magento, Laravel, or (insert other PHP framework here)?
>No, we don’t support them.

Do you think we specifically need to reference Node.js? Is the referenced chat the only instance of people asking about this?

**Comment by ruthiehallarsis** [comment]
Hey @alexfornuto, I think we need to reference it. It's not the only chat we received for node.js inquiries. From time to time we do get some inquiries about node.js and i've tagged some of it on intercom as "node.js availability".

My suggestion would be something like this:

## Node.js 

Node.js is not available in the platform. If running node.js services is a hard requirement for your Drupal or Wordpress application, the node.js service needs to be hosted in a different remote server outside of Pantheon.

**Comment by alexfornuto** [comment]
Excellent copy suggestions @ruthiehallarsis, I used it almost verbatim in the PR.
