### ISSUE TITLE
Solr - Disable Schema Check

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4246]
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8/)

Priority: Low

## Issue Description
Copied from @ccjjmartin [here](https://github.com/pantheon-systems/documentation/pull/4235#issuecomment-437520375):

>While you are looking at this documentation not sure if it is worth it to add a note about disabling the schema verification check. I recently ran into issues (solr wasn't indexing at all) because the check was failing since we are posting the 4.x schema to a 3.x solr instance.

## Suggested Resolution
Test to confirm if schema verification check should be disabled.

**Comment by ccjjmartin** [comment]
@alexfornuto Backported the changes here: https://www.drupal.org/project/search_api_solr/issues/3037213#comment-12996162

Multidev here: http://dev-solr-schema-test.pantheonsite.io/admin/config/search/search-api/add-server

I assume you can add yourself to environments on Pantheon, if not I can add you.  In the screenshots below you will see the main changes are to force retrieving data from the solr server and to disable schema verification checks.

Before patch:
![screencapture-dev-solr-schema-test-pantheonsite-io-admin-config-search-search-api-add-server-2019-03-03-14_31_35](https://user-images.githubusercontent.com/12279982/53701369-195d3780-3dc2-11e9-8e0e-53568610eb01.png)

After patch:
![screencapture-dev-solr-schema-test-pantheonsite-io-admin-config-search-search-api-add-server-2019-03-03-14_34_18](https://user-images.githubusercontent.com/12279982/53701371-224e0900-3dc2-11e9-8f49-679d948fc259.png)

**Comment by alexfornuto** [comment]
@ccjjmartin Thanks for the additional information! Let's pretend that I'm a technical writer who's not familiar with using Solr in practice... yea, pretend.

In that situation, how would you summarize what information you think should be added/changed in this doc?
