### ISSUE TITLE
Quick Start Doc (Video) Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#4262]
Re: [Quick Start](https://pantheon.io/docs/guides/quickstart/user-dashboard/)

Priority: Low

## Issue Description:
The dashboard depicted in the "User Dashboard Overview" video shows the "Advanced" tab, which is no longer present on the dashboard. 

Additionally, the Glossary includes information on the "Advanced" tab.

## Suggested Resolution
Best resolution would be to re-record the video and update the glossary. 

A less time-intensive solution would be to update the glossary or otherwise provide text indicating that the "Advanced" tab no longer exists, with a link to the Terminus docs (e.g. https://pantheon.io/docs/terminus/).

**Comment by EdwardAngert** [comment]
thanks, @sparklingrobots!
I spoke with @davidneedham about getting the video adjusted to match the dashboard
