### ISSUE TITLE
Customer encountered error following Create a Custom Upstream Doc steps 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#4278]
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/)

Priority: Medium

## Issue Description:

When following the instructions to create a custom upstream, [customer reported an error](https://pantheon-community.slack.com/archives/C5EQAM15X/p1543338344016300) about unrelated histories when merging the Pantheon upstream.

## Suggested Resolution

Customer resolved problem by adding `--allow-unrelated-histories`.

I think it might be more straightforward to change the instructions to:
```
git pull pantheon-wordpress master
git push origin master
```
(Instead of `fetch` and `merge`.)

I didn't try this variation, though.

**Comment by alexfornuto** [comment]
I tried using the existing instructions, and the only error I got was trying to `checkout master` on the empty repo:

```
$ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
```

Waiting for more input from the original reporter over Slack.

**Comment by greg-1-anderson** [comment]
Maybe the reported checked the "create README" box when making their repository?

**Comment by alexfornuto** [comment]
Will resolve by adding a warning to the doc to not select any of the auto creation options from GitHub
