### ISSUE TITLE
January Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4279]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.4 
Update to Drupal 8.6.4. For more information, see https://www.drupal.org/project/drupal/releases/8.6.4

**Comment by pantheon-upstream** [comment]
### WordPress 5.0

**Comment by pantheon-upstream** [comment]
### WordPress 5.0

**Comment by pantheon-upstream** [comment]
### WordPress 5.0

**Comment by pantheon-upstream** [comment]
### WordPress 5.0.1

**Comment by alexfornuto** [comment]
## New Docs

### Site Disaster Recovery
A short, high-level overview of Disaster Recovery. #4230

### Add a Client to Your Agency
Everything a client and agency need in order to add a supporting organization, transfer ownership of a site, and get preferred pricing. All in one place. #4317

**Comment by pantheon-upstream** [comment]
### WordPress 5.0.2

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.5 
Update to Drupal 8.6.5. For more information, see https://www.drupal.org/project/drupal/releases/8.6.5

**Comment by alexfornuto** [comment]
Add new items to #4374
