### ISSUE TITLE
Multidev Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4289]
Re: [Multidev](https://pantheon.io/docs/multidev/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
> Unprivileged members of organizations can access, but not create Multidev environments. 

Unclear whether or not an unprivileged user can commit to Multidevs

## Suggested Resolution
Use more explicit language - "access" to what?

**Comment by alexfornuto** [comment]
@rachelwhitton would a link to [this table](https://pantheon.io/docs/change-management/#organizations-roles-and-permissions) address the concern?
