### ISSUE TITLE
Pricing Discrepancies: Website vs. Dashboard

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#4300]
Re: Website vs. Dashboard

Priority: High

## Issue Description
**The "List Price" options on the customer facing website are as follows**:
https://pantheon.io/plans/basic-pricing
https://pantheon.io/plans/performance-pricing
https://pantheon.io/plans/agency-preferred-pricing

- Basic list price = $41/mo
- Small list price = $160/mo
- Medium list price = $275/mo
- Large list price = $550/mo
- Extra Large list price = $687/mo

**However, the "List Price" options on the logged in user Dashboard are as follows**:

- Basic list price = $50 (_same for annually & monthly_)
- Small list price = $175 (_same for annually & monthly_)
- Medium list price = $300 (_same for annually & monthly_)
- Large list price = $600 (_same for annually & monthly_)
- Extra Large list price = $1,000 (_same for annually & monthly_)

### **Basic plan screenshots**:

<img width="296" alt="basic" src="https://user-images.githubusercontent.com/13283316/49547545-f994a100-f8b0-11e8-84d3-c4be0c190646.png">

<img width="730" alt="basic monthly" src="https://user-images.githubusercontent.com/13283316/49547523-e550a400-f8b0-11e8-8846-cfd1fb67e9d0.png">

<img width="729" alt="basic annually" src="https://user-images.githubusercontent.com/13283316/49547532-eda8df00-f8b0-11e8-9bc5-d2b3e75dd7ef.png">

### **Performance Plans screenshots:**

<img width="523" alt="performance" src="https://user-images.githubusercontent.com/13283316/49547581-0e713480-f8b1-11e8-82b4-6cc267d8bf8e.png">

<img width="764" alt="performance_monthly" src="https://user-images.githubusercontent.com/13283316/49547564-0618f980-f8b1-11e8-86dc-4a9be5cde23c.png">

<img width="742" alt="performance_annually" src="https://user-images.githubusercontent.com/13283316/49547572-0a451700-f8b1-11e8-9684-6f7eccf5f0da.png">

## Suggested Resolution
Update the pricing referenced in the Dashboard to align with the pricing listed on the customer facing website. For example, the "Performance" screenshot should say starting at $160/mo* (not $175/mo)
with the sentence underneath that says: > *All monthly pricing is listed at prepaid annual rate.

**Comment by alexfornuto** [comment]
Thanks for the detailed report @cityofoaksdesign! I'm alerting the relevant parties within Pantheon to get this sorted out.

**Comment by alexfornuto** [comment]
Tracking internally as `BUGS-2423`
