### ISSUE TITLE
Dashboard Available Add-Ons

### ISSUE THREAD

**Issue by cityofoaksdesign** [pantheon-systems/documentation#4319]
Re: Dashboard Available Add-Ons

Priority: Medium

## Issue Description
"Pantheon provides Apache Solr v3.6 as a service for most plans except the **Personal** plan."

## Suggested Resolution
Change Personal > Basic
"Pantheon provides Apache Solr v3.6 as a service for most plans except the **Basic** plan."

Additionally, it may also be important to add a similar sentence to the Redis add-on description (_at least for consistency_) which states: "Pantheon provides Redis as a service for most plans except the Basic plan. In other words, either state this plan fact for both Add-ons or neither add-on.

<img width="686" alt="screen shot 2018-12-12 at 10 15 39 pm" src="https://user-images.githubusercontent.com/13283316/49913434-916b2f80-fe5b-11e8-921d-52f8d2a452f8.png">

**Comment by alexfornuto** [comment]
@cityofoaksdesign where are you seeing the quoted sentence? I'm not finding it anywhere n the docs, and you haven't linked to a doc.

**Comment by cityofoaksdesign** [comment]
Hi Alex,

Sorry about that. It's actually not quoted in the docs, but in Dashboard UI for any site.
Site Dashboard > Settings > Add Ons modal window.

![screenshot_2018-12-27 abide pantheon dashboard](https://user-images.githubusercontent.com/13283316/50496868-30b62800-0a01-11e9-90b0-60fcee99816b.png)

**Comment by alexfornuto** [comment]
Thanks for the clarification. Continued in the appropriate repo.
