### ISSUE TITLE
Create a Drupal 8 Site From the Command Line Using Terminus and Drush Doc Update 

### ISSUE THREAD

**Issue by markely** [pantheon-systems/documentation#4330]
Re: [Create a Drupal 8 Site From the Command Line Using Terminus and Drush](https://pantheon.io/docs/guides/drupal8-commandline/)

Priority: Low

## Issue Description:
Under "Before You Begin" we need a fourth bullet that says "Ensure SSH key is loaded in local agent"

## Suggested Resolution
Add that bullet.  Possibly with a link to a doc that exists on how to do this.  (this n00b will just google it)

**Comment by alexfornuto** [comment]
@markely thanks for the issue! Hopefully #4331 resolves it to your satisfaction.
