### ISSUE TITLE
Rename "Add a Client to your Agency"

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4339]
Re: [Add a Client to Your Agency](https://pantheon.io/docs/add-bill-client/)

Priority: Low

## Issue Description
From internal:

> The doc called "Add a Client to your Agency" would have a more accurate reflection if it was called "Add a Client to your Agency Portfolio / Dashboard" or something like long those lines. 

## Suggested Resolution
Discuss new title and rename.

**Comment by alexfornuto** [comment]
Does @pantheon-systems/cse have any input on this?

**Comment by lauren-kelly** [comment]
It would really be "Add a client site to your agency dashboard" no?
They are not adding the client as a whole - just individual sites.

**Comment by alexfornuto** [comment]
@lauren-kelly on that point, wouldn't it technically be their "Organization Dashboard"?

**Comment by lauren-kelly** [comment]
Very true. The more consistent we can be, the less confusing it will be for users

**Comment by alexfornuto** [comment]
So far the front-runner name is:

##Add a Client to Your Organization Dashboard

**Comment by ccorpus** [comment]
I have never used the term "portfolio" with customers and I don't know of any @cse who has used the term as well. I think "Add a Client to your Agency Dashboard" would be good. For me personally, I always use "organization dashboard" instead of "agency dashboard".

**Comment by sparklingrobots** [comment]
I would recommend "Add a Client Site to Your Organization Dashboard", based on @lauren-kelly's initial point that they aren't actually adding the client, but rather individual client sites.

**Comment by sparklingrobots** [comment]
I don't ever use the term "portfolio" either, but it is all over the place in the partner program copy (see the Partner Program tab on any org dashboard for an example).  It would be nice if we could standardize on one concept (e.g. 'portfolio' vs 'dashboard') though that's likely a conversation beyond this issue.
