### ISSUE TITLE
Launch Essentials Doc Update 

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#4349]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/configure-dns/)

Priority: Low
## Issue Description:
Add advantages of adding two AAAA record and disadvantages when not added.

## Suggested Resolution
Create a section where it discusses the advantages of adding two AAAA record and disadvantages when not added.

**Comment by alexfornuto** [comment]
@umandalroald This issue is incomplete without explaining what those advantages are.

**Comment by carl-alberto** [comment]
@umandalroald it seems it is discussed here https://pantheon.io/docs/dns/#what-are-aaaa-records-and-do-i-need-them, would you agree in the PR that this page should be linked instead?

**Comment by umandalroald** [comment]
+1 Carl - I think that explains it.
