### ISSUE TITLE
solr doc - terminus command not working

### ISSUE THREAD

**Issue by hengkit** [pantheon-systems/documentation#435]
Set up a new D7 site with search_api_solr enabled for solr search.

Tried running the following drush command as per doc:
```
terminus drush --site=testbed-kit --env=dev vget search_api_solr_connection_class
Running drush vget search_api_solr_connection_class  on testbed-kit-dev
No matching variable found.                                              [error]
```

however, this works
```
terminus drush --site=testbed-kit --env=dev vget apachesolr_service_class
Running drush vget apachesolr_service_class  on testbed-kit-dev
apachesolr_service_class: PantheonApacheSolrService
```

contradicting the doc.

**Comment by bmackinney** [comment]
@hengkit It should depend on the site I believe. If you're not using search_api, then the search_api_solr_connection_class should not return anything, I believe. Perhaps someone in CSE can comment.
