### ISSUE TITLE
Configuring wp-config.php Doc Update to resolve WP_CONTENT_DIR not defined errors

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4352]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/)

Priority: Low

## Issue Description:
Some users reports that they are getting 
WP_CONTENT_DIR not defined error message

## Suggested Resolution
Add 

```
if ( ! defined( 'WP_CONTENT_DIR' ) ) {
define( 'WP_CONTENT_DIR', dirname( FILE ) . '/wp-content' );
}
```

**Comment by carl-alberto** [comment]
As far as I know, WP_CONTENT_DIR should be defined by default in WP, but to be safe, putting a define in the wp-config on the snippets that we suggest in this page would fix that as outlined in this pr https://github.com/pantheon-systems/documentation/pull/4353 @alexfornuto

**Comment by alexfornuto** [comment]
@carl-alberto This value is defined [here](https://github.com/pantheon-systems/WordPress/blob/master/wp-includes/default-constants.php#L66). In the cases where users are reporting `WP_CONTENT_DIR` not being defined, what's overriding it?

**Comment by alexfornuto** [comment]
I'm going to move this to consider while we wait for more information on the nature of the issue.

**Comment by carl-alberto** [comment]
This might be ok to close as I only encountered one issue on a WP composer based install, usually the solution for that error is easy to find via Google and not doc worthy be included
