### ISSUE TITLE
Network Solutions Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by karenpantheon** [pantheon-systems/documentation#4361]
Re: [Network Solutions Domain Configuration](https://pantheon.io/docs/network-solutions/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
A client of ours was following this doc, that "Network Solutions is not letting me add a CNAME for www, saying that an A record already exists for it… but that A record is now just "none.". But was able to add after waiting a couple of minutes, he may have added it too quickly. 

Reference: ticket 122482.

## Suggested Resolution
Suggest adding a line between the A record and CNAME record steps, by giving Network Solutions ~ 5 mins to process. Otherwise it will deny the CNAME.

**Comment by alexfornuto** [comment]
@karenpantheon has this happened to > 1 customers? Did he first create and then remove an A record for the domain `www`?

One person having one transient issue isn't validation for changing the docs.

**Comment by karenpantheon** [comment]
@alexfornuto Only 1 customer reported this so far. I am ok to close.
