### ISSUE TITLE
February Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4374]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
### WordPress 5.0.3

**Comment by greg-1-anderson** [comment]
PHP 7.2.14 and 7.1.26

Updated to PHP 7.2.14 and 7.1.26. For more information, see http://php.net/ChangeLog-7.php#7.2.14 and http://php.net/ChangeLog-7.php#7.1.26.

**Comment by ari-gold** [comment]
Note that we're explicitly not announcing an update to PHP 5.6 because it's EOL. /cc @greg-1-anderson

**Comment by greg-1-anderson** [comment]
php.net announced 5.6.40, so it seems appropriate that we should now as well; otherwise we'll probably get upgrade requests. I updated the changelog above.

**Comment by pantheon-upstream** [comment]
### Drupal 7.62 
Update to Drupal 7.62. For more information, see https://www.drupal.org/project/drupal/releases/7.62

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.6 
Update to Drupal 8.6.6. For more information, see https://www.drupal.org/project/drupal/releases/8.6.6

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.7 
Update to Drupal 8.6.7. For more information, see https://www.drupal.org/project/drupal/releases/8.6.7

**Comment by pantheon-upstream** [comment]
### Drupal 7.63 
Update to Drupal 7.63. For more information, see https://www.drupal.org/project/drupal/releases/7.63

**Comment by alexfornuto** [comment]
@ari-gold what's a good resource to link to for the "intl php extension"?

**Comment by ari-gold** [comment]
### New Relic PHP Agent Upgraded
New Relic has been upgraded platform-wide to version 8.5.0.235. For details see [New Relic's APM PHP Agent 8.50.236 release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-850235). Also see [Pantheon's New Relic documentation](https://pantheon.io/docs/new-relic/) for general info on using New Relic to monitor your site and identify opportunities to improve application performance.

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.8 
Update to Drupal 8.6.8. For more information, see https://www.drupal.org/project/drupal/releases/8.6.8

**Comment by pantheon-upstream** [comment]
### Drupal 7.64 
Update to Drupal 7.64. For more information, see https://www.drupal.org/project/drupal/releases/7.64

**Comment by alexfornuto** [comment]
Add new items to #4468
