### ISSUE TITLE
Configure Redirects Doc Update add mass 301 redirects

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4379]
Re: [Configure Redirects](https://pantheon.io/docs/redirects/)

Priority: Low

## Issue Description:
Got a few question in the past on how to effectively manage a couple of redirect from one url to another and point them here https://pantheon.io/docs/redirects/#redirect-one-path-to-another but seems to be hard to manage when redirect goes to 100+

## Suggested Resolution
Would it be helpful if this can be added in the redirect options? https://gist.github.com/carl-alberto/d72594f83884073c4af97e572bef7cc8

**Comment by alexfornuto** [comment]
@carl-alberto Maybe? Can you explain what that code snippet does, and how to customize it for the reader?

**Comment by carl-alberto** [comment]
@alexfornuto Added a PR to explain further what it does
