### ISSUE TITLE
Working with Cookies on Pantheon Doc - clarification re: size 

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#4381]
Re: [Working with Cookies on Pantheon](https://pantheon.io/docs/cookies/)

Priority: Low

## Issue Description:

California Closets had an issue during their launch prep with a large number of cookies, noted in this ticket: https://pantheon-systems.desk.com/agent/case/123584

"FYI, we proved that there is more to this than is mentioned in your documentation. The documentation only talks about cookies size in a request. It was happening for us even with no cookies at all in the request but with lots of set-cookie headers (some were duplicates) in the response. The cookies set in the response were all small so total size was not an issue. The problem was solved when we reduced the number of set-cookie headers in the response." 

## Suggested Resolution

Validate feedback and update docs to note that the number of set-cookie headers in the response might cause issues.

**Comment by alexfornuto** [comment]
@joshualieb can you break down what *exactly* is the issue here?
