### ISSUE TITLE
Clarify/unify the doc on how to transfer billing or ownership

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4387]
Re: [Add a Client Site to Your Organization Dashboard](https://pantheon.io/docs/add-client-site/)

Priority: Low

## Issue Description:
When using the keyword 'transfer billing' and 'transfer ownership', it returns a couple of different sources but with slightly different explanations:
1) https://pantheon.io/docs/site-billing/#transfer-ownership-and-billing-for-this-site
2) https://pantheon.io/docs/add-client-site/#send-an-invitation-to-pay-to-your-client
3) https://pantheon.io/docs/site-owner-faq/#can-i-transfer-ownership-of-a-site-to-someone-else

The 3rd one, seems to be the most recent and completely explains the process and limitations.

## Suggested Resolution
- Clarify/unify the doc on how to transfer billing or ownership
- Improve search result relevance for the keyword 'transfer billing' and 'transfer ownership'

**Comment by alexfornuto** [comment]
![image](https://user-images.githubusercontent.com/2349184/51002495-0aac7f80-14f9-11e9-9837-5308b2a5e857.png)

What are you talking about, Willis?

**Comment by carl-alberto** [comment]
Sorry about the lack of details, I have updated this issue to reflect a better context of the issue.
