### ISSUE TITLE
Add procedure to rebuild registry after "Failed to clear caches" error on clone

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#439]
Occasionally after cloning from one environment to another the drush command utilized by the clear_cache action fails due to inconsistencies in the Drupal registry. This leads to a WSOD which can be resolved by issuing a registry rebuild via ` terminus drush rr --site=site-name --env=env`.

**Comment by nataliejeremy** [comment]
@slashzero Are you referring to this article? https://pantheon.io/docs/articles/sites/create/importing-drush-site-archives-with-terminus/ 
If not, please let me know which one needs the update. Thanks!

**Comment by nataliejeremy** [comment]
@slashzero Are you referring to this doc? https://pantheon.io/docs/articles/sites/create/clone-a-drupal-site-using-drush/
