### ISSUE TITLE
Clarify "Site Dashboard" for frozen sites.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4418]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/#inactive-site-freezing)

Priority: Low

## Issue Description
From feedback

>I have a site frozen due to inactivity. You're instructing me to go to the site's dashboard and click "Unfreeze site." How can I possibly do that if I can't get to the site?

## Suggested Resolution
Make it ~even more~ obvious that we're referring to the Pantheon Site Dashboard.

**Comment by kiyaamodien** [comment]
Is it possible for me to unfreeze my website without the email, I had to create multiple websites with various email and cant seem to remember the email allocated with the website however I do remember the password.
