### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#4419]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Our other docs use {{terminus drush}} rather than {{terminus remote:drush}} as described here.

See: https://pantheon.io/docs/drush/ 

## Suggested Resolution
Standardize on one method to reduce customer confusion.  

I don't know if there's a difference. I assume not but I'm not confident enough to say for sure.

**Comment by alexfornuto** [comment]
@sparklingrobots `terminus drush` and `terminus wp` are aliases for `terminus remote:drush` and `terminus remote:wp`. We use them to be more succinct in the other docs.

This page is generated by the output of `terminus list`, so to change it here one would need to change the output provided by Terminus.

**Comment by sparklingrobots** [comment]
The more you know! Thanks for explaining, @alexfornuto!
