### ISSUE TITLE
Document styx-to-application-container encrpytion

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#443]
We are finishing rolling out encryption from styx to application containers.  This isn't something users can disable, but it could possible affect them.  Here's my high-level:

* Traffic in encrypted without our platform (it's still up to you to use SSL to our edge).
* You cannot access the containers directly (i.e. to the IP:PORT), either in a browser or in code

Bam!

@jerryblakley can help with details.

**Comment by nataliejeremy** [comment]
@nstielau Does this need a new doc or would updating this one work? https://pantheon.io/docs/articles/architecture/all-about-application-containers/

**Comment by nstielau** [comment]
No, but I think these two might want a touch-up.  I don’t think we need to
change anything, but might just want to add it there: “Oh, BTW, all traffic
within the pantheon infrastructure, from varnish to application containers,
is encrypted.

We might want an end-to-end encrpytion page, which could go under
CloudFlare, that david and Josh could help with.

https://pantheon.io/docs/articles/sites/domains/adding-a-ssl-certificate-for-secure-https-communication/
https://pantheon.io/docs/articles/sites/domains/developing-with-ssl/

On Fri, Apr 24, 2015 at 10:01 AM, Natalie Jeremy <notifications@github.com>
wrote:

> @nstielau <https://github.com/nstielau> Does this need a new doc or would
> updating this one work?
> https://pantheon.io/docs/articles/architecture/all-about-application-containers/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/documentation/issues/443#issuecomment-95992686>
> .
>



-- 
Nick Stielau
Director of Engineering
Pantheon Systems
