### ISSUE TITLE
Qualify "If a credit card is already associated with the site, site ownership can not be transferred"

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#4430]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/plans/)

Priority: High

## Issue Description:
"If a credit card is already associated with the site, site ownership can not be transferred."
This isn't clear and CSE is using this Doc to assist customer transfer _launched/live_ sites._ If the person transferring the site were to remove their payment method from a live site, the site would go offline. 

## Suggested Resolution
I think the context of the Doc is if there's a payment method associated with a _Sandbox_ site.

**Comment by EdwardAngert** [comment]
fixed with #4437
