### ISSUE TITLE
Multidev FAQ does not reflect the availability of Quicksilver hooks

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/documentation#4431]
Re: [Multidev FAQ](https://pantheon.io/docs/multidev-faq/)

Priority: Low

## Issue Description
The multidev FAQ doc has the following question and answer:

> Is there a public API available for post-commit hooks or other integrations with external project management systems?
> Not at this time, but it is on the development roadmap.

Quicksilver platform hooks, while not git post-commit hooks, can be used to integrate with external project management systems. It is especially relevant to this doc as there is a Quicksilver hood that runs on multidev creation.

## Suggested Resolution
Revise the post-commit question/answer to surface the availability of the multidev Quicksilver hook.

**Comment by alexfornuto** [comment]
@ataylorme does [this section](https://pantheon.io/docs/quicksilver/#hooks) of existing documentation on Quicksilver hooks contain enough information required to answer this Question?

In other words, would a link to that section suffice as resolution to this issue?

**Comment by ataylorme** [comment]
Yes, I think a link to the existing Quicksilver doc would suffice.
