### ISSUE TITLE
Resetting Passwords Doc Update

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#4432]
Re: [Resetting Passwords](https://pantheon.io/docs/resetting-passwords/)

Priority: Low

## Issue Description:
We provide Drush/WP-CLI commands for resetting Drupal/WP account passwords. These are the best option when users can use Terminus, but Windows users are often unable to run Terminus (and this is [unsupported](https://pantheon.io/docs/platform-considerations/#terminus-support)). Support cannot reset Drupal/WP passwords.

## Suggested Resolution
Provide the MySQL equivalent of the Drush/WP-CLI commands as an alternative to using Terminus.

**Comment by sarahg** [comment]
I wrote up the Drupal version of these directions [here](https://github.com/pantheon-systems/documentation/pull/4488/commits/9897551736922f497c05fbbc330b2223e0eeabd1). The WP one would be similar. As I did this I started thinking that this is maybe not a good recommendation for most people. @alexfornuto or @EdwardAngert do you have any opinion on this? 

My intent when I posted this issue was to provide an option for people who can't get Terminus installed (and can't get mail from their site, which is not uncommon if you don't follow our recommendations to offload outgoing mail delivery), but this mysql option is actually kind of hard to do unless you have a working local dev environment (and in that case you could likely get Terminus working).

Maybe we scrap this entirely, or link off to [WP](https://codex.wordpress.org/Resetting_Your_Password#Through_MySQL.2FMariaDB_Command_Line)/[Drupal](https://www.drupal.org/node/1023428) docs on this subject with a word of warning?

**Comment by alexfornuto** [comment]
@sarahg I agree that this is a dangerous area for us to go with our docs. I also agree that we can link off the WP / Drupal docs, since we should always opt to point to good documentation from the systems themselves instead of duplicating content.
