### ISSUE TITLE
Alternative PHP Cache doc update

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#4434]
Re: [What is APC and what is it used for?](https://pantheon.io/docs/alternative-php-cache/)

Priority: Low

## Issue Description
Guide talks about SHM size without any introduction.

## Suggested Resolution
Define SHM and its relationship to the steps described as well as what `shm_size` does.

**Comment by alexfornuto** [comment]
Closing as not required, link to definition provided in 2nd paragraph.
