### ISSUE TITLE
Update Fix Broken Links in Drupal to Drupal 8

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#4441]
Re: [Fix Broken Links in Drupal](https://pantheon.io/docs/drupal-broken-links/)

Priority: Low

## Issue Description
Steps are for Drupal 7

## Suggested Resolution
Add section or steps for Drupal 8

**Comment by SqyD** [comment]
I'm not sure if this issue even applies to Drupal 8. $base_url is gone from D8 and IIRC most content input methods generate relative URLs. The Pathologic module is in a pre-release for d8 and doesn't seems to be actively developed at the moment.

**Comment by NeoMeteor** [comment]
As explained above: https://x-team.com/blog/base_url-drupal-8/

**Comment by alexfornuto** [comment]
The steps that are D7 specific are labeled as such. The first section is version agnostic. There is no issue here.
