### ISSUE TITLE
March Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4468]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by alexfornuto** [comment]
From the previous issue:

https://github.com/pantheon-systems/documentation/issues/4374#issuecomment-461125888

https://github.com/pantheon-systems/documentation/issues/4374#issuecomment-461539877

https://github.com/pantheon-systems/documentation/issues/4374#issuecomment-461573718

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.9 
Update to Drupal 8.6.9. For more information, see https://www.drupal.org/project/drupal/releases/8.6.9

**Comment by ari-gold** [comment]
### WordPress Launch Check Shows Vulnerability Info
A fix has been deployed for WordPress Launch Check and the Pantheon site dashboard "Status" tab now accurately reports plugin vulnerabilities.

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.10 
Update to Drupal 8.6.10. For more information, see https://www.drupal.org/project/drupal/releases/8.6.10

**Comment by pantheon-upstream** [comment]
### WordPress 5.1

**Comment by alexfornuto** [comment]
Add new items to #4532
