### ISSUE TITLE
Configuring wp-config.php Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#4479]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/)

Priority: Medium

## Issue Description:
For cases where we will add a filter or action on the wp-config.php file, WP CLI will fail as the functions are not available before WP bootstrap

## Suggested Resolution

Consider moving the filters to the theme functions.php
Alternatively, add a conditional to exclude these filters during CLI runs

```
if (isset($_ENV['PANTHEON_ENVIRONMENT']) && php_sapi_name() != 'cli') {
   // Add your filters here
}
```

**Comment by alexfornuto** [comment]
@eabquina Can you be more specific about what sections of the doc need this addition?

**Comment by eabquina** [comment]
@alexfornuto This is for the wp-config-php docs page

**Comment by alexfornuto** [comment]
Closing to consolidate with #4658. Thanks @eabquina!
