### ISSUE TITLE
Modules and Plugins with Known Issues - Additional issue for Contact form 7

### ISSUE THREAD

**Issue by ruthiehallarsis** [pantheon-systems/documentation#4487]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority: Medium

## Issue Description:

Issue 2: This plugin has a file attachment field in it's settings which has some issues in the platform when specifying a file URL that is existing inside the wp-content/uploads folder. https://contactform7.com/file-uploading-and-attachment/ 

The wp-content/uploads folder in the platform is symlinked to the /files folder. This plugin’s file attachment field doesn’t seem to accept symlinked paths.

Related ticket: 126521
Related chat: 20808629438

## Suggested Resolution

Move your file attachment anywhere inside the wp-content folder other than the uploads folder. 

If you have this file wp-content/uploads/2019/01/attachment.pdf - this will not work since it’s inside the uploads folder.

You can move it to wp-content/attachment.pdf or wp-content/another-folder/attachment.pdf to make it work. No need to specify "wp-content" in the file attachment field since this field already expects the file to be inside the wp-content folder. So in the file attachment field, you can specify there "attachment.pdf" or "another-folder/attachment.pdf" directly.

Since the file attachment needs to be outside the wp-content/uploads folder, they may need to do this on dev first and commit the file there and then deploy to test and live. They can't do this on test and live since test and live are non-writable.

**Comment by alexfornuto** [comment]
@ruthiehallarsis I don't understand how committing into the codebase an attachment file that's not writable in Live will help users of the form upload their own files. Can you please clarify?

**Comment by ruthiehallarsis** [comment]
Hey @alexfornuto the file attachments getting uploaded and sent by form submitters are okay and working well. 

Contact Form 7 has this feature that can let admins of the site add a default file attachment that gets sent too along with the file attachments uploaded by form submitters. This default file attachment needs to be anywhere inside the wp-content folder. Admins need to specify the default file attachment path URL into the configuration page of the plugin.

The issue is, if the file is inside the wp-content/uploads folder, the plugins's config wont save and will have an error that the file doesnt exist, where in fact it does. But when i moved the file outside the uploads folder, it works and the default file gets submitted too. 

Let me know if you need further explanation.

**Comment by alexfornuto** [comment]
Thanks for the additional context @ruthiehallarsis! I now understand the issue being presented.

In the docs you linked to, it provides an example with thte "Local File" living in uploads. As you pointed out, the plugin assumes a path starting `wp-content`, so I wonder if there's an issue there where we were testing the path as `wp-content/uploads/` and not `/uploads/`. 

Did you encounter this only on a customer's configuration, or did you verify on a sanitized test environment?

**Comment by ruthiehallarsis** [comment]
Hi @alexfornuto, i've tested this out with a test site, and it's indeed happening to it too. 

http://dev-wpcf7.pantheonsite.io/wp-admin/admin.php?page=wpcf7&post=5&action=edit

I uploaded attachment.txt to several places: wp-content/ , wp-content/plugins/, wp-content/uploads/.

These values doesn't work:

<img width="598" alt="wp-content" src="https://user-images.githubusercontent.com/38076987/52932297-39383880-338a-11e9-8441-bc219b712cab.png">
<img width="599" alt="wp-content1" src="https://user-images.githubusercontent.com/38076987/52932303-3ccbbf80-338a-11e9-94c9-89d29e1f41e3.png">
<img width="625" alt="wp-content-uploads" src="https://user-images.githubusercontent.com/38076987/52932307-41907380-338a-11e9-9b3b-780eda7dc291.png">
<img width="630" alt="wp-content-uploads-1" src="https://user-images.githubusercontent.com/38076987/52932313-4523fa80-338a-11e9-9a4f-f9d452bd05cd.png">
<img width="561" alt="uploads" src="https://user-images.githubusercontent.com/38076987/52932318-48b78180-338a-11e9-86f7-748c64b311db.png">
<img width="565" alt="uploads-1" src="https://user-images.githubusercontent.com/38076987/52932325-4bb27200-338a-11e9-8a5e-bc682fd671ab.png">
<img width="868" alt="url-https" src="https://user-images.githubusercontent.com/38076987/52932418-98964880-338a-11e9-8421-a08ac59354df.png">
<img width="828" alt="url" src="https://user-images.githubusercontent.com/38076987/52932419-9c29cf80-338a-11e9-9d26-bfd01a912ccc.png">

But these values work and the form settings gets saved:

<img width="404" alt="attachment" src="https://user-images.githubusercontent.com/38076987/52932424-a0ee8380-338a-11e9-9f30-fd368a95f81d.png">
<img width="400" alt="plugins" src="https://user-images.githubusercontent.com/38076987/52932434-a946be80-338a-11e9-98d5-aefff87d512e.png">

i've tested this out too with another site that i have integrated with sendgrid so it will actually send the email with the attachment, and it worked on dev, test as well as live when the file is not inside the wp-content/uploads folder.

**Comment by ruthiehallarsis** [comment]
Also, @carl-alberto just submit an issue about this to the plugin developer:

https://wordpress.org/support/topic/local-file-attachments-do-not-work-in-pantheon-hosting/
