### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update (Invalid Order)

### ISSUE THREAD

**Issue by slavafomin** [pantheon-systems/documentation#4494]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot/)

Priority: High

## Issue Description:

The command mentioned in the documentation to move WordPress files is incorrect:
`git mv -k $(find . -type f -maxdepth 1  | grep -v pantheon.yml) wp-includes wp-content wp-admin ./*.php web`

It throws the following error in Ubuntu 18.10:

`find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.`

## Suggested Resolution

Replace `find . -type f -maxdepth 1` with `find . -maxdepth 1 -type f`. The `maxdepth` should come before the `type`.

**Comment by alexfornuto** [comment]
Right you are @slavafomin! I'll get this fixed in a ~giffy~... in a ~giphy~... in a ~jiffy~... I'll fix this right away.
