### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update (Too Greedy)

### ISSUE THREAD

**Issue by slavafomin** [pantheon-systems/documentation#4495]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot/)

Priority: High

## Issue Description:

The command suggested to move WordPress files is too greedy:
`git mv -k $(find . -type f -maxdepth 1  | grep -v pantheon.yml) wp-includes wp-content wp-admin ./*.php web`

It will move not only file, required by WordPress, but it will move everything in the root directory, which is almost always is a bad idea. Because it will move `pantheon.upstream.yml`, `.gitignore`, `README.md` and others.

## Suggested Resolution

The much better idea would be to copy only required files, using a less greedy approach: `git mv -k ./wp-includes ./wp-content ./wp-admin ./*.php ./license.txt ./readme.html ./web`.

**Comment by alexfornuto** [comment]
Thanks @slavafomin! We discussed internally and decided to add the files you referenced as not wantint to move to the `grep` Filter. PR incoming!
