### ISSUE TITLE
New Doc Edit Proposal -Email

### ISSUE THREAD

**Issue by macronomicus** [pantheon-systems/documentation#4496]
Priority: Low

## Title
Email on Pantheon

## Description
Page about SMTP services

## Outline - Add Additional Info
Add a couple more popular services.
Theres Amazon SES and Sendinblue both are the cheapest and come with the most for the free plan.  Which might be of more interest to the lower traffic sites.  Sendinblue even has drupal and wordpress plugins too.

https://www.sendinblue.com

## Path
https://pantheon.io/docs/email/

PS: it'd be nice for you to add this service yourselves if you can some day, free for basic use then some premium options perhaps for more?  Just a suggestion, not a demand, I know email is a PITA! lol

**Comment by alexfornuto** [comment]
This is interesting. We'd be interested in contributions from those using these services on how they configured it, and possibly work with Customer Success Managers to identify customers that can verify the proposals.

**Comment by carolyn-shannon** [comment]
Asking in the support channel.

**Comment by alexfornuto** [comment]
Closing do to lack of SME activity.
