### ISSUE TITLE
Delete Launching a WordPress Site?

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#4503]
Re: [Launching a WordPress Site](https://pantheon.io/docs/launch-wordpress/)

Priority: Low

## Issue Description
Doc has content better covered by other docs. Delete?

## Suggested Resolution
Delete

**Comment by alexfornuto** [comment]
@EdwardAngert which other docs?

**Comment by alexfornuto** [comment]
Will remove and redirect to Quick Start Guide, while updating the quickstart intro description to include WP and Drupal.
