### ISSUE TITLE
Delete WinSCP guide?

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#4504]
Re: [Using WinSCP on Pantheon](https://pantheon.io/docs/winscp/)

Priority: Low

## Issue Description
Guide is a how to install for a Windows app. Better covered by [their own docs](https://winscp.net/eng/docs/installation)

## Suggested Resolution
Delete

**Comment by alexfornuto** [comment]
If deleted, our standard SCP/rsync/etc docs should link to said external docs.
