### ISSUE TITLE
Drupal 8 and Composer (no CI) uses Multidev

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#4505]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description
Guide references using Multidev. Is it possible to keep the guide without the Multidev steps, or does the doc need overhaul?

**Comment by alexfornuto** [comment]
cc @ataylorme @mcdwayne @davidneedham

**Comment by davidneedham** [comment]
@alexfornuto @EdwardAngert this could totally work without Multidev, but I don't think that'd be a best practice. Perhaps we could simply add a note explaining this around "Adding a New Module with Composer" and leave the rest as it is?
