### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site Doc Update – composer require fails

### ISSUE THREAD

**Issue by zserno** [pantheon-systems/documentation#4517]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert/)

Priority: Medium

## Issue Description:
This guide tells me to add existing contrib modules to the new codebase using the composer require command. However when I try to run this command with `drupal/admin_toolbar` on a fresh `pantheon-systems/example-drops-8-composer` project, I get the following errors from composer:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package drush-ops/behat-drush-endpoint (locked at 0.0.5, required as ^8) is satisfiable by drush-ops/behat-drush-endpoint[0.0.5] but these conflict with your requirements or minimum-stability.
> 
> 
> Installation failed, reverting ./composer.json to its original content.

### Steps to reproduce

1. `composer create-project pantheon-systems/example-drops-8-composer pantheon-composer`
2. `cd pantheon-composer`
3. `composer require drupal/admin_toolbar`

## Suggested Resolution
After removing the composer.lock file and the vendor folder, composer require runs successfully.

**Comment by alexfornuto** [comment]
CC @dustinleblanc (I know you're in Lando land now, but I'd appreciate your input none-the-less).

**Comment by pirog** [comment]
Coincidently enough re: Lando @alexfornuto I also ran into this with same steps to replicate as @zserno except with my `3` being `composer require "drupal/search_api_pantheon ~1.0" --prefer-dist`

I was able to resolve with 

```bash
composer update
composer require "drupal/search_api_pantheon ~1.0" --prefer-dist
```

**Comment by richyumul** [comment]
Running 'composer update' cleared out this issue for me.

**Comment by dustinleblanc** [comment]
Sounds like the doc just needs a general warning about how version compatibility issues can come up and either a link to an externally documented work around or tell folks to update dependencies. It sounds like the issue here is just with version constraints between different package versions

**Comment by annstringer** [comment]
In composer.json

under minimum stability

changing:  "alpha" to "dev"

worked for me.

**Comment by alexfornuto** [comment]
The stem of this issue (as well as #3890) was an update to the `example-drop-8-composer` project that updated `drush-ops/behat-drush-endpoint` in composer.json but not in composer.lock. https://github.com/pantheon-systems/example-drops-8-composer/pull/187 will resolve the issue, and #4533 will be amended to mention `composer update` as a first troubleshooting step.

**Comment by alexfornuto** [comment]
Closed by https://github.com/pantheon-systems/example-drops-8-composer/pull/187
