### ISSUE TITLE
Custom Certificates on Pantheon's Global CDN Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#4518]
Re: [Custom Certificates on Pantheon's Global CDN](https://pantheon.io/docs/custom-certificates/#how-do-i-renew-my-custom-certificate)

Priority: Low

## Issue Description:
Our docs suggest that we will file a proactive ticket before the custom cert expires.  Per discussion in Slack, I don't believe that process is still happening. 

https://pantheon.slack.com/archives/C0ACN422E/p1550860502147400

## Suggested Resolution

Review with @ari-gold to see if this process is still happening. 
If yes, can we add a timeline (e.g. we will send the proactive ticket X days before expiry)? Don't want to add undue burden on whoever would be handling that, but it would set expectations more clearly. 
Update docs accordingly.

**Comment by alexfornuto** [comment]
Confirmed that the existing documentation is correct, and we do indeed file proactive tickets.
