### ISSUE TITLE
April Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4532]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by pantheon-upstream** [comment]
### WordPress 5.1.1

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.11 
Update to Drupal 8.6.11. For more information, see https://www.drupal.org/project/drupal/releases/8.6.11

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.12 
Update to Drupal 8.6.12. For more information, see https://www.drupal.org/project/drupal/releases/8.6.12

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.13 
Update to Drupal 8.6.13. For more information, see https://www.drupal.org/project/drupal/releases/8.6.13

**Comment by pantheon-upstream** [comment]
### Drupal 7.65 
Update to Drupal 7.65. For more information, see https://www.drupal.org/project/drupal/releases/7.65

**Comment by pantheon-upstream** [comment]
### Drupal 7.65 
Update to Drupal 7.65. For more information, see https://www.drupal.org/project/drupal/releases/7.65

**Comment by pantheon-upstream** [comment]
### Drupal 7.65 
Update to Drupal 7.65. For more information, see https://www.drupal.org/project/drupal/releases/7.65

**Comment by alexfornuto** [comment]
Add new items to #4641
