### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update – pantheon.upstream.yml file is not moved under web folder

### ISSUE THREAD

**Issue by zserno** [pantheon-systems/documentation#4537]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot/)

Priority: Medium

## Issue Description:
After enabling Nested Docroot, I followed the steps for converting an existing site. However the git mv command moved my _pantheon.upstream.yml_ file under the web subdirectory as well.

## Suggested Resolution

I believe the git mv command has a typo in the egrep -v part and it should be `pantheon.upstream.yml` instead of `pantheon-upstream.yml`. 

So the final command would look like this:

```sh
git mv -k $(find . -maxdepth 1 -type f | egrep -v 'pantheon.yml|.gitignore|README.md|pantheon.upstream.yml') core drush modules profiles sites themes vendor index.php web
```

**Comment by alexfornuto** [comment]
@zserno Whoops! That's my bad. I recently updated that code snippet. Thanks for reporting!

**Comment by zserno** [comment]
Thanks a lot, that's what I call excellent support service! 👍  :)
