### ISSUE TITLE
New guide: Essential Developer Training

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#4554]
Priority: Medium

## Issue Description
The DevRel team is creating a new guide for our live Essential Developer Training. We've recorded video for each of our topics and we're creating new sections for the video + resources that cross-reference other docs pages.

Video recording is done. Editing is in process, but almost done. We're drafting the list of resources to include in the text along with the video and expect to have it done this week.

## Suggested Resolution
DevRel team will create a PR with text to put on the distinct pages of the new EDT guide.

**Comment by alexfornuto** [comment]
Resolved by #4610
