### ISSUE TITLE
EDU Organization content

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#4560]
Priority: Low

## Title
EDU Organizations

## Description
EDU org description and features 

## Outline
- Site Ownership
- _Site Owners_ listed on the Site Dashboard are called _Users in Charge_ on the Org Dashboard—perhaps a FEAT to get the Org Dash to say "Owners" like agencies is in order. 
- Associate site with org via Supporting Org to get site to show up on org Dashboard

## Expected Audience
- CSE
- EDU org admins

## Path
https://pantheon.io/docs/organizations/#edu-organization

**Comment by alexfornuto** [comment]
We're going to look at this holistically with #3792 and determine if there is a need for a specific edu orgs page covering:

 - The differences in org structure
 - The content in the page referenced in #3792

**Comment by thomas-thackery** [comment]
![image](https://user-images.githubusercontent.com/536441/69193032-bdb31580-0ada-11ea-9b0c-0481ed5a52a5.png)
