### ISSUE TITLE
Gitlab upstream docs didn't work; chat rep was able to add using deploy token but not API key

### ISSUE THREAD

**Issue by ahebrank** [pantheon-systems/documentation#4562]
Re: https://pantheon.io/docs/create-custom-upstream/

Related to  #3492

Priority: Low

## Issue Description

When trying to add a Gitlab upstream by the recommended method (create a new user with reporter permission, create an OAuth access token, chat support with credentials), custom support was unable to access repo. We tried a Gitlab deploy token instead, which uses HTTP basic auth to access a private repo and it worked fine.

If there's no reason to use the API, it's much easier (and more secure) for Gitlab maintainers to create deploy tokens to provide Pantheon access to repos.

## Suggested Resolution

PR incoming to update docs.

**Comment by ahebrank** [comment]
Here's an edited chat transcript.

--------

let me know what you need -- i've got a Gitlab user set up

👍
The repo link and the authentication details, Andy.
Much better if we can use OAuth token.

ok, repo is https://gitlab.com/PATH/TO/REPO.git
user ID is XXXXXXXX, token is YYYYYYYYYYYYY [this was a new reporter-level user added to the project and the Gitlab API-score token]

What would be the upstream name?

let's do "New Upstream"

Can I try creating a new test site to make sure that the setup is correct?

sure

It failed, Andy. Can we confirm that this token is correct YYYYYYYYYYYYY?

YYYYYYYYYYYYY
looks right

Can we try username and password?

do you just need a public git URL?
cause i can use a deploy token for that, if you just need HTTP auth
gitlab+deploy-token-ZZZZZ / AAAAAAAAAAAAAAA

I think a username and password for a reporter account. But let me check the current token as well. 

try using the above as a username / password combo
it's not an oauth token

gitlab+deploy-token-ZZZZZ:AAAAAAAAAAAAAAA to be exact, correct?

yeah

On progress now.

ok, great
is there any advantage to using the API, or can I do a PR to your documentation, since the deploy tokens are way easier than making a new user

I can think you can create a suggestion in the doc. That would help others too, Andy.
Ok all good, Andy.

**Comment by ahebrank** [comment]
Thanks! Now who do I talk about making this a self-service feature :)

**Comment by alexfornuto** [comment]
huh?

**Comment by ahebrank** [comment]
It's not a docs issue, but it'd be great to be able to specify the repo from the dashboard without contacting support.

**Comment by alexfornuto** [comment]
OIC - Yes, that would be a great feature. I'll make sure your feedback gets seen by the right people.
