### ISSUE TITLE
Inconsistency in use of isset($_ENV) and defined.

### ISSUE THREAD

**Issue by kporras07** [pantheon-systems/documentation#4568]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis/)
Re: [Switching Sites from HTTP to HTTPS](https://pantheon.io/docs/http-to-https/)

Priority: Low

## Issue Description:
- In switching sites docs (https://pantheon.io/docs/http-to-https/#d8) d8 conditional reads `if (isset($_ENV['PANTHEON_ENVIRONMENT']) && php_sapi_name() != 'cli') {` as if there is a need to exclude cli when using isset($_ENV); however, in Redis docs (https://pantheon.io/docs/redis/#no-keys-found) using same isset($_ENV) says "The preceding conditional will only evaluate as true if the application in the Live environment is being invoked through a web visitor, but not via command line PHP." and so it recommends using `if (defined('PANTHEON_ENVIRONMENT')) {`

Given that; I'm not sure which docs is right or if I'm misunderstanding something

## Suggested Resolution
- Make docs clearer :)

**Comment by enotick** [comment]
It looks like both docs are correct from my point of view. The key point from my understanding is here:

_However, all redirection logic should remain nested in isset($_ENV['PANTHEON_ENVIRONMENT']) conditionals, as you only want redirections to occur on web visits, not any Drush invocations._
So the `if (defined('PANTHEON_ENVIRONMENT')) {` part is used for cache logic so it is invoked both in web and cli, but redirects need to only work in web therefore there is a difference in the documentation.
Hope I understood your question correctly. :)

**Comment by ccjjmartin** [comment]
@kporras07 There is actually three methods and there is some documentation to help make it clear here: https://pantheon.io/docs/settings-php/#how-can-i-write-logic-based-on-the-pantheon-server-environment

If you still have questions that is likely the place to fix the docs.

**Comment by alexfornuto** [comment]
Based on the conversation above, it sounds like we can close this issue. @kporras07 would you agree, or do you still have questions?

**Comment by kporras07** [comment]
I think it's ok. Closing.

Thank you very much!
