### ISSUE TITLE
Create a Custom Upstream Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#4581]
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/)

Priority: Low

## Issue Description:

The Site Dashboard is unable to detect custom upstream updates from GitLab repo using deploy token. The site can be deployed but it cannot pull updates from the custom upstream.

> Deploy tokens allow to download (through git clone), or read the container registry images of a project without the need of having a user and a password.

I tested this using Access Token with API access level and it works just fine.

## Suggested Resolution

- Clarify if API access is required so Pantheon can pull/fetch updates from the custom upstream
- Update Doc to reflect this

**Comment by alexfornuto** [comment]
CC @leematos
