### ISSUE TITLE
Gitlab upstreams rework, again

### ISSUE THREAD

**Issue by ahebrank** [pantheon-systems/documentation#4591]
Re: https://pantheon.io/docs/create-custom-upstream/

Priority: Low

## Issue Description

Improvements to Gitlab upstream docs, take 2, now that we've got this working the rest of the way.

The instructions for [adding a Gitlab upstream](https://pantheon.io/docs/create-custom-upstream/#gitlab-https) are missing some pieces:

- "Prepare a Gitlab user" should be explicit that you need to create a new user specifically for Pantheon access to the upstream repository
- "You must provide a username/password or OAuth token" isn't really right. Pantheon CSEs need what Gitlab calls a "Personal Access Token" (not an OAuth application token) and don't need username or password of the new user
- the docs don't mention specifically what data are required by the Pantheon CSE to add the upstream

<img width="880" alt="Screen Shot 2019-03-21 at 8 09 59 AM" src="https://user-images.githubusercontent.com/5023646/54751250-c00e4a00-4bb0-11e9-8c81-7df1b8272710.png">

## Suggested Resolution

The docs should include the following instructions for users wanting to add a Gitlab upstream:

1. Create a new user on gitlab.com specifically and solely for Pantheon access to your custom upstream
2. While logged in as that new user, create a new Access Token (https://gitlab.com/profile/personal_access_tokens) with scope `api`
3. As the custom upstream repo maintainer user, add the new user to your upstream repository on gitlab.com as a Member with Reporter access
4. Contact Pantheon support via chat or ticket and provide:
    - the desired name of your upstream and the application it provides (e.g., Drupal 8)
    - the `https` clone URL for the upstream on gitlab.com (URL ending in `.git`)
    - the api-scope access token created for your new user

related to #4562, #4581 cc @rubelyn

**Comment by alexfornuto** [comment]
@ahebrank I really appreciate you detailing this resolution. I hope you'll review the PR addressing this once I push it up.

**Comment by alexfornuto** [comment]
EXCELSIOR! 
![image](https://user-images.githubusercontent.com/2349184/54786209-48fba480-4bf6-11e9-9af7-7d89cb18ce83.png)
