### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update section in converting a WP site

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4593]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot/)

Priority: Low

## Issue Description:
- Converting a normal WP install to a nested docroot site seems to miss the changes in the .gitignore file
- Related to internal ticket 153001

## Suggested Resolution
- Update necessary steps to complete a conversion of a normal WP site to a nested docroot WP site

**Comment by alexfornuto** [comment]
Determined to not be an issue, as discussed in #4594
