### ISSUE TITLE
Best Practices for Maintaining Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#4607]
Re: [Best Practices for Maintaining Custom Upstreams](https://pantheon.io/docs/maintain-custom-upstream/)

Priority: Low

## Issue Description:

Under the [Test and Release Pantheon Core Updates section](https://pantheon.io/docs/maintain-custom-upstream/#test-and-release-pantheon-core-updates), the doc assumes that Users/Customers can access our Multidev feature. See step 7:

`7. Back on the Site Dashboard for your test site, navigate to the Multidev overview tab and click Git Branches.`

`8. Click the Create Environment button next to the core-update branch.`

`9. Use this new Multidev environment to evaluate your core-update branch. When you're ready to release, merge the branch into master and push to your remote repository on GitHub or Bitbucket:`

Not all Users/Customers have access to Multidev. They can't follow the instruction.

## Suggested Resolution
- Update the doc and provide suggestions on how to do this if you don't have Multidev access

**Comment by alexfornuto** [comment]
@rubelyn I double-checked, and everyone who has access to custom upstreams also has access to multidev. Have you encountered a situation where that's not the case?

**Comment by rubelyn** [comment]
Hi @alexfornuto, yes, I reported this because I got a chat from a customer. I think their Partner trial has expired.

**Comment by alexfornuto** [comment]
So if their trial expired they wouldn't have access to the custom upstream feature anymore, right?

**Comment by alexfornuto** [comment]
Adding @EdwardAngert to follow up with product on what happens when orgs gain then lose partner program status, WRT custom upstreams.
