### ISSUE TITLE
How to a specific support package?

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#4608]
Re: [Get Support](https://pantheon.io/docs/support/)

Priority: Medium

## Issue Description:
As a customer, I look at the Support docs page and want to know how I get to be a specific Support package. 

## Suggested Resolution
Provide a short section for an explanation, or references to instructions about how to specifically have the support package (is purchased, or met through Partner program, etc)

**Comment by alexfornuto** [comment]
Resolved by #5238
