### ISSUE TITLE
Working with Cookies on Pantheon Doc Update 

### ISSUE THREAD

**Issue by dchaffin** [pantheon-systems/documentation#4619]
Re: [Working with Cookies on Pantheon](https://pantheon.io/docs/cookies/)

Priority: High

## Issue Description:
This page is top of Google search results for "Pantheon cookies", but it doesn't mention the cookie naming requirements listed on: https://pantheon.io/docs/caching-advanced-topics

## Suggested Resolution
Include this bit from the latter page in a prominent manner on the first page because it's kind of super important and not easy to find out ...

> Drupal Sites
> Drupal uses SESS-prefixed cookies for its own session tracking, so be sure to name yours differently if you choose to use one. Generally, SESS followed by a few words will work.
> 
> Correct: SESSmysessioncookie, SESShello123, SESSletsgo
> 
> Incorrect: SESS_hello, SESS-12345, mycustomSESS, Sessone, sess123testing, SESSFIVE

**Comment by alexfornuto** [comment]
Good idea @dchaffin, thanks!

@EdwardAngert this sounds like a good use of partials.
