### ISSUE TITLE
Guide to CDN (a superguide with links to other guides)

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#462]
Story: As a developer I want a general guide to CDNs (a superguide if you will) so that i can understand the general use case, then drill into the different option on another guide.

A faq would be good that explain why you should use one on pantheon would be good, it comes up often for people that think this should be build into the platform.

**Comment by rachelwhitton** [comment]
Closing in favor of [existing doc](https://pantheon.io/docs/articles/drupal/content-delivery-network-cdn-for-file-distribution/)
