### ISSUE TITLE
Pantheon Organizations FAQs Doc Update 

### ISSUE THREAD

**Issue by ChristopherMatthews** [pantheon-systems/documentation#4621]
Re: [Pantheon Organizations FAQs](https://pantheon.io/docs/organization-faq/#as-a-partner-do-i-get-enhanced-support)

Priority: Low

## Issue Description:
https://pantheon.io/docs/organization-faq/#as-a-partner-do-i-get-enhanced-support states: 

As a Partner, do I get enhanced support?
No. However, opening support requests from your Organization Dashboard Support tab and checking the box for "Non-site related issue" will direct your request to a specific agent ready to respond to your questions.

## Suggested Resolution
Update answer based on the new support levels for Pantheon Partners per https://pantheon.io/docs/support/#support-features-and-response-times

**Comment by alexfornuto** [comment]
@ChristopherMatthews Welcome back! I was worried when your old username when dark. We should update your Contributors page on our docs.

**Comment by ChristopherMatthews** [comment]
Haha, thanks :)
Yeah, I [converted my previous @cityofoaksdesign user into an organization](https://help.github.com/en/articles/converting-a-user-into-an-organization) so I'm using @ChristopherMatthews for issues now. Yes, if you could update my Contributors page on your docs that would be awesome (or point me to where I can do that).
