### ISSUE TITLE
Log Files on Pantheon Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4624]
Re: [Log Files on Pantheon](https://pantheon.io/docs/logs/)

Priority: Low 

## Issue Description:
Add FAQ for "Can I tail server logs, such as nginx access or php error"?

**Comment by alexfornuto** [comment]
Since a user cannot open a shell session on the container, the answer seems to me to be "Not directly, but you can download them over SFTP and then tail them locally."

**Comment by sarahg** [comment]
When I was developing more sites on Pantheon I'd (kind of) accomplish this by using `watch` to rsync my log file every 2 seconds, then tail that. Something like this:

`watch -n2 terminus rsync $SITE.$ENV:logs/php-error.log ~/logs`
`tail -F ~/logs/php-error.log`

(On OSX you can install `watch` with Homebrew.)

**Comment by alexfornuto** [comment]
@sarahg Interesting...
![image](https://user-images.githubusercontent.com/2349184/55430185-0e2d3100-5553-11e9-89bf-b2c87edf3536.png)


Do you think that's something we could/should incorporate into #4634?

**Comment by alexfornuto** [comment]
@sarahg Interesting...

![beard](https://user-images.githubusercontent.com/2349184/55430276-446ab080-5553-11e9-935e-9e8bd582560b.gif)



Do you think that's something we could/should incorporate into #4634?

**Comment by sarahg** [comment]
Sure, I think it's a viable workaround and not too hard to hook up. Maybe someone else should try it out though to make sure there aren't other setup steps needed to run this. 

The command I wrote above does also require the [Terminus rsync plugin](https://github.com/pantheon-systems/terminus-rsync-plugin). You'd need to write something a bit more complex than the one-liner if you want to capture output from an environment with multiple appservers, but I think wanting to do this on dev/multidevs is a more likely scenario for most people.

**Comment by alexfornuto** [comment]
PR Updated with a script to track and watch logfile changes.
