### ISSUE TITLE
Create a New Site in Pantheon's EU Region Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4638]
Re: [Create a New Site in Pantheon's EU Region](https://pantheon.io/docs/eu-region/)

Priority: Medium 

## Issue Description:
Missing content for how administrators of a contract organization can create a new site in the EU region. 

Note: feature availability must be enabled for the contract organization by Pantheon for the following command to be valid. 

## Suggested Resolution
terminus site:create site-machine-name "Site Human Name" --region=eu 

cc @ari-gold

**Comment by rachelwhitton** [comment]
Potentially add an FAQ section to capture questions like "Can I leverage the EU region availability on existing Pantheon sites?" With an answer such as, yes however you must create a new site then migrate the site over either manually yourself or via paid engagement with our Professional Services team.

**Comment by rachelwhitton** [comment]
Note also that Terminus 2.0 is required for this to work

**Comment by rachelwhitton** [comment]
I have a branch in progress for these changes, I'll submit a PR before end of this week.

**Comment by alexfornuto** [comment]
Resolved by #4654
