### ISSUE TITLE
May Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4641]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by greg-1-anderson** [comment]
Update to PHP 7.3.4, 7.2.17, 7.1.28

**Comment by greg-1-anderson** [comment]
Update to Drush 8.2.3

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.14 
Update to Drupal 8.6.14. For more information, see https://www.drupal.org/project/drupal/releases/8.6.14

**Comment by pantheon-upstream** [comment]
### Drupal 8.6.15 
Update to Drupal 8.6.15. For more information, see https://www.drupal.org/project/drupal/releases/8.6.15

**Comment by pantheon-upstream** [comment]
### Drupal 7.66 
Update to Drupal 7.66. For more information, see https://www.drupal.org/project/drupal/releases/7.66

**Comment by ari-gold** [comment]
Redis support added for sites with [Disaster Recovery](https://pantheon.io/features/disaster-recovery).

**Comment by ari-gold** [comment]
Terminus 2.0.1 released

**Comment by ari-gold** [comment]
PHP 7.3 new default for Drupal 8 and WordPress sites

**Comment by ari-gold** [comment]
[Announcing Pantheon’s New European Region: Now in Limited Availability](https://pantheon.io/blog/announcing-european-region-limited-availability)

**Comment by alexfornuto** [comment]
@ari-gold blog posts go into the changelog anyway.

**Comment by greg-1-anderson** [comment]
### Drupal 8.7.0

For more information, see https://www.drupal.org/project/drupal/releases/8.7.0

**Comment by greg-1-anderson** [comment]
Update to PHP 7.3.5, 7.2.18, 7.1.29

**Comment by alexfornuto** [comment]
Direct new updates to #4722
