### ISSUE TITLE
Managing Drush Versions on Pantheon Doc Update 

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#4645]
Re: [Managing Drush Versions on Pantheon](https://pantheon.io/docs/drush-versions/)

Priority: Low

## Issue Description:

Some sites attempt to use Drush versions with PHP that's too new.

## Suggested Resolution

List maximum PHP versions in addition to minimum ones.

**Comment by alexfornuto** [comment]
@davidstrauss nice catch. We'll either replicate or link to the table [here](https://docs.drush.org/en/master/install/#drupal-compatibility)

**Comment by alexfornuto** [comment]
So I may have spoken to soon. The table I referenced doesn't list max versions. I spoke with one of the Drush maintainers, who says that the max PHP version for Drush versions `<`8 is unknown, and not tracked/tested by the Drush team.

The highest version we can say **for sure** works with these versions is not much higher than the minimum versions, which defeats the purpose of adding this column, IMHO.

Unless there's another avenue to turn that I haven't yet found, I think we have to close this issue without a PR.

CC @greg-1-anderson

**Comment by greg-1-anderson** [comment]
So, it seems that Drush 7 was only tested with 5.3 for sure, and was probably tested with 5.5 as well, and Drush 5 was only tested with 5.3 and maybe 5.4 as well. Insofar as Drush was widely used, though, I would say that the ad-hoc testing of Drush across PHP versions would be very high for all versions of PHP that were available when said version of Drush was supported, and any bugs probably fixed.  That would include PHP 5.5 for Drush 5, and PHP 5.6 for Drush 7. PHP 5.6 almost certainly works with Drush 5 as well, but you could still leave that as "unknown", along with PHP 7.x.

If you feel this information is too anecdotal for documentation purposes, that is fine. Folks should be strongly encouraged to stop using Drush 5 and Drush 7. However, if there's some reason that they're stuck on those versions, it would be even worse to make them think they couldn't go to PHP 7. That probably works, but again, haven't tested the old versions in a long time so unknown. Maybe just leave this alone.

**Comment by alexfornuto** [comment]
So this has been sitting for awhile, and there's no new information. I'm going to close it for now, but if there's more discussion to be had we can re-open it.
