### ISSUE TITLE
New content on Known Modules - S3FS

### ISSUE THREAD

**Issue by markely** [pantheon-systems/documentation#4652]
Priority: Medium

## Title   
S3FS for Drupal 7 on Pantheon

## Description .   
There are still 2 known issues.

## Outline
1. If S3 is setup to take over public filesystem, Drupal's css/js aggregation will not work (or will work with very nasty hack)
2. There still will be no way to upload files over 100MB to S3 through Drupal file fields.

## Expected Audience
Drupal 7 clients looking to offload files to S3

## Path
docs/modules-plugins-known-issues/

**Comment by EdwardAngert** [comment]
thanks @markely !
looking at the [project page](https://www.drupal.org/project/s3fs) I see that they've halted D7 dev for that module.
I can still add it to the list of modules with known issues, but do you know if the same issue with Drupal's CSS/JS aggregation still applies to D8 as well?

**Comment by markely** [comment]
No idea.   I'm asking my team, as I feel like this was a joint discussion and I just was the lucky one to open the PR for docs.

**Comment by alexfornuto** [comment]
@markely any work from your team?

**Comment by nullvariable** [comment]
Issue 2 will persist regardless of D8
It looks like from a quick skim of the 8.3.x branch that the css/js issue will persist

**Comment by markely** [comment]
@alex & Docs team...

We have not had a chance to build out a test for this, but everyone that
has looked seems to agree with Doug's instinct being correct.

-Mark

**Comment by alexfornuto** [comment]
@markely  What's the nasty hack mentioned at the top?

**Comment by carolyn-shannon** [comment]
> @markely What's the nasty hack mentioned at the top?

It's "upload all the static assets belonging to Drupal core and contrib modules to S3 as well, to the root of your bucket" - mentioned here: https://www.drupal.org/project/s3fs/issues/2511090

**Comment by carolyn-shannon** [comment]
Reached out to PS via Slack
