### ISSUE TITLE
Bypassing Cache with HTTP Headers Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#4657]
Re: [Bypassing Cache with HTTP Headers](https://pantheon.io/docs/cache-control/)

Priority: Medium

## Issue Description:

Customer noted that the WordPress code does not work at the top of the wp-config.php file. I tried it on my test site and I got this when going to page that should not be cached instead of the page's content:

Call to undefined function: add_action()

## Suggested Resolution

Not exactly sure of best resolution, but I found if I put this code below the include of the wp-settings.php at the bottom of the file, then it works. Otherwise, it could be added to/as a plugin.

**Comment by alexfornuto** [comment]
Consolidating with #4658. Thanks @dficker!
