### ISSUE TITLE
Add a license for these now-public, forkable docs

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#466]
I'm leaning toward CC-BY-SA for text with dual CC-BY-SA and MIT for code samples.

**Comment by suzannealdrich** [comment]
CC-BY-SA++
MIT++

**Comment by rachelwhitton** [comment]
CC-BY-SA incorporated in #467 

Todo:
- [ ] Add MIT license for code snippets.

**Comment by rachelwhitton** [comment]
MIT added in #468
