### ISSUE TITLE
Ticket template for replacing custom certificate

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#4666]
Re: [Custom Certificates on Pantheon's Global CDN](https://pantheon.io/docs/custom-certificates/)

Priority: High

## Issue Description:
Some customers frequently update an existing certificate, and aren't able to quickly get it updated.

## Suggested Resolution

Include a ticket template:
https://gist.github.com/ari-gold/5161a8b79b351b561e170fd345158925

**Comment by alexfornuto** [comment]
@ari-gold thanks for the issue! In order for the customer to have a new Certificate to provide, wouldn't we already be in communication with them to provide the CSR?  With that being the case, I would suggest that we provide this template via the ticket.

**Comment by ari-gold** [comment]
Yeah, that might work @alexfornuto. I was thinking support or ProServ or whoever is handling the request could link to the doc where the template could live. 

@ttrowell   What do you think is the best path forward here?

**Comment by ttrowell** [comment]
If there is a new cert, then yes, we do send them verbiage to gather what we need for the CSR. However, upon renewal (which can be 3 or 6 months or yearly - or at will) this would help to get the info we need for that renewal back into Support faster to funnel over to PS.   As with some current docs instructions on sending in requests, some customers find and follow it, and others do not.

**Comment by ttrowell** [comment]
@ari-gold @alexfornuto  Best path forward?  Publish the template in docs and internally.  My .02 :)
(see comment above, too)

**Comment by ttrowell** [comment]
For CSE or PS when replying maybe:

> Thank you for working with us to get the site certificate updated.
> Please provide the CN (Common Name) that this certificate is issued for.  If you are unsure what this value is, we can provide identifiers for the certificates that are assigned to the Organization.
> 
> For verification purposes, please include the domains the certificate is valid for (colon separated list):
> domain1.com:domain2.com:domain3.com, etc.
> 
> Thanks!
