### ISSUE TITLE
New Doc Proposal 

### ISSUE THREAD

**Issue by jeffpignataro** [pantheon-systems/documentation#4667]
Priority (Low‚ Medium‚ High): Medium

## Title
Scripting Terminus page suggestion

## Description
I would highly recommend adding an example that takes some sort of action which, in an unscripted environment, requires some sort of actionable interactive prompt. Examples could be database imports or drush commands. These typically require interactive prompts and showing the use of the optional arguments for "Do not ask any interactive question" and "Answer all confirmations with "yes"" would be very helpful and avoid the need to dig through the help commands.

## Expected Audience
Developers

## Path
https://pantheon.io/docs/terminus/scripting/

**Comment by alexfornuto** [comment]
@jeffpignataro great idea! Thanks for the suggestion.

**Comment by alexfornuto** [comment]
@greg-1-anderson do you have any input on how we could best achieve this? Any good examples come to mind?

**Comment by EdwardAngert** [comment]
closed by #4857
