### ISSUE TITLE
Configuring Redirects Enhancement

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#4669]
Priority: Low

## Description
Several times a week, a customer will copy and paste the code from the redirects.md docs and find that their site has now been redirected to www.example.com This confuses and startles them so they open a chat.

## Outline
 I bought the domain name [ReplaceThisWithYourDomain.com](https://ReplaceThisWithYourDomain.com) and built a small guide on what's happening and how to fix it. It's live so if you want to check it out, you can.

## Expected Audience
Copy pasting customers

## Path
documentation/source/_docs/redirects.md

**Comment by alexfornuto** [comment]
@CFin86 neat idea, great initiative. Two problems:

1) Example.com is one of the domains reserved for documentation by [IETF RFC 2606](https://tools.ietf.org/html/rfc2606).
2. The content on example.com does a much clearer job, IMHO, of telling the reader why they are where they are. Your page puts the relevant details in small white text at the bottom in what I feel is a hard to read design.
3. Your site is designed to look like it's part of the official Pantheon platform, but it is not. It's controlled by you and you work for Pantheon, but it's not managed by the same team as other pages featuring Zeus.

I'm happy to discuss further, but at the moment I would lean towards not pursuing this change.

**Comment by alexfornuto** [comment]
Discussed with @CFin86 in Slack, opting to close this for now.
