### ISSUE TITLE
Manually Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4681]
Re: [Manually Migrate Sites to Pantheon](https://pantheon.io/docs/migrate-manual/)

Priority: Low

## Issue Description & Suggested Resolution
1) Under - `Before You Begin` section
Add - Make sure to read Platform Considerations and plan to mitigate any conflicts with the site needs or architecture.
Add - Make sure they don't have any plugins/modules that have issues in the platform listed here: https://pantheon.io/docs/modules-plugins-known-issues
Add- Make that their code is compatible with PHP 7.2(or the latest PHP version), if not they will need to downgrade PHP version on a later time to match which one is compatible with their site using this guide https://pantheon.io/docs/php-versions/#configure-php-version

2)Under `Using an SFTP Client` - Step 4. It would be more helpful if there are tabs here for D7, D8 and WP to indicate which folders are ok to overwrite. For example in WP
Themes - wp-content/themes
Plugins - wp-content/plugins

I believe Drupal have their own folders that can be overwritten

**Comment by alexfornuto** [comment]
@carl-alberto I took care of `1` in #4744. I'm happy to address `2` if you can suggest an SME to provide the directories for Drupal.

**Comment by carl-alberto** [comment]
@eabquina or @sarahg might be able to help with the Drupal section

**Comment by sarahg** [comment]
@carl-alberto Good idea on noting this. This is documented on Drupal.org for D7 and D8:
https://www.drupal.org/node/2621480 (D7)
https://www.drupal.org/docs/8/understanding-drupal-8/directory-structure (D8)

We could just link off to these pages, or copy over the info we need from there.
