### ISSUE TITLE
Create a Custom Upstream Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#4683]
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream/)

Priority: Low

## Issue Description:
Our doc does not provide any info on how to delete an existing custom upstream.

Customers can now delete an existing upstream by going to Org Dash > Upstreams > Settings.

Note: The custom upstream can only be deleted if there is no site using it.

## Suggested Resolution

Add a section on how to delete a custom upstream and include some screenshot.

**Comment by alexfornuto** [comment]
@rubelyn good idea! But I wonder if this new section would be better placed [over here](https://pantheon.io/docs/maintain-custom-upstream/#troubleshoot)
