### ISSUE TITLE
Multipage guide layout shouldn't be full width

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#4687]
Re: [Quick Start](https://pantheon.io/docs/guides/quickstart/create-test-live/)

Priority: Low

## Issue Description:
The main content area (on the right side) of the Multipage guide layout continues to grow based on the width of the window. I feel like this becomes difficult to read and follow as the screen gets wider and videos are included. See comparison screenshots of [guides](https://www.dropbox.com/s/ebdx53ofzt7t28w/Screenshot%202019-04-23%2015.42.26.png?dl=0) vs [other docs pages](https://www.dropbox.com/s/mjyo3bmcl1h1ter/Screenshot%202019-04-23%2015.47.41.png?dl=0).

@rachelwhitton reported this and myself, @mcdwayne, and others in the developer training working session discussed.

## Suggested Resolution
Use a fixed with that matches or is closer to what other doc pages use. (Possibly @rachelwhitton has more specific suggestions?)

**Comment by alexfornuto** [comment]
Resolved by #5088
