### ISSUE TITLE
Network Solutions Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#4688]
Re: [Network Solutions Domain Configuration](https://pantheon.io/docs/network-solutions/)

Priority: Low

## Issue Description:

When some users e-mail Network Solutions to add an IPv6 record as described on http://www.networksolutions.com/support/Adding-an-IPv6-record/ (linked to from this page), they get a message like this:

> Thank you for contacting the IPV6 Processing Department at Network Solutions, a Web.com Company.
> 
> We currently only support IPv6 changes on the Server level, not the domain level. The information provided directs to add resource records for an IPV6 address on the domain level. Therefore all we provide is the glue record.
> 
> To create or an update a glue record please provide the server name. The server name must be linked to a registered domain with Network Solutions and cannot be Network Solutions Servers (ns1.worldnic.com etc..).
> 
> An example of a valid server name we would be dns1.YOURDOMAIN.com.
> 
> We hope this information has been helpful. However, if you have any additional questions, please don't hesitate to contact our Customer Service Department and refer to #######. To reach us, call 1-888-642-9675. If you are calling from outside the U.S. or Canada, please call 1-570-708-8788.

My understanding is that "We currently only support IPv6 changes on the Server level, not the domain level." means that they no longer will set AAAA records for a domain. That is despite the fact that the page linked above says they do this.

## Suggested Resolution

Update the Docs to say that Network Solutions does not support AAAA records. For this reason, we recommend you host your DNS elsewhere.

**Comment by alexfornuto** [comment]
It seems like Network Solutions can't keep their story straight. We recently updated this doc to say that they _could_ add AAAA records: #4301 

@newtoid do you want to weigh in on this?
