### ISSUE TITLE
Database backups do not have correct extension

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#4703]
Re: [Backups Tool](https://pantheon.io/docs/backups/)

Priority: Low

## Issue Description:

A customer noted that the backup download script will save database files as ".tar.gz" files and if an unzip application tries to expand them, it will fail. (It's not a tar file.) As the doc correctly says in other areas, database files should be saved as ".sql.gz" files.

## Suggested Resolution

Rework the script to save code and files as ".tar.gz" and then save the database with a ".sql.gz" extension.

**Comment by alexfornuto** [comment]
@dficker is that not covered in this note?

![image](https://user-images.githubusercontent.com/2349184/57032755-bdbbf880-6c10-11e9-98cb-0d2eb6259432.png)

**Comment by alexfornuto** [comment]
Thanks for the issue @dficker!
