### ISSUE TITLE
Who can add/remove custom domains?

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#4710]
Re: [Add/remove custom domains](
https://pantheon.io/docs/change-management/#organizations-roles-and-permissions,
https://pantheon.io/docs/domains/, 
https://pantheon.io/docs/guides/launch/domains/,
https://pantheon.io/docs/relaunch/ 
)

Priority: Low

## Issue Description:
Doesn't mention _who_ can add/remove domains. A site owner can, but what about an admin from a supporting org? 

## Suggested Resolution
Clearly indicate who can maintain custom domains.

**Comment by alexfornuto** [comment]
@thomas-thackery before I can resolve this issue, can you provide the answer to the question "What roles can add/remove domains?"

**Comment by thomas-thackery** [comment]
@alexfornuto I'm testing out the behavior and will report back.

**Comment by alexfornuto** [comment]
@EdwardAngert assigned to you since you've made many updates regarding who can do what since this issue was created - can you confirm if this can be closed or still requires a PR?
