### ISSUE TITLE
Encoding: should be UTF-8

### ISSUE THREAD

**Issue by mdupont** [pantheon-systems/documentation#472]
Related to "&nbsps replaced with Â"

I was surprised to see that the pantheon.io/docs pages have no encoding declared either in the HTML file or the HTTP headers. In my Firefox browser, the fallback encoding is then Windows-1252.

To avoid future encoding and character display issues, wouldn't it be better to declare UTF-8 as the encoding?

**Comment by bmackinney** [comment]
@mdupont thanks for the issue. I deployed a change that blocked that part of the head. It should be all fixed now.
