### ISSUE TITLE
Using Extensions That Assume Write Access Doc Update add real world examples

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4720]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access/)

Priority: Low

## Issue Description:
Implementing symlinks seems to be trivial to users

## Suggested Resolution
Add some real-world examples where symlinks are commonly used in plugins/modules where users can easily implement it

**Comment by alexfornuto** [comment]
@carl-alberto do you have any examples in mind?

**Comment by carl-alberto** [comment]
@alexfornuto Added an example here https://github.com/pantheon-systems/documentation/pull/4735 for you to review
