### ISSUE TITLE
June Changelog Candidates

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#4722]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by alexfornuto** [comment]
[Moved](https://github.com/pantheon-systems/documentation/issues/4641#issuecomment-489826284)
> Update to PHP 7.3.5, 7.2.18, 7.1.29

**Comment by greg-1-anderson** [comment]
### WordPress 5.2
Update to WordPress 5.2. For more information, see https://wordpress.org/news/2019/05/jaco/

**Comment by greg-1-anderson** [comment]
### Drupal 8.7.1 
Update to Drupal 8.7.1. For more information, see https://www.drupal.org/project/drupal/releases/8.7.1

**Comment by greg-1-anderson** [comment]
### Drupal 7.67 
Update to Drupal 7.67. For more information, see https://www.drupal.org/project/drupal/releases/7.67

**Comment by greg-1-anderson** [comment]
### WordPress 5.2.1
Update to WordPress 5.2.1. For more information, see https://wordpress.org/news/2019/05/jaco/

**Comment by greg-1-anderson** [comment]
### Drupal 8.7.2 
Update to Drupal 8.7.2. For more information, see https://www.drupal.org/project/drupal/releases/8.7.2

**Comment by greg-1-anderson** [comment]
### PHP 7.1.30, 7.2.19 and 7.3.6

See:
- https://www.php.net/ChangeLog-7.php#7.1.30
- https://www.php.net/ChangeLog-7.php#7.2.19
- https://www.php.net/ChangeLog-7.php#7.3.6

**Comment by alexfornuto** [comment]
Add new items to #4789
