### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by ngunner** [pantheon-systems/documentation#4731]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Medium

## Issue Description:
Under section 'Cloning example-drops-8-composer Locally', it seems that users without permission to the 'example-drops-8-composer' github repository can't clone the repo using the command under item 1: 

`git clone git@github.com:pantheon-systems/example-drops-8-composer.git $PANTHEON_SITE_NAME`

User gets this warning:

```
Cloning into 'example-drops-8-composer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Suggested Resolution
Update the clone command to use the direct URL to the repo like this:
`git clone https://github.com/pantheon-systems/example-drops-8-composer.git $PANTHEON_SITE_NAME`

**Comment by alexfornuto** [comment]
Hi @ngunner, thanks for the issue! This error doesn't have anything to do with the permissions on that repository specifically. Using `git clone` over SSH requires an SSH key to be shared with GitHub. You can follow [GitHub's Help doc](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), or [our doc](https://pantheon.io/docs/ssh-keys/).

Having said that, I'll add a note that if you're not using SSH keys on GitHub to replace the path.
