### ISSUE TITLE
Pantheon Enterprise Gateway Doc Update 

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#4737]
Re: [Pantheon Enterprise Gateway](https://pantheon.io/docs/pantheon-enterprise-gateway/)

Priority: High (choose one, remove the other options)

## Issue Description:
The very first link in this page (to https://pantheon.io/features/secure-integration) lands on a 'site under maintenance' page. 

## Suggested Resolution
It appears that the link is fine, but the target page is not being found (see first result on https://www.google.com/search?q=pantheon+secure+integration&oq=pantheon+secure+integration&aqs=chrome..69i57.9405j0j7&sourceid=chrome&ie=UTF-8)

**Comment by alexfornuto** [comment]
Thanks @joshualieb  - it looks like the target URL was fixed my the website maintainers. Closing without Docs action.
