### ISSUE TITLE
Overriding the debug.log location via ini_set is not allowed anymore

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4740]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php/)

Priority: Low

## Issue Description:
overriding the debug.log location is not working anymore via `ini_set` in wp v5.1

## Suggested Resolution
Updating all the related docs to symlink method instead of ini_set override or update related docs with the related change

**Comment by alexfornuto** [comment]
@carl-alberto are you saying that overwriting `debug.log` in the code base was possible before? If so, what changed? Is this a product change or a bug? If the latter, it should be reported to product rather than documented.

**Comment by carl-alberto** [comment]
@alexfornuto I dug deeper into this and it seems that the `ini_set` override is not working anymore for WP version 5.1 and above as per changelog https://make.wordpress.org/core/2019/01/23/miscellaneous-developer-focused-changes-in-5-1/

To quote, this is the new way to override debug location path:

> WP_DEBUG_LOG is a constant that tells WordPress to enable or disable error logging. Its default value is false (no error logging). But, if it’s defined as true (or 1) in the wp-config.php file, site errors will be logged in the wp-content/debug.log file.
Starting in WordPress 5.1, WP_DEBUG_LOG will also accept a file path as a value allowing a custom error log to be defined. For example:
`define( 'WP_DEBUG_LOG', '/srv/path/to/custom/log/location/errors.log' );`


Maybe we can stick with the example for symlinking a file in the symlink section as this is one good example on how to do symlinking of a file to a writable path, then we just update the other related docs regarding this WP core change
