### ISSUE TITLE
PHP Errors and Exceptions Doc Update 

### ISSUE THREAD

**Issue by xq42** [pantheon-systems/documentation#4750]
Re: [PHP Errors and Exceptions](https://pantheon.io/docs/php-errors/)

Priority: Low

## Issue Description:

This doc currently indicates there should be no error messages displayed within the browser for Test environments, but "display_errors" is set to "on" in the Test environments for WordPress, Drupal 7, and Drupal 8 sites, causing errors to be displayed.

## Suggested Resolution

Because Test environments for all 3 CMS' have the same settings, and because it makes sense for php errors to show in the browser for Test environments, it is likely the doc just needs to be updated to reflect this accurately.

However we may want to confirm this (with Product? some other team?) before modifying the doc rather than simply assuming the doc is wrong.

**Comment by alexfornuto** [comment]
@ari-gold can you confirm that `display_errors` should be set to `on` in Test environments?

**Comment by carolyn-shannon** [comment]
@ari-gold can you lend a hand w/this?
