### ISSUE TITLE
Replace all references to SSL

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#476]
We should refer to HTTPS (preferred) or TLS (when HTTPS is inaccurate, which is rare in customer documentation).

SSL is insecure, and we've never really used it. Being more precise will help us improve the clarity of statements like "SSL is not secure."

**Comment by bmackinney** [comment]
@davidstrauss  does this effect the dashboard? 
Is there a general rule-of-thumb we can apply to determine whether HTTPS will be inaccurate and we should use TLS instead?

**Comment by davidstrauss** [comment]
@bmackinney HTTPS is almost always accurate for customers. The only place I think it may be inaccurate is for encrypted MariaDB connections, which aren't yet documented for customers.
