### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by GhostInTheMachines** [pantheon-systems/documentation#4761]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Instructions at the url below should include removing or commenting out "workflows:" in the pantheon.yml file
https://pantheon.io/docs/guides/drupal-8-composer-no-ci/

Issue Description:
Error is thrown about pantheon.yml
## Suggested Resolution
change instructions from:
Remove the following section from pantheon.yml:
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
TO:
Remove the following section from pantheon.yml:
workflows:
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php

**Comment by alexfornuto** [comment]
CC @ataylorme @davidneedham @mcdwayne

**Comment by alexfornuto** [comment]
Resolved by #4800
