### ISSUE TITLE
Horizontal Scalability: Add and Remove Application Containers

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#4765]
Re: [Horizontal Scalability](https://pantheon.io/docs/horizontal-scalability/#add-and-remove-application-containers)

Priority: Low

## Issue Description:
Mentions how to scale up and down based on appserver needs, but doesn't mention: 
1. How to determine if more appservers are required and, if so, how many. A guide/table would be helpful. 
1. Financial impact of changing plans at will
    -  Especially if the site is already on an annual plan
    - When does new plan take effect?
    - How long does the plan change last? Can I scale down? Would need a link/mention about no pro-ration for downgrading midterm.

**Comment by alexfornuto** [comment]
Assigning to @thomas-thackery, who doubles as an SME that can answer the questions he's raised.

**Comment by jfussion** [comment]
We also have a doc about how to compute for dynamic capacity. That might help https://pantheon.io/docs/platform-resources/#calculate-concurrent-user--dynamic-page-capacity

**Comment by alexfornuto** [comment]
@jfussion thanks, but that doc is deprecated and going away soon, so we shouldn't reference it moving forward.
