### ISSUE TITLE
Restoring an Environment from a Backup Doc Update 

### ISSUE THREAD

**Issue by jmcausing** [pantheon-systems/documentation#4768]
Re: [Restoring an Environment from a Backup](https://pantheon.io/docs/restore-environment-backup/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

wget does not seem to work.  see screenshot:
https://downloads.intercomcdn.com/i/o/123225041/32041da355fb00acd9af6d68/image.png

## Suggested Resolution
curl DOWNLOAD_LINK -o "output-file"

If it is possible to add alternative commands to download the file

**Comment by alexfornuto** [comment]
This could also be solved by adding `-O outputfile` to `wget`. Either way, we'll need to also adjust the copy to tell readers to specify the correct extension based on which backup they are downloading.

Thanks for reporting @jmcausing!

**Comment by alexfornuto** [comment]
This has been resolved into the `gatsby` branch. You'll see the update live when the Gatsby build goes into production.
