### ISSUE TITLE
Update  drupal-8-composer-no-ci "Removing Automation Pieces"

### ISSUE THREAD

**Issue by ssteigen** [pantheon-systems/documentation#4773]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description

There are two steps under "Removing Automation Pieces" which appear to no longer be relevant.

> Remove the find .circleci/scripts/pantheon/ -type f | xargs chmod 755, line from the post-update-cmd section of scripts.
> Remove the find tests/scripts/ -type f | xargs chmod 755 line from the post-update-cmd section of scripts. 

## Suggested Resolution

Remove these steps if they are no longer necessary. If they _are_ still necessary, update them appropriately.

**Comment by alexfornuto** [comment]
Thanks for bringing this to our attention @ssteigen! We staged a fix against our Gatsby branch. You'll see the fix go live once we finish migrating to the new build process. Until then, we'll leave this open.
