### ISSUE TITLE
The Pantheon Community and Power Users Group Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#4777]
Re: [The Pantheon Community and Power Users Group](https://pantheon.io/docs/power-users/)

Priority: Low

## Issue Description:
The slack & channel are no longer called Power Users (https://pantheon-community.slack.com/archives/C2GJ3JG7Q/p1559233554004200) but are instead called Pantheon Community and #community. 

## Suggested Resolution
Rewrite references to Power Users on this page (as well as perhaps other pages?).

**Comment by alexfornuto** [comment]
Thanks @sparklingrobots! We'll close this issue when the fix (merged into our Gatsby branch) goes up to production.
