### ISSUE TITLE
Workaround for fast-velocity-minify

### ISSUE THREAD

**Issue by jmcausing** [pantheon-systems/documentation#4778]
Priority: Low/Medium/High (choose one, remove the other options)

## Title
Workaround for this plugin: 
https://wordpress.org/plugins/fast-velocity-minify/

## Description
That plugin is using the server binding ID as static. Our binding ID's are chaning from time to time so if it changes, the site will no longer work.

It is advisable for that plugin to use  $_SERVER  to get the current binding ID

Chat link: 
https://app.intercom.io/a/apps/xkegk7cr/inbox/inbox/search/conversations/22268114001

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by EdwardAngert** [comment]
thanks for filing the issue, @jmcausing!
we can add a section about it to [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/#wordpress-plugins)

**Comment by alexfornuto** [comment]
We'll need to know how to properly override this setting the plugin. Also, an issue on the plugin itself to make it more compatible would be a good idea.

**Comment by alexfornuto** [comment]
@carl-alberto is reviewing the [feedback](https://wordpress.org/support/topic/file-path-for-this-plugin-needs-to-use-_server-variable-1/) from the plugin author.

**Comment by carl-alberto** [comment]
@jmcausing It seems there is an override on where to change the folder cache path https://screencast.com/t/sVkIoVbNa, adding PR for a possible solution in the screenshot

**Comment by alexfornuto** [comment]
@carl-alberto +1 - I'd prefer a solution that isn't "update the path when your bindings change".

**Comment by EdwardAngert** [comment]
@carl-alberto I made a few quick edits to the PR in case we don't discover a better solution and want to publish it as-is. I'll wait on your and @alexfornuto's 👍 for that
