### ISSUE TITLE
Platform Considerations Doc Update 

### ISSUE THREAD

**Issue by jmcausing** [pantheon-systems/documentation#4779]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority: Low

## Issue Description:

IE 11 does not work when clicking the two login buttons in https://dashboard.pantheon.io

Slack: $SLACK/archives/C0ACN422E/p1559307724045600

Chat: 22268891596

See also screenshot below using my IE 11 browser. Chat link above is customer having the same issue.

## Suggested Resolution

![image](https://user-images.githubusercontent.com/10601417/58707754-5c8e6d00-83e8-11e9-9887-0eab28361457.png)

**Comment by EdwardAngert** [comment]
thanks, @jmcausing - I'll check with Product about this and see if it's related to BUGS-1862 (which has been fixed - IE11 should work!)
