### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#4780]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

Customer in chat followed the instructions to remove the Automation Pieces. After making the changes to the pantheon.yml that says to remove those lines, they had this:

> api_version: 1
> web_docroot: true
> php_version: 7.2
> workflows:

Then, when they tried to push these changes, it failed push because the `workflows:` expects some workflows afterwards. Once I told him to remove that line, commit and push, then it worked.

## Suggested Resolution

Maybe just add the `worfklows:` line to the part that needs to be removed from `pantheon.yml`? Or maybe add a note below saying that if there's no `workflows:` left, then you should remove this line? (Not sure if there's a case where there would be other workflows, but in this case, there seemed to be no other.)

**Comment by EdwardAngert** [comment]
tagging with the Consider label for now, and digging into whether or not this is related to #4773, and if it isn't and they're both needed, then we can batch them into the same PR

**Comment by alexfornuto** [comment]
@dficker We'll close this once the fix is live, which will happen once the Gatsby build goes live.
