### ISSUE TITLE
Add a note to import page that we will upgrade to the latest version of core

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#479]
For users with distributions that require an older version of core, this could result in some breakages. 

We should add a warning to the import page

https://pantheon.io/docs/articles/users/importing-an-existing-site/

**Comment by nataliejeremy** [comment]
@timani Can you give me some details about what kind of breakages you're referring to so I can draft the warning message? Thanks!

**Comment by andrewmallis** [comment]
http://drupal.stackexchange.com/questions/63226/drupal-7-20-image-styles-return-a-url-with-access-denied

**Comment by timani** [comment]
What @andrewmallis said. Also some sites and distributions require a specific version of core, such as if it has core patches for some legit reason.
