### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by chill-fpraz** [pantheon-systems/documentation#4799]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/custom-theme/)

Priority: Low

## Issue Description:
First sentence mentions "Terminal **Drush** Console plugin", but I think it should be "Terminal **Drupal** Console plugin"?
## Suggested Resolution
Edit page.

**Comment by alexfornuto** [comment]
Thanks @chill-fpraz! I staged a fix against our upcoming Gatsby site relaunch. You'll see the fix in action once it's merged to master.
