### ISSUE TITLE
Platform Considerations Doc Update add xml-rpc is not enabled in the platform and the reason

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4807]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority: Low

There have been a lot of questions in the past that xml-rpc is not fully working in their site

## Suggested Resolution
Update add xml-rpc is not enabled in the platform and the reason

**Comment by alexfornuto** [comment]
@carl-alberto Who would know the answer to why it doesn't work on the platform?

**Comment by carl-alberto** [comment]
@alexfornuto There's an internal feature request(FEAT-697) and it seems it will not be coming soon in the platform because of the experimental nature of that library

https://www.php.net/manual/en/intro.xmlrpc.php

> Warning: This extension is EXPERIMENTAL. The behavior of this extension including the names of its functions and any other documentation surrounding this extension may change without notice in a future release of PHP. This extension should be used at your own risk.

As suggested by @eabquina , they might be better off using a 3rd party include like http://gggeek.github.io/phpxmlrpc/
