### ISSUE TITLE
Using Extensions That Assume Write Access Doc Update has wrong directory in example

### ISSUE THREAD

**Issue by JaySyzdekO3** [pantheon-systems/documentation#4810]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

Under the example section, "for MacOS & Linux," the code to create the symlink is incorrect.

What is written:

`From the wp-content directory:`
`ln -s ./uploads/cache ./wp-content/cache`
`ln -s ./uploads/wp-rocket-config ./wp-content/wp-rocket-config`

If you're already in the wp-content directory, the second path parameter is wrong/redundant, thus creating the wrong symlink.

## Suggested Resolution

Remove the `wp-content` part from the path and it works. Here is what it should be:

`ln -s ./uploads/cache ./cache`
`ln -s ./uploads/wp-rocket-config ./wp-rocket-config`

I have verified that this works by correctly configuring wp-rocket with the corrected commands.

**Comment by alexfornuto** [comment]
Right you are @JaySyzdekO3! I'll patch this against our upcoming Gatsby-based relaunch.
