### ISSUE TITLE
Revise Going Live

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#482]
https://pantheon.io/docs/articles/going-live/

**Comment by nataliejeremy** [comment]
@ari-gold Can you add more info to this please? Such as a list of tasks for the revision. Thanks.

**Comment by suzannealdrich** [comment]
Here is a list of launch checklist we should definitely be covering in this article, in approximate order:

1. Schedule Backups for Development, Testing, and Production Environments
2. Add New Relic Performance Monitoring
3. Setup Pingdom alert on non-cached page
4. Ensure caching is properly configured for optimized load times
5. Enable cacheserver to improve performance for authenticated users
6. Site Audit Launch Check:
	* Run site audit checks for insecure and vulnerable code
	* Check for available plugin/module updates
	* Detect when too many plugins are installed 
	* Check for plugins or modules that are known to cause problems
	* Detect large files that should be served by CDN
	* Check database for large tables and correct storage engine
7. Post Apache Solr schema and index search results
8. Load Test common user scenarios
9. Verify redirection sends visitors to canonical domain
10. Test DNS settings and lower the record TTL prior to host switchover

**Comment by ari-gold** [comment]
* Setup redirects for URLs changing. Have plan to monitor and mitigate 404s post-launch to retain search rankings.

**Comment by andrewmallis** [comment]
If planning to use SSL, it should be enabled and the cert uploaded.
link to https://pantheon.io/docs/articles/sites/domains/adding-a-ssl-certificate-for-secure-https-communication/

**Comment by andrewmallis** [comment]
Normalizing URLs is also important. www / bare domain redirects are oft forgotten at the very least. Leaving the live-* domain in place also has poor SEO implications.

https://wikihub.berkeley.edu/display/drupal/Launching+a+Site#LaunchingaSite-Adddomainnormalizationcodetosites/default/settings.php

https://kalamuna.atlassian.net/wiki/display/KALA/Configuring+settings.php+on+Pantheon

**Comment by ari-gold** [comment]
Related marketing ebook: http://pantheon.io/sites/default/files/perfect-website-launch-pantheon-ebook.pdf
