### ISSUE TITLE
Use Pantheon Localdev to Develop Sites Locally Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4839]
Re: [Use Pantheon Localdev to Develop Sites Locally](https://pantheon.io/docs/localdev/)

Priority: Low 

## Issue Description:
Does the tool respect/consider .lando config files? 

## Suggested Resolution
Answer this as an FAQ

**Comment by rachelwhitton** [comment]
What's install path after cloning a site locally and is it configurable?

**Comment by joshkoenig** [comment]
The local path is `~/Localdev/site-name-slug` and is not (yet) configurable.

**Comment by EdwardAngert** [comment]
@rachelwhitton, I got a bit of clarifying to add to Josh's response:

**Does Localdev respect/consider .lando config files?**
> It will use whatever you have in a landofile on that first spin up, but currently there is no way to alter the landofile and have Localdev manifest those alterations beyond committing said alterations, destroying and then reiniting that site. In lando terms there is no way to “lando rebuild” through Localdev right now

I see this got labeled as `challenge`, so I'm leaving the relevant info here for now

**Comment by alexfornuto** [comment]
Thanks @EdwardAngert!

**Comment by alexfornuto** [comment]
It sounds like we should make a new FAQ sub-section on the `.lando` file in a Localdev project, and say that since Localdev uses lando that file is part of the initial site creation, but cannot be modified manually after that.

Another section could be made on the install path as Josh described.

**Comment by jfussion** [comment]
LocalDev considers `.lando` file.  PHP version from pantheon.yml/pantheon.upstream.yml is still followed.

If they have services specified in `.lando` LocalDev will return an error. Here's a sample .lando config that will affect LocalDev

```
name: docs-lando
recipe: drupal8
config:
  webroot: web
  php: 7.3

services:
  cache:
    type: redis:3.2
    portforward: 6380
```
