### ISSUE TITLE
Deleting a Site on Pantheon Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#4844]
Re: [Deleting a Site on Pantheon](https://pantheon.io/docs/delete-site/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Information about retaining delete sites is not mentioned. 

## Suggested Resolution:
Please clarify for customers information about retention of deleted sites on Pantheon and any implications concerning sites that have been deleted.

**Comment by alexfornuto** [comment]
Seeking the answers Conrad requested.

**Comment by EdwardAngert** [comment]
Closing after confirming with @allenfear that the warning at the top of [Deleting a Site on Pantheon](https://pantheon.io/docs/delete-site) is accurate.
