### ISSUE TITLE
GCSE - Sort by:

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#485]
[Sort results](https://support.google.com/customsearch/answer/2549537?hl=en) can be used to sort content based on stored keys. 

- [ ] Do we need **Sort by:** ?
- [ ] What do we want to sort by? Guides, Documentation, Blog posts? What should be included and what do we label it? 
- [ ] Determine the best way to add keys to content types - meta tags?

**Comment by bmackinney** [comment]
Closing for now. We can revisit this later if it becomes a nice to have.
