### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by vinmassaro** [pantheon-systems/documentation#4850]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/)

Priority: Low

## Issue Description:
The current "Before You Begin" section installs the latest Terminus release (2.x) but the plugin installs in steps 6, 7, and 8 install plugin versions for Terminus 1.x. 

## Suggested Resolution
Update docs so Terminus 2.x versions are installed across the board.

**Comment by EdwardAngert** [comment]
Thanks, @vinmassaro - I'll get a PR in to fix that
