### ISSUE TITLE
Add http://localhost in manual migrate doc under step 2 where you can add the url / domain.

### ISSUE THREAD

**Issue by jmcausing** [pantheon-systems/documentation#4858]
Priority: Low/Medium/High (choose one, remove the other options)

## Title

Add http://localhost in manual migrate doc under step 2 where you can add the url / domain.

## Description:

Under Step 2: Enter your current website URL, choose your site type (Drupal 7, Drupal 8, or WordPress,), and click Continue:

I think we should also add or mention http://localhost if they are working on local

Related chat: https://app.intercom.io/a/apps/xkegk7cr/inbox/inbox/conversation/22633764909#part_id=comment-22633764909-3300167453

Asked in Slack

## Path
https://pantheon.io/docs/migrate-manual/

**Comment by carl-alberto** [comment]
Thanks @jmcausing, added a PR for us to start with
