### ISSUE TITLE
Launch Essentials Doc Update add section in where to do a search-replace in db 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4859]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/redirects/)

Priority: Low

## Issue Description:
There are times that users are getting redirection errors or mixed content issues after they change the platform domain to their main domain eg. live-sitename.pantheonsite.io to example.com

## Suggested Resolution
There should be a part in the launch that WP users should do a search-replace of the platform domain eg. live-sitename.pantheonsite.io to example.com after they add their main domain

**Comment by carl-alberto** [comment]
Hi @alexfornuto, as far as I can remember, there was a PR regarding this in this doc https://pantheon.io/docs/guides/launch/configure-dns/ but seems it is gone? Can we reopen this or create another PR?

**Comment by alexfornuto** [comment]
Hi @carl-alberto. PR #5860 added the reference to the next page in the guide, which I think is a good place in the process for it. Is there an argument that it should be mentioned while configuring DNS, before setting the primary domain?

**Comment by carl-alberto** [comment]
Ah thanks for pointing that out @alexfornuto, I also missed spotting that part, and is still a common gotcha for users and new CSEs too, would it be good if we can highlight that section so it can be easily spotted? And possibly added in the final checklist https://pantheon.io/docs/guides/launch/next-steps/?

**Comment by alexfornuto** [comment]
I think we can make that happen :)

**Comment by alexfornuto** [comment]
PR created, so I'll re-close this issue.
