### ISSUE TITLE
Fix Broken Links in WordPress Doc Update suggest method to replace urls via plugin

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4861]
Re: [Fix Broken Links in WordPress](https://pantheon.io/docs/wordpress-broken-links/)

Priority: Low

## Issue Description:
Although we have tools in doing search-replace but not all users have the technical capability or hardware to run Terminus. When users try to use the plugin method and frustrate them finding out that there is a lot of search-replace plugin that do not work out of the box.

## Suggested Resolution
Suggest a plugin that worked before with a lot of users with added screenshots. One we've seen great success is https://wordpress.org/plugins/wp-migrate-db/

**Comment by alexfornuto** [comment]
This sounds like a good idea, but I'd be interested to know if anyone else from @pantheon-systems/documentation has expereince with this plugin and would suggest it.

**Comment by calmher** [comment]
+1 on this. 

I've more success in running WP Migrate DB plugin than Better Search and Replace plugin.  Encountered chats on this as well and I normally suggest the former to customers 👍

**Comment by carl-alberto** [comment]
Thanks for the feedback @calmher , added a PR for us to have something to start with @alexfornuto

**Comment by ataylorme** [comment]
+1 for WP Migrate DB. Delicious Brains is a great group of people making quality plugins.
