### ISSUE TITLE
Working with Cookies on Pantheon Doc Update troubleshooting guide on common issues

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4867]
Re: [Working with Cookies on Pantheon](https://pantheon.io/docs/cookies/)

Priority: Low

## Issue Description:
Common issues:
1) My cookie is not being saved/retrieved
2) My site is not being cached when I used this X plugin/module that uses this cookie
3) A plugin/module is using cookie_name, can I request it to be added in the https://pantheon.io/docs/cookies/#cache-busting-cookies cache varying cookie list?

## Suggested Resolution
Add a relevant troubleshooting section that addresses common cookie issues

**Comment by rubelyn** [comment]
Include tools they can use to check the cookie name and values.

**Comment by alexfornuto** [comment]
@ruthiehallarsis good idea! Do you know of any tools we can name?

**Comment by alexfornuto** [comment]
Will resolve by adding a callout to our Agency Partner list for help with advanced cookie configuration.

**Comment by carl-alberto** [comment]
Added the troubleshooting section PR on that page to get it started, feel free to correct and collect feedback from other resources @alexfornuto
