### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by justkristin** [pantheon-systems/documentation#4868]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

The changes noted in these lines are no longer make-able, as the lines do not seem to exist.
Remove the find .circleci/scripts/pantheon/ -type f | xargs chmod 755, line from the post-update-cmd section of scripts.
Remove the find tests/scripts/ -type f | xargs chmod 755 line from the post-update-cmd section of scripts.

## Suggested Resolution
Delete those lines?

**Comment by alexfornuto** [comment]
Good catch @justkristin! We've already [patched this](https://github.com/pantheon-systems/documentation/pull/4800) in the new version of our docs, which should be published in a few weeks. We're converting the whole stack to use Gatsby and a lot of the content needed to be reformatted, so I'm trying to avoid duplicate work on the master branch.

Thanks for contributing!
