### ISSUE TITLE
Drupal 8 and Composer on Pantheon Without Continuous Integration Doc Update 

### ISSUE THREAD

**Issue by justkristin** [pantheon-systems/documentation#4881]
Re: [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

Priority: Low

## Issue Description:

Sorry again. I was trying to make this work, and all was well until
 git add .
 git commit -m 'Drupal 8 and dependencies'
 git push --force

After git push --force, I am getting:

remote:
remote: PANTHEON ERROR:
remote:
remote: Changes to `pantheon.yml` detected, but there was an error while processing it:
remote:
remote: pantheon.yml:
remote: Validation failed with error:
remote: >   None is not of type 'object'
remote:
remote: while validating the following value:
remote: >   null
remote: >   ...
remote:
remote: To learn more about pantheon.yml, please see https://pantheon.io/docs/pantheon-yml/
remote:
remote:
To ssh://codeserver.devblahblahblahalbhalbhalblha.drush.in:2222/~/repository.git
! [remote rejected]   master -> master (pre-receive hook declined)

## Suggested Resolution

I wish I had one. I am not that bright.

**Comment by alexfornuto** [comment]
@justkristin have you run the file through a linter, as @sarahg's PR suggests?
