### ISSUE TITLE
Frequently Asked Questions Doc Update references to US data center

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4889]
Re: [Frequently Asked Questions](https://pantheon.io/docs/faq/)

Priority: Low/

## Issue Description:
There are references to US data center only

## Suggested Resolution
Reflect to the latest Regions that Pantheon offers

**Comment by EdwardAngert** [comment]
thanks, @carl-alberto!
I'm going to close this one and we'll see the effect once Gatsby is live
