### ISSUE TITLE
Platform Considerations Doc Update Drupal s3 can possibly bypass the 256mb large file system limit

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4891]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations/)

Priority: Low

## Issue Description:
Docs show that users cannot upload from the CMS if it goes beyond 256mb 

## Suggested Resolution
Internal discussions seem to indicate that it is possible https://pantheon.slack.com/archives/C03SRV7HB/p1562691152278800 and would need some final confirmation and input from those that tested it

**Comment by alexfornuto** [comment]
@carl-alberto Do I understand the linked thread correctly, that you were talking about a drupal module (considered "code"), and _not_ a file in terms of the platform?

**Comment by carl-alberto** [comment]
To clarify @alexfornuto, the modules(code in platform terms) involved in this doc https://pantheon.io/docs/drupal-s3 which when setuped properly, will bypass the 256mb file limit(files in platform terms) that is indicated in here https://pantheon.io/docs/platform-considerations#large-files at least for the Drupal part

**Comment by alexfornuto** [comment]
This page already references the S3 module, which puts files off of the platform and onto Amazon's.
