### ISSUE TITLE
Secure Runtime Access

### ISSUE THREAD

**Issue by markely** [pantheon-systems/documentation#4899]
Re: Secure Runtime Access

Priority: Medium

## Issue Description
We have this feature called Secure Runtime Access (SRA) and we don't have a lick of documentation telling exactly what it does or how it should work.

## Suggested Resolution
Get info from product, put into doc, publish, profit!
(we need something that details the feature for clients, and something internal that tells CSE how to enable it / support it / debug it)

Initial request:  https://github.com/pantheon-systems/documentation/issues/618
Follow up request: https://github.com/pantheon-systems/documentation/issues/3869

**Comment by EdwardAngert** [comment]
Thanks, @markely! 
I'm currently working with Product to get a proper guide together about SRA, what it does, and how to enable it. Coming soon!
