### ISSUE TITLE
Prevent /search result titles from continuing to 2nd line, getting cut off 

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#490]
Goal: `title text text ...`
![image](https://cloud.githubusercontent.com/assets/646061/7397780/9f629c50-ee5f-11e4-89e0-ad0d8062594f.png)

Current state: At @media (min-width: 992px)? widths, no elipses, wrap to 2nd line, cutoff.
![image](https://cloud.githubusercontent.com/assets/646061/7397824/d231c570-ee5f-11e4-92a3-8bbee89e7e15.png)

**Comment by rachelwhitton** [comment]
Issue Resolved
Screenshot:
![screen shot 2015-06-29 at 2 44 10 pm](https://cloud.githubusercontent.com/assets/10119525/8416748/5de8b672-1e6d-11e5-9c1d-9547b1ef3432.png)
