### ISSUE TITLE
Gandi Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by xq42** [pantheon-systems/documentation#4905]
Re: [Gandi Domain Configuration](https://pantheon.io/docs/gandi/)

Priority: Low

## Issue Description:

Doc describes how to add a CNAME record for subdomains added to the Pantheon dashboard.

## Suggested Resolution

Update instructions to account for recent dashboard change to only recommend A and AAAA records for all domains added to a site's Pantheon dashboard.

**Comment by EdwardAngert** [comment]
thanks, @xq42 ! this is fixed by #4892

**Comment by EdwardAngert** [comment]
reopening so that the referenced PR can close this on merge, which I think is probably a better way to do it

**Comment by EdwardAngert** [comment]
resolved by #4892
