### ISSUE TITLE
New Doc Proposal: Building a custom upstream with Build Tools/CI Workflow

### ISSUE THREAD

**Issue by vinmassaro** [pantheon-systems/documentation#4907]
Priority: Low

## Title
Building a custom upstream with Build Tools/CI Workflow

## Description
My team is beginning to work on a Drupal 8 university installation profile project and would like to use the Build Tools workflow to take advantage of the bundled tooling as part of our development process. We will treat the site it builds as the finished product, a departmental demo site. I would then like to use the resulting work as a custom upstream to spin up many other sites from the installation profile. Creating a custom upstream from the Build Tools repo is not possible because it does not contain the build artifact.

A second repo containing the build artifact would need to be created as the custom upstream source repo. Handling this led to a few ideas in a [Slack thread](https://pantheon-community.slack.com/archives/C2GJ3JG7Q/p1562611139412500):
- Push code to a secondary remote repo if an environment variable is set
- Use a Quicksilver hook from the demo site to trigger a CI job via API call

I'm opening this doc proposal to hopefully establish and document a repeatable procedure for how to best accomplish this.

## Outline
TBD

## Expected Audience
Organizations wanting to spin up many sites from a D8 custom upstream.

## Path
docs/guides/build-tools
docs/create-custom-upstream
docs/maintain-custom-upstream

**Comment by greg-1-anderson** [comment]
Using Quicksilver to trigger a CI job adds unnecessary complexity if it was a CI job that caused the deploy in the first place. Best to push to the custom upstream at the same time as the push to Pantheon right in the build step.

Using Quicksilver would be appropriate in workflows where there was no CI process (e.g. the "no CI workflow").

**Comment by ataylorme** [comment]
@vinmassaro thanks for starting a docs issue/discussion on this topic.

What I typically recommend when folks want to use Build Tools and Custom Upstreams is similar to what you are describing: use Build Tools to develop and maintain the custom upstream (diagram attached).

This consists of creating a Build Tools project, using it to develop the custom upstream, doing QA on the resulting Pantheon site that includes the build artifact. Then, when you are ready to release a new version of the custom upstream, push from the Pantheon site Git remote to a secondary remote for the GitHub repository hosting the Custom Upstream build artifact (this is a different/second GitHub repository from the one containing only the source that Build Tools creates).

The release/push to secondary remote step is often manual. However, you could use Quicksilver to automate it. I would agree with @greg-1-anderson that CI for that portion is overkill. You can add a second remote and push directly in the Quicksilver script, having it be triggered when a deployment to the live environment of the Pantheon QA site is made.

![Pantheon-CI-Custom-Upstream-Diagram](https://user-images.githubusercontent.com/2133004/62958438-8c280100-bdab-11e9-8fc0-5199a4c45e71.png)

**Comment by ataylorme** [comment]
@vinmassaro do you have enough info/are you comfortable taking the first pass at this doc and submitting a pull request?

**Comment by vinmassaro** [comment]
@ataylorme thanks for the diagram, this is helpful. I'm still a little unclear on the recommendation. @greg-1-anderson's comment sounds like we want to add a secondary target repo to push the build artifact as part of CI step, and your diagram makes it look like this would be a Quicksilver script configured to push to the secondary repo on a deploy to live. If it's the latter, it would be a PR against the quicksilver examples repo and a doc update. Do I have that right?

**Comment by ataylorme** [comment]
@vinmassaro the recommendation is to use the Build Tools workflow to build the custom upstream artifact, which gets deployed to a Pantheon site for testing/QA.

Once you are ready to make a release the contents of the Git repository for the Pantheon site, which will have the entire build artifact for the custom upstream, get pushed to a second Git remote for an external repository hosting the custom upstream. That repository will be the one Pantheon tracks for custom upstream updates in the child sites.

Don't get too hung up on _how_ the push from the custom upstream Pantheon QA site to the custom upstream build artifact repository happens. In my experience, releases don't happen that often and the step can be manual, with a dev on the team cloning the Pantheon build artifact site locally and pushing to the external Git repository for the custom upstream build artifact.

That step _could_ be automated but it is not necessary for the workflow. I think what we need here is a PR to this repository for a new doc explaining this workflow. There can be a brief section at the end talking about automating the custom upstream release push from the Pantheon build artifact site to the secondary external Git repository but the main point of the article would be to help those who aren't sure how to use build tools and custom upstreams together to wrap their head around the entire workflow.

**Comment by carolyn-shannon** [comment]
Let's put this on hold until @ataylorme has completed his work on the Build Tools guide, as it seems like a dependency for this.

**Comment by carolyn-shannon** [comment]
Blocked pending approval of [PR5151](https://github.com/pantheon-systems/documentation/issues/5151)

**Comment by sugaroverflow** [comment]
Thanks @alexfornuto for informing me about this issue!

I love the idea of more in-depth guides for Build Tools implementations! We are currently working on figuring out what next steps are for Build Tools and part of that includes what kinds of documentation is needed to better support the ways our clients are using it. Since this issue is over a year old and documentation will be addressed as a part of our scope for the future of the project, I'm going to ahead and close this out. We may reference in the next few months 😄  Thank you!
