### ISSUE TITLE
Relaunch Existing Pantheon Site Doc Update add FAQ section

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4922]
Re: [Relaunch Existing Pantheon Site](https://pantheon.io/docs/relaunch/)

Priority: Low

## Issue Description:
Site relaunch has some FAQs
1) Will the customer lose their preferred pricing?
2) Will the customer be double-billed after deleting and readding their card details?

Since we don't have an automatic way of migrating a site from one region to another, this might also affect this doc https://pantheon.io/docs/regions/#migrate-an-existing-site-to-a-new-region

## Suggested Resolution
No definite answer yet but would love to hear @ccorpus 's feedback regarding the FAQ sections as this involves billing

**Comment by EdwardAngert** [comment]
Considering the way a new site has to be created in a new region and the things we know about getting billed with site changes, I think @ccorpus and I can put an answer together for this. Assigning to me.

thanks, @carl-alberto !
