### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#4929]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso/)

Priority: Low

## Issue Description:

https://www.drupal.org/project/miniorange_saml makes SSO a lot easier and requires very little configuration

## Suggested Resolution
we should consider adding this as an alternative approach in the relevant docs

**Comment by alexfornuto** [comment]
@newtoid would you be a good SME to provide instruction on using this module? If not, do you know who is?

**Comment by alexfornuto** [comment]
Blocked while @newtoid is away.

**Comment by alexfornuto** [comment]
Reached out to @newtoid to schedule this.
