### ISSUE TITLE
Symlink Creation not Described Correctly

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#4934]
Re: [Using Extensions That Assume Write Access](https://pantheon.io/docs/assuming-write-access/)

Priority: Medium

## Issue Description:

I believe this line and the note below is inaccurate (or at least that I misunderstand it and cannot figure out how to get it to work):

ln -s ./wp-content/uploads/new-directory ./wp-content/path/plugin-expects-to-write-to

## Suggested Resolution

I think the command needs to be something more like this:

ln -s .../uploads/new-directory ./wp-content/path/plugin-expects-to-write-to

Also, the target, the first argument after the -s, is, as I understand it, relative to the folder the second argument is in, not to the current location in the console. The link name, the second argument, is relative to the current location.

**Comment by EdwardAngert** [comment]
@dficker, there was a fix for something related to this in #4813 
does that resolve the issue you spotted here?

**Comment by dficker** [comment]
That does I think make that examples section better, for sure.

What i think still is a problem is the 4th step in the "Create A Symbolic Link" part of the page.

I think the note below that step it is right that the second argument of `ln -s` is sensitive to the working directly, but the first argument, as I understand it, is in relationship to where the symlink is placed.

So, in this step, if you run the command as written, you'll end up with a file in this location:

`wp-content/path/plugin-expects-to-write-to`

That is a symlink to this location:

`wp-content/path/wp-content/uploads/new-directory`

As I described in the Suggested Resolution, that command would get you to the right location:

`wp-content/uploads/new-directory`

I could be wrong, but I've definitely wrote my fair share of symlinks just for these reasons before so I think I'm correct in how this works.

I've definitely fielded a number of support requests the past few months where they've made the symlinks wrong, although I'm not exactly clear on what part is confusing them, but i think it could be this.

**Comment by alexfornuto** [comment]
@dficker Right you are, Ken!

`ln` is annoyingly picky about paths and where you invoke it from:

```bash
➜  ~ cd tmp
➜  tmp mkdir -p wp-content/path/                        
➜  tmp mkdir -p wp-content/uploads/new-directory
➜  tmp ln -s ./wp-content/uploads/new-directory ./wp-content/path/plugin-expects-write-to
➜  tmp ls -alh wp-content/path 
...
...    plugin-expects-write-to -> ./wp-content/uploads/new-directory
```

I think we should adjust these instructions to always run `ln` from the directory containing the symlink, so relative paths can be called correctly:

```
➜  tmp cd wp-content/path 
➜  path ln -s ../uploads/new-directory plugin-expects-write-to
➜  path ls -alh
...
...    plugin-expects-write-to -> ../uploads/new-directory
```

@EdwardAngert do you concur?

**Comment by alexfornuto** [comment]
Adding Screenshots for syntax highlighting demonstrating the symlinks being broken or not:

![image](https://user-images.githubusercontent.com/2349184/63468871-7ca15b80-c42e-11e9-9c2a-c6e84a608f57.png)

![image](https://user-images.githubusercontent.com/2349184/63468880-82973c80-c42e-11e9-9094-e735d86963c6.png)
