### ISSUE TITLE
Please add A/AAAA record setup for Cloudflare with elimination of CNAME's - Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by jleetaylor2020** [pantheon-systems/documentation#4935]
[Cloudflare Domain Configuration](https://pantheon.io/docs/cloudflare)

Priority: High 

## Description
Please add A/AAAA record changes to doc to replace former CNAME rules

**Comment by alexfornuto** [comment]
@jleetaylor2020 please review #5137
