### ISSUE TITLE
Suggested Improvement to "Require HTTPS & Primary Domain" WordPress code snippet

### ISSUE THREAD

**Issue by philmprice** [pantheon-systems/documentation#4942]
Priority: Medium

## Title
Suggested Improvement to "Require HTTPS & Primary Domain" code snippet, prompted by security scan concern.

## Description
I may have an improvement to share for the "Redirect to HTTPS and the Primary Domain" WordPress code block at (https://pantheon.io/docs/redirects/).

My VP got in touch with me the other day and let me know that our redirect (using your suggested code block) failed a security scan because it was enforcing HTTPS & primary domain in a single redirect, whereas it needed to happen in two steps where it first switched to HTTPS using the same/original domain that was visited and *then* after it hopped over to HTTPS the primary domain could be enforced.

I didn't do anything fancy or new for the new block, I basically re-shaped the code that was already there to achieve the desired result.

[ Reference ]
https://www.sentinelstand.com/article/http-strict-transport-security-hsts-canonical-www-redirects

[ Reference Excerpt ]
RISK
Site redirects to a domain in a way that limits the security provided by HTTPS and HTTP Strict Transport Security (HSTS) headers; this leaves users vulnerable to being redirected to a spoofed/ malicious version of the site.

RECOMMENDATION
Any HTTP site should redirect the user to a secure (i.e. HTTPS) version of the same domain that was originally requested (or a higher-level/parent version of that same domain). For example, http://www.example.com should only redirect either to https://www.example.com or https://example.com. This redirect should be done before redirecting to any other domain or subdomain.

## Outline
The proposed code snippet that ensures the HTTPS enforcement happens first and *then* the primary domain enforcement is:

```
//  HTTPS & PRIMARY redirects, in sequence
if (isset($_ENV['PANTHEON_ENVIRONMENT']) && ($_ENV['PANTHEON_ENVIRONMENT'] === 'live') && php_sapi_name() != 'cli') {
  
  //  if not using HTTPS
  if (!isset($_SERVER['HTTP_USER_AGENT_HTTPS']) || $_SERVER['HTTP_USER_AGENT_HTTPS'] != 'ON' ) {

    // Name transaction "redirect" in New Relic for improved reporting (optional).
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    //  redirect to HTTPS
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://'. $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
    exit();
  }

  //  if LIVE environment
  if ($_ENV['PANTHEON_ENVIRONMENT'] === 'live') {
    //  use primary domain
    $primary_domain = 'www.example.com';
  } else {
    //  use the domain we're at
    $primary_domain = $_SERVER['HTTP_HOST'];
  }

  //  if not at primary domain
  if ($_SERVER['HTTP_HOST'] != $primary_domain) {

    // Name transaction "redirect" in New Relic for improved reporting (optional).
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    //  redirect to primary environment
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://'. $primary_domain . $_SERVER['REQUEST_URI']);
    exit();
  }
}
```

## Expected Audience
Anybody wanting to implement an HTTPS & primary domain redirect on their Pantheon site.

## Path
source/_docs/redirects

**Comment by alexfornuto** [comment]
Now that HTTPS is set from Pantheon.yml and the Primary domain can be set from the product, we'll resolve by taking the HTTPS redirection out of the fallback PHP snippet.

**Comment by alexfornuto** [comment]
So a lot has changed WRT how we handle redirection, HTTPS, and HSTS since this issue was submitted. @tmountjr and I have been discussing, and reached the following conclusions:

It's now best practice to enforce HSTS from `pantheon.yml`, and redirect to the primary domain from the Site Dashboard.

The PHP redirection snippet exists as a fallback for those not using the product Primary Domain redirect, and the HTTPS section is commented out for use by those who are also not using `pantheon.yml` to set HSTS.

With all this context, I'm going to close this issue without change, but I want to thank @philmprice for a detailed issue. We _may_ be following up with you to send some swag your way as a thank you (cc @EdwardAngert).
