### ISSUE TITLE
Enabling ClamAV for Drupal Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#4948]
Re: [Enabling ClamAV for Drupal](https://pantheon.io/docs/clamav/)

Priority: Low

## Issue Description:
Our screenshot shows a PHP notice and mentions that users can ignore it. That notice has been fixed ([https://www.drupal.org/project/clamav/issues/2810109](https://www.drupal.org/project/clamav/issues/2810109)), so we can remove that from our doc as well.

## Suggested Resolution
Update the screenshot of the settings page (we should show D8) and remove the note about safely ignoring the notice.

**Comment by chicagomom** [comment]
New screenshot for Drupal 8.
<img width="804" alt="clamav-settings" src="https://user-images.githubusercontent.com/993428/63201100-7899c600-c049-11e9-8e9d-b56dd8a6b42c.png">
