### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by angrytoast** [pantheon-systems/documentation#4950]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso/)

Priority: Medium

## Issue Description:
The section in https://pantheon.io/docs/shibboleth-sso/#drupal-configuration has a couple of issues:
- The recommended settings overrides use `1.15.x`, whereas the beginning of the documentation uses `1.16.x` as the example
- The settings path here relies on using the "Download Method" and doesn't reflect the proper location of simplesamlphp when using the "Composer Method"

## Suggested Resolution
- Update the example version
- Update the settings path when using the Composer Method

**Comment by alexfornuto** [comment]
Thanks for reporting this @angrytoast! I just merged #4977 which addresses your first bullet point.

Regarding the settings path when using the composer method, step 5 of the Composer Method tab symlinks the settings file from the same location as the download method, so there shouldn't be any need to specify a different path for the two methods.

If I'm wrong about this, please feel free to elaborate and I'll re-open the issue.
