### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4952]
Re: [Build Tools](https://pantheon.io/docs/guides/build-tools/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
404 link to https://circleci.com/account/api

## Suggested Resolution
Remove or replace link

**Comment by EdwardAngert** [comment]
thanks, @primerg !
The link to `https://circleci.com/account/api` works when you're logged in to circle ci
