### ISSUE TITLE
Drupal Commerce on Drupal 8 Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4953]
Re: [Drupal Commerce on Drupal 8](https://pantheon.io/docs/guides/drupal-8-commerce/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
* 404 link to https://circleci.com/account/api

## Suggested Resolution
Remove or replace link

**Comment by EdwardAngert** [comment]
thanks, @primerg !
The link to https://circleci.com/account/api works when you're logged in to circle ci
