### ISSUE TITLE
Frontend Performance Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4954]
Re: [Frontend Performance](https://pantheon.io/docs/guides/frontend-performance/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
* 500 link to https://wordimpress.com/wordpress-css-and-js-cache-busting/

## Suggested Resolution
Remove or replace link

**Comment by EdwardAngert** [comment]
thanks, @primerg !
I'm working on fixing that link and found some markdown that needs attention in that doc as well - thanks!
