### ISSUE TITLE
New Relic APM Pro Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4956]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
* 404 error - link https://learn.newrelic.com/courses/intro_apm
* 404 error - link https://learn.newrelic.com/courses/apm_advanced

## Suggested Resolution
Remove or replace link

**Comment by EdwardAngert** [comment]
thanks @primerg! I've merged a PR into the gatsby branch, which will replace master in the coming weeks. Once that's live, it will automatically close this issue. thanks!
