### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update 

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4957]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
* 403 error - link http://drupalcode.org/project/cache_backport.git/blob_plain/HEAD:/INSTALL.txt

## Suggested Resolution
Remove or replace link

**Comment by EdwardAngert** [comment]
thanks @primerg! I've merged a PR into the gatsby branch, which will replace master in the coming weeks. Once that's live, it will automatically close this issue. thanks!
