### ISSUE TITLE
Contributors Update

### ISSUE THREAD

**Issue by primerg** [pantheon-systems/documentation#4959]
Re: [Contributors](https://pantheon.io/docs/contributors/)

Priority: Low

## Issue Description:
Reported Technical SEO Problem
Missing images
https://pantheon.io/sites/default/files/styles/540x540_top/public/David_Needham540x540.png
https://pantheon.io/sites/default/files/styles/540x540_top/public/JessiNew.jpg
https://pantheon.io/sites/default/files/styles/540x540_top/public/Dustin LeBlanc.jpg
https://pantheon.io/sites/default/files/styles/540x540_top/public/JMP_9650-800x800.jpg
https://pantheon.io/sites/default/files/styles/540x540_top/public/d0d17cbd-a445-4a69-bdc7-62b39bb90069.jpeg

## Suggested Resolution
Replace author image

**Comment by EdwardAngert** [comment]
thanks @primerg! I started a PR to address this issue

**Comment by alexfornuto** [comment]
Closed by #4968, thanks!
