### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#4971]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/drush/)

Priority: Low

## Issue Description:
https://pantheon.io/docs/drush/#registry-rebuild
This drush command has been deprecated for Drupal 8

https://www.drupal.org/project/registry_rebuild
https://www.drupal.org/project/registry_rebuild/issues/1785672

## Suggested Resolution
A note warning that this command will not work for Drupal 8

**Comment by alexfornuto** [comment]
Thanks @CFin86! I'm seeing a lot of other formatting fixes needed as well. I'm on it!
