### ISSUE TITLE
Temporary File Management Doc Update 

### ISSUE THREAD

**Issue by jfussion** [pantheon-systems/documentation#4972]
Re: [Temporary File Management](https://pantheon.io/docs/tmp/#default-temporary-path)

Priority: Medium

## Issue Description:
Changing file_temporary_path is not possible on Drupal 7 since it is being overwritten by PRESSFLOW_SETTINGS here: https://github.com/pantheon-systems/drops-7/blob/default/includes/bootstrap.inc#L759-L787

## Suggested Resolution
Remove recommendation to replace temp path.

**Comment by jfussion** [comment]
@greg-1-anderson Is this a bug? Or we don't really allow changing the `file_temporary_path`?

**Comment by alexfornuto** [comment]
Reached out to @greg-1-anderson for input.

**Comment by carolyn-shannon** [comment]
@greg-1-anderson do you have any input on this?

**Comment by alexfornuto** [comment]
@greg-1-anderson 
![image](https://user-images.githubusercontent.com/2349184/70463897-6bcf3100-1a83-11ea-9b16-7ac704060221.png)

**Comment by carolyn-shannon** [comment]
Check to see if this is also true for the Drupal 8 version.

**Comment by jfussion** [comment]
In Drupal 8, the configurations are in settings.pantheon.php so I believe it is possible to override the temp path via settings.php for D8.

For D7, a possible temporary workaround would be to modify the file_temporary_path value inside the $_SERVER['PRESSFLOW_SETTINGS'] which might not be a good idea?

**Comment by jfussion** [comment]
To set D7's temp path, we need to modify the PRESSFLOW_SETTINGS. Ticket reference #461683

```PHP
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {

  // Pressflow will override whatever we set here unless we override Pressflow first.

  $pressflow = json_decode($_SERVER['PRESSFLOW_SETTINGS'], TRUE);

  $pressflow['conf']['file_temporary_path'] = $pressflow['conf']['file_directory_temp'] = 'sites/default/files/private/tmp';

  $_SERVER['PRESSFLOW_SETTINGS'] = json_encode($pressflow);

}
```

**Comment by greg-1-anderson** [comment]
Sorry, didn't see this notification earlier. I commented on #5732

**Comment by alexfornuto** [comment]
Closing without merge per discussion in #5732 5732
