### ISSUE TITLE
GoDaddy Domain Configuration Doc Update to remove the CNAME section

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#4973]
Re: [GoDaddy Domain Configuration](https://pantheon.io/docs/godaddy/)

Priority: Low

## Issue Description:
This doc do not reflect the latest changes that CNAMES are not used anymore and should be replaced by A and AAAA records

## Suggested Resolution
Remove CNAMES  and should be replaced by A and AAAA records

**Comment by EdwardAngert** [comment]
thanks, @carl-alberto!
This will be closed by #4892 once Gatsby is live

**Comment by carl-alberto** [comment]
Thanks for pointing that out @EdwardAngert , we encountered a couple of confused users following the outdated GoDaddy guide that we have. Sorry was not able to dig that previous PR up

**Comment by EdwardAngert** [comment]
no worries, @carl-alberto ,  it's been understandably confusing with our transition to Gatsby. thanks for being on the lookout!
resolved by #4892
