### ISSUE TITLE
Terminus commands have confusing -- separator

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#5009]
Re: [Terminus Examples](https://pantheon.io/docs/terminus/examples)

Priority: Medium

## Issue Description
Users are reporting issues with commands that are separated with `--` (not as `--flag` but as a command separator)

## Suggested Resolution
Commands still work without the `--` separator. Remove them wherever possible

**Comment by alexfornuto** [comment]
Pinged @EdwardAngert to determine if there's anything about this we still need to track; sounds like those `--` are there for a reason after all.

**Comment by alexfornuto** [comment]
So I spoke with @TeslaDethray and confirmed that our use of `--` in our docs is correct. The original reports may have referred to the Commands page, where we are using output from `terminus --help` that included brackets around the `--`'s.

I'm going to consider this closable by #5229 unless we get more information.
