### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#5011]
Re: [Modules and Plugins with Known Issues](https://pantheon.iomodules-plugins-known-issues)

Priority: Low

## Issue Description:

Under the WordPress plugins section, plugins listed after "Timthumb" do not have anchor links. 

<img width="282" alt="a" src="https://user-images.githubusercontent.com/14119666/62908020-7533df80-bda8-11e9-940c-f1cd803d0b32.png">

## Suggested Resolution

Add links for the following plugins so we can easily share it to customers:

TubePress Pro
Unbounce Landing Pages
UNLOQ Two Factor Authentication (2FA)

and so forth.

**Comment by alexfornuto** [comment]
This is a known issue with the Gatsby build, ToC submenus are being cut off when they're too long. We're tracking it internally,
