### ISSUE TITLE
Parsing nginx Access Logs with GoAccess Doc Update 

### ISSUE THREAD

**Issue by purdy** [pantheon-systems/documentation#5012]
Re: [Parsing nginx Access Logs with GoAccess](https://pantheon.ionginx-access-log)

Priority: Medium

## Issue Description:
Can't download the access_getlogs.sh script. Results in 404.

## Suggested Resolution
Update link to right location.

**Comment by alexfornuto** [comment]
Thanks for reporting the issue @purdy! I think I have a solution in the works.
