### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by NeoMeteor** [pantheon-systems/documentation#5015]
Re: [Terminus Manual](https://pantheon.io/terminus/install)

Priority: Low

## Issue Description:

Docs lists **_terminus remote:drupal_** and **_terminus remote:composer_** as Terminus commands but they did not exist on my and other’s Terminus. Turns out those commands are only available if you add specific plugins to Terminus:
https://github.com/pantheon-systems/terminus-drupal-console-plugin for **_terminus remote:drupal_**, and https://github.com/pantheon-systems/terminus-composer-plugin for **_terminus remote:composer_**. 

## Suggested Resolution

Within the Terminus Commands doc (https://pantheon.io/docs/terminus/commands) there needs to be a note regarding the commands being dependent on those plugins being added to Terminus, to avoid confusion if/when the commands are not found.

**Comment by alexfornuto** [comment]
I imagine that this is the result of the commands data file being created from a Terminus install with these plugins. I suspect the solution is to update the new deployments process to re-create these files in the CircleCI environment.

**Comment by alexfornuto** [comment]
Resolved by #5163
