### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by markely** [pantheon-systems/documentation#5026]
Re: [Modules and Plugins with Known Issues](https://pantheon.iomodules-plugins-known-issues)

Priority: Medium

## Issue Description:
Contents along the right side of the page does not show all of the WordPress plugins with known issues.  It cuts off after timthumb.

## Suggested Resolution
Show all the plugins with known issues in the menu.

**Comment by alexfornuto** [comment]
Thanks @markely! This is a known issue that we're tracking internally.
