### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#5029]
Re: https://pantheon.io/docs/terminus/get-started/legacy

Priority: Low 

## Issue Description:
There should be a table comparing 0.x and 1.x command structures using this source: https://github.com/pantheon-systems/documentation/blob/master/source/docs/assets/terminus/compare.json

## Suggested Resolution

**Comment by alexfornuto** [comment]
@rachelwhitton we decided to remove that table, since the 1.x structure has been the de-facto for a few years now and previous versions are EOL.
