### ISSUE TITLE
Managing Site Plan Changes and Chargeback for EDU  Sites Doc Update 

### ISSUE THREAD

**Issue by markely** [pantheon-systems/documentation#5043]
Re: [Managing Site Plan Changes and Chargeback for EDU  Sites](https://pantheon.iomanaging-edu-plus)

Priority: Low

## Issue Description:
Broken image links on this page

## Suggested Resolution
https://giphy.com/gifs/reaction-453QsWPQj5bsQaqp8M
:-)  You guys are the best.  I hope this at least made you smile.

**Comment by alexfornuto** [comment]
@markely looks like it's already been fixed, can you confirm?

[fix it!](https://www.youtube.com/watch?v=8ZCysBT5Kec)

**Comment by markely** [comment]
I don't see any broken images on this page anymore.  I don't recall which one(s) were broken.

I appreciate you following [this complex methodology](https://www.youtube.com/watch?v=yo3uxqwTxk0) of fixing all the issues.

Happy Friday!
