### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update Layout Builder

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5080]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docsmodules-plugins-known-issues)

Priority: Low

## Issue Description:
This core module Layout Builder returns an error when trying to be activated `Fatal error: require(): Failed opening required '/srv/bindings/bindingIDxxxxxxxxx/code/vendor/composer/../../web/core/lib/Drupal/Core/Layout/Icon/SvgIconBuilder.php'` 

## Suggested Resolution
Outline steps on how to make the module work

**Comment by alexfornuto** [comment]
@carl-alberto @sarahg does that mean this module/plugin no longer has any issues, across all CMS types/versions it's available for (that Pantheon supports)?

**Comment by sarahg** [comment]
@alexfornuto right, it's not an issue with current D8 core — I would not recommend adding this to docs.

**Comment by alexfornuto** [comment]
Thanks!
