### ISSUE TITLE
Global CDN Caching for High Performance with Drupal and WordPress Doc Update 

### ISSUE THREAD

**Issue by SparxITSolutions** [pantheon-systems/documentation#5082]
Re: [Global CDN Caching for High Performance with Drupal and WordPress](https://pantheon.io/docsglobal-cdn-caching)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by alexfornuto** [comment]
@SparxITSolutions This is an empty issue, are you planning on filling it out or was this a mistake?
