### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update add FacetWP

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5110]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docsmodules-plugins-known-issues)

Priority: Low

## Issue Description:
FacetWP conflicts with New Relic in the platform

## Suggested Resolution
Disable New Relic https://facetwp.com/new-relic-compatibility/

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! This it ready for copy review.
