### ISSUE TITLE
Bots and Indexing on Pantheon Doc Update 

### ISSUE THREAD

**Issue by brettgoldhammer** [pantheon-systems/documentation#5118]
Re: [Bots and Indexing on Pantheon](https://pantheon.io/docsbots-and-indexing)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description: 
There is an error in the wordpress filter example code at the bottom of the page. The "User Agent" directive throws an error when applied in this manner.

## Suggested Resolution

$robots_txt =  "User Agent: * \n";

should be

$robots_txt =  "User-agent: * \n";

**Comment by alexfornuto** [comment]
Thanks @brettgoldhammer!
