### ISSUE TITLE
WordPress and Drupal Core Updates Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5128]
Re: [WordPress and Drupal Core Updates](https://pantheon.io/docscore-updates)

Priority: Medium

## Issue Description:
Broken image link in: 
Apply Upstream Updates via the Site Dashboard
Navigate to the Code tab in the Site Dashboard on the Dev environment to check available updates:![upstream updates../images/dashboard/updates-available-2.png)

## Suggested Resolution
Fix broken image

**Comment by alexfornuto** [comment]
Fixed, thanks @carl-alberto!
