### ISSUE TITLE
DOC-9 Anchor Misbehavior on Git FAQs Doc Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5138]
Re: [Git FAQs](https://pantheon.io/docs/git-faq)

Priority: Medium

## Issue Description:
When clicked, Anchor IDs navigate to incorrect section. e.g., clicking on "How do I manually resolve conflicts" anchor takes one to #how-do-i-resolve-conflicts-when-updating-core. 

## Suggested Resolution

**Comment by alexfornuto** [comment]
Tracking internally, thanks!
