### ISSUE TITLE
Resetting Passwords Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5155]
Re: [Resetting Passwords](https://pantheon.io/docs/resetting-passwords)

Priority: Low

## Issue Description:
Under the section **['Option C: Reset your password directly in the database (advanced)'](https://pantheon.io/docs/resetting-passwords#option-c-reset-your-password-directly-in-the-database-advanced-1)**
The linked wordpress.org page has been moved to [here](https://wordpress.org/support/article/resetting-your-password/#through-mysql-command-line)
https://i.imgur.com/RJDR6lW.png
## Suggested Resolution
Change url from https://codex.wordpress.org/Resetting_Your_Password#Through_MySQL.2FMariaDB_Command_Line to https://wordpress.org/support/article/resetting-your-password/#through-mysql-command-line

**Comment by alexfornuto** [comment]
Thanks @CFin86!
