### ISSUE TITLE
Document how to rename a branch for Multidev compatibility

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#516]
![image](https://cloud.githubusercontent.com/assets/646061/7437978/f706fbaa-f011-11e4-9f01-a8039602d3ca.png)
The 11-character limit means that branches with names exceeding the limit pushed to Pantheon cannot turn into CDE's. The solution is to rename the branch. 
Aritcle and first comment offer the procedure: http://www.benjaminlhaas.com/blog/locally-and-remotely-renaming-branch-git
thanks to @alphex for the prompt in power-users.

**Comment by nataliejeremy** [comment]
@bmackinney Think it's an update to this doc? https://pantheon.io/docs/articles/sites/multidev/

**Comment by bmackinney** [comment]
#637
