### ISSUE TITLE
External Libraries on Pantheon Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5166]
Re: [External Libraries on Pantheon](https://pantheon.io/docs/external-libraries)

Priority: Medium

## Issue Description:
In the section 'Drupal ImageMagick Configuration' ImageMagick includes jpegtran, and there aren't any ImageMagick-specific settings in ImageAPI Optimize in Drupal 8 (perhaps there are in D7?), customers assume this refers to setting the path to tools like jpegtran that are included within ImageMagick. A clarification that this does not work in D8 would be helpful.

Mentioning the module on https://pantheon.io/docs/modules-plugins-known-issues would be useful as well. 

## Suggested Resolution

A section mentioning that jpegtran and other image optimization software is not installed on the platform. A quick workaround is to use a 3rd-party module like reSmush.It or a local application like ImageOptim.

**Comment by alexfornuto** [comment]
Reached out to @CFin86 to clarify what and where.
