### ISSUE TITLE
Search broken when #addsearch is used

### ISSUE THREAD

**Issue by mbaynton** [pantheon-systems/documentation#5167]
## Steps to reproduce
1. Perform a search at pantheon.io/docs, and navigate to a search result.
2. Click back button to return to /docs.
3. Attempt to search for something else.

## Expected result
Second search pulls up results.

## Actual result
No results dropdown appears. Refreshing doesn't help. Removing the #addsearch url component and reloading restores functionality.

**Comment by carolyn-shannon** [comment]
This is an issue w/addsearch. I've filed a ticket and will follow up when they have a fix.

**Comment by carolyn-shannon** [comment]
AddSearch confirmed an issue on their end. They've updated their code, and the issue has been resolved.
