### ISSUE TITLE
Platform and Custom Domains Doc Update 

### ISSUE THREAD

**Issue by jfussion** [pantheon-systems/documentation#5171]
Re: [Platform and Custom Domains](https://pantheon.io/docs/domains#primary-domain)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
The suggestion to Redirect to HTTPS and the Primary Domain is still via PHP
## Suggested Resolution
replace with the same content from https://pantheon.io/docs/guides/launch/redirects

**Comment by alexfornuto** [comment]
Resolved by #5170, thanks @jfussion!
