### ISSUE TITLE
Using Terminus to Create and Update Drupal Sites on Pantheon Doc Update 

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#5172]
Re: [Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs//guides/terminus-drupal-site-management)

**Priority**: Low

## Issue Description:
Since the docs site is built in Gatsby, the Alert component renders the text inside literally, meaning the markdown links don't get processed.

![Terminus alert box](https://user-images.githubusercontent.com/1759794/65932186-31398000-e3d2-11e9-93b5-dee15a870d3a.png)

## Suggested Resolution
An absolute link would work, but unsure if this type of issue has previously been documented and fixed elsewhere so it can still use relative links.

**Comment by alexfornuto** [comment]
Hi @kyletaylored thanks for reporting - The issue here is spacing. With a newline above and below each component line, the markdown will be parse properly. I'll fix shortly.

**Comment by kyletaylored** [comment]
Heyy, there we go. Thanks!
