### ISSUE TITLE
Switching Sites from HTTP to HTTPS Doc Update 

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#5176]
Re: [Switching Sites from HTTP to HTTPS
](https://pantheon.io/docs/http-to-https)

Priority: High

Can we update this to remove the Drupal/WordPress-specific instructions and indicate the new, YAML-based approach?

**Comment by alexfornuto** [comment]
Nice catch @davidstrauss! Please take a look at #5184 for the resolution.
