### ISSUE TITLE
Manage Plans in the Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by karenpantheon** [pantheon-systems/documentation#5179]
Re: [Manage Plans in the Site Dashboard](https://pantheon.io/docs/site-plan)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Typo in the Downgrades section: "No prorated refunds or credits will be **_issues_** for site downgrades."

## Suggested Resolution
Correct typo to "issued".

**Comment by alexfornuto** [comment]
Thanks @karenpantheon!
