### ISSUE TITLE
Fix published_time meta to show actual published date from gh

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#518]
Options: 

1. Remove the tag.
1. Add logic so that the build preserves the last edited time of the source (query Github's API for the data). 
1. Add published and modified date fields to the frontmatter for all articles, (see guides)

**Comment by rachelwhitton** [comment]
This may be out of my scope, I'm not well versed in metadata. 

I'm not sure if this gives any insight into the issue:
```
$ curl -i https://api.github.com/pantheon-systems/documentation/blob/master/source/docs/articles/architecture.md
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Thu, 07 May 2015 19:34:52 GMT
```
Seems that using the Github API isn't an option until we figure out whats resetting the build date in sculpin?

**Comment by rachelwhitton** [comment]
published_time and modified_time removed in #645 

- Todo:

- [ ] Add published_time and modified_time metadata via queries to GitHub API
- [ ] Meta scrape to test outputs
