### ISSUE TITLE
Modify enablements to include ID

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5181]
Priority: Medium

## Issue
Tracking enablements by ID facilitates accurate attribution in docs analytics. As attribution efforts expand, it's essential to have this in place to understand the impact of outreach efforts in docs.

## Suggested Resolution
- Modify gatsby/src/components/enablement/index.js to accommodate ID argument for constructed a tags.
- Modify existing enablements to include ID argument.
- Update/create internal documentation to explain enablement creation/use of ID tags for analytics.

**Comment by carolyn-shannon** [comment]
Waiting for tracking codes setup information.

**Comment by carolyn-shannon** [comment]
Moving to GTM to facilitate cookie compliance tracking.

**Comment by alexfornuto** [comment]
Closed by #5323
