### ISSUE TITLE
Reducing Large Repositories Doc Update 

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#5188]
Re: [Reducing Large Repositories](https://pantheon.io/docs/reducing-large-repos)

Priority: Low

## Issue Description:
A reader reports that the content may be out of date:

>"If you follow these commands and push up the cleaned repo... and then clone again from source... you're back to the original size.
>Also the command for 'git push origin :refs/tags/[tag]' throws a 
>
>```
>remote: Tag removal rejected. The tag ""pantheon_live_9"" is a deployment tag and therefore >cannot be
>remote: deleted. You should push a new deployment tag instead.
>```
>
>error for most tags in a pantheon repo."

## Suggested Resolution

Review and re-rest. CC @hengkit as the author.

**Comment by alexfornuto** [comment]
Reached out to @hengkit over Slack to see if he has any useful insight before I go diving into this.

**Comment by alexfornuto** [comment]
Kit Deferred to @Hornswoggles as the SME to ask. Pinged on Slack.

**Comment by dficker** [comment]
From what i know about Git, it seems to me like it should work. They are pushing the revised history to the remote via these commands:

`git push origin --force --all`
`git push origin --force --tags`

It's true that if they clone the remote right away, it might not be smaller right then. At some point, Git will do a cleanup operation and then purge the stuff no longer needed. Users don't have access to run that on the remote, but at some point, it will happen and then it will be smaller.

At least that's my thoughts. But you don't have to take my word for it....

**Comment by alexfornuto** [comment]
While testing I found that the script in step 5 of **Prune and Optimize Large Repositories** does not work:

```
➜  code git:(master) ✗ git rev-list $BRANCHES -- | while read rev; do git ls-tree -lr $rev | cut -c54- | grep -v '^ '; done | sort -u | perl -e '
while (<>) {
  chomp;
  @stuff=split("\t");
  $sums{$stuff[1]} += $stuff[0];
}
print "$sums{$_} $_\n" for (keys %sums);
' | sort -rn > ../large_files.txt
fatal: bad revision 'astra
jupiter
multi1
plugin-test
sendgrid
sucuri
updates
upgradeto5
viscomposer
master'
➜  code git:(master) ✗ cat ../large_files.txt 
➜  code git:(master) ✗
```
