### ISSUE TITLE
Traffic Limits and Overages Doc Update 

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/documentation#5203]
Re: [Traffic Limits and Overages](https://pantheon.io/docs/traffic-limits)

Priority: Low

## Issue Description:

Platform metrics are sometimes at odds with Google Analytics or other tracking services - i.e. less traffic is reported than the platform metrics suggest. This leads to confusion as to why there is such a discrepancy.

## Suggested Resolution

Provide a clear explanation of why there is a difference between external tracking and platform metrics.

**Comment by alexfornuto** [comment]
@slashzero thanks for the issue! @joshkoenig just added a new [section](https://pantheon.io/docs/traffic-limits#why-doesnt-pantheons-traffic-metrics-match-my-other-analytics) covering this very concern recently in #5175, have you seen it? If so, what additional information do you think we should include?

**Comment by slashzero** [comment]
@alexfornuto hadn't seen that - seems to fit exactly with what I was suggesting, thanks!
