### ISSUE TITLE
Implement Segment Gatsby plugin

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5206]
Priority: High

## Implement Gatsby plugin for Segment 
In order to achieve accurate customer journey conversion metrics for docs (Q4 CS KR), implement Segment plugin and configure page click tracking and event naming consistent with Pantheon event categories to facilitate analytics. https://www.gatsbyjs.org/packages/gatsby-plugin-segment-js/ 

## Suggested Resolution
Download, configure and implement Segment plugin.
Dependencies: Access tokens

**Comment by alexfornuto** [comment]
Moving to "Not Ready' while awaiting access tokens.

*Note to self:* tokens will probably need to go into CircleCI as environment variables.

**Comment by alexfornuto** [comment]
Closed by #5262
