### ISSUE TITLE
WordPress Best Practices Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#5211]
Re: [WordPress Best Practices](https://pantheon.io/docs/wordpress-best-practices)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Missing content re: a common attack vector for WP sites

## Suggested Resolution
Work with SMEs to document recommendation to disable XML-RPC 

cc @ksenour 

WIP -- Kaylan and Rachel to follow up w/stronger details soon.

**Comment by rachelwhitton** [comment]
Good example ticket to reference: 268644

@ksenour are you open to scheduling some time on the calendar for us to work on a PR together?

**Comment by ksenour** [comment]
Rachel - if you can find a block on my calendar, go for it. :)
