### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update add troubleshooting for BUSY Redis

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5212]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis)

Priority: Low

## Issue Description:
Once in a while, a site throws a random error php error `RedisException: BUSY Redis is busy running a script.`

## Suggested Resolution
Add the suggested resolution from BUGS-1821

**Comment by alexfornuto** [comment]
Thanks @carl-alberto!
