### ISSUE TITLE
Cloudflare Domain Configuration Doc Updates

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#5219]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs//cloudflare)

Priority: Low

## Issue Description: 
- Cloudflare screenshots and directions like "scroll down" are no longer accurate (their UI has changed a bit)

https://pantheon.io/docs/cloudflare#option-2-use-cloudflares-cdn-stacked-on-top-of-pantheons-global-cdn

## Suggested Resolution
- Update directions and screenshots to reflect UI changes

**Comment by alexfornuto** [comment]
If anyone has a stacked CDN config we could access, that would be great. Otherwise, I suppose we'll need to set one up to test and document from.

**Comment by sarahg** [comment]
@alexfornuto I've got one I'm testing other things with, I could pick this up if nobody beats me to it. You can do all this with a free CF account, too, though. Here's the new screenshot we'll want:

<img width="1112" alt="cloudflare_https1" src="https://user-images.githubusercontent.com/667501/66876177-67503580-ef76-11e9-8904-937475ec1118.png">

**Comment by alexfornuto** [comment]
![myhero](https://user-images.githubusercontent.com/2349184/66934222-c7d78500-efff-11e9-8252-714c0efcc818.gif)
