### ISSUE TITLE
Metrics in the Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#5223]
Re: [Metrics in the Site Dashboard](https://pantheon.io/docs/metrics)

Priority: Low/Medium/High (choose one, remove the other options)
Low

## Issue Description:
Doc mentions "known bots and crawlers do not count towards site traffic limits". 

## Suggested Resolution
Confirm which known bots and crawlers do not count toward site traffic limits. 
cc: @joshkoenig @EdwardAngert

**Comment by EdwardAngert** [comment]
@ari-gold is the list of "known bots and crawlers" available for public consumption, or is that not really something we're looking to share?

**Comment by EdwardAngert** [comment]
closing per Slack conversation - the list of known bots isn't something we're making public
