### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by brenda003** [pantheon-systems/documentation#5227]
Re: [Build Tools](https://pantheon.io/docs//guides/build-tools/configure)

Priority: Low

## Issue Description:

Two images missing from this page, near the bottom in step 7. Instead of images it displays:

![Sync commit from Pantheon to GitHub](../../../images/pr-workflow/pantheon-circle-github.png)

![Sync commit from GitHub to Pantheon Multidev](../../../images/pr-workflow/github-circle-multidev.png)

## Suggested Resolution

Syntax or path issue?

**Comment by alexfornuto** [comment]
Thanks for letting us know @brenda003! The image paths probably need more `..`, or less `..`. The amount of `..` isn't _just right_. I'll resolve.

**Comment by alexfornuto** [comment]
I was wrong! It was some HTML cruft.
