### ISSUE TITLE
Traffic Limits and Overages Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#5234]
Re: [Traffic Limits and Overages](https://pantheon.io/docs/traffic-limits)

Priority: Low

## Issue Description:
Customers often compare sessions in Google Analytics to visits shown in Pantheon metrics. 

## Suggested Resolution
If sessions are not measured by Pantheon metrics, provide a clear explanation on why they are not measured. cc: @EdwardAngert

**Comment by alexfornuto** [comment]
@ccorpus Does the information added in #5175 not provide the answers you seek?
