### ISSUE TITLE
Build Tools Doc Update - Indicate which token scopes are needed

### ISSUE THREAD

**Issue by twfahey1** [pantheon-systems/documentation#5237]
Re: [Build Tools](https://pantheon.io/docs//guides/build-tools/create-project)

Priority: Low

## Issue Description:
Unless I've overlooked it somewhere, I don't believe we currently indicate what scopes should be selected for the Github personal access token, would be good to indicate the minimum required scope for the access token, so one doesn't need to guess and make one that is either too restrictive or too permissive.

![image](https://user-images.githubusercontent.com/6699959/67120288-9e109080-f1ae-11e9-8f2a-507db0da5dca.png)

## Suggested Resolution
Update docs to reflect which Github personal access token scopes should be selected when creating the token for build tools.

**Comment by alexfornuto** [comment]
CC @ataylorme to see if this is factored into [ongoing work](https://github.com/pantheon-systems/documentation/pull/5194) to that doc, and/or if we should update the current version in the meantime.

**Comment by sugaroverflow** [comment]
Good question!

@rvtraveller helped me discover this in our codebase: https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/8ee1affcd91af81c480938afd0dff1efe7ea56d6/src/API/GitHub/GitHubAPITrait.php#L62

Looks like we need the following scopes:
- 'repo' (required)
- 'delete-repo' (optional)

_ delete-repo is optional - only if you want to use the build:env:obliterate command which will delete your GitHub repo as part of project cleanup_

@twfahey1 if you'd like, can you put up a PR to mention these in the docs explicitly - I can review it!

**Comment by alexfornuto** [comment]
This was resolved in #5444
