### ISSUE TITLE
Fix links to former architecture articles

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#524]
Follow on to #522  - search and replace old links for new. Redirects are in place for search and existing links, but we need to fix this here and in the dashboard @rachelwhitton

**Comment by rachelwhitton** [comment]
- [ ] All about application containers
- [ ] IPv6 Addresses on Pantheon
- [ ] Date and Time
- [ ] Varnish Caching for High Performance
- [ ] Caching - Advanced Topics
- [ ] Debugging Cache
- [ ] Considerations for Google Analytics and PANTHEON_STRIPPED
- [ ] Testing Varnish
