### ISSUE TITLE
WordPress and Drupal Core Updates Doc Update add CONFLICT (modify/delete): pantheon.upstream.yml

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5241]
Re: [WordPress and Drupal Core Updates](https://pantheon.io/docs/core-updates)

Priority: Low

## Issue Description:
Common issue where way outdated WP/Drupal core files throw an error updating from the dashboard:  
`CONFLICT (modify/delete): pantheon.upstream.yml deleted in HEAD and modified in upstream/master. Version upstream/master of pantheon.upstream.yml left in tree`

## Suggested Resolution
Outline steps on how to resolve issue

**Comment by alexfornuto** [comment]
Thanks @carl-alberto!
