### ISSUE TITLE
WP Core in subdirectory via wp-cli.yml in web docroot

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5247]
Re: [twitter thread](https://twitter.com/taupecat/status/1184948304263688198)

Priority: Low

## Document configuration for WP Core in subdirectory
Add documentation for using WP core in a subdirectory by putting wp-cli.yml in a the `web` docroot.

## Suggested Resolution

- Verify the proposed solution works.
- Add to documentation

**Comment by alexfornuto** [comment]
This would be an addition to [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot).

From the thread, the contents of `wp-cli.yml` contains:

```
path: <nested-dir>
```

**Comment by carolyn-shannon** [comment]
n.b. Pantheon supports [one application per site](https://pantheon.io/docs/platform-considerations#one-application-per-site). Should note this in whatever gets created to avoid confusion.

**Comment by alexfornuto** [comment]
After reviewing the [blog post](https://taupecatstudios.com/2019/10/22/wordpress-own-directory-pantheon/) and discussing internally, we're electing not to add this to our documentation. This in an edge case with some big caveats (empty upstream, no core updates from Pantheon).
