### ISSUE TITLE
Enabling Solr on Drupal 8 Doc Update 

### ISSUE THREAD

**Issue by Kingdutch** [pantheon-systems/documentation#5252]
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8)

Priority: High (choose one, remove the other options)

## Issue Description:
SOLR is not actually supported with Drupal 8 on Pantheon. The docs should be updated to reflect this. The documentation suggests using the `search_api_solr` module version 1.x. 

This module will be unsupported starting December 2019, meaning it's unsafe to use.

Additionally [it already states](https://www.drupal.org/project/search_api_solr/) for that version

> The minimum supported Solr version is Solr 4.5.1.

Which means that it probably doesn't already work with Apache Solr v3.6 which is [what's supported by Pantheon](https://pantheon.io/docs/solr).

## Suggested Resolution

Update the documentation to indicate to users that they can not safely use the SOLR service of Pantheon on Drupal 8 until a newer SOLR version is supported by Pantheon.

**Comment by joshkoenig** [comment]
This is actually untrue. The solution is to document that `search_api_solr` works with our `search_api_pantheon` module, which it does. We actually don't allow the CMS to talk "directly" to Solr under any circumstances, so the underlying version number is neither here nor there.

There _are_ a number of features our Solr service doesn't presently support (multilingual, unicode, geospacial, etc), but this is a separate concern from underlying Drupal content indexing and full text search.

It would be helpful to document a HOWTO for setting up `search_api_solr` with Drupal 8.
