### ISSUE TITLE
Cron for Drupal Doc Update - Fix Elysia Cron Disable Steps

### ISSUE THREAD

**Issue by dbr031** [pantheon-systems/documentation#5254]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron)

Priority: Low

## Issue Description

In the section _Disable Cron_, the page describes how to disable the _poor man's cron_ from running on regular visitor requests. The steps are correctly defined when the _Elysia Cron_ module is _not_ enabled. However, under the _Drupal 7 and Elysia Cron_ subsection, the steps on how to disable the _poor man's cron_ are incorrect.

Following the steps currently outlined  on the page (i.e. checking the _Global disable_ option) will **completely disable cron**, preventing all Drupal cron jobs from running, even when invoked through `drush`, `cron.php`, or Elysia's `cron.php`. In turn, this will most likely affect Pantheon's platform-based invocation of cron too, as opposed to just disabling cron on visitor requests.

## Suggested Resolution

Instead of suggesting to enable the _Global disable_ checkbox on the Elysia Cron settings page, the correct suggestion would be to update the _Run cron on visitor's requests, every_ setting, found inside the _Installation settings_ fieldset.

Here is a sample screenshot with the corrected step:
![Image displaying how to disable poor man's cron](https://i.imgur.com/x9RUE9x.png)

This select field exactly mimics the _Run cron every_ select field shown when _Elysia Cron_ is not installed.

**Comment by alexfornuto** [comment]
Looking for SMEs to help confirm.

**Comment by alexfornuto** [comment]
Pining @oseldman who offered to weigh in.

**Comment by alexfornuto** [comment]
Linking #5790 to address when this is in progress.

**Comment by dbr031** [comment]
@alexfornuto I'd argue the two issues are independent of one another. #5790 would affect some or all screenshots **except** for the one in section _Drupal 7 and Elysia Cron_, which this issue is about. As that section is specifically about D7 & Elysia.

To assist reviewing in case anyone does ever weigh in: The _Global disable_ option sets the variable `elysia_cron_disabled` to `TRUE`. This is checked early in `elysia_cron_run()` (unless `$ignore_disable` is passed in as TRUE), and the function aborts when this check passes. The way Elysia is implemented it `dupal_exist()`s shortly after `elysia_cron_run()`, thus no other `hook_cron` implementations are invoked. (There is an `--ignore-disable` flag when running `drush elysia-cron run`, which bypasses this check, but I doubt this is commonly used, and I'd be surprised if cron is triggered by Pantheon that way.)
This is why the _Global disable_ option fully disables all cron tasks from running, and should not be confused with wanting to just disable Drupal 7's regular `index.php`requests from invoking cron. The latter is handled by the _Run cron on visitor's requests, every_ form field as mentioned in the OP.

**Comment by alexfornuto** [comment]
>  I'd argue the two issues are independent of one another.

@dbr031 You're right. They're bundled because the work of updating screenshots can be done easily enough while someone is reviewing this issue. The page is due for a full review anyway.

Thanks for the additional information! Since I'll be likely the one who ends up doing this review, and I'm inexperience with Drupal cron, this really helps.
