### ISSUE TITLE
Automate Downloading Logs from the Live Environment - use rsync to download logs

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#527]
Revise script located in [Automate Downloading Logs from the Live Environment](https://pantheon.io/docs/articles/sites/downloading-live-error-logs/) so that rsync is used. 

Update existing doc with new script.

**Comment by rachelwhitton** [comment]
Todo:
- [ ] Revise script to use rsync instead of SFTP

**Comment by bmackinney** [comment]
@ari are you going to take this one?  If so, consider adding to the PR's attached to #359

**Comment by ari-gold** [comment]
@bmackinney Yes, it's on the roadmap with no ETA.

**Comment by ari-gold** [comment]
The following seems to work, but I'm going to test again to see what happens with log rotation
```
# Replace SITE with value from Dashboard URL
SITE=xxxxxxxxxxx
ENV=live
for app_server in `dig +short appserver.$ENV.$SITE.drush.in`;
do
  rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' $ENV.$SITE@appserver.$ENV.$SITE.drush.in:logs $app_server
done
```

**Comment by rachelwhitton** [comment]
@ari-gold can you test again and let us know if the above snippet works after log rotation? Thanks in advance!
