### ISSUE TITLE
Restore content for how to override max-age for HSTS header

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#5278]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: pantheon.yml and deleted hsts doc page

Priority: Medium? 

## Issue Description
Restore content for how to override max-age for the HSTS header via a plugin or module, as an alternative to the 1 year TTL imposed by pantheon.yml's `enforce_https` configuration for `full`

## Suggested Resolution
Find a good home to reinsert the D7/D8/WP methods as another way to manage HSTS outside of pantheon.yml
https://github.com/pantheon-systems/documentation/commit/28d615aa70f35ac93f382a77d9a801b6b12e54a2#diff-7ca93af42a85bfd886e526d0601864b9L14-L102

**Comment by rachelwhitton** [comment]
I was testing the D7 HSTS module, and found that if you don't override the default for `enforce_https`, the application sends the header twice? So we should suggest users turn it off in pantheon.yml if they're going to manage it elsewhere

I set max-age to 400 in the HSTS module configuration
max-age 300 comes from the pantheon.upstream.yml configuration (transitional)

```
╭─rachel in [~]
╰─➤ $ curl -I https://dev-rachel-d7-hsts-test.pantheonsite.io
HTTP/2 200
cache-control: public, max-age=900
content-language: en
content-type: text/html; charset=utf-8
etag: W/"1572543002-0"
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Thu, 31 Oct 2019 17:30:02 GMT
server: nginx
strict-transport-security: max-age=400
strict-transport-security: max-age=300
x-drupal-cache: HIT
x-frame-options: SAMEORIGIN
x-generator: Drupal 7 (http://drupal.org)
x-pantheon-styx-hostname: styx-fe2-a-5d5d6985d5-cv7jb
x-styx-req-id: 12864d60-fc04-11e9-b1b5-4e707f63d268
date: Thu, 31 Oct 2019 17:30:11 GMT
x-served-by: cache-mdw17366-MDW
x-cache: HIT
x-cache-hits: 1
x-timer: S1572543011.363534,VS0,VE1
vary: Accept-Encoding, Cookie, Cookie
x-robots-tag: noindex
age: 8
accept-ranges: bytes
via: 1.1 varnish
content-length: 7154

```

**Comment by rachelwhitton** [comment]
Definitely need to turn it off in pantheon.yml when managing via Plugin or Module, if the application sends 2 hsts headers the result in an invalid policy: 
"Strict Transport Security (HSTS) Invalid Server provided more than one HSTS header"

https://www.ssllabs.com/ssltest/analyze.html?d=dev%2drachel%2dd7%2dhsts%2dtest.pantheonsite.io&s=23.185.0.2&latest

Strict Transport Security (HSTS) | Invalid   Server provided more than one HSTS header
-- | --




Strict Transport Security (HSTS) | Invalid   Server provided more than one HSTS header
-- | --




Strict Transport Security (HSTS) | Invalid   Server provided more than one HSTS header
-- | --

**Comment by alexfornuto** [comment]
@rachelwhitton I think I understand what you're asking for here, and can probably find a good place in the docs for that information. But first I want to know:

 - What benefit would a customer get from using a plugin or module instead of setting it via the platform? Note that customers can set the value in `pantheon.yml` to `transitional` if they want a lower TTL.

 - If there is no benefit, should we resolve more simply with a warning that customers should not use a plugin/module to enforce HSTS?

**Comment by alexfornuto** [comment]
Spoke to @rachelwhitton. A customer might want to use a plugin/module to have more selective control over their TTL. 180 days is the requirement for A+ from ssllabs.
