### ISSUE TITLE
Enabling Solr for WordPress Doc Update 

### ISSUE THREAD

**Issue by tgillstar** [pantheon-systems/documentation#5306]
Re: [Enabling Solr for WordPress](https://pantheon.io/docs/wordpress-solr)

Priority: Low

## Issue Description:
The anchor link on the right sidebar for "Known Issues/Limitations" goes to the "Install and Configure Plugin" section.

## Suggested Resolution
The anchor link on the right sidebar for "Known Issues/Limitations" should to the "Known Issues/Limitations" section.

**Comment by carolyn-shannon** [comment]
Duplicate of #5307
