### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by brenda003** [pantheon-systems/documentation#5316]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues)

Priority: Low

## Issue Description:

Add Popup Builder Plugin https://wordpress.org/plugins/popup-builder/

Plugin issue with sites with multiple application containers. Patch provided by customer but not fully tested.

## Suggested Resolution

Patch provided by Kurtis Shaner https://gist.github.com/kshaner/7fcbc7e3e967c5694fd38638bff1cc17/revisions

**Comment by alexfornuto** [comment]
@brenda003 what's the issue that this patch solves?

**Comment by brenda003** [comment]
Ah sorry @alexfornuto! The issue is with that it's storing a JSON encoded option in the options table with the file path, which doesn't work properly on plans with multiple containers. Sample image attached. Does that clarify?

![image](https://user-images.githubusercontent.com/347326/68720673-de242280-0564-11ea-8f60-9846b7772356.png)

**Comment by alexfornuto** [comment]
[Patch](https://wordpress.org/support/topic/absolute-path-causes-issues-on-environments-with-multiple-containers/) submitted to plugin author.
