### ISSUE TITLE
Build Tools Guide: Add section on existing sites

### ISSUE THREAD

**Issue by chriscalip** [pantheon-systems/documentation#5325]
Priority: Low/Medium/High (choose one, remove the other options)

## Title
Add sub-section of creating a local instance of an existing site at guide:
https://pantheon.io/docs/guides/build-tools

## Description
https://pantheon.io/docs/guides/build-tools makes sense from perspective of creating a new site.
I was coming from a perspective .. of not creating a new site but trying to help out build existing site.
I got confused with this guide.

## Expected Audience
Developers.

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by alexfornuto** [comment]
I think the resolution to this would be to reference the [Relaunch]() doc, as changing an existing site over to use build tools is not recommended. Pinging @pantheon-systems/devrel for input.

**Comment by carolyn-shannon** [comment]
@sugaroverflow please take a look with an eye to whether this is appropriately resolved by a reference to the Relaunch doc, as above.

**Comment by sugaroverflow** [comment]
I agree. Currently, build tools does not support conversion of an existing site so the Relaunch doc sounds like the best place to direct people. 

There is ongoing work on on a new build tools [project convert command](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/316) if you'd like to keep an eye on that or help with testing @chriscalip.

**Comment by sugaroverflow** [comment]
Closing out this issue, please take any questions to the convert command if you're looking for specifics on moving an existing site over. Thanks!
