### ISSUE TITLE
WordPress Known Issues Doc Update wp ftp related issues in test, live and git mode

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5332]
Re: [WordPress Known Issues](https://pantheon.io/docs/wordpress-known-issues)

Priority: Low

## Issue Description: 

It seems that the solution of adding `define('FS_METHOD', 'direct');` in `wp-config` has been solving a lot of issues in **test**, **live** and **git mode** with these 2 common cases: 

- **Warning that appears in test, live and git mode which is related to this file core file wp-admin/includes/class-wp-filesystem-ftpext.php after upgrading to WP 5.3**

- **FTP form that only appears in test, live and git mode**

Instead of listing all plugins and themes that are causing these issues, might it be better to add it to this page?

**Comment by alexfornuto** [comment]
@carl-alberto I'm working on implementing this, but I'm also wondering; is there any harm in adding `define('FS_METHOD', 'direct');` to our WP upstream? It seems like it would solve a lot of issues.

**Comment by carl-alberto** [comment]
@alexfornuto For the past year, I haven't seen anyone go back and complained about the side effects of using that fix so that is +1 for me, might be a good one to raise with the CSE team and our WP upstream maintainer as it might be a good addition in the wp-config file

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! We'll try to follow up with the powers that be.
