### ISSUE TITLE
Establish standard for user/site-specific modification of code-snippets.

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#534]
@nataliejeremy please do some research and present options in this comment. We need to standardize on something, add it to the style guide, and then modify existing instances. That task can be combined with #262 .

**Comment by bmackinney** [comment]
For reference, @rachelwhitton discovered #533 .

**Comment by nataliejeremy** [comment]
@bmackinney Do you mean standards for how to display code snippets?

**Comment by nataliejeremy** [comment]
Twilio uses {} but we can't support that.I'll keep looking for others, but I think we need to create  our own standard. Something like: 

### Code Snippets
Any bits of code should be wrapped in backticks.  Any standalone code blocks should use [backtick code fencing](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks "Markdown extra fenced code blocks.")

When you include placeholder content in snippets that change per user or environment, enter the placeholder text in angle brackets (< >) within the code snippet, and in the text that follows describe what the user must replace it with.  

**Example:**  
```
terminus site clear-caches --site=<site> --env=<env>
```
**Note**: Replace the value in the brackets with your information.

Twilio example:
![twilio_cloud_communications_-_apis_for_voice__voip__and_text_messaging](https://cloud.githubusercontent.com/assets/9138609/7525726/c8eaea34-f4c0-11e4-94a6-7c629a75ed59.png)

**Comment by nataliejeremy** [comment]
Heroku Example: 
![heroku](https://cloud.githubusercontent.com/assets/9138609/7527635/655bd548-f4d2-11e4-8683-e0b8bb9d440d.png)

**Comment by rachelwhitton** [comment]
I'm in favor of using Heroku's example @nataliejeremy @bmackinney 

The following illustrates using **#** vs **< >**

```
<div class="alert alert-info" role="alert">
<strong>Note</strong>: Replace <code>#site</code> with your site name, and <code><env></code> with the environment (dev, test, or live). You can see a list of all your sites by running <code>terminus sites list</code></div>
```
Renders the following:
![screen shot 2015-05-08 at 11 09 11 am](https://cloud.githubusercontent.com/assets/10119525/7540288/ccdbd25e-f572-11e4-8c74-c874d399115f.png)

+1 for using #

**Comment by nataliejeremy** [comment]
@rachelwhitton @bmackinney That's my preference too

**Comment by bmackinney** [comment]
Good job thinking about the edge case @rachelwhitton.

**Comment by ari-gold** [comment]
# makes sense in the context of JQuery, but not sure it makes sense for other cases.

The Heroku example @nataliejeremy shared uses #query and [your key here]. 

Seems like angle brackets make sense and could be escaped to work in an alert. 

Another option is to use an actual value instead of a placeholder, like https://example.com or live-example.pantheon.io, etc. You'll see that type of thing, e.g., on https://devcenter.heroku.com/articles/using-the-cli

**Comment by rachelwhitton** [comment]
Revisiting this after talking with @ari-gold - I'm changing my vote from # to < > 

We should use < > characters within markdown and `&lt;` `&gt;` within the alert div tags. 
### Example:
```
terminus site wipe --site=<site> --env=<env>
<div class="alert alert-info" role="alert">
<strong>Note</strong>: Replace <code>&lt;site&gt;</code> with your site name, and <code>&lt;env&gt;</code> with the environment (dev, test, or live). You can see a list of all your sites by running <code>terminus sites list</code></div>
```
![screen shot 2015-05-28 at 3 03 53 pm](https://cloud.githubusercontent.com/assets/10119525/7869888/28bccd5c-054b-11e5-96de-6c705fe5c471.png)

@nataliejeremy whatcha think?

**Comment by nataliejeremy** [comment]
I like it. If we can put example/placeholder text in the brackets, we should even be able to remove the note unless it's a complex code example that needs more explanation.
