### ISSUE TITLE
Multidev environment to merge

### ISSUE THREAD

**Issue by pkmondal** [pantheon-systems/documentation#5353]
Priority: Low

## Issue Description
I have faced one issue for Multidev environment to merge switching from dropdown. Unable to select the item at first attempt after login. In my case, I have three item facilitator, lms and v2. I am trying to select lms, but the dropdown is closed three or two times. As you can see from my screencast  https://youtu.be/ib5yPJUuMnA and https://youtu.be/qT8NBr8TPJU

Step to reproduce:

Step - 1:
1. Login to your pantheon account.
2. You should have Multidev environment to merge. Try to select the environment to merge. see it dropdown is closed three or two times. After then it is ok.

Environment:
Microsoft Windows 10 Pro 10.0.17763 Build 17763
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

Note: Do not take as blame. I like the product pantheon.io. Fix it if necessary.

Prasanta Kumer Mondal
SQAE at Sourcetop Inc.

**Comment by alexfornuto** [comment]
Hi @pkmondal. That's definitely strange behavior. I would suggest opening a support ticket to discuss this issue and report upstream as needed. This repo concerns the documentation site and contents.

If you talk to support, be sure to include what OS and browser you're using. You should also try it in a browser window without any extensions or plugins that may be interfering.
