### ISSUE TITLE
Traffic Limits and Overages Doc Update 

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/documentation#5354]
Re: [Traffic Limits and Overages](https://pantheon.io/docs/traffic-limits)

Priority: Low

## Issue Description: 

Examples of included traffic - user asked about XML-RPC requests and admin-ajax heartbeat requests - would it be useful to identify some examples of included traffic for clarity?

**Comment by alexfornuto** [comment]
CC @joshkoenig to weigh in on examples of included but not obvious traffic.

**Comment by joshkoenig** [comment]
Currently we highlight the following types of traffic:

- API requests and AJAX requests.
- Browsers/users that block cookies or javascript, including adblockers or private mode.
- Users that close the browser before the tracking script loads.
- A page where there is no tracking code, or where a javascript error prevents the tracking code from firing.
- Automated traffic from bots or load testing.
- Content pre-fetching by browsers or apps.

Likely what would serve our customers better would be to give examples for all of these cases, possibly bringing it out of the FAQ and elevating it to a primary section.

**Comment by alexfornuto** [comment]
Thanks for weighing in @joshkoenig! I agree that this doc could use a bit of restructuring to help highlight important information. We'll take a pass at that, and also see what we can do to add resources on the "what to do about it" side of high traffic situations.

**Comment by joshkoenig** [comment]
I do not believe it's fruitful for us to document or suggest "what to do about it" other than paying your bill.

There's a highly diverse set of circumstance that lead to high traffic. There's no way the Docs site can be certain to give correct advice and it's irresponsible for us to set people down a path of investing valuable hours of time with no payoff.
