### ISSUE TITLE
Restoring an Environment from a Backup Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#5363]
Re: [Restoring an Environment from a Backup](https://pantheon.io/docs/restore-environment-backup)

Priority: Medium

## Issue Description:
Failed restores in this scenario — https://pantheon.io/docs/restore-environment-backup#restoring-large-sites — can leave a site with missing file uploads, and fixing these up can take a very, very long time (days) if you have to go the rsync/manual restore route. Let's spell out clearer directions for how to safely restore a large site.

## Suggested Resolution
Include step-by-step directions for restoring just your code and DB with Terminus (`terminus backup:restore`).

Maybe add an example of restoring a single directory within Files using rsync.

Internal ref: Desk #274743

**Comment by alexfornuto** [comment]
Thanks @sarahg - I added `help wanted` in case anyone with experience using `terminus backup:restore` wants to take a stab at documenting this before it gets to the top of our queue.
