### ISSUE TITLE
PhP 7.4 Release

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5365]
Re: [Upgrade PHP Versions](https://pantheon.io/docs/php-versions)

Priority: Medium

## Issue Description:
- [PhP version 7.4](https://www.php.net/releases/7_4_0.php) release

## Suggested Resolution
- Update Upgrade PhP Versions page and related

**Comment by AronNovak** [comment]
:+1: Do we have an ETA on this?

**Comment by carolyn-shannon** [comment]
@AronNovak no ETA yet - build tools and other components are actively being tested. The [Changelog](https://pantheon.io/docs/changelog) will announce when it's ready to roll.

**Comment by AronNovak** [comment]
https://v74-php-info.pantheonsite.io/ - this is accessible now
