### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by twfahey1** [pantheon-systems/documentation#5374]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues)

Priority: High (choose one, remove the other options)

## Issue Description:
Hyperlink for WP All Import/Export incorrectly goes to wrong plugin

## Suggested Resolution
Fix link to point at WP All Import/Export

**Comment by alexfornuto** [comment]
@twfahey1 the header link goes [here](http://www.wpallimport.com/), which _looks_ like the right place... What is the correct link?

**Comment by alexfornuto** [comment]
@twfahey1 was referring to the ToC link, which was incorrect in a previous build (most likely do to [this bug](https://github.com/gatsbyjs/gatsby/issues/18000)). Fixed in current build by....bug randomness :roll_eyes:
