### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site - Missing steps associated with cloned composer directory

### ISSUE THREAD

**Issue by jcandan-achieve** [pantheon-systems/documentation#5377]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert#prepare-to-deploy)

Priority: High

> **Note:** No criteria given in CONTRIBUTING for choosing a priority grade.

## Issue Description
Under **Create a New Composer Project**, `$site-composer` is not defined prior to the command example (also referred to as `my-site-composer` directory elsewhere).

The guide then assumes you’ve changed directory into that new composer based project folder for the remainder of the guide

## Suggested Resolution
Provide an export variable command as is currently done for the `$site` variable.

**Comment by alexfornuto** [comment]
Thanks for reporting this @jcandan-achieve! `$site-composer` doesn't needed to be defined, because Bash (and ZSH) will concatenate:

```
$ export site=aSiteName
$ echo $site-composer
aSiteName-composer
```

But I'll review your PR and clean up instances of `my-site-composer` that don't belong.
