### ISSUE TITLE
January 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5378]
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by carolyn-shannon** [comment]
### Drupal 8.8.0 
Update to Drupal 8.8.0. For more information, see https://www.drupal.org/project/drupal/releases/8.8.0

_Originally posted by @greg-1-anderson in https://github.com/pantheon-systems/documentation/issues/5269#issuecomment-561906114_

**Comment by carolyn-shannon** [comment]
### Drupal 7.68 
Update to Drupal 7.68. For more information, see https://www.drupal.org/project/drupal/releases/7.68

_Originally posted by @greg-1-anderson in https://github.com/pantheon-systems/documentation/issues/5269#issuecomment-561890675_

**Comment by greg-1-anderson** [comment]
Automation scripts can't find the Changelog any longer because the title pattern changed.

Will the Changelog title remain "<MONTH> <YEAR> Changelog" hereafter? I don't mind what you call it, as long as it's consistent.

**Comment by greg-1-anderson** [comment]
### WordPress 5.3.1

For more information, see https://wordpress.org/news/2019/12/wordpress-5-3-1-security-and-maintenance-release/

**Comment by carolyn-shannon** [comment]
Thanks @greg-1-anderson! Yes, title will now include year so it's easier to find the correct one.

**Comment by garydylina** [comment]
### Traffic Restriction

Most [UDP traffic](https://en.wikipedia.org/wiki/User_Datagram_Protocol) originating from website containers has been blocked in order to prevent platform abuse.

**Comment by greg-1-anderson** [comment]
### Drupal 7.69 
Update to Drupal 7.69. For more information, see https://www.drupal.org/project/drupal/releases/7.69

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.1 
Update to Drupal 8.8.1. For more information, see https://www.drupal.org/project/drupal/releases/8.8.1

**Comment by greg-1-anderson** [comment]
### Drupal 8.7.11 
Update to Drupal 8.7.11. For more information, see https://www.drupal.org/project/drupal/releases/8.7.11

**Comment by greg-1-anderson** [comment]
### WordPress 5.3.2
Update to WordPress 5.3.2. For more information, see https://wordpress.org/news/2019/12/wordpress-5-3-1-security-and-maintenance-release/

**Comment by greg-1-anderson** [comment]
### Pantheon SSH behavior change

`terminus drush` and `terminus wp` will now prefer to use the binary found in `vendor/bin` over the version installed by Pantheon, if the site has installed its own version via Composer. (See the [Build Tools Workflow](https://pantheon.io/docs/guides/build-tools) and the [No CI Workflow](https://pantheon.io/docs/guides/drupal-8-composer-no-ci) guides for details on managing a site with Composer.)

**Comment by carolyn-shannon** [comment]
#### Special Note on Updating to Drupal 8.8.x 

Drupal 8.7.x sites updating to Drupal 8.8.x require a manual update of  `settings.pantheon.php` to follow updated Drupal 8.8.x recommendations:

- Use `$settings["file_temp_path"]` instead of `$config[system.file][path][temporary]`
- Use `$settings['config_sync_directory']` instead of `$config_directories[CONFIG_SYNC_DIRECTORY]`

@greg-1-anderson does this work?

**Comment by carolyn-shannon** [comment]
Asking @alexfornuto to follow up w/re-worded language here for changelog
