### ISSUE TITLE
Use Pantheon Localdev to Develop Sites Locally Doc Update 

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#5402]
Re: [Use Pantheon Localdev to Develop Sites Locally](https://pantheon.io/docs/localdev)

Priority: High

## Issue Description:
No documentation for how to get latest features/bug fixes available in the Beta version

## Suggested Resolution
Add section about Beta Testing to get latest features and bug fixes, with instructions:

1. Select *Settings* on left menu
2. In the *Current Version* section you’ll see an option to *Switch to Edge*

**Comment by joshkoenig** [comment]
Looks good to me!
