### ISSUE TITLE
Add Hummingbird to known WP plugin issues

### ISSUE THREAD

**Issue by tmountjr** [pantheon-systems/documentation#5409]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: Modules and Plugins with Known Issues

Priority: Low

## Issue Description
Discovered with one of our clients that Hummingbird was trying to serve a `.css` that consisted of the HTML of Pantheon's 401 page (the page served when a site is locked). Working theory is that the site was locked and Hummingbird tried to compile the assets directly on the filesystem, and when it requested the source CSS files, those files required authorization and returned the 401 error instead of the contents of the actual files, and Hummingbird simply included the error text in the compiled file.

The contents of the curl command (obscured the domain):
```
$ curl https://dev-[sitename].pantheonsite.io/wp-content/uploads/hummingbird-assets/[redacted].css
/**handles:parent-style**/
<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title>Pantheon | Site Locked</title><style type='text/css'>body{background-color:#000;color:#fff;font-family:Arial,sans-serif;font-size:16px;line-height:1.5;margin:0;padding:32px;text-align:center}svg{max-width:100%;height:auto;width:400px}p{margin:0 auto;max-width:40em}</style></head><body><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 177"><defs><style>.a{fill:#efd01d}.b{fill:#fff}
      </style>
    </defs>
    <path d="M0 0h480v177H0z"/>
    <path class="a" d="M26.8 19.96L39.39 49.5H23.36l5.3 13h32.49L26.8 19.96zM69.52 127.5l-5.37-13h-7.43l-10.62-25h-6.67l10.62 25h-18.9l34.93 42.54-12.59-29.54h16.03z"/>
    <path class="b" d="M73.84 75.5c.39 0 1.31-.49 1.31-5s-.92-5-1.31-5H51.46l4.25 10h18.13zM60.8 87.5h15c.4 0 1.31-.49 1.31-5s-.92-5-1.31-5H56.56zM73.84 101.5H53.62l4.25 10h16c.39 0 1.31-.49 1.31-5s-.94-5-1.34-5zM75.84 89.5H48.53l4.25 10h23.06c.4 0 1.31-.49 1.31-5s-.91-5-1.31-5z"/>
    <path class="b" d="M73.84 101.5H53.62l4.25 10h16c.39 0 1.31-.49 1.31-5s-.94-5-1.34-5zM75.84 89.5H48.53l4.25 10h23.06c.4 0 1.31-.49 1.31-5s-.91-5-1.31-5z"/>
    <path class="b" d="M45.25 87.5l-5.09-12h2.43l5.1 12H58.5l-9.34-22H25.83c-1.8 0-2.78 0-3.59 2.6-1 3.11-1.08 9-1.08 20.4s.11 17.29 1.08 20.4c.81 2.6 1.8 2.6 3.59 2.6h20.46l-10.14-24h9.09zM162.15 68.53h-11l-16 41h11.22l2.81-7h14.57l2.65 7h11.28zm-10 26l4.37-13.12h.11l4.32 13.12h-8.8zM120.34 68.5h-16.19v41h11v-14h5.56c9.23 0 14.41-4 14.41-13.61.01-9.34-6.03-13.39-14.78-13.39zm-3.84 19h-1.35v-10h1.35c4.11 0 7.61-.08 7.61 5.05.01 4.95-3.77 4.95-7.6 4.95zM327.15 93.5l11 .02V84.5h-11v-7h15v-9h-26v41h26v-10h-15v-6zM231.15 79.5h10l.06 30h10.94v-30h10v-11h-31v11zM296.15 84.5h-15v-16h-11v41h11v-16h15v16h11v-41h-11v16zM368.65 79.5a9.5 9.5 0 1 1-9.5 9.5 9.51 9.51 0 0 1 9.5-9.5m0-11a20.5 20.5 0 1 0 20.5 20.5 20.5 20.5 0 0 0-20.5-20.5zM425.12 91.46L407.5 68.5h-10.35v41h11.04l-.04-23 16.84 23h11.16v-41h-11l-.03 22.96zM212.12 91.46L194.5 68.5h-10.35v41h11.04l-.04-23 16.84 23h11.16v-41h-11l-.03 22.96zM442.85 76.67a7.67 7.67 0 0 1 .63-3.11 8.13 8.13 0 0 1 4.26-4.26 7.93 7.93 0 0 1 6.21 0 8.13 8.13 0 0 1 4.26 4.26 7.93 7.93 0 0 1 0 6.21A8.13 8.13 0 0 1 454 84a7.93 7.93 0 0 1-6.21 0 8.13 8.13 0 0 1-4.26-4.26 7.67 7.67 0 0 1-.68-3.07zm1.42 0a6.43 6.43 0 0 0 .52 2.56 6.56 6.56 0 0 0 3.5 3.5 6.61 6.61 0 0 0 5.12 0 6.55 6.55 0 0 0 3.5-3.5 6.61 6.61 0 0 0 0-5.12 6.55 6.55 0 0 0-3.5-3.5 6.6 6.6 0 0 0-5.12 0 6.56 6.56 0 0 0-3.5 3.5 6.43 6.43 0 0 0-.52 2.56zm3.5-4.62h3.53a3.55 3.55 0 0 1 2.44.71 2.61 2.61 0 0 1 .79 2 2.42 2.42 0 0 1-.62 1.81 2.58 2.58 0 0 1-1.55.71l2.37 3.87H453l-2.28-3.74h-1.23v3.74h-1.68V72zm1.68 4h2a2.32 2.32 0 0 0 .7-.16 1.19 1.19 0 0 0 .51-.39 1.4 1.4 0 0 0 0-1.42 1.18 1.18 0 0 0-.51-.39 2.13 2.13 0 0 0-.7-.15h-2V76z"/>
  </svg>
  <p>
    This site is locked.  Please contact the administrator for access.
  </p>
</body>
</html>
```

Note the comment block at the top of the file, indicating that the response being returned is NOT the 401 response but was instead the legitimate contents of that path.

## Suggested Resolution
For the actual issue, the resolution seemed to be:
1. unlock the environment
2. flush hummingbird cache

The issue resolution should be:
1. set up pristine WP environment with Hummingbird installed
2. lock environment in the dashboard
3. flush Hummingbird cache
4. inspect contents of compiled CSS
5. if the content of the file is the 401 error page, write up an official set of steps to reproduce and resolve and create a PR.

**Comment by jrastaban** [comment]
I was not able to fully replicate the issue reported here but I did confirm odd stuff happens and I suspect that those conditions could lead to the above scenario.

If I cancel when asked to supply a password I get a partial site load with all the assets loaded now throwing 404s
https://test-jrastaban.pantheonsite.io/wp-content/uploads/2020/08/Screen-Shot-2020-08-14-at-8.54.08-AM.png
https://test-jrastaban.pantheonsite.io/wp-content/uploads/2020/08/Screen-Shot-2020-08-14-at-8.54.31-AM.png

After a while I did start getting a full block screen. I wasn't ever able to load a stylesheet with the content of the 404 page but maybe a specific setting needs to be chosen. Maybe we just need a warning about using hummingbird on locked sites. 🤷‍♀️

**Comment by EdwardAngert** [comment]
@pantheon-systems/docs-admins if we want to resolve this issue, it seems the answer might be to add Hummingbird to [plugins-known-issues](https://pantheon.io/docs/plugins-known-issues) with something like
> if you're using Hummingbird on a locked site and encounter a 400-level response, flush Hummingbird cache
