### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5421]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues)

Priority: Medium

## Issue Description:
We have an open issue with WooCommerce theme templating related to multiple appservers https://github.com/woocommerce/woocommerce/pull/23971 and it seems WooCommerce team is not pushing any updates soon as this is becoming a common issue

## Suggested Resolution
As @dficker also suggested that maybe we can add/reference the workaround in the plugins with issues section while there are no long term solution for this yet for easy documentation referral. Looking for a +1 from fellow @pantheon-systems/cse or the docs team regarding this suggestion.

**Comment by sarahg** [comment]
+1 on adding this, good idea @carl-alberto!

**Comment by JulienMelissas** [comment]
Thanks for getting a plan in place for this being documented, y'all. I know us Pantheon customers would also love to see an official fix for this in WC core and would love your support to get updates from them on the ticket!
