### ISSUE TITLE
Quick Start Doc Video Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5426]
Re: [Quick Start](https://pantheon.io/docs//guides/quickstart/site-dashboard)

Priority: Medium

## Issue Description:
CSE going over docs for training noticed video is outdated. (Originated by @NeoMeteor)

## Suggested Resolution
Update tutorial video.

**Comment by alexfornuto** [comment]
Did you take note of what areas are out of date, or is the whole thing a wash?

**Comment by carolyn-shannon** [comment]
> Did you take note of what areas are out of date, or is the whole thing a wash?
Reporter did not comment on what was out of date. Assume starting fresh is a good option here.

Also: original videos do not include captions - please include captions or transcript with new video.

**Comment by alexfornuto** [comment]
Tracking internally as DOC-124
