### ISSUE TITLE
February 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5434]
For updates occurring in January, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by greg-1-anderson** [comment]
### PHP Updated
PHP 7.3.14 and PHP 7.2.27 were updated on Pantheon.

**Comment by greg-1-anderson** [comment]
### Drush Updated
Drush 8.3.2 was updated on the platform.
