### ISSUE TITLE
Pantheon Modules Doc Update 

### ISSUE THREAD

**Issue by mattshoaf** [pantheon-systems/documentation#5438]
Re: [Pantheon Modules](https://pantheon.io/docs/modules)

Priority: High

## Issue Description:

The lcache module is abandoned, it doesn't install correctly or work on your environment.

## Suggested Resolution

Remove references to the lcache module.

**Comment by alexfornuto** [comment]
Ping @davidstrauss as the plugin author.

**Comment by alexfornuto** [comment]
@mattshoaf thanks for the report!
