### ISSUE TITLE
Relaunch doc page, unclear what happens after step 3

### ISSUE THREAD

**Issue by rick02840** [pantheon-systems/documentation#5443]
Re: https://pantheon.io/docs/relaunch/   see  **Relaunch Procedure**

Priority: Low

## Issue Description

It is unclear to me what happens in  **Relaunch Procedure**  after completing Step 2 and 3.  Is the old site still live at that point?

## Suggested Resolution

Assuming the old site is still live at that point, and the new site is not live until Step 5, add this wording after Step 3:

"The old site will still be live at this point.  The new site does not become live until Step 5. "

**Comment by alexfornuto** [comment]
Hey @rick02840 thanks for reaching out. I think I've got an update that clears this up for you.

**Comment by rick02840** [comment]
Thanks!  Our situation is that we are relaunching, D7 site to a new D8 site.  We are not in direct control of DNS and the people who are wanted a day/time certain the change.  So, we could not watch and wait for step 4 (HTTPS) to be done and then do step 5 (DNS), because we have to pre-schedule DNS.  So, knowing that the old site still works after steps 2 & 3 are done, we can do those steps in advance -- say one hour -- which should be enough time for HTTPS to provision.
