### ISSUE TITLE
Add documentation on dealing with networking connectivity and DNS issues with SFTP, MySQL, rsync and Redis

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#545]
Users have connectivity issues from time to time. This should help diagnose and resolve those errors. Rough draft, could do with some sections and formatting =>

The error message indicates that there was a networking error and you can not connect to a service. For example, if there is a problem connecting via SFTP:

```
Command:	open "dev.b098f987-asf7-47af-d0a9s-po7s987f342497@appserver.dev.b098f987-asf7-47af-d0a9s-po7s987f342497.drush.in" 2222
Error:	ssh_init: Host not found
Error:	Could not connect to server''
```

## Debugging connectivity issues

The services such as MySQL and SFTP are running, however, the local client is unable to connect as you may be having DNS issues. You can diagnose in this way:

1. Check to see if you are getting an I.P. address returned when you run the following command, replacing “<xxx>” with your site’s UUID:

```
$ dig @8.8.8.8 dig codeserver.dev.<xxx>.drush.in +short
$
```

If there is no I.P. in the output then the ISP on the network you are currently on is failing to recognize the hostname.

2. The next step is to test this command with name server, in this case Google’s `8.8.8.8` I.P address:

```
$ dig @8.8.8.8 dig codeserver.dev.<xxx>.drush.in +short
192.317.200.218
$
```

## Settings local DNS

If that returns an I.P. address, this means that using Google’s DNS you were able to resolve the hostname. To resolve the issue, you can set your DNS to use Google’s service, or another provider, and you should be able to connect:

https://developers.google.com/speed/public-dns/

Also make sure that port `2222` is not being blocked by your internal firewall. Once that is configured you should be able to connect. 

## Verify connection

We recommend using the command line when possible during debugging as some GUIs and clients may hide the underlying errors:

`$ sftp -o Port=2222 dev.b098f987-asf7-47af-d0a9s-po7s987f342497@appserver.dev.b098f987-asf7-47af-d0a9s-po7s987f342497.drush.in
sftp >`

**Comment by ttrowell** [comment]
For MYSQL connections, the database server for the development environment often needs to be woken up to establish the connection.  DB servers 'sleep' after two hours of inactivity.  

Wake up the DB server by visiting the URL of the dev or test site.
