### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site Doc Update 

### ISSUE THREAD

**Issue by marfillaster** [pantheon-systems/documentation#5455]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs//guides/composer-convert)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

The example commands assume site is already in nested docroot but made no mention of it.

## Suggested Resolution

Require or reference nested docroot setup https://pantheon.io/docs/nested-docroot#convert-an-existing-site

**Comment by carolyn-shannon** [comment]
The **Before You Begin** section includes a specific note to "Review Serving Sites from the Web Subdirectory" (ie a nested docroot). The [Configuration](https://pantheon.io/docs/guides/composer-convert#custom-code) section of "Add in the Custom and Contrib Code" also discusses nested docroot configuration. Closing this out, as the topic appears sufficiently introduced.
