### ISSUE TITLE
Choosing Your Start State Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#5459]
Re: [Choosing Your Start State](https://pantheon.io/docs/start-state)

Priority: Low

## Issue Description:
Some of the upstreams listed here are outdated or no longer maintained. We should probably review this list.

These look like repos we should remove from the list, or find newer versions for:
- Atrium (linked repo is for Drupal 6)
- OpenAid (no commits since 2015)
- OpenIdeal (no commits since 2014)
- OpenOutreach (2015)
- Plato Típico (2015)
- Push Tape (2016)
- RedHen Raiser (2015)

## Suggested Resolution
Remove upstreams that spin up outdated versions of core. Add newer ones if they exist. Document the recommended method to create your own upstream and keep it up-to-date.

**Comment by alexfornuto** [comment]
Blocked pending internal discussion on product ownership of upstreams. Converted to DOC-112 for further tracking.
