### ISSUE TITLE
Unmet dependencies error when installing Drupal 8 on Pantheon

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#5461]
Re: See [UnmetDependenciesException when installing Drupal 8](https://www.drupal.org/project/drupal/issues/2594351) on drupal.org

Priority: Low

## Issue Description

Sometimes, users get errors when installing Drupal:

<img width="1258" alt="Screen Shot 2020-01-16 at 10 32 05 AM" src="https://user-images.githubusercontent.com/612191/72557943-97012900-3856-11ea-9c5a-b90d02e66c76.png">

(Also see screenshots in message linked above)

## Suggested Resolution

It appears that this can be caused by a dirty cookie cache in the web browser. The easiest workaround is to re-install in incognito mode. It might be helpful to document this somewhere on a troubleshooting page.

**Comment by alexfornuto** [comment]
This content will go into the WIP Troubleshooting guide, possible as a partial to be used elsewhere as needed.

**Comment by alexfornuto** [comment]
Marking as blocked until work continues on #4865

**Comment by alexfornuto** [comment]
Consolidated
