### ISSUE TITLE
March 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5477]
For updates occurring in February, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.2 
Update to Drupal 8.8.2. For more information, see https://www.drupal.org/project/drupal/releases/8.8.2

**Comment by ari-gold** [comment]
### Global CDN Network Expansion
New Points of Presence: Ashburn, VA (WDC), Chicago (PWK)
Expanded Capacity: Vancouver (YVR), Sydney, Australia (SYD), NY (LGA), Los Angeles (BUR), Dallas (DFW), Atlanta (FTY), Boston (BOS)
