### ISSUE TITLE
Pantheon YAML Configuration Files Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#5479]
Re: [Pantheon YAML Configuration Files](https://pantheon.io/docs/pantheon-yml)

Priority: Low

## Issue Description:
**enforce_https: full** not sending the "preload" header

<img width="874" alt="a" src="https://user-images.githubusercontent.com/14119666/73230729-34dee700-41b9-11ea-8135-d8954220e9cd.png">

I'm only getting the following:

`strict-transport-security: max-age=31622400`

This works for **enforce_https: full+subdomains:**

`strict-transport-security: max-age=31622400; includeSubDomains; preload`

## Suggested Resolution
Confirm if this the expected behavior and update doc to reflect this.

**Comment by alexfornuto** [comment]
@ari-gold should `full` include the `preload` header, or only `full+subdomains`?

**Comment by ari-gold** [comment]
@alexfornuto  Yes, preload is only sent for full+subdomains, as it's a requirement to cover subdomains in order to preload. Thanks for updating!

**Comment by rubelyn** [comment]
thanks @ari-gold for clarifying this..
