### ISSUE TITLE
Automating and Integrating your Pantheon WebOps Workflow with Quicksilver Platform Hooks Doc Update 

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#5483]
Re: [Automating and Integrating your Pantheon WebOps Workflow with Quicksilver Platform Hooks](https://pantheon.io/docs/quicksilver)

Priority: Low

## Issue Description:
This page about Quicksilver doesn't even have `secrets.json` on the page, even though it's an essential part of using Quicksilver to integrate with third-party APIs. We frequently refer to it in training and give specific examples in the [Quicksilver Examples Repo](https://github.com/pantheon-systems/quicksilver-examples). We also refer to it within integration guides on Docs (like [Integrate Jira](https://pantheon.io/docs/guides/jira) and [Integrate Trello](https://pantheon.io/docs/guides/trello)). This feels important enough to provide some documentation around.

## Suggested Resolution
At a minimum, we should add a section to the Quicksilver doc to define secrets.json and how it is used. I could see this having enough meat to get its own page, but I'll leave that to your expertise to decide.

**Comment by alexfornuto** [comment]
@davidneedham agreed all around, we'll stage a new section for this doc on secrets.json and hit you up for verification,
