### ISSUE TITLE
Add warning for redirect conflict scenario

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#5493]
Re: [Configure Redirects](https://pantheon.io/docs/redirects)

Priority: Med or High

## Issue Description:
Sanitized feedback from @tmountjr : 
> Suppose a site has a bunch of domains that are being redirected from wp-config.php (eg. example-site has example.io which WP is redirecting somewhere deep inside example.com/specific-path). if they set a default domain on their dashboard, example.io will instead redirect straight to example.com from nginx and the deep link [example.com/specific-path] set up in wp-config.php will break. 

## Suggested Resolution
Add warning to redirect doc, and to domains partial 

>  recommend adding a disclaimer on the "default domain" page that if you are manually redirecting domains from your dashboard to somewhere else on your main site, you do NOT use the default domain feature.

**Comment by tmountjr** [comment]
that captures the essence of my specific qualm from the other day. :)

**Comment by alexfornuto** [comment]
Resolving this will also resolve #5508

**Comment by alexfornuto** [comment]
Working on adding this to the primary domain partial file, early feedback requested/appreciated.
![image](https://user-images.githubusercontent.com/2349184/74351123-4eb52800-4d7c-11ea-8135-c992c58ae1b4.png)
