### ISSUE TITLE
Non-Standard Files Locations Doc Update 

### ISSUE THREAD

**Issue by xq42** [pantheon-systems/documentation#5499]
Re: [Non-Standard Files Locations](https://pantheon.io/docs/non-standard-file-paths)

Priority: Low

## Issue Description:

Missing instructions for how to create a symlink on a Windows system.

## Suggested Resolution:

This is one of two docs that shows how to create symlinks as a workaround for a need to write to a location outside of sites/default/files/ or wp-content/uploads/. The other doc:

https://pantheon.io/docs/assuming-write-access#create-a-symbolic-link

includes a Note near the top of the page with llnks to external sources on how to create symlinks on a Windows system. Could we please get that same note added to this doc?

**Comment by alexfornuto** [comment]
I think that we should remove this page and redirect it to /assuming-write-access.

**Comment by xq42** [comment]
That works for me!
