### ISSUE TITLE
Professional Services Doc Update - Onboarding

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#5503]
Re: [Professional Services](https://pantheon.io/docs/professional-services)

Priority: Medium (choose one, remove the other options)

## Issue Description:
Updates related to Onboarding related activities

## Suggested Resolution
- New Page for Onboarding
- Specific topics to move to the new page

**Comment by alexfornuto** [comment]
@carolyn-shannon will follow up with @eabquina and @ttrowell for next steps.
