### ISSUE TITLE
Configure Additional Redirects - Clarification

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5508]
Re: [Configure Redirects](https://pantheon.io/docs/redirects)

Priority: Low

## Issue Description:
When configuring additional redirects (optional section), make more prominent that the primary domain should be set to 'None'.

**Comment by carolyn-shannon** [comment]
h/t: https://twitter.com/Fre_Mun/status/1225690684071370753

**Comment by alexfornuto** [comment]
Resolved by #5493
