### ISSUE TITLE
Switching Sites from HTTP to HTTPS Doc Update 

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#5511]
Re: [Switching Sites from HTTP to HTTPS](https://pantheon.io/docs/http-to-https)

Priority: Low

## Issue Description:
The point of this doc is to explain how to switch sites from HTTP to HTTPS. It was updated somewhat recently when the "primary domain" option was added to the UI of the dashboard. Setting a primary domain works, but doesn't seem to be relevant to redirecting to HTTPS.

I originally discovered this doc when trying to make my site redirect to HTTPS. I had just set a primary domain. That worked, but it was not going to HTTPS. I read everything in the doc, but totally overlooked the part where it says:

> It's a best practice for SEO and security to standardize all traffic on HTTPS and choose a primary domain. Configure redirects to the primary domain with HTTPS in [pantheon.yml](https://pantheon.io/docs/pantheon-yml#enforce-https--hsts).

This point should probably be emphasized, particularly for folks who are troubleshooting.

## Suggested Resolution
Add a section or step after tweaking the setting in the dashboard that mentions`enforce_https:transitional` being the default and that they can check out the doc for more info: https://pantheon.io/docs/pantheon-yml#enforce-https--hsts. Actually, now that I'm writing this, it's possible that the primary domain section is irrelevant and should just be replaced by talking about editing the pantheon.yml file if there are specific needs beyond the default. I'll leave that to you wonderful people to decide. 🙇

**Comment by davidneedham** [comment]
I discovered the reason why my site was not redirecting after reading https://pantheon.io/docs/pantheon-yml#enforce-https--hsts. I had explicitly set `enforce_https:off` way back when this feature was first added by Pantheon because it suddenly broke the site. I forgot about that, but there was no easy way for me to discover that from this docs page.

**Comment by carl-alberto** [comment]
Maybe a troubleshooting section in here https://pantheon.io/docs/http-to-https to suggest what to do if https redirect is not kicking in or adding your resolution here in the troubleshooting section https://pantheon.io/docs/pantheon-yml#troubleshooting here can also help out people that will encounter same issues

**Comment by alexfornuto** [comment]
Closed by #5518 - Thanks for the input @davidneedham and @carl-alberto!
