### ISSUE TITLE
Git FAQs Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#5519]
Re: [Git FAQs](https://pantheon.io/docs/git-faq)

Priority: Low

## Issue Description:
We note that we don't support Git submodules. This is true, but sometimes people migrate sites here that already have these (or add them by mistake). These will cause weird deployment issues and make you sad.

## Suggested Resolution
Let's provide directions about how to properly remove Git submodules, something like this: https://davidwalsh.name/git-remove-submodule

Could be good to also note some symptoms of having submodules:
- module is missing from Test but present on Dev
- module is on your local but not deploying to Dev when you "git push"
- fatal errors about missing files that you think should be there

**Comment by alexfornuto** [comment]
Good idea @sarah! @darkwing's instructions look good, but that post is a bit old and some of the comments suggest things have changed. 

David, would you care to weigh in on the current best practice to remove a git  submodule? We'd be happy to credit you in the proposed addition to our docs.

**Comment by carolyn-shannon** [comment]
More research needed here to:

1. Determine correct method to do this
1. Determine whether the proper method is canonically documented in GitHub, GitLab or other documentation.

**Comment by alexfornuto** [comment]
My research and testing says that modern git handles submodule removal with a simple `git rm submodule-dir/`, so I'm gonna go with that.
