### ISSUE TITLE
Review SendGrid Guide

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#5521]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs//guides/sendgrid)

Priority: Low

## Issue Description:
Review and update SendGrid Guide

(Expanding this issue, orig submitted as specific to SendGrid for WordPress)
Customer noted that this Docs file recommends the SendGrid WordPress plugin for WordPress, but that hasn't been updated in 2 years.

## Suggested Resolution
Review and update SendGrid Guide

SengGrid for WordPress-specific:
Maybe verify this still works? Or other e-mail documentation recommends using SMTP plugin and then authenticating via SMTP to SendGrid: https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/#integrating-with-sendgrid

**Comment by alexfornuto** [comment]
@dficker thanks for the issue! We can certainly look into this, but first I'd like to know where you see us recommending SMTP? From `/docs/email`:

> You can use an SMTP configuration, but because SMTP requests are associated with dynamic outgoing IPs there can be negative impacts to deliverability.

We go on to show some SMTP options, but I wouldn't say we recommend it

**Comment by dficker** [comment]
@alexfornuto Ahh yes, you're right. I was looking in the section that describes how to set up using SMTP. In the tabs under Drupal and WordPress.

On most sites I've worked on, SMTP has worked fine. But recommending the native API is probably a good idea.

In that case, the WordPress plugin directory just has that warning note on the SendGrid plugin that it hasn't been updated in a while or tested with recent major versions, which seems to indicate that the SendGrid team may have abandoned it. Customers were coming to support asking if that plugin still works, and I wasn't sure.

**Comment by alexfornuto** [comment]
As discussed in #5679 there _is_ some outdated information in this page, which is better-detailed there. Closing to consolidate.
