### ISSUE TITLE
Configuration Workflow for Drupal 8 Sites Doc Update 

### ISSUE THREAD

**Issue by rickward** [pantheon-systems/documentation#5523]
Re: [Configuration Workflow for Drupal 8 Sites](https://pantheon.io/docs/drupal-8-configuration-management)

Priority: Medium

## Issue Description:
The recommended value for the config_sync_directory is incorrect. I think this value is correct elsewhere in the Pantheon docs, but I didn't find it on this google-around.

## Suggested Resolution
Correct value should be:
$settings['config_sync_directory'] = dirname(DRUPAL_ROOT) . '/config';

**Comment by alexfornuto** [comment]
Thanks @rickward! We're reviewing this change currently in #5510
