### ISSUE TITLE
Configure Redirects Doc Update platform domain should be stated in the doc that is not included with the redirect when the primary domain is set

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5524]
Re: [Configure Redirects](https://pantheon.io/docs/redirects)

Priority: Low

## Issue Description:
Many users are confused that setting the primary domain will always do the redirect including platform domain to the primary domain that they have set

## Suggested Resolution
It might be better to be indicated in the doc that it doesn't work and they will need to do a php redirect if they want a platform domain redirect to the primary domain

**Comment by alexfornuto** [comment]
@ari-gold can you confirm that the platform domain should be (and is) redirected when the Primary Domain is set?

**Comment by carl-alberto** [comment]
This was raised in the internal ticket 449574 and BUGS-3005 for more back tracking
