### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by jasonawant** [pantheon-systems/documentation#5531]
Re: [Build Tools](https://pantheon.io/docs//guides/build-tools)

Priority: Low

## Issue Description:
The Warning message at top of page suggests
> The current version of the Build Tools plugin is designed for Terminus 1.x, and is not yet compatible with current versions of Terminus. We are working on a new version of the Terminus Build Tools plugin with Terminus 2 support and will update this guide

However, the doc step 2 installs Terminus version 2.3
> curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install

However, the doc then states in step 8
> Install the Terminus Build Tools Plugin. Update the version number in this example from 2.0.0-beta12 to the current version:

## Suggested Resolution
Update doc; remove warning?

**Comment by alexfornuto** [comment]
CC @sugaroverflow

**Comment by sugaroverflow** [comment]
Hi @jasonawant 👋 

I'm the new maintainer for the build tools plugin and still getting up to speed. I'm going to working on  updating the docs for version 2.0 in #5444. Build Tools 2.0 requires a lot more documentation with some of the new features so that might take me some time. 

In the meantime, I believe the warning was meant to indicate that this doc isn't up to date / the installation specified isn't stable. Maybe we can rework the language to reflect that?

**Comment by jasonawant** [comment]
Sure, sounds good. Here's the current warning message copy.

> The current version of the Build Tools plugin is designed for Terminus 1.x, and is not yet compatible with current versions of Terminus. We are working on a new version of the Terminus Build Tools plugin with Terminus 2 support and will update this guide once it is released. In the meantime, you can test the beta release.

Is the first statement true?

> The current version of the Build Tools plugin is designed for Terminus 1.x, and is not yet compatible with current versions of Terminus.

Maybe eliminate it all together. I say eliminate b/c step 2 installs Terminus 2.x and step 8 installs 2.0.0-beta12 build tools.

Then, we're left with 
> We are working on a new version of the Terminus Build Tools plugin with Terminus 2 support and will update this guide once it is released. In the meantime, you can test the beta release.

Consider this change,
> We are working on a new 2.x version of the Terminus Build Tools plugin with Terminus 2 support. In the meantime, you can test the beta release following the instructions below.

And, update step 8 as follows,
> Install the Terminus Build Tools Plugin. Update the version number in this example from 2.0.0-beta18 to the current version:

`composer create-project --no-dev -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^2.0.0-beta18`

Also, b/c step 8 includes a specific beta version (18), you can include a reference to reporting any issues and updating plugins documentation in the warning message at top of page. If we add that, then it would be something like

> We are working on a new 2.x version of the Terminus Build Tools plugin with Terminus 2 support. In the meantime, you can test the beta release following the instructions below. If you have an issue with the build tools, review the [issue queue](https://github.com/pantheon-systems/terminus-build-tools-plugin/issues). If you need to update to the latest version of Terminus Build Tools plugin, see [updating plugin docs](https://pantheon.io/docs/terminus/plugins#update-plugins).

**Comment by populist** [comment]
+1 for removing the warning on the page + updating the information for 2.x. Terminus Build Tools 2.x is pretty far along and I would def recommend people building integrations today start with 2.x. The warning undersells the power of 2.x!

**Comment by sugaroverflow** [comment]
Thank you for your work on this @jasonawant 🎉 And yay, thanks for the +1 @populist! 

I also think this is a great idea and love your suggestions for reworking the warning. I think the last update to the warning message - including the links and the update to step 8 are both great.  Would you like to go ahead and create a PR for this?

In the next few weeks, I'm hoping to have a more public roadmap and once 2.0 releases, we could also link to a list of known issues.
