### ISSUE TITLE
Enabling Solr on Drupal 8 Doc Update search_api_solr 8.x-1.x (reaches EOL December 2020)

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5536]
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8)

Priority: Low

## Issue Description:
The module search_api_solr 8.x-1.x is reaching EOL December 2020 as indicated https://www.drupal.org/project/search_api_solr. 

## Suggested Resolution
It might be a good idea to update the content to reflect the direction of its usage before it goes EOL

**Comment by alexfornuto** [comment]
Will add to the note at the top of the doc.
