### ISSUE TITLE
Drupal 7: URL with ampersand returns HTTP 404 (while percent encoded url works ok)

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#5543]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: not sure where this would go

Priority: Low

## Issue Description

Drupal 7 on Pantheon with an ampersand in the URL returns 404.

## Suggested Resolution

Workarounds:
- encode the URL with %26

ref. BUGS-3011

**Comment by alexfornuto** [comment]
If this is something that happens on Pantheon but not vanilla D7, I'd suggest that it goes in [Platform Considerations](https://pantheon.io/docs/platform-considerations). @ari-gold how's that grab ya?

**Comment by arcataroger** [comment]
This is still an issue a year later... any chance we could see a fix for the underlying issue, not just a documentation update?

URLs with ampersands work fine in Drupal 7 on my local stack. Is this a Pantheon-specific issue, possibly to do with URL rewrites/CDN rules, etc.?
