### ISSUE TITLE
Advanced Redirects and Restrictions Doc Update 

### ISSUE THREAD

**Issue by musicaljoeker** [pantheon-systems/documentation#5553]
Re: [Advanced Redirects and Restrictions](https://pantheon.io/docs/advanced-redirects)

Priority: High

## Issue Description:
The code given to [restrict paths based on IP addresses](https://pantheon.io/docs/advanced-redirects#restrict-wp) has a vulnerability. Specifically, the code in the WordPress block:
```
if (isset($_SERVER['PANTHEON_ENVIRONMENT']) && !is_from_trusted_ip() ) {
   // Check if the path should be locked down
   $to_lockdown = false;
   $clean_request_uri = rtrim(mb_strtolower(strtok($_SERVER["REQUEST_URI"],'?')), '/');
 if ( substr($clean_request_uri, 0, 13) == '/wp-login.php' ) {
     // user login page
     $to_lockdown = true;
   } elseif ( substr($clean_request_uri, 0, 9) == '/wp-admin' ) {
     // admin pages
     $to_lockdown = true;
   }
   if($to_lockdown && (php_sapi_name() != "cli")){
     header('HTTP/1.0 403 Forbidden');
     echo 'Access denied.';
   exit();
   }
 }
```
allows for access on the restricted pages if a user requests the page with a double slash.

For example, https://mycoolsite.com/wp-login.php would return a 403 error, but https://mycoolsite.com//wp-login.php would return a status 200 and show the login screen. Also, it's possible to skirt by the logic by requesting a URL encoded slash (https://mycoolsite.com/%2Fwp-login.php).

## Suggested Resolution
Add one more line of code below the `$clean_request_uri`:
```
$slashes_removed_uri = str_replace( array('/', '%2f'), '', $clean_request_uri );
```
Altogether, the update should look like this:
```
if (isset($_SERVER['PANTHEON_ENVIRONMENT']) && !is_from_trusted_ip() ) {
   // Check if the path should be locked down
   $to_lockdown = false;
   $clean_request_uri = rtrim(mb_strtolower(strtok($_SERVER["REQUEST_URI"],'?')), '/');
   $slashes_removed_uri = str_replace( array('/', '%2f'), '', $clean_request_uri );
 if ( substr($slashes_removed_uri , 0, 12) == 'wp-login.php' ) {
     // user login page
     $to_lockdown = true;
   } elseif ( substr($slashes_removed_uri , 0, 8) == 'wp-admin' ) {
     // admin pages
     $to_lockdown = true;
   }
   if($to_lockdown && (php_sapi_name() != "cli")){
     header('HTTP/1.0 403 Forbidden');
     echo 'Access denied.';
   exit();
   }
 }
```

**Comment by alexfornuto** [comment]
Thanks so much for the issue and PR @musicaljoeker!
