### ISSUE TITLE
April 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5555]
For updates occurring in March, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.3 
Update to Drupal 8.8.3. For more information, see https://www.drupal.org/project/drupal/releases/8.8.3

**Comment by greg-1-anderson** [comment]
### New Relic Agent 9.7.0.258

**Comment by greg-1-anderson** [comment]
### WP-CLI
WP-CLI has been upgraded to [version 2.4.0](https://github.com/wp-cli/wp-cli/releases/tag/v2.4.0).

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.4 
Update to Drupal 8.8.4. For more information, see https://www.drupal.org/project/drupal/releases/8.8.4
