### ISSUE TITLE
Remove content recommendations for STYXKEY for HTML5 & CSS3

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#556]
https://pantheon.io/docs/articles/sites/varnish/caching-advancedtopics/

After seeing STYXKEY I can say it is hard for users to digest. Doing things like mobile detection using modules like https://www.drupal.org/project/mobile_switch_varnish are not supported on the plaftform as the VCL can not be edited. It is also no longer the best or easiest way to do this.

### Summary
I vote that we remove the "Content Customization" section for STYXKEY and recommend this be done on the client side using browser detection, orientation or features like aspect ratio using HTML5, CSS3 and JS.

## Modernizr
Users can allow for a wider selection of browser properties in order to make their themes more responsive. This will also allow requests to have the benefit of being saved in Varnish and rendering correctly depending on the requirements.

## Device detection

A full list of the devices and their support for HTML5 is available on https://html5test.com where a comparison can be done for a variety of clients:

Desktop browsers: https://html5test.com/results/desktop.html 
Tablet browser: https://html5test.com/results/desktop.html 
Mobile browsers: https://html5test.com/results/desktop.html 
Other browsers: https://html5test.com/results/other.html 

## Resources

**Modernizr**
Main site: http://modernizr.com
Official documentation: http://modernizr.com/docs
Modernizr browser feature support matrix: http://www.browserscope.org/user/tests/table/agt1YS1wcm9maWxlcnINCxIEVGVzdBib2KQGDA
Detectizr an extension to detect device features: https://github.com/barisaydinoglu/Detectizr

**Drupal**
Modernizr Module - https://www.drupal.org/project/modernizr
Browser feature detection: https://www.drupal.org/node/1913726
Modernizr.load() and Drupal: Basics - https://www.drupal.org/node/1913830
Implementing the Modernizr Test API within a module or theme - https://www.drupal.org/node/2332277

**Wordpress**
Loading Modernizr for use in a plugin: http://wordpress.stackexchange.com/a/62362

**Comment by nataliejeremy** [comment]
See details on PR #671
