### ISSUE TITLE
WordPress Plugins and Themes with Known Issues Doc Update by Andreas Lopez

### ISSUE THREAD

**Issue by Uriel1339** [pantheon-systems/documentation#5562]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues)

Priority: Medium

## Issue Description:
Missing Points / Discovered Detailed Pain Points

## Suggested Resolution
As Per Ticket History Nr. 451591

Here are my main findings that you might want to add in the future to your speed optimization documentation. I also wouldn’t mind speaking about it at a WordCamp or such being Pantheon sponsored or writing even a guest article.

Either way, here are the main problems and how I solved them over the last few weeks trying a whole lot out:
#1 – YITH themes are not speed optimized whatsoever. We used to have the ‘YITH WooCommerce AJAX Search Premium’ Plugin and their ‘YITH WooCommerce Dynamic Pricing and Discounts Premium’
The former has been replaced with ‘Advanced Woo Search’ which has its own index and works rather fast. I know it’s not as optimal as Solr but it works more reliable due to no need of re-indexing all the time and it had huge performance gains compared to the previous search plugin (customers & customer service dept. stopped complaining).
The Dynamic Pricing we made a workaround with automated coupons which still has the same benefit except for the nice pricing table.

#2 – Immense amount of calls of Admin AJAX calls that slowed down the server at large. We fixed that by using (as per WordPress community recommendations) Heartbeat Control and increasing dashboard calls from 15 to 300 seconds and the Editor calls from 15 to 120 seconds.

#3 – Double-Checked and found obsolete code, we had hardcoded to change the e-mail subject line via a functions.php hook which was doing it in an old way creating PHP Warnings in the PHP Error log. This code was originally written by from Skyverge and has been fixed in the meanwhile.

#4 – We killed Checkout Add-Ons altogether which was made by Skyverge. It made too many calls for no good reason. We replaced it with some custom code to achieve the same functionality of offering customers an upgrade on the whole checkout experience.

#5 – We unhooked WooCommerce Templates with ‘return’ in the .php functions inside the themes template folder which we are not using altogether, i.e. the Sale Badge, Related Items, etc.

#6 – We replaced all Upsell.php generated items with static product listings which makes editing and maintenance a little bit less intuitive, but thanks to an Excel template no problem for us. This is not recommended in general, but it makes sense for our sophisticated team and the fact we like to list 9+ upsell items. The PHP call-outs were immense in loading time which is why we did this as the most elegant solution.

#7 – Limit Products per page to 24-36 down from our original 48 and giving customers even options for 96 at a time. The PHP call outs for each individual product slow each page down dramatically.

#8 – We had to remove the Native PHP Sessions plugin from Pantheon because it was interfering with another plugin or maybe our theme (we still couldn’t nail it down) but our website operates as intended. So there was no real need to have errors being generated every 1-3 minutes for this in our instance.

**Comment by alexfornuto** [comment]
Hi @Uriel1339, thanks for the detailed issue! The point of that doc is to highlight plugins and themes that specifically conflict with our Platform, or are otherwise not built in a way that meshes with a WebOps workflow.

It seems like, with the exception of no.8, these are opinions on plugins based on their general performance. I don't think that the docs is the right place for this information, but I _do_ think that the [community forum](https://discuss.pantheon.io/c/drupal/wordpress) would benefit from these insights.

WRT The Native PHP Session Plugin, it sounds like we could do a better job documenting the benefits of making it a Must Use plugin to avoid conflicts (as discussed on the [plugin page](https://wordpress.org/plugins/wp-native-php-sessions/). I'll make a new issue to capture this work.
