### ISSUE TITLE
Getting the Client IP Address Doc Update 

### ISSUE THREAD

**Issue by davidstrauss** [pantheon-systems/documentation#5566]
Re: [Getting the Client IP Address](https://pantheon.io/docs/client-ip)

Priority: Medium

## Issue Description:

This document explains how to use a client IP address to perform operations like geolocation. Unfortunately, this doesn't play well with caching on the platform. Namely, if you use geolocation in PHP to customize a response for a request on Pantheon, you have two not-so-great options:

- Don't cache the response at all
- Cache the response but set `Vary` for the corresponding header that Global CDN uses for forwarding the client's IP address. This approach isn't very good, though. Global CDN can store about 200 variants of any given page (and there would be one per client IP), but the main issue is that the cache won't hit unless traffic comes from the same IP.

Otherwise, you'll get cache hits that have the wrong personalization for the requesting user, as client IP isn't normally part of the cache key or variant behavior.

Part of why these options aren't great is because requiring a trip through PHP to identify a user's country for personalization purposes is generally slow and bad for caching.

## Suggested Resolution

Users that need geolocation *with caching* should either use Advanced Global CDN or an alternative geo-aware edge.

If a user prefers Cloudflare in general (or prefers it for cost reasons), then Cloudflare should perform the lookup and set its `CF-IPCountry` header. On the Pantheon side, any PHP reading `CF-IPCountry` should also add `Vary: CF-IPCountry` to responses to ensure that Global CDN properly personalizes cache hits. This will ensure cache behavior is both correct (content returned for the user agent's actual location) and efficient (cache can hit for other requests coming from the same country).

**Comment by alexfornuto** [comment]
Thanks @davidstrauss! It seems like most of this content is no longer relevant, and I'm hesitant to document a third party offering like cloudflare in competition to a service provided by Advanced CDN. I'm gonna stage a PR to warn users about the dated nature of this content, and bring it to the team to discuss possible removal of the page.

**Comment by alexfornuto** [comment]
@davidstrauss I'll be reaching out to discuss best options for resolution.
