### ISSUE TITLE
Restricting Access based on IP address is too greedy with /wp-admin

### ISSUE THREAD

**Issue by musicaljoeker** [pantheon-systems/documentation#5568]
Re: https://pantheon.io/docs/advanced-redirects#restrict-wp

Priority: Medium

## Issue Description
Restricting access to the `/wp-admin` pages based on IP addresses is probably not necessary for the use case described in the document. In fact, restricting access via IP address to all `/wp-admin` pages can have unintended consequences.

There are two cases where the current configuration will cause unintended 403 errors (for both authenticated and unauthenticated users) unless you are in the allowlist (whitelist):
 - Ajax calls (site.com/wp-admin/admin-ajax.php)
 - POST data (site.com/wp-admin/admin-post.php)

[Relevant StackExchange post](https://wordpress.stackexchange.com/a/270188)
This discussion is 7 years old, so it might be worthwhile to try and find a more recent discussion.

## Suggested Resolution
I see two paths forward on this issue:

1. Remove the `/wp-admin` check for restricting IP addresses
2. Keep the `/wp-admin` check and make an exception for the two endpoints listed above

I'm happy to make a pull request with either solution.

**Comment by carolyn-shannon** [comment]
PhP help wanted to implement suggested resolution #2, adding exceptions for the two endpoints.

**Comment by alexfornuto** [comment]
Thanks for the issue @musicaljoeker!
