### ISSUE TITLE
yaml: filemount path can be symlinked to both files and cms-specific path

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#5578]
Re: [YAML config file, filemount path](https://pantheon.io/docs/pantheon-yml#filemount-path)

Priority: Medium

## Issue Description

```
Pantheon provides a cloud-based filesystem to store user-generated content and other website files. By default, we create a symlink to this filesystem at /sites/default/files (Drupal) or /wp-content/uploads (WordPress), but you can change the location with the filemount variable:
filemount: /files
This creates a new symlink to the filesystem at the specified location. Note that this setting is only recommended when creating a custom upstream. Instead, consider using a symlink as described in Non-Standard Files Locations.
```

The copy makes it sound like we're changing the place where the symlink lives (/sites/default/files  or /wp-content/uploads), but the example code shows the target of the symlink, which I believe should be immutable.

Even more curious is the section below that:

```
Specify the exact path; limited selection of valid paths:
 - /files
 - /sites/default/files  
 -/wp-content/uploads
```

This seems to indicate that the only paths you can set it to are the ones that are already in place. Testing confirms that they are indeed both (meaning /files and the CMS specific path) present at the same time.

Is the [answer in 3771](https://github.com/pantheon-systems/documentation/issues/3771#issuecomment-396324724) related to this?

**Comment by alexfornuto** [comment]
Merged into #5575
