### ISSUE TITLE
Reading Pantheon Environment Configuration Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5580]
Re: [Reading Pantheon Environment Configuration](https://pantheon.io/docs/read-environment-config)

Priority: Low

## Issue Description:
- It seems it is a little bit outdated as there are new variables like
   - enforce_https
   - php_version
   - PANTHEON_INFRASTRUCTURE_ENVIRONMENT
   - PATH
   - HOME
   - PHPRC
   - PANTHEON_DEPLOYMENT_IDENTIFIER
   - PANTHEON_ROLLING_TMP
   - DRUSH_OPTIONS_URI

- Note that environment variables vary based from CMS and when Redis and Solr is enabled
- For WP sites, these seems to be appearing:
   - AUTH_KEY
   - SECURE_AUTH_KEY
   - LOGGED_IN_KEY
   - NONCE_KEY
   - AUTH_SALT
   - SECURE_AUTH_SALT
   - LOGGED_IN_SALT
   - NONCE_SALT
   - PANTHEON_WPVULNDB_API_TOKEN
   
- When Redis is enabled, these are present
   - CACHE_HOST
   - CACHE_PORT
   - CACHE_PASSWORD

- When Redis is enabled, these are present
   - PANTHEON_INDEX_HOST
   - PANTHEON_INDEX_PORT

## Suggested Resolution
- Might be good to document it and what are those other variables used for easy referral for the correct variables that developers need

---
_Related to internal ticket 455256 as they were used to other hosts that configs are hardcoded, their site was down when the appservers cred is changed due to maintenance_

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! I suggest @EdwardAngert find out from the powers that be is this is indeed all the environment variables we should be documenting.

**Comment by carl-alberto** [comment]
Awesome!
