### ISSUE TITLE
Generate and Add SSH Keys Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5586]
Re: [Generate and Add SSH Keys](https://pantheon.io/docs/ssh-keys)

Priority: Low

## Issue Description: 
https://pantheon.io/docs/ssh-keys#generate-ssh-key
 Under step 4, the file path for the Windows instruction is jumbled.

## Suggested Resolution
Un-jumble the file path.

**Comment by CFin86** [comment]
Should be: `PC C:\Users\usertype .ssh\id_rsa.pub`

![image](https://user-images.githubusercontent.com/22105265/76976676-4bc0d080-6902-11ea-80d7-fe6c098e87ca.png)

**Comment by alexfornuto** [comment]
Thanks @CFin86!
