### ISSUE TITLE
Filter Localdev Changelog for Stable Releases

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5589]
Re: [Use Pantheon Localdev to Develop Sites Locally](https://pantheon.io/docs/localdev)

Priority: Low

## Issue Description:
In the section [Changelog](https://pantheon.io/docs/localdev#changelog) Localdev 0.8.0 is the edge channel release and not the stable channel release. When downloading Localdev, it is default set to the stable channel release, 0.7.0. This leads to confusion about which version of Docker to use. The stable release of Localdev 0.7.0 will not work Docker 2.2.0.4.
 
## Suggested Resolution
A notation that 0.8.0 is the edge channel release and 0.7.0 is the stable channel release.
<img width="1418" alt="Screen Shot 2020-03-18 at 4 27 36 PM" src="https://user-images.githubusercontent.com/22105265/77009704-5c8b3980-6936-11ea-823f-791a4cf34157.png">
<img width="1418" alt="Screen Shot 2020-03-18 at 4 22 10 PM" src="https://user-images.githubusercontent.com/22105265/77009720-67de6500-6936-11ea-8352-79a149ad72f4.png">

**Comment by alexfornuto** [comment]
Hrmmm.... Not a lot I can do about this, unless @pantheon-systems/tandem-developers  starts indicating in the changelog which versions are stable and/or !stable.

**Comment by dustinleblanc** [comment]
@alexfornuto I'll add a card to Localdev's queue for this

**Comment by alexfornuto** [comment]
Attempting a workaround by filtering on `beta` in the version name. Moving forward, we'll track progress in #6233.
