### ISSUE TITLE
Add Localdev note to Lando Doc

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5590]
Re: [Install and Configure Lando](https://pantheon.io/docs//guides/lando)

Priority: Low

## Issue Description:
![Uploading Screen Shot 2020-03-18 at 4.36.28 PM.png…](This guide is found through our guides page) here: https://pantheon.io/docs/guides
We no longer provide support for Lando, in lieu of our own product, Localdev
  
## Suggested Resolution
Change the link to point towards our Localdev doc: https://pantheon.io/docs/localdev

**Comment by alexfornuto** [comment]
Gonna make a note on the lando page to point to Localdev
