### ISSUE TITLE
Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by julian-sloman-ffatg** [pantheon-systems/documentation#5591]
Re: [Plugins with Known Issues with WordFence](https://pantheon.io/docs/plugins-known-issues#wordfence)

Priority: Medium

## Issue Description:

1. cookies are no longer used, that issue can be taken out.

2. there are constants that can help.
a. ) change the path to something writable (like uploads directory, though semantically incorrect and less safe) https://www.wordfence.com/help/advanced/constants/#web-application-firewall-waf
b. ) use database instead of file for logs https://www.wordfence.com/help/firewall/mysqli-storage-engine/

## Suggested Resolution

Mention that in the known issues document: `define('WFWAF_STORAGE_ENGINE', 'mysqli');`

**Comment by alexfornuto** [comment]
For 2a, maybe a protected path could allow for writing to the uploads directory safely: https://pantheon.io/docs/pantheon-yml#protected-web-paths

Seeking SME input.

**Comment by carolyn-shannon** [comment]
Help wanted: WordFence expertise

**Comment by alexfornuto** [comment]
I've been unable to get Wordfence's WAF to work with the mysql storage engine in git mode, but @CFin86 and @jahzlariosa have told of certain levels of success. I'm hoping they'll update this issue with their findings, and/or submit a PR with the steps needed.
