### ISSUE TITLE
GCDN - add 'best practices for caching in stacked CDNs' 

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#5603]
Re: [Pantheon Global CDN](https://pantheon.io/docs/global-cdn)

Priority: Medium (choose one, remove the other options)

## Issue Description:

Two issues:
* The first FAQ (https://pantheon.io/docs/global-cdn#i-already-have-a-cdn---should-i-switch) assumes that there are customers who might still need to switch, or are evaluating it, and I'm not sure this is the case anymore.
* For those customers who do need to stack a CDN in front of the GCDN, either due to feature gap or existing contractual obligation (i.e. 'we are already paying for Akamai'), it would be useful to express some general best practices for stacking secondary CDNs in front, especially as it pertains to configuring caching.

## Suggested Resolution

* The first FAQ should be rewritten to reflect the current state of the customer base.
* Add a new FAQ for 'Configuring caching for stacked CDNs' and express in general the best practices (i.e. 'use GCDN for caching by allowing traffic to pass through'). If there are additional general best practices, add additional FAQs, or rephrase the question to focus on best practices in general.

**Comment by alexfornuto** [comment]
Steps to resolve:

1. Compile existing documentation on Stacked CDN best practices to move or cross-link here.
2. Solicit input from SMEs like @joshualieb on what best practices Pantheon suggests.

**Comment by alexfornuto** [comment]
P.S. A lot of this is probably already in https://pantheon.io/docs/cloudflare

**Comment by tmountjr** [comment]
I think the changes work. @alexfornuto I may ping you separately with some other thoughts around our third-party CDN documentation in general.
