### ISSUE TITLE
May 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5607]
For updates occurring in April, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by greg-1-anderson** [comment]
### WordPress 5.4
Update to WordPress 5.4. For more information, see https://wordpress.org/news/2020/03/adderley/

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.5 
Update to Drupal 8.8.5. For more information, see https://www.drupal.org/project/drupal/releases/8.8.5

**Comment by EdwardAngert** [comment]
### Localdev 0.10.0
Localdev supports Multidev as of Localdev 0.9.3. The newest version includes numerous bug fixes and improvements. See https://pantheon.io/docs/localdev#changelog for more information.

**Comment by greg-1-anderson** [comment]
### WordPress 5.4.1
Update to WordPress 5.4.1. For more information, see https://wordpress.org/news/2020/04/wordpress-5-4-1/
