### ISSUE TITLE
Why you should run migrations in Drush rather than the UI

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#561]
Link to https://www.drupal.org/node/1806824 and add any relevant Pantheon-specific details

**Comment by nataliejeremy** [comment]
@ari-gold Which doc should this be added to?

**Comment by ari-gold** [comment]
I'm not sure. I think we might need a new article on Drupal's Migrate module. I'm happy to take it on soonish. 

If people run into 502 timeouts using the Migrate UI they should try Drush, which is strongly recommended at https://www.drupal.org/project/migrate

Barebones would probably be enough for our first doc iteration and maybe we can later fill it out with a more complete example with terminus (https://github.com/pantheon-systems/cli) commands and/or screenshots.

**Comment by timani** [comment]
A couple of places I can think of:

- https://pantheon.io/docs/articles/sites/timeouts/ 
- https://pantheon.io/docs/articles/sites/errors-and-server-responses/

The server responses is definitely one as they can see the error that they got and the recommended solution

**Comment by ari-gold** [comment]
@timani good call.

**Comment by ari-gold** [comment]
This was addressed by https://github.com/pantheon-systems/documentation/pull/566
