### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5625]
Re: [Terminus Manual](https://pantheon.io/docs//terminus/commands)

Priority: Low

## Issue Description:
The command `terminus plan:info <site_name>` returns a 404. Is this command deprecated?
![Example](https://user-images.githubusercontent.com/22105265/78588519-6c46c100-7804-11ea-802a-b504d1187ee7.png)

using `terminus 2.3.0`

## Suggested Resolution
Remove form docs

**Comment by alexfornuto** [comment]
Reaching out internally to the Terminus team to find out if this command is deprecated or if there's an API endpoint bug, or other.

**Comment by alexfornuto** [comment]
Tracking internally as `BUGS-3082`
