### ISSUE TITLE
Parsing Nginx Access Logs with GoAccess Doc Update 

### ISSUE THREAD

**Issue by geraldvillorente** [pantheon-systems/documentation#5630]
Re: [Parsing Nginx Access Logs with GoAccess](https://pantheon.io/docs/nginx-access-log)

Priority: Medium

## Issue Description:
The Goaccess format is not correct based on our current log format. Using the format indicated in this documentation will give the users different results.

To test: 

- Download `nginx-access.log`.
- Parse `nginx-access.log` using the format indicated on this documentation: `goaccess -f nginx-access.log --log-format '%h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"' --date-format '%d/%b/%Y' --time-format '%T'`
- Parse `nginx-access.log` using the current Goaccess configuration (`/etc/goaccess.conf`): `goaccess -f nginx-access.log --log-format '%^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%h,%^"' --date-format '%d/%b/%Y' --time-format '%H:%M:%S'`
- Compare the results.

## Suggested Resolution
Update the format to match Goaccess configuration in the platform. 

From:

```
time-format %T
date-format %d/%b/%Y
log-format %h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"
```

To: 

```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%h,%^"
```

**Comment by alexfornuto** [comment]
@geraldvillorente I get the same error with either of the example commands above: `Token 'ET' doesn't match specifier '%s'`

I tried running just `goaccess nginx-access.log` or `goaccess nginx-access.log > report.html` with both config formats, and didn't see a difference between the two.

Can you take another look at what needs to happen here?

**Comment by geraldvillorente** [comment]
@alexfornuto there should have a double space between these two: `[%d:%t %^]  "%r"`

Old format: 

```
goaccess -f nginx-access.log --log-format '%h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"' --date-format '%d/%b/%Y' --time-format '%T'
```

New format:

```
goaccess -f nginx-access.log --log-format '%^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%h,%^"' --date-format '%d/%b/%Y' --time-format '%H:%M:%S'
```

Another option is to save the format to a file like:

```
~/goaccess-new.conf
~/goaccess-old.conf
```

Then run like these:

```
$ goaccess -p ~/goaccess-new.conf nginx-access.log
$ goaccess -p ~/goaccess-old.conf nginx-access.log
```

**Comment by alexfornuto** [comment]
Thanks @geraldvillorente!
