### ISSUE TITLE
Add machine token naming conventions to docs

### ISSUE THREAD

**Issue by sugaroverflow** [pantheon-systems/documentation#5637]
Re: Creating and Revoking Machine Tokens
https://pantheon.io/docs/machine-tokens

Priority: Low

## Issue Description

When adding a machine token, if you do any of the following, the token name becomes "Generic Feature Phone". This is not helpful if you're trying to specify the device or CI build you're using the token for. 

- `pantheon hud` 
- `pantheonHud`
- `pantheon-hud`

## Suggested Resolution

Update docs to include naming convention for machine tokens.

**Comment by sugaroverflow** [comment]
I looked and was not able to find any details on naming conventions on the docs, but apologies if I missed this somewhere :)

**Comment by alexfornuto** [comment]
@sugaroverflow I'd first want to check internally to find out if this is a feature or a bug.

**Comment by EdwardAngert** [comment]
reported as BUGS-3095 and holding off on Docs update for now

**Comment by alexfornuto** [comment]
I'm going to close this issue for now. Will re-open if the resolution of BUGS-3095 doesn't resolve the issue.
