### ISSUE TITLE
WordPress Known Issues Doc Update WP cli eval not working

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5650]
Re: [WordPress Known Issues](https://pantheon.io/docs/wordpress-known-issues)

Priority: Low

## Issue Description:
WP cli eval command https://developer.wordpress.org/cli/commands/eval/ is not working in the platform

## Suggested Resolution

Document that wp cli eval command https://developer.wordpress.org/cli/commands/eval/ is not working in the platform for an easy referral to customers

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! We're going to find out if this is simply a known limitation or a bug that Product can fix.

Was this brought up in a ticket/chat?

**Comment by alexfornuto** [comment]
Closing due to lack of communication.

**Comment by carl-alberto** [comment]
Aww, sorry @alexfornuto, this went out of my radar, I believe this would be similar to Drush's eval not working too which is documented here https://pantheon.io/docs/drush#execute-php-code-using-drush-on-pantheon, wp cli has a shell command that seems to be working that can be an alternative https://developer.wordpress.org/cli/commands/shell/ in terminus
