### ISSUE TITLE
Manually Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by brenda003** [pantheon-systems/documentation#5652]
Re: [Manually Migrate Sites to Pantheon](https://pantheon.io/docs/migrate-manual)

Priority: Low

## Issue Description:

This doc doe not work for composer based sites and has caused confusion for customers.

## Suggested Resolution

Add a disclaimer that this is not for migration of composer based sites.

**Comment by alexfornuto** [comment]
@brenda003 How would  we suggest that composer-based sites migrate to Pantheon?
