### ISSUE TITLE
Align "Before You Begin" Section w/ Doc for Manual Migration

### ISSUE THREAD

**Issue by JQTNguyen** [pantheon-systems/documentation#5664]
Re: Align "Before You Begin" Section w/ Doc for Manual Migration

Priority: Low

## Issue Description

Consider aligning the "Before You Begin" tasks/section that appears both here and on the [documentation for Manual Migrations](https://pantheon.io/docs/migrate-manual). 

## Suggested Resolution

Have the same important tasks called to attention in both places. For example, listing [Modules and Plugins with Known Issues](/modules-plugins-known-issues) for both.

For ease of access, below is a copy of the "Before You Begin" sections of both pages, at the time of this writing.

Currently on https://pantheon.io/docs/migrate...

> ## Before You Begin
> To ensure a successful migration, complete the following tasks on the source site first:
> 
> - Upgrade to the latest version of WordPress or Drupal core
> - Clear all caches
> - Remove unneeded code, database tables, and files
> - Make sure to read [Platform Considerations](/platform-considerations) and plan to mitigate any conflicts with the site needs or architecture.

Seen on https://pantheon.io/docs/migrate-manual...

> ## Before You Begin
> To ensure a successful migration, complete the following tasks on the source site before you start:
> 
> - Read [Platform Considerations](/platform-considerations)
> - Reference your plugins and/or modules against [Modules and Plugins with Known Issues](/modules-plugins-known-issues)
> - Make sure your code is compatible with PHP 7.2. If not, be prepared to [adjust PHP versions](/php-versions/#configure-php-version)
> - Upgrade to the latest version of WordPress or Drupal core
> - Clear all caches
> - Remove unneeded code, database tables, and files
> - [Configure SSH keys](/ssh-keys)
>

**Comment by alexfornuto** [comment]
Thanks for the well-written issue @JQTNguyen! Please take a look at the PR resolving it.
