### ISSUE TITLE
Add Known Issue for Thrive Theme Builder - FS Method 

### ISSUE THREAD

**Issue by scottcbranch** [pantheon-systems/documentation#5672]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: Thrive theme Builder needs a direct FS method to work in Live

Priority: Low

## Issue Description
Please update the documentation on the link https://pantheon.io/docs/plugins-known-issues#define-fs_method  to show that Thrive Theme Builder also needs the fs method defined to be direct. 

I launched a new site https://ptshome.com/ and I had an issue where the theme would not save changes correctly and pages were also not displaying correctly.  I added the code below and it works fine now. 

if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
    define('FS_METHOD', 'direct');
}

I also confirmed with the theme developer that the live site was not properly saving changes to the path /wp-content/uploads/thrive/  before the change was made.  After the fs method change the css file is properly saving in that path on the live environment. 

## Suggested Resolution
Update the plugins with known issues page to help others using Thrive Theme Builder on Pantheon
Known Issues Page -FS Method Section
https://pantheon.io/docs/plugins-known-issues#define-fs_method

Thrive Theme Builder Product Page
https://thrivethemes.com/themebuilder/

**Comment by alexfornuto** [comment]
@scottcbranch thanks for letting us know!
