### ISSUE TITLE
Update SendGrid guide

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5679]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs//guides/sendgrid)

Priority: Medium

## Issue Description:
SendGrid's authentication methods have changed; guide requires review and update.

## Suggested Resolution
Update to reflect single sender verification process (for testing) and DNS domain authentication methods. Process described in [SendGrid's docs](https://sendgrid.com/docs/for-developers/sending-email/sender-identity/).

**Comment by sdubois** [comment]
I don't think this is complete. Sendgrid now requires adding some DNS records or doing "single sender authentication" to verify your identity. https://sendgrid.com/docs/ui/sending-email/sender-verification/

The Pantheon documentation should mention this. As it currently stands if someone follows the Pantheon guide for configuring Sendgrid their site will be unable to send emails.

**Comment by alexfornuto** [comment]
@sdubois thanks for this additional info! The account I was using to test and update this guide was made before April 6 2020, so I didn't hit this issue. I'll make a new account and do another round of testing.

**Comment by sdubois** [comment]
Thanks. I set this up on a few sites recently. Let me know if you need any
help.

**Comment by alexfornuto** [comment]
@sdubois If you'd like to be a contributor to this doc, I'd be happy to work with you on a PR to add the required additional info.

**Comment by sdubois** [comment]
I'd be glad to.

**Comment by alexfornuto** [comment]
:+1: - I reached out to you on the Pantheon Community Slack to discuss further.
