### ISSUE TITLE
June 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5687]
For updates occurring in May, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).
```

**Comment by ari-gold** [comment]
### Global CDN enhancement prevents resource exhaustion from specific user-agents

Global CDN now blocks requests identified as being performed by the AspiegelBot when a query string is present. This platform-wide change is intended to guard against resource exhaustion and related site downtime. Going forward these requests will result in a 403 and will not count as site traffic for Pages Served and Visits. For more information see <doc>

**Comment by greg-1-anderson** [comment]
### Drupal 8.8.6 
Update to Drupal 8.8.6. For more information, see https://www.drupal.org/project/drupal/releases/8.8.6

**Comment by greg-1-anderson** [comment]
### Drupal 7.70 
Update to Drupal 7.70. For more information, see https://www.drupal.org/project/drupal/releases/7.70
