### ISSUE TITLE
Better Search Replace and Velvet Blues do not work.

### ISSUE THREAD

**Issue by plethoradesign** [pantheon-systems/documentation#5689]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
The suggested workaround for Velvet Blues doesn't work (for me, anyway). I also tried the Velvet Blues plugin, and that didn't work.
 
WP Migrate DB worked, though, without any workarounds.

## Suggested Resolution
Use WP Migrate DB and do not use Velvet Blues or Better Search Replace.

**Comment by alexfornuto** [comment]
Hi @plethoradesign! Thanks for the suggestion! I think this may be a [community discussion](https://discuss.pantheon.io/) waiting to happen more than a documentation update. We don't currently document anything about Blue Velvet's Plugin, and there isn't any technical details here to go on.
