### ISSUE TITLE
Update usage of passthru in Quicksilver to check return_var

### ISSUE THREAD

**Issue by marfillaster** [pantheon-systems/documentation#5696]
Re: [Database Workflow Tool](https://pantheon.io/docs/database-workflow), [Fix Broken Links in WordPress](https://pantheon.io/docs/wordpress-broken-links)

Priority: Medium

## Issue Description: 
The [passthru](https://www.php.net/manual/en/function.passthru.php) usage for fixing broken links will result in a false positive if wp cli returns with non-zero exit code.

## Suggested Resolution: 
Check &$return_var value and raise an error to propagate the error to the calling quicksilver script.

```php
$cmd = 'wp search-replace "://test-example.pantheonsite.io" "://example.com" --all-tables ';
passthru($cmd . ' 2>&1', $exit);
if (0 !== $exit) {
  trigger_error(sprintf('Command "%s" exit status: %s', $cmd, $exit), E_USER_ERROR);
}
```

**Comment by marfillaster** [comment]
Also created issue on pantheon-systems/quicksilver-examples/issues/169

**Comment by alexfornuto** [comment]
CC @pantheon-systems/devrel

**Comment by alexfornuto** [comment]
Moving to not ready until the discussion in  https://github.com/pantheon-systems/quicksilver-examples/issues/169 creates a resolution we can duplicate.

**Comment by EdwardAngert** [comment]
closing as stale until https://github.com/pantheon-systems/quicksilver-examples/issues/169 is resolved
