### ISSUE TITLE
WordPress Plugins and Themes with Known Issues Doc Update 

### ISSUE THREAD

**Issue by plethoradesign** [pantheon-systems/documentation#5701]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
When using WP Rocket, /wp-content/advanced-cache.php causes caching problems on Test and Live. Symptoms include random blank pages and cache-clears not working whatsoever.

## Suggested Resolution
When using WP Rocket make sure NOT to allow WP Rocket's auto-generated /wp-content/advanced-cache.php file to make it to Test or Live. This file is used by WP Rocket for page caching, which conflicts with Pantheon's own caching. Documentation should mention this. I spent a lot of time debugging WP Rocket on your platform before figuring this out.

**Comment by alexfornuto** [comment]
Thanks @plethoradesign! Since I'm not familiar with this plugin I'm gonna reach out internally for a technical review.

**Comment by carolyn-shannon** [comment]
This step is already described (as Step 1) in the documentation.

**Comment by plethoradesign** [comment]
No it isn't. Advanced-cache.php is not mentioned at all on https://pantheon.io/docs/plugins-known-issues .

**Comment by alexfornuto** [comment]
@plethoradesign I think we're getting the same result through a different method, disabling WP-Rocket's caching as a setting:

> Disable WP-Rocket caching by finding the WP_CACHE value defined by WP-Rocket in wp-config.php, and setting it to false:

Is this not the same?

**Comment by plethoradesign** [comment]
sort of. One could easily interpret " Disable WP-Rocket caching by finding
the WP_CACHE value defined by WP-Rocket in wp-config.php, and setting it to
false" as an optional thing and then not realize WP Rocket will auto-create
that advanced-cache.php file.

Casper Voogt



casper.voogt@plethoradesign.com
Plethora Design
Work: (877) 515-6682 ext.2
https://www.plethoradesign.com
