### ISSUE TITLE
"last reviewed" for modules with known issues is inconsistent

### ISSUE THREAD

**Issue by tmountjr** [pantheon-systems/documentation#5706]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: [Drupal Modules with Known Issues](https://pantheon.io/docs/modules-known-issues)

Priority: Low

## Issue Description
Some (but not all) modules have a subheading entitled "Last reviewed:"; if that header is present, the value for each of these is "Date" (see screenshot).

<img width="671" alt="Screen Shot 2020-05-12 at 09 08 53" src="https://user-images.githubusercontent.com/1203675/81695580-d3254e80-9430-11ea-9933-7a0876ea55ed.png">

## Suggested Resolution
Could either add "Last Reviewed" headers for all modules and update the dates; or remove those headers for all modules.

**Comment by alexfornuto** [comment]
I just took a look and the component is working as far as I can tell. This may have been a transient issue. @tmountjr are you still seeing "Date"?
![image](https://user-images.githubusercontent.com/2349184/81706815-da029000-9435-11ea-82a1-d52f4602f3e7.png)

**Comment by alexfornuto** [comment]
For those playing at home, FF doesn't like it when you specify a timezone in your JS Date object.
