### ISSUE TITLE
Manage Plans in the Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by plethoradesign** [pantheon-systems/documentation#5708]
Re: [Manage Plans in the Site Dashboard](https://pantheon.io/docs/site-plan)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
"Downgrade to Sandbox" section does not actually explain *how* to downgrade to a sandbox.

## Suggested Resolution
Add info on how to downgrade to a sandbox.

**Comment by carolyn-shannon** [comment]
add link to https://pantheon.io/docs/site-plan#downgrades
