### ISSUE TITLE
Build Tools Doc Update - Missing link to customization

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/documentation#5718]
Re: [Build Tools](https://pantheon.io/docs//guides/build-tools/create-project)

Priority: Medium

## Issue Description:

https://pantheon.io/docs/guides/build-tools/create-project
This page states:

> To use your own template repository see Customization.

And links to https://pantheon.io/docs/guides/build-tools/create-project#customization, but there is no customization section on that page.

## Suggested Resolution

Add the correct link or add the intended content.

**Comment by EdwardAngert** [comment]
thanks, @ptmkenny!
I fixed the link to point to https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/README.md#customization
