### ISSUE TITLE
doc page that explains how to configure CDN's for Pantheon

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#572]
and why we don't allow you to set the omit in Drupal.  David Strauss can help.

**Comment by nataliejeremy** [comment]
@nstielau @davidstrauss Would this page work for this? https://pantheon.io/docs/articles/drupal/content-delivery-network-cdn-for-file-distribution/
We can updated it with the additional info.

**Comment by atjuch** [comment]
@nataliejeremy @nstielau @davidstrauss I would like to write up a doc and test the Fastly CDN. Not sure if we want to dedicate it's own page and we can separate it out to have a Drupal and WordPress section. 

If there is any information that could be useful for do's and don'ts with CDN's that would be help @davidstrauss or @nstielau.

Would could add a link to the page Natalie provided to include Fastly. Let me know your thoughts.

**Comment by nstielau** [comment]
Sounds good to me.  Ari worked on Fastly setup with a few different folks,
so he’d have more info.

If we get a few different CDN guides up, we might want to give a one-liner
about why you’d use one or the other, i.e. vastly lets you write custom VCL
if you want to do any edge-side logic.

On Sun, Jun 21, 2015 at 10:43 PM, atjuch <notifications@github.com> wrote:

> @nataliejeremy <https://github.com/nataliejeremy> @nstielau
> <https://github.com/nstielau> @davidstrauss
> <https://github.com/davidstrauss> I would like to write up a doc and test
> the Fastly CDN. Not sure if we want to dedicate it's own page and we can
> separate it out to have a Drupal and WordPress section.
>
> If there is any information that could be useful for do's and don'ts with
> CDN's that would be help @davidstrauss <https://github.com/davidstrauss>
> or @nstielau <https://github.com/nstielau>.
>
> Would could add a link to the page Natalie provided to include Fastly. Let
> me know your thoughts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/documentation/issues/572#issuecomment-114011497>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon

**Comment by bmackinney** [comment]
Closing as dup to #462
