### ISSUE TITLE
Quick Start Doc Update 

### ISSUE THREAD

**Issue by powpow12** [pantheon-systems/documentation#5726]
Re: [Quick Start](https://pantheon.io/docs//guides/quickstart/user-dashboard)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Youtube video is not embedded, the url is printed out.
![image](https://user-images.githubusercontent.com/3721535/82343877-5dd1f480-99c1-11ea-8db8-0a6d514e0949.png)

## Suggested Resolution
* Have the video embedded

**Comment by alexfornuto** [comment]
Whoops! Some idiot (me) forgot to update those references when he switched out a plugin for an MDX Component. Fixing now.

Thanks @powpow12!
