### ISSUE TITLE
WordPress Dashboard: Add process to uninstall WordPress plugins

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5729]
Re: [Working in the WordPress Dashboard and Drupal Admin Interface](https://pantheon.io/docs/cms-admin)

Priority: Low

## Issue Description:
Completely removing a WP plugin requires a two-step process, as WP tries to both update the database and remove files during the uninstall process but the live environment prevents file deletes from the codebase.

## Suggested Resolution
Add instructions for uninstalling WP plugins via a multi-step process ([wpcli reference](https://developer.wordpress.org/cli/commands/plugin/uninstall/)).
1. Test/verify that removing the plugin is fine on local or dev.
1. Use terminus wpcli to run `wp plugin uninstall EXAMPLE --skip-delete` on the live environment to remove the database tables, but skip deletion of the plugin files.
1. Run `wp plugin uninstall EXAMPLE`, or use the dashboard plugin uninstaller, on local or dev, verify again that all works as expected. 
1. Commit the code change, then push the code to live.

## To Do 
- [x] best place to put this may be the CMS Admin page section on the WP Dashboard (https://pantheon.io/docs/cms-admin#wordpress-dashboard), or the Terminus page with a reference on the WP Dashboard command line section.
- [x] the Pantheon Updates plugin disables automatic updates in test and live (https://pantheon.io/docs/plugins#pantheon-updates). We should probably add something there about the process for removing plugins.
- [x] Should include the process for removing any symlinks, as described here: https://pantheon.io/docs/symlinks-assumed-write-access#removing-a-symlink
- [x] Should update the partials describing removing WP Redis and Solr for WP, displayed here: https://pantheon.io/docs/site-plan#basic-plan
- [ ] Process for uninstalling plugins in the Terminus guide would also need update or reference: https://pantheon.io/docs/terminus/plugins

**Comment by carolyn-shannon** [comment]
Thanks to @nullvariable, Kaylan Wagner and @greg-1-anderson for helpful suggestions on process.

**Comment by alexfornuto** [comment]
Removing from the project to continue tracking in [the PR](https://github.com/pantheon-systems/documentation/pull/5828)
