### ISSUE TITLE
Switching Sites from HTTP to HTTPS Doc Update 

### ISSUE THREAD

**Issue by jdpantheon** [pantheon-systems/documentation#5738]
Re: [Switching Sites from HTTP to HTTPS](https://pantheon.io/docs/http-to-https)

Priority: Low

## Issue Description:

I think there's some ambiguity with the language that could be confusing to people worried about redirect chains, specifically in the `Spot-check new and existing redirects` section.

For context, a customer had questioned why there was an additional redirect hop in a ticket/chat:

> That seems to directly contradict your documentation here: https://pantheon.io/docs/http-to-https#spot-check-new-and-existing-redirects
>
> If there's no expectation that setting a primary domain would ever result in a single redirect, then this documentation is at best very misleading.

The issue the customer had was regarding the extra hop when a primary domain was set:

```
$ curl -sIL http://www.examplesite.com | grep HTTP
HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
HTTP/1.1 200 OK
```

Going off our documentation in that section above, that's not ideal to have an additional redirect hop since there's a primary domain set (per our docs). However,  it is confusing because it seems this *IS* expected on our platform when setting a primary domain. Testing the responses on a domain of mine:

*Without a primary domain*

```
$ curl -sIL otherexamplesite.com | grep HTTP
HTTP/1.1 301 Moved Permanently
HTTP/1.1 200 OK
```

*With primary domain set to www.otherexamplesite.com*

```
$ curl -sIL otherexamplesite.com | grep HTTP
HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
HTTP/1.1 200 OK
```

## Suggested Resolution

If someone wants to remove the additional redirect hop, then they would have to do the following:

- make sure they're using `transitional` parameter for `enforce_https` in the pantheon.yml
- ensure there aren't any redirects in their wp-config.php (like listed [here](https://pantheon.io/docs/redirects#redirect-with-php))
- remove the primary domain.

Or state that adding a primary domain would create an addition redirect hop in the chain.

*edited because I forgot I was testing parameters to get this working before. oops.

**Comment by alexfornuto** [comment]
Thanks for the issue! This guide was written before we had HTTPS for all, and even though it's been updated since then, it didn't take the Primary domain into account for this section. Will update.

**Comment by EdwardAngert** [comment]
opened BUGS-3223
