### ISSUE TITLE
Document settings.php changes req'd for DropZoneJS

### ISSUE THREAD

**Issue by dalin-** [pantheon-systems/documentation#5747]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re:
* https://github.com/pantheon-systems/documentation/blob/cadb79e1399a94a6d255d2e36b41c059ad905aea/source/content/modules-known-issues.md
* https://pantheon.io/docs/modules-known-issues

Priority: Medium

## Issue Description
The same "/tmp isn't persistent between webheads" issues as we see with many other modules on this list.

## Suggested Resolution
In `settings.php`

```php
/**
 * Ensure that DropZoneJS works in the live environment.
 * 
 * Which has multiple webheads, so choose a scheme that is 
 * shared by all.
 **/
$config['dropzonejs.settings']['tmp_upload_scheme'] = 'private';

```

**Comment by dalin-** [comment]
Actually, scrap this.  This fix isn't actually working.  Investigating deeper fixes.  See the d.o issue:
https://www.drupal.org/project/dropzonejs/issues/2916330

**Comment by alexfornuto** [comment]
@dalin- thanks for reporting! We'll document this as a known issue, and link to that thread to follow along / wait for a solution to come from the maintainers.
