### ISSUE TITLE
July 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5751]
For updates occurring in June, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).

**Comment by greg-1-anderson** [comment]
### WordPress 5.4.2 released

WordPress has been upgraded to [version 5.4.2](https://wordpress.org/news/2020/06/wordpress-5-4-2-security-and-maintenance-release/). As part of this release, Pantheon also rolled out a configuration change to [block xmlrpc by default](https://pantheon.io/docs/wordpress-best-practices#disable-xml-rpc-via-pantheonyml). If your site uses xmlrpc, [re-enable it](https://pantheon.io/docs/pantheon-yml#protected-web-paths-override) before deploying this release to production.

**Comment by greg-1-anderson** [comment]
### Terminus 2.4.0 released
See the [release notes](https://github.com/pantheon-systems/terminus/releases/tag/2.4.0) for more information.

**Comment by greg-1-anderson** [comment]
### Drupal 8.9.1, 8.8.8 and 7.72 released
These are security releases; all sites are urged to update as soon as possible. For more information, see the release notes ([8.9.1](https://www.drupal.org/project/drupal/releases/8.9.1), [8.8.8](https://www.drupal.org/project/drupal/releases/8.8.8) and [7.72](https://www.drupal.org/project/drupal/releases/7.72), respectively).
