### ISSUE TITLE
Build Tools Doc Update 

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/documentation#5756]
Re: [Build Tools](https://pantheon.io/docs//guides/build-tools/create-project)

Priority: Medium

## Issue Description:

Step 5 says `Create the $HOME/.terminus/plugin directory if it does not already exist`, but step 6 creates a `plugins` directory.  Do we need both, or is just one sufficient?

**Comment by alexfornuto** [comment]
Thanks @ptmkenny! I've staged a fix at #5759
