### ISSUE TITLE
Add to Quicksilver troubleshooting section

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#5768]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: https://pantheon.io/docs/quicksilver#troubleshooting

Priority: Med

## Issue Description

Quicksilver script for deploy hook will not trigger on first deploy

## Suggested Resolution

Document behavior and inform that they must deploy again

**Comment by alexfornuto** [comment]
Pending input from the project maintainer.

**Comment by nullvariable** [comment]
This is actually already covered in the doc, but I think it could be highlighted/called out better

> Likewise, if you are adding new operations or changing the script an operation will target, the deploy containing those adjustments to pantheon.yml will not self-referentially exhibit the new behavior. Only subsequent deploys will be affected.

The wording is a bit collegiate level, and it's buried in a paragraph, so it suffers from readability issues at the very least. I'd suggest a callout box to highlight this information, with something like the following text:

```
Caution! Quicksilver scripts that trigger on the deploy hook will always operate
on the state of the code at the time of the deploy, not the state of the code after the deploy. 
This means new/updated code is not available until the deployment is finished, however the deploy hook is triggered at the start of the deploy.
```
