### ISSUE TITLE
Add MixedCase DNS unsupported to troubleshooting

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#5769]
**Note:** Partial or incorrectly filled out issues may be deferred.

Re: https://pantheon.io/docs/domains#troubleshooting

Priority: Med

## Issue Description

Mixedcase DNS records may show unexpected behavior on site dashboard

.e.g. ExAmPle.cOm

## Suggested Resolution

Document known issue and suggest changing any mixed case records

**Comment by alexfornuto** [comment]
@ari-gold can you expand on what unexpected behavior we're seeing? Is there a bug card or replicated example for reference?
