### ISSUE TITLE
Configuring wp-config.php Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5776]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php)

Priority: Low

## Issue Description:
The second code snippet in [this section](https://pantheon.io/docs/wp-config-php#how-do-i-change-the-default-debuglog-location) is missing the forward-slash before wp-content

## Suggested Resolution
Instead of reading as 
`define( 'WP_DEBUG_LOG', __DIR__ . 'wp-content/uploads/debug.log'`

The correct snippet is 

`define( 'WP_DEBUG_LOG', __DIR__ . '/wp-content/uploads/debug.log'`

**Comment by alexfornuto** [comment]
@CFin86 And it definitely needs the preceding slash? As in, we shouldn't remove it from the other example instead?

**Comment by CFin86** [comment]
Might want to get a second opinion on this as I never want to be the singular source of information, but without the preceding slash it would look like: `example.comwp-content/uploads/debug.log` opposed to my suggested fix which would `example.com/wp-content/uploads/debug.log`

**Comment by alexfornuto** [comment]
Thanks @CFin86! Per Slack discussion, waiting on 2nd opinion from @jocastaneda.
