### ISSUE TITLE
APC Cache

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5778]
Re: [What is APC and what is it used for?](https://pantheon.io/docs/alternative-php-cache)

Priority: Low

## Issue Description:
Confirm that clearing the cache via dashboard actually clears the APC cache.

## Suggested Resolution

**Comment by alexfornuto** [comment]
So it would seem that a lot of information on this page is out of date. I'd like to partner with a developer or one of our platform engineers to go through the entire thing and update it.
