### ISSUE TITLE
Backups Tool Doc Update 

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/documentation#5779]
Re: [Backups Tool](https://pantheon.io/docs/backups)

Priority: Medium

## Issue Description:

The sample `pantheon-backup-to-s3.sh` script on this page invokes `#!/bin/sh`, which will call whatever shell is the default on the system.

However, the line `if [[ $element == "db" ]]; then` is bash specific, so if `bash` is not the default shell, then you get errors:

```
 ./pantheon-backup-to-s3.sh 
 [notice] Logging in via machine token.
 [notice] Created a backup of the live environment.
./pantheon-backup-to-s3.sh: 49: [[: not found
./pantheon-backup-to-s3.sh: 49: [[: not found
```

More info here: https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found/17753098

## Suggested Resolution

Force the script to execute in bash, or rewrite the script so it is more universal.

**Comment by alexfornuto** [comment]
Thanks @ptmkenny! Changing it to `#!/bin/bash` should explicitly invoke bash, right?

**Comment by ptmkenny** [comment]
Yes, that's one way to fix it.
