### ISSUE TITLE
Update Drupal cron screenshots to Drupal 8+

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#5790]
Re: [Cron for Drupal](https://pantheon.io/docs/drupal-cron)

Priority: Low

## Issue Description:
As more users are adopting Drupal 8 and 9 moving forward, it may be beneficial to update the screenshots to show a Drupal 8 interface vs Drupal 7.

## Suggested Resolution
Take new screenshots for Drupal 8 cron steps.

**Comment by alexfornuto** [comment]
Closing this issue as merged with #5254, thanks @kyletaylored!
