### ISSUE TITLE
Add instructions for a new filter to allow the Pantheon WordPress login text to be modified

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/documentation#5791]
Re: Customization filter for WordPress login page
Original Issue: https://github.com/pantheon-systems/WordPress/issues/192
PR: https://github.com/pantheon-systems/WordPress/pull/210

Priority: Medium

## Issue Description
The linked PR fixes an outstanding issue where Pantheon's WordPress login screen customization removes the ability to use the `login_message` filter to add a custom login message
## Suggested Resolution
New documentation on how to use the `pantheon_wp_login_text` filter described in [the PR](https://github.com/pantheon-systems/WordPress/pull/210) from an mu plugin or a theme's `functions.php` file.

**Comment by alexfornuto** [comment]
We should document https://github.com/pantheon-systems/WordPress/issues/155 while we're at it, adding to https://pantheon.io/docs/wp-config-php

**Comment by alexfornuto** [comment]
So I discovered something fun: You apparently cannot customize the WordPress login text and _also_ remove the "Return to Pantheon" button with:

```
if ( ! defined( 'RETURN_TO_PANTHEON_BUTTON' ) ) {
	define( 'RETURN_TO_PANTHEON_BUTTON', false );
}
```

@pwtyler is this expected behavior? If not, can you advise me on how a user can control both aspects of the login page?

**Comment by pwtyler** [comment]
If `RETURN_TO_PANTHEON_BUTTON` is false, wp-login.php will use the default wp-login.php template, so the default WordPress `login_message` [hook](https://developer.wordpress.org/reference/hooks/login_message/) can be used.

So instead of
``` PHP
add_filter( 'pantheon_wp_login_text', function() {
	return "This is my custom message on Pantheon's wp-login.php page";
});
```
use
``` PHP
add_filter( 'login_message', function() {
	return "This is my custom message when not using Pantheon's wp-login override.";
});
```
in functions.php or wherever the filters are implemented. `pantheon_wp_login_text` is specifically for filtering/changing the Pantheon-introduced message.
