### ISSUE TITLE
Add more info to Localdev page about Slack Channel

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#5793]
Re: [Use Pantheon Localdev to Develop Sites Locally](https://pantheon.io/docs/localdev)

Priority: Medium

## Issue Description:

A few customers have come into chat asking how they can access the Localdev Slack channel. The link goes directly to the Slack channel, but doesn't talk about how to get an account if you don't already have one.

## Suggested Resolution

Maybe add a link to the Pantheon Community page? https://pantheon.io/docs/pantheon-community

Or maybe just link to this URL that allows you to get an invite to the Slack channel? https://slackin.pantheon.io/

**Comment by alexfornuto** [comment]
Let's do both.

**Comment by EdwardAngert** [comment]
closed by #5897
