### ISSUE TITLE
HTTPS on Pantheon's Global CDN Doc Update 

### ISSUE THREAD

**Issue by peter-pantheon** [pantheon-systems/documentation#5829]
Re: [HTTPS on Pantheon's Global CDN](https://pantheon.io/docs//https)

Priority: Medium

## Issue Description:
In the section entitled: "Will HTTPS be available for my site throughout the upgrade process?", there is a NOTE pullout that indicates "If you do not already have HTTPS, there's no need to pre-provision." I believe this statement may be unclear or no longer be true. All domains should be validated so the cert can deploy in advance on Pantheon. 

## Suggested Resolution
Update this text.

**Comment by alexfornuto** [comment]
@peter-pantheon I believe the point of that statement is to say that since you don't already have HTTPS/TLS in the scenario being described, pre-provisioning isn't needed to ensure no loss in encryption coverage.

**Comment by alexfornuto** [comment]
Thanks @peter-pantheon!
