### ISSUE TITLE
Manually Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#5831]
Re: [Manually Migrate Sites to Pantheon](https://pantheon.io/docs/migrate-manual)

Priority: High

## Issue Description:
In the section [Using an SFTP Client](https://pantheon.io/docs/migrate-manual#using-an-sftp-client)
Step 4. could benefit from greater clarification. 
> Upload your existing site's plugins, modules, and themes to the code directory. Do not overwrite WordPress or Drupal core files on your Pantheon site.

As it is currently presented, this could be difficult to interpret unless you are familiar with WordPress, Drupal, and Pantheon's platform. It has also been interpreted as "Upload your existing `/plugins`, `/modules`, and `/themes` directory into the `/code` directory.

As WordPress does not use modules, and Drupal does not use plugins, it can cause frustration for new customers looking to migrate their existing site to the platform.

## Suggested Resolution
On 4. alter the instructions to be more descriptive about what Pantheon's file structure looks after connecting with an SFTP client. For example: 
> After successfully connecting, look for the folder named [code](https://i.imgur.com/WqkkRuT.png). This is also sometimes referred to as the `/root` directory. Your Drupal and WordPress core files are located here, but **overwriting or modifying core files is highly discouraged and we are unable to provide support.**

Provide the names of the WordPress/Drupal core files in the corresponding tablist. Adjust the Drupal 7 tab to include the same amount of information as the Drupal 8 tab has.

**Comment by alexfornuto** [comment]
We'll resolve by adding directory trees to each tab.
