### ISSUE TITLE
Frontend Performance Doc Update WP side needs to update the recommended plugins

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5836]
Re: [Frontend Performance](https://pantheon.io/docs//guides/frontend-performance)

Priority: Low

## Issue Description:
We might need to revisit this section as it recommends a 3 yr old un-updated plugin https://wordpress.org/plugins/bj-lazy-load in this section https://pantheon.io/docs/guides/frontend-performance#lazy-load-images

## Suggested Resolution
Autoptimize has the lazy loading feature so we can maybe recommend it instead

**Comment by carolyn-shannon** [comment]
May wish to broaden to include a number of lazy-load image plugins available: https://wordpress.org/plugins/search/lazy-load/

Also reference: https://make.wordpress.org/core/2020/04/08/lazy-loading-of-images-is-in-core/

**Comment by carolyn-shannon** [comment]
Recommend reconsidering Drupal module recommendation in favor of this one instead: https://www.drupal.org/project/lazy

https://www.drupal.org/docs/8/modules/lazy-load/how-to-use-composer-to-install-lazy-load-module-and-its-dependency

**Comment by carolyn-shannon** [comment]
For WP 5.5, lazy loading of images is coming to [WP core](https://make.wordpress.org/core/2020/04/08/lazy-loading-of-images-is-in-core/). This would be a good opportunity to update the lazy loading section with regard to WP plugins and lazy loading images.
