### ISSUE TITLE
Lock Environments - Add section on passing credentials to CI tools

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5853]
Re: [Lock Environments with the Dashboard Security Tool](https://pantheon.io/docs/security)

Priority: Low

## Issue Description:
- For CI script users, when a site environment is locked using the dashboard security tool, you must configure your CI tool to pass the username and password on every request, or tests will not run. See this [Community thread](https://pantheon-community.slack.com/archives/C5EM55T0X/p1594140217382100) for details.

## Suggested Resolution
- Add a section on CI scripting authentication needs with example, eg 
'{"base_url" : "https://username:password@'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io/"}'

**Comment by jane-gravityworks** [comment]
Would it also be possible to include a way to pass credentials to accessibility (Pa11y) and performance (Lighthouse) automatic testing?

For example:
# Run lighthouse
lighthouse "https://$PANTHEON_LOCK_USERNAME:$PANTHEON_LOCK_PASSWORD@$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/" --only-categories="performance" --chrome-flags="headless" --output="html" --save-assets

# Run pa11y-ci
pa11y-ci --sitemap "https://$PANTHEON_LOCK_USERNAME:$PANTHEON_LOCK_PASSWORD@$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/sitemap.xml"

**Comment by carolyn-shannon** [comment]
More info needed: is it possible to make this work by passing credentials in this way? Thread indicates workaround is to use Terminus to unlock, then re-lock site.
