### ISSUE TITLE
Clicking on TOC link scrolls too far on click hiding the section heading

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#5859]
Re: https://pantheon.io/docs

Priority: Medium

## Issue Description:
When a TOC link is clicked, the page scrolls too far past the target anchor/heading, e.g. https://pantheon.io/docs/guides/frontend-performance#full-page-caching overshoots the heading.
![image](https://user-images.githubusercontent.com/536441/86982413-0852d200-c13e-11ea-9dea-772cba66f795.png)

**Comment by EdwardAngert** [comment]
closed by #5888

**Comment by EdwardAngert** [comment]
closed by #5888
