### ISSUE TITLE
WordPress Configuration Management (WP-CFM) Doc Update for multidev

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5865]
Re: [WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm)

Priority: Low

## Issue Description:
Needs an update to get it to work with multidevs with the undocumented filter that was implemented https://github.com/forumone/wp-cfm/issues/95

related to tix#474223

## Suggested Resolution
Additional doc PR to follow

**Comment by alexfornuto** [comment]
Pinged @carl-alberto for the follow-up.
