### ISSUE TITLE
Parsing Nginx Access Logs with GoAccess Doc Update 

### ISSUE THREAD

**Issue by jeor0980** [pantheon-systems/documentation#5868]
Re: [Parsing Nginx Access Logs with GoAccess](https://pantheon.io/docs/nginx-access-log)

Priority: Low

## Issue Description:

In the code block for the rules to add to `goaccess.conf`

`log-format %^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%h,%^"`

Will result in the following error:

```
goaccess nginx-access.log
Parsed 1 lines producing the following errors:

Token for '%h' specifier is NULL.

Format Errors - Verify your log/date/time format
```

## Suggested Resolution

Update rule to:

`log-format %^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%h",%^`

**Comment by alexfornuto** [comment]
@jeor0980 thanks for the issue! On my system, the configuration in the doc works, but your suggest change returns:

```bash
❯ goaccess -p ~/.goaccessrc nginx-access.log
Parsed 1 linesproducing the following errors:

Token 'OST' doesn't match specifier '%s'
```

I'm running version 1.3 on Fedora Linux, what version and OS are you using?

**Comment by jeor0980** [comment]
I am running goaccess 1.4 on Mac OS Catalina (10.15.5)

**Comment by alexfornuto** [comment]
@EdwardAngert can you give this a look on your MBP?

**Comment by EdwardAngert** [comment]
@pantheon-systems/docs-admins to confirm tech (we believe and appreciate you @jeor0980 , but you know, have to verify), then make the change and 🚀

**Comment by EdwardAngert** [comment]
confirmed that it works on my Mac as written - closing
