### ISSUE TITLE
WordPress Site Networks Doc Update 

### ISSUE THREAD

**Issue by panth-jrefuerzo** [pantheon-systems/documentation#5873]
Re: [WordPress Site Networks](https://pantheon.io/docs//guides/multisite/config)

Priority: Low

## Issue Description:
Suggesting additional troubleshooting

## Suggested Resolution
Add in the troubleshooting section if getting error `Error: Cookies are blocked or not supported by your browser`. You must enable cookies to use WordPress. multisite  when users are trying to login in the admin of the multisite, users may need to add this in their wp-config `define('COOKIE_DOMAIN', $_SERVER['HTTP_HOST'] );`

**Comment by jrastaban** [comment]
@panth-jrefuerzo Can you share a little more about what this line does: 
`define('COOKIE_DOMAIN', $_SERVER['HTTP_HOST'] ); `

I think it would be helpful to have some context for why or when they should add this change to the config file.  Is this update targeted at multisite installs running custom TLDs for subsites?
