### ISSUE TITLE
First time launched sites have platform domain urls

### ISSUE THREAD

**Issue by marfillaster** [pantheon-systems/documentation#5881]
Re: [Launch Essentials](https://pantheon.io/docs//guides/launch/redirects)

Priority: Medium

## Issue Description: 

First time launched sites have platform domain urls.

## Suggested Resolution

Search and replace must be done the first time site is launched after successfully connecting custom [primary] domain. terminus example below and/or also add link to https://pantheon.io/docs/wordpress-broken-links

```
terminus wp <site>.live -- search-replace live-<site>.pantheonsite.io <custom-domain> --url=live-<site>.pantheonsite.io --dry-run
```

**Comment by alexfornuto** [comment]
We'll update the [previous page](https://pantheon.io/docs/guides/launch/redirects) to have readers test and update for relative paths before launching.

**Comment by alexfornuto** [comment]
Thanks for reporting @marfillaster!
