### ISSUE TITLE
Deleting a Site on Pantheon Doc Update 

### ISSUE THREAD

**Issue by conorbauer23** [pantheon-systems/documentation#5884]
Re: [Deleting a Site on Pantheon](https://pantheon.io/docs/delete-site)

Priority: Medium 

## Issue Description:
When a DNS rule is left pointing at a pantheon subdomain, it is vulnerable for a "hack". If someone finds out the subdomain, they can create an account on our platform and take over that domain. More about that here: 

https://medium.com/@hussain_0x3c/hostile-subdomain-takeover-using-pantheon-ebf4ab813111

## Suggested Resolution

On our delete site process doc, maybe including a "Hey! Here is a friendly reminder to remove any old DNS rules" or something like that would help.

**Comment by EdwardAngert** [comment]
Just to followup, I submitted FEAT-797 to have the platform trigger an email to key stakeholders when a site moves from Live to Sandbox.
