### ISSUE TITLE
Terminus Manual Doc Update: describe hide_git_mode_warning property

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#5891]
Re: [Terminus Manual](https://pantheon.io/docs//terminus/configuration)

Priority: Low

## Issue Description:
In the [Pantheon Community Slack](https://pantheon-community.slack.com/archives/C57J1MUEM/p1595900513445200?thread_ts=1590764602.239500&cid=C57J1MUEM), it was suggested that the Terminus Configuration page should document the `hide_git_mode_warning` property.

## Suggested Resolution
Add just that one property to the existing example, or maybe add a table of other possible values.

Someone would have to build a list from the source code to make the table; I don't think the Terminus properties are currently documented anywhere.

**Comment by carolyn-shannon** [comment]
Would be good to have a complete list of the properties as a reference along with the commands.

**Comment by EdwardAngert** [comment]
dropping this in as where I think we can find these properties for whomever picks this issue up
https://github.com/pantheon-systems/terminus/blob/master/src/Commands/Remote/SSHBaseCommand.php

**Comment by carolyn-shannon** [comment]
Also, the [ConfigDumpCommand](https://github.com/pantheon-systems/terminus/blob/master/src/Commands/Self/ConfigDumpCommand.php) command allows the user to see what config keys and values current settings.

**Comment by greg-1-anderson** [comment]
#5916 is actually wrong. 

`TERMINUS_HIDE_GIT_MODE_WARNING` is not a property to set in `.terminus/config.yml`. Instead, this is an environment variable that should be set in bash:

`export TERMINUS_HIDE_GIT_MODE_WARNING=1`

Sorry I didn't see the PR to comment on it before it was merged.

**Comment by greg-1-anderson** [comment]
Do we already document `hide_update_message`?

There actually are not a lot of other variables that would be useful to the end user. Some of nominal interest include:

- date_format
- monetary_locale

That's really it.

**Comment by alexfornuto** [comment]
@greg-1-anderson I tested when I made the PR, and just tested again. Setting `TERMINUS_HIDE_GIT_MODE_WARNING: 1` in `~/.terminus/config` _does_ work.

**Comment by greg-1-anderson** [comment]
Oh. Odd. `hide_git_mode_warning: true` is preferred for preferences in config.yml though.
