### ISSUE TITLE
WP Plugins - Known issues page -> Unyson Theme Framework

### ISSUE THREAD

**Issue by yuri-pochepko** [pantheon-systems/documentation#5909]
Re: WP Plugins - Known issues page -> Unyson Theme Framework https://pantheon.io/docs/plugins-known-issues#unyson-theme-framework

Priority: Low

## Issue Description

Typo in paths.

## Suggested Resolution

Please correct paths.

**Now**

Page builder:

    wp-content/plugins/framework/extensions/shortcodes/.gitignore
    wp-content/plugins/framework/extensions/shortcodes/extensions/page-builder/.gitignore

**Should be fixed as**

Page builder:

    wp-content/plugins/unyson/framework/extensions/shortcodes/.gitignore
    wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/.gitignore

**Comment by alexfornuto** [comment]
Thanks @yuri-pochepko!
