### ISSUE TITLE
wp-config-pantheon.php file introduced & support for WP_ENVIRONMENT_TYPE

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/documentation#5911]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php)

Priority: Medium

## Issue Description
https://github.com/pantheon-systems/WordPress/pull/250 refactors the pantheon-specific code in `wp-config.php` to its own file (`wp-config-pantheon.php`) included by wp-config in order to give us a place to make our changes without risking merge conflicts with customers' changes to `wp-config.php`.

The new wp-config file also introduces support for WP_ENVIRONMENT_TYPE [introduced in WordPress 5.5](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/).

## Suggested Resolution
- Update wp-config documentation to reflect this new file and warn against making changes in `wp-config-pantheon.php`.
- Document Pantheon's support for using wp_get_environment_type() based on environment (`development` for dev/multidevs, `staging` on test, `production` on live).

**Comment by EdwardAngert** [comment]
adding this issue to include in the PR: [#252](https://github.com/pantheon-systems/WordPress/issues/252)

**Comment by EdwardAngert** [comment]
@pwtyler @greg-1-anderson 
I was just going through some of our other docs and noticed that in [Best Practices for Maintaining Custom Upstreams](https://pantheon.io/docs/maintain-custom-upstream#test-and-release-pantheon-core-updates), we describe the steps to pull/test core updates.
Does the introduction of `wp-config-pantheon` affect that process?
