### ISSUE TITLE
"Configure WP_DEBUG in wp-config.php" recommends new wp_get_environment_type(), but function cannot be called yet

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/documentation#5922]
Re: [Environment-Specific Configuration for WordPress Sites](https://pantheon.io/docs/environment-specific-config)

Priority: High

## Issue Description
Documentation recommends using `wp_get_environment_type()` in wp-config.php in ["Configure WP_DEBUG in wp-config.php"](https://pantheon.io/docs/environment-specific-config#configure-wp_debug-in-wp-configphp), but that function has not been loaded yet yet, and will cause a fatal error.
```
if ( ! defined( 'WP_DEBUG' ) ) {
    define('WP_DEBUG', (wp_get_environment_type() == "development"));
}
```

## Suggested Resolution
Checking for the `WP_ENVIRONMENT_TYPE` ENV variable instead of using the function, or using the `PANTHEON_ENVIRONMENT` ENV variable.

**Comment by alexfornuto** [comment]
@greg-1-anderson are updates to core that would resolve this expected soon?

**Comment by greg-1-anderson** [comment]
Oh Applesauce. This probably will never be resolved. Fortunately, this suggestion was only made in the documentation, not committed to the WordPress upstream.

I would suggest going back to the old version of the documentation that set the environment up via PANTHEON_ENVIRONMENT.

**Comment by EdwardAngert** [comment]
@pwtyler and @greg-1-anderson thanks for catching and keeping us updated!
I'm getting a revert PR ready for this, and to confirm, if there is somewhere that users can use `wp_get_environment_type`, would you be able to give me a rundown of where they'd use it and how so I can get it back into the docs?

**Comment by greg-1-anderson** [comment]
`wp_get_environment_type()` can be used in plugins. We might want to update the pantheon-hud plugin to use this method. pantheon-hud could then disable any of its Pantheon-specific features when not on Pantheon, and be usable in other contexts. I didn't see any well-maintained environment-indicator-type plugins, could be good exposure / renown.

That's out of scope for this issue, though. As far as documenting `wp_get_environment_type()` is concerned, I would recommend just mentioning its utility in plugins, and point the user to the WordPress documentation of the feature. Maybe this blog: https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

**Comment by pwtyler** [comment]
wp_get_environment_type() can be used from a plugin, theme, or mu-plugin. This [pre-release post](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/) offers a good rundown— One example might be to turn off a prod-specific functionality (blocking emails, turning caching on or off) by environment— the example given in the linked post is:
``` php
switch ( wp_get_environment_type() ) {
    case 'development':
        do_nothing();
        break;
     
    case 'staging':
        do_staging_thing();
        break;
     
    default:
        do_production_thing();
        break;
}
```
