### ISSUE TITLE
Configuration Workflow for Drupal 8 Sites Doc Update 

### ISSUE THREAD

**Issue by tgillstar** [pantheon-systems/documentation#5965]
Re: [Configuration Workflow for Drupal 8 Sites](https://pantheon.io/docs/drupal-8-configuration-management)

Priority: Low

## Issue Description:
The configuration information in the 2nd paragraph of the https://pantheon.io/docs/drupal-8-configuration-management doc is out-dated since Drupal 8.8.0.

## Suggested Resolution

The correct information about the location of the config sync directory seems to be presented in the **_Warning_** block in the https://pantheon.io/docs/settings-php doc. 

Also, the information in the configuration info in the https://pantheon.io/docs/drupal-8-configuration-management#configure-and-relocate section of the doc should be reviewed for consistency as well.

**Comment by alexfornuto** [comment]
Todo:
 - Update config path
 - In settings-php, configure headers for config paths based on version
 - Remove video and replace with reference to https://pantheon.io/docs/guides/drupal8-commandline#managing-content-configuration-and-code-across-environments

**Comment by alexfornuto** [comment]
Thanks for reporting @tgillstar!
