### ISSUE TITLE
Links to Network Solutions Help Docs No Longer Work

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#5968]
Re: [Network Solutions Domain Configuration](https://pantheon.io/docs//network-solutions)

Priority: Low

## Issue Description:

This page links to a few pages on NetworkSolutions.com. These no longer work.

## Suggested Resolution

Looks like their Support Docs are now hosted on Web.com. I was able to find one of the corresponding pages here:

https://knowledge.web.com/subjects/article/KA-01100/en-us#NS

**Comment by alexfornuto** [comment]
While updating the docs link we can also test to see if they now support AAAA records without special privilege and email exchanges.

**Comment by alexfornuto** [comment]
See also #6009
