### ISSUE TITLE
Backups Tool Doc Update 

### ISSUE THREAD

**Issue by dflitner** [pantheon-systems/documentation#5980]
Re: [Backups Tool](https://pantheon.io/docs/backups)

Priority: Low

## Issue Description
https://pantheon.io/docs/backups#via-the-command-line section: the command `wget "wget https://storage.googleapis.com/gcs-pantheon-backups/..."` is incorrect.

## Suggested Resolution
The correct command is `wget "https://storage.googleapis.com/gcs-pantheon-backups/..."`

It might also be helpful to note that this doesn't work on Windows, even with wget installed.

**Comment by alexfornuto** [comment]
Thanks for letting us know @dflitner!

**Comment by alexfornuto** [comment]
I just tested in a VM and was able to download using wget, if the URL was wrapped in quotes.
