### ISSUE TITLE
Configuring wp-config.php Doc Update 

### ISSUE THREAD

**Issue by jdpantheon** [pantheon-systems/documentation#5985]
Re: [Configuring wp-config.php](https://pantheon.io/docs/wp-config-php)

Priority: Medium

## Issue Description:

ionCube (https://pantheon.io/docs/wp-config-php#how-do-i-enable-ioncube-decoder-support) support is limited to 7.1 at the moment. The verbage should be updated to specify users must use 7.1 if they need this package. They can verify that by comparing each PHP versions' info page.

## Suggested Resolution

Change blurb to:

"If you are using a licensed plugin that requires IonCube Decoder support, first ensure you are running PHP 7.1. Please note later PHP versions do not currently support ionCube."

**Comment by alexfornuto** [comment]
Thanks @jdpantheon! Continuing in #5986
