### ISSUE TITLE
Reading Pantheon Environment Configuration Doc Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5988]
Re: [Reading Pantheon Environment Configuration](https://pantheon.io/docs/read-environment-config)

Priority: Low

## Issue Description:
Explain the reason that we cannot set environment variables

## Suggested Resolution

**Comment by alexfornuto** [comment]
RE: FEAT-655

**Comment by joa-pan** [comment]
@EdwardAngert is this still relevant or true?

**Comment by EdwardAngert** [comment]
@joa-pan still relevant and true, but I'm going to close this one as stale and we're not really going to be able to act on it until FEAT-655
