### ISSUE TITLE
Network Solutions Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by EstenSesto** [pantheon-systems/documentation#5993]
Re: [Network Solutions Domain Configuration](https://pantheon.io/docs//network-solutions)

Priority: Low

## Issue Description
seems NetSol now offers AAAA settings

## Suggested Resolution

update help docs please!

**Comment by alexfornuto** [comment]
@EstenSesto Thanks for filing this issue! We've had alto of back-and-forth on AAAA records with NetSol. The last I heard, they were only available to certain customers on certain plains, and only through an email thread.

Is this no longer the case? Are `AAAA` records available directly through their DNS management interface?

**Comment by alexfornuto** [comment]
The discussions in our [forums](https://discuss.pantheon.io/t/network-solutions-aaaa-records/542/5) on this topic include this quote from NetSol:

>We currently only support IPv6 changes on the Server level, not the domain level. The information provided directs to add resource records for an IPV6 address on the domain level. Therefore all we provide is the glue record

In other words, they won't provide `AAAA` records for domains hosted elsewhere.

If this has changed, please let us know.
