### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by jleetaylor2020** [pantheon-systems/documentation#5998]
Re: [Terminus Manual](https://pantheon.io/docs//terminus/updates)

Priority: Low

## Issue Description:
We can see the latest version of terminus is 2.4.1 at: 
https://github.com/pantheon-systems/terminus/tree/2.4.1 

1) Visit section https://pantheon.io/docs/terminus/updates# and 
the doc states "Update to the Current Release 2.4.0"
Doc should read "Update to the Current Release 2.4.1"

2) Visit section https://pantheon.io/docs/terminus/updates#eol-timeline
EOL Timeline Chart should include 2.4.1 with the EOL Date

3) Visit section https://pantheon.io/docs/terminus/updates#changelog
Changelog should include updates for 2.4.1

## Suggested Resolution
1) Doc should read "Update to the Current Release 2.4.1"
2) Changelog should include 2.4.1
3) Add 2.4.1 with the EOL Date to the timeline chart

**Comment by alexfornuto** [comment]
@jleetaylor2020 Thanks for letting us know! Our scripts _should_ update everything but the EOL table automatically. I'll have to look at our CI processes in depth next week. In the meantime, I've pushed a PR to fix.
