### ISSUE TITLE
Vanity Domains: Effects and Considerations - Images with CNAME

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/documentation#6008]
Re: [Vanity Domains: Effects and Considerations](https://pantheon.io/docs/vanity-domains#effects-and-considerations)

Priority: Low

## Issue Description:
Images with CNAME records

## Suggested Resolution
Images with A/AAAA names if necessary

**Comment by alexfornuto** [comment]
To clarify, Thomas is saying that this page has screenshots that need to be updated because they show ups giving CNAME not A/AAAA values.
