### ISSUE TITLE
November 2020 Changelog

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6021]
For updates occurring in October, 2020. 
When entering product updates, please use the following format:

```
### Subject (i.e WP-CLI Upgrades)
Short description, like: WP-Cl has been upgraded to [1.5.0](https://make.wordpress.org/cli/2018/01/31/version-1-5-0-released/).

Priority: Med

**Comment by greg-1-anderson** [comment]
### Drupal 8.9.7

Drupal 8.9.7, a security release, has been deployed to the platform.

**Comment by greg-1-anderson** [comment]
I made a typo above. Drupal 8.9.7 is a patch release. Sorry.

Need to get that typo-free bot hooked up again. :p

**Comment by alexfornuto** [comment]
:facepalm:
