### ISSUE TITLE
Autoptimize Enable 404 fallbacks setting does not work

### ISSUE THREAD

**Issue by marfillaster** [pantheon-systems/documentation#6022]
Re: [WordPress Plugins and Themes with Known Issues - Autoptimize](https://pantheon.io/docs/plugins-known-issues#autoptimize)

Priority: Low

## Issue Description

**Enable 404 fallbacks** setting requires write access and specific location directive not configured in platform's Nginx configuration. Platform does not provide support for custom configuration.

## Suggested Resolution

Uncheck **Enable 404 fallbacks** in Autoptimize settings page.

More details about the setting in [FAQ - What does “enable 404 fallbacks” do? Why would I need this?](https://wordpress.org/plugins/autoptimize/#%0Awhat%20does%20%E2%80%9Cenable%20404%20fallbacks%E2%80%9D%20do%3F%20why%20would%20i%20need%20this%3F%0A)

**Comment by EdwardAngert** [comment]
Raising my hand for this one to see if we can link to elsewhere in our docs where we discuss redirecting 404s - hoping we can link to that instead of just "not going to work"
- https://pantheon.io/docs/advanced-redirects#redirect-files
