### ISSUE TITLE
Lando doc -> notes about Drupal

### ISSUE THREAD

**Issue by yuri-pochepko** [pantheon-systems/documentation#6030]
Re: https://pantheon.io/docs/guides/lando

Priority: Low

## Issue Description
Hi! 

Here in Support we had some customers were asking for a help with having lando + drupal site hosted on pantheon. Our current doc is an article written by Alex Vasquez. Article is great, but some structure changes could improve customer experience. 
Current doc structure:
![изображение](https://user-images.githubusercontent.com/63350179/95082108-3d61c700-0723-11eb-8a4d-c3f0afd2ae2c.png)
So some customers could be frustrated. There are no notes about Drupal at all, so sometimes they ask/think that's is not possible. If they check Lando docs https://docs.lando.dev/config/pantheon.html#getting-started they could also see wp-only examples.

## Suggested Resolution

We just need a note/section/faq that gives an info, that installing Drupal on Lando using Pantheon recipe is also possible and pretty straightforward -> the same steps as stated here: https://pantheon.io/docs/guides/lando#installing-wordpress-using-the-pantheon-recipe 

Just make sure that:
**Pantheon hosted site ready to go. You can either use an existing Pantheon site or spin up a new one**

is a Drupal site.

Sometimes customer wants a full-guided article, but currently I've found only a video from Lando here -> https://www.youtube.com/watch?v=lgaUqMy5a6A

Any thoughts?
thanks!

**Comment by alexfornuto** [comment]
ToDo:

 - Update title and path to reflect WP specificity.
 - Add CTA to top pointing to Localdev as solution for WP and Drupal.
