### ISSUE TITLE
Using SendGrid To Deliver Email Doc Update 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6050]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs//guides/sendgrid)

Priority: Low

## Issue Description:
Users getting concerned about the recommended sengrid plugin being outdated for 3 yrs
<img width="949" alt="Screen Shot 2020-10-12 at 7 10 52 AM" src="https://user-images.githubusercontent.com/5098765/95692681-14c55a00-0c5a-11eb-952e-da7bc0fea66d.png">
seems the author has abandoned this plugin
https://github.com/sendgrid/wordpress/issues/87
https://wordpress.org/support/topic/still-supported-or-dead/

## Suggested Resolution
Maybe putting a note that it still works and maybe they can ignore those warning and flags

**Comment by alexfornuto** [comment]
To be determined:

 - What other methods people using to integrate SendGrid with WP?
 - Is [this information](https://sendgrid.com/docs/for-developers/sending-email/wordpress-faq/) on using  WP Better Emails plugin relevant?

SME input requested.

**Comment by alexfornuto** [comment]
More data points to consider:

 - [3rd party Sendgrid plugin](https://wordpress.org/plugins/wp-sendgrid-mailer/#description)
 - Sendgrid's most recent reviews and feedback has been largely negative; it appears that the service may be mostly abandoned by its new parent company. If so, we should consider documenting another email service instead.

**Comment by alexfornuto** [comment]
I've logged a support ticket with SendGrid asking them to clarify the official best practice for configuring SendGrid on WP.

**Comment by alexfornuto** [comment]
I received no reply from Sendgrid, but found WP Mail SMTP to be easy to use for SendGrid services, will update the docs accordingly.
