### ISSUE TITLE
Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by nullvariable** [pantheon-systems/documentation#6054]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate)

Priority: Low

## Suggested Resolution
Per thread in community slack: https://pantheon-community.slack.com/archives/CT8MC5Y0K/p1602368288044500?thread_ts=1602274347.040900&cid=CT8MC5Y0K

Some users may encounter an error `Index column size too large.` when trying to migrate from WPEngine. One solution for this is to modify the database export file from WPEngine as follows:
open in a text editor and search replace `varchar(255)` with `varchar(191)`.

You can also run this sed command on a *nx command line:
```
sed 's/varchar(255)/varchar(191)/g' [ORIGINAL DB FILE] > [NEW FILE NAME]
```
then import the new file name to Pantheon

**Comment by marfillaster** [comment]
There might be some risk of truncation if naive global search and replace is done. I'd go for inspecting every matching column definition and setting just the length in the key part where the column is used as index.

Example:
```sql
CREATE TABLE person (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    KEY idx_name (name)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE person (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    KEY idx_name (name(191)) -- <- index prefix max 191
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

**Comment by rachelwhitton** [comment]
Related: https://github.com/pantheon-systems/documentation/pull/6053 
cc @lauren-kelly

**Comment by alexfornuto** [comment]
Will reach out to @marfillaster to help break down his solution, which seems less fraught with danger vs regex in a db.

If all else fails, we can at least note the issue in the doc.

**Comment by marfillaster** [comment]
My vote is to add a note. This is not platform specific. It's somehow documented already in https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html

<img width="1157" alt="Screen Shot 2020-10-16 at 8 57 55 PM" src="https://user-images.githubusercontent.com/121793/96261128-98809d00-0ff2-11eb-99d8-b307d30f951b.png">

**Comment by spheromak** [comment]
Yea +1 on pointing to official docs. We shouldn’t be recommending blind regex on db dumps.
