### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update 

### ISSUE THREAD

**Issue by nullvariable** [pantheon-systems/documentation#6062]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis)

Priority: Low

## Issue Description:
Would suggest incorporating information contained in this blog post regarding cache groups ([WP Redis v0.3.0: Cache Groups](https://pantheon.io/blog/wp-redis-v030-cache-groups)) as a recommendation for most sites.
Additionally users should add a value to the `WP_REDIS_DEFAULT_EXPIRE_SECONDS` constant if they use that method. 

Also sites with large amounts of traffic encountering redis issues (example error: `'RedisException' with message 'OOM command not allowed when used memory > 'maxmemory'` ) are likely doing so because they're not expiring redis cache items fast enough, so setting a time for the default, or lowering that time may decrease or prevent these errors.

## Suggested Resolution
Expand docs to cover above, possibly troubleshooting section

related slack thread: https://pantheon.slack.com/archives/C3SQTECS1/p1602763691263900

**Comment by marfillaster** [comment]
Not sure if the setting is relevant for `allkeys-lru` eviction policy which the platform's Redis is configured to. https://redis.io/topics/lru-cache#:~:text=When%20the%20specified%20amount%20of,time%20new%20data%20is%20added.
