### ISSUE TITLE
Caching: Advanced Topics Doc Update 

### ISSUE THREAD

**Issue by nullvariable** [pantheon-systems/documentation#6079]
Re: [Caching: Advanced Topics](https://pantheon.io/docs/caching-advanced-topics)

Priority: Low

## Issue Description:
Not sure where to best add it, but we don't seem to note in the docs that cookies are stripped from static assets. That means that if you rely on the 404 handler in WordPress or Drupal to generate a response that is a 200 for a file that might be dynamic, WordPress/Drupal will not see any cookies as they're stripped at the GCDN layer. This is a rare edge case, but I've run into a couple cases where this was a challenge recently and seems like a callout on this page might be useful.

## Suggested Resolution
Add a callout or note about the above information. I can pull a full list of file types this applies to if it makes senses to include that.

**Comment by alexfornuto** [comment]
Additional context in [Community Slack Thread](https://pantheon-community.slack.com/archives/C2GJ3JG7Q/p1603466184246200) - I think some combo of Platform Considerations and [Working with Cookies on Pantheon](https://pantheon.io/docs/cookies) should also reference this.
