### ISSUE TITLE
MySQL Events and Triggers are not supported

### ISSUE THREAD

**Issue by marfillaster** [pantheon-systems/documentation#6087]
Re: [Platform Considerations](https://pantheon.io/docs/platform-considerations)

Priority: Low

## Issue Description:

Due to lack of persistence guarantee during migration and similar to Stored Procedures, [Events](https://dev.mysql.com/doc/refman/8.0/en/events-overview.html) and [Triggers](https://dev.mysql.com/doc/refman/8.0/en/triggers.html) are not supported in the platform

## Suggested Resolution

Expand **Database Stored Procedures** section to include Triggers and Events to the list of MySQL features not supported in the platform. Propose CMS cron feature as alternative to MySQL Events.

**Comment by alexfornuto** [comment]
@marfillaster please add additional context to this issue, as it's not actionable currently.

**Comment by marfillaster** [comment]
> @marfillaster please add additional context to this issue, as it's not actionable currently.

Issue description updated.
