### ISSUE TITLE
Advanced Redirects and Restrictions Doc Update 

### ISSUE THREAD

**Issue by mpaladino** [pantheon-systems/documentation#6102]
Re: [Advanced Redirects and Restrictions](https://pantheon.io/docs/advanced-redirects)

Priority: Medium

## Issue Description:
Since Pantheon leverages Nginx for HTTP/HTTPS, we often find ourselves wondering how we can recreate our Apache mod_redirects and mod_rewrites on Pantheon. 

## Suggested Resolution
One way to do this, is to replicate those features in PHP. I have some code I use to handle these in this repository:

https://github.com/mpaladino/pantheon-htaccess-rewrites

In this repository, you will find pantheon_rewrites.php, a file which contains code to mimic Apache's mod_redirect and mod_rewrite capabilities on Pantheon. This file gets included at the very beginning of your Drupal settings.php or Wordpress wp-config.php files, and will perform rewrites and redirects, prior to full Wordpress or Drupal bootstrap.

This has been tested and is currently in use by USC, Univ of Washington, UC Davis and several of our partners.

We might want to consider adding this to our Advanced Redirects page and also indicate that my code will handle rewrites too.

**Comment by alexfornuto** [comment]
Thanks @mpaladino! I'm wondering if you would consider making this a Pantheon Org repo and maintaining it there, and/or if @sugaroverflow is interested in including it in her Open-Source projects.

**Comment by mpaladino** [comment]
@alexfornuto Sure. I have no preference really. Does it have to be in the pantheon-systems org or can I put it in say... https://github.com/Pantheon-SE/?

I'm happy to be the maintainer for this.

**Comment by alexfornuto** [comment]
@mpaladino I don't know... @sugaroverflow might have thought about that.

**Comment by alexfornuto** [comment]
womp womp.

**Comment by mpaladino** [comment]
> 

https://github.com/Pantheon-SE/pantheon-htaccess-rewrites

**Comment by sugaroverflow** [comment]
oh hai, sorry I totally missed this notification years ago 😂
