### ISSUE TITLE
Choosing Your Start State Doc Update 

### ISSUE THREAD

**Issue by ksenour** [pantheon-systems/documentation#6107]
Re: [Choosing Your Start State](https://pantheon.io/docs/start-state)

Priority: Low

## Issue Description:
By specifically calling out that our D7 upstream is extended with Pressflow under the first heading, and not addressing D8 - we imply that the D8 upstream isn't also extended with Pressflow.

> We base our Drupal 7 repository on the canonical source from drupal.org, and then extend it with Pressflow modifications and additional features to take advantage of the Pantheon runtime environment

## Suggested Resolution
Either update to say Drupal 7 and 8 repositories, or make it generic with "all Drupal Upstreams" so that we cover D9 as well.

**Comment by alexfornuto** [comment]
I believe that pressflow settings are only a thing on D7, but I'd ask @greg-1-anderson to confirm.

**Comment by alexfornuto** [comment]
Just confirmed, it isn't.
