### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by philoSurfer** [pantheon-systems/documentation#6109]
Re: [Terminus Manual](https://pantheon.io/docs//terminus/install)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Under section **Standalone Terminus PHAR** the curl command fails on macOS. Potentially a ZSH issue only, see error.

*Command that fails:**
`curl -L https://github.com/pantheon-systems/terminus/releases/download/$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m{"tag_name": "\K.*?(?=")}g')/terminus.phar --output terminus`

**Error**
`zsh: parse error near `)'`

## Suggested Resolution
Use the install command in the `README.md` for the terminus repo instead

`curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install`

**Comment by alexfornuto** [comment]
Hi @philoSurfer! We documented the cause of this issue and a solution [in the doc](https://pantheon.io/docs/terminus/install#terminus-phar-installer-parse-error-near-). Did you attempt this resolution?

**Comment by philoSurfer** [comment]
Yes works as expected. 
Sorry ZSH n00b here. Thank you for adding an addendum.

**Comment by alexfornuto** [comment]
No worries! We added that because we hit that issue ourselves and scratched our heads for longer than I'd care to admit.

Please let us know if you encounter any other issues with our docs.
