### ISSUE TITLE
Get Support Doc Update add Sales and Billing office hours

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6120]
Re: [Get Support](https://pantheon.io/docs/support)

Priority: Low

## Issue Description:
We don't have any documentation of the office hours of sales and billing

## Suggested Resolution
It would be nice if we have a section here that we can refer customers that Billing and Sales only works around 9AM-5PM PST Mon-Fri non-holiday

**Comment by carolyn-shannon** [comment]
Consulting with CSE & Billing to confirm this should be included in the scope of the support docs page.
