### ISSUE TITLE
Introduction to Custom Upstreams Doc Update 

### ISSUE THREAD

**Issue by philoSurfer** [pantheon-systems/documentation#6135]
Re: [Introduction to Custom Upstreams](https://pantheon.io/docs/custom-upstream)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Need to expand the Git-based repository support definition here. 
Eg. Azure Repos are supported based on the fundamental requirements for creating a Custom Upstream
## Suggested Resolution

Recommend calling out a bullet point list of what allows an external Git provider compatible with Pantheon, and keep a running list of known supported providers outside of just the GitHub, GitLab, Bitbucket list.

**Comment by jrastaban** [comment]
Thanks for filing this @philoSurfer 

I think the path forward is to broaden the "GitLab" language to something that encapsulates any git based repo. 

Both on this page and in the tabs on this page: https://pantheon.io/docs/create-custom-upstream/ we mention supporting 3 git methods: GitHub, Bitbucket or GitLab.

We really support 2 GitHub & Bitbucket out of the box and then a large range of other git based providers using a manual setup. The workflow for all these other Git providers is very similar to what we have now for GitLab. It involves creating a user account that gives pantheon access to it, and then contacting support to set it up. The URL validator for creating custom upsteams only accepts GitHub, Bitbucket but we can use just about anything using Git, it just needs a person to validate it.
