### ISSUE TITLE
Broken anchor link "Before You Begin" in step one.

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#6136]
Re: [Drupal Commerce on Drupal 8](https://pantheon.io/docs//guides/drupal-8-commerce)

Priority: Low

## Issue Description:
Broken anchor link.

On step one "Follow the Before You Begin section" the [Before You Begin](https://pantheon.io/docs/guides/build-tools/#before-you-begin) anchor link is broken.
![image](https://user-images.githubusercontent.com/4403290/100277796-b69cce00-2f9e-11eb-84de-0e2708eccebf.png)

## Suggested Resolution

Update the anchor link and point it to Create a New Project > Prerequisites

https://pantheon.io/docs/guides/build-tools/create-project/#prerequisites

**Comment by alexfornuto** [comment]
Thanks @umandalroald!
