### ISSUE TITLE
terminus backup:restore and --file parameter - Add a note that backup:restore can only restore pantheon environment backup

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#6137]
Re: [Terminus Manual](https://pantheon.io/docs//terminus)

Priority: Low

## Issue Description:

The --file parameter sometimes can be confusing that it can also accepts files from a local machine. Terminus backup:restore can only restore Pantheon environment backup.

## Suggested Resolution

Maybe update the backup:restore description too.

Restores a specific backup or the latest backup from the Pantheon environment.

And update the --file parameter description from `[filename.tgz] Name of backup file` to `[filename.tgz] Name of Pantheon environment backup file`

**Comment by mcohen-impact** [comment]
Or maybe change description to: 
[filename.tgz] - Name of Pantheon environment backup file.  Use the terminus backup:list command for more details on backup filenames

**Comment by alexfornuto** [comment]
@umandalroald Are you referring to [this page](https://pantheon.io/docs/terminus/commands/backup-restore) specifically? If so, we can solve short-term with a partial file clarifying, and long term with a PR to [Terminus](https://github.com/pantheon-systems/terminus) clarifying the built-in help content.

**Comment by mcohen-impact** [comment]
@alexfornuto this is based on a ticket that I submitted to support asking how to restore a specific backup file that I was attempting to reference from my local machine or server, and then was informed that that's not how it works :).  So yes, I was suggesting a clarification of how the --file directive works

**Comment by alexfornuto** [comment]
Thanks for the additional context! I'll have a PR shortly with additional context added to the page.
