### ISSUE TITLE
Investigate and Remedy Traffic Events Doc Update 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#6141]
Re: [Investigate and Remedy Traffic Events](https://pantheon.io/docs/optimize-site-traffic)

Priority: Low

## Issue Description:
In the section, ["Use a Drupal Module or WordPress Plugin to Block IPs"](https://pantheon.io/docs/optimize-site-traffic#use-a-drupal-module-or-wordpress-plugin-to-block-ips) one of the suggested WordPress plugins [IP Ban](https://wordpress.org/plugins/simple-ip-ban/) has not been tested with the last 3 major versions of WordPress. [**screenshot**](https://i.imgur.com/JAL5SYR.png)

## Suggested Resolution

[IP Blacklist Cloud](https://wordpress.org/plugins/ip-blacklist-cloud) seems to work well with the platform without too much fuss and is actively maintained.

**Comment by alexfornuto** [comment]
Thanks @CFin86!
