### ISSUE TITLE
Contributing to Pantheon Docs Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#6143]
Re: [Contributing to Pantheon Docs](https://pantheon.io/docs/contribute)

Priority: Medium

## Issue Description:
I'd like to include some new material here on contributing back to Drupal and to WordPress using Pantheon as the tooling. 

## Suggested Resolution
* Add a section for Drupal contributions
* Add a section for WP contributions

AmyJune Hineline, @carolyn-shannon & I should be able to collaborate on this one.

**Comment by AmyJuneH** [comment]
Great. Let me know how/when to help.
