### ISSUE TITLE
Accessing MySQL Databases Doc Update 

### ISSUE THREAD

**Issue by josephr5000** [pantheon-systems/documentation#6148]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access)

Priority: Medium

## Issue Description:
Your page doesn't answer this question which I have bumped into numerous times:  "Can I create a readonly database user?"

Such a user would be helpful as a way to more safely expose access to our data to SQL clients (like the ones you mention on this page, by the way!) without risk that they would make modifications.

## Suggested Resolution
Add a FAQ addressing this question and providing an answer.

An even better fix would be to provide a solution (a readonly user) but until that can be done an answer would be helpful.

**Comment by alexfornuto** [comment]
Thanks for the issue @josephr5000! I've tried to answer your question as an update to the docs in #6161. I hope to get some additional review and/or input from our CSE team over there.
