### ISSUE TITLE
Terminus syntax wrong on custom upstream page

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#615]
https://pantheon.io/docs/articles/organizations/adding-a-custom-upstream/

Step 3:

current command:
`terminus sites create upstream-test`

should be:
`terminus sites create --name=upstream-test`

Also, because others have use the name `upstream-test`, the user will get an error asking for an alternate site name if they literally use `upstream-test` in their setup.  Should we clarify the naming of the test site?
@nataliejeremy @rachelwhitton  Thoughts?

**Comment by nataliejeremy** [comment]
@ttrowell Thanks for finding that. Yes, please clarify it so it reduces errors/confusion.
