### ISSUE TITLE
Recommend Deploy Tokens to authenticate with GitLab repositories

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#6155]
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream)

Priority: Low

## Issue Description:
Currently we're recommending user issue a Personal Access token with full API access. There are a few issues with this:

1. The auth token is then assigned to a specific user, which means if there was an organization change or that user left, that can cause future issues.
2. Full API access is overkill and generally just a bad practice and should adhere to a least-privilege access policy.

## Suggested Resolution
Instead, we should recommend creating a Deploy Token that is associated with the repository itself and not any specific user.

1. Create a deploy token which is only associated with the repo, this is usually reserved for CI builds and external servers.
2. No longer relies on an auth token related to a user.
3. Only require read-only repository access.

**Comment by alexfornuto** [comment]
Neat! Deploy tokens are under `/user|org/reponame/settings/keys` on GitHub. @kyletaylored do you know if BitBucket / GitLab have similar token options? If not, whoever picks this up will search for them.

**Comment by kyletaylored** [comment]
Yep! I just set up a Custom Upstream using Deploy Tokens on Gitlab, which are located at:

```https://gitlab.com/<user|org>/<reponame>/-/settings/repository```

Looks like Bitbucket still uses personal access tokens, will look more into that.

**Comment by alexfornuto** [comment]
Will work on this after #6163 is merged, to avoid merge conflicts (lots of markdown linting in that one).

**Comment by alexfornuto** [comment]
Additionally, before continuing we should test this method, and update internal procedure docs, which currently are written with a required username in mind.

**Comment by kyletaylored** [comment]
A customer mentioned this to me today, which seems like Bitbucket's similar alternative to repository tokens, but it's still assigned to the user.

> **App Passwords**
> App passwords are substitute passwords for a user account which you can use for scripts and integrating tools to avoid putting your real password into configuration files.

https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/

**Comment by alexfornuto** [comment]
> A customer mentioned this to me today, which seems like Bitbucket's similar alternative to repository tokens, but it's still assigned to the user.
> 
> > **App Passwords**
> > App passwords are substitute passwords for a user account which you can use for scripts and integrating tools to avoid putting your real password into configuration files.
> 
> https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/

Yup, that's what the current documentation covers. I just tried GitHub and BitBucket, and both only support key pairs for repo-associated authentication. Moving on to GitLab now.
