### ISSUE TITLE
Installing Redis on Drupal or WordPress Doc Update 

### ISSUE THREAD

**Issue by jleetaylor2020** [pantheon-systems/documentation#6164]
Re: [Installing Redis on Drupal or WordPress](https://pantheon.io/docs/redis)

Priority: Low

## Issue Description: 
I see possible outdated paid plans referenced under header: Frequently Asked Question in need of reviewing or revision

## Suggested Resolution
Please review with team re: active or inactive plan sku and please remove any legacy paid plans that are no longer available. Under header: Frequently Asked Questions

**Comment by alexfornuto** [comment]
Thanks @jleetaylor2020! We're already on it in the referenced PR.
