### ISSUE TITLE
Configuring Settings.php Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#6169]
Re: [Configuring Settings.php](https://pantheon.io/docs/settings-php)

Priority: Low

## Issue Description:

Page says IonCube is available on "PHP 7.1 or later". However, it seems to be only available on PHP 7.1 and not later versions.

## Suggested Resolution

Remove "or later" is probably easiest.

**Comment by alexfornuto** [comment]
Aligns with #5986
