### ISSUE TITLE
Generate and Add SSH Keys Doc Update 

### ISSUE THREAD

**Issue by chefatef** [pantheon-systems/documentation#6177]
Re: [Generate and Add SSH Keys](https://pantheon.io/docs/ssh-keys)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by alexfornuto** [comment]
Hi @chefatef, did you want to report an issue with this page?

**Comment by alexfornuto** [comment]
I'm closing this issue since it's empty, but feel free to update us with more (any) details to have it re-opened.
