### ISSUE TITLE
Integrated Composer Doc Update - Pantheon only supports Composer 2 

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#6178]
Re: [Integrated Composer](https://pantheon.io/docs/integrated-composer)

Priority: High

## Issue Description:

For Integrated Composer support, Pantheon only supports Composer 2, and not all packages or modules are Composer 2 ready. When a customer attempts to use IC with an unsupported package, they will get a build error that says contact support and only support can see the actual workflow log that reports the Composer 2 error.

## Suggested Resolution

We need to add to the FAQ that Pantheon only supports Composer 2 (for performance and next gen capabilities) and customers should validate locally first whether their site is Composer 2 compatible.

[Drupal.org: Preparing your site for Composer 2](https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2)

**Comment by EdwardAngert** [comment]
thanks, @kyletaylored! I have some work going in with #6145 and I'll include info there that will close this issue
keeping it open as a reminder for myself

**Comment by EdwardAngert** [comment]
PRed #6248 to get it into the docs faster
