### ISSUE TITLE
WordPress Plugins and Themes with Known Issues Doc Update: add Jetpack and/or blocked xmlrpc.php section

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/documentation#6185]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues)

Priority: Low

## Issue Description:
Jetpack (one of the most popular WP plugins) suddenly stopped working on my WordPress blog. I tracked it down to Pantheon blocking requests to xmlrpc.php ([ref](https://pantheon.io/docs/wordpress-best-practices#avoid-xml-rpc-attacks)), which Jetpack uses to connect to WordPress.com. As it is, Jetpack will not work without making an edit to your `pantheon.yml` file.

## Suggested Resolution
Pantheon added the xmlrpc.php file to the default protected paths ([ref](https://github.com/pantheon-systems/WordPress/commit/80b2a39c43db6b17e5bda717da1108958be7a5d4)). The solution is to disable the defaults ([ref](https://pantheon.io/docs/pantheon-yml#protected-web-paths-override)) and re-set the ones you want ([ref](https://pantheon.io/docs/pantheon-yml#protected-web-paths)) (probably `/private` and `/wp-content/uploads/private`). The end result should look like this:
```
protected_web_paths_override: true
protected_web_paths:
  - /private
  - /wp-content/uploads/private
  ```

I confirmed that this fixed the connection issue on my site.

We may also want to go back and update https://pantheon.io/docs/wordpress-best-practices#avoid-xml-rpc-attacks to include a link to what to do if this broke something or how to undo the block.

**Comment by carolyn-shannon** [comment]
Partially duplicated by https://github.com/pantheon-systems/documentation/pull/6184, but this also needs:
- addition to xml-rpc-attacks doc as above
- caution in https://pantheon.io/docs/traffic-limits around re-enabling XMLRPC causing additional traffic.

**Comment by carolyn-shannon** [comment]
Waiting for additional clarification around whether it's a good idea to encourage folks to re-enable this, and whether this will cause traffic spikes.
