### ISSUE TITLE
Accessing MySQL Databases Doc Update 

### ISSUE THREAD

**Issue by careydayrit** [pantheon-systems/documentation#6189]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/mysql-access)

Priority: Low/Medium/High Medium

## Issue Description:
The MySQL binlogs cannot be accessed in the sub folder data since there is no sub folder.  I've tried accessing the site via sftp and there is no sub folder.  

https://pantheon.io/docs/mysql-access#how-can-i-access-mysql-binary-logs

## Suggested Resolution
Remove **How can I access MySQL binary logs?**

https://pantheon.io/docs/mysql-access#how-can-i-access-mysql-binary-logs

**Comment by alexfornuto** [comment]
Thanks @careydayrit! We're going to confirm with @pantheon-systems/product-management why these bin files are no longer available. We'll also need to update [Logs](https://pantheon.io/docs/logs#available-logs) similarly.

**Comment by sarahg** [comment]
Binlogs are still available via SFTP. Here's an example: https://gist.github.com/sarahg/b175025fea4867660c3be1d004c30e2c (connect via SFTP, cd to `data`, download the desired binlog file).

Maybe the directions need to be clearer? They're OK to me but I wrote them 🙃
