### ISSUE TITLE
Create documentation on using standard git workflows on pantheon

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#619]
This should be for the various use cases such as when the site has multidev or not. Should also account for a single developer or multiple. 
- [ ] Centralized - https://www.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow
- [ ] Feature Branching https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
- [ ] Forking  https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow (multidev)

Connects to #569

**Comment by bmackinney** [comment]
@timani I think this is a dup of #569. If you agree, please move your recommendation there. If not, re-open.
