### ISSUE TITLE
[BUGS-3538] Search API Solr 1.7 breaks new sites and multidevs

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#6191]
Re: [Enabling Solr on Drupal 8](https://pantheon.io/docs/solr-drupal-8)

Priority: ~Medium~ High

## Issue Description:
The latest update of Search API Solr (1.7, released on 12/20) breaks on new sites or multidev instances. It is specifically related to the schema.xml changes, and results in a 400 error when initializing the Solr service.

## Suggested Resolution
Instead of the general `8.x-1.x` branch of Search API Solr, it should be pinned to 1.6 instead.

```
composer require drupal/search_api_solr:~1.6
```

**Comment by alexfornuto** [comment]
We'll need to confirm the [semantic versioning[(https://getcomposer.org/doc/articles/versions.md#tilde-version-range-) shorthand, it looks like `~1.6` will go up to `1.9`
