### ISSUE TITLE
Advanced Redirects and Restrictions Doc Update single redirect hop

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6192]
Re: [Advanced Redirects and Restrictions](https://pantheon.io/docs/advanced-redirects)

Priority: Low

## Issue Description:
When using primary domain from the platform will result to 2 redirect hops eg:

http://example.com -> https://example.com -> https://www.example.com

Users optimizing their site would want to have a single redirect hop for this

Was raised in BUGS-3223 and https://github.com/pantheon-systems/documentation/issues/5738

If this cannot be addressed from the platform level, might be worth putting in docs to have PHP level alternative way to solve this

## Suggested Resolution

If we can document something like:

1) Adding this example code to do a single hop redirect

```
if (isset($_ENV['PANTHEON_ENVIRONMENT']) && ($_ENV['PANTHEON_ENVIRONMENT'] === 'live') && (php_sapi_name() != "cli")) {
  if (in_array($_SERVER['HTTP_HOST'], array(
    'example.com',
  ))) {
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://www.example.com'. $_SERVER['REQUEST_URI']);

    // Name transaction "redirect" in New Relic for improved reporting (optional).
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    exit();
  }
}

```

2) Setting primary domain to none
3) Make sure they're using transitional parameter for enforce_https in the pantheon.yml

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! We're gonna try to push BUGS-3223 before documenting this.

**Comment by alexfornuto** [comment]
BUGS-3223 has been resolved, redirects to the Primary Domain are now 1 hop.
