### ISSUE TITLE
Private Paths for Files and Code Doc Update 

### ISSUE THREAD

**Issue by marji** [pantheon-systems/documentation#6198]
Re: [Private Paths for Files and Code](https://pantheon.io/docs/private-paths)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
limitation of file modes / permissions is not documented.

## Suggested Resolution
Document the current limitation for private files.
We have a module complaining about file permissions:

    User notice: Key file "file:///files/private/public.key" permissions are not correct,
    recommend changing to 600 or 660 instead of 770 in League\OAuth2\Server\CryptKey->__construct()
    (line 59 of /code/vendor/league/oauth2-server/src/CryptKey.php)

When attempted to change file permission from `770` to `660` via SFTP (`chmod 660`), the operation does NOT report any errors, but the file permission does not change.

Current documentation does not address the fact that the file mode/permissons are set by the system as default and are immutable.
People might spend time searching for this problem (like me) and open a support tickets (like me) - documenting this limitation would save time.

Thank you.

**Comment by alexfornuto** [comment]
Thanks @marji! We're going to add this information to the [Pantheon Filesystem](https://pantheon.io/docs/files#troubleshooting) and crosslink here.
