### ISSUE TITLE
Duplicate Content

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#620]
[Importing an Existing Drupal Site to Pantheon](https://pantheon.io/docs/articles/drupal/importing-an-existing-drupal-site-to-pantheon/) and [Importing an Existing Site to Pantheon](https://pantheon.io/docs/articles/sites/create/importing-an-existing-site/) are seen by Google as duplicate pages.

**Comment by rachelwhitton** [comment]
@nataliejeremy  - I'm thinking we can delete the Drupal specific doc and add terminus info to **Importing an Existing Site to Pantheon** 

Let me know what you think is best and I'll create a PR. Thanks!

**Comment by nataliejeremy** [comment]
@rachelwhitton Do you think we need to add the Drupal-specific info to the other one? Is there anything specific for WP?

**Comment by rachelwhitton** [comment]
@nataliejeremy on second thought.. what do you think of the following suggestions:


1. Revise [Importing an Existing Site to Pantheon](https://pantheon.io/docs/articles/sites/create/importing-an-existing-site/) so that it only goes through Dashboard/Terminus import steps. (At this stage the user has an archive already created - beginning of the doc can link to CMS specific docs on generating archives)

2. Create separate and CMS specific docs for preparing sites for exports.

- This means [Importing an Existing Drupal Site to Pantheon](https://pantheon.io/docs/articles/drupal/importing-an-existing-drupal-site-to-pantheon/) would be renamed to **Prepare Drupal Site Exports** or something similar - in addition to being revised so that only prep instructions are present. 

- We would have to draft a WP specific export doc where manual instructions are provided. Currently we only have export instructions via plugins (e.g. duplicator). 


Thoughts?

**Comment by rachelwhitton** [comment]
@bmackinney ^

**Comment by bmackinney** [comment]
Separate issues. Let's resolve the dup content and then add this suggestion to #415
