### ISSUE TITLE
CSS Bug: Introduction to Custom Upstreams

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#6200]
Re: [Introduction to Custom Upstreams](https://pantheon.io/docs/custom-upstream)

Priority: high

## Issue Description: 
There are CSS classes not being applied which misrepresents the levels discussed in the Workflow section. 
For example, currently the doc renders the first level like this: 

<img width="851" alt="Screen Shot 2021-01-12 at 3 15 06 PM" src="https://user-images.githubusercontent.com/10119525/104375462-056bdc00-54e9-11eb-91b3-6887aea7eb8b.png">

It should look more like this: 

<img width="846" alt="Screen Shot 2021-01-12 at 3 11 53 PM" src="https://user-images.githubusercontent.com/10119525/104375542-259b9b00-54e9-11eb-80ec-653777e12c5d.png">

## Suggested Resolution
Debug CSS so that these classes are applied:

```
.upstream-overview-outter {
  padding: 25px;
  border-radius: 5px;
  border: solid rgb(18, 124, 187) 2px;
  display: inline-flex;
}

.upstream-content-inner-icon {
    text-align: left;
    margin-left: 10px;
    display: block;
}
.upstream-content-inner-content {
  text-align: left;
  margin-left: 10px;
  display: block;
  width: 90%;
  margin-top:-10px;
}
.upstream-overview-outter-clear::after {
  content: url('/docs/assets/images/arrow.svg');
}
.upstream-overview-outter-clear {
  text-align: center;
}
.upstream {
  padding-left:10px;
  font-size:small;
}
.upstream li {
  line-height: 1.35;
  padding-bottom: 4px;
}
```

Note there are two instances of `content: url('/docs/assets/images/arrow.svg');` in main.css which may need to be adjusted to `content: url('/docs/images/arrow.svg');` One in the snippet above, and another that's not used in this doc (but is used in [another doc](https://pantheon.io/docs/create-custom-upstream)):

```
.upstreams-regular {
  content: url('/docs/assets/images/upstreams-regular.svg');
  display: inline-block;
  font-style: normal;
  font-weight: normal;
  line-height: 1.4; vertical-align: top; margin-right: 2px; margin-left: 3px; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
}
```

**Comment by alexfornuto** [comment]
Thanks for yet another excellently documented issue @rachelwhitton!
