### ISSUE TITLE
The Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by tgillstar** [pantheon-systems/documentation#6208]
Re: [The Site Dashboard](https://pantheon.io/docs/sites)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
There is no explanation about what the "Workflows" top navigation link is, what information it provides, that red font coloring means it failed, etc. 

In fact, there is no information currently in any of our docs about the Workflows history except in the Quicksilver doc: https://pantheon.io/docs/quicksilver#debugging-via-terminus as it pertains to viewing history via Terminus commands. 

## Suggested Resolution

Create an appropriate section on this doc that provides this information. It would probably be best to place it above the _Team_ and _Settings_ sections if you are going in visual order of the navigation.

**Comment by alexfornuto** [comment]
Thanks @tgillstar! I'll reach out to the appropriate team for internal documentation on the spec of the Workflows display first, so we know everything to cover.
