### ISSUE TITLE
Role-Based Permissions 

### ISSUE THREAD

**Issue by JQTNguyen** [pantheon-systems/documentation#6214]
**Re: [Role-Based Permissions & Change Management]**
https://pantheon.io/docs/change-management

Considering adding `Administrator` to the `User in Charge / Owner` heading for the table that appears at https://pantheon.io/docs/change-management#site-level-roles-and-permissions, and possibly removing `Owner`

<hr> 

Currently, this table does not make it clear what an Organization Administrator can expect to do at the Site Level.

Within the context of a Site owned by an Organization, there is no Owner; the Organization is the Owner.

For reference, in case any related changes should be made, a similar table appears in https://pantheon.io/docs/team-management.

**Comment by carolyn-shannon** [comment]
Edward to follow up w/BrianC on this.

**Comment by EdwardAngert** [comment]
@pantheon-systems/docs-admins let's add the `Org Admin` to the column, then compare the tables on change-management and team-management and if they're about the same, combine the two in a partial (and include the partial on both pages)
