### ISSUE TITLE
Pantheon Secure Integration Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#6217]
Re: [Pantheon Secure Integration](https://pantheon.io/docs/secure-integration)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
One customer read that this line "This is available for contract customers" means it is already available as part of their contract. 

## Suggested Resolution
Make more clear by specifying contract customers mean those who are not paying as "online" or just via credit cards (monthly).

**Comment by alexfornuto** [comment]
Thanks @carl-alberto! Lemme know how #6218 grabs ya.
