### ISSUE TITLE
Add docs for formatting commit messages

### ISSUE THREAD

**Issue by twfahey1** [pantheon-systems/documentation#6220]
Priority: Low

## Issue Description
We don't have any docs on formatting commit messages.

It's possible to format commit messages, e.g.

```**A bold header in my commit**```

It would be good to have reference for what sort of formatting language we're using, what's available to use, etc.

## Suggested Resolution

Add a docs page re: "Formatting commit messages"

**Comment by jordanafung** [comment]
FYI the template we use for MU is
```

**The Managed Updates Service deployed:**

**The following upstream updates applied:**
- upstream update 1
- upstream update 2

**The following plugins updates applied:**
- plugin 1
- plugin 2
```

**Comment by alexfornuto** [comment]
@twfahey1 thanks for the issue? Per the issue template, what page are you looking to see this documented into?

**Comment by alexfornuto** [comment]
Could be added to [Git](https://pantheon.io/docs/git#make-changes), possibly [SFTP](https://pantheon.io/docs/sftp#committing-sftp-changes), after testing if the Dashboard accepts markdown.

**Comment by EdwardAngert** [comment]
thanks, @twfahey1 and @jordanafung !
I just tried formatting a commit on one of my test sites, and I wasn't able to get any of the md to render. I tried making commits the way I normally would, through terminal, and via the dashboard.
Do you get rendered MD in the Dashboard when you make commits like the Managed Updates one? (fwiw, I pasted that into a commit too)

**Comment by EdwardAngert** [comment]
hi friends, I'm going to close this one since it doesn't seem to do the thing we thought it would - users _can_ format commits however they want, but it doesn't look like the Dashboard renders the commits in any way.
