### ISSUE TITLE
Custom Certificates on The Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by peter-pantheon** [pantheon-systems/documentation#6225]
Re: [Custom Certificates on The Pantheon Global CDN](https://pantheon.io/docs/custom-certificates)

Priority: High 
## Issue Description:
The description for Let's Encrypt certs is outdated. This document states the LE certs are shared. The LE certs are not shared. 

<img width="861" alt="Screen Shot 2021-01-27 at 4 47 28 PM" src="https://user-images.githubusercontent.com/18431024/106058658-903f0000-60bf-11eb-981d-5d3712abe99d.png">

## Suggested Resolution

Remove "shared" from these two mentions. Double-check how they really should be named today.

**Comment by alexfornuto** [comment]
Thanks @peter-pantheon! Looks like we missed this table in #5758 - I'm going to look into sharing the table from `/https` so that future updates are shared.

**Comment by alexfornuto** [comment]
Update rolled into #6173

**Comment by alexdicianu** [comment]
@alexfornuto yes, we no longer offer shared certs via Let's Encrypt. The certs are now issued per site-environment. For instance, all domains from a site's live env will be colocated on one or more certs (if the site has more than 100 domains which is the per-cert limit). The same goes for test, dev and any multidev.
