### ISSUE TITLE
Migrate Sites to Pantheon Doc Update - D9 update

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/documentation#6241]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate)

Priority: Medium (choose one, remove the other options)

## Issue Description:

I've started getting questions about D9 site migrations, so this issue is flagging this doc for an update once there is an established playbook for migration. As a note, I see on the tool that it does address D9 through a 'D8 or D9' migration, but I don't think this option works with the new Integrated Composer approach? 

See https://pantheon.slack.com/archives/C01155GMA3E/p1612468128034600 for background.

## Suggested Resolution
* Update screencaps to show new/latest D9-inclusive migration tooling
* Add any D9-specific playbook instructions

**Comment by EdwardAngert** [comment]
thanks, @joshualieb! I've got a PR I'm working on that addresses this issue, basically using the same steps @mpaladino outlined in Slack (pasting here)
hoping to have that ready to share this week 🤞 

1. spun up a D9 site,
2. checked it out to my laptop/lando env.
3. copied all the require statements out of the composer.json
4. added all the custom artifacts
5. committed and pushed back to pantheon
6. did a DB import
