### ISSUE TITLE
wp ban plugin known issue

### ISSUE THREAD

**Issue by nullvariable** [pantheon-systems/documentation#6247]
Re: WordPress Plugins with known issues

Priority: Low

## Issue Description
The WP Ban plugin should be added to the list
https://wordpress.org/plugins/wp-ban/
This plugin will ban traffic to uncached pages, but it uses a 200 status code when returning those pages which causes the platform to cache the banned message for future users.

**Comment by EdwardAngert** [comment]
thanks @nullvariable!
I saw the option to customize a ban message, but I didn't see anything in the options screenshots that makes it seem like it can be set to return a 400-level code instead. I'd love to provide a "solution" along with the issue, but it seems more like a "heads up, this won't do what you think it might do"
pr incoming

**Comment by nullvariable** [comment]
https://github.com/lesterchan/wp-ban/issues/10#issuecomment-777258522

the solution I would recommend is making a PR upstream or waiting for the plugin author to offer additional options

**Comment by nullvariable** [comment]
for now what you've got there warning folks that the plugin may end up being cached and telling all visitors they're banned is all that I'd recommend from our side
