### ISSUE TITLE
Can not drop current database and WordPress site 

### ISSUE THREAD

**Issue by Sparks2Fly** [pantheon-systems/documentation#6255]
I need to recreate the current site.   https://dev-setctest.pantheonsite.io
How do I drop the database and recreate this site?

**Comment by jocastaneda** [comment]
Hi there!

This Github repo is for the documentation that resides in https://pantheon.io/docs so if there is an issue, please do let us know how we can improve on that. If you are encountering issues with the site we do ask that you please open a chat from the Support tab of the site.

**Comment by alexfornuto** [comment]
Hi! It sounds like you need support, which you can reach as indicated by @jocastaneda, one of our Customer Success Engineers. See [Get Support](https://pantheon.io/docs/support) for more information.

This repository is for the public Pantheon docs, and we can only help with docs related issues here. If this is a docs related issue, please make a new ticket and use the template to help us better identify the issue.
