### ISSUE TITLE
Decoupled Sites Doc Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6259]
Re: [Decoupled Sites](https://pantheon.io/docs/decoupled-sites)

Priority: Medium

## Issue Description:

- Decoupled Bridge Managed Service and Edge Sites product are distinct products, and need more complete documentation.

## Suggested Resolution
- Break Decoupled Bridge and Edge Sites into pages for each product/service.
- Decoupled Bridge page - incorporate existing content from [Data Sheet](https://pantheon.io/resources/decoupled-bridge)
- Decoupled Sites page - convert into a topic summary page that includes overview of how Pantheon works with decoupled sites.

**Comment by EdwardAngert** [comment]
resolved by #6923
