### ISSUE TITLE
Create a Drupal 8 Site From the Command Line Using Terminus and Drush Doc Update 

### ISSUE THREAD

**Issue by crashspringfield** [pantheon-systems/documentation#6261]
Re: [Create a Drupal 8 Site From the Command Line Using Terminus and Drush](https://pantheon.io/docs//guides/drupal8-commandline)

Priority: Low

## Issue Description:
Install Drupal Modules step #4 fails with the following error:

```
kint was not found.                                                                       [warning]
Invalid argument supplied for foreach() Project.php:55               [warning]
No release history available for kint current. 
```
According to [the Kint documenation](https://www.drupal.org/project/kint) it is now part of the Devel module in Drupal 8.

## Suggested Resolution
Change `terminus drush $TERMINUS_SITE.dev -- pm-enable devel devel_generate kint webprofiler -y` to `terminus drush $TERMINUS_SITE.dev -- pm-enable devel devel_generate webprofiler -y` (just remove kint from the enable list).

I'd be willing to update the documentation to fix this.

**Comment by EdwardAngert** [comment]
thanks, @crashspringfield ! I'm fixing this one along with the new duplicate, #6378
