### ISSUE TITLE
Pantheon Global CDN Doc Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6264]
Re: [Pantheon Global CDN](https://pantheon.io/docs/global-cdn)

Priority: Low

## Issue Description:
Global CDN page does not contain details about DDoS protection, or other features included in the [AGCDN](https://pantheon.io/product/advanced-global-cdn) page comparison table. 

## Suggested Resolution
Update the page to include this information.

**Comment by EdwardAngert** [comment]
maybe also link to https://pantheon.io/docs/optimize-site-traffic#dos-attack-mitigation
