### ISSUE TITLE
WordPress Configuration Management (WP-CFM) Doc Update 

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6278]
Re: [WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm)

Priority: Medium

## Issue Description:
User feedback received that some of the commands mentioned as being in the dashboard aren't there any longer. User was unable to deploy from dev to test.

## Suggested Resolution
Review and update doc.

**Comment by whitneymeredith** [comment]
@kporras07 @CdrMarks Which commands in the dashboard are no longer there?
