### ISSUE TITLE
Investigate and Remedy Traffic Events Doc Update 

### ISSUE THREAD

**Issue by jdpantheon** [pantheon-systems/documentation#6281]
Re: [Investigate and Remedy Traffic Events](https://pantheon.io/docs/optimize-site-traffic)

Priority: Medium

## Issue Description:

When trying to block a user agent with a "-", the code snippet doesn't work too well:

```
if (stripos($_SERVER['HTTP_USER_AGENT'], 'UglyBot') !== FALSE) {
  header('HTTP/1.0 403 Forbidden');
}
```

For example, trying to block `Go-http-client` using our code snippet still produced a 200 response:

```
34.122.235.200 - - [25/Feb/2021:17:09:37 +0000]  "GET /?code=30%3Aabbb05e1-1a39-489e-8cd1-fc07d319cfb5&client_id=4fb42729-841c-4052-bf61-8ec5958570c2 HTTP/1.1" 200 63854 "-" "Go-http-client/1.1" 0.509 "72.36.244.236, 72.36.244.236, 34.122.235.200"
```

It seems like `stripos` doesn't handle non-alphanumeric too well. Juust simply changing the PHP function to `strpos` (making it case sensitive instead of INsenstive) seems to fix that. Using the below code:

```
// Either check a single bot.
if (strpos($_SERVER['HTTP_USER_AGENT'], 'Go-http-client') !== FALSE) {
  header('HTTP/1.0 403 Forbidden');
}
```

Now throws a proper 403 response when running curl:

```
$ curl -sI --user-agent "Go-http-client1/ihateyou.1" 'https://dev-jdevera-pantheon.pantheonsite.io/wp-login.php?ver=555aa'
HTTP/1.1 403 Forbidden
$ curl -sI --user-agent "ihateyou.1" 'https://dev-jdevera-pantheon.pantheonsite.io/wp-login.php?ver=555aa'
HTTP/1.1 200 OK
$ curl -sI --user-agent "Go-http-client1/ihateyou.1" 'https://dev-jdevera-pantheon.pantheonsite.io/wp-login.php?ver=555aa'
HTTP/1.1 403 Forbidden
```

## Suggested Resolution

Add a caveat to the following [section](https://pantheon.io/docs/optimize-site-traffic#block-user-agents-in-drupal-or-wordpress) to switch the PHP function **from** `stripos` **to** `strpos` when needing to block a user agent with non-alphanumeric character. Something like that.

**Comment by dficker** [comment]
A related pull request: https://github.com/pantheon-systems/documentation/pull/6393

This needs "exit;" after setting a header inside the "if" statement to be effective.
