### ISSUE TITLE
Document git commands used by multidev branch comparisons

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#629]
Please work at @Hornswoggles to document the git commands that will generate the ahead/behind commits for multidev branch comparison.  Some customers are having issues with this, and we might as well document this for both customers and CSE so we have a better understanding of what is happening.

If it turns out that there is more info needed than the customer can get easily, ping me and we can figure out next steps.  

Thanks!

**Comment by bmackinney** [comment]
@nstielau, @Hornswoggles and I met today. I'll document what he taught me about how the dashboard calculates ahead/behind and submit a PR for review.

**Comment by nataliejeremy** [comment]
@bmackinney Can you email the info you have on this?

**Comment by erik-pantheon** [comment]
@nataliejeremy I'll take this one on. :)

**Comment by erik-pantheon** [comment]
It looks like everything we need is here: 

https://github.com/pantheon-systems/titan-mt/blob/0b639ce1050740bb697d9f63ada8a60daf2ca141/endpoint/endpoint_rest.py#L430

**Comment by bmackinney** [comment]
@erik-pantheon It looks like the info is here: https://github.com/pantheon-systems/titan-mt/blob/ab_create_site/endpoint/endpoint_rest.py#L447 Do you have time next week to do this?
