### ISSUE TITLE
Create How Drush works on Pantheon

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#632]
Topics: 
 - Policy/command files `pantheon.drush.inc` 
  - hook command
 - Drush versions

- [x] Convert [Greg's blog post on the subject](https://pantheon.io/blog/fix-drush-site-aliases-policy-file to a doc)
- [x] Explain how to detect drush versions
- [x] Account for changes in drush-ops/drush#1595

**Comment by bmackinney** [comment]
@greg-1-anderson

**Comment by nataliejeremy** [comment]
@greg-1-anderson Do you think you'll have time this week to work on this?

**Comment by greg-1-anderson** [comment]
Sorry, I don't always see my GitHub notifications.

We don't want to document the cookbooks publicly, do we?  Or is this for an internal document?

**Comment by bmackinney** [comment]
- [ ] Convert [Greg's blog post on the subject](https://pantheon.io/blog/fix-drush-site-aliases-policy-file to a doc)
- [ ] Explain how to detect drush versions
