### ISSUE TITLE
Caching: Advanced Topics Doc - clarify deletion behaviour

### ISSUE THREAD

**Issue by deviantintegral** [pantheon-systems/documentation#6322]
Re: [Caching: Advanced Topics](https://pantheon.io/docs/caching-advanced-topics)

Priority: Medium

## Issue Description:

Can file deletion behaviour be documented, likely in the [Manually Expiring Cache for Static Assets](https://pantheon.io/docs/caching-advanced-topics#manually-expiring-cache-for-static-assets) section? For example, in the worst case, what happens on a Drupal 7 site with no cache purging and a file is deleted from the files directory? Will Drupal 8 sites trigger a delete of static assets, and how long should sites expect that to take?

## Suggested Resolution

Update the documentation (and thanks!).

**Comment by michellecolon-pantheon** [comment]
Thanks for your contribution, @deviantintegral ! Can you please provide us with some bullet points on the behavior you experienced so that we may duplicate it and look into this further?

**Comment by deviantintegral** [comment]
> ... has decided to stop using revisions for Media entities. What was happening is that people would be finding outdated versions of documents either through Google searches or were hard-linked in various places

What happened was that they were deleting PDFs, but they were still live on the CDN. What we believe we observed was that the file deletion wasn't being propagated to the CDN, and due to the 1 year cache those PDFs would be available for a long time.

Does that help?

**Comment by michellecolon-pantheon** [comment]
@deviantintegral - Thanks. To clarify, is the expected behavior that when a user deletes a PDF, that the PDF would get automatically deleted on the CDN? If so, do you have a proposed resolution?

**Comment by deviantintegral** [comment]
I think a non-technical end user would expect that, yes.

As a developer, I might expect it but would understand if that's not the case. If file deletions are not propagated immediately to the CDN by the platform, and it's not just a bug, then docs confirming that would be helpful. Otherwise, if they _are_ supposed to be propagated to the CDN, then documenting that too would give us something to point to if we see behaviour otherwise.
