### ISSUE TITLE
WordPress Site Networks: Site Not Found Error

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#6339]
Re: [WordPress Site Networks](https://pantheon.io/docs/guides/multisite/debug/#error-site-not-found)

Priority: Low

## Issue Description:
There is currently an error listed in the FAQ section for debugging WordPress Network Sites that mentions a GitHub issue that has been closed.

## Suggested Resolution
The issue we marked that should be watched has been closed and merged into WP CLI: https://github.com/wp-cli/cache-command/issues/17. Per testing, we could update and remove this issue from the documentation.

**Comment by michellecolon-pantheon** [comment]
Have reached out to @kyletaylored for clarification.
