### ISSUE TITLE
Document how to identify and kill queries using the mysql-cli

### ISSUE THREAD

**Issue by timani** [pantheon-systems/documentation#634]
In the event a flood of slow transactions hits the database, queries can be killed from the mysql-cli using the `kill` command. 

http://smallbusiness.chron.com/kill-long-running-queries-mysql-48524.html

**Comment by sukottokun** [comment]
@timani this too dangerous to show people how to tweak and include?
https://www.percona.com/blog/2009/05/21/mass-killing-of-mysql-connections/

**Comment by timani** [comment]
@sukottokun haven't tried this one before but that'd do the trick too from what I can see. I guess it would be subject to the perms setup for the mysql service. 

More options is better

**Comment by nataliejeremy** [comment]
@timani Is this the doc you want updated?https://pantheon.io/docs/articles/sites/database/mysql-slow-log/
