### ISSUE TITLE
[WIP] Convert an existing Build Tools / "No CI Workflow" site to Drupal 9 IC (without CI) by creating a new site

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6346]
Re: New documentation page on converting from Build Tools without CI to Integrated Composer

Priority: Low

## Issue Description

Customers who are currently using CircleCI or some other CI system to build their Composer-managed site and DO NOT have automated tests, or customers who are manually building their Composer dependencies on their local systems and manually pushing them up to Pantheon might prefer to switch to using Integrated Composer instead.

Build Tools users with automated tests that they do not want to continue using may also follow this guide.

## Suggested Resolution

Create a new Drupal 9 Integrated Composer site and migrate using the procedure outlined below.

Follow steps 1-3 from [Manually Migrate ](https://pantheon.io/docs/guides/drupal-9-migration/migrate-manual-d9) as written.

4. Copy over exported configuration from the original site. From your D9 site, run the following commands: (This is the same as the existing step 4, but adjusted here for path differences)
```
git checkout existing-8/master -- config
git commit -m "Add site configuration."
```

Follow steps 5-7 from [Manually Migrate ](https://pantheon.io/docs/guides/drupal-9-migration/migrate-manual-d9) as written, *but*, add the following warning to step 6:

*DO NOT* add the push-back-to-github.php script from your existing site to your new Drupal 9 site.

8. Examine the contents of the `require` section of your original site's composer.json file and compare it to your new site's composer.json file and upstream-configuration/composer.json file.

Copy over any entry that begins with `drupal/`; you may omit any already in the upstream-configuration/composer.json file, e.g. pantheon-systems/drupal-integrations, drupal/core-composer-scaffold and drupal/core-recommended.

Pick the version of Drush you want to use. Drush 10 is recommended, but you may also use Drush 8. Other versions are not advisable.

You may remove any of the following:

-  drush-ops/behat-drush-endpoint
-  pantheon-systems/quicksilver-pushback
-  rvtraveller/qs-composer-installer
-  zaporylie/composer-drupal-optimizations

If you have changed the version of PHP you are using in your pantheon.yml site, make sure that the entry in `config.platform.php` matches.

Keep the "minimum-stability" of your new site at "dev". TODO: We should use "stable" here but that will take some extra work.

Copy over anything from your "autoload" section that you might need. You do not need the ScriptHandler.php, so most sites will not need anything.

Copy over anything from your "scripts" section that you might need. You do not need "prepare-for-pantheon", "createRequiredFiles" or any of the scaffold-related directives. Copy the unit testing scripts if you are going to use them for local testing. If you have anything in your "build-assets" script other than @prepare-for-pantheon and composer install, then you should not use Integrated Composer at this time. (Need this warning in the "before you begin" section)

Examine your "extra" section and see if there is anything that you need. You do not need "build-env", and "installer-paths" and "drupal-scaffold" should already be correct in your new site's composer.json file, so most likely you will not need anything from "extra".

9. Examine the `require-dev` section of your original site's composer.json file.

If there is a Drupal module listed, copy it to the `require` section of your new site's composer.json file.

If there are any dependencies listed that you will need for testing your site locally, copy them to the `require-dev` section of your new site.

10. Run `composer update` and commit the results.

Important note: Integrated Composer requires that anything installed by `composer install` must be .gitignore'd. After running `composer update`, ensure that only composer.json and composer.lock have changes. If there are any new untracked files, update your .gitignore file before committing.

11. Add custom modules and themes. (This was step 10, but adjusted here for path differences)
```
git checkout existing-8/master -- modules/custom themes/custom
git commit -m "Add custom projects."
```

12. Copy anything you need from your settings file (This was step 11, but adjusted here for path differences)
```
git diff origin existing-8/master web/sites/default/settings.php
# Copy what you need over to web/sites/default/settings.php, and commit as needed.
```

Follow steps 12-15 from [Manually Migrate ](https://pantheon.io/docs/guides/drupal-9-migration/migrate-manual-d9) as written, but renumber (+1) to match step sequence in this doc.

**Comment by EdwardAngert** [comment]
getting things together locally: `6346-buildtools-noci-tod9`

**Comment by b-shrp** [comment]
Fyi. Seems like the Manually Migrate doc has changed and some step numbers may not match. Eg. Step 4 here is Step 3.

**Comment by sambasile** [comment]
Trying to determine what is meant by the numbering system used in this doc.  I suggest adding the Heading to the directions for clarity.  "Follow steps 1-3 found in _Heading Name Here_"

**Comment by wordsmither** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DOC-628] on Pantheon - Build Tools - No CI --> D9 with Composer - JIRA](https://trello.com/c/3s6ijLfI/24-doc-628-on-pantheon-build-tools-no-ci-d9-with-composer-jira)

**Comment by wordsmither** [comment]
Per slack conversation w/Greg, closing this doc (creating using a new site) in favor of existing doc (https://pantheon.io/docs/guides/drupal-9-hosted-createbt), which is the preferred method.
