### ISSUE TITLE
Reducing Large Repositories Doc Update 

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#6350]
Re: [Reducing Large Repositories](https://pantheon.io/docs/reducing-large-repos)

Priority: Low

## Issue Description:
Document limitation when using with custom upstream.

## Suggested Resolution
"Existing sites not only need to be repointed but also force-pushed with latest code from upstream. Except if the new upstream is a clone from previous upstream." Then you can use the upstream normally afterwards

**Comment by EdwardAngert** [comment]
@marfillaster - does it seem like I captured the resolution in a way folks would be able to use?

**Comment by marfillaster** [comment]
For this context, there's no repointing required but force push is necessary since the result is a rewritten repository history. I guess it's more appropriate to be mentioned in https://pantheon.io/docs/create-custom-upstream#switch-an-existing-site-to-a-custom-upstream

**Comment by michellecolon-pantheon** [comment]
@EdwardAngert - Checking in on this one...okay to move to Ready for Work?

**Comment by wordsmither** [comment]
@marfillaster - I'd just like to confirm.  This is a warning we're giving readers, and it should be phrased something like this:

"Existing sites must be force-pushed with the latest code from upstream, unless the new upstream is a clone from previous upstream. Then you can use the upstream normally."

Also, is it relevant to BOTH https://pantheon.io/docs/reducing-large-repos and https://pantheon.io/docs/create-custom-upstream#switch-an-existing-site-to-a-custom-upstream?

**Comment by marfillaster** [comment]
Hi @wordsmither. I think the paragraph is a little vague. 

I'd probably add an info box next to step 1 of [**Prune and Optimize Large Repositories**](https://pantheon.io/docs/reducing-large-repos#prune-and-optimize-large-repositories)

>  For sites using custom upstream, apply the following steps directly to the custom upstream repository. Force push the updated custom upstream repository branch to existing sites' Pantheon repository origin.
