### ISSUE TITLE
Deprecate old documentation page on migrating to Composer 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6356]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs//guides/composer-convert)

Priority: Medium

## Issue Description:

The old "composer-convert" guide, which converts a drops-8 site to a Build Tools site, still has a high Google page rank, and still looks like the most recommended practice.

## Suggested Resolution

Point the users to the [Drupal 9 Integrated Composer migration page](https://pantheon.io/docs/guides/drupal-9-migration/migrate-manual-d9), and recommend users follow those instructions instead. Add a note that the Build Tools conversion may still be used if the user wishes to set up automated testing e.g. on CircleCI, but if in doubt, the Integrated Composer guide should be used instead.

Leave the rest of the existing content on the page as-is.

**Comment by greg-1-anderson** [comment]
It might also be a good idea to have links from the [Build Tools Workflow](https://pantheon.io/docs/guides/build-tools/) and [No CI Workflow](https://pantheon.io/docs/guides/drupal-8-composer-no-ci) pages to the integrated composer documentation. The Build Tools guide should mention that Integrated Composer is an option, but that Build Tools should be used if Continuous Integration tests are desired. The No CI guide should be completely deprecated, or maybe even just remove it and add a redirect to Integrated Composer.

**Comment by EdwardAngert** [comment]
possibly related to DOC-361
the [Covert to Composer](https://pantheon.io/docs/guides/composer-convert) doc got a major update as part of #6145 that takes the steps @greg-1-anderson linked to and keeps them D9-free.

that would leave the remainder of the issue as:

1. Build Tools Guide, [Is Build Tools Rights For You](https://pantheon.io/docs/guides/build-tools/#is-build-tools-right-for-you) should link to Convert to Composer and say ~"Composer is a no-CI option"
2. deprecate/redirect [D8 and Composer no CI](https://pantheon.io/docs/guides/drupal-8-composer-no-ci) to composer-convert

does that sound right?
