### ISSUE TITLE
Imported changelogs are outdated

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#6380]
Priority: High

## Issue Description
We import changelogs for a few projects onto their related doc page. These have gotten stale and are not showing the newest releases of these projects.

| Project  | Release shown | Current release |
| ------------- | ------------- |------------- |
| [Localdev](https://pantheon.io/docs/guides/localdev/changelog)  | 1.0.1  | [1.1.0](https://github.com/pantheon-systems/localdev/releases) |
| [Build Tools](https://pantheon.io/docs/guides/build-tools/) | 2.0.3  | [2.0.4](https://github.com/pantheon-systems/terminus-build-tools-plugin/releases) |
| [Drush](https://pantheon.io/docs/drush#changelog) | 10.4.0-rc1  | [10.4.3](https://github.com/drush-ops/drush/releases) |

## Suggested Resolution
Maybe it's a quick fix to regenerate these? Removing them could also be an option; as a developer, I'd rather read a changelog directly on the project's repo than embedded elsewhere. 

I see these are fetched during the [build process](https://github.com/pantheon-systems/documentation/blob/b6bb2df9a0435d07c4228e1a6f5b725da94d0752/.circleci/config.yml#L33). Perhaps we need to update our GitHub token format in order to fetch this data (similar to this [recent update](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/375) in the Build Tools repo).

**Comment by carolyn-shannon** [comment]
Need help understanding how/where to make this change in CircleCI. @sarahg if you have pointers please reach out in #docs. Thanks!
