### ISSUE TITLE
Integrated Composer Docs - Confusion about Site vs. Upstream

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#6382]
Re: [Integrated Composer](https://pantheon.io/docs/integrated-composer)

Priority: Medium

## Issue Description:

At least a few users, including myself, were not reading carefully and were expecting to see sections like "Add a Dependency to an Individual Site" a bit earlier. And since the "How to Add Dependencies to Your Upstream" section is a bit earlier and sounds similar, we mis-interpreted the latter as how to do the former.

Some users also seemed to be confused as to what an upstream was and if they had to modify the upstream-config folder. Which I believe is not needed unless you're making a custom upstream.

## Suggested Resolution

I would suggest that basic information on how to use Integrated Composer to install and update libraries be at the top. Down further under a clearly marked section about managing upstreams would be info on how we recommend to do that and how the upstream should be structured.

**Comment by joa-pan** [comment]
Thanks for your contribution @dficker. That is a great a point. We are working on improving our Integrated Composer docs 🎉
