### ISSUE TITLE
New Doc: Splunk Integration

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6402]
## Summary

Add doc for Splunk integration. 

Priority: Low

## Issue Description

* Add overview of Splunk integration, following notes on https://pantheon.io/integrations/logging. "Pantheon provides access to all website application containers via SFTP. An external forwarding server can be setup to periodically collect this data from all application containers and send to Splunk. "
* Splunk log aggregation using Terminus to gather sftp connection details in a loop through all sites. (@rachelwhitton)
* Splunk integration with New Relic.
* Automate downloading of logs, then import to Splunk manually.

### Context

* From CSE Support discussion

## Suggested Resolution

* 

## Additional Information

*

**Comment by wordsmither** [comment]
Moving to blocked as there are compatibility issues and we don't yet know how to tell them how to use it.  Currently, best option causes security issues.
