### ISSUE TITLE
Migrate to Drupal 9 Doc: git push should be to origin, not ic

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6412]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority:High

I've got two issues in this single report so that you can deal with them both at the same time.

## Issue Description:

Site needs a pantheon.yml file. Without it, the push fails with:
```
To ssh://codeserver.dev.61ec41bc-....drush.in:2222/~/repository.git
 ! [remote rejected]     composerify -> composerify (pre-receive hook declined)
error: failed to push some refs to 'ssh://codeserver.dev.61ec41bc-...@codeserver.dev.61ec41bc-....drush.in:2222/~/repository.git'
```

## Suggested Resolution

Instead of:
```
If there are settings from pantheon.yml (shown with a - in the diff output), consider copying over your old pantheon.yml to preserve these settings:
```
Tell the user to always copy over their old pantheon.yml. They should remove any settings that they don't need any more, e.g. `drush_version`.

## Issue Description:

The remote is incorrect in the git push step:
```
git push -u ic composerify && terminus env:create $SITE.dev composerify
```

## Suggested Resolution

Change the remote from `ic` to `origin`, i.e.

```
git push -u origin composerify && terminus env:create $SITE.dev composerify
```

**Comment by EdwardAngert** [comment]
done in #6420
