### ISSUE TITLE
Remove Crisis Response Upstream page and related content

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6416]
Re: Remove Crisis Response Upstream content

Priority: High 
Deliver on: 6/30/2021

## Issue Description

* Remove [Crisis Response Upstream](https://pantheon.io/docs/crisis-response-upstream) public docs page and related content from
* Multidev FAQ
* Organization FAQ
* Redirect Crisis Response Upstream traffic to Multidev page.

**Comment by EdwardAngert** [comment]
it looks like we're keeping the Upstream live
can we close this issue?

**Comment by carolyn-shannon** [comment]
Keeping this upstream for now so this issue can be closed, but may revisit this later.
