### ISSUE TITLE
Configure Redirects Doc Update 

### ISSUE THREAD

**Issue by jarkin13** [pantheon-systems/documentation#6417]
Re: [Configure Redirects](https://pantheon.io/docs/redirects)

Priority: High

## Issue Description:

This is quite dangerous and unstable code to recommend to do redirects.  First of all is it bad practice to use `$_SERVER` 

> $_SERVER is an array containing information such as headers, paths, and script locations. The entries in this array are created by the web server. There is no guarantee that every web server will provide any of these; servers may omit some, or provide others not listed here. That said, a large number of these variables are accounted for in the CGI/1.1 specification, so you should be able to expect those.

Secondly, this can cause several redirects, because after testing it seems even if `$_SERVER['HTTP_HOST'] === $primary_domain)` it still has trouble setting this causing multiple redirects. 

## Suggested Resolution

Give the option for proxies, because as a WordPress host this should be a standard.

**Comment by joa-pan** [comment]
Hi @jarkin13 Thank you so much for highlighting this issue. This is currently the recommended approach in our documentation, but our engineering team is working on providing a more standard solution. If you have reoccurring issue with this, you can also file a support ticket. Thanks again for raising this issue.
