### ISSUE TITLE
Serverless CMS | Pantheon Product Page Broken Link

### ISSUE THREAD

**Issue by saintmalik** [pantheon-systems/documentation#6429]
Re: [Serverless CMS | Pantheon](https://pantheon.io/product/serverless-cms)

Priority: Medium

## Issue Description:
The [Multizone Failover: 99.99% Up-Time & Minimize Data Loss | Pantheon](https://pantheon.io/product/features/multizone-failover) is borken due some typo error

## Suggested Resolution
removing the "/prduct/" leaving it this way "https://pantheon.io/features/multizone-failover" fixes the error

**Comment by joa-pan** [comment]
Thanks for this great catch @saintmalik. This should be resolved now. We really appreciate your contribution!

**Comment by saintmalik** [comment]
> Thanks for this great catch @saintmalik. This should be resolved now. We really appreciate your contribution!

Yeah, it has been fixed, works well now, thanks 😌
