### ISSUE TITLE
Pantheon Localdev Doc Update 

### ISSUE THREAD

**Issue by JBCSU** [pantheon-systems/documentation#6437]
Re: [Pantheon Localdev](https://pantheon.io/docs//guides/localdev)

Priority: Low

## Issue Description:

The link in the first sentence of the second paragraph, "Localdev lets you [use an integrated development environment (IDE)](https://pantheon.io/docs/guides/localdev#use-a-local-ide-to-develop-your-pantheon-site) to edit files and code, and push changes to Pantheon right from your desktop." goes to an anchor that doesn't appear on the page, so it's effectively broken.

## Suggested Resolution

Please either fix or remove the link.

**Comment by EdwardAngert** [comment]
#6438 has another broken anchor - probably worth digging through and confirming the rest+closing both issues in one
