### ISSUE TITLE
Pantheon Localdev Doc Update 

### ISSUE THREAD

**Issue by gmtan2** [pantheon-systems/documentation#6438]
Re: [Pantheon Localdev](https://pantheon.io/docs//guides/localdev/troubleshoot-support)

Priority: Medium

## Issue Description:
The link to the Pantheon Localdev Customer Feedback for does not exist. When link is clicked it says "Sorry, the file you have requested does not exist."

## Suggested Resolution
Update the link to the correct Google doc

**Comment by EdwardAngert** [comment]
thanks, @gmtan2 !
Looks like this was fixed in #6442
