### ISSUE TITLE
Pantheon Localdev Doc Update 

### ISSUE THREAD

**Issue by jdpantheon** [pantheon-systems/documentation#6457]
Re: [Pantheon Localdev](https://pantheon.io/docs//guides/localdev/changelog)

Medium

## Issue Description:

It looks like we're missing the 1.1.0 version in the changelog. The only way I've found it is by trying to update my version:

![Pantheon_Localdev](https://user-images.githubusercontent.com/63304703/120669908-e5b85e80-c45d-11eb-957d-1615c49870a0.png)

## Suggested Resolution

Update public changelog for 1.1.0

**Comment by EdwardAngert** [comment]
thanks @jdpantheon !
We're trying to figure out how to fix this for Localdev and Terminus (and Build Tools) - we've got an existing issue in #6380 that we're going to track work in, so I'm going to close this one for now
