### ISSUE TITLE
Migrate to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#6460]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Medium

## Issue Description:

In talking with a customer in Support, there are a few steps missing if they try to deploy to a multidev as described here. Also applies to this page as well: https://pantheon.io/docs/guides/composer-convert

## Suggested Resolution

Add these steps to the "Deploy to a multidev" section:

 - When on the mutlidev, because there are no commits common between the master branch and the multidev, the Pantheon Dashboard will in error show that there are no commits changed from master. And the developers will not be able to see the Integrated Composer build log until deploying to master.
 - When you first push to the mutlidev, it will not see your changes to "pantheon.upstream.yml" and "pantheon.yml". Make a basic space/line change to "pantheon.yml" after the mutlidev is fully created and commit/push that.
 - The UI will not allow you to merge to master directly since there are no common commits. To deploy these changes to master, the developers will need to use "git reset" and a force push to deploy this to master.

I will try to find some time to test this out on one of my sites and see if I can write up a PR for this. But just noting it here in case it helps someone or someone else can update/verify all this before I can do so.

**Comment by mparker17** [comment]
I was also seeing these issues; and had filed support ticket 580214 to try to address.

In that ticket, @emmanuelhallarsis suggested the following way to "merge composerify into master"...

```
$ git checkout master
$ git reset --hard composerify~0
$ git push --force origin master
```

... this worked well for me.
