### ISSUE TITLE
Live Workshop Resources Doc Update 

### ISSUE THREAD

**Issue by KatAussie** [pantheon-systems/documentation#6491]
Re: [Live Workshop Resources](https://pantheon.io/docs/live-workshop-resources)

Priority: Medium?

## Suggested Resolution: Fix the link? :)

**Comment by carolyn-shannon** [comment]
@KatAussie this page is dynamically populated with info, depending on which workshop the user attended. To which workshop are you referring?

**Comment by joa-pan** [comment]
Thanks @KatAussie for submitting this issue 🥇 🥳 .  This should be resolved now. I think the following PRs most likely fixed the issue:
* [6499](https://github.com/pantheon-systems/documentation/pull/6499)
* [6488](https://github.com/pantheon-systems/documentation/pull/6488)
