### ISSUE TITLE
Create a Custom Upstream Doc Update 

### ISSUE THREAD

**Issue by WHoltPantheon** [pantheon-systems/documentation#6519]
Re: [Create a Custom Upstream](https://pantheon.io/docs/create-custom-upstream)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

Customer pointed out there is a discrepancy between "drupal" and "drops" in the command line instructions:

git fetch pantheon-drupal-9 master
git merge pantheon-drops-9/master

They didnt provide much else - Please can you take a look if they are correct or you think there is an error? :)

**Comment by EdwardAngert** [comment]
thanks @WHoltPantheon!
this got fixed in #6521 , but I had forgotten to tag the issue
closing
