### ISSUE TITLE
Symlinks and Assumed Write Access Doc Update; adding NitroPack

### ISSUE THREAD

**Issue by orlandoayeras** [pantheon-systems/documentation#6524]
Re: [Symlinks and Assumed Write Access](https://pantheon.io/docs/symlinks-assumed-write-access)

Priority: Low

## Issue Description:
Raising the Nitropack plugin compatibility in the platform. Nitropack caching plugin assumes write access to advanced.cache.php and the `wp-content/nitropack` folder to store data and gives this error: _**The NitroPack data directory cannot be created. Please make sure that the /wp-content/ directory is writable and refresh this page.**_
As with other caching plugins, Nitropack conflicts with Pantheon's Advanced Page Cache. The caching feature can be disabled so other features like optimization can be used side-by-side. Note that if not disabled, Nitropack will auto-create the advanced-cache.php file.

## Suggested Resolution:
Possibly state in our docs that the reverse proxy server cannot work on our platform due to the dynamic IP that Pantheon has.

### Possible Solution: 

1. Navigate to your Dev’s `code/wp-content/uploads` or `files/` using SFTP client like Filezilla.
2. Create a "nitropack" folder and “advanced-cache.php” file or by doing this command; 
`mkdir ./nitropack​ && touch ./advanced-cache.php`
note: delete any advanced-cache.php that is present from the `./uploads` directory before creating the file
3. Then, do also the first 2 steps both on the Test and Live env. You can connect via SFTP-cli or an SFTP client from the "connection info" tab.
4. And after that, do a symlink inside the `code/wp-content` directory:
`ln -s ./uploads/nitropack/ ./nitropack`
`ln -s ./uploads/advanced-cache.php ./advanced-cache.php`
![image](https://user-images.githubusercontent.com/77082837/125016536-19615680-e0a4-11eb-8ef7-edf37b3c43f0.png)
5. Commit the code changes up to the Live env.

#### Related tickets that this workaround solution work:
577645
580172
574199

**Comment by EdwardAngert** [comment]
thanks, @orlandoayeras !
we'll get this one added to [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues#assumed-write-access) and the Examples section of [Symlinks and Assumed Write Access](https://pantheon.io/docs/symlinks-assumed-write-access#examples)
