### ISSUE TITLE
New Guide: Disaster Recovery

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6525]
Re: Disaster Recovery Guide

Priority: Medium

## Issue Description

* As a user recovering from a site disaster, I need help knowing what steps to take (and not to take) to restore my site, and what steps require Support assistance.

### How will this impact users?

*

### Context

* 

## Suggested Resolution

* Create a scenario-based Disaster Recovery Guide 

## Additional Information

*

**Comment by joshualieb** [comment]
Current internal working document: https://docs.google.com/document/d/1RW0gmJBpqTjBfK7Cm2HC-EtqYG-15R-aN5B7ggKv0d0/edit?usp=sharing
