### ISSUE TITLE
Add Static HTML and Empty upstream documentation

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/documentation#6532]
Re: Add new documentation that covers Empty upstreams and Static HTML

Priority: Low

## Issue Description

* Currently, we only reference Empty upstreams as part of the Build Tools setup process.
* Some customers ask "Can we host static files in a site?" The answer is yes, but we don't have any documentation to send them to.
* Example: Google "pantheon static html"

### How will this impact users?

* Provide documentation for how and why a customer would use an Empty upstream (for example, customers deploying code to Pantheon not using Build Tools or Custom Upstreams)
* Provide documentation for customers looking to just upload static HTML

### Context

* Feedback through sales cycles and customer support questions.

## Suggested Resolution

* Add new documentation for Static HTML and Empty upstreams.

**Comment by michellecolon-pantheon** [comment]
Hi @kyletaylored 👋🏾  For this issue, is there any supplemental info/any links that might give me some more background? Is there a support ticket I can reference where there have been any steps outlined? LMK 🙂

**Comment by michellecolon-pantheon** [comment]
Thank you, Kyle! I will look at the resources you provided and let you know if I have any questions.

**Comment by michellecolon-pantheon** [comment]
Hi @kyletaylored  - One more thing: for the Static HTML piece, is there any additional info I can refer to/look at?

**Comment by kyletaylored** [comment]
Not really, other than we just get a lot of requests of "Can I host a static site or static pages in my site?" and the answer is yes, but we don't have anywhere to point them. The summary is this:

**Can I add static pages to my site?**
Yes, you can commit any static HTML files to your site that are unrelated to the CMS. You can see a demo of this here: [Adding Static Pages through the Pantheon Dashboard](https://www.loom.com/share/da359ade64644644b380a025a05d47e4)

**Can I host a static site with Pantheon?**
Yes. You can start a new site using an Empty upstream, and then add any static files you wish.
