### ISSUE TITLE
Accessible colours for "Configuring Environment Indicators"

### ISSUE THREAD

**Issue by deviantintegral** [pantheon-systems/documentation#6564]
Re: [Configuring Environment Indicators](https://pantheon.io/docs/environment-indicator)

Priority: Medium

## Issue Description:

Not all of the suggested colours pass contrast checks for Environment Indicator. On a typical Drupal site, we'd assume that it should pass AA / regular text as a baseline.

lando:

<img width="592" alt="Screen Shot 2021-07-29 at 1 30 53 PM" src="https://user-images.githubusercontent.com/255023/127537963-59adea2d-85ab-4f24-a8de-f8fbe96d243c.png">

dev:

<img width="592" alt="Screen Shot 2021-07-29 at 1 30 25 PM" src="https://user-images.githubusercontent.com/255023/127537891-9b33a5a8-4304-475d-85b6-3d65cf3f0af4.png">

test 🎉:

<img width="592" alt="Screen Shot 2021-07-29 at 1 31 22 PM" src="https://user-images.githubusercontent.com/255023/127538015-db3de851-c7ad-430c-aefa-3ac76c011f9b.png">

live 🎉:

<img width="592" alt="Screen Shot 2021-07-29 at 1 31 42 PM" src="https://user-images.githubusercontent.com/255023/127538048-119a4b57-95b9-4743-80b5-216f0bedee4c.png">

multidev:

<img width="592" alt="Screen Shot 2021-07-29 at 1 32 12 PM" src="https://user-images.githubusercontent.com/255023/127538124-ed9fcbd8-3279-4542-a212-29b74d16e4c0.png">

## Suggested Resolution

We recently went through this exercise for our own sites, and landed on the following recommended colours:

| Environment    | Colors          | Suggested `fg_color` | Suggested `bg_color`                           |
 |----------------|-----------------|----------------------|------------------------------------------------|
 | Live           | White on Red    | `#ffffff`               | `#e7131a` |
 | Staging        | White on Orange | `#ffffff`               | `#b85c00` |
 | Development    | White on Green  | `#ffffff`               | `#307b24` |
 | Branch Preview | White on Purple | `#ffffff`               | `#990055`       |
 | Local          | White on Grey   | `#ffffff`               | `#505050` |

One note is that we tend to use Red for production, but only developers and technical team members who use multiple environments have permission to see the environment indicator at all. This is reversed from the current docs that recommend green for production.

**Comment by carolyn-shannon** [comment]
Thanks for the suggestion!
