### ISSUE TITLE
Expand Contribute to Docs Guide

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6576]
Re: Contribute to Pantheon Docs

Priority: Medium

## Issue Description

* Expand Contribute to Docs page into a multi-page guide, incorporating the Style Guide page and adding a separate page for voice, style, and flow. 
* Add separate page for content type definitions
* Incorporate existing page template doc
* Add references to the inclusive language guide, glossary

### How will this impact users?

*

### Context

* 

## Suggested Resolution

* 

## Additional Information

*

**Comment by joa-pan** [comment]
Closing in favor of (DOC-405)[https://getpantheon.atlassian.net/browse/DOC-405]

**Comment by joa-pan** [comment]
Closing in favor of https://getpantheon.atlassian.net/browse/DOC-624
