### ISSUE TITLE
WordPress SendGrid plugin is no longer available

### ISSUE THREAD

**Issue by khairulanam-pantheon** [pantheon-systems/documentation#6595]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs//guides/sendgrid)

Priority: Medium

## Issue Description:
WordPress SendGrid plugin is no longer available since July 13, 2021. The official link is here https://wordpress.org/plugins/sendgrid-email-delivery-simplified/

## Suggested Resolution
I have used this plugin to configure SendGrid and it's working perfectly https://wordpress.org/plugins/wp-mail-smtp/

**Comment by EdwardAngert** [comment]
thanks, @khairulanam-pantheon !

we've gotten some more notifications about this one, so I'll bump it into the ready pile
and add a few more places we should update for this:
- https://pantheon.io/docs/email
- https://pantheon.io/docs/guides/sendgrid-wordpress-wp-mail-smtp
- and 136 results for SendGrid in the repo
