### ISSUE TITLE
Retire Drupal 6 documentation

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#6600]
Priority: Medium

## Issue Description

* Remove Drupal 6 documentation references, to make room for updated instructions for Drupal 9 and 10

### How will this impact users?

* Drupal 6 users should move to a supported version of the CMS.

## Suggested Resolution

* Add section to Core Updates page on D6LTS partners, remove other D6 content from that page. (see Migrate page for LTS language that can be used here)
* Leave changelog entries (point to active pages if links currently point to a page that is/will be deprecated)

Impacted pages:
* Database connection errors
* Drupal cron
* Drupal Launch Check
* Drupal updates
* Drush versions
* Drush
* FAQ
* Migrate Manually
* Migrate
* Object Cache
* Pantheon.yml
* PhP Versions
* Reading Environment Config
* Settings.php

## Additional Information

*

**Comment by joa-pan** [comment]
@carolyn-shannon and @EdwardAngert  is this ready to be worked on?

**Comment by carolyn-shannon** [comment]
This is pending an assessment of how many active D6 sites are still running on the platform.

**Comment by carolyn-shannon** [comment]
This is ready for work.
