### ISSUE TITLE
Migrate to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by justkristin** [pantheon-systems/documentation#6607]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Medium

## Issue Description:
Command offered in section 1 of "Contributed Code - Modules and Themes" doesn't work as-is for me.

## Suggested Resolution
Adding a " -- " between pm:projectinfo and --fields fixed it.
Final working version (again, for me):
terminus drush $SITE.dev pm:projectinfo -- --fields=name,version --format=table

Thanks to @namespacebrian for the info

**Comment by joa-pan** [comment]
Thank you for your contribution @justkristin. It is greatly appreciated 🥳

**Comment by joa-pan** [comment]
@EdwardAngert 👀  I think this might relate to https://github.com/pantheon-systems/documentation/pull/6596.

**Comment by EdwardAngert** [comment]
thanks @justkristin !
(and @namespacebrian(!) )

I remember there being discussion about an issue like this before ( [#5010](https://github.com/pantheon-systems/documentation/pull/5010#issuecomment-520928830) ), specifically about `remote` commands, and when I run(ran) the commands as written it worked
(cc: @TeslaDethray - you've got some comments in there that I can't remember if we'd resolved wrt what terminus commands need/don't need `--`)

Anyone of you all know if there's an environmental variable that makes it work without the `--`?
I'm using:
- iterm2
- (oh-my-)zsh
- a grey laptop

**Comment by EdwardAngert** [comment]
and a followup note to @pantheon-systems/docs-admins : this might be something for both the Docs and for terminus `man` and how it's pulled into the docs or we might need to add notes to each relevant command's page

**Comment by namespacebrian** [comment]
@EdwardAngert what version of php are you running? `php --version`

I believe the need (or lack-of-need) for `--` arises in the command argument parsing.. `terminus` interprets args intended for `drush` as its own and errors if it doesn't recognize them.  I have not tested, but I *think* the commands should always work with `--` even if they also work without it.  `--` simply tells terminus not to interpret anything further as arguments, so it passes them through to drush.

I don't know whether the shell would matter, but I know `zsh` is the default shell on recent versions of MacOS (although I think the oh-my-zsh suite is not), but I always switch it back to `bash` because I have a lot of bash config that doesn't work in `zsh` and I don't want to re-learn everything.  I think @justkristin is also using `bash`.

**Comment by EdwardAngert** [comment]
I was finally able to pick this up and test it out, but when I ran the command in the doc (with and without the second `--`), I got:

```
In Application.php line 272:

  The pm-projectinfo command was removed. Please see `drush pm:list` and `com
  poser show`


 [notice] Command: $SITE.dev -- drush pm:projectinfo [Exit: 1]
 [error]

```

I changed the command to:

```
terminus drush $SITE.dev -- pm:list --fields=name,version --format=table
```

and it ran successfully

if that command also works for you @justkristin and @namespacebrian (and @greg-1-anderson ) , I can adjust it in the doc(s) as well

**Comment by EdwardAngert** [comment]
tested on Drupal 8

`pm:list` shows a list:
```
terminus drush $SITE.dev -- pm:list --fields=name,version --format=table

 Name                                              Version
 Actions (action)                                  8.9.16
 Activity Tracker (tracker)                        8.9.16
 Aggregator (aggregator)                           8.9.16
...
```

`pm:projectinfo` as currently written shows drupal version:
```
terminus drush $SITE.dev -- pm:projectinfo --fields=name,version --format=table

 Name    Version
 Drupal  8.9.16

 [notice] Command: $SITE.dev -- drush pm:projectinfo [Exit: 0]
```

`pm:projectinfo` with another set of `--` errors:
```
terminus drush $SITE.dev -- pm:projectinfo -- --fields=name,version --format=table

Unknown option: --.  See `drush help pm-projectinfo` for available   [error]
options. To suppress this error, add the option --strict=0.
 [notice] Command: $SITE.dev -- drush pm:projectinfo [Exit: 1]
 [error]
```

**Comment by greg-1-anderson** [comment]
This worked well for me:
```
terminus drush site.env pm:projectinfo -- --fields=name,version --format=table
 Name                                   Version        
 Drupal                                 8.9.15         
 Pathauto (pathauto)                    8.x-1.0-alpha3 
 Video Embed Field (video_embed_field)  8.x-1.6        
```
Drupal version is shown for Drupal, project version is shown for each project. If you don't have any contrib installed, then you will only see Drupal.

`pm:list` shows all extensions, including core extensions, which might lead you to believe that you have contrib to convert when you in fact do not.

**Comment by EdwardAngert** [comment]
ah - I see you here too, @greg-1-anderson 
that confirms @justkristin 's solution

I'll update the PR
