### ISSUE TITLE
"Clone a Drupal Site" docs should not recommend drush ard to Valhalla

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/documentation#663]
Writing a large tarball to Valhalla is not recommended.  We should change to the docs to recommend either a) using tmp dir and SFTP, or b) using Pantheon backup.

@sukottokun 

https://github.com/pantheon-systems/documentation/edit/master/source/docs/articles/sites/create/clone-a-drupal-site-using-drush.md

**Comment by bmackinney** [comment]
Options: 
1. Delete the doc
2. Add a big warning that it's only safe for small sites and link to clone from dash backup doc

**Comment by nataliejeremy** [comment]
+1 to delete the doc

**Comment by bmackinney** [comment]
Suzanne Aldrich: just delete it.

[11:01] Suzanne Aldrich: nobody reads warnings.

[11:02] Suzanne Aldrich: we have supported ways of doing this, no need for options that don’t work 100%

**Comment by nstielau** [comment]
We should avoid "Add a big warning that it's only safe for small sites and link to clone from dash backup doc" at all costs.
