### ISSUE TITLE
Relaunch Existing Pantheon Site Doc Update 

### ISSUE THREAD

**Issue by Elizabeth-Evans** [pantheon-systems/documentation#6648]
Re: [Relaunch Existing Pantheon Site](https://pantheon.io/docs/relaunch)

Priority: High 

## Suggested Resolution: Work with PS to add instructions for customers relaunching with AGCDN

**Comment by EdwardAngert** [comment]
thanks, @Elizabeth-Evans !

is there a specific part of the doc that we should bring to PS?
is this issue related to or resolved by [PR6624](https://github.com/pantheon-systems/documentation/pull/6624/files#diff-bba911e9b6e28252c2707e9e0880b011c60113efb9eacd24517bdd90d2f776ceR26-R30) ?

**Comment by allenfear** [comment]
@Elizabeth-Evans does the PR Edward linked to above resolve the issue or is more needed?
