### ISSUE TITLE
FontAwesome Slack icon is using Slack's old logo

### ISSUE THREAD

**Issue by CdrMarks** [pantheon-systems/documentation#6649]
## Expected behavior
* See Slack's new logo in the article header next to Discuss in Slack

## Actual behavior
* See Slack's old logo in the article header next to Discuss in Slack

### Steps to reproduce the problem

1. View any docs page.  Example: https://pantheon.io/docs/migrate
2. See Slack's new logo in the article header next to Discuss in Slack

## Suggested Resolution
* Possibly update the version of FontAwesome being used

## Screenshot
![image](https://user-images.githubusercontent.com/3489003/131193474-15b8058f-a309-4769-a90f-d84a05a982f4.png)

## Additional information
Search for `slack` at https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=slack&s=brands&m=free
![image](https://user-images.githubusercontent.com/3489003/131193509-499be8ad-6283-4931-ae34-bcfca729f17f.png)

**Comment by EdwardAngert** [comment]
thanks, @CdrMarks!
We've got work planned to refresh and upgrade a number of things within our documentation stack, including the FA set, so I'm closing this issue for now.
