### ISSUE TITLE
Changelog - terminus repository default branch name changed on github

### ISSUE THREAD

**Issue by namespacebrian** [pantheon-systems/documentation#6676]
Re: Changelog

Priority: Low

## Issue Description
The default branch name on the [terminus github repository](https://github.com/pantheon-systems/terminus) changed from `master` to `2.x`.

### How will this impact users?
This has no impact on ordinary terminus users.  It is only relevant to people with a local clone of the repo, i.e. terminus contributors or plugin developers. 

### Context
This change was made because of upcoming release of Terminus version 3.  There is also an industry movement to move away from the default branch name `master`: https://dev.to/rhymu8354/git-renaming-the-master-branch-137b

## Suggested Resolution
Anyone with a local clone will need to update their branches as described in [Github's documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes):

```
$ git branch -m master 2.x
$ git fetch origin
$ git branch -u origin/2.x 2.x
$ git remote set-head origin -a
```

## Additional Information
We plan to change the `3.x` branch to the default branch after Terminus 3 is released.

**Comment by EdwardAngert** [comment]
possibly also [Terminus: Create Plugins](https://pantheon.io/docs/terminus/plugins/create)
