### ISSUE TITLE
Terminus Manual Doc Update 

### ISSUE THREAD

**Issue by justkristin** [pantheon-systems/documentation#6678]
Re: [Terminus Manual](https://pantheon.io/docs/terminus/commands/site-create)

Priority: Low

## Issue Description:

Having problems creating a site, but only getting the following error message:
`   [error]  The operation failed to complete.
`
Added --verbose and had no change to the error message. 
Noted that, in the "verbose" section of **Options**, there are instructions which seem to hint at giving the verbose option a value:
`  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
`
When I tried giving it the value of 3, however, I was told:
`    The "--verbose" option does not accept a value.
`

As a currently nervous new-hire, I will own this one, as I was able to figure it out by simply entering the blank command 
`  terminus site:create
`
at which point I saw that what I really wanted was -v, -vv or -vvv

It may be good, for  new kids, however, to add the short versions of options to the instructions...? Sorry!

## Suggested Resolution

**Comment by joa-pan** [comment]
Thank you for opening this issue @justkristin 🥳

**Comment by EdwardAngert** [comment]
relates to #5984

**Comment by EdwardAngert** [comment]
@kporras07 I was poking around in the [Terminus repo](https://github.com/pantheon-systems/terminus), but didn't see where I might be able to suggest this change

In `commands.json`, each command that can accept a `-v/vv/vvv` has

```json
"description": "Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug",
```

would we be able to modify that to read:

```json
"description": "Increase the verbosity of messages: 1 for normal output (-v), 2 for more verbose output (-vv), and 3 for debug (-vvv)",
```

**Comment by kporras07** [comment]
Related PR in terminus repo: https://github.com/pantheon-systems/terminus/pull/2320

**Comment by scottbuscemi** [comment]
This issue can be closed here in docs - we will update the terminus output description and include this in the next version (v3.0.9)
