### ISSUE TITLE
Pantheon Filesystem Doc Update 

### ISSUE THREAD

**Issue by ablys** [pantheon-systems/documentation#6684]
Re: [Pantheon Filesystem](https://pantheon.io/docs/files)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by joa-pan** [comment]
Hi @ablys 🥳  Please add more info or context to this issue so we aware of what needs to be fixed. Thanks and we appreciate the contribution.

**Comment by EdwardAngert** [comment]
hi @ablys !
thanks for submitting an issue to help improve the docs

if there was an issue with the documentation that you encountered, please let us know here and we can reopen this issue.
