### ISSUE TITLE
add Nginx note for Smush Pro (WP plugin)

### ISSUE THREAD

**Issue by ccharlton** [pantheon-systems/documentation#6695]
Re: https://pantheon.io/docs/plugins-known-issues

Priority: Medium

## Issue Description
* Smush Pro is not called out on the known plugins page

### How will this impact users?
* It's a popular plugin and users looking to get WebP support out of it won't be able to on our platform.

### Context

> "Hi all - as part of our Technical Review we take a close look at Lighthouse which often will recommend delivering “next-gen image formats” such as WebP. Anyway, Smush Pro appears to now offer this server side but requires some NGINX configuration. However, the instructions talk about making adjustments to the NGINX config file. I don’t think that’s an option, correct? https://wpmudev.com/blog/local-webp-support-smush/#NGINX. Any workarounds we could offer in this situation?"

## Suggested Resolution
* Add the plugin to the known list with the note on limitation and reasons.

## Additional Information
* Highlighting and linking to Advanced CDN page noting our [Image Optimization] addon has WebP auto-conversion at the edge, and is more performant than a plugin relying on PHP/WP is an appropriate detail.

**Comment by EdwardAngert** [comment]
thanks (again) @ccharlton !
for this one, we can totally add it - can you give us a bit more on what the limitation is? is it assuming write access or is a temporary filesystem issue?

also same 2. can you give us a sentence about what alternative we should offer/how?
