### ISSUE TITLE
WebP Express (WP) plugin can use an AGCDN Image Optimization callout

### ISSUE THREAD

**Issue by ccharlton** [pantheon-systems/documentation#6696]
Re: https://pantheon.io/docs/plugins-known-issues

Priority: Medium

## Issue Description
* WebP Express limitation could benefit from AGCDN Image Optimization callout/link.

### How will this impact users?
* It's a popular plugin and users looking to get WebP support out of it won't be able to on our platform.

## Suggested Resolution
* Update the plugin note to link to AGCDN page/docs.

## Additional Information
* Highlighting and linking to Advanced CDN page noting our [Image Optimization] addon has WebP auto-conversion at the edge, and is more performant than a plugin relying on PHP/WP is an appropriate detail.

**Comment by EdwardAngert** [comment]
thanks, @ccharlton !
just to clarify, should we change the language in the known issues doc from `don't use this` and nothing else, to add `you might want to check out agcdn`?

2. can you give us a little more info about the [image optim](https://pantheon.io/docs/platform-considerations#image-optimization-tools) add-on and how it works here?

**Comment by EdwardAngert** [comment]
update: is this related to #6805 ?

**Comment by ccharlton** [comment]
@EdwardAngert, I don't feel they're directly related. This ticket was about how a plugin needs write permissions on prod to do what it's built for, which won't happen on our environments for security & performance reasons. #6805 is about general best practices.
