### ISSUE TITLE
Migrate to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by cse-almamun** [pantheon-systems/documentation#6701]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Medium

## Issue Description:
https://pantheon.io/docs/guides/drupal-9-migration/upgrade-to-d9#add-the-pantheon-integrated-composer-upstream-in-a-new-local-branch in this section point-2 needs to update. 
For few customers, the git API URL doesn't work and its return "git@github.com: Permission denied(Publickey). so we to add another option with https url. 
## Suggested Resolution
Here is the suggested command to add "git remote add ic https://github.com/pantheon-upstreams/drupal-project.git && git fetch ic && git checkout --no-track -b composerify ic/master"

**Comment by EdwardAngert** [comment]
thanks @cse-almamun !
I have a feeling this might be related to users not creating an SSH key or their file permissions aren't configured correctly for the key to be referenced properly
I'll put in a PR to tell folks that they should check their [SSH keys](https://pantheon.io/docs/ssh-keys) and can use the HTTPS if necessary
