### ISSUE TITLE
Pantheon Professional Services Doc Update - Add more description to Redirects

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#6706]
Re: [Pantheon Professional Services](https://pantheon.io/docs//guides/professional-services/advanced-global-cdn)

Priority: Low (choose one, remove the other options)

## Issue Description:
Add details about what kind of redirect I can make

## Suggested Resolution
Additional info about redirects

**Comment by EdwardAngert** [comment]
closed by #6706
