### ISSUE TITLE
Add new page in the docs that educates user about headers

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6730]
Re: Add new page in the docs that educates user about headers

Priority: Low

## Issue Description
Since PS offers Header modification via ACDN: https://pantheon.io/docs/guides/professional-services/advanced-global-cdn#modify-and-filter-headers-at-the-edge, it might be a good internal resource instead of pointing them out in various external sources

### How will this impact users?
This can also help out other depts(sales/cse,etc) that needs to educate customers about headers

### Context
Having an internal page that explains all about headers, might be a good internal resource instead of pointing them out in various external sources

## Suggested Resolution
Add a page that outlines what are headers all about, we can start outlining the headers of pantheon.io and explaining the parts

```
curl -sIL pantheon.io       
                         
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Location: https://pantheon.io/
Server: nginx
X-Pantheon-Styx-Hostname: styx-fe2-a-6b6d6f77d6-2h8pw
X-Styx-Req-Id: fc9fff1e-22f6-11ec-b5ec-8e8cf3dee576
Cache-Control: public, max-age=86400
Content-Length: 162
Date: Sat, 02 Oct 2021 05:54:17 GMT
Connection: keep-alive
X-Served-By: cache-mdw17383-MDW, cache-mnl9724-MNL
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1633154057.404067,VS0,VE1
Vary: Cookie, Cookie
Age: 33584
Accept-Ranges: bytes
Via: 1.1 varnish, 1.1 varnish

HTTP/2 200 
cache-control: public, max-age=3600
content-language: en
content-security-policy: frame-ancestors https://app.experiencewelcome.com/ https://test-panther.pantheonsite.io/;
content-type: text/html; charset=utf-8
etag: W/"1633149256-0"
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Sat, 02 Oct 2021 04:34:16 GMT
link: <https://pantheon.io/>; rel="canonical"
permissions-policy: interest-cohort=()
server: nginx
strict-transport-security: max-age=31622400
x-drupal-cache: HIT
x-frame-options: SAMEORIGIN
x-pantheon-styx-hostname: styx-fe2-b-56496ffc66-drgj6
x-styx-req-id: 8fac5f23-2340-11ec-b570-325a77174e1b
date: Sat, 02 Oct 2021 05:54:20 GMT
x-served-by: cache-mdw17373-MDW, cache-mnl9724-MNL
x-cache: HIT, MISS
x-cache-hits: 1, 0
x-timer: S1633154060.092324,VS0,VE245
vary: Accept-Encoding, Cookie, Cookie, Cookie
age: 1986
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
content-length: 156587
```

## Additional Information

We can also add other sections like
- security headers( Content-Security-Policy, Referrer-Policy, Permissions-Policy, X-Content-Type-Options, X-Frame-Options
- webp/image optimization is in effect( so PS can also refer here so users can double-check that their purchase ACDN IO is in effect after implementation)
- what to check in the headers if the WAF is in effect as well as the ACDN
- caching data in the headers

**Comment by michellecolon-pantheon** [comment]
Closing this in favor of #7054
