### ISSUE TITLE
Configure Redirects Doc Update 

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#6753]
Re: [Configure Redirects](https://pantheon.io/docs/redirects#redirect-with-php)

Priority: Low

## Issue Description:

as requested by @ksenour 
explain how users can redirect traffic to their live site/domain from `$site.pantheonsite.io`

## Suggested Resolution

add a subsection to the Redirect with PHP section that explains how users can redirect traffic to their live site/domain from `$site.pantheonsite.io`

@namespacebrian gave us some code:

```php
if (preg_match('/^live-(.+)\.pantheonsite\.io$/', $_SERVER["HTTP_HOST"], $matches)) {
		$redirect_url = 'https://www.' . $matches[1] . '.com';
    $response_code = 301;
	}
```

probably link to it from [Platform Domains](https://pantheon.io/docs/domains#platform-domains) and some others

as a bonus, Brian also provided some code that could be referenced by `wp-config` or `settings` to check for redirects, but it'd take extra steps:

> sites/default/example-redirects.php in the custom upstream, which was not included by anything, then settings.php checked for the presence of a redirects.php and included it if it was present.
individual sites would copy the example to redirects.php if they wanted to add redirects... so the code was already provided by the custom upstream, but individual sites were responsible for their own redirects...

**Comment by namespacebrian** [comment]
I think the "bonus" part about the separate `redirects.php` file might be too complicated / nitty-gritty detail to be worth including in the primary documentation... but it's a good thing for CSM/CSE/SalesEngineering to know about for customers who ask them directly how to handle redirects, especially when it comes to custom upstreams.

**Comment by namespacebrian** [comment]
Redirect everything from a hostname -- this is the simple case for this ticket:
```
  if($_SERVER['HTTP_HOST'] == 'old.domain.com') {
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://new.domain.com/');
  }
  ```
  
  Redirect a `/requested/path`:
  ```
  if($_SERVER["REQUEST_URI"] == '/old/path') {
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: /new/path/');
  }
  ```
  
The example in the ticket description uses regular expressions to match a pattern and redirect based on that pattern.. this specific code redirects `live-*.pantheonsite.io` to `www.*.com`:
```
if (preg_match('/^live-(.+)\.pantheonsite\.io$/', $_SERVER["HTTP_HOST"], $matches)) {
    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://www.' . $matches[1] . '.com/');
}
```
