### ISSUE TITLE
Making a cURL request using http_build_query

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#676]
### Scenario:  
Making a cURL request to a remote API when using http_build_query does not return expected response.

### Possible solution:

If using http_build_query, explicitly separate parameters with "&" 

```
 $params = http_build_query($params, null, '&'); 
```
Or change the default value by adding the following line to `settings.php` or `wp-config.php`

```ini_set('arg_separator.output', '&'); ``` 

Details From Sprintly Card:

Customers are having issues with arg_separator.output being set to ```&amp;```
instead of &

It seems like this was required by Drupal 6, but not D7/D8: 
https://www.drupal.org/node/2476057#comment-985677... Might auger for 
different INIs for different frameworks or products.

Symptoms:

cURL requests do not return expected response

Known Workarounds:

Add ```ini_set('arg_separator.output', '&');``` to settings.php

**Comment by nataliejeremy** [comment]
@ari-gold Can you add a link to the doc you want updated?

**Comment by ari-gold** [comment]
@nataliejeremy I think it's a new doc. Wondering if'd make sense to have a series of short problem/solutions like this one, maybe like our internal Customer Success Playbook?

**Comment by nataliejeremy** [comment]
@ari-gold Until we have something like that, would it make sense to add this as an FAQ to these two docs? 
https://pantheon.io/docs/articles/drupal/configuring-settings-php/ and https://pantheon.io/docs/articles/wordpress/configuring-wp-config-php/

**Comment by ari-gold** [comment]
@nataliejeremy Good question, but no, not really relevant to those docs. I think this might be fixed in the platform and make it so we don't need this doc, which would probably be preferable. 

See https://groups.google.com/a/pantheon.io/forum/#!topic/power-users/z86bbcoUvtQ

**Comment by ari-gold** [comment]
@nataliejeremy Maybe the settings.php and wp-config.php docs could have a more general note about ini_set()?  @timani what do you think?
