### ISSUE TITLE
Apache Solr for Drupal Doc Update 

### ISSUE THREAD

**Issue by jahzlariosa** [pantheon-systems/documentation#6817]
Re: [Apache Solr for Drupal](https://pantheon.io/docs//guides/solr-drupal/solr-drupal-9)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Customers are getting this error when merging a multidev that is already in d9 to dev master that is still on d8

Error

“Requested search version 8 is not compatible with your framework and version: Drupal 8.9.19” 

## Suggested Resolution

- Customer will have to remove solr8 first and merge the multidev to dev to upgrade it first to d9
- Re-add solr 8 to multidev and merge again (optional add solr 8 to dev directly)

**Comment by joa-pan** [comment]
https://getpantheon.atlassian.net/browse/BUGS-4235 resolve this issue for now
