### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site Doc Update 

### ISSUE THREAD

**Issue by jahzlariosa** [pantheon-systems/documentation#6834]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs//guides/composer-convert)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Typo Error under **Add Upgrade Status Module**

`$ composer require drupal/upgrade-status
`
## Suggested Resolution

Should be using underscore

`$ composer require drupal/upgrade_status
`

**Comment by carolyn-shannon** [comment]
@joa-pan Please assign a priority and move from the inbox. Thanks!
