### ISSUE TITLE
Migrate to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by Matt-B50** [pantheon-systems/documentation#6849]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Low

## Issue Description:
I cannot upgrade to Drupal 9 from a composer manager Drupal 8.9 site on Pantheon.  When I enter `composer update drupal/core* -W` I get the following error messages:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush is locked to version 10.6.1 and an update of this package was not requested.
    - drupal/core-recommended[9.2.0-beta1, ..., 9.2.0-beta3] require symfony/process v4.4.22 -> satisfiable by symfony/process[v4.4.22].
    - Conclusion: don't install symfony/process v4.4.22 (conflict analysis result)
    - drupal/core-recommended[9.2.0-rc1, ..., 9.2.x-dev] require symfony/process v4.4.25 -> satisfiable by symfony/process[v4.4.25].
    - Conclusion: don't install symfony/process v4.4.25 (conflict analysis result)
    - drush/drush 10.6.1 requires consolidation/site-process ^2.1 || ^4 -> satisfiable by consolidation/site-process[2.1.0].
    - drupal/core-recommended[9.3.0-alpha1, ..., 9.4.x-dev] require symfony/process v4.4.30 -> satisfiable by symfony/process[v4.4.30].
    - Conclusion: don't install symfony/process v4.4.30 (conflict analysis result)
    - consolidation/site-process 2.1.0 requires symfony/process ^3.4 -> satisfiable by symfony/process[v3.4.0-BETA1, ..., 3.4.x-dev].
    - You can only install one version of a package, so only one of these can be installed: symfony/process[v2.1.0, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev].
    - drupal/core-recommended 9.2.0-alpha1 requires symfony/process v4.4.20 -> satisfiable by symfony/process[v4.4.20].
    - Root composer.json requires drupal/core-recommended ^9.2 -> satisfiable by drupal/core-recommended[9.2.0-alpha1, ..., 9.4.x-dev].`

## Suggested Resolution
Just do `composer update` instead?  I ran `composer update drupal/core* -W` afterwards but there was nothing then to update.  Alternatively advise runnning `composer update` should there be an error message.

**Comment by EdwardAngert** [comment]
@namespacebrian can you help us confirm/validate this, please?

**Comment by namespacebrian** [comment]
I use a pretty iterative and interactive process when appeasing composer, so it's hard to speak definitively without interacting directly with the codebase (at least the `composer.json`), but I have found that sometimes composer needs you to list `drush/drush` for upgrade, even when drush doesn't actually need to be updated.  I don't know why it does this, but it does.

@Matt-B50 could you try `composer update drupal/core* drush/drush -W` to see if it helps?  If you're still stuck, would you be able to share your `composer.json`, or at least a pruned version of it which exhibits the same problems you're having?

Note that, while I think some people may have functional sites which require both `drupal/core` and `drupal/core-recommended`, this is not the intended approach.  The expectation is that people's sites will be requiring only one or the other, and preferably `drupal/core-recommended`.

I do have a task for documenting ways to appease composer when it complains about things like this and it's competing with other tasks for priority.

**Comment by Matt-B50** [comment]
@namespacebrian thank you - I do apprecitate just how tricky it is to appease composer!  Just `composer update` allowed me to move on and I now have a working D9 site.  I just ran `composer update drupal/core* -W` again and it's running fine.

I guess if your documentation on appeasing composer would help here (once it is done) it would be worth linking to it for troubleshooting in this doc?
