### ISSUE TITLE
Debugging Sites with Log Files - add a warning message about Varnish logs not being available

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#685]
Under the section `Raw Webserver Log Files` a message such as

*Warning*
Varnish logs are not available for download.

https://pantheon.io/docs/articles/sites/debugging-sites-with-log-files/#raw-webserver-log-files

**Comment by ari-gold** [comment]
@alexdicianu Looks like a good note to add to the page, but Varnish isn't technically a web server, so not sure it belongs in that section?

**Comment by ari-gold** [comment]
@alexdicianu @rachelwhitton What about adding it to the FAQ?

**Comment by nataliejeremy** [comment]
+1 @ari-gold I'll make that change.
