### ISSUE TITLE
Provisioning HTTPS with TXT records updates

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#6852]
Re: [Launch Essentials](https://pantheon.io/docs//guides/launch/domains/)

Priority: Medium

## Issue Description:

Pre-provisioning HTTPS using a DNS TXT record is now doable through the Dashboard and does not necessitate the Terminus plugin any longer. The content in the blue "Note" box should perhaps be updated to reflect this.

It would be helpful to document how long the TXT values are valid for. It seems like it's less than 3 days? (I see different TXT values today, 11/5/21, than what I saw on 11/3/21 when I added my domains). This is tricky to deal with when you're passing these values over to a client (who then passes them over to an IT team) to change, so clarity on this would be much appreciated.

## Suggested Resolution

- Note that you can get DNS TXT records on the Dashboard now
- Note how long they're valid for

**Comment by joa-pan** [comment]
Hi @sarahg 👋  Good to see you 🥳

**Comment by sarahg** [comment]
Haha hey hey @joa-pan! I did a little research on this and I think these ACME challenge records might be valid for 7 days, if we're just going with whatever LetsEncrypt provides: https://community.letsencrypt.org/t/time-of-life-dns-txt-record/114508/6

However I definitely see different values on the Dashboard after only 2 days. Unsure if the records I passed over to my client on Wednesday are still going to work or not.

**Comment by sarahg** [comment]
After talking to @dficker via a support ticket, we found that the TXT records my client had put in place on Nov 3 were incorrect. Maybe this misconfiguration caused the values to change, even if they weren't expired? Still unsure what the expected behavior would be here.

If this is working as designed, I think it'd be worth documenting that a misconfiguration invalidates these (no second chances!), and this can be why the recommended values change unexpectedly. Unlike your A/AAAA records, the Dashboard does not provide any feedback on whether or not you got these right.
