### ISSUE TITLE
rsync and SFTP Doc Enhancement 

### ISSUE THREAD

**Issue by CFin86** [pantheon-systems/documentation#6858]
Re: [rsync and SFTP](https://pantheon.io/docs/rsync-and-sftp)

Priority: Low

## Issue Description:
In the section [Upload a Directory to Pantheon](https://pantheon.io/docs/rsync-and-sftp#upload-a-directory-to-pantheon) it would be beneficial to include a section on how to upload a directory but not overwrite the existing files. This greatly speeds up the file uploading process.

From the rsync man pages: 
https://linux.die.net/man/1/rsync#:~:text=--ignore-existing%20%20%20%20%20%20%20skip%20updating%20files%20that%20exist%20on%20receiver

## Suggested Resolution

`rsync --ignore-existing -rLvz --size-only --checksum --ipv4 --progress -e 'ssh -p 2222' ~/files/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:files/`

is the same as the example command but with the `--ignore-existing` addition

**Comment by EdwardAngert** [comment]
docs: suggest this as the default, and add that `--ignore-existing` as a "if you're migrating a site or somehow otherwise overwrite existing, leave it out"

**Comment by CFin86** [comment]
@EdwardAngert Hey, that's an even better idea!
