### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#6867]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/drush)

Priority: Low

## Issue Description:
Document mentions that php-eval is disabled, it does work however there are issues with sending special characters that engineering needs to resolve before it can be advertised. 

## Suggested Resolution
Follow up with Greg for product status

**Comment by EdwardAngert** [comment]
tagging this as Ready for Work, but we should:
1. get the associated jira ticket (and see what the changes actually are/when they're expected)
2. make the edits where we need to
3. wait until the feature is definitely live on the platform before merging

**Comment by jms-pantheon** [comment]
Looks like this was just merged in, not sure if it is deployed yet

https://github.com/pantheon-systems/pantheon-sshd/pull/78

https://getpantheon.atlassian.net/browse/BUGS-3343

The only change to this doc be to remove this whole section:
Execute PHP Code Using Drush on Pantheon

I haven't searched around to see if `php-eval` or `eval` or `ev` is mentioned as prohibited elsewhere.

**Comment by jms-pantheon** [comment]
New code has been rolled out
