### ISSUE TITLE
Pantheon Workflow documentation is incomplete wrt deploying code to live and caching

### ISSUE THREAD

**Issue by ajbarry** [pantheon-systems/documentation#688]
The following documentation suggests that all code changes are immediately available when deploying from test to live. While the code may be updated, static assets such as images and css may still be outdated due to caching rules. Suggest adding instructions or links on how to mange the cache for live sites.

https://pantheon.io/docs/articles/sites/code/using-the-pantheon-workflow/#3.-deploy-code-to-live

> Deploy code to Live
> After testing your changes, you can take them live. Deploying code from Test to Live will immediately update your live website.

**Comment by nataliejeremy** [comment]
@ajbarry would a link to this doc work? https://pantheon.io/docs/articles/sites/varnish/debugging-cache/
