### ISSUE TITLE
Compare "Migrate to Drupal 9" Doc with drupal.org version 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6881]
Re: [Migrate to Drupal 9](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Low

## Issue Description:

A community member was having trouble getting Composer to work using the steps in the above doc. I pointed him at the [drupal.org version](https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-to-drupal-9-or-later) and he said it worked.

## Suggested Resolution

Not sure what the difference was in his case, but perhaps we could review the drupal.org steps and compare to ours and see if we can make any adjustments.

**Comment by joa-pan** [comment]
Thanks @greg-1-anderson. This is mentioned in a previous issue. Closing in favor of #6849 .
