### ISSUE TITLE
WordPress Site Networks Doc Update add guidelines in the wp-config if customers will be using custom domains instead of platform domain

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#6931]
Re: [WordPress Site Networks](https://pantheon.io/docs//guides/multisite/config/)

dd guidelines in the wp-config if customers will be using custom domains instead of platform domain

Priority: Low

## Issue Description:
Sometimes users may overlook or forget to change it later on when they use the custom domains that they need to change this in their config if using custom domains
<img width="649" alt="Screen Shot 2021-12-16 at 3 13 31 PM" src="https://user-images.githubusercontent.com/5098765/146324929-4df6919f-c3c8-48f9-925c-bbdbb36e9c2c.png">

## Suggested Resolution
Add a reminder or clarification in that section to better guide customers

**Comment by carl-alberto** [comment]
Sorry @joa-pan @michellecolon-pantheon as I may not been clear with the resolution on this issue, for subdomain sites

Instead of using `define( 'DOMAIN_CURRENT_SITE', 'live-<site>.pantheonsite.io' );` it would be  `define( 'DOMAIN_CURRENT_SITE', $_SERVER['HTTP_HOST'] );` so would be asking for another WP SME for another validation as I may not have enough time to fully test this

**Comment by hckia** [comment]
@joa-pan @carl-alberto $_SERVER['HTTP_HOST'] seems to correctly identify the primary domain on different environments. So it likely would work, in fact as @jocastaneda pointed out it might be able to replace the entire switch case, but that doesn't mean we should do it. As Jordan pointed out it's standard practice to hardcode this, but the only legitimate reason I can think of as to WHY it is hardcoded is for troubleshooting purposes. After a clone/migration if the search-replace failed "grep DOMAIN wp-confg*" can clue the troubleshooter in as to what the primary domain was/should be. Still, for our purposes it may be the right call, so I am setting aside some time to test this later today.

**Comment by joa-pan** [comment]
Thank you so much @hckia @jocastaneda @jms-pantheon

**Comment by joa-pan** [comment]
Hi @hckia! Is this technically correct?

**Comment by hckia** [comment]
@joa-pan apologies for the delay here. Tested on a subdomain and subdirectory multisites. works just fine.
