### ISSUE TITLE
Pantheon Localdev Doc Update 

### ISSUE THREAD

**Issue by XjSv** [pantheon-systems/documentation#6933]
Re: [Pantheon Localdev](https://pantheon.io/docs//guides/localdev/changelog)

Priority: Low

## Issue Description
There is no change log for the edge channel updates. It would be helpful to know what is the latest supported docker version and what has changed.

## Suggested Resolution
Include the change log for the edge channel updates.

**Comment by EdwardAngert** [comment]
thanks, @XjSv !
this is a long-standing issue that we're trying to work on as part of a larger improvement to the docs site

closing this issue for now as a duplicate of #6380
