### ISSUE TITLE
Terminus Manual Doc Update out of sync from https://github.com/pantheon-systems/terminus/releases

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#7034]
Re: [Terminus Manual](https://pantheon.io/docs//terminus/updates)

Priority: Low

This part of the doc seems to be out of sync from the release page of Terminus https://github.com/pantheon-systems/terminus/releases

## Suggested Resolution

**Comment by EdwardAngert** [comment]
closed by #7043
