### ISSUE TITLE
Migrate to Drupal 9 on Pantheon Doc Update 

### ISSUE THREAD

**Issue by ersonnogot** [pantheon-systems/documentation#7084]
Re: [Migrate to Drupal 9 on Pantheon](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Medium

## Issue Description:
Missing colon in "[Set Drupal Core Version](https://pantheon.io/docs/guides/drupal-9-migration/upgrade-to-d9#set-drupal-core-version)'s" Composer command. This makes following the doc returns a Composer error.
## Suggested Resolution
Add a colon changing the command from:
`composer require --update-with-dependencies --no-update 'drupal/core-recommended:^9' 'drupal/core-composer-scaffold^9'`
to this:
`composer require --update-with-dependencies --no-update 'drupal/core-recommended:^9' 'drupal/core-composer-scaffold:^9'`

**Comment by joa-pan** [comment]
Thanks @ersonnogot. I think [PR 7085](https://github.com/pantheon-systems/documentation/pull/7085) resolves the issue.
