### ISSUE TITLE
Document best practices for configuration management and content staging in relation to the Pantheon Workflow

### ISSUE THREAD

**Issue by suzannealdrich** [pantheon-systems/documentation#711]
connects to #569

There are two directions to the Pantheon workflow. Code moves up from dev->test->live, and Content for launched sites move down from live->test->dev. When content is cloned, it overwrites the content in the destination, so you normally wouldn't want to clone a development database to a live production environment.

The Pantheon workflow accommodates the simple general workflow of deploying code changes. To add configuration change management or content staging to your development workflow will require a little more work on your part, since you’ll need to think through the problem as it relates to the specific development use case for a project. We have some documentation on this subject specifically:

https://pantheon.io/docs/articles/sites/code/using-the-pantheon-workflow/#handling-configuration-changes

While we can’t make specific recommendations, we can give general best practices for configuration management and content staging. This is a very common issue for which many strategies and workarounds exist. Since Drupal 6 & 7, and WordPress store all content and configuration in the database, it can be difficult to version control.

Here are the existing best practices and projects developed by the Drupal community for configuration management and content staging:

Configuration management:
Configuration (backport of Drupal 8 CMI) – https://www.drupal.org/project/configuration
Exportables (Ctools) – https://drupal.org/project/ctools
Features – https://drupal.org/project/features

Content staging:
Feeds – https://drupal.org/project/feeds
Migrate – https://drupal.org/project/migrate

You can find more information on these projects and configuration management at Drupal.org and other community resources:

Comparison of staging and deployment modules – https://drupal.org/node/980186
Newest ‘configuration-management’ Questions – Drupal Answers – http://drupal.stackexchange.com/questions/tagged/configuration-management

For WordPress, we suggest checking out how to use Advanced Custom Field Exports, and the WP-CFM plugin:

Using WordPress Advanced Custom Fields Exports - https://stevegrunwell.com/blog/exploring-the-wordpress-advanced-custom-fields-export-feature/
WP-CFM plugin - https://wordpress.org/plugins/wp-cfm/

**Comment by bmackinney** [comment]
connects to #568

**Comment by allenfear** [comment]
This is covered in the Workflow,WP-CFM doc and the D8 config management docs:
https://pantheon.io/docs/pantheon-workflow/#configuration-management
https://pantheon.io/docs/drupal-8-configuration-management/
https://pantheon.io/docs/wp-cfm/
