### ISSUE TITLE
Clarify usage of command line interface to generate certificate signing requests

### ISSUE THREAD

**Issue by suzannealdrich** [pantheon-systems/documentation#712]
On Pantheon, adding SSL to your site is a completely self-serve option; Pantheon does not provide Private Keys or CSRs, or any SSH login for you to generate these. The key and certificates are cryptographically sensitive elements which you should take care to not send through email, as cleartext is very insecure.

Instead, we provide instructions for how to perform these steps yourself, and input into the form on the Domains/SSL tool in the site dashboard. The wizard you used generated the necessary command-line you’ll need to input into a Terminal:

```
openssl req -new -newkey rsa:2048 -nodes -out www_mysite_com.csr -keyout www_mysite_com.key -subj "/C=US/ST=California/L=San Francisco/O=MySite LLC/CN=www.mysite.com"
```

If you're using Mac OS X, you can open your Mac's Terminal application by going to Applications | Utilities | Terminal or using Spotlight to search. Sometimes this program is stored directly in Applications. Once you launch, you'll be presented with a window where you can directly paste that command.

Once you've generated the CSR and Key, you can find the files to provide to your certificate provider.

After receiving your signed certificate and any intermediary certificates you'll need to paste the contents in the SSL tool on the Pantheon dashboard.

**Comment by ari-gold** [comment]
@nataliejeremy 

I don't know if we need all of this added to docs. I think https://pantheon.io/docs/articles/sites/domains/adding-a-ssl-certificate-for-secure-https-communication/ is pretty comprehensive.

But the paragraph: "If you're using Mac OS X...:" would make a good new doc, "Working with Terminal in Mac OS X" and then we could have a callout/link to that article where appropriate, like from the generating CSR section of the SSL doc.

**Comment by nataliejeremy** [comment]
@ari-gold I took some of it, and changed the CL instructions. https://github.com/pantheon-systems/documentation/pull/719/files

**Comment by nataliejeremy** [comment]
@ari-gold Thanks. Looks like it's not needed so I'll close the PR.
