### ISSUE TITLE
Migrate to Drupal 9 on Pantheon Doc Update 

### ISSUE THREAD

**Issue by Exemplify-Dan** [pantheon-systems/documentation#7127]
Re: [Migrate to Drupal 9 on Pantheon](https://pantheon.io/docs//guides/drupal-9-migration/upgrade-to-d9)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Edit (from Exemplify-Dan): This is the simplest way to install the plugin:

terminus self:plugin:install pantheon-systems/terminus-site-clone-plugin

## Suggested Resolution

**Comment by whitneymeredith** [comment]
@Exemplify-Dan Thanks for creating this issue! Can you provide some additional detail? What update would you like to see made to the doc?
