### ISSUE TITLE
Integrated Composer Docs Page Infinite Redirect Loop

### ISSUE THREAD

**Issue by rvtraveller** [pantheon-systems/documentation#7174]
The Integrated Composer is in an infinite redirect loop switching between a URL that ends with a / and a URL that does not.

## Expected behavior
* I can load https://pantheon.io/docs/integrated-composer/

## Actual behavior
* I get redirected back and forth between https://pantheon.io/docs/integrated-composer/ and https://pantheon.io/docs/integrated-composer

### Steps to reproduce the problem

1. Navigate to main docs page (https://pantheon.io/docs/)
2. In the search bar, type "Integrated Composer"
3. Select the "Integrated Composer" option in the auto-suggest

Alternatively, here is a curl command that also reproduces the issue: `curl -I https://pantheon.io/docs/integrated-composer`

## Suggested Resolution
*

## Additional information

```
$ curl -I https://pantheon.io/docs/integrated-composer
HTTP/2 301 
content-type: text/html
location: https://pantheon.io/docs/integrated-composer/
server: nginx
strict-transport-security: max-age=31622400
traceparent: 00-523faeeb7b664a4290b94ecb82ecd60e-ab8ae5e4528a4e56-00
x-cloud-trace-context: 523faeeb7b664a4290b94ecb82ecd60e/12360944896071847510;o=0
x-pantheon-styx-hostname: styx-fe2-a-854c9bcdfb-956mp
x-styx-req-id: 3ceadd31-a5d5-11ec-8683-6e19aa217a0b
cache-control: public, max-age=86400
date: Thu, 17 Mar 2022 17:14:42 GMT
x-served-by: cache-mdw17327-MDW, cache-mia11330-MIA
x-cache: HIT, HIT
x-cache-hits: 1, 1
x-timer: S1647537283.761651,VS0,VE1
vary: Cookie, Cookie
age: 27702
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
content-length: 162

```

```
$ curl -I https://pantheon.io/docs/integrated-composer/
HTTP/2 301 
cache-control: no-cache, must-revalidate
content-type: text/html; charset=UTF-8
expires: Sun, 19 Nov 1978 05:00:00 GMT
location: https://pantheon.io/docs/integrated-composer
server: nginx
strict-transport-security: max-age=31622400
traceparent: 00-86b9c760e2f640319e3e84026fbfea6f-4c23b9894b1a3cf2-00
x-cloud-trace-context: 86b9c760e2f640319e3e84026fbfea6f/5486432770389064946;o=0
x-content-type-options: nosniff
x-drupal-cache: MISS
x-pantheon-styx-hostname: styx-fe2-b-f66bf767-tmrbw
x-styx-req-id: b50353bc-a615-11ec-b140-f600ebb86140
date: Thu, 17 Mar 2022 17:14:30 GMT
x-served-by: cache-mdw17378-MDW, cache-mia11369-MIA
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1647537270.284583,VS0,VE65
vary: Cookie, Cookie
age: 0
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
content-length: 0
```

**Comment by EdwardAngert** [comment]
thanks, @rvtraveller ! you caught that doc [right after it moved](https://github.com/pantheon-systems/documentation/pull/7102/files#diff-58fb7662b4d5e22532d9acfb2ed1bb1b484dd04ca203afc7fb8c389b8351ed43) and before we'd set the redirect
we're still battling some redirect issues with the site (like the loop to add/remove the trailing `/`), but that one _should_ go to the right place now
let us know if it doesn't
