### ISSUE TITLE
Use the Pantheon WebOps Workflow Doc Update 

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#7179]
Re: [Use the Pantheon WebOps Workflow](https://pantheon.io/docs/pantheon-workflow)

Priority: Low

## Issue Description:
Workflow logs history gets deleted after an amount of time. [BUGS-4154](https://getpantheon.atlassian.net/browse/BUGS-4154)

## Suggested Resolution
Add information somewhere in the documentation about how long we keep workflow logs.

For example:

"These workflow logs are deleted after xxxx timeframe"

**Comment by EdwardAngert** [comment]
thanks @umandalroald ! 
Do you know what that timeframe is or where we'd locate it?

**Comment by umandalroald** [comment]
I will DM you the info, thank you @EdwardAngert

**Comment by EdwardAngert** [comment]
got it, thanks @umandalroald !

@pantheon-systems/docs-admins : check BUGS-4154 for more information and as a place to find SMEs/collab-ers
