### ISSUE TITLE
WordPress Best Practices Doc Update 

### ISSUE THREAD

**Issue by ersonnogot** [pantheon-systems/documentation#7315]
Re: [WordPress Best Practices](https://pantheon.io/docs/wordpress-best-practices)

Priority: Low

## Suggested Resolution
Not really a resolution but we just want to check if we are still good at recommending this plugin since we just noticed a site that uses this which caused the container size to go bloated. Right now it's been mitigated but we just want to check if we are still clear to suggest this one. Would love to paste the ticket but it's internal, please let me know if you would like to check.

**Comment by whitneymeredith** [comment]
After discussing this with Erson, I'm removing the reference to GD Security since at least one customer has experienced severe performance problems using it. Erson will let us know if more customers report a problem with this plugin so we can add it to the list of plugins with known issues.
