### ISSUE TITLE
Deliver Email Through Your Drupal Site on the Pantheon Platform Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#7317]
Re: [Deliver Email Through Your Drupal Site on the Pantheon Platform](https://pantheon.io/docs//guides/sendgrid)

Priority: Low 

## Issue Description:
Missing final installation/configuration instruction for Drupal sites

## Suggested Resolution
After step 3 in this section: https://pantheon.io/docs/guides/sendgrid#integrating-sendgrid-with-drupal 
There needs to be another step to set the System-wide default MailSystemInterface class to "SendGridMailSystem".

https://www.drupal.org/files/issues/sengrid-integration-mailsystem-settings-example.png

See module README for confirmation

**Comment by joa-pan** [comment]
Hi @rachelwhitton does the theme that will have to be used for render, also need to be added to our proc?
