### ISSUE TITLE
Generate and Add SSH Keys Doc Update 

### ISSUE THREAD

**Issue by fewd555** [pantheon-systems/documentation#7325]
Re: [Generate and Add SSH Keys](https://pantheon.io/docs/ssh-keys)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution Update step 3 to advise users on Windows to use the "cat ~/.ssh/id_rsa.pub" command.

**Comment by joa-pan** [comment]
Hi @fewd555. Thank you for submitting this issue. May I ask if you are using the Windows Powershell or the terminal in Windows?  The `cat` command works in the terminal, but `type` works in the Powershell. I think `type` is the Windows Powershell equivalent of `cat`. I have run the commands and the `type` command appears to work.

**Comment by joa-pan** [comment]
Closing this as the procedure appears to be correct as is.
