### ISSUE TITLE
Drupal Multi-site setup manually migrating.

### ISSUE THREAD

**Issue by v0jpantheon** [pantheon-systems/documentation#7332]
Re: [Manually Migrate Sites to Pantheon](https://pantheon.io/docs/migrate-manual)

Someone just had problems with manually migrating to pantheon using multi-site. We may need an additional section if you're setup is multi-site (trying to migrate one of the sites within multi-site) to Pantheon.

We may need instructions on how to make one of their multisite compatible with the Pantheon by doing:

Drupal 7 specific:
1. Copy base site to a new directory.
2. Delete ALL sites/* EXCEPT for

- `sites/{sitename}` (to be renamed to `sites/default`) -> the site they are trying to migrate
- `sites/all` -> where all modules and themes.

3. Rename `sites/{sitename}` -> to `sites/default`.
4. Extract database. (this may need a separate topic altogether)

I'll make a PR about this soon.

**Comment by wordsmither** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Drupal Multi-site setup manually migrating. #7332](https://trello.com/c/YfRoKY8e/39-drupal-multi-site-setup-manually-migrating-7332)

**Comment by wordsmither** [comment]
@v0jpantheon - at what part in the process should the user perform these steps?

**Comment by v0jpantheon** [comment]
Hi @wordsmither ,

This should be part of the preparation work. So essentially this step is converting one of their site in multi-site to just a regular Drupal site. Then they can proceed with other steps as a regular Drupal 7 site migrating to Pantheon.

**Comment by v0jpantheon** [comment]
It would be something like this:

This highly depends on how the sub-site was set up, and how it shares the database tables with the other sites. Sometimes they can share standard tables such as users and nodes but has separate themes and settings.

They can start looking at settings.php:

```
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'database2',
      'username' => 'root',
      'password' => 'root',
      'host' => '127.0.0.1',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => array (
        'default'      => '',
        'users'        => 'database1.',
        'sessions'     => 'database1.',
        'role'         => 'database1.',
        'authmap'      => 'database1.',
        'block_role'      => 'database1.',
        'role_permission' => 'database1.',
        'users_roles'     => 'database1.',
      ),
    ),
  ),
);
```

In the example above, there is a prefix on some table names. These prefixes are used to share the tables with other sub-sites.

If their setup is similar to this, they have to extract all the tables that the subsites use, including the shared ones. Then all the table prefixes should be removed and just be normal table names.

After renaming, it will just be a regular drupal database ready for migrating to Pantheon. Then they can follow the one you sent:  https://pantheon.io/docs/local-development#get-the-database
