### ISSUE TITLE
How to Remove Multidev App Servers from New Relic 

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#738]
Our New Relic doc should include how to remove multidev environments from a site in NR. The Apps are added automatically, but after deletion, need to be removed in NR manually. 
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/remove-applications-servers
<img width="421" alt="remove-nr-app" src="https://cloud.githubusercontent.com/assets/646061/8807598/799a02f0-2f92-11e5-9442-830d33e938d5.png">

**Comment by nataliejeremy** [comment]
@bmackinney You want it added to this doc? https://pantheon.io/docs/articles/sites/newrelic/

**Comment by bmackinney** [comment]
Yes.
