### ISSUE TITLE
Apache Solr for Drupal Doc Update 

### ISSUE THREAD

**Issue by joshuami** [pantheon-systems/documentation#7396]
Re: [Apache Solr for Drupal](https://pantheon.io/docs//guides/solr-drupal/solr-drupal-9)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

When implementing Search API Pantheon, our team was working from a local environment where we gave the server instance the machine name of "pantheon". There are hardcoded references to the "DEFAULT_ENVIRONMENT" in the timeout logic that expects the machine name to be "pantheon_solr8". If it is named anything else, when a timeout is triggered, an error is generated that makes viewing or editing the index unavailable. Documented in the following D.o issue: https://www.drupal.org/project/search_api_pantheon/issues/3277226

## Suggested Resolution

Ideally, we could name our Solr server anything we want, but short of that, it might help others that run into this same issue to make it explicit in this documentation that the Solr server must have the machine name pantheon_solr8.

**Comment by stevector** [comment]
Looks like this issue should have been closed with the merging of #7438
