### ISSUE TITLE
Clarify config management notes for Drupal for WebOps Workflow

### ISSUE THREAD

**Issue by joa-pan** [pantheon-systems/documentation#7406]
## Expected behavior
*  Version specific information is provided for the the config management notes for Drupal in [Use the Pantheon WebOps Workflow](https://pantheon.io/docs/pantheon-workflow#drupal)

## Actual behavior
* The config management notes for [Use the Pantheon WebOps Workflow](https://pantheon.io/docs/pantheon-workflow#drupal) refer to using update hooks or features.
It is unclear whether we were advocating using this over config sync (import/export) for D9 / D8 sites. The docs don't mention a version, and I'm guessing we'd want them to describe the process for the latest version anyway.

## Suggested Resolution
* We should clarify with version-specific information and most likely describe the process for the latest version. 
* Update information on automating Drupal site updates with a deployment module, if needed for D9

## Additional information
* [Slack thread](https://pantheon.slack.com/archives/C03SU7UCJ/p1654685812002509)

**Comment by EdwardAngert** [comment]
@wordsmither this might be relevant to the Drupal cross-linking adventure you're on

**Comment by wordsmither** [comment]
It does not appear to be related to the cross-linking project.  Unassigning myself for now.
