### ISSUE TITLE
Yoast SEO: WordPress Plugins and Themes with Known Issues Doc Update 

### ISSUE THREAD

**Issue by ryanshoover** [pantheon-systems/documentation#7423]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues#yoast-seo)

Priority: Medium

## Issue Description:

On very large sites, Yoast will cause performance issues when it tries to create its "indexables" and populate the `wp_yoast_indexables` table.

## Suggested Resolution

On very large sites, they may be able to add `add_filter( 'Yoast\WP\SEO\should_index_indexables', '__return_false' );`
On extremely large sites, Professional Services has a tool that can help index.

**Comment by joa-pan** [comment]
This is closed by https://github.com/pantheon-systems/documentation/pull/7427
