### ISSUE TITLE
Object Cache (formerly Redis) Doc Update 

### ISSUE THREAD

**Issue by khairulanam-pantheon** [pantheon-systems/documentation#7477]
Re: [Object Cache (formerly Redis)](https://pantheon.io/docs/object-cache)

Priority: Medium 

## Issue Description:
Running the following command are not working on the Redis server directly:
--stat, and --bigkeys 

Steps to reproduce the issue:
1. Connect the Redis server via SSH
2. Run the above commands.

Is there anything else I skip or do we have to follow any extra steps like installing Redis on my local?

![image](https://user-images.githubusercontent.com/78079262/177219436-710f0d65-a2f3-4b8e-9a2c-e389083f439d.png)

## Suggested Resolution

**Comment by jms-pantheon** [comment]
Hey @khairulanam-pantheon can you elaborate a bit on what the objective is here? I don't believe this is a docs issue but more a question of how these commands are to used. While these are some useful tools, I'm not sure that it falls on Pantheon to document them as they are specific to Redis CLI and not Pantheon.

The `--stat` command is not meant to be ran as a command within the CLI, but as a flag to modify its behavior when calling the redis-cli:
![image](https://user-images.githubusercontent.com/91161717/177830594-efbc1e98-633b-4b5d-9099-9828e949f8b7.png)
https://redis.io/docs/manual/cli/#continuous-stats-mode

The same is true for `--bigkeys`
![image](https://user-images.githubusercontent.com/91161717/177831033-818f37f2-8cf8-41d1-b9c0-34806e577bd0.png)
https://redis.io/docs/manual/cli/#scanning-for-big-keys

**Comment by jms-pantheon** [comment]
Sorry I should have read closer, I see now that there are screenshots showing that this used to work on Redis, those should be updated. I can do that work!
