### ISSUE TITLE
[CMS-125] Manually Migrate Sites to Pantheon Doc Update 

### ISSUE THREAD

**Issue by rwagner00** [pantheon-systems/documentation#7506]
Re: [Manually Migrate Sites to Pantheon](https://pantheon.io/docs/migrate-manual)

Priority: Medium

## Issue Description:

We've added the ability to use `drush archive-dump` and Terminus to import sites to Pantheon, and the steps need to be documented here.

### Setup
* Ensure that you have Terminus 3 installed on your local system: https://pantheon.io/docs/terminus/install
* Install Terminus Conversion Tools plugin: https://github.com/pantheon-systems/terminus-conversion-tools-plugin#installation
* Install Drush 11.1.1 or higher: https://www.drush.org/latest/install/

### Dump Site
* In your local site directory, run `drush archive:dump` to create an `archive.tar.gz` file which is a backup of your site

### Import 
* To create the site on Pantheon, run `terminus conversion:import-site site-machine-name /path/to/archive.tar.gz --site-label="Site Label"`

**Comment by whitneymeredith** [comment]
@greg-1-anderson @rwagner00 This content already exists on the Docs site: https://pantheon.io/docs/drush-import Do we need to update the existing content for improved user experience / functionality?

**Comment by rwagner00** [comment]
@whitneymeredith Yes, specifically it should clarify that for modern versions of Drupal that Drush 11.1.1 or higher will be needed, and that if you're converting from no-composer to composer that the composer tool will be needed.

**Comment by rwagner00** [comment]
@whitneymeredith Update -- It's probably worth leaving these instructions as-is under a Drupal 7/Drupal 8 tab, and then including the new instructions under a Drupal 9/10 tab.

**Comment by whitneymeredith** [comment]
@rwagner00 You can see the new tab here: https://pr-7514--pantheon-docs.my.pantheonfrontend.website/docs/drush-import#import-your-archive
