### ISSUE TITLE
Upgrade PHP Versions Doc PHP 8.1

### ISSUE THREAD

**Issue by whitneymeredith** [pantheon-systems/documentation#7520]
Re: [Upgrade PHP Versions](https://pantheon.io/docs/php-versions)

Priority: Medium

## Issue Description:

The documentation states that New Relic is incompatible with PHP 8.1. This is no longer correct.

## Suggested Resolution
Remove New Relic / PHP 8.1 incompatibility statements for the Docs site.

**Comment by greg-1-anderson** [comment]
Note, however, that there are still problems with mysqlproxy and PHP 8.1, so the docs should not imply that 8.1 is supported yet.

**Comment by whitneymeredith** [comment]
Thanks @greg-1-anderson ! I'll update the docs to simply remove  references that New Relic is incompatible with PHP 8.1

**Comment by greg-1-anderson** [comment]
Welp, the docs have already been updated in a way that implies that the only problems with 8.1 lie with new relic and wordpress; I think that's painting too rosey a picture. IMO, 8.1 should not be advertised as simply "Available". There needs to be some cautionary note.

**Comment by whitneymeredith** [comment]
@greg-1-anderson Are there specific concerns that we should let users know about?

**Comment by greg-1-anderson** [comment]
> There are still problems with mysqlproxy and PHP 8.1.

We're discussing positioning of this right now.
