### ISSUE TITLE
Add image to Using the Pantheon Workflow to show code moves up, content moves down

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#760]
Looks like such an image is in a slide deck that was part of the Agency Summit, so just need to track that down https://pbs.twimg.com/media/CKsVL7GUcAAue17.jpg

**Comment by bmackinney** [comment]
@mishabuggy can you send us the location of all of the great graphics you've been creating, including this one?

**Comment by joshkoenig** [comment]
BAM!

![devtestlive](https://cloud.githubusercontent.com/assets/143186/8914563/e97a4280-3454-11e5-8831-f87f81e788ce.png)

![multidev_features](https://cloud.githubusercontent.com/assets/143186/8914573/f14d3314-3454-11e5-9ce3-8046e3dd3e6a.png)
