### ISSUE TITLE
Add overview to drupal 9 guides

### ISSUE THREAD

**Issue by wordsmither** [pantheon-systems/documentation#7606]
Re: [Migrate a Custom Upstream to Drupal 9](https://pantheon.io/docs/guides/drupal-9-hosted-createcustom) and [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs/guides/composer-convert)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description

Add a summary of the process to be performed.  Bullets below provided by @namespacebrian 

- clone site repo locally
- add the new upstream as a second git remote
- create a new branch based on the new upstream's git history.. the new branch does not share history with the master branch
- create a multidev from that branch
- transplant all the things that make the site unique into the  new branch.. e.g. composer requireing each module/theme/profile/etc...
- ...until the multidev is looking good
- replace master branch with the multidev branch

**Comment by namespacebrian** [comment]
Here's the language that had been used in the D9 custom upstream migration guide: https://github.com/pantheon-systems/documentation/blob/47d9fd0f0d9647bebcf5255286920975153a4e8d/source/content/guides/integrated-composer-convert-custom.md?plain=1#L14

> Working in a new branch, you will replace the entire file structure with the code from Pantheon's Integrated Composer upstream, then re-add your contrib and custom code to the new codebase. Then you will create multidev environments on individual sites for testing and to apply any site-specific code customizations.

would it be reasonable to re-add this language to the "introduction" section of that guide? https://pantheon.io/docs/guides/drupal-9-hosted-createcustom

the language for the regular composer conversion guide would be slightly different.
