### ISSUE TITLE
Remove excess spacing and box at right and bottom of all articles

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#762]
@rachelwhitton @informanddelight I just noticed this bit of funk. 

![image](https://cloud.githubusercontent.com/assets/646061/8915826/21c9ed82-345c-11e5-8f3f-f5d4ef19770e.png)

**Comment by rachelwhitton** [comment]
I'm not seeing the same thing @bmackinney - tested on safari, firefox, and chrome.

**Comment by rachelwhitton** [comment]
The only funk I've noticed is that the breadcrumbs implementation generates an empty div container on the home page, which adds some padding above the search bar. 

Adding it to this issue for future CSS work:

<img width="1210" alt="screen shot 2015-07-28 at 9 37 14 am" src="https://cloud.githubusercontent.com/assets/10119525/8934263/73b0c764-350c-11e5-911e-24fe2f89ab8a.png">

**Comment by bmackinney** [comment]
@rachelwhitton Seems to have resolved for me too.

**Comment by bmackinney** [comment]
Or.. #764 will close this
