### ISSUE TITLE
Permissions documentation page doesn't list what levels of access are needed for uploading files.

### ISSUE THREAD

**Issue by madeline-holland** [pantheon-systems/documentation#7627]
## Expected behavior
* The permissions explanation gives a good overview of what SFTP access to upload files each role has. 

## Actual behavior
* Uploading files isn't mentioned on that page. 

### Steps to reproduce the problem

1. See this [file](documentation/source/content/change-management.md) or [this url](https://pantheon.io/docs/change-management) to see the lack of mention of uploading files. 

## Suggested Resolution
* If access to uploading files (for example to `/files/private` on a site's live environment) does not depend on the level of permissions a user has, or what environment they're pushing to, the documentation should mention that. If it does depend on the user role / permissions / environment, then that should be mentioned too, and put into the tables that already exist. 

## Additional information
We have a site where an account could upload fully to the `dev` environment's `files/private/` directory, but could not do the same for the `live` environment. We're trying to work out if it is a permissions error, and this documentation page doesn't mention it, though it seems like it should.

**Comment by whitneymeredith** [comment]
@madeline-holland Thanks for submitting this! Our section on [Site-Level: Roles and Permissions](https://pantheon.io/docs/change-management#site-level-roles-and-permissions) provides role-based information on who can deploy to Test and Live environments.
