### ISSUE TITLE
WordPress with Composer on Pantheon Doc Update to its own guide?

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#7665]
Re: [WordPress with Composer on Pantheon](https://pantheon.io/docs/guides/wordpress-composer/wordpress-composer-managed)

Priority: Low

## Discuss

From @CdrMarks 

Consider splitting WP Composer Bedrock-specific guide out of the greater WP Composer guide to help focus feedback and conversation from Bedrock Early Access users

options:
- move doc to its own `/docs/guides/wordpress-composer/wordpress-composer-managed` out of the WP Composer guide and into `/docs/wordpress-composer-managed` ?
- redirect `/docs/wordpress-composer-managed` to existing doc?
- make a new subdirectory under the current guide for EA? so `/docs/guides/wordpress-composer/pre-ga/wordpress-composer-managed` so that the doc maintains its relationship, but isn't in the left-hand nav as if its a GA option?

**Comment by CdrMarks** [comment]
@EdwardAngert I'd like to remove the `?` above unless you have other thoughts.

**Comment by EdwardAngert** [comment]
closing

After talking with the team, we're sticking with keeping the WordPress Composer doc where it is to maintain our information architecture efforts and because we don't have a good easy way to make the `pre-ga` subdirectory work well yet

**Comment by EdwardAngert** [comment]
although, now that I've closed this

PR incoming
