### ISSUE TITLE
Legacy Dashboard Doc Update 

### ISSUE THREAD

**Issue by RUANSOUZAF** [pantheon-systems/documentation#7710]
Re: [Legacy Dashboard](https://pantheon.io/docs//guides/legacy-dashboard/create-sites)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by whitneymeredith** [comment]
@RUANSOUZAF Thanks for your contribution! Can you provide more information about the issue you found with this doc?

**Comment by whitneymeredith** [comment]
Closing this due to lack of information.
