### ISSUE TITLE
Symlinks and Assumed Write Access Doc Update 

### ISSUE THREAD

**Issue by SayedTareq** [pantheon-systems/documentation#7754]
Re: [Symlinks and Assumed Write Access](https://pantheon.io/docs/symlinks-assumed-write-access)

Priority: High

## Suggested Resolution

Please check the loom https://www.loom.com/share/b495087b780b466bbaaa9fc32d842d48

The problem is specifically named advanced-cache.php symlink not commit. Please give me the solution for that. I need to commit advanced-cache.php named symlink on the wp-content folder. What is the solution???

**Comment by whitneymeredith** [comment]
@SayedTareq Thanks for reaching out! I see from your Loom video that you are using Windows.  The [Creating a Symbolic Link](https://pantheon.io/docs/symlinks-assumed-write-access#create-a-symbolic-link) section note provides links to assist Windows users in this process: [Start a Command Prompt as an Administrator](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc947813(v=ws.10)?redirectedfrom=MSDN) and [Mklink](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc753194(v=ws.11)?redirectedfrom=MSDN). I also recommend that you review the [Pantheon Filesystem](https://pantheon.io/docs/files) doc for additional information on Symlinks as they relate to the wp-content folder.
