### ISSUE TITLE
Advanced Global CDN Doc Update 

### ISSUE THREAD

**Issue by shelleycabarrubias** [pantheon-systems/documentation#7770]
Re: [Advanced Global CDN](https://pantheon.io/docs//guides/agcdn/agcdn-wafio)

Priority: Medium

## Issue Description: 
Rate Limiting feature availability status is no longer on Early Access. This feature is now fully available as long as customer has WAF/IO

## Suggested Resolution
Early access status for Rate Limiting should be removed.

<img width="617" alt="AGCDN_with_WAF___IO_Features___Advanced_Global_CDN___Pantheon_Docs" src="https://user-images.githubusercontent.com/78002933/194331492-23f33da0-257d-4c8c-8a68-a4c8a83c8de7.png">

**Comment by joa-pan** [comment]
Thank you @shelleycabarrubias . The EA note has been removed
