### ISSUE TITLE
Doc for Using SendGrid has some wrong config in settings.php

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/documentation#780]
Report from client, didn't had the time to test.

=========

Hi folks,
In https://pantheon.io/docs/guides/using-sendgrid-to-deliver-email-with-wordpress-and-drupal/ you added `$conf['smtp_on'] = TRUE;` to the settings.php
However that won't work, as it requires a submit action (see smtp_admin_settings_form_submit)
I'd recommend changing this in your docs, and asking people to click on the submit button.

**Comment by ttrowell** [comment]
Alternate config suggested and tested here:
https://www.drupal.org/node/2548249#comment-10205825

$conf['mail_system']['default-system'] = 'SmtpMailSystem';
