### ISSUE TITLE
New Relic Performance Monitoring on Pantheon Doc Update 

### ISSUE THREAD

**Issue by ericmichalsen** [pantheon-systems/documentation#7829]
Re: [New Relic Performance Monitoring on Pantheon](https://pantheon.io/docs//guides/new-relic/activate-new-relic)

Priority: Medium

## Issue Description:
Activate NR with a UIC that is a distro-list email, not a singular email

## Suggested Resolution
What we (onboarding) have been told is that if the UIC changes to a new user, NR will re-activate to a fresh setup, deleting all previous data and logs.

**Comment by ericmichalsen** [comment]
Out of curiosity I thought I would tested this on a personal site it didn't clear data, as I was told it would ...so, let me table this change until I can get this locked down as myth or real :)

**Comment by whitneymeredith** [comment]
@ericmichalsen Any luck tracking this down?
