### ISSUE TITLE
Cron for WordPress Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#7910]
Re: [Cron for WordPress](https://pantheon.io/docs/wordpress-cron)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

If the site is using Pantheon cron, this command doesn't work, as described on this page:

`terminus` wp site.env -- cron test`

So how can customers test cron is working by running it manually?

## Suggested Resolution

With the help of Engineering, I was able to find that this is the command run at the Pantheon platform level every hour:

`terminus wp site.env -- cron event run --due-now`

When Pantheon runs it, it will only run for 3 minutes and will then be halted. But if customers run this manually, it can run for much longer.

So if we could note the above info on this page somewhere, that would be helpful.

**Comment by whitneymeredith** [comment]
This was addressed in #7908
