### ISSUE TITLE
Autopilot Premium Plugin / Module Support

### ISSUE THREAD

**Issue by ejcabquina** [pantheon-systems/documentation#7934]
Re: [Pantheon Autopilot](https://pantheon.io/docs//guides/autopilot/autopilot-faq/)

Priority: Medium

## Issue Description: 
CSM's outreach for better Autopilot adoption received recurring questions from multiple customers about Autopilot and premium plugins.

## Suggested Resolution

Add the question "Can autopilot work with premium plugins?". Include troubleshooting links containing step-by-step guide as well.

**Comment by whitneymeredith** [comment]
This is documented on [#7941 ](https://github.com/pantheon-systems/documentation/pull/7941)
