### ISSUE TITLE
Pantheon Docs Recommend WordPress/Sendgrid/Swift Mailer Plugin But Those Require PHP Short Tags

### ISSUE THREAD

**Issue by bthompson-mindgrub** [pantheon-systems/documentation#795]
This page of the docs:  https://pantheon.io/docs/guides/using-sendgrid-to-deliver-email-with-wordpress-and-drupal/ recommends using the WordPress Sendgrid plugin and Swift Mailer plugin to send emails using SMTP.  However, the SendGrid Plugin documentation page on WordPress.org (https://wordpress.org/plugins/sendgrid-email-delivery-simplified/) states "After installing 'Swift Mailer' plugin, you must have PHP-short_open_tag setting enabled in your php.ini file." which Pantheon doesn't do.

Seems like we would need to come up with a different recommendation for SMTP email sending on WordPress, right?

**Comment by rachelwhitton** [comment]
Thanks for opening this issue @bthompson-mindgrub! We opened a support topic in the WP repo a while back and the swift mailer plugin was updated so that short tags were not used. We tested and were able to configure SendGrid using SMTP successfully. 

The plugin description is a bit confusing so we've asked that it be updated: https://wordpress.org/support/topic/php-short-tags-to-full-tags

**Comment by bthompson-mindgrub** [comment]
@rachelwhitton Thanks for the quick update Rachel!

In talking with some of the other folks on my end, they pointed out that some of the documentation on the Pantheon page is out of date due to SendGrid updates.  It's outside the scope of this specific issue, but I'll have someone submit a PR next week to take care of that portion of it.  We'll make sure to add a line about short tags not being required, even though the plugin page (currently) says that you need short tags enabled..

**Comment by rachelwhitton** [comment]
Hey @bthompson-mindgrub, just a quick update. The plugin description was updated and no longer references short tags. 

- [Resolved Issue](https://wordpress.org/support/topic/php-short-tags-to-full-tags?replies=8#post-7358568)
- [Plugin Description](https://wordpress.org/plugins/sendgrid-email-delivery-simplified/)

**Comment by rachelwhitton** [comment]
Hey @bthompson-mindgrub are you still planning a Pull Request to update the instructions on this guide to match SendGrids new interface? If not, I can complete the work this week. Thanks!

**Comment by bthompson-mindgrub** [comment]
If all goes according to plan, I'll have one submitted late tonight or tomorrow (Eastern time).

**Comment by bthompson-mindgrub** [comment]
@rachelwhitton PR #893
