### ISSUE TITLE
Migrate a Drupal 8 Site to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#7961]
Re: [Migrate a Drupal 8 Site to Drupal 9](https://pantheon.io/docs//guides/drupal-9-hosted/create-site)

Priority: Medium

## Issue Description:

I see that we set Drupal core to D8 here, but I'm not seeing where we update it to be D9 again

## Suggested Resolution

I was looking for a step later on that would look something like:

```
composer require --no-update drupal/core-recommended:^9.2
composer require --no-update drush/drush:"^11||^12"
composer require --dev drupal/core-dev:^9.2
```

But I do not have a site for testing this whole process on at the moment

**Comment by wordsmither** [comment]
@namespacebrian , @kporras07 , can you confirm that we should add instructions similar to what is proposed to the guide?  I'm assuming if so, we'd add them to the end of this page: https://pantheon.io/docs/guides/drupal-9-hosted/code.

Also, if true, it appears this instruction is missing from all our migration docs, so yea... that's fun.

**Comment by kporras07** [comment]
@wordsmither that's right! It's missing stuff like https://pantheon.io/docs/guides/drupal-9-hosted-md/dependencies and https://pantheon.io/docs/guides/drupal-9-hosted-md/drupal-core-version

**Comment by jms-pantheon** [comment]
I started looking at this as a part of some other work on making the partial that sets Composer to use D8 also include a rollback to a compatible version of Drush. That's on PR #7968 and I've adjusted the code sample above to address the Drush version as well. 

Here's my review of where this partial is included, please don't consider this exhaustive, but I wanted to point out some of these don't need it as they are intended to remain on D8

This has them manually pull required custom code into a new d9 repo, but doesn't actually move back to d9
source/content/guides/drupal-9/drupal-9-hosted/05-create-site.md:
  50  
  51: <Partial file="drupal-9/core-version-remain-on-d8.md" />
  52  

Needs updating back to D9
source/content/guides/drupal-9/drupal-9-hosted-createempty-md/05-composer-upstream.md:
  41  
  42: <Partial file="drupal-9/core-version-remain-on-d8.md" />
  43  

Stays on D8
source/content/guides/migrate/manual-d8-composer-to-d8/03-prepare.md:
  26  
  27: <Partial file="drupal-9/core-version-remain-on-d8.md" />
  28  

Stays on D8
source/partials/drupal-8-convert-to-composer-from-empty.md:
  36  
  37: <Partial file="drupal-9/core-version-remain-on-d8.md" />
  38  

Stays on D8
source/partials/drupal-8-convert-to-composer.md:
  36  
  37: <Partial file="drupal-9/core-version-remain-on-d8.md" />
  38

**Comment by wordsmither** [comment]
@kevinhowbrook and @jms-pantheon , thank you so much for the info.  Now the fun begins!
