### ISSUE TITLE
Site Level Permissions (Needs Review)

### ISSUE THREAD

**Issue by tristanhipolito** [pantheon-systems/documentation#7964]
Re: [Workspaces, Sites, and Teams](https://pantheon.io/docs//guides/account-mgmt/workspace-sites-teams/teams)

Priority: Low (choose one, remove the other options)

## Issue Description:
I've noticed from [site level permissions](https://pantheon.io/docs/guides/account-mgmt/workspace-sites-teams/teams#site-level-permissions), The team member role on enabling Pantheon Search was marked as ❌, however, when I tried to enable it using a user with a team member role, it works. 

## Suggested Resolution
I don't know if the mistake is from the docs or from the expected result of its functionality.

**Comment by whitneymeredith** [comment]
@tristanhipolito I created a Team Member account and  was allowed to enable Solr as well.  I'm going to update the table to correct this information. Thanks!
