### ISSUE TITLE
Using SimpleSAMLphp with Shibboleth SSO Doc Update 

### ISSUE THREAD

**Issue by kreynen** [pantheon-systems/documentation#7973]
Re: [Using SimpleSAMLphp with Shibboleth SSO](https://pantheon.io/docs/shibboleth-sso)

Priority: Medium

## Issue Description:

With the D10.0.0 release just weeks away, it might be worth pointing out that the recommended solution for site-level SSO for Drupal on Pantheon is incompatible with D10/Symfony 6.

## Suggested Resolution

See https://github.com/simplesamlphp/simplesamlphp/issues/1689

**Comment by kporras07** [comment]
@whitneymeredith that's true. It seems that 4.x branch (dev version) of the Drupal module will have D10 compatibility by using dev-master version of the simplesamlphp library.

Some (maybe structural) changes should be done to that page to account for this situation
