### ISSUE TITLE
WordPress Plugins and Themes with Known Issues Doc Update 

### ISSUE THREAD

**Issue by orlandoayeras** [pantheon-systems/documentation#8025]
Re: [WordPress Plugins and Themes with Known Issues](https://pantheon.io/docs/plugins-known-issues)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Step 3 in Wordfence.
## Suggested Resolution
For Step 3 of Wordfence, please specify the directory for the creation of symlink. It should be `cd /my-site/wp-content/` since changing the directory to the root only can make confusion for the customers. Thanks!
![image](https://user-images.githubusercontent.com/77082837/208136333-3d659402-b61c-4fbd-bdec-9e8075df7129.png)

**Comment by EdwardAngert** [comment]
thanks @orlandoayeras 
do you know if the `../../` in all three of those `ln` commands will still be accurate? looks like it's two `../` in the first and one `../` in the second and third
if we `cd my-site/wp-content`, shouldn't that first `ln` then create the symlink as `./wflogs`?:

```bash
ln -s ../../files/private/wflogs ./wflogs
```

edit: I'm just grabbing this one - there are a few adjustments I want to make to this section

**Comment by orlandoayeras** [comment]
Thank you, @EdwardAngert. Thanks for reviewing it. That looks odder once you have pointed out the symlink command for the wflogs. Though maybe changing them to refer the target directory to wp-content:
`ln -s ../../files/private/wflogs ./wflogs`
`ln -s ../../files/private/wordfence-waf.php ./../wordfence-waf.php`
`ln -s ../../files/private/.user.ini ./../.user.ini`

So they should all have the same source path for symlinking.

**Comment by jms-pantheon** [comment]
This was correct before, I suggest a revert of the change specifically to the symlink instructions. 

As changed here, the symlink would point two directories up from `/code` and miss the `/files` directory. I don't see a need to cd into `/wp-content` directory and then create symlinks up a directory, it complicates the steps.

I've opened PR #8340  WordFence symlinks are relative to code root
