### ISSUE TITLE
Update Account Management Billing Doc to incorporate Billing Center 

### ISSUE THREAD

**Issue by wordsmither** [pantheon-systems/documentation#8028]
Re: [Billing](https://pantheon.io/docs//guides/account-mgmt/billing)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

Enterprise Billing Center will launch on the 20th, and [docs have been created](https://pr-7962--pantheon-docs.my.pantheonfrontend.website/docs/guides/enterprise-billing-center).  Incorporate/update the content in the existing billing guide to reflect this new feature

## Suggested Resolution

**Comment by whitneymeredith** [comment]
[PR 7962](https://github.com/pantheon-systems/documentation/pull/7962/commits) closes this issue.
