### ISSUE TITLE
Missing D9 upstream from guides

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8038]
Re: [Troubleshooting Custom Upstreams](https://pantheon.io/docs//guides/custom-upstream/troubleshooting)

Priority: Low

## Issue Description:

Guides on using upstreams only contain references to WordPress and Drupal 7, need the Integrated Composer upstream which works for D9 and D10

These two guides only have D7 upstream in the tabs:
https://pantheon.io/docs/guides/git/resolve-merge-conflicts
https://pantheon.io/docs//guides/custom-upstream/troubleshooting

## Suggested Resolution

Expand to have a tab for Drupal 9/10 which points to https://github.com/pantheon-systems/drupal-composer-managed

I believe that needs to use the branch `default` as well

**Comment by whitneymeredith** [comment]
Closing this because [https://github.com/pantheon-systems/documentation/issues/8024](https://github.com/pantheon-systems/documentation/issues/8024) will address the changes needed in this issue.

**Comment by jms-pantheon** [comment]
Hey @whitneymeredith I just reviewed #8024 and it looks unrelated, this issue still stands

**Comment by wordsmither** [comment]
https://pantheon.io/docs//guides/custom-upstream/troubleshooting was resolved as a part of https://github.com/pantheon-systems/documentation/pull/8004 - however, the updates are not appearing live as a result of the issues with the docs site.  Opened #8117 to address https://pantheon.io/docs/guides/git/resolve-merge-conflicts
