### ISSUE TITLE
Quick Start Doc Update 

### ISSUE THREAD

**Issue by zoo-it-tech** [pantheon-systems/documentation#8055]
Re: [Quick Start](https://pantheon.io/docs//guides/quickstart/ui-changes/)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution 
Either write instructions that work or write instructions on how to install via composer

**Comment by wordsmither** [comment]
Hello @zoo-it-tech -

Thank you for the feedback.  We have tested the instructions and they do seem to work, though we will be making some minor clarifications.  If you are still having issues, please see the WordPress or Drupal documentation that is included in the doc, or see https://pantheon.io/docs/overview/support for support options.
