### ISSUE TITLE
Drupal 10 Doc Update 

### ISSUE THREAD

**Issue by sashainparis** [pantheon-systems/documentation#8059]
Re: [Drupal 10](https://pantheon.io/docs/drupal-10)

Priority: Medium (choose one, remove the other options)

## Issue Description:

OP: Not delivered to Pantheon :-( 

edit (-EA): The steps in [Create a Drupal 10 Site](https://pantheon.io/docs/drupal-10#create-a-drupal-10-site) end with writing the commit message locally and should include the `git push`.

## Suggested Resolution

OP: One should probably push this commit  ;-D

edit (-EA): Add `git push origin master` to push the changes up

**Comment by wordsmither** [comment]
Thank you for submitting this issue.  Is there specific content you're recommending be changed?

**Comment by wordsmither** [comment]
closing for now.  please let me know if you want to discuss this further.

**Comment by EdwardAngert** [comment]
re-opened with new info
