### ISSUE TITLE
Instructions to install Terminus, the Pantheon CLI, on Windows

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#807]
* Install or update Cygwin: https://cygwin.com/install.html
* Select Cygwin packages: curl and openssh (net), php, php-curl, php-phar, php-json (php)

**Comment by macrocosm144** [comment]
FYI, I also had to install ctype (php) module in cygwin for it to work.

**Comment by ari-gold** [comment]
Thanks @macrocosm144. This doc update has been (re)-deployed. Would you be willing to issue a Pull Request for your addition?
