### ISSUE TITLE
Pantheon WordPress Upstream Doc Update 

### ISSUE THREAD

**Issue by rospencers** [pantheon-systems/documentation#8078]
Re: [Pantheon WordPress Upstream](https://pantheon.io/docs//start-states/wordpress)

Priority: Low/Medium/High (choose one, remove the other options)

Medium

## Issue Description:

Upstream update states there is info about a critical fatal error fix at https://pantheon.io/docs/start-states/wordpress#20230117 (J17 Jan 2023), but the info does not exist. The page has had no update since July 2022.

Adopting undocumented fixes by a third party is troubling.

## Suggested Resolution

Provide the 17 Jan 2023 information as promised in the upstream update.

**Comment by whitneymeredith** [comment]
@rospencers Thank you for your contribution! I'm closing this issue because the information will be added in a pre-existing issue. You can see existing issue here:[https://github.com/pantheon-systems/documentation/pull/8063](https://github.com/pantheon-systems/documentation/pull/8063)
