### ISSUE TITLE
terminus import:database docs do not specify that it drops the database

### ISSUE THREAD

**Issue by kirrrk** [pantheon-systems/documentation#8088]
Re: [terminus import:database](https://pantheon.io/docs/terminus/commands/import-database)

Priority: Low

### Issue Description:
The documentation for the import:database command does not specify that the command drops the existing database and imports the target to a new database. Some customers have assumed this command imports the target file into the existing database, resulting in accidental database deletion.

### Suggested Resolution:
Specify that the database:import command drops the existing database and point to the [database access docs](https://pantheon.io/docs/guides/mariadb-mysql/mysql-access) for other database operations.

**Comment by stevector** [comment]
this page now says "Imports a database archive to the environment. This command drops the existing database and imports the target into a new database. Use with caution to avoid accidental database deletion."
