### ISSUE TITLE
Enabling Solr for WordPress Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#8091]
Re: [Enabling Solr for WordPress](https://pantheon.io/docs/wordpress-solr)

Priority: Medium

## Issue Description:

This command on this page is not a valid syntax:

`terminus wp <site>.<env> -- url=example.pantheonsite.io/subsite solr index`

## Suggested Resolution

It should be this to follow WP-CLI and Terminus syntax:

`terminus wp <site>.<env> -- --url=example.pantheonsite.io/subsite solr index`

Or this could also be a more clear version of it too:

`terminus wp <site>.<env> -- solr index --url=example.pantheonsite.io/subsite`

**Comment by carl-alberto** [comment]
It seems the change is already in the docs https://docs.pantheon.io/guides/wordpress-developer/wordpress-solr

![Screen Shot 2023-06-01 at 6 30 23 PM](https://github.com/pantheon-systems/documentation/assets/5098765/2629c2fe-9168-4df9-9771-82d0ccab778d)

**Comment by whitneymeredith** [comment]
Thanks @carl-alberto . I'll mark this issue as closed.
