### ISSUE TITLE
Migrate a Site That Was Created With an Empty Upstream to Drupal 9 Doc Update 

### ISSUE THREAD

**Issue by raffishtenant** [pantheon-systems/documentation#8106]
Re: [Migrate a Site That Was Created With an Empty Upstream to Drupal 9](https://pantheon.io/docs//guides/drupal-9-hosted-createempty-md/composer-upstream)

Priority: Medium

## Issue Description:
I ran into a couple issues within step 2 at the top of this page:

1)
> git fetch ic
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

2) 
> git checkout --no-track -b composerify ic/main
warning: unable to rmdir 'vendor/drupal/coder': Directory not empty

## Suggested Resolution
1) I realize that most devs may have this issue sorted out already, but for those of us who don't regularly use GitHub (or haven't yet done so from our current dev platform), it might be useful to provide the following link, which explains it:
https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey
Users who run into this will probably just need to generate a new SSH key and add it to GitHub.

2) I'm not sure if this error will cause problems downstream or not. For now, I'm simply going to rename the directory to something else and hope for the best, but if it's truly safe to remove this directory at this point (regardless of what might be inside it), it might be a good idea to advise 'rm -rf vendor/drupal/coder' before proceeding with the checkout.

**Comment by wordsmither** [comment]
@raffishtenant , thank you for your input.  Fortunately, this information already lives in the [Troubleshooting](https://pantheon.io/docs/guides/drupal-9-hosted-createempty-md/troubleshooting#permission-denied-publickey) section, with all other troubleshooting content for this process.  I believe its best served by staying in that location.
