### ISSUE TITLE
Cloudflare Domain Configuration Doc Update 

### ISSUE THREAD

**Issue by philoSurfer** [pantheon-systems/documentation#8124]
Re: [Cloudflare Domain Configuration](https://pantheon.io/docs//cloudflare)

Priority: Low/Medium/High (choose one, remove the other options)
High

## Issue Description:
This documentation lacks information about cache invalidation best practices. 

Eg. if caching is turned on In CF, and there is no cache invalidation hook fired off when there are content changes, then CF will be unaware and persist stale cache. 

## Suggested Resolution
Make a suggestion to turn of CF caching (only), until such time they can extend the `pantheon_advanced_page_cache` module/plugin to send API calls out to CF. 

ping me for examples if needed.

**Comment by ccharlton** [comment]
Do we have a number of support tickets showing customers actually see this issue even after following our documented steps, versus one or two cases from (common) misconfiguration?
