### ISSUE TITLE
Convert a Standard Drupal 8 Site to a Composer Managed Site Doc Update 

### ISSUE THREAD

**Issue by mattkirschner** [pantheon-systems/documentation#8134]
Re: [Convert a Standard Drupal 8 Site to a Composer Managed Site](https://pantheon.io/docs//guides/composer-convert)

Priority: Medium
## Issue Description:
On *Set Drupal Core Version*:
Running the line ```composer require --dev drupal/core-dev:^8.9``` gives the error: **Your requirements could not be resolved to an installable set of packages.**

The problem seems to result from the following conflicts;
- symfony/finder[v6] require php >=8 (config has php set to 7.4)
- drush[11] require symfony/finder ^4
- drupal/core-dev[8.9] require symfony/finder ~3.4

## Suggested Resolution
This isn't my wheelhouse so I'm not sure, but I'd expect documentation to work out-of-the-box.

**Comment by EdwardAngert** [comment]
hi @mattkirschner, sorry this one let you down. We have [an update to this](https://github.com/pantheon-systems/documentation/commit/a2f695fdd5ea404e660721edef378c86f6d6d906#diff-5de48a9c5daeb5cc7677c2d93a0f4500abf0bc6cedd153c5d2291f5e46cc96e2) merged to `main` but not yet built/deployed and it seems you encountered it before the fix could go live. We hope to have changes live on the docs site by the end of next week.

In the meantime, try the updated steps that specify a newer version:

```bash
composer require --no-update drupal/core-recommended:^9
composer require --dev drupal/core-dev:^9
git add composer.*
git commit -m "Remain on Current Version"
```

Let us know if that works + enjoy your day.

**Comment by mattkirschner** [comment]
I'm confused, I thought the point of those steps was to keep the site on Drupal Core v8 while migrating to composer. Won't setting the require version to ^9 cause core to be updated premmaturely?

**Comment by kporras07** [comment]
Hi @mattkirschner apologies, you're right.

It would be great to see the full output of your `composer require` command; however, with what you posted I see some issues there:
- You seem to be using drush 11 which as per [drush docs](https://www.drush.org/latest/install/#drupal-compatibility) is not compatible with drupal 8; that may be causing some dependency conflicts in your site
- Something seems to require `symfony/finder[v6]` which is only php >= 8 and PHP is set to 7.4. Maybe drush?
- PHP should be set to 7.4 in this case as Drupal 8 is not compatible with PHP >=8 as per https://www.drupal.org/docs/system-requirements/php-requirements

I'd advice you to make sure you have the right versions and them attempt to convert the site again; if that still doesn't work, please paste commands full output here

Thanks!

**Comment by mattkirschner** [comment]
Thanks for the response, @kporras07.

My drush version is 10.3.2-dev, so it's strange that I'm getting requirements for 11.

Since it's not too long, I've attached a screenshot of the full output of the require statement. In the meantime, I'll look into playing around with PHP version to see if that's the culprit. I'm not sure if composer can choose which PHP version to use, though I don't even have 7.x installed. I'll install it, see if it works, then make it my default if it's still failing.

![requirements-error](https://user-images.githubusercontent.com/31108104/218800023-ca7541ce-4664-4039-824b-16e7289a8ea6.jpg)

**Comment by kporras07** [comment]
Hmmm, I think I got it! Try fixing drush version:
`composer require --no-update drush/drush:"^10"`, then retry your `composer require --dev` command

I think this should probably be added to the docs, but please let me know if it helps

**Comment by mattkirschner** [comment]
Holy smokes, you're a wizard @kporras07! It worked.

Would you mind explaining why? Was the default still trying to use drush v11 despite me not having it (and D8 not supporting it)?
