### ISSUE TITLE
Pantheon Autopilot Doc Update 

### ISSUE THREAD

**Issue by JQTNguyen** [pantheon-systems/documentation#8200]
Re: [Pantheon Autopilot](https://docs.pantheon.io//guides/autopilot)

Priority: Low

## Issue Description:

Clearer explanation of Drupal compatibility that is inclusive of Drupal 7.

## Suggested Resolution

Rather than saying:

- Drupal 8 (with Integrated Composer or Drush 8) = ✔ compatible
- Drupal (with Integrated Composer) = ✔ compatible

It may be better to re-order this so that it is...

- Drupal (with Integrated Composer) = ✔ compatible
- Drupal 8 (with Integrated Composer or Drush 8) = ✔ compatible

...and then change the Drupal 8 line by removing the "Integrated Composer" bit (since it's covered in the first statement), and then also call out Drupal 7 as well so it becomes...

- Drupal (with Integrated Composer) = ✔ compatible
- Drupal 7 or 8 (with Drush 8) = ✔ compatible

That way, it essentially reads:

- If you are using Drupal (regardless of which version) and are using Integrated Composer, then you are compatible.
- If you are using Drupal 7 or 8 and using Drush 8 (regardless of if you are using IC), then you are compatible.

**Comment by wordsmither** [comment]
Closing in favor of #8066
