### ISSUE TITLE
Evaluate Installation Method for WP Redis Plugin

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#823]
## For: [Installing Redis on WordPress](https://pantheon.io/docs/articles/sites/installing-redis-on-wordpress/)

#793 was recently merged, and then reverted in [d37043](https://github.com/pantheon-systems/documentation/commit/d37043d471bd7ee4499ecd9d3aaa1a5223cb8cb9) for further testing.

We need confirmation that creating a symbolic link from `wp-content/plugins/wp-redis/object-cache.php` to target `wp-content/object-cache.php` is best practice. 

## Current Installation Method - Move object-cache.php
This successfully creates the drop-in plugin and is the current installation method recommended by CSE (@newtoid confirmed). 
![current wp-redis installation method drop-ins list](https://pantheon.io/docs/assets/images/plugin-drop-ins.png)
### Reported Issue
Plugin updates are reportedly broken as a result of moving the `object-cache.php` file (see #793).

## Suggested Alternative - Symbolic Link
When creating the symbolic link as suggested in #793, the drop-ins list shows `object-cache.php` but the description for WP Redis is no longer present, leading me to believe that it is not properly activated as a drop-in:
![screen shot 2015-08-17 at 5 22 34 pm](https://cloud.githubusercontent.com/assets/10119525/9319507/c015495a-4514-11e5-9efe-c32fa6a8dc61.png)

**Comment by rachelwhitton** [comment]
ping @joshkoenig - can you review this issue and determine the recommended installation method?

**Comment by rachelwhitton** [comment]
#### Related
Mark Jaquith provided suggestions for the WP Redis plugin within the [wp_launch_check repo](https://github.com/pantheon-systems/wp_launch_check/issues/11#issuecomment-93548147). Seems like those updates would solve this issue, along with potential redeclaration errors resulting from the plugin and drop-in plugin being active simultaneously.

**Comment by joshkoenig** [comment]
I'll need to find a block of time to dig in and get the right answer. Thanks for surfacing this!
