### ISSUE TITLE
Environment Configuration Doc Update 

### ISSUE THREAD

**Issue by mukitmuntasir** [pantheon-systems/documentation#8240]
Re: [Environment Configuration](https://docs.pantheon.io//guides/environment-configuration/environment-indicator)

Priority: Medium

## Issue Description:

In step 3 of drupal environment indicator. The following Environment Indicator module settings is not wokring:

$conf['environment_indicator_overwrite'] = TRUE;
  $conf['environment_indicator_overwritten_position'] = 'top';
  $conf['environment_indicator_overwritten_fixed'] = FALSE;

  if (!defined('PANTHEON_ENVIRONMENT')) {
      $conf['environment_indicator_overwritten_name'] = 'Local';
      $conf['environment_indicator_overwritten_color'] = '#505050';
      $conf['environment_indicator_overwritten_text_color'] = '#ffffff';
  }
  // Pantheon Env Specific Config
  if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
      switch ($_ENV['PANTHEON_ENVIRONMENT']) {
        case 'lando': // Localdev or Lando environments
          $config['environment_indicator.indicator']['name'] = 'Local Dev';
          $config['environment_indicator.indicator']['bg_color'] = '#990055';
          $config['environment_indicator.indicator']['fg_color'] = '#ffffff';
          break;
        case 'dev':
          $conf['environment_indicator_overwritten_name'] = 'Dev';
          $conf['environment_indicator_overwritten_color'] = '#307b24';
          $conf['environment_indicator_overwritten_text_color'] = '#ffffff';
          break;
        case 'test':
          $conf['environment_indicator_overwritten_name'] = 'Test';
          $conf['environment_indicator_overwritten_color'] = '#b85c00';
          $conf['environment_indicator_overwritten_text_color'] = '#ffffff';
          break;
        case 'live':
          $conf['environment_indicator_overwritten_name'] = 'Live!';
          $conf['environment_indicator_overwritten_color'] = '#e7131a';
          $conf['environment_indicator_overwritten_text_color'] = '#ffffff';
          break;
        default:
          //Multidev catchall
          $conf['environment_indicator_overwritten_name'] = 'Multidev';
          $conf['environment_indicator_overwritten_color'] = '#e7131a';
          $conf['environment_indicator_overwritten_text_color'] = '#000000';
          break;
      }
  }
  
  **Instead of $conf it should be $config**

## Suggested Resolution

$conf['environment_indicator_overwrite'] = TRUE;

$conf['environment_indicator_overwritten_position'] = 'top';

$conf['environment_indicator_overwritten_fixed'] = FALSE;

if (!defined('PANTHEON_ENVIRONMENT')) {

$config['environment_indicator.indicator']['bg_color'] = '#505050';

$config['environment_indicator.indicator']['fg_color'] = '#ffffff';

$config['environment_indicator.indicator']['name'] = 'Local';

}

// Pantheon Env Specific Config

if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {

switch ($_ENV['PANTHEON_ENVIRONMENT']) {

case 'dev':

$config['environment_indicator.indicator']['name'] = 'Dev';

$config['environment_indicator.indicator']['bg_color']= '#307b24';

$config['environment_indicator.indicator']['fg_color'] = '#ffffff';

break;

case 'test':

$config['environment_indicator.indicator']['name'] = 'Test';

$config['environment_indicator.indicator']['bg_color']= '#b85c00';

$config['environment_indicator.indicator']['fg_color'] = '#ffffff';

break;

case 'live':

$config['environment_indicator.indicator']['name'] = 'Live!';

$config['environment_indicator.indicator']['bg_color']= '#e7131a';

$config['environment_indicator.indicator']['fg_color'] = '#ffffff';

break;

default:

//Multidev catchall

$config['environment_indicator.indicator']['name'] = 'Multidev';

$config['environment_indicator.indicator']['bg_color']= '#e7131a';

$config['environment_indicator.indicator']['fg_color'] = '#000000';

break;

}

**Comment by wordsmither** [comment]
Hello @mukitmuntasir, 

Thank you so much for your feedback!  Could you please tell us what upstream and Drupal version you are using?

**Comment by wordsmither** [comment]
@mukitmuntasir , could you please provide the upstream and Drupal version you are using?

**Comment by wordsmither** [comment]
[Jira Created](https://getpantheon.atlassian.net/browse/BUGS-6115)
