### ISSUE TITLE
Integrated Composer Doc Update 

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#8253]
Re: [Integrated Composer](https://docs.pantheon.io/guides/integrated-composer/ic-faq)

Priority: Medium

## Issue Description:

paraphrasing [from slack](https://pantheon.slack.com/archives/CU174QD1B/p1678990977267439) (h/t @matthewboman @dficker @namespacebrian)

<https://docs.pantheon.io/guides/integrated-composer/ic-faq#why-are-contrib-modules-placed-in-modulescomposer-instead-of-modulescontrib> has confusing instructions for where the custom modules go and some instructions are in comments on `.gitignore`:

```none
# Ignore custom modules managed by Composer.
#
# When a development team creates one or more custom modules that
# are intended for use on more than one site, the typical strategy
# is to register them in Packagist and give them the type
```

## Suggested Resolution

clarify <https://docs.pantheon.io/guides/integrated-composer/ic-faq#why-are-contrib-modules-placed-in-modulescomposer-instead-of-modulescontrib> and add an additional note linking out to how to handle custom modules?

**Comment by wordsmither** [comment]
Jared Sulzdorf will be creating a ticket for https://github.com/pantheon-systems/documentation/issues/8222 to review the full doc - this will likely be covered as a part of that.
