### ISSUE TITLE
Update a Drupal Site with Integrated Composer to the Latest Version of Drupal Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8273]
Re: [Update a Drupal Site with Integrated Composer to the Latest Version of Drupal](https://docs.pantheon.io/guides/upgrade-drupal-8-ic-to-drupal-9)

Priority: Medium

## Issue Description:
This page does not seem to contain the steps to accomplish the stated goal. It has us install Composer, PHP, and Git, and then apply upstream updates via Terminus. 

## Suggested Resolution
It should include steps to upgrade Drupal, similar to those outlined here: 

These instructions are to go specifically to D10, I'm not sure what the intent of this guide is. If it is to get the latest version, then no version constraint should be in the commands. If it is to update to the latest minor version of the existing Drupal major version, then the steps will need to be adapted to whatever version of Drupal the site is already using.

https://docs.pantheon.io/drupal-10#create-a-drupal-10-site

```
composer config minimum-stability rc
git commit -am "composer config minimum-stability rc"
composer config platform.php 8.1
git commit -am "composer config platform.php 8.1"
composer config allow-plugins.phpstan/extension-installer true
git commit -am "composer config allow-plugins.phpstan/extension-installer true"
composer require --no-update --dev drupal/core-dev:^10
composer require --no-update drupal/core-composer-scaffold:^10
composer require --no-update pantheon-systems/drupal-integrations:^10
composer require --no-update drupal/core-recommended:^10
composer update
git commit -am "Update to Drupal 10"
git push origin master
```

**Comment by wordsmither** [comment]
closing per slack convo with opener
