### ISSUE TITLE
Terminus Guide Updates page doesn't show changelog content

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#8278]
Re: [Terminus Guide](https://docs.pantheon.io/terminus/updates)

Priority: Medium

## Issue Description:

Terminus changelog is being treated like docs.pantheon.io/changelog. It shows the heading and first bit of content, but treats it like an excerpt. (thanks for pointing out, @jsulz )

## Suggested Resolution

Modify the way the changelog component is treated to include only `/changelog`

**Comment by rachelwhitton** [comment]
Terminus Changelog preview is stale on production, up to date on local: 

<img width="1698" alt="Screenshot 2023-11-30 at 5 02 36 PM" src="https://github.com/pantheon-systems/documentation/assets/10119525/89124d7c-79ea-440c-b41e-6708da5f9924">

This issue should be considered as part of the larger initiative in progress now for improving Changelog ux, and likely to be consolidated into a single canonical Changelog that also includes entries from other repositories such as WordPress Upstream release notes housed here currently: https://docs.pantheon.io/wordpress

**Comment by rachelwhitton** [comment]
Closing as a dupe since convo is further along in #8954
