### ISSUE TITLE
Redirects Guide Doc Update 

### ISSUE THREAD

**Issue by caspervoogt** [pantheon-systems/documentation#8293]
Re: [Redirects Guide](https://docs.pantheon.io//guides/redirect/primary-domain)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description: Doc mentions "Navigate to the Choose Primary Domain" but there is no such section when I view the "Domains / HTTPS" for my environment.
<img width="1107" alt="Screen Shot 2023-03-30 at 4 50 50 PM" src="https://user-images.githubusercontent.com/722776/228961405-a41e69dd-67f4-48c6-b1e6-9e62475d6926.png">

## Suggested Resolution

**Comment by caspervoogt** [comment]
This is not resolved. I still do not see any way to choose a primary domain. #8349 mentions redirects. I wasn't talking about redirects. Rather, my point was simply that there is no way for me to set the primary domain via the UI, even though the docs suggest that is possible (and I remember it being an option before).

**Comment by carl-alberto** [comment]
Hi @caspervoogt, thanks for raising this concern via our docs and sorry that we closed this without any explanation.

This PR that we made yesterday https://github.com/pantheon-systems/documentation/pull/8349 added a note here https://docs.pantheon.io/guides/domains/primary-domain#set-a-primary-domain-via-the-dashboard that the primary domain redirect option should only appear if you have 2 CUSTOM domains added, in your case, you only have one CUSTOM domain which is `itwcookingtest1.com`, if you will add another one `www.itwcookingtest1.com`, the primary redirect should be an available option.

Hope that makes sense but please do reach out if you need further clarification or issues.

Thanks!

**Comment by caspervoogt** [comment]
Hi @carl-alberto. I did read that note. My issue isn't with the redirects but the fact that there is no "Choose Primary Domain" section. The instructions on https://docs.pantheon.io/guides/domains/primary-domain#set-a-primary-domain-via-the-dashboard say "3. Navigate to the Choose Primary Domain section, select the domain to which traffic should be redirected, and then click Save Configuration." There is no such option on my end. See my original screenshot. 

If Terminus is the only way to set the primary domain, the docs should be updated to reflect that. I'd love to not have to use Terminus for a basic thing like this, though.
