### ISSUE TITLE
Site: Implement a button to copy code

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#8297]
Re: code blocks

## Issue Description

* As a user who needs to copy commands and sections of code, I want to click a button to copy to clipboard instead of highlighting lines of text.

### How will this impact users?

* It'll make it easier to copy code!

## Suggested Resolution

* Possible plugin: https://www.npmjs.com/package/clipboard
* here’s how folks did it in the Gatsby docs: https://github.com/gatsbyjs/gatsby/pull/15834

## Additional Information

* Digging through the code, this functionality might've already existed on the site:
  * ZeroClipboard: https://github.com/pantheon-systems/documentation/blob/main/source/docs/assets/js/src/application.js#L128
  * [clipboardy](https://www.npmjs.com/package/clipboardy): https://github.com/pantheon-systems/documentation/blob/main/package-lock.json#L8036

**Comment by rachelwhitton** [comment]
Opting to close as we are likely to switch frameworks
