### ISSUE TITLE
Drupal Upgrade and Migration Guides Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8301]
Re: [Drupal Upgrade and Migration Guides](https://docs.pantheon.io/drupal-migration)

Priority: Medium

## Issue Description:
It seems the documentation for upgrading from D8 to D9 or Integrated Composer may have been lost. The introduction here on the Drupal 8 section of the migration guides indicates there should be a guide for it: https://docs.pantheon.io/drupal-migration#i-use-drupal-8

As does the introduction to the guide that is linked to:
https://docs.pantheon.io/guides/drupal-hosted-createdashboard-set8

However from there on the steps diverge and assumed the user is on D9 and upgrading to D10?

## Suggested Resolution
Resurrect or replace with an appropriate guide

**Comment by wordsmither** [comment]
@jms-pantheon , our guides were intentially updated to instruct users to upgrade to the latest version of Drupal (v10), so there is no longer a guide for upgrading to version 9.  We do still have [documentation on using Integrated Composer](https://docs.pantheon.io/drupal) with Drupal, and we have docs on [converting a standard Drupal site to Integrated Composer](https://docs.pantheon.io/guides/composer-convert). If you are seeing specific references to 9, please let me know so we can correct those.

**Comment by jms-pantheon** [comment]
Hi @wordsmither thanks for looking at this one. Good to know about everything being set to D10. In this case, the issue is that the guide is meant to be for sites that were created before D9 to upgrade to D9/D10 in this case

> I use Drupal 8
> Pantheon Dashboard + Drupal 8
> Use Upgrade a Site Created With the Pantheon Dashboard to the Latest Version of Drupal to start your upgrade if you used the Pantheon Dashboard to create your Drupal site, and your site requires the version to be set to Drupal 8.

This is for users that created a site on Pantheon for Drupal 8 using our D8 upstream and wish to upgrade to the latest version of Drupal. However, the guide that is linked to only contains instructions for upgrading from D9 to D10 which is a very different process. This should be a separate guide.

**Comment by stovak** [comment]
Ah, the permutation hydra. She is a beast. Would be great if we could do a "scan my site and recommend upgrade instructions" based on the repo.
