### ISSUE TITLE
Diagramming or full SVG support

### ISSUE THREAD

**Issue by wordsmither** [pantheon-systems/documentation#8307]
The need is to be able to create diagrams that create links.  This could be done either via a text diagramming tool (i.e. mermaid) or by using SVGs - however, our site renders SVGs as static, without any embedded links.

## Issue Description

* 

### How will this impact users?

*

### Context

* 

## Suggested Resolution

* 

## Additional Information

*

**Comment by EdwardAngert** [comment]
adding @whitneymeredith since you've done some Mermaid research too
