### ISSUE TITLE
Error with Permissions-Policy header

### ISSUE THREAD

**Issue by ThomasPof** [pantheon-systems/documentation#8312]
Priority: Medium (choose one, remove the other options)

## Issue Description:

On a wordpress website hosted on Pantheon, I followed those guidelines : https://docs.pantheon.io/guides/wordpress-developer/wordpress-best-practices#security-headers to implement security headers, but I always have the same error in the console no matters the value of the Permissions-Policy header

`Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.`

**Comment by whitneymeredith** [comment]
@ThomasPof Thanks for reaching out. As the documentation says, the code for  adding security headers is only an example to help you get started. You'll need to modify the code for your specific needs.
