### ISSUE TITLE
WordPress REST API Best Practices

### ISSUE THREAD

**Issue by wordsmither** [pantheon-systems/documentation#8314]
https://docs.pantheon.io/guides/wordpress-developer
https://docs.pantheon.io/guides/wordpress-developer/wordpress-login-attacks
https://docs.pantheon.io/pantheon-yml#protected-web-paths

Customer suggestion for a possible addition to [WordPress Best Practices](https://docs.pantheon.io/guides/wordpress-developer)/[Avoid WordPress Login Attacks](https://docs.pantheon.io/guides/wordpress-developer/wordpress-login-attacks).
WP exposes information about authorized users via the JSON REST API. If you hit any default-configured WP site with the URL `/wp-json/wp/v2/users`, you get a JSON message with a list of users.
A couple possible solutions that need vetting:

- [Protected path via pantheon.yml](https://docs.pantheon.io/pantheon-yml#protected-web-paths)
- Block with AGCDN (allows wildcard block of all wp-json urls),
- Use a plugin to lock down the entire JSON REST API ([as recommended by Green Geeks](https://www.greengeeks.com/tutorials/disable-rest-api-json-wordpress/)).
- 
- ### Steps to reproduce the problem

1.

## Suggested Resolution
*

**Comment by jazzsequence** [comment]
Any solution that blocks the entire `/wp-json/wp/v2/users/` path -- in any form -- has the potential to break elements of Gutenberg or the Full Site Editor, since both of those are React apps that use the REST API to talk to WordPress. We should provide examples that are more closely tailored to blocking access to _non-authenticated users_ rather than blocking the endpoint _entirely_, and note the distinction (and why) in the docs.

**Comment by jazzsequence** [comment]
I've got a couple code snippets that will disable the `/users/` endpoint to people who don't need to see it:

Trigger a REST authentication error if the current user is not logged in or does not have access to the `list_users` capability:
```php
function restrict_user_endpoints( $access ) {
	if ( ! is_user_logged_in() || ! current_user_can( 'list_users' ) ) {
		$requested_route = $_SERVER['REQUEST_URI'];
		if ( strpos( $requested_route, '/wp/v2/users' ) !== false ) {
			return new WP_Error( 'rest_forbidden', 'Sorry, you are not allowed to do that.', array( 'status' => 403 ) );
		}
	}

	return $access;
}
add_filter( 'rest_authentication_errors', 'restrict_user_endpoints' );
```

Hook into `rest_pre_dispatch` to trigger an error if the user does not have permission to `list_users` before the route is served:
```php
function custom_rest_api_permissions($result, $server, $request) {
    if ($request->get_route() === '/wp/v2/users' && !current_user_can('list_users')) {
        return new WP_Error('rest_forbidden', __('You are not allowed to access this resource.'), array('status' => 403));
    }
    return $result;
}
add_filter('rest_pre_dispatch', 'custom_rest_api_permissions', 10, 3);
```

Functionally, both of these do the same thing in different ways. We can probably document both. When you would use one over the other is likely dependent upon what you're doing. I suspect the `authentication_errors` route is more "correct" but I know a lot of people are more familiar with working with `rest_pre_dispatch`.

**Comment by jazzsequence** [comment]
I should note that I've tested these both locally, not on Pantheon, yet. I will test both of these methods on Pantheon before updating docs.

**Comment by jazzsequence** [comment]
Also relevant: Ryan McCue's explanation about why this decision was made in the first point (which debunks a lot of fears or concerns about why this is a "security" issue in the first place): https://www.reddit.com/r/ProWordPress/comments/1clp2dm/comment/l2v1nu2/

**Comment by jazzsequence** [comment]
[This gist](https://gist.github.com/danielbachhuber/8f92af4c6a8db784771c) confirms the `rest_authentication_errors` method is more correct. Will go with that instead of `pre_dispatch` even though it ends up being more code.

**Comment by jazzsequence** [comment]
Added docs in #9167 
I don't agree with adding to protected site paths because that approach seems both heavy-handed and limited (and able to be worked around). Handling this within WordPress is a better solution.
