### ISSUE TITLE
Confusing Autopilot requirements

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8339]
Re: [Pantheon Autopilot: Autopilot Requirements](https://docs.pantheon.io/guides/autopilot#autopilot-requirements)

Priority: Low

## Issue Description:

Autopilot supports more than Drupal 8, it also supports Drupal 7. That's also stated here: https://docs.pantheon.io/guides/autopilot/autopilot-faq/#what-versions-of-drupal-are-supported-by-autopilot

Moreover I find the table presentation confusing, I always have to read it a few times as I tend to think it's a decision grid. 

## Suggested Resolution

Perhaps just drop the table and expand on the bullet points above, or re-think the table to be more of a grid with main CMS versions vertically and other factors horizontally.

**Comment by wordsmither** [comment]
@jms-pantheon - what table are you referring to?  Also, Drupal 7 is mentioned.  Could you help me better understand the issue?

**Comment by jms-pantheon** [comment]
The linked text here does not state that Drupal 7 is supported, but it is supported

> A supported framework:
Drupal with Integrated Composer
Drupal 8 with Integrated Composer or Drush 8

https://docs.pantheon.io/guides/autopilot#autopilot-requirements

Then this table right below that also misses that information. Additionally I was noting that I find the display here confusing every time, perhaps it is just me though

<img width="671" alt="image" src="https://user-images.githubusercontent.com/91161717/236279978-350e0428-9d19-4ccf-aacb-ccacf552568a.png">

**Comment by wordsmither** [comment]
ah, got it.  I was looking at the very first link, and was very confused. thank you!
