### ISSUE TITLE
August Changelog Candidates

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#836]
Add platform improvements we should list in the August newsletter to the comments
PR: https://github.com/pantheon-systems/documentation/blob/master/source/docs/changelog/2015-08-01-August.md

**Comment by bmackinney** [comment]
https://github.com/pantheon-systems/WordPress/issues/13

**Comment by ari-gold** [comment]
https://github.com/pantheon-systems/titan-mt/pull/13428

**Comment by bmackinney** [comment]
Terminus releases are up to 0.7.1 now. We need to keep updated and make it current on the 31st. https://github.com/pantheon-systems/cli/releases

**Comment by bmackinney** [comment]
Backup failure rate cut in half.

**Comment by nataliejeremy** [comment]
@bmackinney Is there anything to link to for that or any other details to add?
