### ISSUE TITLE
Update Object Cache Pro configuration details to include multisite-specific instructions

### ISSUE THREAD

**Issue by kerri-hicks** [pantheon-systems/documentation#8361]
Re: [Object Cache Pro on Pantheon](https://docs.pantheon.io/guides/object-cache-pro/installing-configuring/)

Priority: Medium

## Issue Description:

Not sure if this documentation is intended for WP multisite users.

Documentation step 8: Navigate to `/wp-admin/options-general.php?page=objectcache` to see the current status of Object Cache Pro on your site as well as live graphs of requests, memory usage, and more.

Trying to access the network root version of that page throws a "Sorry, you are not allowed to access this page." error.

However, I **can** see (what I assume are the multisite-wide) graphs at `/wp-admin/network/settings.php?page=objectcache`

On an individual site, if I try `/<SUBSITENAME>/wp-admin/options-general.php?page=objectcache` I get a "you do not currently have privileges on this site" error. If I try `/<SUBSITENAME>/wp-admin/network/settings.php?page=objectcache` I get a 404.

Also, **on a subsite**, there _is_ an Object Cache panel on the dashboard: 
<img width="598" alt="Screen Shot 2023-04-18 at 2 38 12 PM" src="https://user-images.githubusercontent.com/990888/232872748-0901e379-8cb4-429f-b6a9-0ef15c159fac.png">

But there is no entry for Object Cache under the subsite's "Settings" menu. (There is an Object Cache entry under Settings at the network root, however.)

It's unclear how this is supposed to work/look for WP Multisite installations, so I'm not sure what needs fixing. It's clear that something's not right, however. Is Object Cache intended to work only at the root level, for the entire multisite? Or is it able to be managed at the subsite level?

If it can't be managed at the subsite level, it's detrimental to have a panel in the dashboard for each site.

**Comment by stevector** [comment]
Thanks for the question @kerri-hicks! @scottbuscemi, do you have insight here?

**Comment by whitneymeredith** [comment]
@jazzsequence Adding you as well in case you have any insight into this topic. Thanks!

**Comment by scottbuscemi** [comment]
Hi Kerri! Thanks for the feedback - we definitely need to update the documentation to include information about multisite installation.

* You are correct that `/wp-admin/network/settings.php?page=objectcache` is the URL for the network-wide configuration/graphs/etc. ... This is the only screen throughout the network to see this information.
* Subsites do not get their own configuration or graphs. Activating Object Cache Pro applies to all subsites.

Could you elaborate on how the subsite widget is detrimental? It'd be helpful for us to share that feedback with Object Cache Pro.

**Comment by kerri-hicks** [comment]
Thanks, @scottbuscemi. This is helpful. 

The reason an OCP subsite widget is detrimental -- my group supports approximately 150 web editors, each with their own subsite. Having that panel there increases my support load (what is that? I want access to that!) x150, requires me to update my documentation (including all new screenshots), and increases the risk that editors will use it (there's a "Flush Cache" button that I assume actually does something -- although I'm unclear what it would do...flush the entire site's cache? Flush only the subsite's cache?).

If we must, we'll write around it locally to hide it in the dashboard, but it'd be nice for multisite to hide it on individual dashboards.

**Comment by tillkruss** [comment]
We could probably introduce it as an option in a future release to hide it. For now you can easily hide it yourself: https://objectcache.pro/docs/customizations#dashboard-widget

**Comment by scottbuscemi** [comment]
@kerri-hicks Totally makes sense about how admins in the subsites might clear cache unnecessarily! It would indeed clear for the entire network. The first filter in Till's link would be the best bet!

I'll send you an email regarding the `pantheon.yml` issue so we can resolve that for your site. (I need to ask for site info so not good for a public forum 😄 )

**Comment by kerri-hicks** [comment]
Done, and works as expected!

**Comment by jazzsequence** [comment]
I have it on my plate to update our documentation after I take some time to test OCP on multisite some more, so I will definitely come back to this. Thanks @kerri-hicks @tillkruss @whitneymeredith
