### ISSUE TITLE
Redis Drupal Module

### ISSUE THREAD

**Issue by RobLoach** [pantheon-systems/documentation#840]
## Initial report
It seems [redis as a caching backend](https://github.com/pantheon-systems/documentation/blob/f49e59667674943ef95b5bf25af660dc0ed50436/source/docs/articles/sites/redis-as-a-caching-backend.md) could use some documentation updates:

1. We have successfully migrated over to [Redis Drupal module](https://www.drupal.org/project/redis) 3.10 on one of our environments.
2. The Redis 3.x has the [additional configuration](http://cgit.drupalcode.org/redis/tree/README.txt#n63) as well:

  ``` php
  $conf['path_inc'] = 'sites/all/modules/redis/redis.path.inc';
  ```

## Resolution
- [ ]

**Comment by rachelwhitton** [comment]
Thanks for the issue @RobLoach! 

I'm getting the following PHP error after enabling 3.10 on a D7 site:
![screen shot 2015-08-24 at 11 37 08 am](https://cloud.githubusercontent.com/assets/10119525/9446019/ee318728-4a54-11e5-8939-c8ff31c176a0.png)

Did you encounter the same thing, @RobLoach? Any tips for a work around? I added the provided config examples in the article and in your issue above to my `settings.php` file:
```
// All Pantheon Environments.
if (defined('PANTHEON_ENVIRONMENT')) {
  // Use Redis for caching.
  $conf['redis_client_interface'] = 'PhpRedis';
  $conf['cache_backends'][] = 'sites/all/modules/redis/redis.autoload.inc';
  $conf['cache_default_class'] = 'Redis_Cache';
  $conf['cache_prefix'] = array('default' => 'pantheon-redis');
  // Do not use Redis for cache_form (no performance difference).
  $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
  // Use Redis for Drupal locks (semaphore).
  $conf['lock_inc'] = 'sites/all/modules/redis/redis.lock.inc';
  $conf['path_inc'] = 'sites/all/modules/redis/redis.path.inc';
}
```


@newtoid or @timani can you review this issue and comment?

**Comment by RobLoach** [comment]
https://www.drupal.org/node/2556643

**Comment by nataliejeremy** [comment]
@newtoid or @timani can you comment on this?

**Comment by newtoid** [comment]
I can test - @rachelwhitton what php are you running?

**Comment by rachelwhitton** [comment]
@newtoid since it was back in August, I'm not sure - can you try 5.3 w/ the patch? 3.10 was originally reported working, but 3.11 has been released since.

**Comment by nataliejeremy** [comment]
The doc has been updated in PR #1378
