### ISSUE TITLE
Access management for Site Owners, PMs, et al.

### ISSUE THREAD

**Issue by sukottokun** [pantheon-systems/documentation#841]
From Hal@Door3's post, room for expansion, check with Conrad, support billing for common issues.:

I have an idea / request for a Documentation page, "How to remove an un-trusted resource from my pantheon site"
At the moment I am the "un-trusted" resource, and it's just a formality because my wife left her job at a company, and on good terms.
So while I can provide advice on how to remove me and audit that I've done nothing to the site DB or code they should technically not be getting that advice from me, or really from anyone I recommend.
On the other hand if there were a manual page that said, here is how you dot your I's and cross your T's that I could point to that would probably be good enough.
It's really great that they are doing this, I've found that I still have admin access to some sites I haven't touched in years.
I'd like to think it's because they think, "well we can't pay him for support, but if our site ever gets hosed we can call him for help"  but really it's probably just "I didn't even think of it, and don't know how to remove him anyway."

I'll also mention that their first thought was that they should move the site to a different host, which is silly since I'm fairly sure just checking that delete X in the team popup would be just as secure and 100,000 X less work.
That and the simplicity of checking last commit in the git log on the dashboard (last login in drupal) is basically the level of effort that I believe is required for this company.

It may be that a thorough scrub is not possible for some sites, I mean a developer does have a copy of the database which means they should really change every users's password.  And if I really didn't trust someone I would run Hacked and then review all my past commits.   It's a lot of work, and as likely as not that's still forgetting something crucial.
So to at lay out the options, issues, and level of effort would be good for everyone to see and consider.

And to point out the benefits of the platform as a service, such as not having to mess with OS or Database users and passwords, and virtually no way code could be slipped in and not be in the git history.

**Comment by rachelwhitton** [comment]
Awesome suggestion. +1 for a new doc on the topic - if best practices include modifications to the DB, it may be a good candidate for a guide? Otherwise a simple doc may be the way to go.
