### ISSUE TITLE
Site: Adopt a Docs MD linter to analyze new PRs for spelling, language, and style consistency (DOCO-4)

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#8413]
Re: docs.pantheon.io

moves: [DOCO-4](https://getpantheon.atlassian.net/browse/DOCO-4)

Priority: Low

### Context

* Part of the greater effort to ensure consistency across all Pantheon assets to align how we talk about products and features. This would also give us a tool to help contributors choose more appropriate language consistent with our Style and Inclusion guides.

## Suggested Resolution

* Implement and customize [Vale](https://github.com/errata-ai/vale-action) or a similar GitHub Action linter
  * Use:
    * [Confluence: Vocabulary Rules](https://getpantheon.atlassian.net/wiki/spaces/VULCAN/pages/2469003265/Vocabulary+Rules)
    * https://developers.google.com/style/word-list

[DOCO-4]: https://getpantheon.atlassian.net/browse/DOCO-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rachelwhitton** [comment]
opting to close
