### ISSUE TITLE
New Doc Proposal: Migrating WordPress sites from WPEngine

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#847]
## Description
Explain the deviations from the normal process required to migrate sites from WPEngine to Pantheon

## Outline
Credit http://brianjackson.io/migrating-website-away-wp-engine/

1. Use bv-pantheon plugin?
1. Create restore point
2. Download archive
3. Unpack
5. FTP download of `wp-content/uploads`
5. Be aware of filesize limitations
4. Add `wp-content/uploads` 
5. rm -rf the files listed in Brian Jackson's article
6. Compress archive(s)
7. Import
8. Verify success and resume `sites/migrate`

## Expected Audience
WPEngine users

## Path
`source/docs/articles/sites/migrate/from-wpengine`)

**Comment by atjuch** [comment]
@bmackinney I am currently working with the developer and owner of BlogVault.net who created a WPEngine migration plugin for their site. He also created one for Pantheon that is functional that migrates everything automatically.

https://wordpress.org/plugins/bv-pantheon-migration/

Right now we are testing migrations from hosts that include WPEngine, Pagely, SiteGround, Pressable, and more. The Pantheon Migration plugin will automatically exclude a specific range of files when being imported to Pantheon, avoiding the end user to have to worry about deleting other MU plugins and caching files/directories.

I will be creating a video tutorial on how to do this along with continuing to help develop the plugin to improve the filtering configuration for files from other webhosts. Let me know if you would like to talk and schedule time this week to go over this.

**Comment by bmackinney** [comment]
@atjuch I added it as a potential first option. A few concerns I have regarding it: 

 - Does the plugin have documentation?
 - It could be very short-lived on wpengine, given their stance on backup plugins and ability to block specific plugins. Their migration plugin is understandably blocked on their platform. 
 - We have a similar plugin in development, if only at the early stages. 
 - We don't do video production at the moment, and don't currently embed them on our docs. a series of static images will be more effective and less costly to produce and update.
