### ISSUE TITLE
Featured Contributor Panel Missing

### ISSUE THREAD

**Issue by wordsmither** [pantheon-systems/documentation#8475]
Re: [WooCommerce Quick Start](https://docs.pantheon.io/guides/woocommerce/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

https://docs.pantheon.io/lockr  and https://docs.pantheon.io/guides/woocommerce/ both have frontmatter of `featuredcontributor: true`. However, the panel is not appearing on these pages.

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Not resolved, but opt'ing to close
