### ISSUE TITLE
Pantheon Front-End Sites Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8498]
Re: [Pantheon Front-End Sites](https://docs.pantheon.io/guides/decoupled/overview)

Priority: Low

## Issue Description:
Long URL breaks page layout on mobile
<img width="460" alt="image" src="https://github.com/pantheon-systems/documentation/assets/91161717/35d8b7d2-1a60-409f-9b03-a9fc42aaa21d">

## Suggested Resolution
Replace link with page name instead of full URL

**Comment by stevector** [comment]
It looks like this task was completed
