### ISSUE TITLE
Autopilot Course 404 

### ISSUE THREAD

**Issue by kevinblanco** [pantheon-systems/documentation#8508]
The Autopilot course in the Learning Platform is showing a "not found" result. https://learning.pantheon.io/autopilot-quick-start This page is referenced in many places, for example, the community hub. 

## Expected behavior
Link works fine or a redirection is in place for the new course page

## Actual behavior
Page is showing a 404 not found

### Steps to reproduce the problem

1. Go here https://learning.pantheon.io/autopilot-quick-start 

## Suggested Resolution
* URL should show the autopilot page or at least redirect to a new page

**Comment by JQTNguyen** [comment]
This has been corrected on the Pantheon Learning side.

@kevinblanco: Thank you so much for catching this!
