### ISSUE TITLE
Resetting Passwords Doc Update 

### ISSUE THREAD

**Issue by mahmudulhossain** [pantheon-systems/documentation#8536]
Re: [Resetting Passwords](https://docs.pantheon.io/resetting-passwords#option-b-use-terminus-drush-to-set-a-password)

Priority: Medium

## Suggested Resolution

Instead of the existing command below,

terminus drush <site>.<env> -- user-password user_name --password='Astr0nGP455w0rD'

it should be now 

terminus drush <site>.<env> -- user-password user_name 'Astr0nGP455w0rD'

This means, now, "--password" tag is not necessary or does not work. If I keep "--password=" in the command, then the password takes as "--password='Astr0nGP455w0rD'" which is wrong.
![mahmudulhossain@mahmudulhossain:~ 2023-06-15 10-02-07](https://github.com/pantheon-systems/documentation/assets/82840646/e3a26f66-afcc-4e22-a4a9-a7dc70efe298)

**Comment by kyletaylored** [comment]
It looks like it depends on the version of Drush.

[Drush 8](https://drushcommands.com/drush-8x/user/user-password/)  uses the `--password` flag, but [Drush 9](https://drushcommands.com/drush-9x/user/user:password/)  and up use positional arguments.
