### ISSUE TITLE
Terminus Guide Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8544]
Re: [Terminus Guide](https://docs.pantheon.io/terminus/updates)

Priority: Medium

## Issue Description:
Terminus change log is missing all information

## Suggested Resolution
Should include content from https://github.com/pantheon-systems/terminus/blob/3.x/CHANGELOG.md

**Comment by wordsmither** [comment]
Already tracked in https://github.com/pantheon-systems/documentation/issues/8278
