### ISSUE TITLE
New Doc: Optimize WP Cache

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#858]
- [ ] Create WP equivalent of [Drupal Performance and Varnish Caching Settings](https://pantheon.io/docs/articles/drupal/drupal-7-performance-and-caching-settings/)

As far as I know, WP sites on Pantheon are already optimized on the platform via Varnish and the Pantheon Cache plugin.

The only way to alter caching in WP is to send specific HTTP header requests or to use the Pantheon Cache settings in wp-admin to set default TTL higher than 600s. Doc should link out to testing varnish article and new doc suggested in #414 

## Related Doc Update
Document limitations of Pantheon Cache plugin TTL value in [Pantheon Plugins](https://pantheon.io/docs/articles/wordpress/pantheon-plugins/#pantheon-cache) 
The [Pantheon Cache](https://github.com/pantheon-systems/WordPress/blob/master/wp-content/mu-plugins/pantheon/pantheon-cache.php#L85) plugin does not _currently_ allow the default TTL to be lower than 600. It can be increased.

**Comment by ari-gold** [comment]
See ticket #43996
