### ISSUE TITLE
Creating and Revoking Machine Tokens Doc Update 

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/documentation#8609]
Re: [Creating and Revoking Machine Tokens](https://docs.pantheon.iomachine-tokens)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

from @sharlenerozario8 

Broken link: [Go to your Personal Settings](https://docs.pantheon.io/guides/personal-settings) -> gives 404
Additionally the link for [Machine Tokens](https://dashboard.pantheon.io/users/#account/tokens/) redirect to the legacy dashboard, but if the customer is on new dash the link just redirects them to their homepage.

## Suggested Resolution

**Comment by stevector** [comment]
Fixed in https://github.com/pantheon-systems/documentation/pull/9099
