### ISSUE TITLE
Caching: Advanced Topics Doc Update 

### ISSUE THREAD

**Issue by philoSurfer** [pantheon-systems/documentation#8612]
Re: [Caching: Advanced Topics](https://docs.pantheon.iocaching-advanced-topics)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Under *Manually Expiring Cache for Static Assets*, the note about 

> Dev and Multidev environments do not cache static assets.

 needs to be more prominent as this is an important environment detail tends to trip up many people when working on performance related issues..

 
## Suggested Resolution
At minimum bold the sentence: **_Dev and Multidev environments do not cache static assets_**.   or call it out separately in a notice component that identifies this configuration.

**Comment by stevector** [comment]
Fixed in https://github.com/pantheon-systems/documentation/pull/9105
