### ISSUE TITLE
New Relic Performance Monitoring on Pantheon Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#8616]
Re: [New Relic Performance Monitoring on Pantheon](https://docs.pantheon.io/guides/new-relic)

Priority: Medium

## Issue Description:

Going forward in order for new relic to register hook-level information, Pantheon sites will need to install the new relic drupal contrib module. Previous to this latest version of New Relic's module that was not necessary. It now is.  https://www.drupal.org/project/new_relic_rpm 

## Suggested Resolution
Capture in troubleshooting section, consider inclusion in the activation/setup section as well

**Comment by scottbuscemi** [comment]
This is no longer needed. 

https://docs.pantheon.io/guides/new-relic/monitor-new-relic#enable-drupal-hooks--modules-metrics
