### ISSUE TITLE
Test Patches for IMCE module

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#864]
Re: [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins/)

Surfaced in https://github.com/pantheon-systems/documentation/pull/852#discussion-diff-38116432

 - https://gist.github.com/tauno/4236123
 - https://www.drupal.org/node/974568

Test patches and update doc to recommend a better solution than "split up your directories to avoid timeouts".

**Comment by rachelwhitton** [comment]
The most up to date patch has a "Needs Work" status. Both patches use apc, which is not recommended on Pantheon because it ["lacks the ability to span multiple server environments"](https://pantheon.io/docs/articles/sites/what-is-apc-and-what-is-it-used-for/). 

Updated agenda as discussed with @zepner: 
- [ ] Replicate timeout issue on [d7 sandbox](http://dev-test864.pantheon.io/user/1/imce)
- [ ] Test apc patch as a solution for personal sites
- [ ] Create and test a redis patch using redis for sites with multiple app servers

**Comment by bmackinney** [comment]
>- [ ] Create and test a redis patch using redis for sites with multiple app servers

Our standard procedure is not to create patches for extensions with encoded assumptions not to work with highly-available sites. Create an issue in the module or follow existing issues.

**Comment by rachelwhitton** [comment]
@bmackinney updated

**Comment by alexdicianu** [comment]
We have a patch that we recommend to clients. Directory scanning in valhalla is slow (when they have lots and lots of files) and the ajax HTTP request sometimes timesout - that's why people are seeing 502 errors. This patch puts files in the cache (Redis or db) which should make reading them faster.

https://getpantheon.atlassian.net/wiki/display/VULCAN/Working+with+IMCE+on+Pantheon

PS: It might take a couple of runs before all files arrive in the cache.

**Comment by paulsheldrake** [comment]
This came up in a google search for IMCE performance.  There is a patch for D7 that gets it working with large folders now.
 https://www.drupal.org/project/imce/issues/3158288#comment-13741873

**Comment by alexfornuto** [comment]
@paulsheldrake what coincidental timing! This section was removed from out docs last year, but there's [a PR](https://github.com/pantheon-systems/documentation/pull/5858) to reintroduce it. Let's move the conversation about documenting this patch over there.
