### ISSUE TITLE
Solr 8 ports now match solr 3

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8649]
Re: [Apache Solr for Drupal](https://docs.pantheon.io/guides/solr-drupal/solr-drupal)

Priority: Low

## Issue Description:

Port 443 is no longer a reliable indicator of Solr version

## Suggested Resolution

Remove steps

**Comment by stevector** [comment]
Yeah, I think we can remove everything within the **Verify pantheon.yml is Configured Correctly** section. Also, remove references to "limited availability"

**Comment by stevector** [comment]
Removing the "quick fix" label because I think there's a lot on this page that can be cut. I think this page was written when Solr 8 was new to the platform and contains more explanation than it needs.
