### ISSUE TITLE
Upgrading PHP doc doesn't specify supported versions of PHP

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8658]
Re: [PHP on Pantheon](https://docs.pantheon.io/guides/php/php-versions)

Priority: Low

## Issue Description:

Would be nice to link to https://docs.pantheon.io/guides/php#supported-php-versions

## Suggested Resolution

**Comment by stevector** [comment]
Thanks @jms-pantheon! Done in https://github.com/pantheon-systems/documentation/pull/9100
