### ISSUE TITLE
Terminus Guide Doc Update 

### ISSUE THREAD

**Issue by aarontocenter** [pantheon-systems/documentation#8673]
Re: [Terminus Guide](https://docs.pantheon.io/terminus)

Priority: High (choose one, remove the other options)

## Issue Description:
There is no Video tutorials as indicated in your documentation via a VIDEO icon. 
## Suggested Resolution
Restore the Video tutorials on how to use your systems correctly.

**Comment by stevector** [comment]
I don't see a video icon on https://docs.pantheon.io/terminus. Can you reopen if I'm missing something?
