### ISSUE TITLE
GoDaddy Domain Configuration Doc makes incorrect statements for subdomains

### ISSUE THREAD

**Issue by dalin-** [pantheon-systems/documentation#8679]
Re: [GoDaddy Domain Configuration](https://docs.pantheon.io/godaddy)

Priority: Medium

## Issue Description:

I've never used Go Daddy for DNS, but I'm directing a client to this page.  This doc page seems to imply that only an `A` record is needed for `www` (or other subdomains) and not also `AAAA` records.  That seems wrong to me. 

## Suggested Resolution

Remove section "A Record for subdomain".  Add an H2 section for "Subdomains" saying something like "Use the same instructions to set up subdomains (such as `www`)."   while being consistent with the pages for other DNS providers.

**Comment by rachelwhitton** [comment]
Thanks for the feedback here, very helpful @dalin- !
