### ISSUE TITLE
Pantheon Filesystem Doc Update update file count

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#8680]
Re: [Pantheon Filesystem](https://docs.pantheon.io/guides/filesystem/large-files)

Priority: Medium

## Issue Description:
file count should be updated to a lower one as we see more and more issues where files around 25k are having issues with Valhalla instead of 100k

## Suggested Resolution

Instead of 

Highly populated directories can cause a small decline in performance at around 50,000 files in a single directory, and a significant performance drop at over 100,000 files. Once above 100,000 files, backups may fail, and the filesystem itself may be corrupted leading to data loss and site dwontime.

to

Highly populated directories can cause a small decline in performance at around 10,000 files in a single directory, and a significant performance drop at over 25,000 files. Once above 25,000 files, backups may fail, and the filesystem itself may be corrupted leading to data loss and site downtime.

**Comment by rachelwhitton** [comment]
Closed by #8760
