### ISSUE TITLE
Backups Tool Doc Update 

### ISSUE THREAD

**Issue by webidextrousdev** [pantheon-systems/documentation#8700]
Re: [Backups Tool](https://docs.pantheon.io/guides/backups/access-backups)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
The links for 
[AWS S3 Setup for WordPress](https://docs.pantheon.io/guides/wordpress-configurations/wordpress-s3)
[AWS S3 Setup for Drupal](https://docs.pantheon.io/drupal-s3)
are incorrect.
## Suggested Resolution
The correct links are
https://docs.pantheon.io/guides/wordpress-developer/wordpress-s3
https://docs.pantheon.io/drupal-s3

**Comment by rachelwhitton** [comment]
Thanks for reporting this issue! I will fix right now
