### ISSUE TITLE
The Site Dashboard Doc Update 

### ISSUE THREAD

**Issue by webidextrousdev** [pantheon-systems/documentation#8702]
Re: [The Site Dashboard](https://docs.pantheon.iosite-dashboard)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Missing screenshot

## Suggested Resolution
Add the missing screenshot

**Comment by stevector** [comment]
Looks like this was actually fixed in https://github.com/pantheon-systems/documentation/pull/8762
