### ISSUE TITLE
Drupal Drush Command-Line Utility on Pantheon Doc Update 

### ISSUE THREAD

**Issue by dalin-** [pantheon-systems/documentation#8708]
Re: [Drupal Drush Command-Line Utility on Pantheon](https://docs.pantheon.io/guides/drush/drush-versions)

Priority: Medium

## Issue Description:
This page talks about how Drush 11 is supported, but that I can't specify 11 in `pantheon.yml`.  So then what version am I supposed to specify in `pantheon.yml`?

## Suggested Resolution
If you set `pantheon.yml` to Drush version 10, it will use the Drush that you've included via Composer.

**Comment by rachelwhitton** [comment]
Hey @dalin- thank you so much for opening this issue! 

We have a related PR in progress here: https://github.com/pantheon-systems/documentation/pull/8619#issuecomment-1655838870 where we are discussing the right action to take in the docs for managing Drush versions going forward. For Drush 11, require it via composer and the platform Drush (whatever it's configured to) will be ignore in favor of your site-local drush requirement instead 

If you'd like to weigh in on the discussion in the related PR please feel free, we would welcome your insights and experience! Thanks again for contributing to the docs repository here, much appreciated!
