### ISSUE TITLE
Terminus Guide Doc Update 

### ISSUE THREAD

**Issue by dylanbaumann** [pantheon-systems/documentation#8712]
Re: [Terminus Guide](https://docs.pantheon.io/terminus/install)

Priority: Low

## Issue Description:
- Under the section for "[Recommended Packages](https://docs.pantheon.io/terminus/install#recommended-packages)" our link to Drush links to a 404 page
    - current link: https://docs.drush.org/en/master/install/ 
<img width="1381" alt="Screenshot 2023-09-29 at 10 18 55 AM" src="https://github.com/pantheon-systems/documentation/assets/2158549/069cc4df-8bb0-4287-9f46-9c559cc87cc9">

## Suggested Resolution
- Alter link to point at current Drush install page: https://docs.drush.org/en/8.x/install/
<img width="1223" alt="Screenshot 2023-09-29 at 10 19 40 AM" src="https://github.com/pantheon-systems/documentation/assets/2158549/c58bfa09-15ea-4964-a79f-5300034800a8">

**Comment by rachelwhitton** [comment]
Solved by #8762
