### ISSUE TITLE
Pantheon WebOps Workflow Doc Update 

### ISSUE THREAD

**Issue by dylanbaumann** [pantheon-systems/documentation#8726]
Re: [Pantheon WebOps Workflow](https://docs.pantheon.iopantheon-workflow)

Priority: Low

## Issue Description:
Within our "Why does Pantheon do this?" dropdown, we link out to an old blog post on "Cowboy Coding", but that article doesn't seem to exist any more (and I cannot find the original article after Googling around). 
<img width="1024" alt="Screenshot 2023-10-05 at 2 03 35 PM" src="https://github.com/pantheon-systems/documentation/assets/2158549/e0348512-39e1-44fb-b573-32035371bf39">

## Suggested Resolution
Remove the link (and just leave it in quotes), or link to the correct location of the article if we can find it

**Comment by stevector** [comment]
@joshkoenig looks like this blog post hasn't migrated from old Drupal to new Drupal. Should it? I'd prefer we keep such posts.

**Comment by joshkoenig** [comment]
Quite possibly! I think of "Cowboy Coding" as one of those things we help people mature beyond. Maybe a re-write is in order, as it apparently wasn't doing numbers before. :P

**Comment by dylanbaumann** [comment]
On a light-hearted note, I referenced the phrase "Cowboy Coding" on monday when speaking with Christine and DK and they both got a kick out of it (they hadn't heard of it before), so a rewrite of the article to keep a classic phrase alive and well does sound nice (if for no other reason than for the fun of it).

**Comment by stevector** [comment]
@jazzsequence we can fix this issue together as an excuse to walk through the publishing workflow in Drupal. We'll bring back this old blog post from D7 in D10.

**Comment by jazzsequence** [comment]
@stevector where does this blog post exist currently?

**Comment by stevector** [comment]
It was on the old D7 site. I've manually migrated it: https://pantheon.io/blog/cowboy-coding-nostalgia
