### ISSUE TITLE
WordPress Plugins and Themes with Known Issues Doc Update 

### ISSUE THREAD

**Issue by alialtwany123** [pantheon-systems/documentation#8742]
Re: [WordPress Plugins and Themes with Known Issues](https://docs.pantheon.ioplugins-known-issues)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by stevector** [comment]
I'm not sure what issue you are reporting. Please reopen if there is a specific problem we can address.
