### ISSUE TITLE
Workspace Offboarding Doc Update 

### ISSUE THREAD

**Issue by dalin-** [pantheon-systems/documentation#8773]
Re: [Workspace Offboarding](https://docs.pantheon.ioworkspace-offboarding)

Priority: High

## Issue Description:

> Everything: removes a member from all workspaces and associated sites.

This is very ambiguous.  Will this also remove their Drupal/WP users accounts?  If so, what happens to their content?

## Suggested Resolution

The CMS account stuff gets tricky.  Prolly best to avoid getting involved there. But just be clear with the messaging.

**Comment by stevector** [comment]
Thanks @dalin-! Change in progress here: https://github.com/pantheon-systems/documentation/pull/9108
