### ISSUE TITLE
Adding Redis versions supported

### ISSUE THREAD

**Issue by anthonymendozagarces** [pantheon-systems/documentation#8782]
Re: [Object Cache Overview](https://docs.pantheon.io/object-cache)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Customers do not know the Redis Version we do have.

## Suggested Resolution
It's a great idea to also add in our docs about the version we do use and to what version we do support.

**Comment by stevector** [comment]
It's in https://docs.pantheon.io/object-cache/faq but we can add it to this page too.
