### ISSUE TITLE
Drupal Drush Command-Line Utility on Pantheon Doc Update 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#8793]
Re: [Drupal Drush Command-Line Utility on Pantheon](https://docs.pantheon.io/guides/drush/drush-versions)

Priority: Medium

## Issue Description:

Pantheon documentation does not report Drush 12 as supported.

## Suggested Resolution

Add Drush 12 as an option everywhere that Drush 11 is listed. In particular, note that the statement "Drush 11 is not available through pantheon.yml" also applies to Drush 12.

**Comment by thejimbirch** [comment]
This is proving quite frustrating to developers who have to update to Drupal 10.2 which requires Drush ^12.4.3.  It looks as though you can't upgrade to the latest version of Drupal because Pantheon does not support Drush 12.

**Comment by thejimbirch** [comment]
Still running into this as Drush 13 is about to be released around Drupal 11.

**Comment by stevector** [comment]
@greg-1-anderson can you review https://github.com/pantheon-systems/documentation/pull/9010

**Comment by rachelwhitton** [comment]
Closed by #9010
