### ISSUE TITLE
Pantheon YAML Configuration Files Doc Update 

### ISSUE THREAD

**Issue by Qrmworld** [pantheon-systems/documentation#8795]
Re: [Pantheon YAML Configuration Files](https://docs.pantheon.iopantheon-yml)

Priority: High 

## Suggested Resolution: Kindly restore site backend for Qrmmall

**Comment by stevector** [comment]
This issue appears to be with your specific site, yes? Not a problem with the yml documentation? If I'm wrong, please re-open.
