### ISSUE TITLE
Audit use of popovers, remove unnecessary code

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#8814]
Many, but not all of our `/src/templates` files contain the same code in `ComponentDidMount`.

https://github.com/pantheon-systems/documentation/blob/71aa57d2bd672fe9f7427fe162cca6c3a9a1275e/src/templates/resource.js#L57

I suspect it is not used in many (or any?) places. We should either remove it entirely or DRY it out to reduce the likelihood of breakage.

**Comment by rachelwhitton** [comment]
Still weird but opting to close as we are likely to switch frameworks
