### ISSUE TITLE
Create a Static Site Using an Empty Upstream Doc Update 

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/documentation#8830]
Re: [Create a Static Site Using an Empty Upstream](https://docs.pantheon.io/static-site-empty-upstream-demo)

Priority: Low

## Issue Description:
It looks like this page: https://docs.pantheon.io/static-site-empty-upstream-demo
Is already replaced by this one: https://docs.pantheon.io/static-site-empty-upstream

## Suggested Resolution
301 `static-site-empty-upstream-demo` to `static-site-empty-upstream`

**Comment by stevector** [comment]
@rachelwhitton we should also reconcile this guidance with Front-End Sites.
