### ISSUE TITLE
Inaccurate documentation: Terminus does does not support php version 8.3+ but Pantheons documentation states it does.

### ISSUE THREAD

**Issue by zane-kanopi** [pantheon-systems/documentation#8831]
https://docs.pantheon.io/terminus/install

## Expected behavior
* Terminus works: `terminus --version` displays the version.

## Actual behavior
```
$ terminus --version

PHP 8.3+ is not supported by this version of Terminus.
Check for new versions at https://github.com/pantheon-systems/terminus/releases

Set environment variable TERMINUS_ALLOW_UNSUPPORTED_NEWER_PHP to try continuing anyway.
Stopping.
```

### Steps to reproduce the problem

1. Run the above commands.

## Suggested Resolution
* Update documentation to note 8.3 is not supported.

Current docs state:
> PHP Version 7.4 or later
reference: https://docs.pantheon.io/terminus/install#required-packages

<img width="1552" alt="Screenshot 2024-01-18 at 11 52 58 AM" src="https://github.com/pantheon-systems/documentation/assets/142340302/dcdcbff4-98c4-46c7-b43d-51a22f856aaf">

**Comment by stevector** [comment]
It looks like this issue was fixed here: https://github.com/pantheon-systems/terminus/pull/2517/files

On my local machine I'm seeing:

```
terminus --version

Terminus 3.3.5
```

and

```
 php -v
PHP 8.3.4 (cli) (built: Mar 12 2024 23:42:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.4, Copyright (c), by Zend Technologies
```

Please re-open if there's still a problem
