### ISSUE TITLE
Drupal Modules with Known Issues Doc Update 

### ISSUE THREAD

**Issue by pete-cleary** [pantheon-systems/documentation#8835]
Re: [Drupal Modules with Known Issues](https://docs.pantheon.iomodules-known-issues)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
The module Simple OAuth/OAuth 2.0 now has no more known issues. It works with Pantheon without a workaround. 

## Suggested Resolution
Remove this module from the list of modules with known issues. Line 379.

**Comment by stevector** [comment]
This is getting worked out in https://github.com/pantheon-systems/documentation/pull/8836
