### ISSUE TITLE
Integrated Composer Doc Update 

### ISSUE THREAD

**Issue by PMU-ops** [pantheon-systems/documentation#8861]
Re: [Integrated Composer](https://docs.pantheon.io/guides/integrated-composer/ic-upstreams#add-dependencies-to-your-upstream)

Priority: Medium

## Issue Description:
Specify what files should be committed to avoid confusion to the customers from the https://docs.pantheon.io/guides/integrated-composer/ic-upstreams#upstream-and-site-structure

## Suggested Resolution
On the Number 4: Commit the changes without the composer.lock file and push your changes.

**Comment by stevector** [comment]
Thanks @PMU-ops! https://github.com/pantheon-systems/documentation/pull/9107
