### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update 

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/documentation#8864]
Re: [Serving Sites from the Web Subdirectory](https://docs.pantheon.ionested-docroot)

Priority: Medium

## Issue Description:

On the "Disable One-Click Updates" section of this page, there are two tabs. "Drupal" and "WordPress".

The solution under "Drupal" only works for Drupal 6/7 sites (sites using the "drupal" Framework.

For sites using the "drupal8" Framework (Drupal 8/9/10 and future), they need to use this command:

`terminus site:upstream:set <site> empty`

## Suggested Resolution

Either remove the current "Drupal" answer or maybe created two different Drupal tabs with each answer.

**Comment by stevector** [comment]
Thanks @dficker! https://github.com/pantheon-systems/documentation/pull/9106
