### ISSUE TITLE
B & M Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#887]
Re: [Backup Creation](https://pantheon.io/docs/articles/sites/backups/backup-creation/#why-is-the-drupal-module-backup-&-migrate-not-recommended-on-pantheon?) and [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins/#backup-&-migrate)
## Issue Description:
Test B & M
## Suggested Resolution 
Update content accordingly - includes anchors for promised content

**Comment by rachelwhitton** [comment]
I've tested BM on a few D7 sites and can confirm that archives successfully import using the Dashboard Import tool (both URL and File). **Import is only successful if the `sites/default/files` directory exists within the archive**. If `sites/default/files` does not exist, the import tool will provide the following error: 
```
Errors during site creation:
Skipping file import, unable to locate the files directory.
```
@ronan is submitting an issue to address the error. 


@bmackinney should any current information on Backup and Migrate be preserved in the docs? Here's my todo, I need help with the 2nd: 

- [ ] Delete BM from [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins/#backup-&-migrate) 
- [ ] Determine what information within [Backup Creation](https://pantheon.io/docs/articles/sites/backups/backup-creation/#why-is-the-drupal-module-backup-&-migrate-not-recommended-on-pantheon?) is still applicable/valuable.

**Comment by bmackinney** [comment]
@rachelwhitton BM is still unsupported and problematic and all info is applicable. This update should be restricted to it's inclusion as an option for creating a single-file archive of a site hosted elsewhere or running locally, and being able to import those archives to the platform through the importer.
