### ISSUE TITLE
External Libraries on Pantheon Doc Tika Path is wrong 

### ISSUE THREAD

**Issue by square360-douglas** [pantheon-systems/documentation#8883]
Re: [External Libraries on Pantheon](https://docs.pantheon.ioexternal-libraries)

Priority: Medium

## Issue Description:

Documentation for using tika incorrect/outdated. 
Legacy path is in docs, but this does not appear to work (today D10).
`/srv/bin/tika-app-1.11.jar`

## Suggested Resolution
Update docs to include latest/working version: `/srv/bin/tika-app-1.18.jar`

**Comment by stevector** [comment]
Thanks! I've opened https://github.com/pantheon-systems/documentation/pull/9104
