### ISSUE TITLE
Add script to get connection info via Terminus

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#890]
Re: [Accessing MySQL Databases](https://pantheon.io/docs/articles/local/accessing-mysql-databases)
## Issue Description:
Add script on how to get Sequel Pro database connection info
## Suggested Resolution 
Add script that:
grabs the latest connection string via terminus,
writes a temp file for the connection ("spf" format, same as when you "save" a connection), 
and opens the temp file (in sequel pro, so long as your system binds sequel pro to .spf extension)

Tested this only on OSX 10.10

https://gist.github.com/aaronbauman/f50cc691eb3ed60a358c

**Comment by rachelwhitton** [comment]
@nataliejeremy is there an advantage to using the linked script over the following drush command? 
```
$ terminus sites aliases
$ drush @pantheon.{sitename}.{env} sql-connect
```

**Comment by nataliejeremy** [comment]
@rachelwhitton This was requested by @ari-gold  because of an email sent to the power users group.

**Comment by ari-gold** [comment]
The script is specifically for Sequel Pro.
