### ISSUE TITLE
Migrate a Composer Managed Drupal Site from Another Platform Doc Update 

### ISSUE THREAD

**Issue by v0jpantheon** [pantheon-systems/documentation#8913]
Re: [Migrate a Composer Managed Drupal Site from Another Platform](https://docs.pantheon.io/guides/drupal-unhosted-composer/contrib-custom)

Priority: Low

## Issue Description:

In the `##Install Libraries with drupal-library` section, there's a minor typo:
Use must use Composer to install your libraries.

## Suggested Resolution
You must use Composer to install your libraries.

**Comment by stevector** [comment]
Thanks! I fixed it https://github.com/pantheon-systems/documentation/pull/9103
