### ISSUE TITLE
Add RSS feed to Release Notes page

### ISSUE THREAD

**Issue by markmont** [pantheon-systems/documentation#8977]
Re: [Pantheon release notes](https://docs.pantheon.io/release-notes)

Priority: Medium

## Issue Description

Customers do not find out about additions to the release notes unless they remember to periodically visit the page.

### How will this impact users?

Customers will be better informed about recent changes.  This should reduce support costs for Pantheon by avoiding chats/tickets/calls for things already addressed in the release notes.

### Context

The University of Michigan is making this request under our Diamond Support contract (["Platform" scope, "Find appropriate documentation"](https://docs.pantheon.io/guides/support/#scope-explanations)).  Steve Persch (Pantheon Director of DevRel)
 instructed us to open an issue here rather than submitting a ticket or going through our account team.

## Suggested Resolution

Add an RSS feed to https://docs.pantheon.io/release-notes per the instructions at [Adding an RSS Feed](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-an-rss-feed/) in the Gatsby documentation.

**Comment by scottbuscemi** [comment]
Thanks Mark - 100% in favor of helping folks discover the Release Notes contents.

What are your thoughts around an email subscription? Perhaps with options to get every release note emailed, or a weekly digest?

**Comment by IngridKwok** [comment]
Mark - I'm fully on board with adding an RSS feed to the release notes page. This will help push updates to users and increase awareness. Email subscription, as Scott mentioned, is another great option. Who will take the lead on implementing this, and what's the timeline/efforts for getting it done?

Regarding monthly/weekly digest - is there a way to automate the creation process?

**Comment by markmont** [comment]
An email subscription would be fine, although I prefer the RSS feed since I'm a web person :)

With an email subscription, it would be important to get people to the right place so that they can sign up and also manage all their subscriptions.  As an example, I know that release notes were sent out by email in January of this year but I only knew about it because our senior procurement specialist forwarded the email message to me.  She has never wanted the release notes, but kept getting them and can't unsubscribe at https://learn.pantheon.io/email-preference-center.html  But even if I use the link in the footer of emails I _do_ get from getpantheon.com addresses that takes me with my user token to https://learn.pantheon.io/email-preference-center.html , I can't sign up for the "Changelog Newsletter" -- every time I check the box and click "Update settings", the next time I go back to the email preference center, the box is unchecked again.

I'll also add that I put in this issue only exactly what I was asking for without any embellishment.  But since both of you (Scott, Ingrid) have responded...  I'd hope that once you add an RSS feed for the release notes page, you might add one for other key pages (although I don't know which those would be), or even for the site as a whole, too, so people can get notified when new pages are published, or existing pages are revised even if it doesn't reach the level to be included in the release notes.  I'm not sure how many people would like a site-wide feed for any/all documentation changes, though -- I am likely to be in the minority here :D

**Comment by gravelpot** [comment]
+1 for this request from the University of Texas at Austin.

I would normally prefer email for something like this, but I am constantly bamboozled by Pantheon's automated email settings. Some newsletters (like the "Changelog") will appear for a while and then disappear. An RSS feed would give me a better feeling of control, plus I feel like that release notes page has more independence from the marketing machine. I like the more "just the facts" tone to it.

Also, I could plug an RSS feed into one of my team's Microsoft Teams channels, which would put it in front of the rest of my team even if they choose not to subscribe to the emails. That's also how we handle the Status Page feed.

**Comment by IngridKwok** [comment]
Your insights into the challenges of email subscriptions resonate, especially regarding the difficulties in managing preferences effectively. That's also one of the reasons why we paused sending out the email newsletter after January while looking into ways to improve the experience. 

Your suggestion to extend RSS feeds beyond release notes to other key pages or the entire site for broader notifications is valuable. We'll evaluate the feasibility of implementing these enhancements to release notes first. Currently finding the right person to talk to regarding evaluation and implementation.

**Comment by markmont** [comment]
Hi, Pantheon staff!  Is there any update on this?  We're hoping to get this change under our Diamond Support contract rather than having to do the work ourselves and submit a PR.

**Comment by markmont** [comment]
Thanks, Ingrid!  I appreciate it.

**Comment by rachelwhitton** [comment]
Closed by #9034 

Thanks everyone for your participation on this thread!
