### ISSUE TITLE
New Doc Proposal - HTTPS for Sites Using Customized Base Domains

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#898]
This new doc has been requested internally. @joshkoenig can you review the outline?
ping @bmackinney @nataliejeremy 

## Title
HTTPS for Sites Using Customized Base Domains

## Description
Learn how to enable HTTPS for site environments using your Organization's customized base domain. 

### Intro
Feature is available to Pantheon Partners, Strategic Partners, Enterprise accounts, Resellers, and OEM Partners service levels. 
Restate customized base domain purpose and value. Link to [Customizing Your Base Domain](https://pantheon.io/docs/articles/organizations/base-domains/#request-the-base-domain).
### Before You Begin
- Must have a customized base domain
 - If you do not have a customized base domain, [request one](https://pantheon.io/docs/articles/organizations/base-domains/#request-the-base-domain) before proceeding
- Requires Wildcard cert from a recommended SSL provider

### Single Domain Configuration
In single domain config scenarios, sites associated with the organization (e.g. projectsite-env.pantheonpartner.com) and the main site (e.g. www.pantheonpartner.com) will be served using the same wildcard certificate. 
Requires DNS change for pantheonpartner.com - set up all DNS to go to the IP for the TLS/SSL endpoint in the live env, like so:
```
*.pantheonpartner.com A [IP for TLS/SSL endoint in live env]
```
Sites associated with the org will be accessible via a similar URL to the following: `https://www.projectsite-env.pantheonpartner.com`
### Multiple Domain Configuration
Alternatively, you could load up one cert for the live environment, and use the test environment for another cert (e.g. "*.partnerprojects.com") that is on a more clear "dev" domain, configuring the different DNS records accordingly. 
## Expected Audience
Partners 
## Path
 `/docs/articles/organizations/https-for-sites-using-customized-base-domains`

**Comment by joshkoenig** [comment]
+1 for this. 

We should note that running your agency homepage on Pantheon is free, so you can request that and set it up and use that for the HTTPS endpoint without having to pay for anything.
