### ISSUE TITLE
WinSCP SFTP on Pantheon Doc Update 

### ISSUE THREAD

**Issue by tmiddlecote** [pantheon-systems/documentation#8986]
Re: [SFTP on Pantheon](https://docs.pantheon.io/guides/sftp/winscp)

High 

## This documentation should be updated to reflect the new approach to connecting via WinSCP.

**Comment by rachelwhitton** [comment]
I submitted a pull request to update this doc page, will merge it later today and you can expect this to be updated in production shortly after merging
