### ISSUE TITLE
WordPress on Pantheon Quick Start Guide Doc Update 

### ISSUE THREAD

**Issue by sayisanthosh** [pantheon-systems/documentation#9024]
Re: [WordPress on Pantheon Quick Start Guide](https://docs.pantheon.io/guides/wordpress-pantheon/wordpress-launch-check)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description: Undefined array key "postId" in /code/wp-includes/blocks/comments.php on line 27

plugins/wp-optimize/vendor/monolog/monolog/src/Monolog/Handler/PHPConsoleHandler.php	3659	$_SESSION
plugins/wp-optimize/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php	9336	$_SESSION

## Suggested Resolution

**Comment by stevector** [comment]
@sayisanthosh our support chat is better equipped to help you with specific PHP errors.
