### ISSUE TITLE
Doc/Guide Request: Pantheon + Deploybot

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/documentation#905]
A lot of customers make use of DeployBot (aka deploy.io, aka beanstalk). I think it should be pretty easy to integrate with Pantheon, and if so we'd definitely benefit from having a doc page/guide on how to set this up.

**Comment by nataliejeremy** [comment]
ToDo:
- [ ] Overview of deploybot/Benefits of using
- [ ] Link to create a new account
- [ ] Steps to link GH repo 
- [ ] deployment process

@ `CSE` Can you added anything else that should be included in this doc?

**Comment by nataliejeremy** [comment]
@bmackinney `@cse` Can you add anything else to the task list?

**Comment by bmackinney** [comment]
No. Carry on with an outline.

Brian MacKinney
Developer Training Manager | Pantheon
p 415-800-1957
brian@pantheon.io
www.linkedin.com/in/bmackinney

**Comment by ataylorme** [comment]
@nataliejeremy One nice feature of deploybot is the ability to run a build process, like Grunt to compile CSS, before deploying.

They have [an article on how to set this up](http://deploybot.com/guides/building-assets-with-grunt-or-gulp-during-deployment) that is probably worth linking to.

**Comment by nataliejeremy** [comment]
Great, thanks! @ataylorme

**Comment by cse** [comment]
You tagged the wrong person. Please don't do that. :)

**Comment by bmackinney** [comment]
Sorry about that @cse. We were doing that for slack integration. @nataliejeremy @rachelwhitton please use @pantheon-systems/documentation to ping the team.

**Comment by newtoid** [comment]
Not sure if this will work as desired - happy to take advice on it though, I set this up and deploybot requires a deployment path to be configured in their UI, obviously this can change, how should I approach that?

**Comment by ataylorme** [comment]
@nataliejeremy 
Heads up we might not want to publish this doc yet. I was testing DeployBot and there are issues with our Git repo URLs. See their response below:

> Sorry about all the back and forth. Turns out, we’d already looked into that issue before. The URL format doesn’t have anything to do with it. The problem is, the Java SSH library that we rely on for cloning repos via SSH doesn’t play well with the longer encryption key lengths required by Pantheon. We’re planning to upgrade to a newer JDK soon, which should solve this. It will probably happen within the next month or so. Alternatively, you could weaken up the key length requirements on your end to make them closer to what GitHub and BitBucket support, though I understand that it might be hard to justify such change.

This was on 6/9, I can follow up with DeployBot at the beginning of July to see if they have updated their SDK.

**Comment by rachelwhitton** [comment]
@ataylorme thanks for the update, much appreciated!

@newtoid I used `~/code` for the deployment path and it was successful (SFTP deploy). Thoughts?

**Comment by newtoid** [comment]
@rachelwhitton I tried that too and the path was not accepted by the form - happy to continue working on this if we set some expectations about what it can do. Ideally I would like to get it working with Git.

**Comment by alexfornuto** [comment]
Closed by #1323.
