### ISSUE TITLE
Update and automate the running of Prettier

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#9082]
Undo https://github.com/pantheon-systems/documentation/pull/9047/commits/4ba642056d75b77fa5afac890c789638e97e69ab based on convo in Slack

**Comment by jazzsequence** [comment]
Link to Slack convo for context?

**Comment by stevector** [comment]
https://pantheon.slack.com/archives/C1PAPP30W/p1719329592090319?thread_ts=1719327342.183359&cid=C1PAPP30W

We should probably chat through how best to do this. As far as I can tell, our docs code base has functioned for years without an enforced standard. I think it'd be unnecessarily disruptive to add it broadly now. But it might be worthwhile to add enforcement of a standard to new files and directories, and progressively add it to other directories as they are modified.

**Comment by jazzsequence** [comment]
Do you want to

a. _Detect and flag_ linting issues in new/changed files on PRs, or
b. _Change and commit_ linting fixes per Prettier standards in new/changed files on PRs?

There's some prior art I can look at for either use case, but as I was personally resistant to `b` for a long time, I want to get a pulse for what you were thinking here.

For reference:
- https://github.com/pantheon-systems/wordpress-composer-managed/blob/e5e245f12295c10ecf81719101f3423e1ba559b1/.github/workflows/phpcbf.yml
- https://github.com/pantheon-systems/pantheon-content-publisher-for-wordpress/blob/primary/.github/workflows/php-style-lint.yml#L32-L35

**Comment by stevector** [comment]
ooooh, both of those options are more sophisticated than what I had in mind (a manually maintained listing of files to check)

I think my preference is for `a` because it seems better suited to educating/guiding people who aren't 100% fluent in the code they're working in. Option `b` seems better suited to speeding up an already optimized team.
