### ISSUE TITLE
Automate running of vitest

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#9083]
I'm adding vitest in https://github.com/pantheon-systems/documentation/pull/9047

It should run on PRs

**Comment by jazzsequence** [comment]
@stevector I see [playwright tests](https://github.com/pantheon-systems/documentation/pull/9047/files#diff-1f770dffed8da73a43393041838c4912b1ec826572e4d8b15c988fb96b17ab0f) and I see that `vitest` is [installed](https://github.com/pantheon-systems/documentation/pull/9047/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R72) -- Does vitest wrap around Playwright? What needs to be added to CI exactly?

**Comment by stevector** [comment]
You can ignore Playwright for now. We're treating Playwright as an E2E suite. Right now we're only using it for visual regression and false positive failures are so common that @rachelwhitton and I agreed to not pursue connect it to CI at this time.

vitest I added separately for unit testing so that I'd be more comfortable writing helper functions  that do data manipulation to feed into the sidebar menu.

Can you make a new branch off of https://github.com/pantheon-systems/documentation/commit/1a8a51f61771525f612359f12c7bb68e7ef66e5b and add a GitHub action that runs `npx vitest src/components` ? (I'm suggesting branching off of that commit specifically because I see that in the subsequent commit I added a change that breaks the unit test but not the actual functionality of the React component 🙃 )

**Comment by stevector** [comment]
Looks like I started failing the unit test with this change https://github.com/pantheon-systems/documentation/commit/e237ecd3b139e7826fc01e4278781285beb50d70

vitest doesn't like this direct usage I JSX that I added here

```
    linkText = (
      <>
        <Icon iconName="externalLink" /> {item.title}
      </>
    );
    ```

That instead needs to use `React.createElement`

**Comment by stevector** [comment]
That's why I want CI 😆

**Comment by jazzsequence** [comment]
I've got a successful run of the workflow here: https://github.com/pantheon-systems/documentation/actions/runs/10307574827/job/28533128469?pr=9161

I will create a new PR off of #9047 so we can just merge that into that branch with just the new GH action and not create divergent histories.
