### ISSUE TITLE
Redis as a Caching Backend D8 Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#911]
Re: [Redis as a Caching Backend](https://pantheon.io/docs/articles/sites/redis-as-a-caching-backend)
## Issue Description:
Needs to be updated w/ info for D8. 

## Suggested Resolution 
Clarify 6 and 7 are supported; 8 is not. Link to the Redis module page and issue queue.

**Comment by rachelwhitton** [comment]
Complete in #999
