### ISSUE TITLE
Incorrect value for DNS TTL examples

### ISSUE THREAD

**Issue by gravelpot** [pantheon-systems/documentation#9116]
## Issue description

At: https://github.com/pantheon-systems/documentation/blob/7d496ef6285f1e335e8fc6c06d1443bc4f1073f1/source/content/partials/dns-propagation.md?plain=1#L11

the shortest TTL example shown says: `500 (5 minutes)`

This is presumably meant to say `300 (5 minutes)` (60 seconds * 5 minutes = 300 seconds), or perhaps `600 (10 minutes)`. A TTL of 500 seconds would be 8.3 minutes, which would be unusual.

The same value is repeated a few lines lower:

```
Lower the TTL values as low as allowed (usually 500) several days in advance at your DNS service manager.
```

## Suggested Resolution

* Update to a correct value in both places, as appropriate.

**Comment by stevector** [comment]
Thanks @gravelpot! I opened https://github.com/pantheon-systems/documentation/pull/9287
