### ISSUE TITLE
Bug: RSS subscribers are not updated when multiple release notes are published in a single day 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#9126]
Publishing more than one release note in a given day does not update RSS subscribers, we suspect that is because the entries have the same value for pubDate (e.g., `<pubDate>Wed, 24 Jul 2024 00:00:00 GMT</pubDate>`)

**Comment by stevector** [comment]
We should look at how other SSG docs sites/frameworks handle this issue.

**Comment by rachelwhitton** [comment]
Today we had 5 release notes to publish, which is out of the norm, but we spent a lot of time trying to workaround this issue and we were not successful. Is this something you can maybe prioritize for review @mel-miller? 

While we don't normally see this volume day to day, it's not uncommon to see more than one in a day. 

cc @jazzsequence

**Comment by rachelwhitton** [comment]
Related config: https://github.com/pantheon-systems/documentation/blob/main/gatsby-config.js#L251-L307

Related js component: https://github.com/pantheon-systems/documentation/blob/main/src/components/PublishedDate/index.js

**Comment by mel-miller** [comment]
@rachelwhitton -- Refresh my memory, didn't we talk about this maybe having something to do with how the dates are handled at the site level? Or is it specific to release notes?

**Comment by rachelwhitton** [comment]
I think we talked about a different issue, where the site flashes the correct date initially then updates to one day earlier than whatever is set by frontmatter, I'm not sure though. 

This issue here stems from entries published with the same `00:00:00 GMT` timestamp in the rss.xml file, so RSS readers never pick them up. We think we have a solution ready for your review in the related PR, can you take a look?
