### ISSUE TITLE
Apache Solr on Pantheon D8 Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#914]
Re: [Apache Solr on Pantheon](https://pantheon.io/docs/articles/sites/apache-solr)
## Issue Description:
Add note that D8 module is in development (include link) and instructions to check the project page for updates
## Suggested Resolution 
Add Drupal 8 version (not yet available)

**Comment by bmackinney** [comment]
There is a further issue, that D7 requires a Pantheon Apachesolr module. That needs to be considered here. So far, it's not in drops-8, and I've asked in the wiki whether it will be there or in contrib.

**Comment by rachelwhitton** [comment]
Complete in #999
