### ISSUE TITLE
Drupal.md Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#915]
Re: [Drupal](https://pantheon.io/docs/articles/drupal)
## Suggested Resolution 

- [ ] Update intro to include D8 upstream info
- [ ] Under Apache Solr, add link to Drupal 8 module

**Comment by rachelwhitton** [comment]
Completed in https://github.com/pantheon-systems/documentation/commit/d0dab816b192e4ce38650f95da4edfdc4fb0156d within #999
