### ISSUE TITLE
What is the "pantheon_api.module" D8 Doc Update

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#917]
Re: [What is the "pantheon_api.module"](https://pantheon.io/docs/articles/sites/code/what-is-the-pantheon_api-module)
## Issue Description:
There is not a Drupal 8 version of the module. 
## Suggested Resolution 
Note the above

**Comment by greg-1-anderson** [comment]
At the moment, we do not have a pantheon_api.module for Drupal 8.  On Drupal 7, the only thing that pantheon_api does at the moment is replace a certain recursive file delete operation in the image cache module with a Pantheon bulk-delete operation.

We need to investigate whether this, or anything else, is necessary for Drupal 8.

**Comment by bmackinney** [comment]
@greg-1-anderson can you update and if unnecessary, close?

**Comment by greg-1-anderson** [comment]
At some point that we may have a pantheon_api module for Drupal 8, but at the moment we do not.
