### ISSUE TITLE
Configuring Settings.php D8 Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#918]
Re: [Configuring Settings.php](https://pantheon.io/docs/articles/drupal/configuring-settings-php)
## Suggested Resolution 
- [x] Update intro content to specify Pressflow Drupal is for D7, and add info on D8. 
- [x] Add code snippets for Drupal 8 under “Local Database Configuration for Development”
- [x] Add link to D8 default.settings.php under the FAQ "Where can I get a copy of a default.settings.php?"

**Comment by bmackinney** [comment]
@timani @greg please review this issue, and edit the description if inaccurate, and +1 before @timani starts

**Comment by bmackinney** [comment]
@timani it looks like you've done most of this already here: https://github.com/pantheon-systems/pantheon-settings-examples/tree/master/drupal-8

**Comment by timani** [comment]
Oh right, I remember starting this but it does need an update to be complete

**Comment by ttrowell** [comment]
Also, as a 'hash_salt' setting is needed, should we include a method for users to add that to their settings.php for their local environment?   We set it per environment with the following code:

`/**
 * Handle Hash Salt Value from Drupal
 *
 * Issue: https://github.com/pantheon-systems/drops-8/issues/10
 *
 */
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  $settings['hash_salt'] = $_ENV['DRUPAL_HASH_SALT'];
}`

**Comment by rachelwhitton** [comment]
#1097 was created as a duplicate - adding related description here. @timani are you planning a PR for this issue? 

Re: [Configuring Settings.php](https://pantheon.io/docs/articles/drupal/configuring-settings-php)
## Issue Description:
Drupal 8 includes a bundled settings.php file, unlike previous versions.
## Suggested Resolution 
Update doc throughout as needed to align with Drupal 8, while preserving suggestions/best practices already mentioned that apply to D6/D7. 

[See note from Greg](https://github.com/pantheon-systems/documentation/pull/1058/files#r44310575): 
>Do we want to say anything about the fact that Drupal 8 sites do come with a bundled settings.php? Also, the bundled settings.php and default.settings.php both include the necessary settings.pantheon.inc. If someone used a stock default.settings.php, their Drupal 8 site would stop working. Maybe we should have another document that describes settings.php for Drupal 8 (did not check to see if that already exists), and just cross-link to it here?

**Comment by greg-1-anderson** [comment]
Yes, folks should make their own HASH_SALT value in their settings.local.php file.  See:

https://github.com/pantheon-systems/drush-config-workflow/blob/master/bin/quickstart

If for some reason someone wants to use the Pantheon HASH_SALT in their local site (not necessary), then can get it via:

`drush @pantheon.sitename.dev ev 'return getenv("DRUPAL_HASH_SALT")' `

c.f. https://github.com/pantheon-systems/drops-8/issues/103
