### ISSUE TITLE
Environment Log Files on Pantheon Doc Update 

### ISSUE THREAD

**Issue by Tajdar001** [pantheon-systems/documentation#9189]
Re: [Environment Log Files on Pantheon](https://docs.pantheon.io/guides/logs-pantheon/nginx-access-logs)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

**Comment by rachelwhitton** [comment]
@Tajdar001 Looks like we didn't get any details here in the issue description. Closing this for now but if there is an issue please let us know
