### ISSUE TITLE
Using Lockr to Secure and Manage API and Encryption Keys Doc Update 

### ISSUE THREAD

**Issue by john-sutkowski-mindpath** [pantheon-systems/documentation#9190]
Re: [Using Lockr to Secure and Manage API and Encryption Keys](https://docs.pantheon.iolockr)

Priority: Medium

## Issue Description:
Noting that our company was looking at LockR as a secure way to store our API keys but decided against it as their Wordpress plugin has not been supported/updated from the last 3 major releases.
https://wordpress.com/plugins/lockr

## Suggested Resolution
Better solutions for storing API keys securely in Wordpress.

**Comment by rachelwhitton** [comment]
@john-sutkowski-mindpath thank you for submitting this issue! We will review this doc page in detail and make updates. 

[Today we announced Limited Availability for the new Pantheon Secrets feature](https://docs.pantheon.io/release-notes/2024/08/pantheon-secrets-limited-availability), along with a [new guide](https://docs.pantheon.io/guides/secrets). The WordPress example can be found here on the [PHP Usage](https://docs.pantheon.io/guides/secrets/php) page. Let us know if this does not meet your requirements

**Comment by john-sutkowski-mindpath** [comment]
Hi Rachel,

Thank you for sending this over. Going to test implentation for our keys and will reach out if we have any issues. Thank you again for reaching out.
________________________________
