### ISSUE TITLE
Terminus Guide Doc Update - updates page

### ISSUE THREAD

**Issue by jhuebsch** [pantheon-systems/documentation#9198]
Re: [Terminus Guide](https://docs.pantheon.io/terminus/updates)

Priority: Low

## Issue Description:
This page is out of date. The information on it is about a 6 month old release. This misleads users into what the current version of Terminus is.
## Suggested Resolution
Instead of linking to this page, it should link directly to the github releases page https://github.com/pantheon-systems/terminus/releases

**Comment by rachelwhitton** [comment]
Hi @jhuebsch thank you for opening! This is back on our radar and we've picked discussion back up on issue #8954 I will close this one out but again we'll keep working to solve in the existing issue
