### ISSUE TITLE
New Doc Proposal: Adding a services.yml file

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#920]
# Adding a `services.yml` file
From: pantheon-systems/drops-8#26

## Description
The directory permissions on the sites/default are being set by Drupal to 555 when the site is in SFTP mode. Success reported from committing the file locally and pushing, or changing the permissions via SFTP client.

## Outline
1. Explain the symptom
2. Create file locally, commit and push 
3. Change permissions with SFTP client or from the command line (if possible)

## Expected Audience
Drupal 8 users

## Path
/docs/articles/drupal

**Comment by rachelwhitton** [comment]
Completed work within #999
