### ISSUE TITLE
Enable Object Cache Pro for WordPress Doc Update 

### ISSUE THREAD

**Issue by RayHollister** [pantheon-systems/documentation#9206]
Re: [Enable Object Cache Pro for WordPress](https://docs.pantheon.io/object-cache/wordpress)

Priority: Medium (choose one, remove the other options)

## Issue Description:
Instructions are woefully out of date. None of them work. 

## Suggested Resolution
Go through the whole page and rewrite it. The most heinous part is "config/application.php". That file does not exist.

**Comment by rachelwhitton** [comment]
Hi @RayHollister thanks for opening this issue. I just want to make sure, are you able to successfully set up Object Cache Pro following the [non-composer steps here](https://docs.pantheon.io/object-cache/wordpress#installation-and-configuration-for-non-composer-wordpress-sites)?  `config/application.php` is only applicable to composer managed WordPress sites

**Comment by RayHollister** [comment]
No, when I followed the Non-Composer section instructions, it did not set up correctly. I was only able to get it working using a combination of some of the steps in the Non-Composer section and adaptations of the steps in the Composer-Managed section. Unfortunately I did not document what it took to get it working. I kind of had to poke around and try things until it worked correctly. Also unfortunately, I am still unable to get it working correctly on Lando. In order to develop locally I have to delete the object-cache.php drop-in file and restore it before I push my changes.

**Comment by jazzsequence** [comment]
@RayHollister Can you share what failed when you tried to use the Terminus command? Was there an error that was visible in the Workflow Log? Did you previously or do you currently have other object cache plugins installed (like WP Redis)?

cc @scottbuscemi @pwtyler

**Comment by jazzsequence** [comment]
## Todo:

* [ ] Write a "manual" installation workflow
* [ ] Suggest Pantheon Secrets as a method for storing and fetching the API key

**Comment by RayHollister** [comment]
OK, I just went through the process again, and here's my experience. 

I went through all of the instructions on [Enable Object Cache Pro for WordPress](https://docs.pantheon.io/object-cache/wordpress#with-terminus) through line 6c of [Installation and Configuration for non-Composer WordPress Sites](https://docs.pantheon.io/object-cache/wordpress#installation-and-configuration-for-non-composer-wordpress-sites)

It worked fine on the multidev server, but when I pulled it to my local Lando server, it will only gives me the error: "Error establishing a Redis connection" on the browser. If I shut down the Lando server down and restart it, I just get `[500] [ECONNREFUSED]` unless I delete the /plugins/object-cache-pro/ folder.

**Comment by pwtyler** [comment]
I've never successfully enabled Redis in Lando, can you try adding to your wp-config.php? This should prevent it from trying to initialize while running locally.

``` php
if ( isset( $_ENV['LANDO'] ) && 'ON' === $_ENV['LANDO'] ) {
  define('WP_REDIS_DISABLED', true);
}
```
https://objectcache.pro/docs/configuration

**Comment by RayHollister** [comment]
> I've never successfully enabled Redis in Lando, can you try adding to your wp-config.php? This should prevent it from trying to initialize while running locally.
> 
> ```
> if ( isset( $_ENV['LANDO'] ) && 'ON' === $_ENV['LANDO'] ) {
>   define('WP_REDIS_DISABLED', true);
> }
> ```
> 
> https://objectcache.pro/docs/configuration

I was literally in the middle of doing that when I got the notification from GitHub. 🤣 I'll let you know if it works.

**Comment by RayHollister** [comment]
@pwtyler OMG FINALLY! I can work on my Lando servers again!

I guess I don't really need Redis on my Lando servers. 🤷🏻‍♂️ 

But since [Lando includes Redis](https://docs.lando.dev/plugins/redis/) support I just assumed I was doing something wrong. 

I'm gonna test it on another Lando, and if it works, I'll submit it as a recommended edit and close out this issue.

**Comment by RayHollister** [comment]
Done and Done. Tested it on three broken and sad Landos on my computer. Submitted [Pull Request #9309](https://github.com/pantheon-systems/documentation/pull/9309)

**Comment by pwtyler** [comment]
Ah, I just re-read your error! Using a similar pattern, try setting serializer to `php` instead, if you can't get igbinary support setup in Lando.

```
$serializer = "igbinary";
if ( isset( $_ENV['LANDO'] ) && 'ON' === $_ENV['LANDO'] ) {
  $serializer = "php";
}

....
// Within WP_REDIS_CONFIG...
  'serializer' => $serializer,

**Comment by pwtyler** [comment]
Different error at least, similar, may be able to adjust the compression setting to something that is supported by Lando's version of PHP
> https://objectcache.pro/docs/configuration-options#compression
