### ISSUE TITLE
Create Drupal 8 Configuration Management article

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#921]
- [x] Build the doc from Greg's blog post: https://pantheon.io/blog/configuration-workflow-drupal-8-sites
- [x] Link to post, link post to doc with notice that current information will be found here

Path: /docs/articles/drupal/

**Comment by greg-1-anderson** [comment]
Might want to discuss managing configuration stores somewhere; c.f. pantheon-systems/drops-8#82. Not sure if this should be something that we encourage or discourage, though.

**Comment by rachelwhitton** [comment]
To preserve info from [Running Drupal 8 on Pantheon](https://pantheon.io/docs/articles/drupal/running-drupal-8/#using-drupal-8-configuration-management-on-pantheon) we should evaluate the following and include within this doc if needed:

> Pantheon supports the [Drupal 8 Configuration Management system](https://www.drupal.org/documentation/administer/config) and defaults configuration into the `sites/default/config` directory for each Pantheon Drupal 8 site. You can export your configuration into that directory directly using Drush's config-export command or indirectly using Drupal's UI to download the configuration and then use SFTP/Git to place the configuration in `sites/default/config`. For more information on how this all works, check out Matt Cheney and David Strauss' presentation on [Drupal 8 CMI on Managed Workflow at Drupalcon Amsterdam](https://amsterdam2014.drupal.org/session/drupal-8-cmi-managed-workflow).

**Running Drupal 8 on Pantheon** will be deleted in the D8 docs release.

**Comment by greg-1-anderson** [comment]
I am going to move the location of the 'staging' configuration store to sites/default/config/staging with the release of Drupal 8.0.0-beta16.
c.f. pantheon-systems/drops-8#76
