### ISSUE TITLE
Edge Integrations Doc Update 

### ISSUE THREAD

**Issue by MikeNGarrett** [pantheon-systems/documentation#9213]
Re: [Edge Integrations](https://docs.pantheon.io/guides/edge-integrations/configuration-overview/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

All the information here appears out of date and links to read-only repositories. 

## Suggested Resolution

**Comment by rachelwhitton** [comment]
Thanks for raising this issue! Given the respective repos are public archives we are opt'ing to deprecate this guide (example of [deprecated doc page](https://docs.pantheon.io/object-cache/wordpress-deprecated) here). assigning to @jazzsequence for next steps
