### ISSUE TITLE
Get ready for WP Composer GA 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#9220]
Follow-up action items from copy review of #9205 

We shouldn't have a WP flavored composer guide, it needs to be better incorporated into existing and related docs instead. 

**Sometime between removing EA copy from docs and announcing GA, we should:** 

- [x] 1. Consolidate [Introduction](https://docs.pantheon.io/guides/wordpress-composer) page of the WordPress Composer guide into the Integrated Composer guide
   1. Also, the standalone doc [Composer Fundamentals](https://docs.pantheon.io/composer) should be repurposed as the new [Introduction](https://docs.pantheon.io/guides/integrated-composer) page for the Integrated Composer guide. There won’t be much to preserve from the WP intro page once this is done.
- [x] 2. Consolidate [Create a Composer-managed WordPress Site with Bedrock ](https://docs.pantheon.io/guides/wordpress-composer/wordpress-composer-managed)into the Integrated Composer guide on a new page focused on site creation which covers both Drupal and WP (the [Introduction](https://docs.pantheon.io/guides/integrated-composer) page of the Integrated Composer guide is doing that today, but it’s stale info for WP and an intro page is more appropriate for conceptual content as suggested in 1i above)
- [x] 3. Consolidate [Create a Composer-managed WordPress Site with Terminus Build Tools](https://docs.pantheon.io/guides/wordpress-composer/create-wp-site-composer-ci-auto-test) into the Build Tools guide either as a new page or a new section on the existing [Create a New Project](https://docs.pantheon.io/guides/build-tools/create-project/) page.
- [x] 4. Consolidate [Multisite Configuration](https://docs.pantheon.io/guides/wordpress-composer/multisite-configuration) into the [Configure](https://docs.pantheon.io/guides/multisite/config/) page of the Multisite guide
- [x] 5. Consolidate [Create a Composer-managed WordPress Site with Integrated Composer and Custom Upstreams ](https://docs.pantheon.io/guides/wordpress-composer/wordpress-ic)into the [Custom Upstream](https://docs.pantheon.io/guides/integrated-composer/ic-upstreams) page of the Integrated Composer guide

**Comment by jazzsequence** [comment]
@rachelwhitton for 2, a single doc seems like it would be pretty long, especially if I'm moving [this content](https://pr-9234-documentation.appa.pantheon.site/drupal#drupal-with-integrated-composer) out of the Drupal page and into the IC page and doing the equivalent for WPCM. I propose separate pages for each, especially since we link out to them from the introduction.

**Comment by rachelwhitton** [comment]
Sounds good, we discussed also removing `/drupal` to be redirected to `/supported-drupal` not much there worth preserving but the last line needs to be moved over
