### ISSUE TITLE
Create Upgrading Your Site to Drupal 8 article

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#923]
## Title: Upgrading Your Site to Drupal 8 

Possibly similar to: https://pantheon.io/docs/articles/drupal/major-version-drupal-upgrades/

## Path
/docs/articles/drupal/

**Comment by ari-gold** [comment]
@nataliejeremy Looks like you're tackling this with https://github.com/pantheon-systems/documentation/pull/931 ?

**Comment by bmackinney** [comment]
Yes. @ari. I don't think this warrants a new doc.

**Comment by ari** [comment]
What's this to do with me?
