### ISSUE TITLE
Using Terminus to Create and Update Drupal Sites on Pantheon D8 Doc Update

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#924]
Re: [Using Terminus to Create and Update Drupal Sites on Pantheon](https://pantheon.io/docs/guides/terminus-drupal-site-management)
## Issue Description:
[Create a Brand New Site](https://pantheon.io/docs/guides/terminus-drupal-site-management/#create-a-brand-new-site) screenshot will require an update.
## Suggested Resolution 
Update screenshot once official D8 product is created. Test `terminus drush site-install` on a D8 site

**Comment by bmackinney** [comment]
blocked until release or a functioning Onebox with D8 active as a regular product is available.
