### ISSUE TITLE
Create Console on Pantheon article

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#925]
## Description

The Drupal Console is a suite of tools that you run on a command line interface (CLI)
to generate boilerplate code and interact with a Drupal 8 installation.
Build from https://pantheon.io/introduction-drush-and-drupal-console 
## Outline
1. Explain Console and how it works on Pantheon
2. Installation
3. Commands and their usage
## Expected Audience

D8 users
## Reference

 https://www.drupal.org/project/console
## Path

(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by bmackinney** [comment]
Remote execution is not a thing yet. Consider removing this new article from MVP release, keep it on the back burner for when it's possible.

**Comment by timani** [comment]
Adding a link to the issue on drush reference

https://github.com/drush-ops/drush/pull/1337/

**Comment by jmolivas** [comment]
@bmackinney @nataliejeremy 
Remote command execution is now and available feature on DrupalConsole. 

Slides from my BADCamp session: 
http://jmolivas.com/slides/badcamp2015/faster-and-smarter-development-with-drupal-console/#/60 

I can help with this article, writing and/or providing information related to DrupalConsole.

**Comment by nataliejeremy** [comment]
@jmolivas That would be great--we'd really appreciate your help creating this doc. Let us know how we can help.

**Comment by alexfornuto** [comment]
@jmolivas are you still interested in contributing to this guide? We have most of it staged at #2342, but could use some help creating some example usage.

**Comment by jmolivas** [comment]
@alexfornuto sure I am still interested.

**Comment by alexfornuto** [comment]
@jmolivas Awesome. The empty sections start [here](https://github.com/pantheon-systems/documentation/pull/2342/files#diff-faaf32c0688799c3da5c255eb5e2de87R57). Please take a look, and let me know how I can help.

**Comment by greg-1-anderson** [comment]
Rather than writing a whole DrupalConsole tutorial in the Pantheon docs, maybe a link out to helpful existing blogs and docs would be sufficient here?

Mind you, I'm not opposed to having a whole DrupalConsole tutorial in docs -- I'm only talking about effort level here.

**Comment by rachelwhitton** [comment]
Closing, to be tracked internally at DSI-74

@jmolivas we'll circle back to this and ping you for a peer review once we have some more progress made on our composer docs
