### ISSUE TITLE
Clarifying vanilla WP / WPMS migration steps and language

### ISSUE THREAD

**Issue by codyfishman** [pantheon-systems/documentation#9252]
Re: [WordPress Multisite](https://docs.pantheon.io/guides/multisite/)

Priority: Medium

## Issue Description:
This [section](https://docs.pantheon.io/guides/multisite/#:~:text=Existing%20WordPress%20sites%20cannot%20be%20converted%20to%20a%20multisite%2C%20however%20they%20can%20be%20migrated.) about how vanilla WP / WPMS migrations happen on Pantheon is overly vague and has caused some confusion for customers with lesser WPMS experience. 

Specifically, the sentence starts out by talking about how existing vanilla WP sites "cannot be converted" to WPMS, which seems to imply the vanilla WP site is on Pantheon already since this limitation doesn't apply to most other hosting providers. The latter part of the sentence goes on to say that "they", seemingly referring to vanilla WP sites on Pantheon, "can be migrated." And there is a link to [documentation](https://docs.pantheon.io/migrate-wordpress-multisite) that explains how to migrate a non-Pantheon WPMS to Pantheon. 

This sentence lacks continuity in the topic it is covering, because the secondary portion is discussing non-Pantheon WPMS and how to migrate it to Pantheon. That is a different scenario than the beginning portion of the sentence that is implicitly referring to vanilla WP sites on Pantheon. 

## Suggested Resolution
Expand the highlighted content to be more inclusive of relevant scenarios and starting host environments. In my opinion, we should cover at least the following scenarios. 

- non-Pantheon vanilla WP -> Pantheon WPMS
- non-Pantheon WPMS -> Pantheon WPMS
- Pantheon vanilla WP -> Pantheon WPMS

**Comment by kali4nication** [comment]
Do you let me fix it?

**Comment by kali4nication** [comment]
As you wishEm 06/11/2024 16:59, Rachel ***@***.***> escreveu:
Assigning to @jazzsequence with updates around frameworks
