### ISSUE TITLE
Update screenshot with TTL for PAPC plugin

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/documentation#9263]
## Expected behavior
* Screenshot at https://docs.pantheon.io/guides/wordpress-configurations/wordpress-cache-plugin#use-pantheon-cache-functions-programmatically reflects the newer one-week TTL default PAPC 2.0 uses

## Actual behavior
* Screenshot currently displays 600 second (10 minute) TTL

## Suggested Resolution
* New screenshot of the updated PAPC dash view

-------------
Cloned from [wp.org support topic](https://wordpress.org/support/topic/allow-max-age-configuration-for-api/).

**Comment by jazzsequence** [comment]
Dupe of https://github.com/pantheon-systems/documentation/issues/9195

**Comment by pwtyler** [comment]
Duplicate of https://github.com/pantheon-systems/documentation/issues/9195
