### ISSUE TITLE
Create a New CMS Site Doc Update 

### ISSUE THREAD

**Issue by azizulhakim12** [pantheon-systems/documentation#9267]
Re: [Create a New CMS Site](https://docs.pantheon.io/add-site-dashboard)

Priority: Medium

## Issue Description:

![image](https://github.com/user-attachments/assets/c224851d-8468-48ec-935e-534a979db23e)

The screenshot above is outdated and not available anymore while creating new sites.

## Suggested Resolution

We can update the screenshot.

**Comment by rachelwhitton** [comment]
Can you provide a screenshot of what you're seeing?

**Comment by jpro2222** [comment]
There are multiple errors here, not just an outdated screenshot.

The documentation indicates that after choosing Drupal (Composer Managed), the next step will allow the option of choosing Drupal 11, 10, or 7. That step is totally absent. The installer goes directly to an unspecified Drupal installation. After the installation is complete, you have to go to the new site to learn that the version installed is 9.

Issues:

- Documentation explicitly indicates the next step will allow a choice of version
- No choice is presented
- No indication is made of which version actually is being installed
- No indication is made of how to achieve an installation of 10 (or 11), which is almost certainly the desired outcome

<img width="1107" alt="choose" src="https://github.com/user-attachments/assets/39bc09ec-ee8e-42c4-9cb7-b8ac44e66011">
<img width="1223" alt="deploy" src="https://github.com/user-attachments/assets/8e4d529d-5a81-403a-a496-fea93d54ae41">

**Comment by rachelwhitton** [comment]
@azizulhakim12 thanks for the details here, very helpul! 

@stephpawlowski can you take a look at this issue when convenient? I think it boils down to the docs covering the Phoebe site creation experience and ignoring the Hermes site creation experience - is there a timeline for when these experiences will be aligned?

**Comment by stephpawlowski** [comment]
@rachelwhitton you are correct. The docs covers the site creation experience that begins in Phoebe, but it does appear that the experience that originates in Hermes is still available. I am trying to pull some numbers on usage in the meantime. 

We are retiring customer-facing Hermes experiences in the first half of next year. That would include moving all of site creation into Phoebe

**Comment by jpro2222** [comment]
In the meantime, is there any way to install Drupal 10?
