### ISSUE TITLE
New Doc Proposal: Drush on Drupal 8

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#927]
## Outline
Similar to: https://pantheon.io/docs/articles/local/drupal-drush-command-line-utility/
Build from Greg's blog: https://pantheon.io/blog/introducing-drush-8
1. Issues with using Drush 7
2. Upgrading to Drush 8 (git users, composer users, pantheon users)
3. Troubleshooting
 
## Expected Audience
D8 and Drush users

## Path
/docs/articles/local/

**Comment by rachelwhitton** [comment]
Closed by #1058
