### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Naara-ai** [pantheon-systems/documentation#9277]
Re: [PHP on Pantheon](https://docs.pantheon.io/guides/php/php-errors)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution
buenos dias, quiero entrar en pantheon y me sale este error "Fatal error: Cannot redeclare get_cli_args() (previously declared in /code/wp-admin/includes/class-wp-importer.php:276) in /code/wp-admin/includes/class-wp-importer.php on line 276
Ha habido un error crítico en este sitio.

[Aprendé más sobre el diagnóstico de WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)"
Y por mail no recibo nada

**Comment by Naara-ai** [comment]
por favor necesitaria una solucion cuando antes de este problema

**Comment by rachelwhitton** [comment]
Hi @Naara-ai this seems to be a WordPress application issue and not specific to Pantheon's platform. The scope of this doc page is not meant to solve for an error like this but instead covers more general information about how application errors are handled by the platform based on the given environment. 

Closing this issue, but you are welcome to [reach out to our support team](https://docs.pantheon.io/guides/support/contact-support/) or [join our community slack](https://docs.pantheon.io/pantheon-community/) to continue discussion. 

Thank you for taking the time to read our docs and open this issue.
