### ISSUE TITLE
Importing a Large Site Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#928]
Re: [Importing a Large Site](https://pantheon.io/docs/articles/sites/migrate/importing-a-large-site)
## Issue Description:
The "Import the Codebase" only has drops-7 instructions. 

## Suggested Resolution 
Add Drupal 8 specific import instructions

**Comment by bmackinney** [comment]
This doc is being revised in #958, and this this issue is now moot.
