### ISSUE TITLE
Major Version Drupal Upgrades Doc Update 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#929]
Re: [Major Version Drupal Upgrades](https://pantheon.io/docs/articles/drupal/major-version-drupal-upgrades)
## Issue Description:
D8 puts migrate.module in core and no longer supports upgrading through update.php
## Suggested Resolution 
Add D8 upgrade instructions

See this article for reference: 
https://www.drupal.org/node/2350521

**Comment by rachelwhitton** [comment]
Completed in https://github.com/pantheon-systems/documentation/commit/f106882482b3d1a8b765c0647a75505eabd7898f within #999
