### ISSUE TITLE
Terminus command search field width is smaller on Chrome browsers

### ISSUE THREAD

**Issue by ccharlton** [pantheon-systems/documentation#9292]
Re: [Terminus Guide](https://docs.pantheon.io//terminus/commands)

Priority: Low

## Issue Description:
The commands search/filter textfield renders shorter on Chrome browsers (macOS), cutting off the help text and providing less space for the user to type.

Also, largely the command search field is not prominent enough like it could be; kinda hides in plain site.

### Screenshots
<img width="800" alt="terminus commands search field - Chrome" src="https://github.com/user-attachments/assets/8bfc2aa4-1ba7-4e8f-9a25-adc1e46647d8">

<img width="398" alt="terminus commands search field - Firefox" src="https://github.com/user-attachments/assets/cf52d88d-4f19-4694-9e80-a1c8ae540c22">

<img width="398" alt="terminus commands search field - Safari" src="https://github.com/user-attachments/assets/5c50117f-eb9c-4598-9c31-107a44a0b87c">

## Suggested Resolution
Either fix the width for Chrome or just force the field to render the field wider for all browsers. A bigger+wider search bar may just clobber nuance renderings or styles needed between browser types and provide an opportunity to make that important field stick out more.

**Comment by rachelwhitton** [comment]
@mel-miller is this something you can look into for us?
