### ISSUE TITLE
New Doc Proposal: Create services.yml file on D8

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#934]
See pantheon-systems/drops-8#26.

**Comment by bmackinney** [comment]
Duplicate of #920

**Comment by greg-1-anderson** [comment]
Sorry -- didn't see the other issue, and GitHub did not create a cross-link.  Hm.

**Comment by greg-1-anderson** [comment]
The cross-link was there -- user blindness error.
