### ISSUE TITLE
New Doc Proposal: Known Issues

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#939]
## Known Platform Issues
 - [x] Identify owner
 - [ ] Define criteria for publishing issues
 - [ ] Create labels 
 - [ ] Create procedure for labeling included issues and adding to the doc
 - [x] Create a content type

## Description
We have a known-limitations doc explaining issues users might run into that are a result of the platform architecture, that we will not fix. This page will list known issues or bugs we want to share with users, that we are planning on fixing. This document will require regular updating and maintenance. We will create a label on internal issue queues that will facilitate updating. 

## Outline
1. Explain the purpose of the doc
2. list of known issues

## Expected Audience
All users

## Path
/source/docs/issues

## Other Considerations
 - Links from dashboard and pantheonstatus.com should be on the table.

**Comment by sukottokun** [comment]
Will want to discuss who owns it and what are the criteria.

**Comment by bmackinney** [comment]
Task list added to issue description
