### ISSUE TITLE
Update DNS configuration documentation for Drupal 8

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#945]
Drupal 8 has a new security feature related to DNS configuration; we will need to update our documentation to explain how users can stay secure.  See pantheon-systems/drops-8#79.

(added by Brian)
@greg-1-anderson reports [this is a non issue](https://github.com/pantheon-systems/drops-8/issues/79#issuecomment-145693381). If we resolve it in a pantheon_api module, we will not need to document it. If not, we'll need to add a note that it is not possible on the platform. 

https://pantheon.io/drupal/drupal8

**Comment by greg-1-anderson** [comment]
This might become a no-op if we can handle the trusted domains feature in the platform.

**Comment by bmackinney** [comment]
Updated description in response to https://github.com/pantheon-systems/drops-8/issues/79#issuecomment-145693381. Still blocked pending decision on pantheon_api module.

**Comment by ttrowell** [comment]
Per my conversation on 2/11/16 with @greg-1-anderson I am working on a snippet that is generic enough for use either by users.  

Info on config here and linked to snippet:
https://pantheon.io/docs/articles/drupal/drupal8/

Snippet to live here:
https://pantheon.io/docs/articles/drupal/configuring-settings-php/
