### ISSUE TITLE
Review CLI documentation - Terminus 0.8.0 release

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#948]
Re: [Release 0.8.0 ](https://github.com/pantheon-systems/cli/releases/tag/0.8.0)
## Issue Description:
#947 fixes 1 instance of outdated terminus commands - we should check to see if any more exist. 
## Suggested Resolution 
Audit existing terminus documentation to ensure suggested commands are still valid.

**Comment by nataliejeremy** [comment]
- [ ] search the changelog for commands that have changed https://github.com/pantheon-systems/cli/blob/master/CHANGELOG.md
