### ISSUE TITLE
Unsupported/Problematic Modules and Plugins Doc Update 

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#952]
Re: [Unsupported/Problematic Modules and Plugins](https://pantheon.io/docs/articles/sites/code/unsupported-modules-plugins)
## Issue Description:
Using the /tmp directory links to anchors below do not work

**Comment by rachelwhitton** [comment]
Reopened because #962 did not resolve issue in production. Suggest removing the `/` from the header section so that anchor link is `#using-the-tmp-directory`

**Comment by rachelwhitton** [comment]
Closed via #968
