### ISSUE TITLE
Track drush-ops/drush#1595

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#953]
Improved management for site-local drush usage reported in [#933](https://github.com/pantheon-systems/documentation/pull/933#issuecomment-140837876):

> Just a little note, drush-ops/drush#1595 will make this way easier.  The user will just need to `require drush/drush '8.*'` in their Drupal site, if using Composer, or install Drush at __ROOT__/sites/all/drush/drush/drush (that is, the 'drush' script is inside the __DRUSH_ROOT__ with is inside the "drush" folder in sites/all/drush), and Drush will always use this site-local Drush for all operations.

> Prerequisites:  Above PR committed to Drush master and 7.x branches, and Pantheon updated to Drush 7.1.0.  We'd also want to make Drush 7 the default for new sites.  This is probably a month or two off, at least, and legacy sites are going to be stuck with the policy file, as described above, but I thought I'd mention it anyway.

Track status and plan updates.

**Comment by bmackinney** [comment]
@greg-1-anderson merged and closed. He merged it into master locally. The github issue will indicate closed, but it's in.

**Comment by greg-1-anderson** [comment]
c.f. drush-ops/drush#1644.

**Comment by rachelwhitton** [comment]
Work included within issue #632 pr #1058 - closing as it's now a duplicate issue.
