### ISSUE TITLE
Configuring Settings.php Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#964]
Re: [Configuring Settings.php](https://pantheon.io/docs/articles/drupal/configuring-settings-php)
## Issue Description:
No warning exists for modifying `settings.pantheon.php`
This doc seems like an appropriate place for the warning, but could be included elsewhere if another doc is more appropriate. 
## Suggested Resolution 
Create warning against modifying the `settings.pantheon.php` file for any reason. 

See https://github.com/pantheon-systems/documentation/issues/937#issuecomment-142679968:

> **IMPORTANT NOTE:** settings.pantheon.php is for Pantheon's use only. Any documentation that instructs the user to configure settings should tell them to modify settings.php. Modifying settings.pantheon.php is not allowed, as this file might change in a future release, which would cause conflicts on update.

**Comment by nataliejeremy** [comment]
@rachelwhitton Is this based on feedback from Support? I'm wondering how often users try to modify that file.

**Comment by rachelwhitton** [comment]
It's based on the linked issue comment, not sure how often users try to modify.

**Comment by nataliejeremy** [comment]
Maybe just an FAQ would do then, rather than a warning. I think it's important to save the warnings for important info they need to complete the task (configuring settings.php) and not for extraneous information.

**Comment by rachelwhitton** [comment]
+1 FAQ seems like a good spot for it. Agreed that we should be conservative with our warning usage.
