### ISSUE TITLE
Role-Based Permissions update

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#979]
Re: [Role-Based Permissions 

- [x] Enterprise  needs developer and team member roles.

**Comment by bmackinney** [comment]
@nataliejeremy I refined the scope - we need to account for Pantheon One orgs.

**Comment by nataliejeremy** [comment]
@bmackinney Pantheon One is gone. Enterprise is accounted for in the doc. Can you add specifics?

**Comment by bmackinney** [comment]
@nataliejeremy Pantheon One is not gone. All existing enterprise orgs converted to Pantheon One and now have that in their dashboard. Some have admins and their roles should be limited to admin/unprivileged.

**Comment by nataliejeremy** [comment]
So per our convo it's fine as it is, right? @bmackinney
