### ISSUE TITLE
New Doc Proposal: Identifying your site's upstream

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#985]
## Title

Identifying your site's upstream

## Outline

From Site Dashboard
1. Click Settings >> About Site
2. See link to upstream 

Include screenshot

TODO
- [x] update sites.md doc with instructions and screenshot

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by nataliejeremy** [comment]
@ari-gold Is this a question you get often? We have that documented here: https://pantheon.io/docs/articles/sites/#about-site

Think a whole new doc is required?
