### ISSUE TITLE
Git requires SSH Key Doc Updates

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#989]
Re: [Get Started](https://pantheon.io/docs/articles/getting-started/#interact-with-your-code)
## Issue Description:
The following is not accurate:
>Using Git requires that you add an SSH Key to your account.

## Suggested Resolution 
Test by deleting SSH Key and attempting to interact with remote site repo, then remove outdated content. 
Same applies to the following:
Re: [Generating SSH Keys](https://pantheon.io/docs/articles/users/generating-ssh-keys)
>If you have no keys remaining but still have active sites, you will still have access to them and can make edits via SFTP using your account password to authenticate. However, there will be no Git access as you need a valid key uploaded to your account.

**Comment by bmackinney** [comment]
@rachelwhitton you tested this right?

**Comment by rachelwhitton** [comment]
@bmackinney not yet. scope of the issue is to test, confirm, then update.
